### ISSUE TITLE
7.0.0-preview.2 PSReadLine stops working after Get-Help or other commands

### ISSUE THREAD

**Issue by eedwards-sk** [PowerShell/PSReadLine#1007]
# Overview

Certain (possibly just full-screen overlayed) commands or operations cause PSReadLine to stop working afterwards, and in some cases, for the console (process) to become completely unresponsive.

I have a reliable reproduction below, although it only reproduces one aspect of the problem I've surfaced (I don't have a reliable repro for the console becoming unresponsive).

# Steps to reproduce

```powershell
pwsh-preview -NoProfile
help Get-Alias
(press 'q' to quit)
(press Up-Arrow / Down-Arrow to cycle through history)
```

# Expected behavior

History is cycled

# Actual behavior

History is not cycled / input sometimes unresponsive

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
I can repro this easily.  Doing a `cls` to clear the screen seems to make it work again.

**Comment by SteveL-MSFT** [comment]
So what appears to be happening is that after you exit `less`, the up arrow is received as the VT100 escape sequence `{ESC}A` which PSReadLine doesn't treat as the up arrow (this is true for all for arrow keys, you can't go left for example).  Clearing the screen seems to reset the terminal so the arrow keys are received as just arrow keys.  Seems like this might be an issue in corefx.

**Comment by SteveL-MSFT** [comment]
This looks like a regression in .NET Core 3.0.  Using 6.2.1 w/ same PSReadLine doesn't repro.  I'll have to see about getting them a simpler repro.

**Comment by marcinsmialek** [comment]
I had similar issues after invoking any command with completion which triggered scrolling,

**Comment by daxian-dbw** [comment]
Just checked that the .NET Core fix is not included in .NET Core Preview 9.

**Comment by rkeithhill** [comment]
Well, that's a bummer.  :-(

**Comment by daxian-dbw** [comment]
The fix was included in .NET Core RC1 and available with 7.0.0-preview.4

**Comment by eedwards-sk** [comment]
@daxian-dbw this isn't fixed -- please re-open

it's still occurring on 7.0.0-preview.4

**Comment by daxian-dbw** [comment]
The issue doesn't reproduce on Linux anymore, but still reproduce on macOS.

**Comment by mklement0** [comment]
@daxian-dbw: Curiously, I don't see it on my macOS 10.14.6 system with preview 4.

**Comment by daxian-dbw** [comment]
Weird. I can repro it on macOS 10.14.6 system with preview 4 ...

**Comment by eedwards-sk** [comment]
Same -- I'm on OSX 10.14.6 and still reproing it.

**Comment by daxian-dbw** [comment]
OK, I just built PowerShell against .NET Core 3.0 RTM on my macOS and the issue is gone with the .NET Core 3.0 RTM.

**Comment by daxian-dbw** [comment]
I will leave this issue open until we release 7.0.0-preview.5, which will use .NET Core 3.0 RTM build.

**Comment by SteveL-MSFT** [comment]
Doesn't repro for me on macOS PS7 P5.
