### ISSUE TITLE
Visual Studio code started throwing error

### ISSUE THREAD

**Issue by Tamulavage** [PowerShell/PSReadLine#1014]
& {
    "PS version: $($PSVersionTable.PSVersion)"
    $v = (Get-Module PSReadline).Version
    $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSReadLine.psd1" | Select-String "Prerelease = '(.*)'"
    if ($m) {
        $v = "$v-" + $m.Matches[0].Groups[1].Value
    }
    "PSReadline version: $v"
    if ($IsLinux -or $IsMacOS) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
    "BufferWidth: $([console]::BufferWidth)"
    "BufferHeight: $([console]::BufferHeight)"
}

**Comment by msftrncs** [comment]
@tamulavage, you might have to edit your post, make sure its not wrapped in comments.

In the mean time, I suspect your issue is probably related to PowerShellEditorServices crashing the PowerShell Integrated Terminal, and PSReadLine is getting blamed for it.  😄
