### ISSUE TITLE
editing wrapped line in history, up-arrow doesn't function at end of wrapped line.

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PSReadLine#1020]
Using a build of PSReadLine from 'master' + @daxian-dbw's PR #979
Windows 10 Insiders
PowerShell 7 beta 3

Steps to reproduce or exception report
--------------------------------------

scroll back through history, and edit one where at least one line is so long it wraps in the terminal.  On that line, arrow out to the end of the line, then attempt to go up by pressing up-arrow.  Nothing will happen.  Going down will work, but coming back up will again stop at this line.  Pressing left-arrow once, then up-arrow, and the cursor moves as expected.

![image](https://user-images.githubusercontent.com/26179051/64470137-c3b46f80-d103-11e9-9513-a4413c4a5a93.png)

**Comment by daxian-dbw** [comment]
This behavior exists without the changes in #979 (phew ... what a relief 😄)

**Comment by msftrncs** [comment]
@daxian-dbw, I agree.  It occurs in an earlier beta for sure.  I should have confirmed and mentioned that earlier.

To add a note, while editing (move the cursor within the item, then back to the end) a history item with only 1 line that wraps, an up arrow at the end of the line will take you up to the previous history item.
