### ISSUE TITLE
Add capability to scroll display by one line

### ISSUE THREAD

**Issue by favorini** [PowerShell/PSReadLine#104]
It would be handy to be able to scroll the display one (or n) line(s) at a time. Ctrl+UpArrow and Ctrl+DownArrow would map nicely to those. A half screenful is also a useful unit (like u and d in less).

**Comment by favorini** [comment]
Thanks for adding the functions. I guess you can mark this as closed now.

**Comment by lzybkr** [comment]
Fixed in commit 040b75a742b93da6dfa38b96972a98bcee9cbda1
