### ISSUE TITLE
extra line after submitting command in VS Code terminal

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PSReadLine#1042]
Environment data
----------------

```
PS version: 7.0.0-preview.3
PSReadline version: 2.0.0-beta4
os: 10.0.18975.1000 (WinBuild.160101.0800)
PS file version: 7.0.0.0
BufferWidth: 174
BufferHeight: 25
```
This is actually a build of PSReadLine using PR #979

Steps to reproduce
--------------------------------------
Using PowerShell in VS Code's terminal (currently 1.38.1 Stable and Nightly) enter commands until the buffer (screen) is full.  At that time, every command entered seems to receive a blank line immediately after the last line of the command, before the results or next prompt appears.   This can be demonstrated with a blank command entry.

![image](https://user-images.githubusercontent.com/26179051/64835205-ad4a6000-d5aa-11e9-8c49-cc912e5bd418.png)

This does not happen with the normal Windows console, nor does this happen if I switch to CMD in a PowerShell session, inside VS Code's terminal.

![image](https://user-images.githubusercontent.com/26179051/64835279-0e723380-d5ab-11e9-8798-53cc45110b0b.png)

**Comment by msftrncs** [comment]
I forgot two details:
- this only happens in the PowerShell Integrated Console inside VS Code (VSCode-PowerShell extension)
- PSReadLine cannot be removed from the PowerShell Integrated Console, so I haven't been able to determine that this issue isn't actually from the integrated console or its implementation of PSReadLine.

So its possible this issue belongs in the VSCode-PowerShell repository.

**Comment by SeeminglyScience** [comment]
> * PSReadLine cannot be removed from the PowerShell Integrated Console, so I haven't been able to determine that this issue isn't actually from the integrated console or its implementation of PSReadLine.

You should (hopefully) be able to set `"powershell.developer.featureFlags": []` to disable it.

> So its possible this issue belongs in the VSCode-PowerShell repository.

Yeah it does.  When I was integrating PSRL I was a bit aggressive in fixing an issue where prompts stayed on the same line and forgot to go back and fix it.  Should be just removing an extra `WriteOutput` line in the host somewhere.

**Comment by msftrncs** [comment]
Thanks, @SeeminglyScience, I was going to doublecheck the method to the `powershell.developer.featureFlags`, and sure enough that indicates that without the integration of PSReadLine in the integrated console, the double line feeds stop.

I'll close this here and reopen one in VSCode-PowerShell.
