### ISSUE TITLE
ystem.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by petterrb** [PowerShell/PSReadLine#1043]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 1 9 . 9 . 3 4 9 1 1 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 6 9 1 4 ' Space ' d : \ O n e D r i v e \ D o c u m e n t s \ S k o l e \ I T G K \ O v i n g Space 3 \ t e k s t s p i l l 2 . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: Verdien må være større enn eller lik null, og mindre enn konsollens bufferstørrelse i den dimensjonen.
Parameternavn: top
Den faktiske verdien var -2.
   ved System.Console.SetCursorPosition(Int32 left, Int32 top)
   ved Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   ved Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   ved Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)

My error messages are displayed in Norwegian, but the error message translates to:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name : top
Actual value was -2.
 at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)

This error occurs every second time i run my code and all subsequent times in the same terminal.
I assume the error message has something to do with the wall of text that appears when I hit ctrl+F5:
'd:\OneDrive\Documents\Skole\ITGK\Oving 3'; ${env:ALLUSERSPROFILE}='C:\ProgramData'; ${env:AMD_ENTRYPOINT}='vs/workbench/services/extensions/node/extensionHostProcess'; ${env:APPDATA}='C:\Users\pette\AppData\Roaming'; ${env:APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL}='true'; ${env:asl.log}='Destination=file'; ${env:BESIEGE_GAME_ASSEMBLIES}='C:/Program Files (x86)/Steam/steamapps/common/Besiege/Besiege_Data\Managed/'; ${env:BESIEGE_UNITY_ASSEMBLIES}='C:/Program Files (x86)/Steam/steamapps/common/Besiege/Besiege_Data\Managed/'; ${env:CommonProgramFiles}='C:\Program Files\Common Files'; ${env:CommonProgramFiles(x86)}='C:\Program Files (x86)\Common Files'; ${env:CommonProgramW6432}='C:\Program Files\Common Files'; ${env:COMPUTERNAME}='DESKTOP-FNFJ4L1'; ${env:ComSpec}='C:\WINDOWS\system32\cmd.exe'; ${env:DriverData}='C:\Windows\System32\Drivers\DriverData'; ${env:ELECTRON_RUN_AS_NODE}='1'; ${env:HOMEDRIVE}='C:'; ${env:HOMEPATH}='\Users\pette'; ${env:LOCALAPPDATA}='C:\Users\pette\AppData\Local'; ${env:LOGONSERVER}='\\DESKTOP-FNFJ4L1'; ${env:NUMBER_OF_PROCESSORS}='8'; ${env:OneDrive}='D:\OneDrive'; ${env:OneDriveConsumer}='D:\OneDrive'; ${env:OS}='Windows_NT'; ${env:PATHEXT}='.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'; ${env:PIPE_LOGGING}='true'; ${env:PROCESSOR_ARCHITECTURE}='AMD64'; ${env:PROCESSOR_IDENTIFIER}='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel'; ${env:PROCESSOR_LEVEL}='6'; ${env:PROCESSOR_REVISION}='5e03'; ${env:ProgramData}='C:\ProgramData'; ${env:ProgramFiles}='C:\Program Files'; ${env:ProgramFiles(x86)}='C:\Program Files (x86)'; ${env:ProgramW6432}='C:\Program Files'; ${env:PSModulePath}='C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules'; ${env:PUBLIC}='C:\Users\Public'; ${env:SESSIONNAME}='Console'; ${env:SystemDrive}='C:'; ${env:SystemRoot}='C:\WINDOWS'; ${env:TEMP}='C:\Users\pette\AppData\Local\Temp'; ${env:TMP}='C:\Users\pette\AppData\Local\Temp'; ${env:USERDOMAIN}='DESKTOP-FNFJ4L1'; ${env:USERDOMAIN_ROAMINGPROFILE}='DESKTOP-FNFJ4L1'; ${env:USERNAME}='pette'; ${env:USERPROFILE}='C:\Users\pette'; ${env:VERBOSE_LOGGING}='true'; ${env:VSCODE_CWD}='C:\Users\pette\AppData\Local\Programs\Microsoft VS Code'; ${env:VSCODE_HANDLES_UNCAUGHT_ERRORS}='true'; ${env:VSCODE_IPC_HOOK}='\\.\pipe\886264c37f5381057cc53449ae39a12a-1.38.1-main-sock'; ${env:VSCODE_IPC_HOOK_EXTHOST}='\\.\pipe\vscode-ipc-b12628db-2714-4ba4-a5ee-b0167ee812f7-sock'; ${env:VSCODE_LOGS}='C:\Users\pette\AppData\Roaming\Code\logs\20190913T145406'; ${env:VSCODE_LOG_STACK}='false'; ${env:VSCODE_NLS_CONFIG}='{"locale":"nb","availableLanguages":{},"_languagePackSupport":true}'; ${env:VSCODE_NODE_CACHED_DATA_DIR}='C:\Users\pette\AppData\Roaming\Code\CachedData\b37e54c98e1a74ba89e03073e5a3761284e3ffb0'; ${env:VSCODE_PID}='8204'; ${env:VSCODE_PREVENT_FOREIGN_INSPECT}='true'; ${env:windir}='C:\WINDOWS'; ${env:__COMPAT_LAYER}='DetectorsMessageBoxErrors'; ${env:Path}='C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\pette\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Brackets\command;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts;C:\Users\pette\Anaconda3\Scripts;;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\pette\AppData\Local\Microsoft\WindowsApps;;C:\Users\pette\AppData\Local\Programs\Microsoft VS Code\bin'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe' 'c:\Users\pette\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py' '--default' '--nodebug' '--client' '--host' 'localhost' '--port' '56914' 'd:\OneDrive\Documents\Skole\ITGK\Oving 3\tekstsp

With my very limited knowledge of how the debug console works, it seems to me as if it's trying to access random and completely unrelated files from my computer like games and mouse software.

I don't know if my bug report is posted correctly, apologies if so.

Thanks for any help.

**Comment by daxian-dbw** [comment]
This should have been fixed by #979
The `2.0.0-beta5` version of PSReadLine was released this morning, which contains the fix. Please get it from PowerShellGallary.
