### ISSUE TITLE
出现bug

### ISSUE THREAD

**Issue by small-pony** [PowerShell/PSReadLine#1047]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
# 出现bug
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 7 个密钥:
 c l Space Tab Tab Tab Tab

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -5。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.Internal.VirtualTerminal.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32 y)
   在 Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   在 Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   在 Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean 
menuSelect)
   在 Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@small-pony, you didn't mention what version of PSReadLine you are using. Have you tried using the preview release 2.0.0 beta5? This error probably no longer occurs with that version.

**Comment by daxian-dbw** [comment]
> 在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new

This URL was changed to `https://github.com/PowerShell/PSReadLine/issues/new` in beta4, so @small-pony must be using a version prior to beta4.

@small-pony please install the 2.0.0-beta5 from PowerShellGallery, which contains the fix to this issue.
