### ISSUE TITLE
Binding to Alt+arrow keys doesn't seem to work

### ISSUE THREAD

**Issue by favorini** [PowerShell/PSReadLine#105]
When I bind functions to Alt+Up/Down/Left/RightArrow or Alt+PageUp/Down or Alt+Home/End/Insert, the binding is made, but pressing the chord does nothing. Alt+Delete is the only one that works. Not sure if that's expected behavior.

I notice that [Console]::ReadKey($true) doesn't respond to these either.

**Comment by eugenesvk** [comment]
Are there any existing/planned solutions to these? Was also hoping to use several of the alt+arrow bindings, they are so accessible and yet reserved for some never-used .Net nonsense :(

**Comment by lzybkr** [comment]
It's not planned, but I might stop using Console.ReadKey for other reasons, making it a little easier to support.

I do think that i18n support requires the Alt+Numpad support, so I'm not sure how best to add support - implicitly disable Alt+Numpad only when you bind certain keys, or require an extra option to be more explicit? We'll see.

**Comment by eugenesvk** [comment]
Ok think about it when you stop using Console.ReadKey, these are rather useful keybinds to just sit around :)

**Comment by gilescope** [comment]
It's a pity as from a fish perspective alt-right arrow would have been nice. #687

I guess I'll have to live with `Set-PSReadLineKeyHandler -Key "Ctrl+RightArrow" -Function ForwardWord`

**Comment by daxian-dbw** [comment]
Close this one as external given that we have no plan to moving away from `Console.ReadKey`.

**Comment by benallred** [comment]
_wishes GitHub had a sad emoji to react with_

(Yes, I know there is a thumbs down but that doesn't feel appropriate here.)

I was really hoping to do something like alt+shift+right arrow to increase the selected scope, like some editors, including VS Code. Is there perhaps a .NET issue about this we can track?

**Comment by daxian-dbw** [comment]
> Is there perhaps a .NET issue about this we can track?

Not that I know of. But feel free to open one at https://github.com/dotnet/runtime
