### ISSUE TITLE
I don't know what is happening

### ISSUE THREAD

**Issue by aihnatiuk** [PowerShell/PSReadLine#1052]
Последние клавиши 200: (last keys 200)
 e x e ' Space ' c : \ U s e r s \ a n d r e \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 1 9 . 9 . 3 4 9 1 1 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 1 2 0 0 ' Space ' c : \ P r o g r a m m i n g \ V S _ C o d e \ P y t h o n \ a . p y ' Space Enter

Исключение:  (exception)
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной 
размерности. (The value must be greater than or equal to zero and less than the size of the buffer in this
dimension.)
Имя параметра: top (Parameter name)
Фактическое значение было -16. (
Fakticheskoye znacheniye bylo
25/5000
Actual value was)
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender() 
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by andrii-ihnatiuk** [comment]
![image](https://user-images.githubusercontent.com/55395347/64962446-1fb78a80-d8a0-11e9-86fc-aefaf5b18bcb.png)

**Comment by aihnatiuk** [comment]
![image](https://user-images.githubusercontent.com/55395347/64963608-365ee100-d8a2-11e9-82c1-2db0c2574c8c.png)
![image](https://user-images.githubusercontent.com/55395347/64963649-4971b100-d8a2-11e9-9449-042baf0147c1.png)
![image](https://user-images.githubusercontent.com/55395347/64963716-65755280-d8a2-11e9-9f30-5a4739dc8981.png)

**Comment by aihnatiuk** [comment]
When i first open my file it works perfectly. When i do it second time there are so much stuff in the console. But if i make the console smaller some errors appear.

**Comment by msftrncs** [comment]
@andrii-ihnatiuk, regarding the error, the most recent version of PSReadLine (2.0.0-beta5) should resolve.

**Comment by daxian-dbw** [comment]
> GitHub: https://github.com/lzybkr/PSReadLine/issues/new

This URL indicates that you are using the beta2 or prior version of PSReadLine.
The issue should have been fixed in the latest 2.0.0-beta5 version of PSReadLine. Please upgrade to the latest version.
