### ISSUE TITLE
 Chinese character Repeat twice

### ISSUE THREAD

**Issue by obhen233** [PowerShell/PSReadLine#1053]
![TIM截图20190916111429](https://user-images.githubusercontent.com/24905302/65006709-78d1fd80-d936-11e9-9739-ec3cc9b705a8.png)

**Comment by obhen233** [comment]
window 8.1

**Comment by msftrncs** [comment]
@obhen233, have you tried with PSReadLine unloaded? (`remove-module PSReadLine`)  If it still happens with PSReadLine removed, its possibly a PowerShell or .NET issue.  Since it looks like its happening in PowerShell results, its probably not PSReadLine.

**Comment by msftrncs** [comment]
I found a reference for this: #779.

**Comment by daxian-dbw** [comment]
Close as a duplicate to #779
