### ISSUE TITLE
Command line editing character spacing of some characters in NSimSun Font

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PSReadLine#1054]
Environment data
----------------

```
PS version: 7.0.0-preview.3
PSReadline version: 2.0.0-beta5
os: 10.0.18980.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
BufferWidth: 120
BufferHeight: 9001
```

Steps to reproduce or exception report
--------------------------------------

Using the NSimSun font in the Windows 10 console hosting PowerShell Preview, attempt using characters such as the curly double quotes or emdash on the command line.

```PowerShell
echo “出现问题。
```
When editing this command, the curly double-quote at the ~end~ begining causes corruption on the screen when the cursor should be just past it, due to it requiring two character spaces (double wide character) in this font, but PSReadLine appears to assume it only takes 1.  Only ``` `u{2018}-`u{2019}``` and ``` `u{201C}-`u{201D}``` quotes seem to be affected, along with the dashes, ``` `u{2013}-`u{2015}```

I believe this has been posted before, but an initial search did not uncover it.

**Comment by daxian-dbw** [comment]
Just so I'm clear, this is about the position of the cursor, right?
Comparing the cursor in pwsh `7.0.0-preview4` and cmd.exe:

![pwsh](https://user-images.githubusercontent.com/127450/65902992-71681680-e370-11e9-8f37-1b8483b03374.gif)

![cmd](https://user-images.githubusercontent.com/127450/65902995-75943400-e370-11e9-8b4e-8d70c59c1ca1.gif)

**Comment by daxian-dbw** [comment]
Also, half of the Chinese character left behind when pressing `Escape` to clear the current editing.
![edit](https://user-images.githubusercontent.com/127450/65903150-c441ce00-e370-11e9-8f34-45a44cb8b123.gif)

**Comment by msftrncs** [comment]
Position of the cursor, or that while editing, the spacing might be off by a half character causing corruption of the text as some characters may be drawn half-off.  This might be more common when referencing the command history.

The root cause is that PSReadLine is unable to estimate the actual cursor position, when it needs to specifically move the cursor, and redraw part of the command line. 

And for clarification, I have only been working in the Windows 10 console, not in Windows Terminal.

I'll try to follow up with what specifically makes the characters corrupted.

Maybe its the terminal that should be accounting for the character width when repositioning the cursor … probably too late for that now though.
