### ISSUE TITLE
PS Azure exception - requested I submit it

### ISSUE THREAD

**Issue by jdpavek** [PowerShell/PSReadLine#1062]
[PsAzureBugRpt.txt](https://github.com/PowerShell/PSReadLine/files/3639080/PsAzureBugRpt.txt)

Environment data
----------------

Connecting terminal...
======================= hope the below is what you wanted -jd =============
MOTD: Manage Azure Active Directory: Get-Command -Module AzureAD*

VERBOSE: Authenticating to Azure ...
Azure:/
PS version: 6.2.3
Azure:/
PS Azure:\>     $v = (Get-Module PSReadline).Version
Azure:/
PS Azure:\>     $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSReadLine.psd1" | Select-String "Prerelease = '(.*)'"
PS Azure:\>     if ($m) {
>>         $v = "$v-" + $m.Matches[0].Groups[1].Value
>>     }
Azure:/
PSReadline version: 2.0.0-beta3
Azure:/
>>         "os: $(uname -a)"
>>     } else {
>>     }
os: Linux cc-d01c6cc4-7f9b455b5c-grp82 4.15.0-1059-azure #64-Ubuntu SMP Fri Sep 13 17:02:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Azure:/
PS Azure:\>     "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
PS file version: 6.2.3.0
Azure:/
PS Azure:\>     "BufferWidth: $([console]::BufferWidth)"
BufferWidth: 126
Azure:/
PS Azure:\>     "BufferHeight: $([console]::BufferHeight)"
BufferHeight: 13
Azure:/
PS Azure:\>

Steps to reproduce or exception report
--------------------------------------
I can't seem to reproduce it but will try and attach the exception report.

**Comment by msftrncs** [comment]
This should go away with PSReadLine 2.0.0-beta5.  Its being caused by PSReadLine trying to perform the page-up/page-down operations, but cannot do so because the .NET libraries for the console support do not support those functions on the terminal being used (or do not know how to support cursor positioning).  Beta5 prevents PSReadLine from attempting that function on non-Windows consoles.

**Comment by daxian-dbw** [comment]
Thanks @msftrncs for the detailed explanation of the issue!
@jdpavek, the issue will be resolved once Cloud Shell moves to 2.0.0-beta5 PSReadLine.
