### ISSUE TITLE
Visual Studio Code 1.38.1 & conda

### ISSUE THREAD

**Issue by johninpoole** [PowerShell/PSReadLine#1063]
# This is a comment
print ('hello')

PS I:\Desktop Folders\Desktop 3\FILES\Intro to Python Development> & 'C:\ProgramData\Anaconda3\python.exe' 'c:\Users\YY\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '54265' 'i:\Desktop Folders\Desktop 3\FILES\Intro to Python Development\helloworld.py'
hello
PS I:\Desktop Folders\Desktop 3\FILES\Intro to Python Development> C:/ProgramData/Anaconda3/Scripts/activate
PS I:\Desktop Folders\Desktop 3\FILES\Intro to Python Development> conda activate base

conda : The term 'conda' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundExc  
   eption
    + FullyQualifiedErrorId : CommandNotFoundException

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by johninpoole** [comment]
Just updated Anaconda and updated to Visual Studio Code 1.38.1
This error shows on every run of code.

**Comment by msftrncs** [comment]
This looks like you are expecting a function named `conda` from a module in your profile?

The error message indicated, would not implicate PSReadLine in anyway that I know.  I think you might consider this to be a issue of the PowerShell extension in VS Code (PowerShell/VSCode-PowerShell), if you are using the integrated PowerShell console, or more generally an issue of VS Code's terminal's operation of PowerShell.  You also might make sure that the PowerShell in VS Code's terminal is the correct edition of PowerShell.  You may have a custom profile for PowerShell Core, but you might be in Windows PowerShell while running in VS Code.

**Comment by daxian-dbw** [comment]
I agree with @msftrncs. The reported issue doesn't seem to have anything to do with PSReadLine.
