### ISSUE TITLE
Visual Studio Code 1.38.1

### ISSUE THREAD

**Issue by johninpoole** [PowerShell/PSReadLine#1064]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 n - 2 0 1 9 . 9 . 3 4 9 1 1 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . 
p y ' Space ' - - d e f a u l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 
4 3 9 3 ' Space ' i : \ D e s k t o p Space F o l d e r s \ D e s k t o p Space 3 \ F I L E S \ I n t r o Space t o Space P y t h o n Space D e v e l o p m e n t \ H e l 
l o _ w o r l d . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -37.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)  
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS I:\Desktop Folders\Desktop 3\FILES\Intro to Python Development> cd 'i:\Desktop Folders\Desktop 3\FILES\Intro to Python Development'; ${env:ALLUSERSPROFILE}='C:\ProgramData'; ${env:AMD_ENTRYPOINT}='vs/workbench/services/extensions/node/extensionHostProcess'; ${env:APPDATA}='C:\Users\YY\AppData\Roaming'; ${env:APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL}='true'; ${env:CommonProgramFiles}='C:\Program Files\Common Files'; ${env:CommonProgramFiles(x86)}='C:\Program Files (x86)\Common Files'; ${env:CommonProgramW6432}='C:\Program Files\Common Files'; ${env:COMPUTERNAME}='YY-PC'; ${env:ComSpec}='C:\WINDOWS\system32\cmd.exe'; ${env:DASHLANE_DLL_DIR}='C:\Users\YY\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\YY\AppData\Roaming\Dashlane\6.1907.0.17833\ucrt;C:\Users\YY\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Qt;C:\Users\YY\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Ssl'; ${env:DriverData}='C:\Windows\System32\Drivers\DriverData'; ${env:ELECTRON_RUN_AS_NODE}='1'; ${env:FPS_BROWSER_APP_PROFILE_STRING}='Internet Explorer'; ${env:FPS_BROWSER_USER_PROFILE_STRING}='Default'; ${env:FP_NO_HOST_CHECK}='NO'; ${env:HOME}='C:\Users\YY'; ${env:HOMEDRIVE}='C:'; ${env:HOMEPATH}='\Users\YY'; ${env:LOCALAPPDATA}='C:\Users\YY\AppData\Local'; ${env:LOGONSERVER}='\\YY-PC'; ${env:MSMPI_BIN}='C:\Program Files\Microsoft MPI\Bin\'; ${env:MYSQLCONNECTOR_ASSEMBLIESPATH}='C:\Program Files (x86)\MySQL\Connector.NET 6.9\Assemblies\v4.5'; ${env:NUMBER_OF_PROCESSORS}='8'; ${env:OneDrive}='C:\Users\YY\OneDrive'; ${env:OneDriveConsumer}='C:\Users\YY\OneDrive'; ${env:OS}='Windows_NT'; ${env:PATHEXT}='.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'; ${env:PIPE_LOGGING}='true'; ${env:PROCESSOR_ARCHITECTURE}='AMD64'; ${env:PROCESSOR_IDENTIFIER}='Intel64 Family 6 Model 42 Stepping 7, GenuineIntel'; 
${env:PROCESSOR_LEVEL}='6'; ${env:PROCESSOR_REVISION}='2a07'; ${env:ProgramData}='C:\ProgramData'; ${env:ProgramFiles}='C:\Program Files'; ${env:ProgramFiles(x86)}='C:\Program Files (x86)'; ${env:ProgramW6432}='C:\Program Files'; ${env:PSModulePath}='C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\'; ${env:PUBLIC}='C:\Users\Public'; ${env:SESSIONNAME}='Console'; ${env:SystemDrive}='C:'; ${env:SystemRoot}='C:\WINDOWS'; 
${env:TEMP}='C:\Users\YY\AppData\Local\Temp'; ${env:TMP}='C:\Users\YY\AppData\Local\Temp'; ${env:USERDOMAIN}='YY-PC'; ${env:USERDOMAIN_ROAMINGPROFILE}='YY-PC'; ${env:USERNAME}='YY'; ${env:USERPROFILE}='C:\Users\YY'; ${env:VERBOSE_LOGGING}='true'; ${env:VS140COMNTOOLS}='C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\'; ${env:VSCODE_CWD}='C:\Program Files\Microsoft VS Code'; ${env:VSCODE_HANDLES_UNCAUGHT_ERRORS}='true'; ${env:VSCODE_IPC_HOOK}='\\.\pipe\8615ab5fc6d231b2a0d5932954bc0601-1.38.1-main-sock'; ${env:VSCODE_IPC_HOOK_EXTHOST}='\\.\pipe\vscode-ipc-fa896d77-f75a-45d1-9c9a-205dac6f0083-sock'; ${env:VSCODE_LOGS}='C:\Users\YY\AppData\Roaming\Code\logs\20190922T193956'; ${env:VSCODE_LOG_STACK}='false'; ${env:VSCODE_NLS_CONFIG}='{"locale":"en","availableLanguages":{},"_languagePackSupport":true}'; ${env:VSCODE_NODE_CACHE761284e3ffb0'; ${env:VSCODE_PID}='12520'; ${env:VSCODE_PREVENT_FOREIGN_INSPECT}='true'; ${env:windir}='C:\WINDOWS'; ${env:Path}='C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\YY\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program 
Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Common Files\Seagate\SnapAPI\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\YY\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Common Files\Acronis\TibMounter64'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\ProgramData\Anaconda3\python.exe' 'c:\Users\YY\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py' '--default' '--nodebug' '--client' '--host' 'localhost' '--port' '54393' 'i:\Desktop Folders\Desktop 3\FILES\Intro to Python Development\Hello_world.py' 
hello

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by johninpoole** [comment]
Problem happens when code is run from powershell rather than Start Debugging or Start Without Debugging

**Comment by msftrncs** [comment]
You might want to reedit your issue, some of the 'comment' got left behind...

However, this issue should be resolved by PSReadline 2.0.0-beta5, you can download it from PowerShellGallery.

**Comment by daxian-dbw** [comment]
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

In general, it would be much helpful if version information can be included in the issue report.
The URL indicates you were using 2.0.0-beta3 or prior versions of PSReadLine. Please try 2.0.0-beta5.
