### ISSUE TITLE
Prompt unresponsive with custom AddHistoryHandler since commit #1058

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PSReadLine#1067]
Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta5
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001

**And:**

PS version: 7.0.0-preview.4
PSReadline version: 2.0.0-beta5
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
BufferWidth: 120
BufferHeight: 9001

Steps to reproduce or exception report
--------------------------------------
@daxian-dbw:
1. Add custom PSReadLine history handler to PowerShell Profile:
```powershell
Get-Content $profile
#The only thing in profile is this:
$Parameters = @{
    AddToHistoryHandler = {
        param($line)
        $line -notmatch '^\s+|ToSecureString|AsPlainText'
    }
}
Set-PSReadLineOption @Parameters
```
2. Restart PowerShell session and start typing as soon as prompt is ready. The prompt is unresponsive during first few keystrokes and then outputs all typed keystrokes at once.
3. The workaround is to return new *AddToHistoryOption* enumerator type:
```powershell
Get-Content $profile
#The only thing in profile is this:
$Parameters = @{
    AddToHistoryHandler = {
        param($line)
        if ($line -notmatch '^\s+|ToSecureString|AsPlainText') {
            [Microsoft.PowerShell.AddToHistoryOption]::MemoryAndFile
        } else {
            [Microsoft.PowerShell.AddToHistoryOption]::SkipAdding
        }
    }
}
Set-PSReadLineOption @Parameters
```
It looks like there is issue with PSReadLine code handling returned *Boolean* (AKA old behavior)?

**Comment by daxian-dbw** [comment]
@kborowinski Thanks for self-hosting the dev builds and reporting this issue!
This is a bug in handling the script block handler after changing the handler type to `Func<string, object>`. The new handler type causes PowerShell to directly return `PSObject` that wraps the true return value.
A PR is out to fix this issue.
