### ISSUE TITLE
Error when try to display all possibilities for Enable-WindowsOptionalFeature

### ISSUE THREAD

**Issue by SlayerCult** [PowerShell/PSReadLine#1076]
Произошла ошибка. Сообщите об этой ошибке, указав данные ниже.
Напишите в GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Последние клавиши 200:
 RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow " Space Backspace Backspace | Space g e t - Tab Backspace Backspace Backspace h e l o p Backspace Backspace p Enter
 UpArrow Tab Tab Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Delete Enter
 c l s Enter
 UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Home g e t - h e l p Space Enter
 UpArrow Space = Backspace - e x Tab Enter
 e n a b l e - w i n Tab Tab Tab Shift+Tab Space - Ctrl+Space Enter
 Space * * LeftArrow s u b s y s t e m Enter
 UpArrow UpArrow DownArrow DownArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space Space Ctrl+Space Backspace Ctrl+Space y

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было -1677.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   в Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   в Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   в Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
> https://github.com/lzybkr/PSReadLine/issues/new

This URL indicates you are using `2.0.0-beta3` or prior versions of `PSReadLine`. This issue was fixed in `2.0.0-beta5`, please upgrade to the latest `PSReadLine` from PowerShellGallery.
