### ISSUE TITLE
Feature request: autocomplete executables without extension

### ISSUE THREAD

**Issue by ferenczy** [PowerShell/PSReadLine#1080]
Could you add an option to autocomplete names of executables without an extension like for example bash is doing, please?

That means if I have an executable `program.exe` and I autocomplete its name, PSReadline inserts just `program` without the extension.

**Comment by msftrncs** [comment]
Completions are actually handled by PowerShell, PSReadLine only presents a system to display them in a menu format.

Technically in a Windows environment, the completion would need to include the extension, to be 'complete'.   Bash comes from an environment where there typically is no extensions (at least for executable files of any kind), but without a extension on a Windows system, the item would still be considered ambiguous.  For instances, for VS Code, there is both a `code.cmd` and a `code.exe`, though only `code.cmd` is exposed by the `PATH`.
