### ISSUE TITLE
Exception: System.ArgumentOutOfRangeException:

### ISSUE THREAD

**Issue by mistwire** [PowerShell/PSReadLine#1084]
Environment data
----------------

PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
BufferWidth: 192
BufferHeight: 26
Steps to reproduce or exception report
--------------------------------------
I just tried to run a python script that I've run previously. It looks like it runs fine the 1st time, than any other time that I try to run it (without closing/reopening VSCode) it does this. The script still runs fine - but this bug happens. 

Last 200 Keys:
 l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 6 1 7 3 8 ' Space ' c : \ U s e r s \ c h r i s \ O n e D r i v e \ D o c u m e n t s \ G r e e n P a g e s \ C l i c k S o f t w a r e \ 0 2 5 2 7 7 6 _ A W S _ S S M \ p r o j e c t _ s c r i p t s \ l o g g i n g Space s c r i p t s \ c l i c k _ p g _ a u t o _ f r o m _ s 3 . p y ' Space Enter

**Comment by msftrncs** [comment]
Please try PSReadline 2.0.0-beta5 from PowerShellGallery, it should resolve this issue, from past reports.
