### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by valeevr** [PowerShell/PSReadLine#1087]
Последние клавиши 200:
 А л ь ф р е д о \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 1 9 . 9 . 3 4 9 1 1 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 0 2 3 4 ' Space ' c : \ P y t h o n H o m e w o r k \ H i t o r i \ H i t o r i . p y ' Space Enter

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было -18.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@Dambldore, you didn't mention what version of PSReadline your console is using, but this is probably fixed in PSReadline 2.0.0-beta5.  Try upgrading from the PowerShellGallery and then try again.

**Comment by iSazonov** [comment]
Is it possible add the version info in the error report? This could simplify bug reports.

**Comment by valeevr** [comment]
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by daxian-dbw** [comment]
@Dambldore The issue template has the script to get the environment data, all you need to do is to run the script and copy/paste the output.
This exception is very likely fixed in `2.0.0-beta5` of PSReadLine. Please upgrade and try again.
