### ISSUE TITLE
Blank lines not permitted after operator in specific terminals

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PSReadLine#1088]
Enter the following directly into terminal with Enter or Shift+Enter between lines:
```powershell
5 +

5 -

10
```

In PowerShell's _default_ terminal, this works perfectly and lines are allowed to be continued.

However, in a VS Code pwsh terminal (not the vscode-powershell Integrated Terminal, just a regular one) _and_ in the new Windows Terminal, a parsing error is reported as soon as the blank line is entered, not allowing any time to add additional input.

This works as expected when executing a stored script file. I suspect this is a bug in PSReadLine, but I suppose it's possible that the bug comes from Windows Terminal _and_ VS Code's terminal, this just seems like the most logical place to start. 🙂 

Environment data
----------------

## Windows Terminal
```
PS version: 7.0.0-preview.3
PSReadline version: 2.0.0-beta5
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 27
```

## VS Code Terminal

```
PS version: 7.0.0-preview.4
PSReadline version: 2.0.0-beta5
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 221
BufferHeight: 16
```

Steps to reproduce or exception report
--------------------------------------

1. Open terminal
2. Enter aforementioned simple expression with empty lines in between
3. See error.

**Comment by rkeithhill** [comment]
Yeah, this has been very annoying.  It also hoses the ability to do multiline pastes.  A fix would be **very welcome**.

**Comment by msftrncs** [comment]
Ctrl+Enter does succeed at generating new lines past the cursor in Windows Terminal.

There is a thread on this regarding VS Code, @TylerLeonhardt, I think, was looking in to this.

**Comment by SeeminglyScience** [comment]
This is more or less because the <kbd>SHIFT</kbd> + <kbd>ENTER</kbd> key binding doesn't play well with winpty/conpty. When you press <kbd>SHIFT</kbd> + <kbd>ENTER</kbd>, only the <kbd>ENTER</kbd> comes across, no <kbd>SHIFT</kbd>.

In VSCode you can get around it by adding this to your `keybindings.json`

```json
{
    "key": "shift+enter",
    "command": "workbench.action.terminal.sendSequence",
    "args": { "text": "\u2665" },
    "when": "terminalFocus",
},
```

and this to your PowerShell profile:

```powershell
# Treat the heart emoji like shift+enter when in VSCode.
if ($env:TERM_PROGRAM -eq 'vscode') {
        Set-PSReadLineKeyHandler -Chord "$([char]0x2665)" -Function AddLine
}
```

Afaik there's nothing PSRL can do about this because all it's getting is <kbd>ENTER</kbd>.

**Comment by vexx32** [comment]
Interesting... is there anything we can do on Windows Terminal to get something similar?

**Comment by SeeminglyScience** [comment]
Not that I can see.  It doesn't look like they have a command for that, and looking at the [schema](https://aka.ms/terminal-profiles-schema) for their settings file it seems to only accept a simple command name, no args (so probably a bit of work until they have something like `sendSequence`).

**Comment by daxian-dbw** [comment]
Thanks @SeeminglyScience for the insights!
@vexx32 I found https://github.com/microsoft/terminal/issues/530 in the Terminal repo.
