### ISSUE TITLE
error while launching a java project in vscode

### ISSUE THREAD

**Issue by anagonousourou** [PowerShell/PSReadLine#1094]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

Exception:
System.ArgumentOutOfRangeException: La valeur doit tre suprieure ou gale  zro et infrieure  la taille de la mmoire tampon de la 
console dans cette dimension.
Nom du paramtre: top
La valeur relle tait -2.
    System.Console.SetCursorPosition(Int32 left, Int32 top)
    Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
    Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
    Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
    Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
    Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
    Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
    Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
The issue was fixed in `2.0.0-beta5` version of `PSReadLine` module. Please upgrade from PowerShellGallery and try it out.
