### ISSUE TITLE
Unhandled exception in ConsolePal.ReadKey

### ISSUE THREAD

**Issue by edyoung** [PowerShell/PSReadLine#1099]
Steps to reproduce
------------------
I don't have a consistent repro, sorry. See version details below. Typed c space d backspace backspace, pwsh hung for about 10 seconds then produced error below and exited

```powershell
PS C:\onebranch> c
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey(Boolean intercept)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadOneOrMoreKeys()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKeyThreadProc()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

Expected behavior
-----------------
Don't crash

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@iSazonov I cannot. I cannot reproduce this, and the reported exception was thrown from the .NET Core code. Hope it's fixed in the .NET Core 3.0

**Comment by iSazonov** [comment]
https://stackoverflow.com/questions/46901071/readkey-not-working-in-net-core/46952718
https://stackoverflow.com/questions/6064989/running-a-windows-service-in-console-mode
https://github.com/OmniSharp/omnisharp-vscode/issues/1746

They say that it is terminal issue. I guess VS Code terminal.

We could close the issue until we get stable repo.

**Comment by jazzdelightsme** [comment]
This problem could be caused by: https://github.com/dotnet/runtime/issues/88697

I plan to open a new Issue for how this could be addressed in PSReadLine.
