### ISSUE TITLE
Cannot debug program.

### ISSUE THREAD

**Issue by Loreton** [PowerShell/PSReadLine#1111]
Hi, I'm not able to debug my program. 

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - c l i 
e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 4 9 9 9 3 ' Space ' K : \ F i l u \ L n D i s k \ G I T - R E P O \ g o o g l e D r i v e S y n c \ _ _ m 
a i n _ _ . p y ' Space ' - - u p l o a d ' Space ' - - c l e a n ' Space ' - - s k i p - d ' Space ' - - f o r c e ' Space ' - - d a t a Space L n D i s k ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -61.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS K:\Filu\LnDisk\GIT-REPO\googleDriveSync> cd 'K:\Filu\LnDisk\GIT-REPO\googleDriveSync'; ${env:ALLUSERSPROFILE}='C:\ProgramData'; ${env:AMD_ENTRYPOINT}='vs/workbench/services/extensions/node/extensionHostProcess'; ${env:APPDATA}='C:\Users\Loreto\AppData\Roaming'; ${env:APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL}='true'; ${env:COMMANDER_DRIVE}='K:'; ${env:COMMANDER_EXE}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\realApp\WinCmd\TOTALCMD64.exe'; ${env:COMMANDER_INI}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\LnData\Config\WinCmd.ini'; ${env:COMMANDER_PATH}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\realApp\WinCmd'; ${env:CommonProgramFiles}='C:\Program Files\Common Files'; ${env:CommonProgramFiles(x86)}='C:\Program Files (x86)\Common Files'; ${env:CommonProgramW6432}='C:\Program Files\Common Files'; ${env:COMPUTERNAME}='SILVIAPC'; ${env:ComSpec}='C:\WINDOWS\system32\cmd.exe'; ${env:DriverData}='C:\Windows\System32\Drivers\DriverData'; ${env:ELECTRON_RUN_AS_NODE}='1'; ${env:FPS_BROWSER_APP_PROFILE_STRING}='Internet Explorer'; ${env:FPS_BROWSER_USER_PROFILE_STRING}='Default'; ${env:GITDIR}='K:\Filu\LnDisk\LnFree\Pgm\PortableGit'; ${env:HOMEDRIVE}='C:'; ${env:HOMEPATH}='\Users\Loreto'; ${env:JAVA_HOME}='K:\Filu\LnDisk\LnFree\Pgm\Java\jdk1.8.0_66'; ${env:LN_BROWSERFORSUBLIME}='C:\Filu_C\LnDisk\LnFree\Network\Browser\Opera\launcher.exe'; ${env:LN_DRIVE}='K:'; ${env:LN_FREEDIR}='K:\Filu\LnDisk\LnFree'; ${env:LN_GITREPODIR}='K:\Filu\LnDisk\GIT-REPO'; ${env:LN_KITTYEXE}='K:\Filu\LnDisk\LnFree\Network\Telnet\Kitty\kitty.exe'; ${env:LN_LESLADIR}='K:\Filu\LnDisk\Lesla'; ${env:LN_LORETODIR}='K:\Filu\LnDisk\Loreto'; ${env:LN_MYBROWSER}='K:\Filu\LnDisk\LnFree\Network\Browser\Opera\launcher.exe'; ${env:LN_MYEDITOR}='K:\Filu\LnDisk\LnFree\Editors\SublimeText_3\sublime_text.exe'; ${env:LN_NOTEPAD}='K:\Filu\LnDisk\LnFree\Editors\NotePad++\notepad++.exe'; ${env:LN_PORTABLEAPPSDIR}='K:\Filu\LnDisk\PortableApps\PortableApps'; ${env:LN_PYTHONDIR}='K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64'; ${env:Ln_PythonExe}='K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64\python.exe'; ${env:LN_ROOTDIR}='K:\Filu\LnDisk'; ${env:LN_SCRIPTDIR}='K:\Filu\LnDisk\LnStart'; ${env:LN_STARTDIR}='K:\Filu\LnDisk\LnStart'; ${env:LN_SUBLIMEEDITOR}='K:\Filu\LnDisk\LnFree\Editors\SublimeText_3\sublime_text.exe'; ${env:LN_TC_CONFIGDIR}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\LnData\Config'; ${env:LN_TC_DATADIR}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\LnData'; ${env:LN_TC_DIR}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN'; ${env:LN_TC_FTPINIFILE}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\LnData\Config\wcx_ftp.ini'; ${env:LN_TC_ICONSDIR}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\LnData\Icons'; ${env:LN_TC_INIFILE}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\LnData\Config\WinCmd.ini'; ${env:LN_TC_LOGDIR}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\log'; ${env:LN_TC_PATH}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN'; ${env:LN_TC_PLUGINDIR}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN\LnData\PlugsIN'; ${env:LN_WINSCPDIR}='K:\Filu\LnDisk\LnFree\Network\FTPc\WinSCP'; ${env:LN_WINSCPEXE}='K:\Filu\LnDisk\LnFree\Network\FTPc\WinSCP\WinSCP.exe'; ${env:LN_WINSCPKITTYCMD}='K:\Filu\LnDisk\GIT-REPO\Scripts\Python\Sources\KittyFromWinScp\bin\kitty-from-WinScp.cmd'; ${env:LN_WINSCPKITTYPY}='K:\Filu\LnDisk\GIT-REPO\Scripts\Python\Sources\KittyFromWinScp\__main__.py'; ${env:LOCALAPPDATA}='C:\Users\Loreto\AppData\Local'; ${env:LOGONSERVER}='\\SILVIAPC'; ${env:myDIR}='K:\Filu\LnDisk\LnStart'; ${env:NUMBER_OF_PROCESSORS}='4'; ${env:OneDrive}='C:\Users\Loreto\OneDrive'; ${env:OneDriveConsumer}='C:\Users\Loreto\OneDrive'; ${env:OS}='Windows_NT'; ${env:PATHEXT}='.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'; ${env:PIPE_LOGGING}='true'; ${env:PRG}='LnStartProgram.zip'; ${env:PROCESSOR_ARCHITECTURE}='AMD64'; ${env:PROCESSOR_IDENTIFIER}='Intel64 Family 6 Model 42 Stepping 7, GenuineIntel'; ${env:PROCESSOR_LEVEL}='6'; ${env:PROCESSOR_REVISION}='2a07'; ${env:ProgramData}='C:\ProgramData'; ${env:ProgramFiles}='C:\Program Files'; ${env:ProgramFiles(x86)}='C:\Program Files (x86)'; ${env:ProgramW6432}='C:\Program Files'; ${env:PROMPT}='$P$G'; ${env:PSModulePath}='C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\'; ${env:PUBLIC}='C:\Users\Public'; ${env:SESSIONNAME}='Console'; ${env:sleepTime}='4'; ${env:SystemDrive}='C:'; ${env:SystemRoot}='C:\WINDOWS'; ${env:TEMP}='C:\Users\Loreto\AppData\Local\Temp'; ${env:TMP}='C:\Users\Loreto\AppData\Local\Temp'; ${env:USERDOMAIN}='SILVIAPC'; ${env:USERDOMAIN_ROAMINGPROFILE}='SILVIAPC'; ${env:USERNAME}='Loreto'; ${env:USERPROFILE}='C:\Users\Loreto'; ${env:VERBOSE_LOGGING}='true'; ${env:VSCODE_CWD}='K:\Filu\LnDisk\LnFree\Pgm\VSCode_138'; ${env:VSCODE_HANDLES_UNCAUGHT_ERRORS}='true'; ${env:VSCODE_IPC_HOOK}='\\.\pipe\5eae12b387990e3475b0ec4c82473878-1.38.1-main-sock'; ${env:VSCODE_IPC_HOOK_EXTHOST}='\\.\pipe\vscode-ipc-609c0529-b42d-4b9e-a939-76014d3071ef-sock'; ${env:VSCODE_LOGS}='K:\Filu\LnDisk\LnFree\Pgm\VSCode_138\data\user-data\logs\20191020T123211'; ${env:VSCODE_LOG_STACK}='false'; ${env:VSCODE_NLS_CONFIG}='{"locale":"en-us","availableLanguages":{},"_languagePackSupport":true}'; ${env:VSCODE_NODE_CACHED_DATA_DIR}='K:\Filu\LnDisk\LnFree\Pgm\VSCode_138\data\user-data\CachedData\b37e54c98e1a74ba89e03073e5a3761284e3ffb0'; ${env:VSCODE_PID}='10388'; ${env:VSCODE_PORTABLE}='K:\Filu\LnDisk\LnFree\Pgm\VSCode_138\data'; ${env:VSCODE_PREVENT_FOREIGN_INSPECT}='true'; ${env:windir}='C:\WINDOWS'; ${env:WORKINGDIR}='K:\Filu\LnDisk\LnFree\Files\Manager\WinCmd-LN'; ${env:Path}='K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64;K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64\DLLs;K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64\Lib;K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64\Scripts;K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64\Lib\site-packages;K:\Filu\LnDisk\Ldk1.8.0_66\bin;K:\Filu\LnDisk\LnFree\Pgm\PortableGit\bin;K:\Filu\LnDisk\GIT-REPO\gitUtils;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Lesla-Programs\AOMEI\Backupper;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Users\Loreto\AppData\Local\Microsoft\WindowsApps;;K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64\lib\site-packages\pywin32_system32;;K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64\lib\site-packages\pywin32_system32;'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'K:\Filu\LnDisk\LnFree\Pgm\WPy-3710\python-3.7.1.amd64\python.exe' 'k:\Filu\LnDisk\LnFree\Pgm\VSCode_138\data\extensions\ms-python.python-2019.10.41019\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '49993' 'K:\Filu\LnDisk\GIT-REPO\googleDriveSync\__main__.py' '--upload' '--clean' '--skip-d' '--force' '--data LnDisk'

**Comment by msftrncs** [comment]
@Loreton, this is more than likely fixed in PSReadLine 2.0.0-beta5, available from PowerShellGallery.  Give it a try.
