### ISSUE TITLE
Poor performance when copy & pasting large script into console.

### ISSUE THREAD

**Issue by JamesLear92** [PowerShell/PSReadLine#1113]
PS version: 5.1.18362.1
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000

**Issue description:**
If you copy and paste a large amount of code into a PowerShell window with PSReadLine, it takes a long time for the text to actually load. It starts off ok, but it's almost like PSReadLine has to redraw everything that has been entered so far, each new line loaded (almost as if it's clearing the host, then pasting everything in again with one more line).
There are no error messages shown, this appears to be a performance issue. I've had this on any PowerShell window running this module.

**Steps to reproduce:**
Copy and paste any large amount of text into a PowerShell window running PsReadLine.

**Comment by msftrncs** [comment]
PSReadLine 2.0.0-beta5 might resolve this.  Its true that the older versions redraw the entire command for each new line added, and the newest version still might.  There are some technical reasons for that.  Each line of code added could change the syntax highlighting of previously entered code, though it is rare and usually only affects the line immediately previously entered.

**Comment by lzybkr** [comment]
Also worth checking - how did you paste? Right click or <kbd>Ctrl+v</kbd>? The latter should be fast.

**Comment by daxian-dbw** [comment]
`2.0.0-beta5` should have solved this problem. Please try it out. Also, please use `Ctrl+v` like @lzybkr suggested.
