### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by vishal-daniel** [PowerShell/PSReadLine#1115]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by vschweitzer** [comment]
Have you tried installing PSReadLine 2.0.0-beta5? It fixed the issue (#1117) for me.
More info in [msftrncs's answer](https://github.com/PowerShell/PSReadLine/issues/1112#issuecomment-544745396).
