### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#1118]
Set-PSReadLineOption -Colors @{default='apple'}

Exception message is: o

**Comment by msftrncs** [comment]
and unsupported hash members are quietly accepted.

Set-PSReadLineOption -Colors @{everything='apple'}

Reference https://github.com/PowerShell/PSReadLine/issues/845#issuecomment-456493865

**Comment by SteveL-MSFT** [comment]
I'll fix both these issues
