### ISSUE TITLE
Autocomplete feature in powershell 

### ISSUE THREAD

**Issue by anirugu** [PowerShell/PSReadLine#1126]
originally posted here https://github.com/PowerShell/PowerShell/issues/10889

I write few command every time when I open powershell at global level. For example doing npx create-reacta-app abcd.

It can be anywhere. What I am looking for is when I started typing npx, it show something with grey text and if I press the Tab, the text will be set into the current line.

This could be quite useful. In few case on mac I see this thing, What is helpful here is I don't need to type everything by hand again. Just tab will type everything.

**Comment by msftrncs** [comment]
@anirugu, please edit your request to include the complete text of your original request, and keep the link included as well.

In a sense, what you are looking for might already exist with PSReadLine. 

At a blank prompt, press CTRL-R, then start trying, to find additional matches with what you have typed so far, press CTRL-R again and again.  Its going backward through your history of recent command entries.   To go forward in the list, use CTRL-S.

**Comment by msftrncs** [comment]
Note: reference #687 ...
