### ISSUE TITLE
Pasting code with Tabs and multilines instead of inserting the tab character is inserting the first code suggestion making working code fail

### ISSUE THREAD

**Issue by LazaroOnline** [PowerShell/PSReadLine#1128]
From VS Code using the "Powershell" Terminal,
Pasting code that contains multiline and Tabs instead of inserting the tab character in the terminal, is inserting the first code suggestion making working code fail.

Example:

This code should work:
```PowerShell
Class Person { [String] $Name; [String] $SurName}
$Person1 = New-Object Person -Property @{ Name = "Adam";
	SurName = "First" }
```
If you copy the above code (all at once) and paste it in Visual Studio Code's "PowerShell" Terminal it will fail because it will make a nasty parsing of the pasted code as if I was typing it myself instead of putting down the same text I have, resulting into adding to the last line:
`NameSurName = "First" }` which will make the previously working copied code into a failing one after just pasting it.
This error doesn't happen in a normal PowerShell window (powershell.exe) nor in the new Windows Terminal App.

It is not the first bug with copy/paste I report myself on VS Code's terminal, also the performance of such operation is terribly poor, plus in the bug template you have a comment prompting us to check for duplicates on other bugs related to pasting code... 
It seems to me that the whole way of pasting code is broken from it's very roots, something that should be simple and does work in other apps like powershell.exe or Windows Terminal.

Please consider not just solving this bug, but re-implementing "copy-paste" functionality in Visual Studio Code terminal, it is a nightmare after nightmare.

PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.356 (WinBuild.160101.0800)
PS file version: 10.0.18362.356 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 134
BufferHeight: 12

Visual Studio Code
Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by msftrncs** [comment]
Pasting in VS Code's terminal, or by using right-click on ConHost terminal, PSReadLine has no awareness, and cannot treat things any differently.  As far as PSReadLine (or any app running in VSCode's terminal) is concerned, they are just keypresses, so it literally looks like you are pressing TAB, even though you pasted it.

> If you copy the above code (all at once) and paste it in Visual Studio Code's "PowerShell" Terminal it will fail because it will make a nasty parsing of the pasted code as if I was typing it myself instead of putting down the same text I have, resulting into adding to the last line:

Yes, that's exactly what pasting in VS Code does when pasting…  it simply types it for you.

And the reason for this, is that VS Code has no idea where your shell really resides.   You could be remotely connected to a shell, and in that case, there is no clipboard support, so pasting must be performed by simulating typing.

This is probably why the default in VS Code's editor settings is to use spaces, not tabs.

**Comment by msftrncs** [comment]
> This error doesn't happen in a normal PowerShell window (powershell.exe) nor in the new Windows Terminal App.

Yes it does, if you paste via Right-Click.  But no, it does not happen in a normal ConHost, or VSCode terminal if PSReadLine is removed, although, in VS Code there is a delay when a tab is encountered indicating that a search is being performed, but its result does not seem to be used.

**Comment by LazaroOnline** [comment]
Probably this bug should be in a different repository, but for users of VS Code like me it gets hard to know where to open the bug, maybe in VS Code directly, feel free to transfer this issue to another repo.

It is nice to hear that VS Code can handle remote shells, but I don't see how it should sacrifice basic functionality that is used in everyday basis by most users like proper copy/paste to have that feature, and even so I don't see why it could not have both features considering that we are talking about interoperability between two microsoft products.

If VS Code is not aware of where powershell is, or if it cannot send the text from the clipboard to the terminal in a reliable way then that is what I meant by re-implementing or re-architecting the feature.

**Comment by daxian-dbw** [comment]
> if PSReadLine is removed ... in VS Code there is a delay when a tab is encountered indicating that a search is being performed, _but its result does not seem to be used_.

I just want to add that a tab completion is performed by the default host in this case, but without PSReadLine, the host  does NOT have the context of `$Person1 = New-Object Person -Property @{ Name = "Adam";` part when doing the tab completion, so no tab completion result is returned.

@LazaroOnline about the ctrl+v behavior of the VSCode terminal, it's better to submit your feedback at https://github.com/microsoft/vscode. We don't have the permission to transfer issues to the vscode repository, so you will have to open a new issue in that repository to give your feedback.
