### ISSUE TITLE
I got this issue from one of my own scripts ???

### ISSUE THREAD

**Issue by heintonny** [PowerShell/PSReadLine#1137]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by heintonny** [comment]
The last command before error message was:

if ($rule.Media1.ToUpper() -eq "X") {
>>         $nsgMedia1 | ForEach-Object {
>>             Write-Host "Create NSG rule in $($_.name): Name: $($rule.Name), SourceIP: $tempSourceAddressPrefix, SourcePort: $($rule.SourcePortRange), DestinationIP: $tempDestinationAddressPrefix, DestinationPort: $tempDestinationPortRange"
>>             @(az network nsg rule create -n "$($rule.Name)" --nsg-name $_.name --resource-group "$($rgSecurityGroup.name)" --priority "$($rule.Priority)" `
>>                 --access Allow --description "$($rule.Description)" --destination-address-prefixes $tempDestinationAddressPrefix --destination-port-ranges $tempDestinationPortRange `
>>                 --direction Inbound --protocol "$($rule.Protocol)" --source-address-prefixes $tempSourceAddressPrefix --source-port-ranges $($rule.SourcePortRange) --verbose)
>>         }
>>     }

**Comment by msftrncs** [comment]
You didn't provide any environment data or exception report.  You can edit your post to correct that.

However, if the environment data states that you are using PSReadline less than 2.0.0-beta5, you may want to upgrade and give it a try.

**Comment by daxian-dbw** [comment]
Close the issue due to lack of information.
