### ISSUE TITLE
report

### ISSUE THREAD

**Issue by happyztw** [PowerShell/PSReadLine#1139]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
异常:
System.ArgumentOutOfRangeException: 
该值必须大于或等于零，且必须小于控制
台缓冲区在该维度的大小。
参数名: left
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)       
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, 
Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) 
-----------------------------------------------------------------------

**Comment by msftrncs** [comment]
@happyztw, this looks a lot like an exception that should be fixed in PSReadLine 2.0.0-beta5, but you didn't mention what version you are using.

**Comment by happyztw** [comment]
thank you，the&nbsp;problem has solved.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Carl Morris"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 中午11:05
收件人:&nbsp;"PowerShell/PSReadLine"<PSReadLine@noreply.github.com&gt;;
抄送:&nbsp;"3219625830"<3219625830@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PowerShell/PSReadLine] report (#1139)




@happyztw, this looks a lot like an exception that should be fixed in PSReadLine 2.0.0-beta5, but you didn't mention what version you are using.
