### ISSUE TITLE
feature request: make Set-PSReadLineKeyHandler apply only for specific command, not every command

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#1142]
Environment data
----------------

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Steps to reproduce or exception report
--------------------------------------

see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5046#issue-516337459

**Comment by msftrncs** [comment]
@ratatoeey, you will need to provide a bit more of what you are looking for in your request (you can edit the request).  The linked issues do not make it clear what you are thinking.  While linked issues are great, all of the content of your idea should be expressed here in detail.  Be sure to include some detail as to how you would use such a feature for making a process you perform better.

**Comment by ghost** [comment]
if you can;t read it all, I'd say read just this -> https://github.com/Moeologist/scoop-completion/issues/11#issuecomment-548929998
----

regards ratatoeey

**Comment by daxian-dbw** [comment]
@ratatoeey Close the issue due to the lack of information.
Like @msftrncs suggested, please express your idea clearly in the issue description in details.

**Comment by ghost** [comment]
i tried to be more clear than issue#60 in https://code.visualstudio.com/docs/supporting/faq#_why-does-visual-studio-code-have-a-different-license-than-the-vscode-github-repository, I might try again later if time permits.

----

regards ratatoeey
