### ISSUE TITLE
something went wrong when i run my python code the second time by pressing ctrl+f5

### ISSUE THREAD

**Issue by elin-croft** [PowerShell/PSReadLine#1147]
Environment data
----------------
windows 10 pro 1903
vscode :1.39.2
python:3.7.3 64bit
python extension :2019.10.44104

Steps to reproduce or exception report
--------------------------------------
i run my python code by pressing ctrl+f5 
when i run my python code the first time after i open vscode everything just looks normal.
BUT, when i try to run my code the second time, the power shell will run a totally different command and tells me that(see below) 

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 e x e ' Space ' c : \ U s e r s \ w a n g y \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 1 9 . 1 0 . 4 4 1 0 4 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 9 9 6 2 ' Space ' d : \ e x p e r i m e n t \ r e l u 6 . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -15.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

and after it does this couple times then it execute my code

**Comment by elin-croft** [comment]
here is a screenshot of my code and powershell command
![show](https://user-images.githubusercontent.com/26298602/68069048-3c4b4b80-fd96-11e9-89f0-afcef311a92a.png)

**Comment by msftrncs** [comment]
@elin-croft, the issue that causes the exception report is resolved in PSReadline 2.0.0-beta5, which is available from the PowerShellGallery (via `-AllowPrerelease`).  Give it a try.

**Comment by elin-croft** [comment]
thanks it really helped my problem
