### ISSUE TITLE
hashtable assignment bug

### ISSUE THREAD

**Issue by eliassone** [PowerShell/PSReadLine#1148]
### Steps to reproduce or exception report

|Name|Value|
|----|-----|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|{1.0, 2.0, 3.0, 4.0...}|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

**This works:**
$relations = @(
    @{op="add";path="/relations/-";value=@{rel="Hyperlink";url="http://blogs.msdn.com"}},
    @{op="add";path="/relations/-";value=@{rel="Hyperlink";url="http://blogs.msdn.com"}}
)

**This doesn't work:**
$relations = @(
    @{
        op    = "add"
        path  = "/relations/-"
        value = @{
            rel = "Hyperlink"
            url = "http://blogs.msdn.com"
        }
    },
    @{
        op    = "add"
        path  = "/relations/-"
        value = @{
            rel = "Hyperlink"
            url = "http://blogs.msdn.com"
        }
    }
)

### Output
 PS >> $relations = @(
 \>\> @{
 \>\>     op    = "add"
 \>\>     path  = "/relations/-"
 \>\>     value = @{
 \>\>         rel = "Hyperlink"
 \>\>         url = "http://blogs.msdn.com"
 \>\>     }
 \>\> },
 \>\> @{
 \>\>     op    = "add"
 \>\>     path  = "/relations/-"
 \>\>     value = @{
 \>\>         rel = "Hyperlink"
 \>\>         url = "http://blogs.msdn.com"
 \>\>     }
 Oops, something went wrong.  Please report this bug with the details below.
 Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
 -----------------------------------------------------------------------
 Last 200 Keys:
  l Space = Space " H y p e r l i n k " Enter
  Space Space Space Space Space Space Space Space u r l Space = Space " h t t p : / / b l o g s . m s d n . c o m " Enter
  Space Space Space Space Ctrl+Alt+} Enter
  Ctrl+Alt+} , Enter
  Ctrl+Alt+@ Ctrl+Alt+{ Enter
  Space Space Space Space o p Space Space Space Space = Space " a d d " Enter
  Space Space Space Space p a t h Space Space = Space " / r e l a t i o n s / - " Enter
  Space Space Space Space v a l u e Space = Space Ctrl+Alt+@ Ctrl+Alt+{ Enter
  Space Space Space Space Space Space Space Space r e l Space = Space " H y p e r l i n k " Enter
  Space Space Space Space Space Space Space Space u r l Space = Space " h t t p : / / b l o g s . m s d n . c o m " Enter
  Space Space Space Space Ctrl+Alt+} Enter
  Ctrl+Alt+} Enter
  ) Enter
 
 
 Exception:
 System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
 Parameter name: top
 Actual value was -3.
    at System.Console.SetCursorPosition(Int32 left, Int32 top)
    at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
    at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
    at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
    at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
    at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
    at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

### Note
**It works with:**

|Name|Value|
|----|-----|
|PSVersion|6.2.3|
|PSEdition|Core|
|GitCommitId|6.2.3|
|OS|Microsoft Windows 10.0.18362|
|Platform|Win32NT
|PSCompatibleVersions|{1.0, 2.0, 3.0, 4.0…}|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

**Comment by msftrncs** [comment]
@eliassone, this was resolved in a recent beta of PSReadLine.  You can get 2.0.0-beta5 from PowerShellGallery (it must be installed separately for Windows PowerShell vs PowerShell 6/7).  Give it a try.
