### ISSUE TITLE
BUG in Chinese-mode 

### ISSUE THREAD

**Issue by brealid** [PowerShell/PSReadLine#1157]
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 200 个密钥:
 Enter
 1 Space 1 Space 5 Space 1 Enter
 2 Space 1 Space 4 Space Enter
 UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow DownArrow Backspace 3 Enter
 UpArrow Enter
 3 Space 1 Space 4 Enter
 UpArrow UpArrow Enter
 3 Space 1 Space 4 Backspace Backspace Backspace Backspace Backspace UpArrow Enter
 UpArrow Enter
 { Enter
 t e s t Space = Space 1 Enter
 r e t u r n Space t e s t Enter
 } Enter
 UpArrow Backspace ; ; Enter
 i f Space ( x ) Space LeftArrow LeftArrow Backspace r e Backspace Backspace t e s RightArrow LeftArrow t RightArrow Space r e t u r n Space y Enter
 i f Space g g Enter
 w e Space w i l l Space g g Enter
 l e t Space p o w e r s h e l l Space G G Enter
 l u o g u Space g g Enter
 e Enter
 e ^ x Enter
 t e s t Enter
 g g Enter
 l e t Enter
 d Enter
 }

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -3。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@hkxadpall, give PSReadline 2.0.0-beta5 a try, from the PowerShellGallery.  It most likely will solve the issue.
