### ISSUE TITLE
IOException: The system cannot open the device or file specified : 'PSReadLineHistoryFile_____'

### ISSUE THREAD

**Issue by tivup** [PowerShell/PSReadLine#1159]
Environment data
PS version: 6.2.3
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At /Users/n0212741/read_line_diag.ps1:17 char:44
+ ... et-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSRead ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
 
Get-Content : Cannot find path '/PSReadLine.psd1' because it does not exist.
At /Users/n0212741/read_line_diag.ps1:17 char:10
+     $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Pa ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (/PSReadLine.psd1:String) [Get-Content], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
PSReadline version: 
os: Darwin __<<computer_name>>__ 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
PS file version: 6.2.3.0
HostName: ConsoleHost
BufferWidth: 80
BufferHeight: 24
-------
Steps to reproduce or exception report
--------------------------------------
1. Running pwsh in terminal on a mac gives me the following error:
Exception:
```
System.IO.IOException: The system cannot open the device or file specified : 'PSReadLineHistoryFile_1638318841'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
----------



2. This seems to be related to https://github.com/PowerShell/PSReadLine/issues/988 but I chmod'd /tmp to 755 and got the same exception after restarting the terminal

3. Environment data is included above

**Comment by tivup** [comment]
FYI: I installed and reinstalled powershell using brew on my mac - I think my problem is trivial i.e. the path is set incorrectly or something similar.  I'd really appreciate if someone can help me decipher this error or help if they've run into this before.

**Comment by msftrncs** [comment]
@tivup, can you please edit your post, and correct the code block for the exception report, so that the issue you referenced will hyperlink correctly?  Thanks,

Do you know what version of PSReadLine you have?   The environment detail script seems to have an issue.

`(module psreadline).privatedata.psdata` should spit out the beta version if its a 2.0.0 version.

**Comment by tivup** [comment]
Closing this issue since I've found a work around and will be using my windows VM for powershell.  Giving up on pwsh on MAC for now.
