### ISSUE TITLE
vscode提示bug

### ISSUE THREAD

**Issue by sclbeta** [PowerShell/PSReadLine#1171]
在调试代码时出现以下错误，同时提示出现bug，让我到这里提issue 

200 个密钥:
 y t h o n . p y t h o n - 2 0 1 9 . 1 0 . 4 4 1 0 4 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 1 5 4 8 ' Space ' c : \ W o r k P r o j e c t \ 临 沂
 大 学 \ 临 沂 大 学 授 课 \ 2 0 1 9 - 2 0 2 0 - 1 \ P y Q t 5 - m a s t e r \ C h a p t e r 0 4 \ q t 0 4 1 4 _ Q m e n u . p y ' Space Enter

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -2。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@sclbeta, this issue should be fixed in PSReadLine 2.0.0-beta5.  Give it a try, from PowerShellGallery.

**Comment by daxian-dbw** [comment]
@sclbeta Please provide the environment data when you submit issues in future. The bug template has the script to collect the environment data for you.
