### ISSUE TITLE
마지막 200 키:  . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 1 9 . 1 0 . 4 4 1 0 4 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - -  n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 0 4 5 3 ' Space ' c : \ U s e r s \ 문 석 민 \ D e s k t o p \ T e s t \ S t  u b b o r n _ b e a r . p y ' Space Enter

### ISSUE THREAD

**Issue by tirals88** [PowerShell/PSReadLine#1175]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by msftrncs** [comment]
@tirals88, its preferred if you would complete the exception report and environment data sections, but also, your issue (VSCode and Python) is probably resolved in PSReadLine 2.0.0-beta5, give it a try from the PowerShellGallery.
