### ISSUE TITLE
PowerShell crashes w/ unhandled exception in PlatformWindows.OnBreak

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#1177]
Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta4
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 165
BufferHeight: 46

Steps to reproduce or exception report
--------------------------------------
I don't have a consistent repro, but when I look in the event log, I see the following:

```
Application: pwsh.exe
CoreCLR Version: 4.700.19.50403
.NET Core Version: 3.1.0-preview1.19506.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at PlatformWindows.OnBreak(ConsoleBreakSignal signal)
```

PlatformWindows.OnBreak is in PSReadLine, not PowerShell.

**Comment by msftrncs** [comment]
Yes,  I have reproduction here!

https://github.com/PowerShell/PowerShell/issues/10579
