### ISSUE TITLE
Pressing PageUp Or PageDown

### ISSUE THREAD

**Issue by khlph** [PowerShell/PSReadLine#1187]
Environment data
----------------

PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 211
BufferHeight: 3000

Steps to reproduce or exception report
--------------------------------------
Last 200 Keys:
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace ` p y t h o n Space Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c d Space . . Enter
 c d Space K Tab Enter
 g i t Space s t a t u s Enter
 g t Space l l Backspace Backspace Backspace Backspace i t Space l o g Enter
 g i t Space p u l l Enter
 g i t Space s t a t u s Enter
 g u t Space Backspace Backspace Backspace i t Space l o g Enter
 ` p y t h o n Space t r a Tab Enter
 ` ` UpArrow Enter
 d f Backspace Backspace PageUp PageDown PageUp PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown Ctrl+z Ctrl+x Enter
 Enter
 PageUp PageDown

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by msftrncs** [comment]
@khlph, I cannot reproduce this.  PSReadLine 2.0.0-beta6 is now available in PowerShellGallery.  Give it a try.  If you can still reproduce this, please come back and update this issue.
