### ISSUE TITLE
Colorizing ContinuationPrompt causes cursor to be in wrong position

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSReadLine#1188]
Environment data
----------------

PS version: 7.0.0-preview.5
PSReadline version: 2.0.0-beta6
os: 10.0.19018.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: Visual Studio Code Host
BufferWidth: 217
BufferHeight: 20

Happens in all hosts (windows terminal, etc.)

Steps to reproduce or exception report
--------------------------------------

I want my continuation prompt to match my promptText, but if I add the color, the prompt is off. I'd guess that PSReadline is not subtracting the ansi escape sequences from it's "how far to indent" count for continuationprompt.

It works fine, types fine, and if I take out the ansi color, indents fine however.

```powershell
$plRight = "$([char]0xe0b4)"
$reset = "$([char]0x1b)[0m"
$grey = "$([char]0x1b)[90m"
$white = "$([char]0x1b)[1m"
$separator = "$grey$plRight$reset"

Set-PSReadLineOption -PromptText "$grey$plRight " -ContinuationPrompt "$plright$plright"

function prompt {
    "PS $($executionContext.SessionState.Path.CurrentLocation)$($separator * ($nestedPromptLevel + 1)) "
}
```

![Capture](https://user-images.githubusercontent.com/15258962/68927669-1da56700-073d-11ea-926f-26d981a094ef.gif)

**Comment by msftrncs** [comment]
I think `Set-PSReadLineOption -colors @{ContinuationPrompt="darkgray"}`. would work better, though there might be some issues around that.   ~PSReadLine definitely does not do ANSI escape decoding,~ edit: in the right cases, it does account for VT color sequences.

**Comment by JustinGrote** [comment]
@msftrncs for some reason I totally spaced on that setting, I can probably work with that.

**Comment by msftrncs** [comment]
I did just create issue #1189, just to be aware of that.

**Comment by heaths** [comment]
I'm hitting the same issue with:
```powershell
Set-PSReadLineOption -ContinuationPrompt "`e[0;37;100m`u{e0b1}`e[0;90m`u{e0b0}`e[0m "
```
But if it helps diagnosing the issue, my cursor is even further to the left, which maybe is a result of how long the continuation prompt vterm sequence is:

![image](https://user-images.githubusercontent.com/1532486/70221126-996f4f80-16fc-11ea-8053-084d5ea7c9e2.png)

**Comment by heaths** [comment]
FWIW, this does appear only to be when coloring lines. Using Unicode characters alone still works as expected:

```powershell
Set-PSReadLineOption -ContinuationPrompt "`u{e0b1}`u{e0b1} "
```

![image](https://user-images.githubusercontent.com/1532486/70225692-5f09b080-1704-11ea-92ef-ce1ba607a463.png)
