### ISSUE TITLE
Continuing blank lines causes continuation prompt to revert to default color.

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PSReadLine#1189]
Environment data
----------------
PSReadLine 2.0.0-beta6
Windows 10

Steps to reproduce or exception report
--------------------------------------
Set continuation prompt color:

``` PowerShell
Set-PSReadLineOption -colors @{ContinuationPrompt="darkgrey"}
```
Then enter several empty lines using <KBD>SHIFT</KBD>-<KBD>ENTER</KBD>.

As long as the current line is empty (but not counting the first line), the next continuation prompt will have default color instead of the specified prompt color.

![image](https://user-images.githubusercontent.com/26179051/68970682-71e82f80-07ad-11ea-8cf0-5a537370572c.png)

**Comment by JustinGrote** [comment]
I was actually just troubleshooting on this lol.

It doesn't seem to be super-consistent, for instance this generally works with pwsh -noprofile:
`set-psreadlineoption -Colors @{ContinuationPrompt = 'green'}`

![image](https://user-images.githubusercontent.com/15258962/68971476-72c59500-079e-11ea-84ed-5e44be6bdd10.png)

But it doesn't in my "fancy" profile which has a lot of ansi escapes in the prompt (but a regular continuation prompt)
![image](https://user-images.githubusercontent.com/15258962/68971582-aef8f580-079e-11ea-821e-d1a170ab2437.png)

Haven't figured out the common demoninator yet.

**Comment by msftrncs** [comment]
I'm not getting inconsistent results.  It doesn't seem to matter what method is used to produce a continuation.

If after having a bunch of blank continuation lines, if I insert a space on a line, all the continuation prompts currently present will correct their color, but new continuation prompts, starting at the end, will not, regardless of where the insertion happened.

I surmise, that during rendering, the renderer keeps track of whether it changed colors, but during normal insert mode, full renders are not occurring, so it forgets that the color was changed back to default for the next character (before the next character arrives) on a new line.  The render's are (at least partially) remembered, so that's why once its changed, it stays,

**Comment by msftrncs** [comment]
@daxian-dbw, this appears to be a possibly new regression starting in PSReadLine 2.0.0-beta5, with changes to `ReallyRender()` to save from reprinting lines, so when it prints the new continuation prompt line (at the end), the current active color of the terminal isn't the expected color of the prompt.  I don't think there are any other possible scenario's to get in to this condition.  The continuation prompt does it because it wasn't typed.  

I can produce other side effects, such as

```
Prompt>
>> -
>> -
```
Inserting lines via InsertLineBelow from the prompt line, will cause the operators on each of the continuation line to fail to color, only if the continuation prompt color and operator color is the same.  There would be similar scenario's anywhere the first token on a continued line matches the line continuation color.  If one adds another token on any of the higher lines, all of them will be colored correctly because rendering will update all lines below the change.

My only though on this, is that line continuation prompt (or just the line continuation itself) should always output the color sequence (reset active color to `null`?), so that its always in the render buffer so that `ReallyRender()` can start with any line and get the color right at the start of the line.
