### ISSUE TITLE
Circumflex dead key not working

### ISSUE THREAD

**Issue by xylographe** [PowerShell/PSReadLine#1190]
```
PS version: 5.1.14409.1018
PSReadline version: 2.0.0-beta6
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
HostName: ConsoleHost
BufferWidth: 272
BufferHeight: 32766

keyboard: US (international)
language: nl-NL
```
Apostrophe, grave, quote and tilde work fine, but the circumflex dead key has no effect.

Examples:
Pressing **`"o`** results in **`ö`**, as expected.
Pressing **`^o`** results in **`o`**, where **`ô`** is expected.
Pressing **`~~`** results in **`~~`**, as expected.
Pressing **`^^`** generates no output, where **`^^`** is expected.

**Comment by xylographe** [comment]
After PSReadline upgrade,
```
PSReadline version: 2.0.0
```
Same behaviour.

**Comment by daxian-dbw** [comment]
I will address this issue in 2.1.0
