### ISSUE TITLE
v1.0.0.11 -- PowerShell history is not populated

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PSReadLine#120]
Automatically saved history is a must have feature. Thank you very much!

But it looks like PSReadline populates its internal history only. Is it by
design or is it just work in progress? I would expect PowerShell history to be
populated as well, so that PowerShell history commands work and related user
defined tools for history work, too.

---

Off topic

> To install, you'll need WMF5, but it will work fine with V3/4. I'm just restricting who installs to the most motivated folks until I get some more testing.
> Alternatively, you can build it yourself, all the code has been pushed.

I am motivated :) but I do not have WMF5 and I cannot build myself, currently. It was slightly difficult to get this release for testing...

**Comment by daxian-dbw** [comment]
Actually, I see more interest around the convergence between the PSReadLine history and PowerShell built-in history cache. 
There are more discussion about this in #1247, so close this one as a duplicate of #1247.
