### ISSUE TITLE
System.ArgumentOutOfRangeException: 索引和长度必须引用该字符串内的位置。

### ISSUE THREAD

**Issue by HaroldCC** [PowerShell/PSReadLine#1204]
-----------------------------------------------------------------------
上 27 个密钥:
 c d Space d Tab Tab Tab Tab Enter
 Enter
 d c Backspace Backspace c d Space Tab DownArrow RightArrow RightArrow Enter
 Enter
 c d Space Tab

异常:
System.ArgumentOutOfRangeException: 索引和长度必须引用该字符串内的位置。
参数名: length
   在 System.String.Substring(Int32 startIndex, Int32 length)
   在 Microsoft.PowerShell.PSConsoleReadLine.GetMenuItem(String item, Int32 columnWidth)
   在 Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   在 Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   在 Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)    在 Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by msftrncs** [comment]
@HaroldCC, you didn't report your environment data, but most likely your issue has been resolved in PSReadLine 2.0.0-beta6 available from PowerShellGallery.  Give it a try.

**Comment by daxian-dbw** [comment]
Close due to the lack of environment data and repro steps.
Please try the `2.0.0-beta6` and see if the issue still repros.
