### ISSUE TITLE
Tool tips for parameters should be displayed as the user types

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#1207]
There should be an setting to enable a mode where as the user types a command, we can dynamically show a tooltip on information about parameters such as type information or short description from help.  Could also apply to .NET API calls for parameters or showing overloads.

**Comment by vexx32** [comment]
This is already available from PSReadLine as the `MenuComplete` option as triggered from tab completion currently. Are you suggesting we'd somehow expand this functionality to trigger on every keystroke? 🤔 

Having .NET method parameters included there would be awesome as well! 💖

**Comment by SteveL-MSFT** [comment]
@vexx32 Not the same as MenuComplete.  In this case, I may have already typed: `Get-Command -Name`, the tool tip should show the type `string[]` and maybe show the first line of help for this parameter: `Specifies an array of names. This cmdlet gets only commands that have the specified name. Enter a name or name pattern. Wildcard characters are permitted.`

**Comment by msftrncs** [comment]
Is this the same as #1096?

**Comment by SteveL-MSFT** [comment]
@msftrncs close enough that I'll close this one!
