### ISSUE TITLE
python debug flask error

### ISSUE THREAD

**Issue by blwuer** [PowerShell/PSReadLine#1208]
I use vscode to debug the Python flask code. When I press F5, the environment variables are automatically added to the console, which results in debugging failure. The previous version of vscode 1.32 did not have this problem. This problem occurred after the update today.

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by daxian-dbw** [comment]
@blwuer what you described doesn't sound like a PSReadLine issue.
