### ISSUE TITLE
System.ArgumentOutOfRangeException: 

### ISSUE THREAD

**Issue by Rirre** [PowerShell/PSReadLine#1210]
Last 200 Keys:
 Enter
 Enter
 Enter
 UpArrow UpArrow Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Ctrl+v Enter
 Enter
 Enter
 g e t - h e l p Space * d e b u g * Enter
 Enter
 g e t - p r o c e s Tab Space - n a Tab Space * W i n " UpArrow DownArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow DownArrow DownArrow DownArrow g e t - p r o Tab Space - n a m Tab Space W I N * Enter
 Enter
 UpArrow Backspace Backspace Backspace Backspace W I N Backspace Backspace Backspace w i n i n i t LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Space Ctrl+Alt+| Enter
 Enter
 Enter
 UpArrow UpArrow DownArrow Ctrl+Alt+| Enter
 c l e a r Enter
 UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Ctrl+Alt+$ '

Exception:
System.ArgumentOutOfRangeException: Värdet måste vara större än eller lika med noll och mindre än konsolens buffertstorlek i dimensionen.
Parameternamn: left
Det faktiska värdet var -1.
   vid System.Console.SetCursorPosition(Int32 left, Int32 top)
   vid Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   vid Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   vid Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   vid Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   vid Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   vid Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   vid Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   vid Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@Rirre, you didn't report the environment data from the script in the template, but most likely you are not using PSReadLine 2.0.0-beta6, available from PowerShellGallery.  Give that a try, and if it still occurs, report back.

**Comment by Rirre** [comment]
Thanks for you answer Carl,

I’ll will try that later.


Regards
//Rickard

Från: Carl Morris <notifications@github.com>
Svara till: PowerShell/PSReadLine <reply@reply.github.com>
Datum: fredag 29 november 2019 21:55
Till: PowerShell/PSReadLine <PSReadLine@noreply.github.com>
Kopia: Rickard Ekström <rickard@rdeconsulting.se>, Mention <mention@noreply.github.com>
Ämne: Re: [PowerShell/PSReadLine] System.ArgumentOutOfRangeException: (#1210)


@Rirre<https://github.com/Rirre>, you didn't report the environment data from the script in the template, but most likely you are not using PSReadLine 2.0.0-beta6, available from PowerShellGallery. Give that a try, and if it still occurs, report back.

**Comment by daxian-dbw** [comment]
Close the issue for now. Please report back if the exception happens with the `2.0.0-beta6` of PSReadLine.
