### ISSUE TITLE
The entry is incomplete

### ISSUE THREAD

**Issue by he852100** [PowerShell/PSReadLine#1213]
```
PSReadline version: 2.0.0-beta6
```
```
param(
    [ValidateSet('取消购买的域名','检索指定域的详细信息','更新指定域的详细信息')]
    [string] $Name,
    [int32] $id
)
```
Results
```
PS > /test.ps1 -Name
更新指定域...检索指定域...取消购买的...
```
Expected
```
取消购买的域名    检索指定域的详细信息    更新指定域的详细信息
```
or
```
取消购买的域名
检索指定域的详细信息
更新指定域的详细信息
```

**Comment by msftrncs** [comment]
Doublewidth CJK character issue?  I can confirm the behavior.  I used a function:

```PowerShell
function test {
    param(
        [ValidateSet('取消购买的域名','检索指定域的详细信息','更新指定域的详细信息')]
        [string] $Name,
        [int32] $id
    )
}

test -name <CTRL-SPACE>
```

Result was:
```
取消购买的...更新指定域...检索指定域...
```

I confirmed that TabExpansion2().CompletionMatches included the complete and correct results.

It would appear that the number of characters were accounted for, but not the number of buffer cells.  This can probably be remedied fairly easily.

Thanks for the report.
