### ISSUE TITLE
Console Problems

### ISSUE THREAD

**Issue by fjimenezjob** [PowerShell/PSReadLine#1219]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
I have a problem when I enter DEBUG mode in Visual Studio Code, the first time I enter nothing happens, but from the second gives a lot of errors followed. Although in the end it works, I don't understand what happens.
I leave the error code next:
`Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
The error that the debug console shows me is as follows:
Últimas 200 claves:
 s Ctrl+Alt+\ f j g w i Ctrl+Alt+\ . v s c o d e Ctrl+Alt+\ e x t e n s i o n s Ctrl+Alt+\ m s - p y t h o n . p y t h o n - 2 0 1 9 . 1 1 . 5 0 7 9 4 Ctrl+Alt+\ p y t h o n F i l e s Ctrl+Alt+\ p t v s d _ l a u n c h e 
r . p y ' Space ' - - d e f a u l t ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 6 1 5 5 9 ' Space ' - m ' Space ' f l a s k ' Space ' r u n ' Space ' - - n o - d e b u g g e r ' Space ' - - n o - r e l o a d ' Space Enter

```
Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: top
Valor actual -18.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)`

```
What the powershell script shows me is the following:

```
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.476 (WinBuild.160101.0800)
PS file version: 10.0.18362.476 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000
![Anotación 2019-12-01 145603](https://user-images.githubusercontent.com/49567838/69915018-b977e800-144a-11ea-8328-7cfc49de4d14.png)


```

**Comment by msftrncs** [comment]
@fjimenezJOB, you should find that PSReadLine 2.0.0-beta6, available from PowerShellGallery should solve your issue.  Give it a try.
