### ISSUE TITLE
LengthInBufferCells() is not adequate to estimate buffer cells actually used by a line

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PSReadLine#1223]
Just raising a potential issue.

When `LengthInBufferCells()` is used to estimate the buffer cells that an entire line will consume, it can be inaccurate when a double-wide character lands with only 1 cell remaining at the edge of the buffer.  Functions such as `ConvertOffsetToPoint()` and `ConvertLineAndColumnToOffset()` do account for this.

The most likely places this will cause a problem is in trying to calculate where on the screen needs to be cleared after rendering an edited line.

**Comment by StevenBucher98** [comment]
Think this makes more sense to have in PowerShell or dotnet repo as that method is part of System.Management.Automation
