### ISSUE TITLE
Allow a variable or setting option to disable prepending remote machine name

### ISSUE THREAD

**Issue by heaths** [PowerShell/PSReadLine#1227]
Corresponding bug for PowerShell itself can be found [here](https://github.com/PowerShell/PowerShell/issues/11280).

Until (if ever) PowerShell fixes that issue (or I do, if they would accept it), because PSReadline is so ubiquitous it would be great if we had a way to prevent [GetPrompt](https://github.com/PowerShell/PSReadLine/blob/599e1784a96d1acfce8d4d2a561c82b07920ada4/PSReadLine/ReadLine.cs#L1004) from simply prepending the remote machine name, which messes up pretty prompts like powerline, form which mine below took some inspiration (e.g. of how the remote machine name looks):

![image](https://user-images.githubusercontent.com/1532486/70355630-7e4d2e80-1827-11ea-859a-820446fccefe.png)

If this were only in PSReadline for the time being, it might make more sense to be an option set via `Set-PSReadlineOption` and, if disabled, would set variable names for remote username and computername (if not already set, in case PowerShell implemented this later) in or around [line 1051](https://github.com/PowerShell/PSReadLine/blob/599e1784a96d1acfce8d4d2a561c82b07920ada4/PSReadLine/ReadLine.cs#L1051).

**Comment by daxian-dbw** [comment]
PSReadLine doesn't control writing out the prompt string ordinarily. It's done by PowerShell.
The `GetPrompt()` method you referred to is used only in some limited cases where PSReadLine needs to re-render the prompt string, such as when pressing <kbd>Ctrl+l</kbd> to clear the screen, so making changes to this method won't get you what you really want.

**Comment by heaths** [comment]
Except in those situations. If I can get PowerShell to implement such a variable, why not support it in this case?

**Comment by daxian-dbw** [comment]
If PowerShell has such a variable, then `GetPrompt()` should just honor that variable -- add or avoid the computer name based on the value of that variable when re-rendering the prompt.
