### ISSUE TITLE
bug while running python

### ISSUE THREAD

**Issue by karthick98** [PowerShell/PSReadLine#1229]
![report](https://user-images.githubusercontent.com/35052650/70376892-16383e80-1934-11ea-87f3-2950bc1d3e3e.PNG)

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by daxian-dbw** [comment]
You are using a version prior to 2.0.0-beta3. There have been many fixes that improves the stability of PSReadLine, so please try out the latest version 2.0.0-beta6 from the PowerShellGallery.
