### ISSUE TITLE
Change the availability set for a Windows VM

### ISSUE THREAD

**Issue by thiagobeier** [PowerShell/PSReadLine#1232]
Hi everyone,

Environment data
----------------
recreating production vm to add availability set
using https://docs.microsoft.com/bs-cyrl-ba/azure/virtual-machines/windows/change-availability-set
we got errors adding NICS on the vm

Azure:/
PS Azure:\> # Create the basic configuration for the replacement VM
PS Azure:\>     $newVM = New-AzVMConfig `
>>    -VMName $originalVM.Name `
>>    -VMSize $originalVM.HardwareProfile.VmSize `
>>    -AvailabilitySetId $availSet.Id
Azure:/
PS Azure:\>
Azure:/
PS Azure:\>     Set-AzVMOSDisk `
>>    -VM $newVM -CreateOption Attach `
>>    -Name $originalVM.StorageProfile.OsDisk.Name `

Name                     : SERVER-SQL
AvailabilitySetReference : {Id}
HardwareProfile          : {VmSize}
StorageProfile           : {OsDisk}

Azure:/
Azure:/
PS Azure:\> # Add Data Disks
Azure:/
PS Azure:\>     foreach ($disk in $originalVM.StorageProfile.DataDisks) {
>>     Add-AzVMDataDisk -VM $newVM `
>>    -Name $disk.Name `
>>    -ManagedDiskId $disk.ManagedDisk.Id `
>>    -Caching $disk.Caching `
>>    -Lun $disk.Lun `
>>    -DiskSizeInGB $disk.DiskSizeGB `
>>    -CreateOption Attach
>>     }

Name                     : SERVER-SQL
AvailabilitySetReference : {Id}
HardwareProfile          : {VmSize}
StorageProfile           : {OsDisk, DataDisks}

Name                     : SERVER-SQL
AvailabilitySetReference : {Id}
HardwareProfile          : {VmSize}
StorageProfile           : {OsDisk, DataDisks}

Name                     : SERVER-SQL
AvailabilitySetReference : {Id}
HardwareProfile          : {VmSize}
StorageProfile           : {OsDisk, DataDisks}

Name                     : SERVER-SQL
AvailabilitySetReference : {Id}
HardwareProfile          : {VmSize}
StorageProfile           : {OsDisk, DataDisks}

Name                     : SERVER-SQL
AvailabilitySetReference : {Id}
HardwareProfile          : {VmSize}
StorageProfile           : {OsDisk, DataDisks}

Name                     : SERVER-SQL
HardwareProfile          : {VmSize}

Name                     : SERVER-SQL
AvailabilitySetReference : {Id}
HardwareProfile          : {VmSize}
StorageProfile           : {OsDisk, DataDisks}

Azure:/
PS Azure:\>
Azure:/
PS Azure:\> # Add NIC(s) and keep the same NIC as primary
Azure:/
PS Azure:\> foreach ($nic in $originalVM.NetworkProfile.NetworkInterfaces) {
>> if ($nic.Primary -eq "True")
>> {
>>     Add-AzVMNetworkInterface `
>>        -VM $newVM `
>>        -Id $nic.Id -Primary
>>        }
>>        else
>>        {
>>          Add-AzVMNetworkInterface `
>>         -VM $newVM `
>>          -Id $nic.Id
>>                 }
>>   }
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
```
 Space Space Space Space Tab Space Tab Space Space - I d Space $ n i c . I d Space Enter
 Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space } Enter
 Space Space Tab } Enter
 Enter
 # Space R e c r e a t e Space t h e Space V M Enter
 Space Space Space Space N e w - A z V M Space ` Enter
 Tab Space Space Space - R e s o u r c e G r o u p N a m e Space $ r e s o u r c e G r o u p Space ` Enter
 Tab Space Space Space - L o c a t i o n Space $ o r i g i n a l V M . L o c a t i o n Space ` Enter
 Tab Space Space Space - V M Space $ n e w V M Space ` Enter
 Tab Space Space Space - D i s a b l e B g i n f o E x t e n s i o n
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------
Azure:/
PS Azure:\> foreach ($nic in $originalVM.NetworkProfile.NetworkInterfaces) {
>> {
>>     Add-AzVMNetworkInterface `
>>        -VM $newVM `
>>        -Id $nic.Id -Primary
>>        }
>>        else
>>        {
>>          Add-AzVMNetworkInterface `
>>         -VM $newVM `
>>          -Id $nic.Id
>>   }

Name                     : SERVER-SQL
AvailabilitySetReference : {Id}
NetworkProfile           : {NetworkInterfaces}
StorageProfile           : {OsDisk, DataDisks}

Azure:/
PS Azure:\> # Recreate the VM
Azure:/
>>    -ResourceGroupName $resourceGroup `
>>    -VM $newVM `
WARNING: Since the VM is created using premium storage or managed disk, existing standard storage account, goallinediag189, is used for boot diagnostics.
RequestId IsSuccessStatusCode StatusCode ReasonPhrase
                         True         OK OK

Steps to reproduce or exception report
--------------------------------------

copy and paste the script from https://docs.microsoft.com/bs-cyrl-ba/azure/virtual-machines/windows/change-availability-set

changed only 

# Set variables
    $resourceGroup = "resourcegroupname"
    $vmName = "SERVER-SQL"
    $newAvailSetName = "PRODAvailabilitySet"

**Comment by msftrncs** [comment]
Didn't mention your environment ...  version of PSReadLine would be very important.  See if PSReadLine 2.0.0-beta6 resolves this issue.

**Comment by daxian-dbw** [comment]
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

The URL indicates you are using a version that is prior to 2.0.0-beta4. Please try out the 2.0.0-beta6 from the PowerShell Gallery. The issue is likely fixed.
