### ISSUE TITLE
opps something went wrong

### ISSUE THREAD

**Issue by olibra1** [PowerShell/PSReadLine#1236]
PS version: 6.2.3
PSReadline version: 2.0.0-beta3
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 6.2.3.0
HostName: ConsoleHost
BufferWidth: 105
BufferHeight: 9001

See attached. PS told me to tell you about it so I'm doing that. The error didn't seem to stop me from doing anything though. 
![20191210PSSWW0445AM](https://user-images.githubusercontent.com/51077209/70518873-1178b380-1b09-11ea-8e83-8695e30bd89f.jpg)

**Comment by daxian-dbw** [comment]
This issue has been fixed in the more recent PSReadLine versions. Please try out 2.0.0-beta6 from PowerShell Gallery.
