### ISSUE TITLE
Option to make MenuComplete show cadidates on the first tab

### ISSUE THREAD

**Issue by joonro** [PowerShell/PSReadLine#124]
Hi,

I have been using `MenuComplete` for a couple of days, and I prefer showing candidates on the first tab and highlighting the first candidate on the second tab input to doing the latter on the first tab input. 

The reason is that I found that if I have many candidates, it is quicker to identify the candidate I want and then press the next character, so I can narrow down the candidates and then use the highlighting to select the one I want. 

So it would be great to have an option for this.

Showing the list of candidates on the first tab would be convenient for `Complete` as well, since currently I have to press tab twice to do so.

Thanks again for the `MenuComplete` - it is already fantastic.

Best,
Joon

**Comment by daxian-dbw** [comment]
The implementation for filtering menu completion when user typing the next character was done, so close this one.
