### ISSUE TITLE
Set-PSReadLineOption doesn't support -ErrorAction

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#1246]
Environment data
----------------

```
PS version: 4.0
PSReadline version: 1.2
os: 6.3.9600.16384 (winblue_rtm.130821-1623)
PS file version: 6.3.9600.17396 (winblue_r4.141007-2030)
HostName: ConsoleHost
BufferWidth: 180
BufferHeight: 3000
```

Steps to reproduce or exception report
--------------------------------------
I have a number of different servers with various versions of PSReadLine installed but I'm trying to use the same configuration file. Some of the configuration items are different and I would like to ignore any errors with something like:

`Set-PSReadLineOption --ViModeIndicator Script -ViModeChangeHandler $OnViModeChange -ErrorAction SilentlyContinue`

Currently I have to wrap the call with `try {} catch {}` to quiet errors.

I realize this is PSReadLine 1.2 but `-ErrorAction` doesn't seem to be honored with `PSReadline version: 2.0.0-beta6` either.

**Comment by daxian-dbw** [comment]
With PSReadLine 1.2, the parameter binding will fail for your specified parameters/arguments.
`-ErrorAction` is for the cmdlet to determine how to handle the non-terminating errors thrown from the cmdlet, but the error you see are from the parameter binder, not from the cmdlet, so you have to use `try/catch` to quiet errors in this case.

As for in `2.0.0-beta6`, you didn't specify the exact issue, but be noted that `-ErrorAction` only covers non-terminating errors. Exceptions thrown from a cmdlet or terminating error thrown from `ThrowTerminatingError` are not affected by `-ErrorAction`.

**Comment by msftrncs** [comment]
Suggestion ...  place each option on separate executions of `Set-PSReadLineOption` so that only the ones that fail to bind will not set.   Once binding fails, no part of the command will be executed.
