### ISSUE TITLE
Set-PSReadlineKeyhandler won't take keys produced using AltGr

### ISSUE THREAD

**Issue by weq** [PowerShell/PSReadLine#1250]
Environment data
----------------

PS version: 5.1.17763.771
PSReadline version: 2.0.0-beta2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000

Steps to reproduce or exception report
--------------------------------------
On this machine I can reproduce this error on 5.1 & 6.2.3, while it works in PS7 preview 6.

I'm using a Norwegian keyboard layout and to make the character `[` we use AltGr+7 and for `{` we press AltGr+8. We can also use ctrl+alt as a substitution for the AltGr key. E.g. AltGr+7 -eq Ctrl+Alt+7.
Regardless of what symbol I use as long as the key combination requires alt+shift or alt-gr won't work as expected with `Set-PSReadlineKeyHandler`

This is the code I use to register the key, it was so "hard" to copy the code in a pretty markdown manner in here so I linked the gist and highlighted the lines instead.
https://gist.github.com/brettmillerb/e04778bb46e79217ad508d7c2272658a#file-profile-ps1-L40-L75

**Comment by daxian-dbw** [comment]
> On this machine I can reproduce this error on 5.1 & 6.2.3, while it works in PS7 preview 6.

@weq If it works in PS7 preview 6, then the issue has been fixed in a recent version of PSReadLine. Please try out 2.0.0-rc1 from PowerShell Gallery. You can install 2.0.0-rc1 PSReadLine for both 5.1 and 6.2.3
