### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by weihoo** [PowerShell/PSReadLine#1255]
上 200 个密钥:
 n s \ m s - p y t h o n . p y t h o n - 2 0 1 9 . 1 1 . 5 0 7 9 4 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e 
f a u l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 8 2 9 7 ' Space ' c : \ U s e r s \ A d m i n i s t r a t o r \ D e s k t o p \ 简 道 云 A P I 学 习 \ P y t h o n 调 用 简 道 云 获 取 字 段 
. p y ' Space Enter

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -19。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg) 
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@weihoo, you didn't provide your environment data from the script in the template, but good chances you are not using the latest, PSReadLine 2.0.0-rc1, you can get from PowerShellGallery, give it a try.
