### ISSUE TITLE
ArgumentOutOfRangeException in RevertLine after F8 then Shift-F8 after second search term was used

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PSReadLine#1257]
### Environment
PSReadLine: 2.0.0-rc1
PowerShell: 6.2.3
OS: Microsoft Windows 10.0.19536
Last 71 Keys
```
 d e s c Backspace Backspace Backspace Backspace Backspace Backspace t e s t Backspace Backspace Backspace Backspace Backspace Backspace Backspace h e l p Spacebar F8 F8 F8 F8 F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Escape Escape Escape Escape d e s c r i b e Spacebar Shift+F8 F8 F8 F8 F8 F8 F8 F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Shift+F8 Escape
```

### Exception
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Environment data
----------------
PS version: 6.2.3
PSReadline version: 2.0.0-rc1'; ProjectUri = 'https://github.com/PowerShell/PSReadLine
os: 10.0.19536.1000 (WinBuild.160101.0800)
PS file version: 6.2.3.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001

Steps to reproduce
--------------------------------------
I can get this exception to occur consistently.

1. Type a term. (I typed `help`)
2. Press <kbd>F8</kbd>, several times to move through several matches.
3. Press <kbd>Shift</kbd>-<kbd>F8</kbd> several times to revert back to the original input.
4. Press <kbd>Esc</kbd>.
5. Type another term. (I typed `describe`, from some Pester tests I had run)
6. Press <kbd>F8</kbd>, several times to move through several matches.
7. Press <kbd>Shift</kbd>-<kbd>F8</kbd> several times to revert back to the original input.

Note:  At this point, the original search term (in my case, `help`) was back on the command prompt, instead of the more recent term (`describe`).

8. Press <kbd>Esc</kbd>.

At this point the exception occurs.

In Windows Terminal, this causes the PowerShell Core tab to close completely, but in ConsoleHost it remained.

**Comment by daxian-dbw** [comment]
Submitted PR #1259 to fix this issue.

**Comment by msftrncs** [comment]
I might have missed a detail, as I focused on the exception, and was utilizing `RevertLine()` (<kbd>Esc</kbd>) between searches.  It should be noted though, that if step 4 is replaced with <kbd>Back</kbd> 4 times, the resulting behavior is still not right, though no exception is generated.    

The exception might also have something to do with the history of edits being tracked for the current line.  When I look back at the 'Last Keys', I had a lot of edits.  Running a debug version gives an assertion failure instead of the ArgumentOutOfRangeException.

```
Process terminated. Assertion failed.
Character to undo is not what it should be
   at Microsoft.PowerShell.PSConsoleReadLine.EditItemInsertChar.Undo()
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable`1 key, Object arg)
```

While the wrong behavior still happens, the exception does not seem to happen in beta2 (which keeps getting loaded in Windows PowerShell after an Insiders Update).

**Comment by daxian-dbw** [comment]
One more issue with history operation:

1. `Set-PSReadLineKeyHandler -Key F3 -Function EndOfHistory`
2. type a term (e.g. `git`)
3. type <kbd>F3</kbd> (the line will be cleared)
4. typing any character (e.g. `a`) will raise an exception.

```
### Exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.RemoveEditsAfterUndo()
   at Microsoft.PowerShell.PSConsoleReadLine.SaveEditItem(EditItem editItem)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by msftrncs** [comment]
What puzzles me a little, is that if `_savedCurrentLine` isn't being restored correctly when the wrong command line is restored, because if it was completely restored, then the edit information there in contained should be the correct edit information for the command line that was restored, and it should be impossible to get an exception...   Maybe `_savedCurrentLine.edits` is not actually a copy of the edits at the time of saved, but actually a reference to the current edits?

That is it ..  `.edits` is a `List<EditItems>` and that would only be a reference.  So later when the `_savedCurrentLine.CommandLine` is restored (but it is the wrong one), the `_savedCurrentLine.edits` is more updated than the `_savedCurrentLine.CommandLine`, and so any attempt to undo the edits will be making incorrect undo operations.

I think `SaveCurrentLine` might need to clone the `.edits` list??

**Comment by daxian-dbw** [comment]
> I think `SaveCurrentLine` might need to clone the .edits list??

I chose to clone the edits when restoring the save current line, at the following place.
The idea is that most of time we won't go back to the save line, so cloning in `SaveCurrentLine` may cause more wasted allocations.

Actually, on a second thought, cloning `_edits` in `SaveCurrentLine` won't help. We have to clone when restoring the saved current line, because otherwise the `_edits` and `_savedCurrentLine._edits` will again refer to the same `List` instance after restoring, which will be used by the subsequent editing.

https://github.com/PowerShell/PSReadLine/blob/d648aed6da66e2c3947e71825fbc8e7009a30c3d/PSReadLine/History.cs#L469-L474
