### ISSUE TITLE
Line continuation with line-initial | (pipe symbol) not recognized on Unix-like platforms.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PSReadLine#1261]
PS Core now supports continuing a pipeline by placing the `|` at the start of the following line.

On _Windows_ pasting such a pipeline works fine, but not on Unix-like platforms (macOS, Linux).

Environment data
----------------

```none
PS version: 7.0.0-rc.1
PSReadline version: 2.0.0-rc1
os: Darwin MkiMac.home 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 180
BufferHeight: 60
```

Steps to reproduce or exception report
--------------------------------------

**On macOS or Linux**, paste the following in a PowerShell terminal:

```
Get-Date
  | % ToUniversalTime
```

This works fine on Windows, but on Unix-like platforms the 2nd line is unexpectedly treated as a _new_ command, which predictably fails:

```none
ParserError:
Line |
   1 |   | % ToUniversalTime
     |   ^ An empty pipe element is not allowed.
```

**Comment by mklement0** [comment]
Sorry, @lzybkr, I accidentally submitted this without content first - the report is now complete.

**Comment by msftrncs** [comment]
This is, actually related to certain terminals, and so can be reproduced on Windows as well if not using ConsoleHost (VS Code's terminal is a prime suspect), and it has to do with whether the paste operation is performed by the terminal, or handled directly by PSReadLine.

I think @lzybkr or @daxian-dbw might be looking in to a solution, related to the speed at which input characters are arriving for processing, and using that as a signal that the terminal is 'pasting'.

This is then, effectively, a duplicate to #579.  Pasting on 'nix is equivalent to right-click pasting on Windows.

**Comment by mklement0** [comment]
Thanks, @msftrncs - I keep forgetting about #579; indeed sounds like I've created another duplicate, so I'm closing this.
