### ISSUE TITLE
Cursor misplacement: cursor jumps to buffer

### ISSUE THREAD

**Issue by he852100** [PowerShell/PSReadLine#1269]
光标会不定期跳到缓冲区内，这是经常发生的事情。估计因为改变窗口大小触发的故障，看起来与psreadline有关。因为禁用psreadline时，没有发生过此问题。
我使用的[Termux for android](https://wiki.termux.com/wiki/Main_Page)控制台.安装了[Aarch](https://wiki.termux.com/wiki/Aarch), [Fedora](https://wiki.termux.com/wiki/Fedora)。故障相同。

> The cursor can be often misplaced, which could be caused by the resizing of the window when the input-pad becomes active/inactive.
It's very possible related to `PSReadLine` as it works fine when `PSReadLine` is unloaded.
>
> This happens in [Termux](https://wiki.termux.com/wiki/Main_Page), an Android terminal emulator and Linux environment application.
[Aarch](https://wiki.termux.com/wiki/Aarch), [Fedora](https://wiki.termux.com/wiki/Fedora) are installed.

https://github.com/SDRausty/TermuxArch/issues/201
Related issue: #1164

![Screenshot_20191231_161537](https://user-images.githubusercontent.com/26913892/71614838-fde0da00-2be8-11ea-8781-c9da76f1ef9b.jpg)

![Screenshot_20191231_164529](https://user-images.githubusercontent.com/26913892/71615624-1226d600-2bed-11ea-92b1-f925dcd7b058.jpg)

**Comment by msftrncs** [comment]
Can you run the script contained in the issue template in this instance of PowerShell?  I think it would be good to include the output of the script here.  A screen-shot of the output would be fine.

**Comment by he852100** [comment]
![Screenshot_20191227-151354](https://user-images.githubusercontent.com/26913892/71506423-cfe35900-28bb-11ea-8191-04175a71135a.png)
![Screenshot_20191227-151431](https://user-images.githubusercontent.com/26913892/71506424-cfe35900-28bb-11ea-9f8a-235112959ff8.png)
![Screenshot_20191227-151453](https://user-images.githubusercontent.com/26913892/71506425-d07bef80-28bb-11ea-8287-a0619e9b8a26.png)
![Screenshot_20191227-151520](https://user-images.githubusercontent.com/26913892/71506426-d1148600-28bb-11ea-8dc0-ba1d316e4a99.png)

**Comment by daxian-dbw** [comment]
@he852100 The stack trace shown in your screenshot doesn't look like related to PSReadLine. It's a NullReferenceException in PowerShell remoting code. If that's the case, you should report the issue in the [PowerShell repo](https://github.com/powershell/powershell) instead.

**Comment by he852100** [comment]
@daxian-dbw 输入字符时光标跳到了缓冲区。这也是他们的问题吗？可是当我禁用psreadline后没有出现这种问题。

**Comment by daxian-dbw** [comment]
@he852100 Given the screenshot full of exception stack trace, it was not clear to me what exact is the issue you were reporting. It would be helpful if you can edit https://github.com/PowerShell/PSReadLine/issues/1269#issue-542530833 to better describe the issue.

I don't have the device to reproduce the issue, but my guess is that the console window gets resized when the on-screen keyboard is activated. Resizing the console window could cause the cursor to be misplaced.

**Comment by daxian-dbw** [comment]
@he852100 This is the first time I learnt that PowerShell gets used in a Android terminal emulator, very interesting :)
In SDRausty/TermuxArch#201, you mentioned that the misplacement of cursor also happened without using `pwsh`, and reply was that https://github.com/termux/termux-app/pull/1390 might resolve the issue. Have you tried out the fix? Is the cursor misplacement gone with that fix when not using `pwsh`?

**Comment by he852100** [comment]
@daxian-dbw This seems to be a problem specific to `pwsh`,When using `pwsh`, the fault occurs continuously.Use `bash` and`zsh`everything is fine.

[1390][1] provides a way to clear the buffer,I don't think they're directly connected。


[1]:https://github.com/termux/termux-app/pull/1390

**Comment by he852100** [comment]
Progress bar,

![20200104_024253](https://user-images.githubusercontent.com/26913892/71744432-33641c80-2ea2-11ea-9dee-8a243e80d1e6.gif)

![20200104_025334](https://user-images.githubusercontent.com/26913892/71744460-44ad2900-2ea2-11ea-9709-f4c68026e30f.gif)

**Comment by StevenBucher98** [comment]
Closing to track in #3637
