### ISSUE TITLE
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。

### ISSUE THREAD

**Issue by ggi2003** [PowerShell/PSReadLine#1272]
PS F:\Tools\SpringCloud+Vue项目实战\整套系统全部资料\微服务后端系统开发所有资料\微服务后端项目全部资料\配套软件\jenkins> docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                               NAMES
ac10eb685b37        jenkins/jenkins:lts   "/sbin/tini -- /usr/…"   7 days ago          Up 58 minutes       50000/tcp, 0.0.0.0:8081->8080/tcp   ggi_jenkins
PS F:\Tools\SpringCloud+Vue项目实战\整套系统全部资料\微服务后端系统开发所有资料\微服务后端项目全部资料\配套软件\jenkins> d
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 78 个密钥:
 d o c k e r Space c p Space . \ c l o u d b e e s - f o l d e r . h p i Space g g i _ j e n k i n s : / v a r / j e n k i n s _ h o m e / p l u g i n s / Enter
 UpArrow Enter
 d o d o

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: left
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS F:\Tools\SpringCloud+Vue项目实战\整套系统全部资料\微服务后端系统开发所有资料\微服务后端项目全部资料\配套软件\jenkins>

**Comment by daxian-dbw** [comment]
@ggi2003 The issue has been fixed in newer versions of PSReadLine. Please try out 2.0.0-rc1 from PowerShell Gallery.
