### ISSUE TITLE
Ran a python script fine the 1st time, subsequent times I get this... but then it works.

### ISSUE THREAD

**Issue by mistwire** [PowerShell/PSReadLine#1274]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
Try to run any python program twice. The 1st time it works fine, the second (and any other times until you restart vscode) it does this. Note that eventually the program still runs.

**Comment by daxian-dbw** [comment]
@mistwire The description of the issue is missing. Please edit the issue to add the necessary information. Also, make sure the environment data is provided.
