### ISSUE TITLE
Ctrl+) Key Handler does not work properly

### ISSUE THREAD

**Issue by veleek** [PowerShell/PSReadLine#129]
I would like to create custom key handlers for `Ctrl+(` and `Ctrl+)` but it appears as though the right bracket does not work properly.

I have setup the bindings as so:

`Set-PSReadlineKeyHandler -Chord "Ctrl+Shift+9", "Ctrl+Shift+0"`

And just have a test function that dumps some output to the buffer.  `Ctrl+(` works fine but `Ctrl+)` does nothing.  `Ctrl+0` also appears to work fine.

**Comment by veleek** [comment]
I realize that this is a bit old, but I was trying to clear out some old e-mail and decided to take a look at this.  There appears to be some issues with using Ctrl+Shift+0 as a shortcut key because it's bound by default to the IME Switch Input Language command (https://support.microsoft.com/en-us/kb/967893).  According to this (and a few other internet sources) if you just disable the key bindings in the keyboard settings then it will work properly.  I've already done this and I'm STILL having the same issue however.

Would anyone be willing to try and reproduce this?  I'm on Windows 10, but would be interested in results on other versions.
1. Open up the Language control panel (the legacy one, not the modern one).
2. Click **Advanced Settings** in the left column.
3. Click **Change language bar hot keys** is the _Switching input methods_ section
4. Disable all the hotkeys.
5. Open up powershell and run `[Console]::ReadKey()`. _This should pause for user input_
6. Press `Ctrl+Shift+0` and see if it returns.

I dug into it a bit further, and it looks like for whatever reason the KeyDown event of Ctrl+Alt+0 is not returned by the P/Invoke call to `ReadConsoleInput`.  Only the KeyUp event, and ReadKey only returns on KeyDown events.  If I use some other tool (i.e. AutoHotkey) I can see that the keydown event is actually occurring, but it just doesn't appear to make it to C#.  So this could be an underlying problem with the CLR or Windows or something.

**Comment by veleek** [comment]
According to this post, this may just be a Windows 8+ issue: https://answers.microsoft.com/en-us/windows/forum/games_windows_10/ctrlshift0-in-windows-10/337b6542-4159-4143-83a8-a4496f8f995c?auth=1&rtAction=1463376311366&lc=1033

I believe I was on Windows 8 when I first tried to use PSReadLine.

**Comment by lzybkr** [comment]
Now that PowerShell is cross platform, I tried out `Ctrl+(` and `Ctrl+)` on Linux and found that those keys are indistinguishable from `(` and `)` - this was verified by running `showkeys -a` which shows the bytes a console program like PowerShell (via the CLR's console apis) would see.

Because of this, I don't think it makes sense to add this so am closing the issue. It would require a lot of Windows specific code and would only enable a scenario that can't work on Linux, at least not in some common scenarios.
