### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by what-is-code** [PowerShell/PSReadLine#1292]
Environment data
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 136
BufferHeight: 37
----------------

Steps to reproduce or exception report

--------------------------------------
上 200 个密钥:
 _ 1 0 1 \ b i n \ j a v a ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ z h a n g m i n g b o \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ b c f 1 b 1 5 3 c 8 e 8 5 f 8 c 7 9 9 9 e 3 3 3 f d e f a 1 c 8 \ r e d h a t . j a v a \ j d t _ w s \ j d t . l s - j a v a - p r o j e c t \ b i n ' Space ' H o m e W o r k 2 ' Space Enter

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
@what-is-code the issue was fixed in the more recent versions of PSReadLine. Please try out the `2.0.0-rc1` version from the PowerShell Gallery.
