### ISSUE TITLE
'ArgumentOutOfRangeException' issues were fixed in recent versions

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PSReadLine#1306]
Quite a few fixes were made to address the various issues related to the `ArgumentOutOfRangeException` thrown from `PSReadLine`.
The exception usually has a stack trace that looks like one of the followings.

If you run into a similar issue, please try out the latest version of `PSReadLine` from [PowerShell Gallery](https://www.powershellgallery.com/packages?q=PSReadLine).
You may find the [Installation and Upgrading instructions](https://github.com/PowerShell/PSReadLine#installation) helpful.

```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -7.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   ...
```
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 9001.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu, Boolean menuSelect)
   ...
```
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 9001.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   ...
```

The PRs that fixed those issues are: 
#979, #967  -- these 2 PRs fixed most of the `ArgumentOutOfRangeException` thrown from `ReallyRender`.
#984, #1182, #1206 -- they fixed the exception thrown in other scenarios.

Here is an in-complete list of the closed duplicate issues related to the `ArgumentOutOfRangeException`:
https://github.com/powershell/psreadline/issues?q=is%3Aissue+label%3AOutOfRange+is%3Aclosed

**Comment by DHowett-MSFT** [comment]
Would it be possible to link some of that work? As an API provider (on the console side) I'd like to understand if there's some learnings I can take back to my team. :smile:

**Comment by daxian-dbw** [comment]
@DHowett-MSFT Sure, I just added links to those related PRs in the issue description. Hope that helps!

**Comment by DHowett-MSFT** [comment]
Thanks!

**Comment by nu8** [comment]
https://github.com/PowerShell/PSReadLine/issues/1611

**Comment by bstrobel** [comment]
Just to let you know, the issue is fixed for me. I use the default PS version on Win10 Professional and executed the following command (in cmd) to upgrade PSReadLine:
powershell -noprofile -command "Install-Module PSReadLine -Force -SkipPublisherCheck -AllowPrerelease"

Thanks for fixing it!

**Comment by Backist** [comment]
When I was running a Python script using the debugger in the VSCode Python Extension, I got the following error:

```
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 4 claves:
 Ctrl+c UpArrow Enter
 Ctrl+l

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: top
Valor actual -22.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

```

**Comment by publicmessages** [comment]
adding here just for sake of completeness

saw an exception in Windows Terminal Powershell (not core)

```text
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 1977ms.
PS C:\Users\[redacted]>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -4.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\[redacted]> date

Thursday, August 11, 2022 10:08:17 AM

```

**Comment by daxian-dbw** [comment]
@Backist and @publicmessages The URL _"https://github.com/lzybkr/PSReadLine/issues/new"_ shown in the exception you saw indicates that you are using a very old version of PSReadLine (prior to 2.0.0-beta2). Please upgrade to the latest version https://www.powershellgallery.com/packages/PSReadLine/2.2.6.

**Comment by dbrgn** [comment]
Just wondering, almost 3 years later: I installed a new Windows 10 machine, which has PowerShell preinstalled, but that ships with this outdated version of PSReadLine. Wouldn't it be possible to somehow ship an updated version of PSReadLine with Windows Update, to ensure that a freshly installed and fully updated system doesn't have a 3 years old buggy version of a PowerShell module which explicitly asks the users to open an issue for a long-fixed bug? (From looking through the issue tracker, it seems that it would be a good thing for the project maintainer as well 🙃)
