### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by yuriy-poret** [PowerShell/PSReadLine#1311]
1. Start Windows PowerShell.
2. Shift+Enter.
3. Error!

ScreenShot:
![2020-01-23 19 03 21](https://user-images.githubusercontent.com/56883857/73001313-4e77db80-3e13-11ea-9881-689b39506a4a.png)

**Comment by daxian-dbw** [comment]
This issue has been fixed. Please try out the latest version from PowerShell Gallery.
