### ISSUE TITLE
Get-PSReadLineKeyHandler not working

### ISSUE THREAD

**Issue by dj-Query** [PowerShell/PSReadLine#1312]
## Environment

```none
PS version: 6.2.3
PSReadline version: 2.0.0-beta3
os: 10.0.18362.650 (WinBuild.160101.0800)
PS file version: 6.2.3.0
HostName: ConsoleHost
BufferWidth: 117
BufferHeight: 9001
```

## Exception report
```
Get-PSReadLineKeyHandler : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineKeyHandler
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineKeyHandler], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetKeyHandlerCommand
```
## Steps to reproduce
1. open powershell
2. write command
   > Get-PSReadLineKeyHandler

## Expected behavior

This command returns all key mappings, bound and unbound. [docs](https://docs.microsoft.com/en-gb/previous-versions/powershell/module/psreadline/Get-PSReadLineKeyHandler?view=powershell-5.0#examples)

**Comment by daxian-dbw** [comment]
I cannot repro this issue. Please try out the latest version `2.0.0-rc2` from the PowerShell Gallery.
