### ISSUE TITLE
Terminal doesn't read my code

### ISSUE THREAD

**Issue by augustomagno** [PowerShell/PSReadLine#1321]
I wirte a code to calculate the sum for a n number of digits, but the terminal try to run my code e show a message saying that something gone wrong. I try to run the code with thw windows prompt and it works. i've send the code as attchment

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
- You file an issue that has many duplicates;
- You file an issue completely blank in the body.
```
