### ISSUE TITLE
Error from within dbatools function

### ISSUE THREAD

**Issue by olegstrutinskii** [PowerShell/PSReadLine#1328]
## Environment

```none
PS version: 6.2.3
PSReadline version: 2.0.0-beta3
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 6.2.3.0
HostName: ConsoleHost
BufferWidth: 237
BufferHeight: 9001
```

## Exception report

-----------------------------------------------------------------------
Last 200 Keys:
```
 \ D A T A Space - R e s t Tab Tab Space _ c u r r e n t _ LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Backspace Backspace c RightArrow LeftArrow LeftArrow RightArrow LeftArrow r Backspace t e s t + Backspace _ RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Space - D e s t Tab Tab Space t e s t _ c u r r e n t _ Enter
 Ы у е - В и ф В и Щ ц т у к Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace S e t - D b a D B R e c Tab Space - Tab Space s r v - s q l - Backspace 0 5 Space - D a t a Tab Space Tab Tab Tab Tab Tab Tab Tab Tab Tab c u Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace PageUp Backspace Backspace Backspace
```

Exception:
```
System.IO.IOException: The parameter is incorrect
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

## Steps to reproduce

1. Load PS module [dbatools](https://github.com/sqlcollaborative/dbatools)
2. Type - Get-DbaDatabase <sqlservername> -Database <PressTabHere>

<PressTabHere> is the place where we want to get autocomplete to help us get database name from server <sqlservername>.

## Expected behavior

Nothing, or get <databasename> from dbatools autocomplete feauture

## Actual behavior

Got error.

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
This issue will be closed because you didn't follow the bug report template to provide **environment data** and **repro steps**.
You can update your issue description and re-open the issue afterwards.
Also, please try out the latest version of PSReadLine from PowerShell Gallery, tons of issues have been fixed in recent versions.

**Comment by daxian-dbw** [comment]
Thanks for updating the issue description with the necessary information.

The exception stack frame `ScrollDisplayUp` indicates this happens when `PageUp` was pressed which caused this exception to happen, not tab completion.
See https://github.com/PowerShell/PSReadLine/issues/551#issuecomment-341856386:

> I've reviewed PSReadLine and the .Net api that is used and this seems like an impossible condition. The .Net api Console.SetWindowsPosition validates the parameters before calling the Win32 api, yet it's the Win32 api reporting the error.
>
> As this was not reproducible, I'll chalk this up to some random corruption in conhost - it wouldn't be the first transient error like this that I've seen.
>
>Sorry I can't do anything about it, but thanks for reporting it.
