### ISSUE TITLE
Cannot cross window height

### ISSUE THREAD

**Issue by he852100** [PowerShell/PSReadLine#1330]
## Environment

```none
[run the script below and paste the output here]
```

## Actual behavior

![20200202_023907](https://user-images.githubusercontent.com/26913892/73597403-9363e680-4566-11ea-905f-044a57254978.gif)

![20200202_024006](https://user-images.githubusercontent.com/26913892/73597410-a8d91080-4566-11ea-8f93-06d59846d4d6.gif)
![20200202_024114](https://user-images.githubusercontent.com/26913892/73597416-babab380-4566-11ea-831b-a2d09ce810e2.gif)

```
PSVersion                      7.0.0-rc.2                                     PSEdition                      Core                                           GitCommitId                    7.0.0-rc.2
OS                             Linux 4.9.112-perf #1 SMP PREEMPT Mon Jan 7 1…
Platform                       Unix                                           PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3                                            SerializationVersion           1.1.0.1                                        WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
This is by design. PSReadLine is not an editor and it does't have its own buffer. Once the text was scrolled up off the terminal buffer, you won't be able to move the cursor there.
