### ISSUE TITLE
Windows Powershell "Oops, something went wrong." when trying to open Notepad

### ISSUE THREAD

**Issue by ErikaJZhou** [PowerShell/PSReadLine#1331]
When attempting to open Notepad from Windows Powershell an error occurred after typing the " character.
Computer has Windows 10, Version 1903 (OS Build 18362.239).

PS C:\Users\Erika Zhou\OneDrive - University of Missouri\Spring Semester 2020\CS 2050 Algorithm Design & Programming II> notepad

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 i r Space p r e l a b 2 Enter
 m v Space e r i k a z h o u 0 1 A - p r e l a b 2 . c , Space e r i k a z h o u 0 1 A - p r e l a b 2 _ e x t e n s i o n . c Space p r e l a b 2 Enter
 d i r Enter
 m k Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c d Space p r e l a b 2 Enter
 d i r Enter
 c d Space . . Enter
 d i r Enter
 c d Space p r e l a b 3 Enter
 d i r Enter
 . / a . e x e Enter
 c o d e Enter
 c d Space . . Enter
 c d Space . . Enter
 n o t e p a d Space Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace n o t e p a d Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

Opening Notepad from PowerShell worked fine after that occurrence, though. (I did realize the file I wanted to open was in another directory and moved the file before trying again :P)

PS C:\Users\Erika Zhou\OneDrive - University of Missouri\Spring Semester 2020\CS 2050 Algorithm Design & Programming II> notepad "CS2050 README"

Version information:
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by daxian-dbw** [comment]
Please check out the pinned issue #1306

**Comment by ErikaJZhou** [comment]
Thank you for your response! Sorry for taking up your time.
Please have a nice day,
- ErikaJZhou
