### ISSUE TITLE
Prevent invalid commands from entering history

### ISSUE THREAD

**Issue by gogsbread** [PowerShell/PSReadLine#1332]
Trying to prevent invalid commands from being inserted into history file to avoid clutter.
Been playing around with some options involving `ValidateAndAcceptLine` `CommandValidationHandler` etc, but none seem to work the way that I wanted.
Is there a standard pattern(command\code recipe ..) to prevent wrong commands from being inserted into history?

**Comment by lzybkr** [comment]
Can you elaborate? The default for `ValidateAndAcceptLine` doesn't add anything to history if a command is not found:

![image](https://user-images.githubusercontent.com/2148248/73677474-2c7c2580-466b-11ea-80de-9918bcc2b5b6.png)
