### ISSUE TITLE
出现问题

### ISSUE THREAD

**Issue by small-pony** [PowerShell/PSReadLine#1333]
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 200 个密钥:
 p t s " : Space { Enter
 Space Space Space Space " t e s t " : Space " e c h o Space \ " E r r o r : Space n o Space t e s t Space s p e c 
i f i e d \ " Space & & Space e x i t Space 1 " , Enter
 Space Space Space Space " b u i l d " : " n o d e Space / t o o l s / b u i l d . j s " Enter
 Space Space } , Enter
 Space Space " d e v D e p e n d e n c i e s " : Space { Enter
 Space Space Space Space " w e b p a c k " : Space " ^ 4 . 4 1 . 5 " Enter
 Space Space } , Enter
 Space Space " a u t h o r " : Space " 马 若 冲 " , Enter
 Space Space " l i c e n s e " : Space " I S C " Enter
 } Enter

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -4。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean 
ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
Please checkout the pinned issue #1306
