### ISSUE TITLE
Encountered SystemIOException

### ISSUE THREAD

**Issue by updixit** [PowerShell/PSReadLine#1341]
Last 97 Keys:
 Ctrl+r d e p o Enter
 Ctrl+r g e t - a l Enter
 Enter
 Enter
 Enter
 Ctrl+r g e t - e s c RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Backspace n o d e a t t r s ? Delete Enter
 UpArrow Space - R Tab Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow PageUp PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

![image](https://user-images.githubusercontent.com/26333155/74007074-5450df00-4932-11ea-9d28-b1ae292b7219.png)

**Comment by jeannot49** [comment]
Hello,

I'm facing exactly the same issue, I'm using Windows 10 1809.

I can't even write anything into the console.

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the reported exception, see https://github.com/PowerShell/PSReadLine/issues/551#issuecomment-341856386. Quoted below:

> I've reviewed PSReadLine and the .Net api that is used and this seems like an impossible condition. The .Net api Console.SetWindowsPosition validates the parameters before calling the Win32 api, yet it's the Win32 api reporting the error.
>
> As this was not reproducible, I'll chalk this up to some random corruption in conhost - it wouldn't be the first transient error like this that I've seen.
>
>Sorry I can't do anything about it, but thanks for reporting it.
