### ISSUE TITLE
 i reported  of this error indicating the details that do you have next

### ISSUE THREAD

**Issue by Maxaterneth** [PowerShell/PSReadLine#1342]
last 200 keys 
3 8 - 3 2 Ctrl+Alt+\ p y t h o n . e x e ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ m a x i m Ctrl+Alt+\ . v s c o d e Ctrl+Alt+\ e x t 
e n s i o n s Ctrl+Alt+\ m s - p y 
t h o n . p y t h o n - 2 0 2 0 . 1 . 5 8 0 3 8 Ctrl+Alt+\ p y t h o n F i l e s Ctrl+Alt+\ l i b Ctrl+Alt+\ p y t h o n Ctrl+Alt+\ n e w _ 
p t v s d Ctrl+Alt+\ n o _ w h e e 
l s Ctrl+Alt+\ p t v s d Ctrl+Alt+\ l a u n c h e r ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ m a x i m Ctrl+Alt+\ O n e D r i v e Ctrl+Alt+\ D o c u m e n t o s Ctrl+Alt+\ P y t h o n Ctrl+Alt+\ a l e a t 
o r i o . p y ' Space Enter       

Excepción:
System.ArgumentOutOfRangeException:
The value must be greater than or equal to zero and less than the console buffer size in that dimension. Parameter name: top
Current value -3.
System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object 
arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the exception you reported, please checkout the pinned issue #1306
