### ISSUE TITLE
error ctrl+v

### ISSUE THREAD

**Issue by Py3uk** [PowerShell/PSReadLine#1348]
-----------------------------------------------------------------------
Последние клавиши 1:
 Ctrl+v

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было -1.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the exception you report here, check out the pinned issue #1306
