### ISSUE TITLE
Ctrl-L doesn't clear screen, prints error instead.

### ISSUE THREAD

**Issue by paulhazen** [PowerShell/PSReadLine#1351]
<pre>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 5 / l a b 5 / Tab Enter
 g i t Space a d d Space . \ w e e k 5 \ l a b e Backspace Escape c d Space w e e k 5 \ l ; a b Backspace Backspace Backspace a b 5 Enter
 l s Enter
 g i t Space a d d Space d r i v e r . c p p Enter
 g i t Space a d d Space L i s t . c p p Enter
 g i t Space a d d Space L i s t . h Enter
 Ctrl+l Ctrl+l Ctrl+l c l s Enter
 UpArrow UpArrow UpArrow Escape l s Enter
 g i t Space a d d Backspace Backspace Backspace s t a t u s Enter
 g i t Space a d d Space D o x y f i l e . t x t Enter
 g i t Space a d d Space o u t p u t - a l l . t x t Enter
 g i t Space a d d Space m y Backspace Backspace Backspace Backspace Enter
 c l s Enter
 Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
</pre>

**Comment by iSazonov** [comment]
@paulhazen Please use _Issue template_ to report.

> The maintainer may close your issue without further explanation or engagement if:
>- You delete this entire template and go your own path;
>- You file an issue that has many duplicates;
>- You file an issue completely blank in the body.

**Comment by daxian-dbw** [comment]
Please follow the issue template for the next report. Also, check out the pinned issue #1315
