### ISSUE TITLE
PWSH is crashed after killing subprocess

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PSReadLine#1354]
## Environment

```none
PS version: 7.0.0-preview.6
PSReadline version: 2.0.0
os: 10.0.17763.701 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001

```

## Exception report

![image](https://user-images.githubusercontent.com/22290914/74530363-a655be00-4f4b-11ea-86c4-a1dc2a561bcf.png)

## Steps to reproduce

1. Run on Windows:
```powershell
$a=[System.Diagnostics.process]::Start("cmd.exe")
```
2. Open TaskManager and find two cmd.exe processes created on previous step
3. Kill any cmd.exe in Task Manager

## Expected behavior

PowerShell continues to work.

## Actual behavior

PowerShell windows is closed.

**Comment by daxian-dbw** [comment]
Related to #1044, but not exactly the same.
Both process are competing reading input from stdin.
Also related to https://github.com/PowerShell/PowerShell/issues/11215, see my comments https://github.com/PowerShell/PowerShell/issues/11215#issuecomment-567249629

**Comment by daxian-dbw** [comment]
> PS version: 7.0.0-preview.6

☝️ Man, you should use rc.2 😄

**Comment by iSazonov** [comment]
I should add that no crash occurs while I type anything in console.
> Both process are competing reading input from stdin.

I guess console detach event causes the issue.
