### ISSUE TITLE
Large text assignment error when scrolling command history

### ISSUE THREAD

**Issue by knarfalingus** [PowerShell/PSReadLine#1357]
in console window, typed $s = then enter then @'

pasted block with 102 lines of text

then on new line typed `@ then enter

then when scrolling up through command history get :

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 o r Space t h i s Space s e s s i o n Enter
 Enter
 & Space $ p r o f i l e Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 ' @ Enter
 s r t Backspace Backspace e t - c o n t e n t s Space f . p s 1 Space - v a u l e Backspace Backspace Backspace l u e S
pace $ # LeftArrow Delete s Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow L
eftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Delete Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow DownArrow DownArrow Escape m Backspace c o p y - i t e m Space f . p s 1 Space C : \ i n e t p u b \ w w w r o
o t \ f i l e s \ i n s t a l l - v i - e d i t o r / p s Backspace Backspace Backspace . p s 1 Space LeftArrow . c s s
Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer s
ize in that dimension.
Parameter name: top
Actual value was -64.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by knarfalingus** [comment]
Name             : ConsoleHost
Version          : 5.1.18362.145
InstanceId       : ce0c4d1a-b8d6-4d35-9a4e-748f73eabfa3
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace


OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

**Comment by iSazonov** [comment]
Do you see #1306?

**Comment by daxian-dbw** [comment]
Check out the pinned issue #1306
