### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by hsbanga** [PowerShell/PSReadLine#1359]
Last 200 Keys:
 . 5 " , Enter
 Space Space Space Space " n i g h t w a t c h " : Space " ^ 0 . 9 . 2 1 " , Enter
 Space Space Space Space " n i g h t w a t c h - h t m l - r e p o r t e r " : Space " 2 . 0 . 0 " , Enter
 Space Space Space Space " r e q u e s t " : Space " ^ 2 . 6 7 . 0 " , Enter
 Space Space Space Space " s u p e r t e s t " : Space " ^ 1 . 0 . 1 " , Enter
 Space Space Space Space " t w i l i o " : Space " ^ 2 . 1 1 . 1 " , Enter
 Space Space Space Space " u n d e r s c o r e " : Space " 1 . 8 . 3 " , Enter
 Space Space Space Space " u r l " : Space " ^ 0 . 1 1 . 0 "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\HarjinderSinghBanga\Downloads\automation-hub-microservices> "assert": "^1.5.0",
>>     "chai": "^3.5.0",
>>     "chance": "^0.7.7",
>>     "cheerio": "^1.0.0-rc.3",
>>     "debug": "~2.2.0",
>>     "fs": "0.0.2",
>>     "googleapis": "^17.1.0",
>>     "http": "0.0.0",
>>     "https": "^1.0.0",
>>     "mailazy": "^1.0.23",
>>     "mocha": "^2.2.5",
>>     "nightwatch": "^0.9.21",
>>     "nightwatch-html-reporter": "2.0.0",
>>     "request": "^2.67.0",
>>     "supertest": "^1.0.1",
>>     "twilio": "^2.11.1",
>>     "underscore": "1.8.3",
>>     "url": "^0.11.0"

**Comment by iSazonov** [comment]
@hsbanga See https://github.com/PowerShell/PSReadLine/issues/1306

**Comment by hsbanga** [comment]
@iSazonov I just tried to install the URL package and it shows me the message

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

For this one, as @iSazonov commented, please see the pinned issue #1306
You can upgrade `PSReadLine` by following the instructions here: https://github.com/PowerShell/PSReadLine#upgrading

**Comment by Backist** [comment]
When I was running a Python script using the debugger in the VSCode Python Extension, I got the following error:

```
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 4 claves:
 Ctrl+c UpArrow Enter
 Ctrl+l

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: top
Valor actual -22.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

```
