### ISSUE TITLE
PowerShell Intellisense dropdown in Microsoft Terminal

### ISSUE THREAD

**Issue by Ayanmullick** [PowerShell/PSReadLine#1362]
## Description of the new feature/enhancement

Could an [SQLCLI-like terminal intellisense dropdown](https://cloudblogs.microsoft.com/sqlserver/2017/12/12/try-mssql-cli-a-new-interactive-command-line-tool-for-sql-server/) be enabled for PowerShell in the new Microsoft Terminal thru PSReadline?

![Image of Yaktocat](https://cloudblogs.microsoft.com/uploads/prod/2017/12/mssql-cli-autocomplete.gif)
## Proposed technical implementation details (optional)

Working on the terminal with PowerShell 7 could become more convenient if one was able to see all the potential matches for one's cmdlets and parameter values in a dropdown right in the terminal.

![image](https://i.imgur.com/5AFMukh.gif)

Creating issue as discussed during community call.
https://github.com/PowerShell/PowerShell-RFC/issues/242#issuecomment-589230728

**Comment by lzybkr** [comment]
See https://github.com/microsoft/terminal/issues/3121

**Comment by Ayanmullick** [comment]
> See [microsoft/terminal#3121](https://github.com/microsoft/terminal/issues/3121)

@DHowett-MSFT , a member of the Microsoft Terminal product group, had explained that [this needs to be enabled at the PowerShell level](https://github.com/microsoft/terminal/issues/4436) by the PowerShell team and not at the Terminal level.

**Comment by lzybkr** [comment]
@Ayanmullick - right - the shell must do something to invoke some UI.

The UI could be implemented 100% by the shell  - [PowerTab](https://github.com/jasonmarcher/PowerTab) was popular for an experience close to what you're suggesting.

Alternatively, the terminal could provide a UI that the shell invokes which is what I understand something some terminals provide or are considering providing.

**Comment by Ayanmullick** [comment]
@lzybkr , Right and PowerTab errors out on VSC and on MSTerminal.

**Comment by Ayanmullick** [comment]
Even AzCLI has an [interactive mode](https://docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?view=azure-cli-latest) that works on the cloudshell too.

**Comment by lzybkr** [comment]
@Ayanmullick - have you tried `MenuComplete`? It is a different experience than the examples you've raised, but it is an interactive experience showing help and filtering.

The default key binding <kbd>Ctrl+Spacebar</kbd> doesn't work in Windows Terminal, but you can bind it to another key.

**Comment by Ayanmullick** [comment]
@lzybkr , I tried it. I prefer the more fluid experiences in the screenshot above to the `Ctrl+Spacebar` experience. However, since most of my work is with the Az modules the Az predictor somewhat fills that gap. I wish there was a predictor for the MSGraph modules too.

**Comment by StevenBucher98** [comment]
A lot of this is addressed with the latest preview of Windows Terminal, https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-19-release/

**Comment by Ayanmullick** [comment]
Yes, the `Suggestions UI` and [`Shell Completion Menu`](https://github.com/microsoft/terminal/wiki/Experimental-Shell-Completion-Menu) look promising. That's what I was looking for. Does it work with Azure resources, too, like in the screen clip above, @StevenBucher98?

**Comment by StevenBucher98** [comment]
I do not believe so, I think it just uses tab completion for the suggestions and not sure if Az does tab completions for that.

cc @dcaro
