### ISSUE TITLE
why ?

### ISSUE THREAD

**Issue by faysalfadelm** [PowerShell/PSReadLine#1363]
![image](https://user-images.githubusercontent.com/61302422/75000442-e9a2b600-5490-11ea-8d75-78f303c23ede.png)

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PSReadLine/issues/1306

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

For this one, as @iSazonov commented, please see the pinned issue #1306
