### ISSUE TITLE
Error Report Caused by Command Ctrl+L  from PowerShell

### ISSUE THREAD

**Issue by Ucag** [PowerShell/PSReadLine#1364]
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 200 个密钥:
 l s Enter
 f a Backspace Backspace f a Backspace Backspace c d Space s Tab a Tab a a Backspace Backspace c Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace . / s Tab a c Tab Enter
 Ctrl+l l s Backspace Backspace d i r Enter
 Tab Tab Tab Tab Tab Ctrl+l l s Backspace Backspace Backspace l s Enter
 l s Enter
 l f Enter
 l s Enter
 Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l c l s Enter
 c l s Enter
 l s Enter
 p i p Space - = Backspace - v e r s i o n Enter
 f d s a Backspace Backspace Backspace Backspace Backspace Backspace Backspace f d s a Backspace Backspace Backspace Backspace Ctrl+l c l s Enter
 c o d Backspace Backspace Backspace p i p Space i n s t a l l Space p y l i n t Enter
 f a Backspace Backspace Ctrl+l c l s Enter
 Ctrl+l d i r Enter
 c l s Enter
 Ctrl+l

异常:
System.IO.IOException: 参数错误。

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.Console.SetWindowPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for this one, please see the pinned issue #1315
