### ISSUE TITLE
Inconsistency in PRSREadline when setting/getting colours

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PSReadLine#1366]
If I use Get-PSReadLineOption, I see a colour table as follows:
```powershell
CommandColor                           : "`e[96m"
CommentColor                           : "`e[32m"
ContinuationPromptColor                : "`e[96m"
DefaultTokenColor                      : "`e[97m"
EmphasisColor                          : "`e[96m"
ErrorColor                             : "`e[91m"
KeywordColor                           : "`e[92m"
MemberColor                            : "`e[92m"
NumberColor                            : "`e[97m"
OperatorColor                          : "`e[93m"
ParameterColor                         : "`e[96m"
SelectionColor                         : "`e[30;102m"
StringColor                            : "`e[93m"
TypeColor                              : "`e[32m"
VariableColor                          : "`e[93m"
```
You can see that the 4th entry is "DefaultTokenColor"

However setting that colour name to a colour fails:
```powershell
Set-PSReadLineOption -Colors @{
    DefaultTokenColor        = [System.ConsoleColor]::DarkYellow
}
```
As does this:
Set-PSReadLineOption -Colors @{
    DefaultToken        = [System.ConsoleColor]::DarkYellow
}

Can we please make the output and input consistent.

## Environment

```none
PS version: 7.0.0-rc.3
PSReadline version: 2.0.0
os: 10.0.19569.1000 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001
```

## Steps to reproduce

Attempt to set a colour based on the output

## Expected behavior
I expected it to work - if you show a 'DefaultTokenColour' setting a hash table entry of DefaultToken should work as it is what is shown in the Get-PSReadlineOption

## Actual behavior

PSReadline displays console in an unreadable state.

**Comment by daxian-dbw** [comment]
Please see the docs on `Set-PSReadLineOption` at https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7
The valid keys for `-Colors` are
```
ContinuationPrompt: The color of the continuation prompt.
Emphasis: The emphasis color. For example, the matching text when searching history.
Error: The error color. For example, in the prompt.
Selection: The color to highlight the menu selection or selected text.
Default: The default token color.
Comment: The comment token color.
Keyword: The keyword token color.
String: The string token color.
Operator: The operator token color.
Variable: The variable token color.
Command: The command token color.
Parameter: The parameter token color.
Type: The type token color.
Number: The number token color.
Member: The member name token color.
```

That being said, I understand your frustration because a more intuitive experience should be what you see is what you get.
The experience should be improved.

**Comment by doctordns** [comment]
I know how the Set-PSReadLIneoption is meant to work. But here, by default, the colour scheme is unusable so I've just removed PSRead line.

**Comment by msftrncs** [comment]
@doctordns, this works though right? 

``` PowerShell
Set-PSReadLineOption -Colors @{
   Default = [System.ConsoleColor]::DarkYellow
}
```

This is my current color setup: https://gist.github.com/msftrncs/a5814ff720396c6754ad01a8a7d3635b
