### ISSUE TITLE
PSReadline sets unusable colours With RC3

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PSReadLine#1367]
I have just loaded RC3 and the colour tables by default are not usable.

After a reload of PSReadline - by default I see:
```powershell
CommandColor                           : "`e[93m"
CommentColor                           : "`e[32m"
ContinuationPromptColor                : "`e[92m"
DefaultTokenColor                      : "`e[92m"
EmphasisColor                          : "`e[96m"
ErrorColor                             : "`e[91m"
KeywordColor                           : "`e[92m"
MemberColor                            : "`e[97m"
NumberColor                            : "`e[97m"
OperatorColor                          : "`e[90m"
ParameterColor                         : "`e[90m"
SelectionColor                         : "`e[30;102m"
StringColor                            : "`e[36m"
TypeColor                              : "`e[37m"
VariableColor                          : "`e[92m"
```

However the parameter, operator and emphasis colour are not visible on the screen - BY DEFAULT!

See this screen shot

![2020-02-24_10-18-40](https://user-images.githubusercontent.com/3630329/75144688-5d41fe80-56ef-11ea-9d5b-f8e5b4d6571c.png)

<!--

## Environment

```none
PS version: 7.0.0-rc.3
PSReadline version: 2.0.0
os: 10.0.19569.1000 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001
```

## Steps to reproduce

1. Install RC3
2. Remove ALL traces of PSReadline
3. Install a new copy from the psgallery
4. Attempt to use this module

## Expected behaviour
I assume that a default installation of PowerShell and PSReadline would produce a usable console. 

## Actual behaviour

With PSReadline - PowerShell 7 is not usable

My workaround to being able to actually use PowerShell 7's console is to remove PSReadline.

**Comment by daxian-dbw** [comment]
The default colors settings are never changed, and it's based on the foreground and background colors of your console/terminal.
For example, `ContinuationPromptColor` is using the foreground color of your console by default, so it looks to me the foreground color of your console is `ConsoleColor.Green` for some reason.

Here the default color settings when opening 7-rc.3 `pwsh` from `cmd` with the default foreground/background colors:
![image](https://user-images.githubusercontent.com/127450/75482983-b2357d00-595a-11ea-9504-80a3d9d57ee8.png)

Here is the default color settings when opening from windows terminal:
![image](https://user-images.githubusercontent.com/127450/75483057-d729f000-595a-11ea-8dab-e09f48f74129.png)

-----------

Note that the `EmphasisColor`, `OperatorColor` and `ParameterColor` in my default settings are the same as yours, but the rendering is different.
So it must be something with your console settings. Can you check on that and provide more information?

**Comment by msftrncs** [comment]
A thing to keep in mind, to clarify what @daxian-dbw is saying, the standard colors are set by the terminal.  The choices for what standard colors were used for what was clearly based on Windows terminal, but they are still defined by the terminal.   VSCode is a definite offender, as both its bright and dim standard colors are practically the same, making them undifferentiable, and that is no fault of PSReadLine's.  I had to change VSCode's terminal colors so that my PSReadLine theme would work reasonably.

**Comment by daxian-dbw** [comment]
Closing the issue given that the question was answered/explained.
