### ISSUE TITLE
ArgumentOutOfRangeException on backspace-ing a tab-completed path name

### ISSUE THREAD

**Issue by MisterD123** [PowerShell/PSReadLine#1379]
I think the last thing I put into the console was cd <part of path name>, tab complete, then backspace, and Powershell reported the following exception, asking me to report it here:

Last 200 Keys:
 Backspace c d Space Ctrl+Alt+\ u s Tab j s Tab Backspace d Tab d e k Backspace s k Tab Tab Tab e x Tab Tab Backspace Backspace Home Delete s Delete t a r t Enter
 c Ctrl+Alt+\ Backspace : Ctrl+Alt+\ u s Tab j Tab g Tab d Tab t Tab a r Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace a r Backspace Backspace t a r Tab g e t Tab Backspace Backspace Backspace Backspace Backspace Backspace i n Tab Tab t a r Tab a r Tab b Tab e x Tab Space i m Tab Tab Tab Enter
 UpArrow Enter
 e x i f Tab Ctrl+Backspace UpArrow Space - y a w Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+c d i r Enter
 c d Space u n Tab Backspace Backspace i m Tab Enter
 d i u r Enter
 d i r Enter
 s t a r t Space . Enter
 c d Space g o i Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
Do you see the pinned issue https://github.com/PowerShell/PSReadLine/issues/1306 ?

**Comment by MisterD123** [comment]
I did not check for existing issues, I was in the middle of debugging other things and as far as I recall, I thought since you made it so easy to send in the issue with Powershell immediately giving the link directly to the submission form I might as well submit it. Maybe you've made it too easy? ;) I think to see The pinned issue I would have had to navigate away from the form and then later go back? But I may also have overlooked it, apologies in that case.

**Comment by daxian-dbw** [comment]
@MisterD123 No worries at all, I appreciate your time to report the issue here. The exception report was intentionally made in such a way to make reporting an issue easy. But the environment data and repro step are also crucial to the investigation, and hence the bug template.
