### ISSUE TITLE
Menu Complete not working in WindowsTerminal

### ISSUE THREAD

**Issue by SonOfDiablo** [PowerShell/PSReadLine#1380]
## Environment

```none
PS version: 6.2.4
PSReadline version: 2.0.0-beta3
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 6.2.4.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 241
BufferHeight: 55
```

## Steps to reproduce

Write a part of any command (example: `Get-`) then hit `Ctrl+Space`

## Expected behavior

Running pwsh.exe directly works:
![image](https://user-images.githubusercontent.com/9123250/75609573-0d59a200-5b0a-11ea-89b9-7190c75e5f87.png)

## Actual behavior

Running pwsh.exe through WindowsTerminal (Nothing happens):
![image](https://user-images.githubusercontent.com/9123250/75609581-23676280-5b0a-11ea-9e39-5f30c8a6dabe.png)

**Comment by daxian-dbw** [comment]
I cannot repro this with the latest PSReadLine (version 2.0.0). You can get the latest PSReadLine from PowerShell Gallery. The "upgrading" instruction in README.md will be helpful.

![norepro](https://user-images.githubusercontent.com/127450/75703327-1a8ea200-5c6c-11ea-8aff-c2f6ce0b8c27.gif)

**Comment by lzybkr** [comment]
@daxian-dbw - your screen capture does not show `MenuComplete` working.

<kbd>Ctrl+Space</kbd> not working in Windows terminal is reported here: https://github.com/microsoft/terminal/issues/2865

**Comment by daxian-dbw** [comment]
I thought the author meant something different, as the "Expected Behavior" and "Actual Behavior" sections in the PR description indicate what author wants is what the GIF showed.

The menu completion works in Windows Terminal (v0.9.433.0) too:
![image](https://user-images.githubusercontent.com/127450/75716879-f4293080-5c84-11ea-9c69-f490cd0c21a1.png)

**Comment by SonOfDiablo** [comment]
After updating PSReadLine the `MenuComplete` (`Ctrl+Space`) actually works.
The Expected and Actual behavior descriptions might be a bit off, that one is my bad.

However it was the `Ctrl+Space` behavior I was talking about, it didn't trigger at all before, which is what I tried to show with the screenshots, though I must admit that it isn't super clear.
