### ISSUE TITLE
Exceção no PoweShell quando aperta "seta para cima" como a primeira tecla após abrir a linha de comandos

### ISSUE THREAD

**Issue by lecchi2003** [PowerShell/PSReadLine#1381]
Mensagem exibida:

Opa, algo deu errado. Relate este bug com os detalhes abaixo.
Relate no GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 1 Chaves:
 UpArrow

Exceção:
System.ArgumentOutOfRangeException: O valor deve ser maior ou igual a zero e menor que o tamanho do buffer do console nessa dimensão.
Nome do parâmetro: top
Valor real era -1.
   em System.Console.SetCursorPosition(Int32 left, Int32 top)
   em Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   em Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   em Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   em Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   em Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by vexx32** [comment]
@lecchi2003 please see #1306 🙂

**Comment by IzaqueL95** [comment]
I see the same problem today 

![image](https://user-images.githubusercontent.com/79032014/204030398-d1720d79-e7be-4212-b0ce-815af304fe9a.png)
