### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by aegal-creator** [PowerShell/PSReadLine#1382]
Last 188 Keys:
 & Space & Space " c : / U s e r s / a m i n a / O 
n e D r i v e / D e s k t o p / p y t h o n Space p r a c t i c e / h e l l o w o r l d / S c r i p t 
s / p y t h o n . e x e " Space - m Space p i p Space i n s t a l l Space - U Space p y l i n t Enter 
 c l e a r Enter
 & UpArrow Enter
 & m e s s a g e Space = Space " h e l l o Space w 
o r l d " Enter
 p r i n t ( m e s s a g e ) Enter
 p r i n t ( m e s s a g e ) Enter
 p r i n t ( m e s s a g e ) Enter

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps**.
