### ISSUE TITLE
Copy/Paste this sample into PowerShell launched from Windows Terminal app to get this error "Oops, something went wrong.  Please report this bug with the details below. Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new"

### ISSUE THREAD

**Issue by caliniaru** [PowerShell/PSReadLine#1383]
function RetrievePCIObjects 
{ 
    $ret = Get-WmiObject Win32_PnPEntity | Where-Object { 
        $_.HardwareID -like "PCI\*" -or $_.HardwareID -contains 'ACPI\PNP0A08'
    } | Select-Object `
    Service,
    @{ Name="Problem";
       Expression={ "{0:X}" -f [int]$_.GetDeviceProperties("DEVPKEY_Device_ProblemCode").deviceProperties.Data; }
    },
    @{ Name="Status";
       Expression={ "{0:X}" -f [int]$_.GetDeviceProperties("DEVPKEY_Device_DevNodeStatus").deviceProperties.Data; }
    },
    @{ Name="HardwareID";
       Expression={$_.HardwareID[0]}
      },
    @{ Name="BDF";
       Expression={
          $BusNo = $_.GetDeviceProperties("DEVPKEY_Device_BusNumber").deviceProperties.Data;
          $DevFn = $_.GetDeviceProperties("DEVPKEY_Device_Address").deviceProperties.Data;
          $FnNo = $DevFn -band 0x0000FFFF;
          $DevNo = $DevFn -shr 16;
          [int] ($BusNo -shl 8) -bor ($DevNo -shl 3) -bor $FnNo;
       }
     }, 
    Caption, DeviceID, 
    @{ Name="Parent";
       Expression={$_.GetDeviceProperties("DEVPKEY_Device_Parent").deviceProperties.Data;}
     }, 
     @{ Name="InstalledOn";
        Expression={$_.GetDeviceProperties("DEVPKEY_Device_InstallDate").deviceProperties.Data;}
     },
     @{ Name="MatchingId";
        Expression={$_.GetDeviceProperties("DEVPKEY_Device_MatchingDeviceId").deviceProperties.Data}
      }, 
    @{ Name="Next"; Expression={@()} },
    @{ Name="Displayed"; Expression={0} } | Sort-Object BDF

    return $ret;
}

**Comment by iSazonov** [comment]
@caliniaru Please use Issue template to report. We need more info.

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps**.
