### ISSUE TITLE
Ctrl-C doesn't work if PowerShell was started with Russian keyboard layout

### ISSUE THREAD

**Issue by ForNeVeR** [PowerShell/PSReadLine#1393]
## Environment

```none
PS version: 7.0.0
PSReadline version: 2.0.0
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 170
BufferHeight: 32766
```

## Steps to reproduce

1. Enable Russian keyboard layout on Windows (I use Alt-Shift to do that)
2. Start PowerShell Core 7.0 (which includes PSReadLine 2.0)
3. Press Ctrl-C in the shell

## Expected behavior

Ctrl-C should terminate current command/input/whatever, it should work as Ctrl-C usually do.

## Actual behavior

Russian letter "с" getting inserted into the command line, and no actual Ctrl-C behavior happens.

Ctrl-C is still broken even if I switch to the English keyboard layout (then English letter "c" gets inserted inctead of actual Ctrl-C behavior heppening).

**Comment by iSazonov** [comment]
@ForNeVeR Do you see the issue without PSReadline? If no please move the issue to PSReadline repo.

**Comment by ForNeVeR** [comment]
@iSazonov, no, I cannot reproduce the issue without PSReadLine.

Isn't this repository already a PSReadLine repo? I can see that some repository movement has been involved, but this is definitely a repo I [have been reporting](https://github.com/PowerShell/PSReadLine/issues/338) PSReadLine issues earlier.

Please direct me to a right repo if this isn't right. I've tried searching for other PSReadLine repo but wasn't successful, sorry.

**Comment by iSazonov** [comment]
> Isn't this repository already a PSReadLine repo?

Oh, sorry.

**Comment by daxian-dbw** [comment]
> Ctrl-C is still broken even if I switch to the English keyboard layout (then English letter "c" gets inserted inctead of actual Ctrl-C behavior heppening).

@ForNeVeR Thanks for the reporting. Just want some clarification on this behavior, was it broken for you when using the English keyboard from the very beginning?

**Comment by ForNeVeR** [comment]
Ctrl-C works fine if I start PowerShell session when English keyboard layout is active. It is only broken if I start the session with Russian layout.

**Comment by daxian-dbw** [comment]
A duplicate of this issue is reported in #1442 with a different repro -- `ctrl+r` results in the Russian letter к.

**Comment by ForNeVeR** [comment]
Yes, actually all of the Ctrl-hotkeys are broken.

**Comment by ForNeVeR** [comment]
Exact steps to reproduce:
1. Start PSReadline (e.g. by starting `PSReadline-net461` from sources).
2. Enable Russian keyboard layout, and then press Ctrl-C or Ctrl-R one time (it won't work).
3. After that, you may change the current keyboard layout as many times as you want, Ctrl-hotkeys won't work for you in this session. The session is absolutely broken.

Also, I've been able to reproduce the issue both in PowerShell Core and in PowerShell 5.1.

I was able to determine that the culprit is likely `Microsoft.PowerShell.PSKeyInfo.KeyInfoAsString`: this method returns a string `"Ctrl+к"` even when I press `Ctrl-r` with English keyboard layout enabled (and the input argument properly indicates `Ctrl+r` as being pressed). Most likely, there're two different issues:
1. Something in `PSKeyInfo` is static and wrongly so, so it remembers my (Russian) keyboard layout when I enter this method for the first time, and then reuses this layout even if I change it afterwards.
2. It just doesn't work as it should: it relies on the current keyboard layout for some reason, when the expected behavior would be to ignore it and always use the default one (at least, every single program I know behaves that way with the Russian+English keyboard layouts; there may be some exceptions from this rule, but I'm not aware of them yet).

I'll try to investigate further.

**Comment by ForNeVeR** [comment]
This call of `ToUnicode` causes problems: https://github.com/PowerShell/PSReadLine/blob/70249682ed8d87ddc3869e5d0ba852a0d6da99da/PSReadLine/Keys.cs#L150

On my system, it looks like it remembers the first keyboard layout with which it is called, and then it just uses it for all subsequent calls. So, while it obviously should hold `"r"` for input values of `ConsoleKey.R, 19, (an array of 256 zeros), (an array of 2 zeros), 2, 4`, actually it returns a Russian letter `"к"`.

[In the documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-tounicode), it isn't specified which layout it will use, but I could try to guess it uses current thread layout or something like that, and, since this code is called on a background thread (which may not process keyboard layout change messages properly), it may actually auto-initialize the keyboard layout for the first usage, and then leave it as-is. And this behavior could be dependent on OS version, installed language pack, or whatever else factor comes into play here.

I believe we could try to load an English keyboard layout and pass it to `ToUnicodeEx` (which takes a layout as input instead of relying on some vague global value), since our hotkeys seem to be specified in English.

@lzybkr, am I right? Would that be a good fix for the issue? I'm not quite sure why do you call all this `ToUnicode` business instead of e.g. creating a table like `ConsoleKey.R => "r"`, but it surely was a good reason, I presume?

**Comment by lzybkr** [comment]
Console applications are "sticky" with regards to the keyboard layout. I reported this as a bug to the appropriate internal team but there were concerns of appcompat issues.

I don't know if specifying the English keyboard layout works correctly or not.  Hopefully it would, but I vaguely recall experimenting specifying an explicit keyboard layout and it not working.

That said, I don't know under what conditions you would specify the English keyboard layout. How would PSReadLine know, for any given keyboard layout, that you really wanted a shortcut given that some normal keys use modifiers to type. This is why PSReadLine uses `ToUnicode` in the first place.

**Comment by iSazonov** [comment]
Perhaps the problem is more fundamental: in https://github.com/dotnet/runtime/issues/802 keyboard layout is discussed too.

**Comment by ForNeVeR** [comment]
@lzybkr, well, if there's a bug with sticky keyboard layout, then I can't experience it in usual console application. Only in PSReadLine-enabled PowerShell instance.

I agree that my plan about English keyboard doesn't look very good, so I'd like to take it back. What other options do we have?

Look, Windows applications usually set their hotkeys not based on the national keyboard, but based on the virtual key codes ([see the RegisterHotKey function](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) as an example). This mean that my initial use case described in the first post _makes sense_, and it should work (without any need to define additional keys for Russian keyboard layout or any others; it should just work out of the box).

And, as I can see in the current code in `Keys.cs`, PSReadLine for some reason decided to move away from this solution, and tries to interpret keys that are essentially the hotkeys in their national keyboard layout context (which may be frozen on background thread, but this is another issue).

Was this done by purpose? If not, then I believe we could fix the issue (by _not_ using `ToUnicode` WinAPI function for cases when there's any known modifiers (Ctrl/Alt) pressed with the key, or by performing an additional search with raw, "ununicoded" hotkey sequence).

What do you think of this plan?

@iSazonov, I'm only experiencing an issue on Windows (and everything seems to be okay on my Mac, where I use pwsh+PSReadLine, too), so I don't think that bug is relevant here.

**Comment by lzybkr** [comment]
If the console application uses cooked mode, then conhost (a WIndows GUI application, not a console application) implements reading input, so it doesn't have any issues with a sticky keyboard layout.

In v1.2, PSReadLine used [`ConsoleKeyInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.consolekeyinfo?view=netcore-3.1) as the key for dispatch. The [`Key` property](https://docs.microsoft.com/en-us/dotnet/api/system.consolekeyinfo.key?view=netcore-3.1) is the virtual key code (wrapped in a .Net enum). This mostly worked, but did have usability issuses. For example, `;` is Oem1 with the en-us keyboard layout. PSReadLine even lets you bind keys this way:

```PowerShell
Set-PSReadLineKeyHandler -Key 'Ctrl+Oem1' -Function Complete
```

And it converts `Oem1` to `;` using the initial keyboard layout, so when you run `Get-PSReadLineKeyHandler` you'll see:

```
Ctrl+;        Complete            Complete the input if there is a single completion, otherwise complete the input with common prefix for all completions.  Show
                                  possible completions if pressed a second time.
```

In v2, I moved to using a canonical string representation of the shortcut for better portability because `ConsoleKeyInfo` values differed between platforms. Unfortunately I don't recall specifics now.

I considered doing something special when <kbd>Alt</kbd> is in use, but the .Net api `Console.ReadKey` reports the use of <kbd>Alt</kbd> when using AltGr which does not really indicate a modified key, so I considered this approach a non-starter.


@ForNeVeR - Can you this setting in a new instance of PowerShell (needs to be set before PSReadLine is loaded):

```
$env:PSREADLINE_VTINPUT = 1
```

This will use a code path that is more similar to what runs on Linux/Mac. Some key bindings won't work because Windows key bindings are richer than what can be expressed by VT escape sequences, but it might be a reasonable workaround for some if it works.

**Comment by ForNeVeR** [comment]
Alright, thanks for discussion. Now, when I understand the details a little bit better, I could try to improve the keyboard handling without breaking everything else.

I've tried to set `$env:PSREADLINE_VTINPUT = 1` (and made sure I set this environment variable _before_ starting the PowerShell process, and it properly inherits it), but it didn't have any effect on this issue: it still reproduces.

**Comment by ForNeVeR** [comment]
Interestingly enough, only Ctrl-containing shortcuts are affected. Alt-containing characters (e.g. `Alt-d: KillWord`) seem to work. And we even enter the erroneous block after we know that the user has pressed a control character! https://github.com/PowerShell/PSReadLine/blob/70249682ed8d87ddc3869e5d0ba852a0d6da99da/PSReadLine/Keys.cs#L231-L253

Another interesting fact is that 44 tests for `en_US_Windows` fail on my system (after I enable the English keyboard layout).

**Comment by ForNeVeR** [comment]
And it starts to work if I set `control: true` instead of `control: false`.

Alright, it's time to summarize. I believe that _probably_ Windows itself has the code that uses the correct (English?) keyboard layout if it sees that the user has pressed the Ctrl key. For some reason, we destroy this knowledge by overriding `control: false`.

Why is this code required currently is beyond me, since it has something to do with a "dead key", a concept foreign to me, since I, unfortunately, have no dead keys in any of the keyboard layouts I use (though I understand its purpose and basics of how it works). So, I have no intuition about how the key bindings should work with a dead key.

@lzybkr, it looks like you're the original author of this snippet and `control: false`. Could you please explain why is it written like this? Are there any examples of input/output for this part of the code? (Even if I'll have to install some additional keyboard layout to try them out, it's okay.)

If the purpose of this code was to only detect a dead key, could it be written in a way to not override the `c` character?

I think it should never override a control character with a non-control one, would this be sufficient?
```csharp
var keySansControl = new ConsoleKeyInfo(key.KeyChar, consoleKey, isShift, isAlt, control: false);
char c1 = c;
TryGetCharFromConsoleKey(keySansControl, ref c1, ref isDeadKey);
if (char.IsControl(c1)) c = c1; // only override a control character with another control character
```

Or we could try to drop this `ref c` completely. I have verified that this fix works well with both of my keyboard layouts (tests are even more broken after the patch: 47 vs 44, should we care though?).

**Comment by lzybkr** [comment]
It's been too long since I wrote that code so I won't pretend to remember details or to defend the code in any way.

Maybe the safest change is to avoid that code for the unambiguous control characters.

I think you could safely add `c > 26 &&` to this test: https://github.com/PowerShell/PSReadLine/blob/70249682ed8d87ddc3869e5d0ba852a0d6da99da/PSReadLine/Keys.cs#L237

**Comment by Den-dp** [comment]
I came across this big quite often

**Comment by 0x241F31** [comment]
Any updates on this? How can I help with solving issue?

**Comment by farag2** [comment]
Yes, the bug still exists for Russian layout.

**Comment by airdev7** [comment]
Please fix the bug with the Russian keyboard layout, as it was said before, if you run Powershell with the Russian layout, all the keyboard shortcuts are broken...

**Comment by motcke** [comment]
@ForNeVeR I had the same issue (with pwsh 7 only) but with the Hebrew language, and I found out that it was caused by having two keyboard layouts defined for Hebrew (HE, HE3, in addition to EN). Removing the HE3 layout solved it.
Check if you have the same with Russian.

**Comment by ili101** [comment]
> @ForNeVeR I had the same issue (with pwsh 7 only) but with the Hebrew language, and I found out that it was caused by having two keyboard layouts defined for Hebrew (HE, HE3, in addition to EN). Removing the HE3 layout solved it. Check if you have the same with Russian.

Doesn't work for me. I think you are probably testing it wrong?
You can see in my reproduction steps and video here https://github.com/PowerShell/PowerShell/issues/17181 that I only have EN and HE.

**Comment by Kadeluxe** [comment]
Eh, here I am, I reported this issue to Windows Terminal first because I couldn't reproduce it outside of the Windows Terminal but yeah, this issue still present and is very annoying.
https://github.com/microsoft/terminal/issues/14318

**Comment by blackrek** [comment]
wha have any solutions or workarounds?

**Comment by conioh** [comment]
Still broken on PowerShell 7.3.5 with PSReadLine 2.2.6, with other languages too.

**Comment by ForNeVeR** [comment]
Alright, folks. I am very tired of this issue, so I've decided to publish a workaround.

- go to https://github.com/ForNeVeR/PSReadLine/releases/tag/v2.3.1-bugfix1393
- download [Microsoft.PowerShell.PSReadLine2.dll](https://github.com/ForNeVeR/PSReadLine/releases/download/v2.3.1-bugfix1393/Microsoft.PowerShell.PSReadLine2.dll)
- Replace `C:\Program Files\PowerShell\7\Modules\PSReadLine\Microsoft.PowerShell.PSReadLine2.dll` with this file.

> **Warning**
> Normally, you should not download files from the internet and replace the vendor stuff with them, but in this case it's the only quick solution I've found.

I've tried packing it up properly with a different name, but haven't been successful: it turns out that PowerShell really insists on loading the real PSReadline on startup, which breaks any of my workarounds with publishing the same module with alternate name.

If someone has experience with publishing/authoring PS modules, please take a look and help me to publish it properly, so `Get-Module` or `Install-Module` would work.

The workaround I've decided to use is [this commit](https://github.com/ForNeVeR/PSReadLine/commit/bfbf2c40598ca25cc057f7eec3ec49a3969d9ac9). It should force the `ToUnicode` to use US English layout when consuming the hotkey presses (Dvorak folks, I'm sorry, and I'm ready to provide an option and/or an alternative build for you if required!)

I also have a hypothesis (somewhat tricky to check unfortunately) that if we add a way to get _the right version_ of the current keyboard layout in that code, then we can fix the issue somewhat (it won't be perfect, but will stop sticking with _the wrong layout_ it seen on the first key press).

Unfortunately, this is quite tricky to do: the normal `WM_INPUTLANGCHANGE` message only gets sent to the active window (and our background keyboard-processing thread is definitely not _the active window_ and cannot own one), and so the only remaining way to do it is via some COM interop and [ITfActiveLanguageProfileNotifySink](https://learn.microsoft.com/en-us/windows/win32/api/msctf/nn-msctf-itfactivelanguageprofilenotifysink). I haven't tried that, but COM interop in modern .NET is a bit messy, so I'd also accept help on that. It's hard to even try that to check if it will work.

## Conclusion

So, for now, enjoy the workaround (and I hope I'll be able to publish updated versions of that package while pwsh gets updated), and maybe in the future I'll experiment more on a better workaround that we can merge into the main repository.

I have to say I am a bit disappointed with how the PSReadline team has handled this issue and my pull request. But I still love and respect y'all folks for your great job, and hope we'll be able to improve our communications in the future.

**Comment by conioh** [comment]
Thanks to my colleagues @bugale and @kobykahane an incredible workaround has been found.

It turns out that if you enable the _let me use a different input method for each app window_ setting (e.g. using the GUI or `Set-WinLanguageBarOption -UseLegacySwitchMode`), new PoserShell processes (even inside the same window and console) will have working Ctrl+_X_ keyboard shortcuts.

This solution depends on English being the default/first keyboard layout, but I consider it the correct thing to do anyway.

**Comment by ForNeVeR** [comment]
↑ the above sounds logical: the thread that checks the keyboard layout will then get the initial English and will never be able to switch to anything else.

I don't want to turn this on in my environment, though, since I like to have a global keyboard layout instead of having it remembered per each window.

**Comment by conioh** [comment]
Yeah, it's kind of logical, but there are some complications.

I haven't reversed any of this so I'm speaking only about documentation and observed behavior.

The name of the setting is "let me use a different input method for each _app window_", but as I said it fixes the issue even within an existing window (e.g. open a new PowerShell tab in Windows Terminal) and even within the same console (run `pwsh.exe` from within an existing PowerShell session).

What's interesting to note is that in all of those cases, even when this setting (" let me use a different input method for each app window") is enabled, and the current keyboard layout for the windows is _Some Language_ (rather than English), when I hit Ctrl-Shift-T I get a new PowerShell tab _with the same language_ - not English! - and yet the keyboard shortcuts work. If I Alt-Tab into another windows the keyboard layout changes to that window's language, as expected.

If indeed every new application would have English set as it's keyboard layout, I'd expect that when I Ctrl-Shift-T inside Windows Terminal to open a new tab and PowerShell session it would be in English. But it's not. It's in whatever language I was using in Windows Terminal, and yet somehow the PSReadLine keyboard shortcuts work.

I guess something a bit more complicated happens there. I can't explain it but it works.

**Comment by ForNeVeR** [comment]
After a good look at the code, I can summarize that PSReadline works by polling the console key buffer in a separate thread.

That thread, despite not owning any windows, is considered as a separate "window" by whatever logic controls the keyboard layout in Windows. It's set to system default the first time we do anything keyboard-related (by asking the layout for the first time) in that thread, and then never gets reset to anything else (because the thread doesn't even have a message loop to possibly process this event).

Getting the right keyboard layout is pretty painful in Windows' console apps (because they don't own a window on their own and rely on whatever's provided by the corresponding console host/terminal app), and doubly so in a console app _from a background thread_.

**Comment by ForNeVeR** [comment]
I've experimented a bit with `ITfLanguageProfileNotifySink`, and this approach won't work.

This interface works the same as everything else: it will only notify the owner of the active window, so it's impossible to use in a hidden service window to get notifications of system keyboard layout changes, as we'd like to.

Moreover, now, after a message from @conioh, I don't believe this approach could ever work correctly: it's possible to make every window to keep its own layout, so we _really want_ to get the correct layout from the console window, and not from our hidden service window or whatever.

And [that's currently impossible in Windows Terminal](https://github.com/microsoft/terminal/issues/83).

So, I don't know what else to do. Perhaps let's add a setting for my workaround that forces the keyboard shortcuts to be processed as if the English QWERTY layout is enabled?

**Comment by ForNeVeR** [comment]
My next attempt to fix that for good is https://github.com/PowerShell/PSReadLine/pull/3786.

It will only make the hotkeys work properly in case the current keyboard layout supports that, but it's still a stable improvement, opens a possibility for the users to just change the layout and use the keys without restarting their shell, and (hopefully?) shouldn't break the old use cases with national layouts. But only make them work more "properly", whatever that means (I'm still unsure how the keyboard shortcuts generally _should_ work in those cases, but maybe let's not get too deep into that?).

**Comment by ForNeVeR** [comment]
My release of 2.3.3 + keyboard fix: https://github.com/ForNeVeR/PSReadLine/releases/tag/v2.3.3%2Bkeyboard-layout

Dear maintainers, could someone please take a look at my PR fixing the issue? https://github.com/PowerShell/PSReadLine/pull/3786

**Comment by ExzoTikStyle** [comment]
> My release of 2.3.3 + keyboard fix: https://github.com/ForNeVeR/PSReadLine/releases/tag/v2.3.3%2Bkeyboard-layout
> 
> Dear maintainers, could someone please take a look at my PR fixing the issue? #3786

I tried it and the bug still persists
```
PS Version: 7.3.7
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.3
PSReadLine EditMode: Windows
OS: 10.0.19041.3324 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

**Comment by ForNeVeR** [comment]
@ExzoTikStyle please share your testing methodic. I expect the following results:
- press `Ctrl+C` in non-English keyboard layout: doesn't work
- switch keyboard layout to English in the same shell session, press `Ctrl+C`: works

This is because this build contains a new fix that passes all the tests (#3786) and is less intrusive than the previous one (and I really hope we'll be able to merge it to upstream because of that).

This new build, in my personal opinion, works worse than the previous (that just hard-coded English to be used in all the keys), but I think it has a better change of being adopted by the upstream repo, and that's why I published that.

(that being said, I am of course testing it on my computer myself, and it seems to work for me, but it's possible you have found a bug)

**Comment by ExzoTikStyle** [comment]
> @ExzoTikStyle please share your testing methodic. I expect the following results:
> 
> * press `Ctrl+C` in non-English keyboard layout: doesn't work
> * switch keyboard layout to English in the same shell session, press `Ctrl+C`: works
> 
> This is because this build contains a new fix that passes all the tests (#3786) and is less intrusive than the previous one (and I really hope we'll be able to merge it to upstream because of that).
> 
> This new build, in my personal opinion, works worse than the previous (that just hard-coded English to be used in all the keys), but I think it has a better change of being adopted by the upstream repo, and that's why I published that.
> 
> (that being said, I am of course testing it on my computer myself, and it seems to work for me, but it's possible you have found a bug)

Initially I launch the terminal with the Cyrillic layout. I press Ctrl+c and only c is displayed. I switch the layout to English, press Ctrl+C and the result is the same as with the Cyrillic layout.
Attached screenshots of the terminal and virtual keyboard
![1](https://github.com/PowerShell/PSReadLine/assets/37483500/2ebbec6c-771f-4709-a3b4-cfbe6a86e457)

![2](https://github.com/PowerShell/PSReadLine/assets/37483500/f240c538-e8af-4411-bb36-be43b9aaa1a1)

**Comment by ForNeVeR** [comment]
This is very strange. Could you please check the module list of your pwsh process? Does it list the file you've replaced by my release?
<img width="759" alt="image" src="https://github.com/PowerShell/PSReadLine/assets/92793/172bdac6-e5fb-45cd-9b92-0dcf3d11df5b">

(to see the module list, attach any debugger or use a tool like Process Hacker 2)

**Comment by ExzoTikStyle** [comment]
> This is very strange. Could you please check the module list of your pwsh process? Does it list the file you've replaced by my release?
> (to see the module list, attach any debugger or use a tool like Process Hacker 2)

Yes,this file exist in pwsh modules 
![image](https://github.com/PowerShell/PSReadLine/assets/37483500/a08928d7-d590-4c0c-bcb8-83bad9f56776)
![image](https://github.com/PowerShell/PSReadLine/assets/37483500/67e3bfcc-2aad-4f70-8bd6-73accf5b5a02)

**Comment by ForNeVeR** [comment]
Ok, 2.3.3+e8 is correct: it is [the commit with my fix](https://github.com/ForNeVeR/PSReadLine/commit/e8c26aeb98ada25e4fa3b4d6017fb29fe7a75eb1).

Could you please show the process tree of this pwsh process? Does it have Terminal as the parent process?

**Comment by ExzoTikStyle** [comment]
> Ok, 2.3.3+e8 is correct: it is [the commit with my fix](https://github.com/ForNeVeR/PSReadLine/commit/e8c26aeb98ada25e4fa3b4d6017fb29fe7a75eb1).
> 
> Could you please show the process tree of this pwsh process? Does it have Terminal as the parent process?

I found the reason. The PSReadLine module was installed in the user's environment, although I did not specify the scope. I added your file there and everything worked as expected. Thank you!
I would add to the instructions a definition of the path where the file should be copied
```
(Get-Module -Name PSReadLine).path
```

**Comment by ForNeVeR** [comment]
In my own experiments, I never have been able to replace the original module with a custom installation, but from your feedback it looks like this is possible.

**Comment by ForNeVeR** [comment]
A new PowerShell version with newer PSReadline, so I've republished my fork as well: https://github.com/ForNeVeR/PSReadLine/releases/tag/v2.3.4%2B05836c5553c9b134929f00a0b3263ee326a3913f

@daxian-dbw, I am sorry I don't know whom to ping. Could you please help us to find a responsible person to review #3786? Thank you!

**Comment by daxian-dbw** [comment]
@ForNeVeR I will make sure get to it this week. I've also added a reviewer who has good experience in the Windows console area, and hopefully we can get his help too.

**Comment by Kadeluxe** [comment]
@ForNeVeR thank you for your fork, I was able to get it working with local PSReadLine installation (located in `%USERPROFILE%\Documents\PowerShell\Modules\PSReadLine\2.3.4`).
Works on Latin layout even if Terminal was started using Cyrillic. Still annoying that it doesn't work with Cyrillic but it's still a step forward I guess. I hope there could be a definitive fix for this issue.

**Comment by ForNeVeR** [comment]
> Still annoying that it doesn't work with Cyrillic

Unfortunately, the current opinion is that such behavior would actually break the habits of some users (who use shortcuts in local keyboard layouts; such a thing exists!), and my early tries to fix it that way broke the PSReadline tests. So I've decided to have a more lightweight fix that only loads the current layout correctly before looking up the shortcut.

**Comment by ForNeVeR** [comment]
Folks, love y'all so much. Finally, we'll have a significant improvement on this in the next release ❤️ 

The shortcuts are still expected to be defunct if you have a "wrong" keyboard layout enabled when you hit `Ctrl+C`, but it won't stick with you until the end of PowerShell session: just change the layout to English, and it will start working again.

It was verified in several terminal apps (including the Windows Terminal, of course), but there are cases when it is still broken (e.g. in the old console, or when you start Windows Terminal as a default terminal app, as opposed to explicitly clicking the Terminal icon).

I'd suggest to report new cases separately, and you may link them in this thread. I'll try to take a look at new particular scenarios and improve them if possible.

But again: we expect that in majority of cases, the issue will be gone next release. I am so happy 🎉

**Comment by TimofeyBiryukov** [comment]
I've just ran in to this, and this still seems to be a problem.

If you start PowerShell (7.4.1), with a Russian layout enabled. CTRL+C wouldn't be working. Switching back to Eng layout doesn't fix the issue. More, if you hold CTRL and press any button, the letters will be in a layout you started with, regardless of if you switched layouts or not. I.e. switch to Eng, press F button see F on screen, hold CTRL press F, see A(Ru) on screen.

**Comment by ForNeVeR** [comment]
Not sure if the fix was integrated into 7.4.1. So far, it looks like the latest release of PSReadLine is 2.3.4, built _before_ merging of my PR.

So, it looks like we just need to wait for a bit more for the next release.

In the meantime, I think you can use [my workaround fork](https://github.com/ForNeVeR/PSReadLine/releases/tag/v2.3.4%2B05836c5553c9b134929f00a0b3263ee326a3913f) (installation instructions are notably messy but are included in the release page).

**Comment by Kadeluxe** [comment]
I'm on 7.4.2 and it's not working without manually replacing.

**Comment by ForNeVeR** [comment]
Sadly, the last release, PSReadLine v2.3.5, still doesn't have my fix included. Check the list of commits by this link: https://github.com/PowerShell/PSReadLine/compare/v2.3.5...master

**Comment by daxian-dbw** [comment]
The fix is included in [v2.4.0-beta0](https://www.powershellgallery.com/packages/PSReadLine/2.4.0-beta0). Please install that version and try again.

**Comment by Kadeluxe** [comment]
`Install-Module -Name PSReadLine -AllowPrerelease -Force` worked, thanks for the tip.

Once again @ForNeVeR thank you for your time, I really do appreciate your work here.

**Comment by bn45hkurr0y4** [comment]
This problem still exists in PSReadline 2.4.5.
bash/zsh/cmd do not have this problem.
```
PS C:\Users\Computer> Get-Module -Name PSReadLine

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.4.5                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

PS C:\Users\Computer> pwsh -v
PowerShell 7.5.4
PS C:\Users\Computer> winget list Microsoft.WindowsTerminal
Name             Id                        Version      Source
---------------------------------------------------------------
Windows Terminal Microsoft.WindowsTerminal 1.23.20211.0 winget

PS C:\Users\Computer> winver
Windows 11 25H2 26200.7623
```
