### ISSUE TITLE
Python 3.8.1, env config in windows 10

### ISSUE THREAD

**Issue by Xhevairi** [PowerShell/PSReadLine#1394]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 s k e l l " , Enter
 Space Space " n i m " : Space " n i m Space c o m p i l e Space - - v e r b o s i t y : 0 Space - - h i n t s : o f f Space - - r u n " , Enter
 Space Space " l i s p " : Space " s b c l Space - - s c r i p t " , Enter
 Space Space " k i t " : Space " k i t c Space - - r u n " , Enter
 Space Space " v " : Space " v Space r u n " , Enter
 Space Space " s a s s " : Space " s a s s Space - - s t y l e Space e x p a n d e d " , Enter
 Space Space " s c s s " : Space " s c s s Space - - s t y l e Space e x p a n d e d " Enter
 }

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and 
less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -36.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String 
defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS F:\Python\py_code> "code-runner.executorMap": {
>>   "javascript": "node",
>>   "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
>>   "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt", 
>>   "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
>>   "objective-c": "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
>>   "php": "php",
>>   "python": "python -u",
>>   "perl": "perl",
>>   "perl6": "perl6",
>>   "ruby": "ruby",
>>   "go": "go run",
>>   "lua": "lua",
>>   "groovy": "groovy",
>>   "powershell": "powershell -ExecutionPolicy ByPass -File",
>>   "bat": "cmd /c",
>>   "shellscript": "bash",
>>   "fsharp": "fsi",
>>   "csharp": "scriptcs",
>>   "vbscript": "cscript //Nologo",
>>   "typescript": "ts-node",
>>   "coffeescript": "coffee",
>>   "scala": "scala",
>>   "swift": "swift",
>>   "julia": "julia",
>>   "crystal": "crystal",
>>   "ocaml": "ocaml",
>>   "r": "Rscript",
>>   "applescript": "osascript",
>>   "clojure": "lein exec",
>>   "haxe": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
>>   "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
>>   "racket": "racket",
>>   "scheme": "csi -script",
>>   "ahk": "autohotkey",
>>   "autoit": "autoit3",
>>   "dart": "dart",
>>   "pascal": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
>>   "d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
>>   "haskell": "runhaskell",
>>   "nim": "nim compile --verbosity:0 --hints:off --run",
>>   "lisp": "sbcl --script",
>>   "kit": "kitc --run",
>>   "v": "v run",
>>   "sass": "sass --style expanded",
>>   "scss": "scss --style expanded"
>> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 s k e l l " , Enter
 Space Space " n i m " : Space " n i m Space c o m p i l e Space - - v e r b o s i t y : 0 Space - - h i n t s : o f f Space - - r u n " , Enter
 Space Space " l i s p " : Space " s b c l Space - - s c r i p t " , Enter
 Space Space " k i t " : Space " k i t c Space - - r u n " , Enter
 Space Space " v " : Space " v Space r u n " , Enter
 Space Space " s a s s " : Space " s a s s Space - - s t y l e Space e x p a n d e d " , Enter
 Space Space " s c s s " : Space " s c s s Space - - s t y l e Space e x p a n d e d " Enter
 }

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and 
less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -37.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String 
defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)     
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PSReadLine/issues/1306
