### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by mac40** [PowerShell/PSReadLine#1395]
Ultimi 200 tasti:
 s c o d e - j a v a - d e b u g - 0 . 2 5 . 1 \ s c r i p t s \ l a u n c h e r . b a t ' Space ' C : \ P r o g r a m Space F i l e s \ J a v a \ j d k - 
1 3 . 0 . 2 \ b i n \ j a v a . e x e ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ m a r c o \ A p p D a t a \ L o c a l \ T e m p \ c p _ b d 0 y a 5 g o s 6 8 w n 6 v 2 7 b 8 2 3 u v y k . a r g f i l e ' Space ' M a i n ' Space Enter

Eccezione:
System.ArgumentOutOfRangeException: Il valore deve essere maggiore o uguale a zero e minore della grandezza del buffer della console in tale dimensione.   
Nome parametro: left
Valore effettivo: -1.
   in Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   in Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   in Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   in Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   in Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   in Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PSReadLine/issues/1306
