### ISSUE TITLE
Set-PSReadLineKeyHandler -Key Ctrl+U not working

### ISSUE THREAD

**Issue by gfody** [PowerShell/PSReadLine#1396]
This stopped working when I upgraded from PowerShell 5.1 to PowerShell 7 (which consequently upgraded PSReadLine from 1.2 to 2.0.0)

# Steps to reproduce

```powershell
Set-PSReadLineKeyHandler -Key Ctrl+U -Function RevertLine
```

# Expected behavior
ctrl+u reverts the line

# Actual behavior
ctrl+u results in `^U`

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
Try:

```
Set-PSReadLineKeyHandler -Key Ctrl+u -Function RevertLine
```

Note the change in case from `U` to `u`. Previously you had to specify the state of the <kbd>Shift</kbd> but that is now inferred to better support keyboard layouts other than en-US.

@daxian-dbw - You should make sure this breaking change gets documented. I don't think it is mentioned in the changelog.

**Comment by gfody** [comment]
lowercase `Ctrl+u` worked, thanks! closing.

**Comment by zhangjunlei26** [comment]
same as linux terminal mode
https://docs.microsoft.com/zh-cn/powershell/module/psreadline/about/about_psreadline?view=powershell-7.2

```shell
Import-Module PSReadLine
Set-PSReadLineOption -EditMode Emacs
```
