### ISSUE TITLE
VSCode console returning error (Powershell)

### ISSUE THREAD

**Issue by VectorBCO** [PowerShell/PSReadLine#1400]
`Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -3.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)`

System Win 10 pro 1909
VSCode v.1.42.1
PSVersion 5.1.18362.628

Story:  working on a project for 3 days with debugging some stuff so cannot restart VSCode (dont want lost some cached data) and after some time I start getting those type of errors. 
At the same time after error displayed in a terminal all other things working fine

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PSReadLine/issues/1306

**Comment by VectorBCO** [comment]
Hi, thanks for reference link
I update vscode and will see maybe this issue will not come again 
I report this issue as was suggested in issue text so if you think that this information did not needed for any debug issue can be simply closed

**Comment by VectorBCO** [comment]
btw I have latest psreadline (2.0.0), if issue somehow related to this module version

**Comment by vexx32** [comment]
Windows PowerShell doesn't show the prerelease version. PSReadLine 2.0 has had 6? 7? prerelease versions, so odds are you don't have the full 2.0.0 release version. 🙂 

You'll likely need to manually update / force the update after also updating PowerShellGet.

**Comment by VectorBCO** [comment]
I had previously installed PS6 and PS7 RC1, but after installation official release PS7 all previous RC was removed automatically
I will try update psreadline and let you know about results
Do you know how to check exact pre-release module version?

You was right:

> WARNING: Version '2.0.0-beta2' of module 'PSReadline' is already installed at 'C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0'. To install version '2.0.0', run Install-Module and add the -Force parameter, this command will install version '2.0.0' in
side-by-side with version '2.0.0-beta2'

**Comment by iSazonov** [comment]
Use Get-Module PSReadline to find the module path and see a content of PSReadLine.psd1 file.

**Comment by VectorBCO** [comment]
![image](https://user-images.githubusercontent.com/13451494/76615264-f8293e00-6521-11ea-9c2d-4318282bc605.png)
Am I right understand that GUID is unique module identificator?

**Comment by iSazonov** [comment]
No, the GUID does not help. See ModuleVersion value and Prerelease value in PrivateData.

**Comment by VectorBCO** [comment]
so, in this case first psd file from beta2 pre-release and second one is general release, correct?

**Comment by iSazonov** [comment]
I am not sure about your screenshot. See original file https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/PSReadLine.psd1

**Comment by daxian-dbw** [comment]
> so, in this case first psd file from beta2 pre-release and second one is general release, correct?

Yes, that's correct. The issue has been fixed in the 2.0.0 GA version of the PSReadLine. Please try out the GA version.
