### ISSUE TITLE
What is PSReadline version distributed with PowerShell 7.0?

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PSReadLine#1405]
In the repo manifest is
https://github.com/PowerShell/PSReadLine/blob/198a64390e713214df20ef580f7a546b5c3ac1e8/PSReadLine/PSReadLine.psd1#L1-L19

Manifest from C:\Program Files\PowerShell\7\Modules\PSReadLine (PowerShell 7.0 is installed from MSI)
```
@{
RootModule = 'PSReadLine.psm1'
NestedModules = @("Microsoft.PowerShell.PSReadLine2.dll")
ModuleVersion = '2.0.0'
GUID = '5714753b-2afd-4492-a5fd-01d9e2cff8b5'
Author = 'Microsoft Corporation'
CompanyName = 'Microsoft Corporation'
Copyright = '(c) Microsoft Corporation. All rights reserved.'
Description = 'Great command line editing in the PowerShell console host'
PowerShellVersion = '5.0'
DotNetFrameworkVersion = '4.6.1'
CLRVersion = '4.0.0'
FormatsToProcess = 'PSReadLine.format.ps1xml'
AliasesToExport = @()
FunctionsToExport = 'PSConsoleHostReadLine'
CmdletsToExport = 'Get-PSReadLineKeyHandler','Set-PSReadLineKeyHandler','Remove-PSReadLineKeyHandler',
                  'Get-PSReadLineOption','Set-PSReadLineOption'
HelpInfoURI = 'https://go.microsoft.com/fwlink/?LinkId=2113630'
}
```

You can see difference `ModuleVersion = '2.0'` vs `ModuleVersion = '2.0.0'`.

Why do we have this? Is right PSReadline version distributed with PowerShell 7.0

/cc @daxian-dbw

**Comment by daxian-dbw** [comment]
@iSazonov The `2.0` is replaced with the actual version during the build, see https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine.build.ps1#L187.

This way we don't need to update the `PSReadLine.psd1` for every release.
