### ISSUE TITLE
PSReadline eat № at right click

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PSReadLine#1406]
## Environment

```none
PS version: 7.0.0
PSReadline version: 2.0.0
os: 10.0.17763.701 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001
```

## Steps to reproduce

1. Open Notepad.exe
2. Create two lines
- first with one char `№`
- second with space before the same char ` №`
3. Copy the content
4. Run pwsh (7.0 version)
5. Right click in pwsh window.

## Expected behavior

`№`
` №`

## Actual behavior

`№`
` ` (one space inserted)

**Comment by daxian-dbw** [comment]
@iSazonov Does this happen without PSReadLine?

**Comment by iSazonov** [comment]
Ctrl-V works well with PSReadline.
After removing PSReadline right click works well.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please investigate the issue closely before 2.2.0 release?

**Comment by daxian-dbw** [comment]
I won't be able to look into this before 2.2.0. If `Ctrl+v` works, then it's a low priority.

**Comment by iSazonov** [comment]
This works now (Beta4). Thanks!
