### ISSUE TITLE
异常: System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。

### ISSUE THREAD

**Issue by EthanAIPro** [PowerShell/PSReadLine#1407]
PS D:\scf_workspace>  ${env:PTVSD_LAUNCHER_PORT}='61879'; & 'C:\Users\wangz\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe' 'c:\Users\wangz\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\new_ptvsd\wheels\ptvsd\launcher' 'd:\scf_workspace\firt_demo\hello_world\i
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 200 个密钥:
 7 _ q b z 5 n 2 k f r a 8 p 0 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ w a n g z \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h 
o n . p y t h o n - 2 0 2 0 . 2 . 6 4 3 9 7 \ p y t h o n F i l e s \ l i b \ p y t h o n \ n e w _ p t v s d \ w h e e l s \ p t v s d \ l a u n c h e r ' Space ' d : \ s c f _ w o r k s p a c e \ f i r t _ d e m o \ h e l l o _ w o r l d \ i n d e x . p y ' Space Enter

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PSReadLine/issues/1306

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for this issue, please see #1306 for details.
