### ISSUE TITLE
Visual Studio, Python Code 

### ISSUE THREAD

**Issue by Andrew7-cloud** [PowerShell/PSReadLine#1412]
ops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

 |      x.__getitem__(y) <==> x[y]
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
-----------------------------------------------------------------------
Last 200 Keys:
 7 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t '  |  __init__(self, /, *args, **kwargs)Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 5 8 6 0 ' Space ' c : \ U s e r s \......
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.        
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(
Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.For |      Initialize self.  See help(type(self)) for accurate signature.ceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
chTable, Boolean ignoreIfNoAction, Object arg)rocessOneKey(ConsoleKeyInfo key, Dictionary`2 dispat
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
------------------------------------------
-----------------------------
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |

 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __repr__(self, /)
-- More  --                                                                 --default' '--nodebug' '--client' '--host' 'localhost' '
At line:1 char:3
+ --default' '--nodebug' '--client' '--host' 'localhost' '
+   ~
Missing expression after unary operator '--'.
At line:1 char:3
+ --default' '--nodebug' '--client' '--host' 'localhost' '
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'default' '--nodebug' '--client' '--host' 'localhost' '' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

**Comment by Andrew7-cloud** [comment]
Using Anaconda, writing python. Code below:
""" 
Working with a files contents.
Ex 3: loop through lines, then add to string
"""

file_path = 'C:/Users/......

with open(file_path) as file_object:
    # readlines method stores the file_object as a list
    lines = file_object.readlines()

pie_string = ''
for line in lines:
    pie_string += line.strip()

birthday = input("Enter your birthday in the form mmddyy:  ")
if birthday in pi_string:
    print("Your birthday appears in the first million digits in pi!")
else:
    print("Your birthday does not appear in the first million digits in pi!")

**Comment by iSazonov** [comment]
See #1306

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the issue, please see #1306 for details.
