### ISSUE TITLE
-AllowPrerelease not available in vanilla powershell 5.1's Install-Module

### ISSUE THREAD

**Issue by scottnm** [PowerShell/PSReadLine#1423]
The docs for upgrading with powershell 5.1 say...

> If you are using the version of PSReadLine that ships with Windows PowerShell, you need to run: `powershell -noprofile -command "Install-Module PSReadLine -Force -SkipPublisherCheck -AllowPrerelease`.

this didn't work for me.

I kept getting the error `Install-Module : A parameter cannot be found that matches parameter name AllowPrerelease.`

turns out the default install of powershell on my work machine had an outdated version of PowershellGet

the fix I followed to update was detailed here https://evotec.xyz/install-module-a-parameter-cannot-be-found-that-matches-parameter-name-allowprerelease/

namely I needed to update PowershellGet first with `Install-Module PowershellGet -Force` and then restart my shell

**Comment by iSazonov** [comment]
You should update PowerShellGet. Please read and follow https://github.com/PowerShell/PSReadLine#install-from-powershellgallery-preferred

**Comment by scottnm** [comment]
Ah! I didn't realize there was already a reference to this issue in your docs.

To be clear, I'd already solved this issue myself using the provided link because I didn't realize it was already in your docs.

Since I already had PSReadline and Powershell installed, I skipped the installation instructions and went straight to the Update instructions which don't reference this sneaky problem.

Maybe your update instructions could include this link back to your installation docs with a note saying "make sure you have powershellget updated as well"

**Comment by iSazonov** [comment]
Feel free to pull the simple PR.

**Comment by iSazonov** [comment]
@daxian-dbw Do you consider GitHub Wiki to simplify updating the docs by users?

**Comment by daxian-dbw** [comment]
Closed via #1424

**Comment by daxian-dbw** [comment]
Even if we go with Wiki, I don't think we will give permission to random users to edit the wiki pages.
