### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by kesavamuthu** [PowerShell/PSReadLine#1433]
I am getting exception. Initial input is git diff then pressing the ctrl + l is throwing this exception for other details I've attached the log.

[log.txt](https://github.com/PowerShell/PSReadLine/files/4399094/log.txt)

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro step** the next time.

Issues related to `Ctrl+l` has been fixed by avoid using `SetCursorPosition`, see #1315.
