### ISSUE TITLE
Paste with tabs renders ^I

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#144]
If you paste text with Ctrl+V and the text has tab characters, they are rendered with ^I, e.g.

function foo
{
^IWrite-Host "In foo"
}

Tabs should probably be replaced with a user configurable number of spaces.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PowerShell/PSReadLine/issues/144#event-1337497655

Per https://github.com/PowerShell/PowerShell/issues/24037#issue-2400529452, this doesn't work consistently - I've still had `^I` appear in a few (albeit not most) scenarios, when pasting text.
