### ISSUE TITLE
Calls to AddToHistory before Init cause NullRef

### ISSUE THREAD

**Issue by Bosparan** [PowerShell/PSReadLine#145]
Hi,

I just tried out the current version (up from 1.0.0.8) and had some significant problems with it:
I have built an executable that runs Powershell.exe with an encoded command and the -NoExit parameter. If I call the AddToHistory() method in this encoded script it will throw an error:
"Object reference not set to an instance of an object."
(Stacktrace at the bottom of the post).

However, if I run the same command without the AddHistory calls in it (but with Import-Module calls), it resolves flawlessly, and entering them manually afterwards is no issue.

Cheers,
Bosparan

Note: Problem persists in 1.0.0.12
# Command to reproduce error

(edit: In the original code there's no space before ::AddToHistory - I added those as otherwise the website won't show me the "[" and "]")
$command = @'
Import-Module "[Path to Module]\PSReadLine.psd1"
[PSConsoleUtilities.PSConsoleReadLine] ::AddToHistory("Get-Help")
[PSConsoleUtilities.PSConsoleReadLine] ::AddToHistory("$error")
[PSConsoleUtilities.PSConsoleReadLine] ::AddToHistory("Let me out!")
'@
$encoded = [convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($command))
Start-Process PowerShell.exe -Verb "RunAs" -ErrorAction 'Stop' -ArgumentList @("-WindowStyle normal", "-NoLogo", "-ExecutionPolicy Unrestricted", "-NoExit", "-EncodedCommand", $encoded)
# Stacktrace

System.NullReferenceException: Object reference not set to an instance of an object.
   at PSConsoleUtilities.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32
undoEditIndex, Boolean readingHistoryFile) in
[Path to Module]\History.cs:line 47
   at PSConsoleUtilities.PSConsoleReadLine.AddToHistory(String command) in
[Path to Module]\History.cs:line
238
   at CallSite.Target(Closure , CallSite , RuntimeType , String )

**Comment by lzybkr** [comment]
Still repros in V2.

**Comment by daxian-dbw** [comment]
This issue is sorta resolved after introducing the `CancellationToken` parameter to `PSConsoleReadLine.ReadLine`.
The command can be written in this way:
```pwsh
$command = @'
  $token = [System.Threading.CancellationToken]::new($true)  ## create a cancelled token
  [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($Host.Runspace, $ExecutionContext, $token, $null)
  [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory("Get-Help")
  [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory("$error")
  [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory("Let me out!")
'@
$encoded = [convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($command))
Start-Process PowerShell.exe -Verb "RunAs" -ErrorAction 'Stop' -ArgumentList @("-WindowStyle normal", "-NoLogo", "-ExecutionPolicy Unrestricted", "-NoExit", "-EncodedCommand", $encoded)
```

The delay initialization is by-design, it requires the `Runspace` and `EngineIntrinsics` to properly initialize all the state. Calling `PSConsoleReadLine.ReadLine` with a cancelled token is the way to work around this limitation.
