### ISSUE TITLE
DefaultAddToHistoryHandler filters too aggressively

### ISSUE THREAD

**Issue by Livven** [PowerShell/PSReadLine#1459]
## Description of the new feature/enhancement

The default history filter as implemented in #1058 is nice but including `key` causes too many false positives, as `key` is often used in a non-sensitive context e.g. as a synonym for ID.

I would suggest removing it but the question of course is whether minimizing false positives or false negatives should have priority here. IMO the filter should be less aggressive (i.e. filter less) by default for the following reasons:

- Not being able to find some commands in the history is confusing.
- There are bound to be many commands with secrets that will not be caught by the filter anyway.
- There was no filter for a long time, and e.g. bash does not have one either, so there should be a certain level of awareness about not entering secrets directly in commands.

**Comment by daxian-dbw** [comment]
I agree that `key` as a sensitive word is too aggressive. Some false positives that one can easily run into:
- `Set/Get/Remove-PSReadLineKeyHandler`
- `-KeyFilePath` parameter on all PowerShell remoting cmdlets, such as `Enter/New-PSSession`, `Invoke-Command`
- `-Key` parameter on CIM cmdlets such as `New/Get-CimInstance`, which specifies the properties that are used as keys.
- `Update-TypeData -DefaultKeyPropertySet`
-  `-Key` and `-SecureKey` parameter on `ConvertTo/ConvertFrom-SecureString` accept a byte array and a `SecureString` respectively, so they don't need to be removed from the history.

I think we should change `key` to `apikey`, which is what `Publish-Module/Script -NuGetApiKey` uses to accept a sensitive string.
