### ISSUE TITLE
PSReadline throws error on Windows Terminal when copying a selection using Shift+Home and Ctrc+C Binding

### ISSUE THREAD

**Issue by isawrub** [PowerShell/PSReadLine#1462]
### Environment
---
```
PS version: 6.2.3
PSReadline version: 2.0.1
os: 10.0.18363.720
PS file version: 6.2.3
HostName: Windows Terminal (wt.exe)
Host Version: 0.10.781.0
BufferWidth: Any
BufferHeight: Any
```

### Steps to reproduce
---
1. Start Windows Terminal  -> PowerShell Core 6 (Make sure key bindings are set for Ctrl+C for Copy)
2. Type/paste a command e.g. `npm install --save-dev @babel/core @babel/preset-env @babel/preset-react webpack webpack-cli webpack-dev-server babel-loader css-loader style-loader html-webpack-plugin`
3. Use Shift+Home to make selection
4. Press Ctrl-C in the terminal

### Expected behavior
---
Ctrl-C should copy the selected text, it should work as Ctrl-C usually do.

### Actual behavior
---

Ctrl-C causes an error in PSRreadLine.

Here's the exception and the last 200 keys.
### Exception:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.PowerShell.PSConsoleReadLine.ExecuteOnSTAThread(Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Last 200 Keys:
 ```
Backspace Backspace Backspace Backspace Backspace c d Spacebar . . Enter
 c l e a r Enter
 c o d e Spacebar . Enter
 n p m Spacebar i n s t a l l Spacebar - - s a v e - d e v Spacebar @ b a b e l / c o r e Spacebar @ b e b Backspace Backspace a b e l / p r e s e t - e n v Spacebar @ b a b e l / p r e s e t - t e a c t Spacebar w e b p a c k Spacebar w e
b p a c k - c l i Spacebar w e b p a c k - d e v - s e r v e r Spacebar b a b e l - l o a d e r Spacebar c s s Spacebar
Backspace - l o a d e r Spacebar s t y l e - l o a d e r Spacebar h t m l - w e b p a c k - p l u g i n Shift+Home Ctrl+c
```

**Comment by iSazonov** [comment]
@isawrub Please use Issue template to share all needed information.

**Comment by isawrub** [comment]
Done @iSazonov 
Hope I've got all the details in there.

**Comment by daxian-dbw** [comment]
@isawrub Are you sure you were using PSReadLine 2.0.1? PSReadLine 2.0.1 doesn't use `System.Windows.Forms` at all. The copy operation was changed to use Win32 APIs directly on Windows. Can you upgrade to [PowerShell 7.0.1](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.1) and see if you can reproduce the issue?

**Comment by isawrub** [comment]
The issue does not reproduce on my Powershell 7.0.1 installation, but I did a clean installation of Windows last week of 20H1 release, and did not upgrade to 7.0.1
