### ISSUE TITLE
Predictive IntelliSense

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/PSReadLine#1468]
Reference issue: [RFC#687](https://github.com/PowerShell/PSReadLine/issues/687)

Predictive IntelliSense is an addition to the interactive experience to assist in command discovery
and accelerate full command execution. This enables new and experienced users of PowerShell to
discover, edit, and execute full commands based on matching predictions from the users history or
additional provider.

<img width="967" alt="pi-static" src="https://user-images.githubusercontent.com/12662278/79141685-28593c00-7d6f-11ea-911f-0e780dc305a4.png">

Tab Completion has accelerated the success of both new and experienced PowerShell users. New users get the benefit of discovery; seeing available cmdlets and parameters as options while interactively typing. Experienced users receive the benefit of acceleration; typing less while using the <tab> key to quickly complete a command.

The increasing amount of technology translates to an increase in cmdlets and full command
complexity. Predictive IntelliSense is an addition to the concept of Tab Completion; helping the
user discover, build and edit full commands based on the users history or additional plugins.

The proposal is to add Predictive IntelliSense and enhancements for MenuComplete/Dynamic Help to the users interactive experience.

**Predictive IntelliSense Protoype** maybe found on [PSGallery](https://www.powershellgallery.com/packages/PSReadLine/2.1.0-beta1).

## Proposed technical implementation details

1. Predictive IntelliSense displays a best match command completion from command history. The
  prediction may change if a better match is found as the user types additional information. The
  predicted command may be accepted, edited, or ignored. It may be possible to support additional
  predictive providers.

<img width="967" alt="pi-static" src="https://user-images.githubusercontent.com/12662278/79141974-a9183800-7d6f-11ea-911e-a98eeb41c75f.png">

2. Predictions are searchable and may be edited. Additional key bindings may be added to the users
  Profile as in the example below:

```powershell
Set-PSReadLineKeyHandler -Key "Ctrl+d" -Function MenuComplete
Set-PSReadLineKeyHandler -Key "Ctrl+f" -Function ForwardWord
Set-PSReadLineKeyHandler -Key "Ctrl+b" -Function BackwardWord
Set-PSReadLineKeyHandler -Key "Ctrl+z" -Function Undo
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
```

3. Predictions are searchable based on the current cursor position.

- Searching history from cmdlet verb.

![pi-arrow-verb](https://user-images.githubusercontent.com/12662278/79142103-d664e600-7d6f-11ea-95dc-212beb9a7e7e.gif)

- Searching histroy from cmdlet noun.

![pi-arrow-Noun](https://user-images.githubusercontent.com/12662278/79142148-e4b30200-7d6f-11ea-9bdc-87d6bddb26e8.gif)

- Searching history from parameter.

![pi-arrow-param](https://user-images.githubusercontent.com/12662278/79142161-eb417980-7d6f-11ea-94b4-835529f82766.gif)

4. Predictions may be edited by stepping-through the parameters and arguments.

- Moving forward and backward using additional key bindings.

![pi-fb](https://user-images.githubusercontent.com/12662278/79142544-85a1bd00-7d70-11ea-90a3-5dd90e7630d1.gif)

- Note: Changing the parameter/argument, changes the prediction.

![pi-fb-arg](https://user-images.githubusercontent.com/12662278/79142450-61de7700-7d70-11ea-93b2-535e50fbd331.gif)

5. MenuComplete/Dynamic Help is a current feature of PSReadLine. When combined with Predictive IntelliSense, MenuComplete provides additonal discovery and help information.

- MenuComplete providing cmdlet discovery and help.

![mc-noun2](https://user-images.githubusercontent.com/12662278/79142653-ad912080-7d70-11ea-9b7a-bb880934cb6a.gif)

- MenuComplete providing parameter discovery and help.

![mc-param](https://user-images.githubusercontent.com/12662278/79142678-b5e95b80-7d70-11ea-98c0-07af4eb908dc.gif)

Open discussion items:

- Should the number of lines displayed for MenuComplete be restricted and what should that
  restriction be?
- Should an interactive cursor-based scroll bar for paging be included?
- What should the content of Dynamic Help include?

<img width="528" alt="mc-realestate" src="https://user-images.githubusercontent.com/12662278/79142803-f47f1600-7d70-11ea-8c77-c0056802ed8e.png">

6. Full cmdlet help is accessible using a key binding to access the help in a virtual terminal. An
   additional key binding will return the user from the virtual terminal to the previous screen.

<img width="1594" alt="dh-f1" src="https://user-images.githubusercontent.com/12662278/79142839-05c82280-7d71-11ea-9de1-c99f60ef7d54.png">

7. Predictive IntelliSense Accessibility is managed through the users profile.

<img width="967" alt="pi-color" src="https://user-images.githubusercontent.com/12662278/79142887-1bd5e300-7d71-11ea-843b-73898b4091b1.png">

<img width="972" alt="pi-color2" src="https://user-images.githubusercontent.com/12662278/79142918-22645a80-7d71-11ea-9304-13550d0dd2cc.png">

```powershell
Set-PSReadLineOption -Colors @{ Prediction = '#8A0303'}
Set-PSReadLineOption -Colors @{ Prediction = '#2F7004'}
```

![pi-color2-fb](https://user-images.githubusercontent.com/12662278/79142971-39a34800-7d71-11ea-9a16-a625278e3b98.gif)

Multiple color code values are supported currently in [PSReadLine](https://docs.microsoft.com/en-us/powershell/module/PSReadline/Set-PSReadlineOption?view=powershell-7).

Examples of different color code values:

```powershell
Set-PSReadLineOption -Colors @{ Prediction = 'DarkRed'}
 # Use a ConsoleColor enum
Set-PSReadLineOption -Colors @{ Prediction = [ConsoleColor]::DarkRed}
 # 24 bit color escape sequence
Set-PSReadLineOption -Colors @{ Prediction = "$([char]0x1b)[38;5;100m"}
 # RGB value
Set-PSReadLineOption -Colors @{ Prediction = "#8181f7"}
```

8. Predictive IntelliSense Extensibility

It may be possible to support 1st party and 3rd party predictive plugins.

**Comment by TylerLeonhardt** [comment]
I'd also love to see proposed PowerShell API additions so that this isn't a shell-only feature. Something like this would be really nice in editors as well, for example.

**Comment by Windos** [comment]
#### What should the content of Dynamic Help include?

For cmdlets/functions it should show the synopsis. Syntax sounds helpful, but on bigger commands with lots of parameters and parameter sets it's... unwieldy.

For parameters it should should show the helpmessage, that normally only surfaces at the mandatory prompt when you type `!?`

#### Predictive IntelliSense Extensibility

I want to have this available in VS Code.

As a module author, I want to be able to inject common use cases for my modules' functions.

**Comment by bergmeister** [comment]
Predictions should also be based on the current working directory. Example: In some local repos I might do a `git pull origin master` but in others I do a `git pull origin develop`

**Comment by sheldonhull** [comment]
This is amazing. Subscribed. I posted in the slack channel for vscode asking what magical vodoo was happening, as I had never seen this and it felt like such a natural thing to have. Didn't realize it got rolled out with the insiders powershell extension. Looking forward to the improvements. #win

**Comment by p0W3RH311** [comment]
it's work on non  VT ?

**Comment by TylerLeonhardt** [comment]
One other thing about the Dynamic Help feature... the PowerShell extension has been providing this experience for a while (see the box on the right):

![image](https://user-images.githubusercontent.com/2644648/79240634-e4c20900-7e26-11ea-8958-2b85e7ee3985.png)

It's called the [`completionItem/resolve` request as a part of the language server protocol](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#completionItem_resolve).

The idea here is... for a completion, give me _more details_ about it... but only send the request for more details when it is highlighted.

However, the PowerShell extension goes a step further to provide syntax as you're typing parameters too:

![image](https://user-images.githubusercontent.com/2644648/79240982-4a15fa00-7e27-11ea-95af-83f45b0d2097.png)

VS Code decided it was a good idea to separate this into it's own request called the [Signature Help Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_signatureHelp).

There are a lot of learning from the PowerShell extension and LSP that can be leveraged in the design of the features outlined here. Please consider them in the design.

**Comment by jszabo98** [comment]
This is pretty cool.  The first thing I do in my $profile is

```powershell
set-psreadlineoption -editmode emacs
```
so that pressing tab lists all the choices at once.

**Comment by IarwainBen-adar** [comment]
I just upgraded to the prerelease version of PSReadLine and I see real potential for this feature. As it is now, though, I find the history-biased suggestions a bit frustrating. Consider this scenario:
- current working directory is `c:\foo\bar\baz`
- at some point in the past, I have entered the command `cd ..\qux`
- unfortunately, `c:\foo\bar` _has no subdirectory_ named `qux`
- nevertheless, while sitting at `c:\foo\bar\baz`, as soon as I type `cd ..` a ghostly `\qux` is suggested to me — a completely invalid path

Overall this seems far less useful than it would be if it were suggesting valid completions of the partially-typed command line. I'm fairly new to PSReadLine, so I'm sorry if this is a naive question, but is it possible to configure this behavior? Or to validate potential completions before suggesting them (and then not suggest invalid completions at all)?

**Comment by brunovieira97** [comment]
> I just upgraded to the prerelease version of PSReadLine and I see real potential for this feature. As it is now, though, I find the history-biased suggestions a bit frustrating. Consider this scenario:
> 
> * current working directory is `c:\foo\bar\baz`
> * at some point in the past, I have entered the command `cd ..\qux`
> * unfortunately, `c:\foo\bar` _has no subdirectory_ named `qux`
> * nevertheless, while sitting at `c:\foo\bar\baz`, as soon as I type `cd ..` a ghostly `\qux` is suggested to me — a completely invalid path
> 
> Overall this seems far less useful than it would be if it were suggesting valid completions of the partially-typed command line. I'm fairly new to PSReadLine, so I'm sorry if this is a naive question, but is it possible to configure this behavior? Or to validate potential completions before suggesting them (and then not suggest invalid completions at all)?

AFAIK this happens because, currently, the only prediction source available is the commands history. Since it's a WIP, there's room for improvement, and probably the first would be to get history entries and then only let through (to the user) the ones that really would apply to his current terminal state (directory, Git repo, etc).

**Comment by rdhar** [comment]
Looking at #687, it looks like some progress has been made with the following:

```powershell
# Search auto-completion from history
Set-PSReadLineOption -HistorySearchCursorMovesToEnd
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward

# Show auto-complete predictions from history
Set-PSReadLineOption -ShowToolTips
Set-PSReadLineOption -PredictionSource history
Get-PSReadLineOption | ForEach-Object predictionsource
```

That said, still nowhere near as feature-rich as PowerShell's VS Code extension.

**Comment by theJasonHelmick** [comment]
[This feature](https://devblogs.microsoft.com/powershell/announcing-psreadline-2-2-beta-2-with-dynamic-help/), along with Dynamic Help, is currently in PSReadLine 2.2.0-beta4 and is available on the [Powershell Gallery](https://www.powershellgallery.com/packages/PSReadLine/2.2.0-beta4). Please file issues for feedback in the PSReadLine repository.

Predictive IntelliSense is planned to ship GA in January 2022.

**Comment by ToxicSmurf** [comment]
Sorry but how do I turn this off?

**Comment by gwitsch** [comment]
How can i turn this off?

**Comment by gwitsch** [comment]
Found the solution to disable it here:
https://devblogs.microsoft.com/powershell/announcing-psreadline-2-1-with-predictive-intellisense/?WT.mc_id=-blog-scottha

Running this command, disabled it
`Set-PSReadLineOption -PredictionSource None`

The trick to set the option for all new terminals, was to update the PowerShell profile.
First type `notepad $PROFILE` in the terminal and then add the following content to the opened file:
```
Import-Module PSReadLine

Set-PSReadLineOption -PredictionSource None
```

Save the file and reopen the terminal to verify the option.

**Comment by jiasli** [comment]
@gwitsch, thanks for the information. It is super helpful.

Apparently, not everyone likes `InlineView` for `-PredictionViewStyle` (see this [reddit post](https://www.reddit.com/r/PowerShell/comments/108s64g/i_dont_like_predictive_intellisense_in_73/)). Personally, I find it distracting and prefer `ListView`.

However, instead of totally disabling Predictive IntelliSense using [`Set-PSReadLineOption -PredictionSource None`](https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-7.3#enable-predictive-intellisense), is it possible to keep its functionality but not automatically show the suggestions (both `InlineView` and `ListView`)? In that case, I can manually trigger the `ListView` with some sort of shortcut, such as <kbd>F2</kbd>([`SwitchPredictionView`](https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline_functions?view=powershell-7.3#switchpredictionview)). I currently use <kbd>F8</kbd> ([`HistorySearchBackward`](https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline_functions?view=powershell-7.3#historysearchbackward)) but it is apparently not as fancy as Predictive IntelliSense `ListView`.

Most IDEs support turning suggestions off.

PyCharm:

![image](https://github.com/PowerShell/PSReadLine/assets/4003950/eb8b306a-93a8-4fd5-9343-6577f5d64a40)

VS Code: https://code.visualstudio.com/docs/editor/intellisense#_settings
