### ISSUE TITLE
Last 4 Keys:  & Space C : Exception: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by NIATHFP** [PowerShell/PSReadLine#1472]

**Comment by NIATHFP** [comment]
import matplotlib.pyplot as plt

squares = [-2, 4, 9, 16, 25]
plt.plot(squares)
plt.show()


Above are the codes

**Comment by iSazonov** [comment]
See #1306
And please remove long text from header

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
