### ISSUE TITLE
Error While Running Script

### ISSUE THREAD

**Issue by INGourav** [PowerShell/PSReadLine#1476]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -19.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

-------------------------------------------------------------------------------------------------------------

Script is : -

$credentials = Get-Credential

# If we many server then use csv file with IP and uncomment below line by removing # symbol but we have to make sure that it should be domain credentials.
#Servers  = Import-CSV C:\temp\Servers.csv

# If we have one server then use below line
$Servers  = "192.168.xx.xx" , "localhost"

ForEach( $Server in $Servers)
{

$DISKS = Get-wmiobject  Win32_LogicalDisk  -Credential $credentials -computername $server -ErrorAction SilentlyContinue -filter "DriveType= 3"
FOREACH ($objdisk in $DISKS)
{
$total = "{0:N0}" -f ($objDisk.Size/1MB)
$Free = "{0:N0}" -f ($objDisk.Freespace/1MB)
$Used = "{0:N0}" -f ((($objDisk.Size)-($objDisk.Freespace))/1MB)
$Drive = $objDisk.DeviceID
$UsedPercent = "{0:N0}" -f ((($objDisk.Size)-($objDisk.Freespace))*100/$objDisk.Size)
write-host ""Message.$Drive": $Used MB used out of total $total MB i.e. $UsedPercent %"
write-host ""Statistic.$Drive": $UsedPercent"
}
}

--------------------------------------------------------------------------------------------------------------

Name                                                             Value
----                                                             -----
PSVersion                                      5.1.18362.628
PSEdition                                      Desktop
PSCompatibleVersions                {1.0, 2.0, 3.0, 4.0...}
BuildVersion                               10.0.18362.628
CLRVersion                                 4.0.30319.42000
WSManStackVersion                  3.0
PSRemotingProtocolVersion      2.3
SerializationVersion                   1.1.0.1

**Comment by iSazonov** [comment]
See #1306

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
