### ISSUE TITLE
control +scroll , control + L

### ISSUE THREAD

**Issue by moyue83** [PowerShell/PSReadLine#1479]
When zooming in by control + scrolling to a very high font and press control + L to clear the screen will throw the following exception:

Last 37 Keys:
 Ctrl+l Ctrl+Enter l s Enter
 Ctrl+l Ctrl+l Enter
 Enter
 c l e a r Enter
 Ctrl+l Ctrl+l c l e a r Enter
 Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l c l e Enter
 l s Enter
 Ctrl+l Ctrl+l

Exception:
System.IO.IOException: De parameter is onjuist.

   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.Console.SetWindowPosition(Int32 left, Int32 top)
   bij Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   bij Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bij Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
Are you using the latest 2.0.1 version of the PSReadLine module? This issue was fixed (see #1315), and you can get the 2.0.1 version of PSReadLine from PowerShellGallery.
