### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#1490]
上 200 个密钥:
 d i o \ S h a r e d \ P y t h o n 3 7 _ 6 4 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ C o n r a d _ S h e n \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 4 . 7 4 9 8 6 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ w h e e l s \ d e b u g p y \ l a u n c h e r ' Space ' e : \ A L L C o d e \ P y t h o n C o d e \ C o d e s \ w t f . p y ' Space Enter  

异常:
System.ArgumentOutOfRangeException: 该
值必须大于或等于零，且必须小于控制台缓
冲区在该维度的大小。
参数名: top
实际值是 -2。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See #1306

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
