### ISSUE TITLE
System.IO.IOException when trying to resize the window using keyboard

### ISSUE THREAD

**Issue by houssam2293** [PowerShell/PSReadLine#1497]
here is the exception:

Oups, un problème s'est produit. Signalez ce bogue avec les détails ci-dessous.
Signaler sur GitHub : https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Dernières 161 touches :
 1 UpArrow Enter
 UpArrow UpArrow DownArrow DownArrow DownArrow p y t h o n Space - m Space p i p Space f r e e z e Space > Space r e q u i r e m e n t s . t x t Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 ` Ctrl+` Ctrl+` Ctrl+PageUp Ctrl+PageUp

Exception :
System.IO.IOException: Paramètre incorrect.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.Console.SetWindowPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUpLine(Nullable`1 key, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
@houssam2293 I recommend you to use the latest 2.0.1 version of PSReadLine (https://www.powershellgallery.com/packages/PSReadLine/2.0.1).

As for the reported exception, see https://github.com/PowerShell/PSReadLine/issues/551#issuecomment-341856386. Quoted below:

> I've reviewed PSReadLine and the .Net api that is used and this seems like an impossible condition. The .Net api `Console.SetWindowsPosition` validates the parameters before calling the Win32 api, yet it's the Win32 api reporting the error.
>
> As this was not reproducible, I'll chalk this up to some random corruption in conhost - it wouldn't be the first transient error like this that I've seen.
>
>Sorry I can't do anything about it, but thanks for reporting it.
