### ISSUE TITLE
Debugging Isuues VS code cpp file : Try the new cross-platform PowerShell https://aka.ms/pscore6

### ISSUE THREAD

**Issue by asmat-wecan** [PowerShell/PSReadLine#1504]
Code: 
#include<iostream>
using namespace std;
int main(int argc, const char** argv) {
   
   int x = 10;
   int y = 20;
    cout<<"Hello World"<<endl;
    cout<<x+y<<endl;
  //  system("pause");

    return 0;
}

Terminal: 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 799ms.
(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-qvxgq3fv.1mn' '--stdout=Microsoft-MIEngine-Out-krd1tb2s.vru' '--stderr=Microsoft-MIEngine-Error-st4wct4x.41j' '--pid=Microsoft-MIEngine-Pid-uuvcegyf.4dy' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi'
(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ef3jxypy.tfh' '--stdout=Microsoft-MIEngine-Out-nlqpdtrh.urc' '--stderr=Microsoft-MIEngine-Error-m5zblruj.rkq' '--pid=Microsoft-MIEngine-Pid-pw2tecsx.2zo' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi'
(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine(base) PS E:\CPP>  & 'c:\Users\aul018\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-r0npqwlx.gft' '--stdout=Microsoft-MIEngine-Out-3mi32pae.mi1' '--stderr=Microsoft-MIEngine-Error-220u1ma1.5ju' '--pid=Microsoft-MIEngine-Pid-vwmqvtxw.wap' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi'
(base) PS E:\CPP>

Debug Console : 
=thread-group-added,id="i1"
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
=cmd-param-changed,param="args",value="2>CON 1>CON <CON"
[New Thread 11628.0x34f0]
[New Thread 11628.0x3934]
[New Thread 11628.0x2da0]
[New Thread 11628.0x1474]
Loaded 'C:\WINDOWS\SysWOW64\kernel32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\KernelBase.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\apphelp.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\AcLayers.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\msvcrt.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\user32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\win32u.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\gdi32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\gdi32full.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\msvcp_win.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\ucrtbase.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\shell32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\cfgmgr32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\SHCore.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\rpcrt4.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\sspicli.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\cryptbase.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\bcryptprimitives.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\sechost.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\combase.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\windows.storage.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\advapi32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\profapi.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\powrprof.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\umpdc.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\shlwapi.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\kernel.appcore.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\cryptsp.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\oleaut32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\setupapi.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\bcrypt.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\mpr.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\sfc.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\winspool.drv'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\propsys.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\IPHLPAPI.DLL'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\sfc_os.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\SysWOW64\imm32.dll'. Symbols loaded.

**Comment by daxian-dbw** [comment]
@Asmat87 I don't understand what is this issue about and don't believe this is a PSReadLine issue.
Please follow the bug template when opening a new issue.
