### ISSUE TITLE
PSReadLine

### ISSUE THREAD

**Issue by abbes-mebrouki** [PowerShell/PSReadLine#1509]
**I got this issue after leaving PowerShell open in the windows terminal over 24h.**
-------------------------------------------------------------------------------

Last 200 Keys:
 Space . . Space . . Space . . Enter
 c d Space . . Enter
 c d / / Backspace Backspace UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 c d Space U s e r s Ctrl+Alt+\ A b b e s Enter
 l s Backspace Backspace Backspace Ctrl+l m o n g o Enter
 Ctrl+l m o n g o d Space - f Space ' Backspace " " LeftArrow C : Ctrl+Alt+\ P r o g r a m Space F i l e s Ctrl+Alt+\ M o n g o D B Ctrl+Alt+\ S e r v e r Ctrl+Alt+\ 4 . 2 Ctrl+Alt+\ b i n Ctrl+Alt+\ m o n g o d . v f Backspace Backspace c f g Enter
 UpArrow Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -18.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
The issue related to `Ctrl+l` was fixed (see #1315). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
