### ISSUE TITLE
Error al presionar Ctrl+l

### ISSUE THREAD

**Issue by rjmp1991** [PowerShell/PSReadLine#1515]
-----------------------------------------------------------------------
Últimas 4 claves:
 l s Enter
 Ctrl+l

Excepción:
System.IO.IOException: El parámetro no es correcto.

   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.Console.SetWindowPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by iSazonov** [comment]
@rjmp1991 Please use a script from issue template to share all information and please add repo steps.

**Comment by daxian-dbw** [comment]
@rjmp1991 The issue related to `Ctrl+l` was fixed, see #1315 for more info. Please upgrade to the `2.0.1` version of PSReadLine from PowerShell Gallery, and give it a go.
