### ISSUE TITLE
VS code is very slow

### ISSUE THREAD

**Issue by satya1657** [PowerShell/PSReadLine#1516]
My IDE VS Code is very slow generally I use it to write c++ codes and run in it. But it is very slow I have to wait about 30 second for a program to run. it is giving an error also which is given below.

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

what should I do?

**Comment by daxian-dbw** [comment]
@satya1657 You didn't provide the whole details of the error report. The URL `https://github.com/lzybkr/PSReadLine/issues/new` indicates you are using a fairly old version of PSReadLine, so the issue you ran into was likely fixed. Please upgrade to the `2.0.1` version of PSReadLine from PowerShell Gallery and give it a go.

As for VS Code is being slow for you, I don't think it's related to PSReadLine. Maybe you can seek help from https://github.com/microsoft/vscode
