### ISSUE TITLE
error

### ISSUE THREAD

**Issue by matumoto1234** [PowerShell/PSReadLine#1531]
前 200 個のキー:
 n n e r F i l e Space } Space ; Space i f Space ( $ ? ) Space { Space . \ t e m p C o d e R u n n e r F i l e Space } Enter
 Enter
 g c c Space - - v e r s i o n Enter
 g + + Space - - v e r s i o n n Backspace Enter
 c d Space " c : \ U s e r s \ m a t u m \ O n e D r i v e \ デ ス ク 
ト ッ プ \ コ ー ド 入 れ \ a t c o d e r \ " Space ; Space i f Space 
( $ ? ) Space { Space g + + Space t e m p l a t e . c p p Space - l m 
Space - o Space t e m p l a t e Space } Space ; Space i f Space ( $ ? 
) Space { Space . \ t e m p l a t e Space } Enter

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの次元 
のバッファー サイズ未満を指定しなければなりません。
パラメーター名:left
実際の値は -1 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)       
   場所 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
Upgrade to latest version. See #1306.

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
