### ISSUE TITLE
「問題が発生しました。このバグを以下の詳細と共に報告してください。」だそうですので、報告します。

### ISSUE THREAD

**Issue by nkutomi** [PowerShell/PSReadLine#1535]
過去の履歴から実行しようと、上ボタンを押しているときに、複数行の履歴が表示された瞬間、毎回このエラーです。

----
問題が発生しました。このバグを以下の詳細と共に報告してください。
GitHub で報告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
直前 14 個のキー:
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow DownArrow

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの次元のバッファー サイズ未満を指定しなければなりません。
パラメーター名:top
実際の値は -33 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   場所 Microsoft.PowerShell.PSConsoleReadLine.NextHistory(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
