### ISSUE TITLE
I don't know how to set the color of the prompt, as shown in the figure, the color is too light. When the background color of Windows terminal is white, the effect will be more obvious. Right

### ISSUE THREAD

**Issue by awesomezao** [PowerShell/PSReadLine#1550]
I searched a lot of information, but it didn't work and there were no similar problems. Maybe my English was too poor
![](https://gitee.com/ruoyiwen/img/raw/master/blog/20200525225859.png)

**Comment by daxian-dbw** [comment]
@lyandzao Do you mean the color of the predictive suggestion text? You can change the color by `Set-PSReadLineOption -Colors @{ Prediction = '<your-choice-of-color>' }`.
I submitted https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6029 to include the `Prediction` color setting in the doc.

**Comment by awesomezao** [comment]
@daxian-dbw thanks a lot, it works!
