### ISSUE TITLE
Broken after writing " in windows

### ISSUE THREAD

**Issue by Carles11** [PowerShell/PSReadLine#1554]
This is what I get (and I cannot further write " on buildIn terminal.

git commit -m 
################################################

Leider ist ein Fehler aufgetreten. Geben Sie mit diesem Fehler folgende Details an.
Bericht auf GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Letzte 31 Tasten:
 c l e a r Enter
 g i t Space a d d Space . Enter
 g i t Space c o m m i t Space - m Space "

Ausnahme:
System.ArgumentOutOfRangeException: Der Wert muss größer als oder gleich 0 (null) sein und geringer als die Puffergröße der Konsole in dieser Dimension.
Parametername: left
Der tatsächliche Wert war -1.
   bei System.Console.SetCursorPosition(Int32 left, Int32 
top)
   bei Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   bei Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   bei Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   bei Microsoft.PowerShell.PSConsoleReadLine.Insert(Char 
c)
   bei Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean 
ignoreIfNoAction, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bei Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)        
-----------------------------------------------------------------------

**Comment by iSazonov** [comment]
See #1306. You should use latest version.

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
