### ISSUE TITLE
PSReadLine conflicts with WinCompose in PowerShell 7 (but not in Windows Terminal!)

### ISSUE THREAD

**Issue by IarwainBen-adar** [PowerShell/PSReadLine#1560]
## Environment

```none
PS version: 7.0.1
PSReadline version: 2.1.0-beta1
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.1.0
HostName: ConsoleHost
BufferWidth: 157
BufferHeight: 9001
```

## Steps to reproduce

1. Install [WinCompose](https://github.com/samhocevar/wincompose) v0.9.4 (default settings: <kbd>right Alt</kbd> key set to <kbd>compose</kbd>)
1. Open PowerShell 7
1. Ensure that PowerShell 7 has the PSReadLine module loaded `Import-Module PSReadLine`
1. Ensure that PowerShell 7 has `$OutputEncoding`, `[System.Console]::InputEncoding`, and `[System.Console]::OutputEncoding` all set to UTF-8
1. At the PowerShell 7 prompt, type Unicode character composition `å` via compose key sequence <kbd>compose</kbd><kbd>o</kbd><kbd>a</kbd> = `å`
1. Observe that no character is sent to PowerShell 7 (no Unicode error character, no fallback character `a` either)
1. At the PowerShell 7 prompt, type <kbd>Alt</kbd><kbd>0</kbd><kbd>2</kbd><kbd>2</kbd><kbd>9</kbd> and observe that `å` is sent to the shell when typed via <kbd>Alt</kbd> numpad code input
1. Copy/paste the `å` character to PowerShell and observe that `å` is sent to the shell when pasted from the clipboard
1. Unload the PSReadLine module with `Remove-Module PSReadLine`
1. With the PSReadLine module unloaded, repeat the compose key test in PowerShell 7 by typing <kbd>compose</kbd><kbd>o</kbd><kbd>a</kbd> and observe that the `å` character is sent to PowerShell correctly now that the PSReadLine module is unloaded
1. Open a PowerShell 7 tab in Windows Terminal
1. Ensure that the Windows Terminal-hosted PowerShell 7 tab has the PSReadLine module loaded `Import-Module PSReadLine`
1. Repeat the compose key test in the Windows Terminal-hosted PowerShell 7 tab and observe that <kbd>compose</kbd><kbd>o</kbd><kbd>a</kbd> **does send** `å` to the Windows Terminal shell **correctly**, even with the PSReadLine module loaded!

## Expected behavior

I would expect PSReadLine to behave consistently between PowerShell 7 and a Windows Terminal-hosted PowerShell 7 tab

## Actual behavior

When the PSReadLine module is loaded, it seems to disable compose key Unicode character compositions in PowerShell 7, but not in Windows Terminal-hosted PowerShell 7 tabs

**Comment by samhocevar** [comment]
For the record, WinCompose uses the [`SendInput()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput) function to send characters to applications.

**Comment by virgoparna** [comment]
Windows 10 builtin PSReadLine also has problem... I can enter lower case characters with WinCompose, but not Upper Case characters. I have CapsLock as Compose key:
<kbd>CapsLock</kbd><kbd>o</kbd><kbd>a</kbd>=<kbd>å</kbd>
<kbd>CapsLock</kbd><kbd>o</kbd><kbd>A</kbd>-nothing appears, expected <kbd>Å</kbd>
That is in stand-alone PowerShell window and in Windows Terminal.
$(Get-Host).Version: 5.1.19041.906
PSReadLine: 2.0.0
After upgrading PSReadLine to 2.1.0 lower case characters also stop working in standard Windows PowerShell window (just execute powershell), but both lower case and upper case work in Windows Terminal.

**Comment by StevenBucher98** [comment]
@IarwainBen-adar is this still an issue on the latest version of PSReadLine?

**Comment by virgoparna** [comment]
Seems to work. I had forgot because I pretty much only use Windows Terminal
```
> $(Get-Host).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  2364

> Get-InstalledModule PSReadLine
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.2.3      PSReadLine                          PSGallery            Great command line editing in the PowerShell con...

> åÅžŽöÖõÕ

all entered with WinCompose. In standard Windows Console Window. Windows 10 22H2 (19045.2604)
```

**Comment by StevenBucher98** [comment]
Closing and can reopen if folks still come across this issue 😄
