### ISSUE TITLE
cmd terminal throws OutOfRangeException

### ISSUE THREAD

**Issue by JTF-2** [PowerShell/PSReadLine#1561]
Opened a cmd line terminal on a win10 machine; when I pressed "Ctrl v" the message below appeared, with instructions to report it here.
![Bug Screenshot](https://user-images.githubusercontent.com/31679917/83065469-64431a80-a018-11ea-99d0-52645eafae87.PNG)

> Last 1 keys
> 
> Ctrl+v
> 
> Exception:
> System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
> Parameter name: top
> Actual value was -1.
>    at System.Console.SetCursorPosition(Int32 left, Int32 top)
>    at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
>    at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
>    at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
>    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
Thanks for the reporting and the screenshot. This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
