### ISSUE TITLE
'WinIOError' when pressing 'PageUp'

### ISSUE THREAD

**Issue by Wrawller117** [PowerShell/PSReadLine#1564]
Last 47 Keys:
 l s Enter
 c l e a r Enter
 . / Backspace Backspace c d Space / / Enter
 c d Space . . Enter
 c d Space . . Enter
 c d Space . . Enter
 l s Enter
 F o r c e Space PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
What version of the PSReadLine are you using? Please upgrade to the `2.0.1` version of PSReadLine and give it a go. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.

**Comment by ret394** [comment]
was reproducible. went away for a while. trigger enter the text then press PageUp or PageDown.
sample text - das

2.0.1 version PSReadLine
thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by daxian-dbw** [comment]
@ret394 Can you please provide the repro steps?
Also please run the following script to get the environment data, thanks!

```powershell
& {
    $hostName = $Host.Name
    if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
        $id = $PID
        $inWindowsTerminal = $false
        while ($true) {
            $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
            if (!$p -or !$p.Name) { break }
            if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
            $id = $p.ParentProcessId
        }
        if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
    }

    "`nPS version: $($PSVersionTable.PSVersion)"
    $m = Get-Module PSReadline
    $v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
    if ($pre) { $v = "$v-$pre" }
    "PSReadline version: $v"
    if ($IsLinux -or $IsMacOS) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
    "HostName: $hostName"
    "BufferWidth: $([console]::BufferWidth)"
    "BufferHeight: $([console]::BufferHeight)`n"
}
```
