### ISSUE TITLE
If input is redirected on startup, PSReadline causes the process to crash

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#158]
If you start PowerShell with input redirected, e.g. with

```
Start-Process -RedirectStandardInput input.txt -FilePath powershell -NoNewWindow
```

Then powershell will crash if PSReadline is loaded from your profile.

**Comment by OpusKrokus** [comment]
This is old, but appears to still be occurring.  In my use case, it is because I am trying to execute a script from within TextPad.  I have seen several tickets closed as a duplicate because they are referencing the same issue.  I would imagine that this will continue due to the error output giving specific instructions to "Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new".

As a developer, I understand how and why stuff keeps getting shuffled down in the backlog.  But with the issue being about two years old and no updates, are there any plans to fix it?

**Comment by lzybkr** [comment]
Plans - yes, but there are some difficulties.  Lack of time is the biggest issue, but without full pseudo-tty support, many key bindings won't be available.

The version shipping in Windows 10 Anniversary edition gracefully falls back to work as though PSReadline isn't loaded instead of reporting this error, I just haven't updated the release published on GitHub.

**Comment by erichiller** [comment]
I am running Windows Creators update on Host and Client using Powershell SSH and am still receiving this error, has there been any update with this issue?

**Comment by lzybkr** [comment]
I have a change in this repo (but not in Windows) that gracefully fails when input is redirected, but it falls back to not using PSReadline, so there's little difference compared to just removing the module like this: `Remove-Module PSReadline`

As for why there hasn't been any progress - this is a side project for me and I don't hit this problem, so I haven't find the right combination of time and motivation to deal with it. I do think I will fix it at some point, but I'd also be happy for a PR - I might have some ideas on how to tackle the problem as well.

**Comment by erichiller** [comment]
Would the change which allows for a graceful fail be present in the PsGet package? I forcefully upgraded this evening and have the exact same issue:

```powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\ehiller>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
No, that package matches the code in Windows 10.

**Comment by erichiller** [comment]
@lzybkr - ah ok ; When you say  '_I have a change in this repo_' how do I run this most recent code? The github archival link is antiquated. (2015 file dates) Or do you mean it is in source only form and must be compiled still?

I'd be interested to hear your ideas (If you'd be interested in sharing) While I am currently in the same boat as you, at least as far as time is concerned, I have motivation occasionally.

**Comment by lzybkr** [comment]
You can grab a build out of appveyor - the latest from master is [here](https://ci.appveyor.com/project/lzybkr/psreadline/build/1.0.121) or if you are willing to test the next major release I'm working on, grab any recent build from the ansi_render branch [here](https://ci.appveyor.com/project/lzybkr/psreadline/history).

The basic idea on handling stdin is to map the characters sent by the terminal to instances of `ConsoleKey`. Basic keys are easy, but modified keys get interesting because the terminal sends multiple characters. The easiest way to get started is to call [SetConsoleMode](https://docs.microsoft.com/en-us/windows/console/setconsolemode) on the standard input handle with ENABLE_VIRTUAL_TERMINAL_INPUT set, then read directly from `Console.In`. If you are on Linux or WSL, it's useful to run `showkey -a` to see the characters the terminal is sending for a particular keystroke:

```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[a      27 0033 0x1b
         97 0141 0x61
^A        1 0001 0x01
^[^A     27 0033 0x1b
          1 0001 0x01
```

Here I typed `Alt+a` `Ctrl+a` `Alt+Ctrl+a`, so three keystrokes total, but the terminal sent 5 characters. I believe terminal emulators will look for extra characters after specific characters like ESC (0x1b), but they do so with a limited timeout - on timeout they just assume the key is ESC. This is why tools like Emacs or PSReadline map `ESC` `b` and `Alt+b` to the same function.

**Comment by parkovski** [comment]
What needs to be done to enable this after the recent merges? I'd really like to be able to have a tmux session with PowerShell on Windows, and I can help get this to that point if I know what needs to be done.

**Comment by lzybkr** [comment]
@parkovski - that would be awesome.

The general approach is to map `char` input to `ConsoleKeyInfo` - this can be done in `ReadOneOrMoreKeys` - basically just go down a different code path when input is redirected.

I have a couple thoughts on mapping `char` input to `ConsoleKeyInfo`. .Net Core does this already in a way that (mostly) works for PSReadLine (with one relatively useful key not correctly mapped). This mapping only works on non-Windows platforms, so I'm hoping for a solution that doesn't rely on that code. The mapping done by .Net Core is generic - it shouldn't matter what terminal type you use because it uses the `terminfo` database so it can map character input properly.

Because this should support Windows as well, `terminfo` is not available, so I was thinking of just supporting the only terminal mode that Windows supports which is documented [here](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) - search for `Input Sequences`.

Note that the latest change I made is somewhat more flexible in the properties in `ConsoleKeyInfo` in an attempt to:
1. support Linux better by trusting the `KeyChar` as much as possible
2. ideally make this work easier
3. be more portable between different keyboard layouts

Hopefully this is enough to get you started, and if you need more help, ask away, here or email (in my profile).

**Comment by lzybkr** [comment]
See #564.
