### ISSUE TITLE
Terminal - Zoom then Multi-Line Paste Causes Error

### ISSUE THREAD

**Issue by rgroefer** [PowerShell/PSReadLine#1580]
Problem:
Error when pasting content with 3 or more lines (some type of carriage return) into the terminal after zooming in or out.

Reproduce:
Using Terminal, open a Windows PowerShell tab, zoom in, then paste 3 or more lines of content using CTRL+V.
You may zoom by CTRL+= or CTRL+Mouse-Wheel-Up.  Both reproduce the error.
PowerShell (7+) does not appear to have the same problem (as often).  I got it maybe once, but Windows PowerShell throw the error every time.

This result from this code seems to be enough to trigger the error:
1..3 | Clip

Workaround:
Hit 'Enter' immediately after zooming and before you paste.  You can also just type any letter/number and then delete it.  As long as you break the sequence of zoom-paste, then it seems fine.

Shall we call this a win for PowerShell (7) and just drop Windows PowerShell? ;)

System:
Name                                         Value
----                                             -----
PSVersion                                   5.1.18362.752
PSEdition                                   Desktop
PSCompatibleVersions               {1.0, 2.0, 3.0, 4.0...}
BuildVersion                               10.0.18362.752
CLRVersion                                 4.0.30319.42000
WSManStackVersion                  3.0
PSRemotingProtocolVersion      2.3
SerializationVersion                   1.1.0.1

-----------------------------------------------------------------------
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
What version of PSReadLine are you using for Windows PowerShell? You can run the following script to get the environment data in your Windows PowerShell:

```powershell
& {
    $hostName = $Host.Name
    if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
        $id = $PID
        $inWindowsTerminal = $false
        while ($true) {
            $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
            if (!$p -or !$p.Name) { break }
            if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
            $id = $p.ParentProcessId
        }
        if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
    }

    "`nPS version: $($PSVersionTable.PSVersion)"
    $m = Get-Module PSReadline
    $v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
    if ($pre) { $v = "$v-$pre" }
    "PSReadline version: $v"
    if ($IsLinux -or $IsMacOS) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
    "HostName: $hostName"
    "BufferWidth: $([console]::BufferWidth)"
    "BufferHeight: $([console]::BufferHeight)`n"
}
```

-----------------------------------------------------------------------

This issue looks to me was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. If you see the same exception after upgrading to 2.0.1 version of PSReadLine, then please re-open this issue.
