### ISSUE TITLE
When more than one Powershell instance open, PSReadLine does not save history correctly

### ISSUE THREAD

**Issue by darthstark1138** [PowerShell/PSReadLine#1581]
## Environment
Happens in all Powershell versions and hosts
```
PS version: 7.0.1
PSReadline version: 2.0.0
os: 10.0.19041.320 (WinBuild.160101.0800)
PS file version: 7.0.1.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 65

PS version: 7.0.1
PSReadline version: 2.0.0
os: 10.0.19041.320 (WinBuild.160101.0800)
PS file version: 7.0.1.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001

PS version: 5.1.19041.1
PSReadline version: 2.0.0-beta2
os: 10.0.19041.320 (WinBuild.160101.0800)
PS file version: 10.0.19041.320 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000
```

## Steps to reproduce

1. Open 2 Powershell windows (any version or host)
2. On the 1st window type "cd ~\Downloads"
3. On the 2nd window type "cd ~\Documents"
4. On the 1st window type "cd ~\Pictures"
5. Type "(Get-Content (Get-PSReadlineOption | select -expand HistorySavePath))[-3..-1]"

## Expected behavior

Contents of :

```
cd ~\Downloads
cd ~\Documents
cd ~\Pictures
```

## Actual behavior

```
cd ~\Downloads
cd ~\Downloads
cd ~\Downloads
```

**Comment by vexx32** [comment]
Please update to the latest PSReadLine version and see if that resolves the issue?
