### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by oichievas** [PowerShell/PSReadLine#1583]
Последние клавиши 200:
 e . Ctrl+Enter Space Space Space Space Space Space Space Space / / Space T o Space l e a r n Space m o r e Space a b o u t Space p a n e s , Space v i s i t Space h t t p s : / / a k a . m s / t e r m i n a l - p a n e s Ctrl+Enter Space Space Space Space Space Space Space Space { Space " c o m m a n d " : Space { Space " a c t i o n " : Space " s p l i t P a n e " , Space " s p l i t " : Space " a u t o " , Space " s p l i t M o d e " : Space " d u p l i c a t e " Space } , Space " k e y s " : Space " a l t + s h i f t + d " Space } Ctrl+Enter Space Space Space Space ] Ctrl+Enter } Ctrl+Enter

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было -58.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
