### ISSUE TITLE
Bug please help

### ISSUE THREAD

**Issue by PedroViannaSilveira** [PowerShell/PSReadLine#1585]
Últimas 117 Chaves:
 & Space " C : Ctrl+Alt+/ P r o g r a m Space F i l e s Ctrl+Alt+/ P y t h o n 3 8 Ctrl+Alt+/ p y t h o n . e x e " Space " c : Ctrl+Alt+/ U s e r s Ctrl+Alt+/ P e d r o Ctrl+Alt+/ O n e D r i v e Ctrl+Alt+/ D o c u m e n t o s Ctrl+Alt+/ F A T E C Ctrl+Alt+/ L o 
g i c a Space d e Space p r o g r a m a c a o Ctrl+Alt+/ f u n c a o 1 . p y " Enter

Exceção:
System.ArgumentOutOfRangeException: O valor deve ser maior ou igual a zero e menor que o tamanho do buffer do console nessa dimensão.
Nome do parâmetro: left
Valor real era -2.
   em System.Console.SetCursorPosition(Int32 left, Int32 top)     
   em Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   em Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   em Microsoft.PowerShell.PSConsoleReadLine.ForceRender()        
   em Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)       
   em Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   em Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
