### ISSUE TITLE
Crash at checking Sym-Links after Dropbox gets wild on win10

### ISSUE THREAD

**Issue by SebastianBoehmer** [PowerShell/PSReadLine#1590]
after update of windows,
dropbox is not able to handle new environemnt.
I decided to kill dropbox.

Then I am looking on the symbolic-links and detect, that the target should be a symbolic-link, as the PS said.

Last 200 Keys:
 e t ( ) Enter
 UpArrow Backspace Backspace Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace T a r Tab Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow c d Space $ ( Backspace Backspace Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow $ ( Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow ) Enter
 UpArrow UpArrow DownArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow RightArrow RightArrow LeftArrow LeftArrow " Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow " Enter
 Ctrl+l UpArrow Backspace Backspace Ctrl+DownArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace $ d i r Space = Space Enter
 e c h o Space $ d i e r Backspace Backspace r Enter
 c d Space $ d i r Enter
 UpArrow . t o S Ctrl+Space ) Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+Backspace Ctrl+Backspace $ d i r S t r Space = Space Space Enter
 c d Space $ d i r S T r Backspace Backspace t r Enter
 c d Space " Ctrl+v " Enter
 Ctrl+l c d e Backspace Space " Ctrl+v " Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace " Enter
 Enter
 l s Space - V e r Tab Enter
 G e t - Backspace Backspace Backspace Backspace $ i t e m Space =

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by SebastianBoehmer** [comment]
also, the top:



PS C:\Users\sebas\Acus Akademie\Back-Office - Documents\General\Anmeldebestaetigung E-Mails\Frankfurt> $item
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 e t ( ) Enter
 UpArrow Backspace Backspace Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace T a r Tab Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow c d Space $ ( Backspace Backspace Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow $ ( Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow ) Enter
 UpArrow UpArrow DownArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow RightArrow RightArrow LeftArrow LeftArrow " Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow " Enter
 Ctrl+l UpArrow Backspace Backspace Ctrl+DownArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace $ d i r Space = Space Enter

**Comment by SebastianBoehmer** [comment]
happen, when I enter *$item *

is *reproducable* !

**Comment by SebastianBoehmer** [comment]
Was the '=' sign after '$item ' which runs the exception.

Try to reboot...

**Comment by SebastianBoehmer** [comment]
- restart done
- dropbox killed
- started PS as Admin
- enter 
> $i = "asdf"
is running!

**Comment by iSazonov** [comment]
What is version you use? See #1306 and update to latest version.

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
