### ISSUE TITLE
Make `ForwardChar` configurable to accept whole suggestion or the next word of it

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PSReadLine#1596]
Loving new the suggested line - just on quite small problem, and I half expect the answer to be 
"We know, we're working on it", but I couldn't see it in the open issues.

## Environment

```none
PS version: 7.0.1
PSReadline version: 2.1.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.1.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 172
BufferHeight: 39
```

I don't think this is version dependent - apart from needing this version of PSReadLine, 
## Steps to reproduce
1.  Start Powershell (7) and allow PSRL 2.1.0 beta 2 to load normally, then run  `Set-PSReadLineOption -PredictionSource History`

2. Start typing a line from the history and see that it is suggested. Press right arrow to accept the line and then us left and right to move forwards and backwards along the line.  Run or escape from the command.

3. Run `Get-PSReadLineKeyHandler | where function -Match "accept" ` AcceptSuggestion  and AcceptNextSuggestionWord  are not listed

4. run `Get-PSReadLineKeyHandler | where key -Match "rightarrow"` only the normal cursor movements are listed. 

5.  I would like right arrow to be accept next word and ctrl+rightarrow or end to be accept all so I run 
```
set-PSReadLineKeyHandler -Function AcceptNextSuggestionWord -Chord RightArrow
set-PSReadLineKeyHandler -Function AcceptSuggestion -Chord ctrl+RightArrow

```

6. Run `Get-PSReadLineKeyHandler | where Key -Match "rightarrow"` again these keys have lost their normal behavior

7. Verify that accept suggestion by work or whole line works, select left works, but select right doesn't

## Expected behavior

A key can work inside and outside "suggestion" mode (as with the default right arrow.). 

## Actual behavior

It can't

**Comment by daxian-dbw** [comment]
The `accept all suggestion text` functionality is built-in to the function `ForwardChar`, which is the default binding function for <kbd>RightArrow</kbd>.
Similarly, the `accept next suggestion word` functionality is also built-in to `ForwardWord`, which is currently not bound by default, but we may add <kbd>Ctrl+f</kbd> to it as the default binding .

Those 2 cursor movement functions are able to tell if the cursor is already at the end of the editing line. If not, they move the cursor in the editing line; if yes, they operate on the suggestion text.

Functions `AcceptNextSuggestionWord` and `AcceptSuggestion` are made bindable to allow you use different key bindings for the suggestion text acceptance operations. They don't deal with cursor movement.

It sound to me what you want is to have `ForwardChar` somewhat configurable on whether it accepts the whole suggestion or a word of it. It's a reasonable ask. We will see if this issue will attract more interests (up-votes).

**Comment by daxian-dbw** [comment]
Also, the ask can be easily satisfied by implementing a custom script block key binding, such as the one below.
Given this, I don't think it's necessary to have it built-in in PSReadLine, at least not initially.

```powershell
Set-PSReadLineKeyHandler -Key RightArrow -ScriptBlock {
       param($key, $arg)

       $line = $null
       $cursor = $null
       [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)

       if ($cursor -lt $line.Length) {
           [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar($key, $arg)
       } else {
           [Microsoft.PowerShell.PSConsoleReadLine]::AcceptNextSuggestionWord($key, $arg)
       }
}
```

**Comment by jhoneill** [comment]
@daxian-dbw  - we might quibble about "Easily", but yes I agree,  no code change needed. 
   
I think it would be good to document this - at least with a better description in the release notes.

**Comment by silverqx** [comment]
> Also, the ask can be easily satisfied by implementing a custom script block key binding, such as the one below.

Thank you 🙏, your code snippet script block helped me a lot, I used it like this:
```
# Accept the current inline suggestion
Set-PSReadLineKeyHandler -Key End -ScriptBlock {
       param($key, $arg)

       $line = $null
       $cursor = $null
       [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)

       if ($cursor -lt $line.Length) {
           [Microsoft.PowerShell.PSConsoleReadLine]::EndOfLine($key, $arg)
       } else {
           [Microsoft.PowerShell.PSConsoleReadLine]::AcceptSuggestion($key, $arg)
       }
}
```
