### ISSUE TITLE
Smart quotes get removed when pasting to PS7

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#1603]
## Environment

```none
PS version: 7.1.0-preview.3
PSReadline version: 2.1.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 179
BufferHeight: 53
```

## Steps to reproduce

Copy the script from: https://devblogs.microsoft.com/powershell/mandelbrot-one-liner/

Paste into Windows PowerShell
Paste into PowerShell 7 (doesn't matter if conhost or Windows Terminal)

Does't matter if CTRL-V or right click to paste

## Expected behavior

Script runs like in Windows PowerShell

## Actual behavior

```
ParserError:
Line |
   1 |  … ile(($y++) -lt 15) {for($x=0; ($x++) -lt 84; write-host ( .:-;!/>`)|& …
     |                                                                 ~
     | Missing closing ')' in expression.
```

The "smart quotes" around the string of printable characters get removed.  Removing PSReadLine enables paste to work correctly.  Paste with PSReadLine works fine on macOS.

**Comment by vexx32** [comment]
This was reported a couple years back already, I think. #760 is the same issue; seems like it affects quotes and dashes as well.

**Comment by lzybkr** [comment]
This doesn't reproduce in conhost or Windows Terminal if the output encoding is UTF8:

```PowerShell
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
```

**Comment by daxian-dbw** [comment]
> Does't matter if CTRL-V or right click to paste

When PSReadLine is imported, the issue only reproduce for me when pasting using `Right Click`, not when using <kbd>ctrl+v</kbd>.
@SteveL-MSFT are you able to reproduce using <kbd>ctrl+v</kbd>?

`Right Click` removes the smart quotes even after setting the console output encoding to UTF8. But once unload PSReadLine, `Rigth Click` works fine in both conhost and WIndows Terminal, even if the output encoding is not UTF8 (default output encoding is `ibm437`).

**Comment by daxian-dbw** [comment]
Further investigation shows this is likely caused by the call to `Console.KeyAvailable`. It somehow causes the next Unicode character input to be skipped. I opened https://github.com/dotnet/runtime/issues/38966 and will mark this issue external.

**Comment by nu8** [comment]
https://github.com/malxau/yori/issues/53

**Comment by wswind** [comment]
It has been such a long time . I'm still waiting for this issue to be fixed <https://github.com/PowerShell/PSReadLine/issues/1771#issuecomment-680270025>
