### ISSUE TITLE
프로그램 실행 시 마다 이런 문제가 생깁니다.

### ISSUE THREAD

**Issue by YakJangSu** [PowerShell/PSReadLine#1604]
python 으로 작성 후 실행 시 마다 "마지막 1 키:"의 &가 하나씩 늘어나며 프로그랩 실행 오류가 납니다.
어떻게 해결해야 하나요?
==========================================
마지막 1 키:
 &

예외:
System.ArgumentOutOfRangeException: 값 
은 0보다 크거나 같아야 하며 해당 범위에
서 콘솔의 버퍼 크기보다 작아야 합니다. 
매개 변수 이름: left
실제 값은 -1입니다.
   위치: System.Console.SetCursorPosition(Int32 left, Int32 top)
   위치: Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   위치: Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   위치: Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   위치: Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   위치: Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   위치: Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   위치: Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   위치: Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
