### ISSUE TITLE
Exception: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by b-chmiel** [PowerShell/PSReadLine#1605]
> python taks.    
                
Oops, something went wrong.  Please report this bug with the details below.  
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space r Backspace u h n Backspace Delete Backspace n i t t e s t Space d i s c o f Backspace v e r Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 Enter
 c o v e r a g e Space r e p o r t Enter
 Ctrl+v Enter
 UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace t e s t Backspace Backspace Backspace a s k Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c o v e r a g e Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace t a s k Enter
 UpArrow . p y Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace a t Backspace Backspace t a k 
s . ,

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
ta, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)                                             i
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
