### ISSUE TITLE
PS C:\Users\dsb32\Desktop\site> Произошла ошибка. Сообщите об этой ошибке, указав данные ниже. 

### ISSUE THREAD

**Issue by david-shiko** [PowerShell/PSReadLine#1608]
Последние клавиши 200:
 Delete Enter
 UpArrow Backspace Backspace / ? Enter
 UpArrow LeftArrow LeftArrow a d d Space Enter
 UpArrow LeftArrow LeftArrow i p l i s t e n Enter
 UpArrow LeftArrow LeftArrow Space Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow Enter
 ` UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow UpArrow DownArrow UpArrow DownArrow Enter
 Ctrl+c UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+v Enter
 UpArrow Enter
 UpArrow DownArrow c d Space d e Tab r u Tab Tab s i Tab Enter
 UpArrow UpArrow Enter
 Ctrl+l Ctrl+l Ctrl+l c l e a r Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+l Ctrl+l Ctrl+l

Исключение:
System.IO.IOException: Параметр задан неверно.

   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.Console.SetWindowPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
The `Ctrl+l` issue was fixed (see #1315). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
