### ISSUE TITLE
Tab Expansion on [Set-Culture -Cultureinfo]

### ISSUE THREAD

**Issue by BDRfox** [PowerShell/PSReadLine#1613]
I did a tab expansion on Set-Culture -Cultureinfo *(here's where I did it) in a PS console
and it asked me if I want to display all the possibilities.
I entered y then the error message showed below.

> Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 a n g a u g e * Backspace Backspace Backspace Backspace Backspace a Backspace u a n g e Backspace Backspace Backspace g
 e * Enter
 g c m Space g e t - * l a n u Backspace g u a g e * Enter
 g c m Space * c u l t u r e * Enter
 g e t - c u l t u r e Enter
 s e t - c u l t u r e Tab Space - Tab Space Ctrl+Space Tab Ctrl+Space y Backspace Backspace Backspace Backspace Backspa
ce Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspa
ce Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspa
ce Backspace Backspace Backspace Backspace Backspace UpArrow UpArrow DownArrow Space - Tab Tab Tab Backspace Backspace B
ackspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space Escape s e t Backspa
ce Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspa
ce Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace s e - t f c Backspace Backspace Backs
pace Backspace t 0 Backspace - c u l t Tab Space - Tab Space Ctrl+Space n Ctrl+Space y

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer s
ize in that dimension.
Parameter name: top
Actual value was -1845.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
The `ArgumentOutOfRangeException` thrown from `DrawMenu` was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery, and give it a go. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
