### ISSUE TITLE
System.ArgumentOutOfRangeExceptions after function prompt {">"}

### ISSUE THREAD

**Issue by Dreamykass** [PowerShell/PSReadLine#1616]
# terminal at first crash

![whole console screen at the point of crash image](https://i.imgur.com/MHnFgl3.png)

[gist of the terminal content](https://gist.github.com/Dreamykass/d0211d6419a213f45f916425f6a85707)

# steps to replicate?
![steps to replicate image](https://i.imgur.com/SKO1Z53.png)

# system

Windows Terminal version: 1.0.1401.0
System: Windows 10 Home 1903 (18362.900) x64

(Windows Terminal is great, btw; I'm really enjoying it, and I even got a custom theme! It nicely fits in to the VS and VSCODE environments :D )

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
