### ISSUE TITLE
TAB completion - only show relevant content

### ISSUE THREAD

**Issue by 9Rune5** [PowerShell/PSReadLine#1632]
1. Navigate to a build folder full of dlls
2. Press TAB

// expected: Only enumerate files or cmdlets that has a chance of executing.
// actual: It enumerates dlls. Trying to execute one of them: "Program 'adaplU.dll' failed to run: No application is associated with the specified file for this operation."

In my case, the folder in question contains a dozen files matching a*.dll and only a single file that matches a*.exe.

**Comment by daxian-dbw** [comment]
This is how tab completion in powershell does and PSReadLine just renders the results. If you have question about that behavior, open an issue in http://github.com/powershell/powershell instead.
