### ISSUE TITLE
Bug or feature? Handling Tab in clipboard text (or from F8 in VS Code) 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PSReadLine#1633]
## Environment

```none
PS version: 7.0.2
PSReadline version: 2.1.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.2.0
HostName: ConsoleHost
BufferWidth: 233
BufferHeight: 37
```

## Steps to reproduce

I had some file names which I needed to copy in an excel sheet  so I filled "copy" down the column to their left and "\temp" down the column to the right and copied and pasted. 
Excel puts this in the clipboard as 
```
Copy[tab]name1[tab]\temp
Copy[tab]name2[tab]\temp
```
And these are interpreted as if they had been typed, so instead of a space, `copy` is tab expanded (on my system it becomes `Copy-ExcelWorksheet` but other systems will expand differently )

I thought "OK.  I'll paste into a new window in VSCode and run it from there". VSCode preserves the tabs from Excel and F8 does the same thing. 

## Expected behavior

A tab character in the clipboard becomes white space on paste

## Actual behavior

A tab character in the clipboard is handled like pressing the tab key. 

This might be by design, and I'm not sure the paste / F8 are going through the same route.  Although we encourage people to use spaces and not tab characters in their PowerShell code, I don't think F8 should not break if code _does_ have tabs.

**Comment by SeeminglyScience** [comment]
Duplicate of #579.  As a work around you can use PSReadLine's paste key handler (<kbd>CTRL</kbd> + <kbd>v</kbd> by default).  In the case of VSCode, you can use the PowerShell extension's <kbd>F8</kbd> and it'll work as expected.

**Comment by jhoneill** [comment]
@SeeminglyScience   thanks for the quick reply  I hadn't gone far enough back to find the earlier one , I'll close this one.  

F8 works for the integrated shell in VS code but not for other instances.  (at one time F8 didn't work for those at all, now it works but inserts differently) 

I hadn't twigged ctrl + v was a _different_  paste
