### ISSUE TITLE
Holding down/chilling on a key gives unhandled exception

### ISSUE THREAD

**Issue by rasmushalland** [PowerShell/PSReadLine#1636]
My cat found this missing error handling:

![image](https://user-images.githubusercontent.com/6505868/86381410-9ab22c00-bc8d-11ea-833e-f1396aac7693.png)

Environment: VS 2019, win 10 2004, via the new (?) "Terminal" item in the View menu.
 Windows Terminal is installed.

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
