### ISSUE TITLE
Sharing a response from powershell 

### ISSUE THREAD

**Issue by irattan** [PowerShell/PSReadLine#1638]
Oops, something went wrong.  Please report this bug with the details below. 

Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new 

----------------------------------------------------------------------- 

Last 200 Keys: 

Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space DownArrow DownArrow DownArrow DownArrow DownArrow RightArrow UpArrow DownArrow UpArrow RightArrow RightArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow LeftArrow DownArrow DownArrow DownArrow LeftArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace a z v i r Tab Backspace Backspace Backspace Tab Backspace Backspace Backspace Ctrl+Space DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow Enter 

Enter 

Ctrl+Space UpArrow Ctrl+Space Enter 

Space Ctrl+Space n LeftArrow Ctrl+v Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace UpArrow Space Ctrl+Space y Enter 

Enter 

Enter 

Enter 

Enter 

Enter 

Enter 

Enter 

Enter 

g e t - a z s e Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space Ctrl+Space Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space y v p n Ctrl+Space RightArrow DownArrow UpArrow LeftArrow Enter 

Ctrl+Space RightArrow Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Space Ctrl+Space y 

  

Exception: 

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. 

Parameter name: top 

Actual value was -1556. 

   at System.Console.SetCursorPosition(Int32 left, Int32 top) 

   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount) 

   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu) 

   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect) 

   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect) 

   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg) 

   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop() 

   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) 

----------------------------------------------------------------------- 

PS C:\WINDOWS\system32> Get-AzVpnClientConfiguration

**Comment by irattan** [comment]
I was able to generate another kick back, 
I am connected to Azure portal with powershell, 
trying to access the specifics of my VM and when requesting/generating the additional options, it kicks back the error, 
Good luck,

 

 PS C:\WINDOWS\system32> Get-AzVmssVM 5AS_RemoteDesktop 

Oops, something went wrong.  Please report this bug with the details below. 

Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new 

----------------------------------------------------------------------- 

Last 200 Keys: 

Backspace Backspace UpArrow Space Ctrl+Space y Enter 

Enter 

Enter 

Enter 

Enter 

Enter 

Enter 

Enter 

Enter 

g e t - a z s e Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space Ctrl+Space Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space y v p n Ctrl+Space RightArrow DownArrow UpArrow LeftArrow Enter 

Ctrl+Space RightArrow Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Space Ctrl+Space y Enter 

UpArrow Backspace Ctrl+Space RightArrow Backspace Ctrl+Space Backspace Ctrl+Space Ctrl+Space Ctrl+Space Ctrl+Space Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space n v p n Ctrl+Space DownArrow DownArrow RightArrow RightArrow Enter 

Enter 

UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace v m Ctrl+Space Backspace Backspace a z v m Ctrl+Space RightArrow RightArrow RightArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow Enter 

Ctrl+Space RightArrow LeftArrow Enter 

Space Ctrl+Space RightArrow Enter 

Ctrl+Space Space Ctrl+Space - - Backspace Ctrl+Space y 

  

Exception: 

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. 

Parameter name: top 

Actual value was -1556. 

   at System.Console.SetCursorPosition(Int32 left, Int32 top) 

   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount) 

   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu) 

   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect) 

   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect) 

   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg) 

   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop() 

   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) 

----------------------------------------------------------------------- 

PS C:\WINDOWS\system32> Get-AzVmssVM 5AS_RemoteDesktop

**Comment by daxian-dbw** [comment]
The `ArgumentOutOfRangeException` thrown from `DrawMenu` was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery, and give it a go. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
