### ISSUE TITLE
Error while pressing auto tab complition

### ISSUE THREAD

**Issue by hms86** [PowerShell/PSReadLine#1639]
Hi

I am using powershell through the windows terminal.

I have swiched the "EditMode" option to "Emacs" using
`Set-PSReadLineOption -EditMode Emacs`

When executing the cmdlet `Get-Process -Name` and i press tab for auto complition i get this error:

` Oops, something went wrong.  Please report this bug with the details below. `
` Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new `
` ----------------------------------------------------------------------- `
` Last 200 Keys: `
` Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace`
` Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace`
` UpArrow  UpArrow Enter`
` UpArrow UpArrow DownArrow DownArrow UpArrow Backspace Backspace Backspace Backspace Backspace W i n Tab Enter`
` UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow G E t Backspace Backspace e Tab t - s e r v Tab`
` Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace`
` Backspace Backspace Backspace Backspace Backspace Backspace t - s e r Tab Space - Backspace - n a m e Tab Space Tab Tab Tab`
` Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace`
` Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace`
` Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace`
` Backspace Backspace Backspace UpArrow UpArrow Enter`
` UpArrow UpArrow DownArrow DownArrow G e t - S e r v i Tab Space - n Tab Space Tab Tab Tab y UpArrow DownArrow`
` UpArrow Tab Tab DownArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow UpArrow DownArrow`
` DownArrow G e t - S e Tab r v Tab Space - N a Tab Space Backspace Tab Tab Space Tab Tab Tab y`
` Exception:`
` System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.`
` Parameter name: top `
` Actual value was -49. `
`   at System.Console.SetCursorPosition(Int32 left, Int32 top)`
`   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)`
`   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)`
`   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)`
`   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)`
`   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary2 dispatchTable, Boolean ignoreIfNoAction, Object arg)`
`   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()`
`   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)`

The workaround to make the tab work is to zoom out a lot using ` ctrl + mouse wheel ` in the windows terminal and then press tab again. After doing so, even if i zoom in again, the tab will keep working.

Thank you

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
