### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by dzittin** [PowerShell/PSReadLine#1640]
Windows 10, Visual Studio. Occurs frequently when I run a small test program, but not every time.

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 t h o n 3 8 - 3 2 / p y t h o n . e x e Space c : / U s e r s / D a v e / D e s k t o p / W e b u c a t o r / P y t h o n / d e f a u l t _ d i c t . p y Enter
 & Space C : / U s e r s / D a v e / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 8 - 3 2 / p y t h o n . e x e Space c : / U s e r s / D a v e / D e s k t o p / W e b u c a t o r / P y t h o n / d e f a u l t _ d i c t . p y Enter    

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that 
dimension.
Parameter name: top
Actual value was 17.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
