### ISSUE TITLE
CommandValidationHandler not called

### ISSUE THREAD

**Issue by nguerrera** [PowerShell/PSReadLine#1643]
I may be misunderstanding how this is supposed to work, but I am unable to figure out how to use Set-PSReadLineOption -CommandValidationHandler. The validation handler never seems to get called. 

## Environment
```
PS version: 7.0.2
PSReadline version: 2.0.0
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.0.2.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30
```

## Steps to reproduce

1. Run this:

https://github.com/PowerShell/PSReadLine/blob/a88c22fd60a69f41d1b727b7c51b5cbf8f9b5f68/PSReadLine/SamplePSReadLineProfile.ps1#L565-L582

2.  Run `git cmt`

## Expected behavior

`git cmt` is corrected to `git commit`

## Actual behavior

`git: 'cmt' is not a git command. See 'git --help'.`

**Comment by lzybkr** [comment]
Add the following to your profile:

```powershell
Set-PSReadLineKeyHandler -Key Enter -Function ValidateAndAcceptLine
```

**Comment by nguerrera** [comment]
@lzybkr Thanks, that works!
