### ISSUE TITLE
test my code issue

### ISSUE THREAD

**Issue by aluisiocastro** [PowerShell/PSReadLine#1644]
Last 200 Keys:
 n . e x e Space " c : / U s e r s / a l u _ n / A p p D a t a / R o a m i n g / C o d e / U s e r / g l o b a l S t o r a g e / m o o c f i . t e s t - m y - c o d e / t m c d 
a t a / T M C Space w o r k s p a c e / E x e r c i s e s / h y / h y - d a t a - a n a l y s i s - w i t h - p y t h o n - 2 0 2 0 / p a r t 0 2 - e 0 3 _ r e d _ g r e e n _ b l u e / s r c / r e d _ g r e e n _ b l u e . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.

**Comment by aluisiocastro** [comment]
Hi Dongbo,

Tks for your help. I am super beginner and did not get the instructions right the way. Would you help me with some screeshots. Exactly where to type the commands for example...

Thanks again

Aluisio

________________________________

**Comment by daxian-dbw** [comment]
Sure. Assuming you are using Windows PowerShell 5.1, please do the followings:

1. Close all PowerShell instances, including the opened PowerShell consoles and VS Code.
2. Open the Command Prompt `cmd.exe`
3. In the `cmd` console, run `powershell -noprofile -command "Install-Module PSReadLine -Force -SkipPublisherCheck"`, and that should install the latest stable version of `PSReadLine` for you.

Hope this helps :)

**Comment by aluisiocastro** [comment]
thanks, installations seemed to work fine but now in VSCode my Run button disapeared:

[cid:699b5c1b-dc1a-4683-ab29-19e17205da36]

________________________________

**Comment by daxian-dbw** [comment]
Weird, installing the PSReadLine module shouldn't affect the VSCode. I asked to close VSCode in the steps above is only because VSCode terminal may have powershell opened as the default terminal.

**Comment by aluisiocastro** [comment]
Never mind, I restarted the pc and it is working now
Thank you so much for your great support.


________________________________
