### ISSUE TITLE
Python terrific bug in here

### ISSUE THREAD

**Issue by park-star** [PowerShell/PSReadLine#1645]
Hello Im korean 
I dont know this bug so Plz help me thank you

There was a problem. Please report this bug with the details below. Report on github: 

https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
the last 92 keys :
 & Space C : / P h t h o n 3 8 / p y t h o n . e x e Space " c : / U s e r s / p f 6 7 1 / O n e D r i v e /  
바 탕 Space 화 면 / P h y t h o n Space W o r k S p a c e / . v s c o d e / h e l l o . p y " Enter

Exceptions :
System.ArgumentOutOfRangeException: 
The value must be greater than or equal to zero and less than the console's buffer size in that range. 
Parameter Name : left
The truth value is -1
  Location: System.Console.SetCursorPosition(Int32 left, Int32 top)
 Location : Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   Location: Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)      
   Location: Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
  Location: Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   Location: Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   Location: Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, 
Boolean ignoreIfNoAction, Object arg)
op()
   Location: Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)-----------------------------------------------------------------------
PS C:\Users\pf671\OneDrive\바탕 화면\Phython WorkSpace> & C:/Phthon38/python.exe "c:/Users/pf671/OneDrive/바탕
 화면/Phython WorkSpace/.vscode/hello.py"
hello
PS C:\Users\pf671\OneDrive\바탕 화면\Phython WorkSpace>
PS C:\Users\pf671\OneDrive\바탕 화면\Phython WorkSpace>

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
