### ISSUE TITLE
Pasting with Ctrl-V assigned to Paste OR to PasteAfter erases line before pasting

### ISSUE THREAD

**Issue by HerbM** [PowerShell/PSReadLine#1646]
Pasting with Ctrl-V assigned to Paste OR to PasteAfter erases line before pasting

## Environment

PSVersion                      7.1.0-preview.5     PSReadLine 2.0.2                 
PSVersion                      7.0.2
PSVersion                      5.1.19035.1
Also some older versions of PSReadline (but not early ones)

```
PS version: 5.1.19035.1
PSReadline version: 2.0.2
PS file version: 10.0.19035.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 135
BufferHeight: 9999
```

## Exception report

No exception present.

## Steps to reproduce

Recall or type text, leave cursor at end or move to anywhere on line.
Paste
Previous text is removed

## Expected behavior

Clipboard should be pasted in at cursor position leaving existing text surrounding the paste.
## Actual behavior

Existing text is removed before clipboard is pasted

NOTE:  Right click with quick edit pastes into the current text as expected.

Thanks so much, and I figured this was MY issue but it's using the default keyhandler Ctrl-v == Paste.
Also trying Ctrl-v == PasteAfter gives same/similar resulte.

**Comment by daxian-dbw** [comment]
@HerbM I cannot reproduce the issue, see my screen git below with PSReadLine 2.0.2 (recorded on PS5.1, but the same for 7.0.2 and 7.1.0-preview.3). All I did was <kbd>Ctrl+v</kbd> and <kbd>Ctrl+z</kbd> (undo)

![tabcom](https://user-images.githubusercontent.com/127450/86979976-7d6ed900-c137-11ea-841b-adc7f5a94c56.gif)

What the result when you run this command `Get-PSReadLineKeyHandler -Key 'ctrl+v'`?

**Comment by HerbM** [comment]
@daxian-dbw
Thanks for looking:

*** It's my fault -- close this.  I found another macro that was designed long before PSReadline


> $PSVersionTable.PSVersion; Get-PSReadLineKeyHandler -Key 'ctrl+v' | ft

Major  Minor  Build  Revision
5      1      19035  1
7      0      2
7      1      0      preview.5

# same result for all 3 for the Get-PSReadlineKeyHandler

Basic editing functions
=======================

Key    Function Description
---    -------- -----------
Ctrl+v Paste    Paste text from the system clipboard

**Comment by HerbM** [comment]
This problem was on my side.

Apologies to all who wasted time on this.
