### ISSUE TITLE
Your wish

### ISSUE THREAD

**Issue by VitaliyMonster** [PowerShell/PSReadLine#1647]
Последние клавиши 200:
 t h o n . e x e ' Space ' c : \ U s e r s \ 6 0 0 8 3 6 5 5 \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 6 . 9 1 3 5 0 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e 
b u g p y \ l a u n c h e r ' Space ' 2 3 4 2 6 ' Space ' - - ' Space ' c : \ U s e r s \ 6 0 0 8 3 6 5 5 \ P r o j e c t s \ A P I \ d o s t o v e r n o s t - - a p i - t a s k \ s r c \ a p p . p y ' Space Enter

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было 24.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
Thanks for the report @VitaliyMonster. This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
