### ISSUE TITLE
[vi-mode] Using 'dd' should only delete the current logical line and not the entire buffer.

### ISSUE THREAD

**Issue by springcomp** [PowerShell/PSReadLine#1657]
## Description of the new feature/enhancement

Using <kbd>d</kbd><kbd>d</kbd> currently deletes the entire buffer, which seems wrong when using multiline input.

**Comment by gwojan** [comment]
Shouldn't <kbd>D</kbd> and <kbd>d</kbd><kbd>$</kbd> behave similarly by acting on the logical line? Currently they delete from the current position to the end of the buffer.

**Comment by springcomp** [comment]
Indeed, they should.

I was hoping to implement those in other PRs.
Should I add other commits to this PR until we have a consistent behaviour?

**Comment by springcomp** [comment]
The following commands should probably be included in subsequent commits/PRs:

- [x] <kbd>d</kbd><kbd>_</kbd>: deletes the entire logical line. ([47378fe](https://github.com/PowerShell/PSReadLine/pull/1658/commits/47378fe59b506a0d1cc22632c0174773b7b9094a))
- [x] <kbd>d</kbd><kbd>^</kbd>: deletes from the first non blank character of the logical line to the current position. ([352edb9](352edb9c6278959579272fa6ab4c794f35b92527))
- [ ] <kbd>d</kbd><kbd>0</kbd>: deletes from the beginning of the logical line to the current position.
- [x] _n_<kbd>d</kbd><kbd>j</kbd>: deletes the next _n+1_ lines from the current logical line. ([62c6b41](https://github.com/PowerShell/PSReadLine/commit/62c6b41f5098145196a050f24e189b90f7e6729c))
- [x] _n_<kbd>d</kbd><kbd>k</kbd>: deletes the previous _n+1_ lines from buffer to the current logical line. ([7024968](https://github.com/PowerShell/PSReadLine/commit/70249682ed8d87ddc3869e5d0ba852a0d6da99da))
- [x] _n_ <kbd>d</kbd><kbd>g</kbd><kbd>g</kbd>: delete from the current logical line to the requested line number in a multiline buffer ([eadcf2c](https://github.com/PowerShell/PSReadLine/commit/eadcf2c4def91881fb2c88ef06fa05486a908224)).
- [x] <kbd>d</kbd><kbd>G</kbd>: deletes the logical lines from the current position to the end of the buffer. ([c316374](https://github.com/PowerShell/PSReadLine/pull/1692/commits/c316374816613421be37539843e58ad3e4a051e2))
- [x] _n_<kbd>D</kbd> or <kbd>d</kbd><kbd>$</kbd>: deletes to the end of the current or next _n_ logical lines. ([b3f3975](https://github.com/PowerShell/PSReadLine/commit/b3f3975cd1bfe883d6278017302e83f486e6c138))
