### ISSUE TITLE
System.ArgumentOutOfRangeException: The value  must be greater than or equal to zero and less than the console's buffer size in that dimension. Parameter name: top

### ISSUE THREAD

**Issue by ImJoke** [PowerShell/PSReadLine#1660]
Last 200 Keys:
 \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 6 . 9 1 3 5 0 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 5 1 8 4 8 ' Space ' - - ' Space ' c : \ U s e r s \ Y o b e l \ D o c u m e n t s \ P y t h o n \ 1 3 . 0 7 . 2 0 2 0 Space P U K U L Space 0 8 . 0 0 Space - Space 1 0 . 1 5 . . . Space S E R A G A M Space P U T I H Space B I R U Space S M P Space I K A T Space P I N G G A N G Space H I T A M . p y ' Space Enter

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
