### ISSUE TITLE
System.ArgumentOutofRangeException: Actual value was -1

### ISSUE THREAD

**Issue by jgmonteirohub** [PowerShell/PSReadLine#1666]
Hello, I am not too experienced with python or visual studio code so I will try to explain this issue as best as I can. 

I am currently creating a classification machine learning model using the Titantic dataset from Kaggle. Everything has been running smoothly so far but I have recently running into an issue when I attempt to run my program. This error then tells me to report the issue here which is what brings me here today. 

The error states:

"Exception:
System.ArgumentOutofRangeException: The value must be greater than or equal to 1 to zero and less than the console's buffer size in that dimension. 
Actual value was -1."

After this, it provides a number of "Microsoft.Powershell" errors. What confuses me is that the code runs perfectly fine sometimes, then at others it provides this exact error. So I don't understand why it's happening.

Thank you for your time. 

![image](https://user-images.githubusercontent.com/60673760/87734304-44221300-c7a0-11ea-932b-2e01ac36aab6.png)

**Comment by nick-terry1** [comment]
Ive gotten the same error, not after running a command but by hitting escape

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.3 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
