### ISSUE TITLE
[Windows Sandbox] System.BadImageFormatException: Signature is not IMAGE_CEE_CS_CALLCONV_LOCAL_SIG

### ISSUE THREAD

**Issue by Cerlancism** [PowerShell/PSReadLine#1668]
I tried to use Powershell in Windows Sandbox I keep getting the following error.

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.BadImageFormatException: Signature is not IMAGE_CEE_CS_CALLCONV_LOCAL_SIG.
   at .cctor()
-----------------------------------------------------------------------
```

I think the recent Windows update caused this as I can recall it is working fine last time.

My host system:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041

Sandbox:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19041 Build 19041

Possible causes:
https://support.microsoft.com/en-us/help/4565627/kb4565627-cumulative-update-for-net-framework
https://support.microsoft.com/en-us/help/4565503/windows-10-update-kb4565503

**Comment by daxian-dbw** [comment]
@Cerlancism Thanks for reporting the issue. By _Sandbox_, do you mean a windows container?

> When [an MSIL method] gets compiled to IL, the compiler will create a signature based on the number of local variables (2) and their types (both int32). At the very beginning of the signature the compiler will also add a special byte to identify the type of the signature, which is 0x07 (IMAGE_CEE_CS_CALLCONV_LOCAL_SIG) for local variables.

It's very likely caused by the container after your windows update. I'm afraid there is nothing we can do in PSReadLine.

**Comment by TakamiChie** [comment]
I've been experiencing the same symptoms in my environment, which led me here.
Windows Sandbox is a feature added to Windows 10 last spring version (1903), and is an application that reproduces the same version of Windows as the main PC.

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview

When I was using Windows Sandbox in last fall's version (1909), it was perfectly fine, but after upgrading to this spring's version (2004 Build 19041 ), I'm getting the above error only on Windows Sandbox.
I know that there is nothing that PSReadLine itself can do about this case.

However, as @Cerlancism writes, I think it's very likely that this is a Windows update issue.

According to his Github profile, @daxian-dbw works for Microsoft, so if that's the case, do you know of an appropriate source of feedback on this issue?

**Comment by SeeminglyScience** [comment]
@TakamiChie The Feedback Hub app.  Category "Security and Privacy" subcategory "Windows Sandbox"

**Comment by Cerlancism** [comment]
I have reported to the feedback hub at https://aka.ms/AA928xa

Do upvote and comment to the issue so it gets more attention, or you maybe you guys could help to escalate the issue internally to the Windows Sandbox team.

**Comment by TakamiChie** [comment]
Thanks for the quick action.
