### ISSUE TITLE
This is what happens while i am installing nodejs 

### ISSUE THREAD

**Issue by adi3221** [PowerShell/PSReadLine#1669]
PS D:\My corona lockdown\Node.Js\express.js>    
Oops, something went wrong.  Please report this 
bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 113 Keys:
 n p m Space i n s t a l l Space e x p r e s s Enter
 c l e a r Enter
 n p m Space i n i t Enter
 v Backspace c l e a r Enter
 n p m Space i n s t a l l Space e x p r e s s Enter
 c l e a r Enter
 n p m Space i n i t Enter
 c l e a r Enter
 n p m Space i n s t a l l Space e x s Backspace p r e s s Enter
 c l e a r Enter
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.  
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
