### ISSUE TITLE
Encountered an Error when compiled the c++ code

### ISSUE THREAD

**Issue by chawlajay** [PowerShell/PSReadLine#1680]
When I tried to compile a code of C++ in VS Code ,I faced this error(attached as file) and now I am unable to compile my C++  code. My VS Code is already updated to latest version ( 1.47.2(user.setup) ) of Windows 10. I hope this problem soon gets resolved.
[vscode_error.txt](https://github.com/PowerShell/PSReadLine/files/4959400/vscode_error.txt)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.3 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
