### ISSUE TITLE
Good day! I opened PowerShell and pressed the up button to get the previous command. I got this error:

### ISSUE THREAD

**Issue by vladislavostapov** [PowerShell/PSReadLine#1683]
Произошла ошибка. Сообщите об этой ошибке, указав данные ниже.
Напишите в GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Последние клавиши 1:
 UpArrow

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было -1.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   в Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.3 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
