### ISSUE TITLE
[vi-mode] Rendering bug while trying to implement a new command

### ISSUE THREAD

**Issue by springcomp** [PowerShell/PSReadLine#1696]
## Environments
[Custom version](https://github.com/springcomp/PSReadLine/commit/75114df626d5aeb16125fa2a4d01a9b6e226f564) of PSReadLine. (see [this PR](https://github.com/PowerShell/PSReadLine/pull/1697))

PS version: 5.1.19041.1
PSReadline version: 2.0.0-beta2
os: 10.0.19041.322 (WinBuild.160101.0800)
PS file version: 10.0.19041.322 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30

PS version: 7.1.0-preview.2
PSReadline version: 2.0.1
os: 10.0.19041.322 (WinBuild.160101.0800)
PS file version: 7.1.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30

## Steps to reproduce

I’m currently working on implementing the <kbd>d</kbd><kbd>j</kbd> command that deletes the current logical line and the next _n_ logical lines in a multiline buffer. However, I stumble upon a rendering bug and I have no idea where to look in order to solve it.

## Expected behavior

The prompt should be rendered correctly.

## Actual behavior

The following animation show how the prompt gets rendered incorrectly when using the command.
In particular, an empty, blank line is rendered, even though it is not part of the prompt (and cannot be navigated to).

![dj](https://user-images.githubusercontent.com/8488398/88456192-f716fe80-ce7b-11ea-8ae2-7c99f2440691.gif)

**Comment by springcomp** [comment]
For information, [the code that implements](https://github.com/springcomp/PSReadLine/blob/75114df626d5aeb16125fa2a4d01a9b6e226f564/PSReadLine/ReadLine.vi.cs#L785-L795) the new command is a simple function that calls `DeleteLine` with an argument that corresponds to the requested line count.

https://github.com/springcomp/PSReadLine/blob/75114df626d5aeb16125fa2a4d01a9b6e226f564/PSReadLine/ReadLine.vi.cs#L785-L795

Using <kbd>d</kbd><kbd>j</kbd> on the line `three` calls `DeleteLine` with `arg` equals to `2` and triggers the faulty rendering behaviour.

Using <kbd>2</kbd><kbd>d</kbd><kbd>d</kbd> while on line `three` calls `DeleteLine` with `arg` equals to `2`. But this does not trigger the faulty rendering behaviour.

**Comment by daxian-dbw** [comment]
I will take a look.
