### ISSUE TITLE
Произошла ошибка. Сообщите об этой ошибке, указав данные ниже. Напишите в GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by David-Valters** [PowerShell/PSReadLine#1707]
Последние клавиши 200:
 / p y t h o n . e x e Space " c : / U s e r s / v a l t e / O n e D r i v e / Р о б о ч и й Space с т ? л / z a d a c h i 
P y / d a / d w a . p y " Enter
 & Space C : / U s e r s / v a l t e / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 8 - 3 2 / 
p y t h o n . e x e Space " c : / U s e r s / v a l t e / O n e D r i v e / Р о б о ч и й Space с т ? л / z a d a c h i P y / d a / d w a . p y " Enter

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было 12.
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

[dwa — копия.py.txt](https://github.com/PowerShell/PSReadLine/files/4982582/dwa.py.txt)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
