### ISSUE TITLE
Ctrl-[ as equivalent to Esc in vi mode

### ISSUE THREAD

**Issue by davetapley** [PowerShell/PSReadLine#1708]
## Description of the new feature/enhancement

The [vim docs](http://vimdoc.sourceforge.net/htmldoc/intro.html#%3CEsc%3E) give `CTRL-[` as an 'equivalent' to `Esc`. 

It would be nice if `PSReadLine` also honored this.

## Proposed technical implementation details (optional)

I tried to workaround this with a shortcut using [Custom Key Bindings
](https://docs.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-7#custom-key-bindings) to [command mode](https://docs.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-7#vicommandmode) thus:

```
Set-PSReadLineKeyHandler -Key 'Ctrl+[' -Function ViCommandMode
```

But it doesn't work, when I `Ctrl+[` it is just printed, e.g:

```
❯ test^[^[^[
```

**Comment by gwojan** [comment]
@davetapley I'll save you the trouble... Your issue is a duplicate of #906. In the meantime I'm using the workaround of using <kbd>Ctrl+;</kbd> and binding it to `ViCommandMode`.

**Comment by davetapley** [comment]
Thanks @gwojan, now to start retraining my fingers 🤪

**Comment by gwojan** [comment]
@davetapley Lol! Yeah! I specifically chose <kbd>Ctrl+;</kbd> because it's relatively close to <kbd>Ctrl+[</kbd>.
