### ISSUE TITLE
エラー内容

### ISSUE THREAD

**Issue by raito12345** [PowerShell/PSReadLine#1709]
直前 200 個のキー:
 P y t h o n \ P y t h o n 3 6 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ m a k a n \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 6 . 9 1 3 5 0 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 6 0 4 0 0 ' Space ' - - ' Space ' c : \ U s e r s \ m a k a n \ D e s k t o p \ p y t h o n \ . . p y t h o n \ T h e n s i n . p y ' Space Enter

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの次元のバッファー サイズ未満を指定しなければなりません。      
パラメーター名:top
実際の値は -1 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
