### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by IlPalandra** [PowerShell/PSReadLine#1722]
Ultimi 200 tasti:
 f i e d E r r o r I d Space : Space C o m m a n d N o t F o u n d E x c e p t i o n Enter
 Enter
 P S Space C : \ U s e r s \ S a b a t i n o > Enter
 P S ` ù ù ` + à o o Enter
 Backspace Home PageUp ` RightArrow Enter
 ` + Backspace Home DownArrow Delete y 6 F6 9 t u j h Ctrl+g ` ` ` A Ctrl+LeftArrow Ctrl+` : _ , m , 9 0 ` Ctrl+9 Ctrl+N Enter
 m Insert Backspace , Home . l PageUp Ctrl+p Ctrl+` Ctrl+o Ctrl+] Ctrl+RightArrow Ctrl+p è Ctrl+Enter UpArrow Enter
 Shift+Enter § é 3 Space Backspace m j UpArrow Ctrl+Alt+\ Ctrl+Alt+, Ctrl+Alt+u Ctrl+Alt+y Ctrl+Alt+` Ctrl+Alt+1 Ctrl+Alt+F1 Ctrl+Alt+? Ctrl+Alt+` Escape Escape Escape Escape Escape Q 5 A T S Y R T U X J D C K H ` V , Space Ctrl+Alt+m Ctrl+Alt+` Space Space v m c ` Space ` , - m l ò k ù è l Enter
 DownArrow + p Home Backspace PageDown è UpArrow ì

Eccezione:
System.IO.IOException: Parametro non corretto.

   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.Console.SetWindowPosition(Int32 left, Int32 top)
   in Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   in Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
