### ISSUE TITLE
Win+Dot,  '??' -> '? ?'

### ISSUE THREAD

**Issue by Schokokex** [PowerShell/PSReadLine#1729]
Leider ist ein Fehler aufgetreten. Geben Sie mit diesem Fehler folgende Details an.
Bericht auf GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Letzte 61 Tasten:
 ? ? Backspace Backspace Alt+. Enter
 ` ? ? ? ? Backspace Backspace Backspace Backspace Backspace ` ? Backspace ` ? ? ? ? Backspace Backspace Backspace Backspace Backspace ` ? ? ? ? ? ? ? ? Backspace Backspace Backspace Backspace Backspace Backspace Enter
 Enter
 ` ? ? Enter
 ? ? Enter
 ` ? ? Enter
 UpArrow LeftArrow Space Enter

Ausnahme:
System.Text.EncoderFallbackException: Das Unicode-Zeichen \uD83D im Index 0 kann nicht in die angegebene Codepage übersetzt werden.
   bei System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   bei System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   bei System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   bei System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   bei System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   bei System.IO.StreamWriter.Dispose(Boolean disposing)
   bei System.IO.TextWriter.Dispose()
   bei Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass81_0.<WriteHistoryRange>b__0()
   bei Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   bei Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   bei Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bei Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
Closing as a dup of #949
