### ISSUE TITLE
Could a Powerline statusline be built for PSReadline?

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PSReadLine#173]
I'm wonder if this is achievable in PSReadline? Could it be done all in script? Any thoughts at the level of effort?

[Powerline](https://github.com/Lokaltog/powerline)

A colleague of mine built vim-airline. ![vim-airline](https://raw.githubusercontent.com/wiki/bling/vim-airline/screenshots/demo.gif)

**Comment by lzybkr** [comment]
I don't see doing this, at least not as part of PSReadline.
