### ISSUE TITLE
 Error occur in MenuComplete

### ISSUE THREAD

**Issue by namelessGonbai** [PowerShell/PSReadLine#1733]
I have set MenuComplete as the Tab Key behavior.

In a certain folder, when I hit Tab to use completion from the state where ".\\" was entered, this error occurred.
As a reminder, all the folders inside that folder had Japanese, or multi byte, names.

these names.
> PCB緊張
> PCW挿入
> PCW緊張
> アンカーセット
> グラウト
> シース配線
> パネルゾーン
> 天板調整
> 柱建方
> 梁架設
> 練り工事

-----------------------------------------------------------------------
直前 200 個のキー:
 RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Backspace Space | Space T Backspace t r e e Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Tab DownArrow RightArrow LeftArrow Enter
 Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Tab LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Backspace Backspace Tab Tab Enter
 UpArrow DownArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c d Enter
 l s Enter
 C o n v e r t - p Tab Space . Tab \ Backspace \ Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace , / Tab Backspace Backspace Backspace Backspace . / \ Backspace Tab Backspace Backspace Backspace G e t - P S R Tab RightArrow RightArrow LeftArrow LeftArrow Enter
 Enter
 . \ Tab

例外:
System.ArgumentOutOfRangeException: インデックスおよび長さは文字列内の場所を参照しなければなりません。
パラメーター名:length
   場所 System.String.Substring(Int32 startIndex, Int32 length)
   場所 Microsoft.PowerShell.PSConsoleReadLine.GetMenuItem(String item, Int32 columnWidth)
   場所 Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   場所 Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   場所 Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   場所 Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   場所 Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

-----------------------------------------------------------------------

**Comment by namelessGonbai** [comment]
sorry. I reported this error because it happened no matter how many times I tried it a while ago. But when I got calm and restarted, this error did not recur...
Perhaps an error that occurred in a completely different place had spread and caused this error, so I think the explanation section is meaningless. However, I will leave this issue as a report that there was an error for the time being, so please handle it as you like.

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
