### ISSUE TITLE
The katakana middle dot (U+30FB) is missing when paste string from a clipboard

### ISSUE THREAD

**Issue by ichi-kotobuki** [PowerShell/PSReadLine#1736]
## Environment

```none
PS version: 7.0.3
PSReadline version: 2.0.2
os: 10.0.18362.890 (WinBuild.160101.0800)
PS file version: 7.0.3.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 50
```

## Steps to reproduce

1. Copy the following string: ミッシング・キャラクター
1. Paste it.

## Expected behavior

I will get the string 'ミッシング・キャラクター' in the console.

## Actual behavior

I get the string 'ミッシングキャラクター' in the console.

**Comment by mkht** [comment]
I can reproduce this issue by pasting using right click, but not by Ctrl+V.

There are a some Issues that may be relevant.
#579 #1603 #760

**Comment by ichi-kotobuki** [comment]
I want to confirm one thing.
I guess below pasting methods are same as right click. Is it right?
* Paste command in system menu
* Paste command in Windows Terminal

**Comment by daxian-dbw** [comment]
Closing this as a dup of #1603 

@ichi-kotobuki I'm not sure what is the "Paste command" you referred to. Can you clarify it?

**Comment by ichi-kotobuki** [comment]
@daxian-dbw This is it.

![PasteCommand](https://user-images.githubusercontent.com/47664578/91625108-9bdaad80-e9df-11ea-9d58-090c359d96ad.png)

And I think I was mistaken about Windows Terminal. It doesn't have the edit menu.

**Comment by nu8** [comment]
https://github.com/dotnet/runtime/issues/38966
