### ISSUE TITLE
Trouble!

### ISSUE THREAD

**Issue by nicksohn** [PowerShell/PSReadLine#1739]
문제가 발생했습니다. 아래 세부 정보와 함께 이  
버그를 보고해 주세요.
GitHub에 대한 보고: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
마지막 200 키:
 e ' Space ' c : \ U s e r s \ n i c k s \ . v 
s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 7 . 9 6 4 5 6 \ 
p y t h o n F i l e s \ l i b \ p y t h o n \ d5 7 ' Space ' - - ' Space ' c : \ U s e r s \ n i c k s \ O n e D r i v e \ 문 서 \ P y t h o 
n Space S c r i p t s \ N e u r a l Space N e t w o r k \ r a n d o m Space s a m p l e s . p 
y ' Space Enter

예외:
System.ArgumentOutOfRangeException: 값은 0보다 
크거나 같아야 하며 해당 범위에서 콘솔의 버퍼 크
기보다 작아야 합니다.
매개 변수 이름: left
실제 값은 -1입니다.
   위치: System.Console.SetCursorPosition(Int32 left, Int32 top)
   위치: Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   위치: Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   위치: Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   위치: Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   위치: Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)        
   위치: Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   위치: Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   위치: Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\nicks\OneDrive\문서\Python Scripts>  cd 'c:\Users\nicks\OneDrive\문서\Python Scripts'; & 'C:\Users\nicks\Anaconda3\python.exe' 'c:\Users\nicks\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\debugpy\launcher' '62061' '--' 'c:\Users\nicks\OneDrive\문서\Python Scripts\Neural Network\random samples.py'
[[0.15486813 0.37207683]
 [0.34064554 0.10172718]]
PS C:\Users\nicks\OneDrive\문서\Python Scripts>
PS C:\Users\nicks\OneDrive\문서\Python Scripts>

**Comment by vexx32** [comment]
Please check your PSReadLine version and ensure you're using the latest version. 🙂

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
