### ISSUE TITLE
Bug in vs code while programming in C

### ISSUE THREAD

**Issue by MaviMendes** [PowerShell/PSReadLine#1742]
While I was running a C program in VS code, this bug ocurred and there was a message to report it
The massage:
Últimas 200 Chaves:
 Space ( $ Ctrl+Alt+? ) Space { Space . \ a r q u i v o _ e o f _ 
0 7 Space } Enter
 c d Space " c : \ U s e r s \ M a r i a Space V i t ó r i a \ D o c u m e n t s \ C Space l a n g u a g e Space - Space l e a r n i n g \ a r q u v o s \ " Space ; Space i f Space ( $ Ctrl+Alt+? ) 
Space { Space g c c Space a r q u i v o s _ f p u t s _ 0 8 . c Space - o Space a r q u i v o s _ f p u t s _ 0 8 Space } Space ; Space i f Space ( $ Ctrl+Alt+? ) Space { Space . \ a r q u i v o s _ f p u t s _ 0 8 Space } Enter
 c d Space " c : \ U s e r

Exceção:
System.ArgumentOutOfRangeException: O valor deve ser maior ou igual a zero e menor que o tamanho do buffer do console nessa dimensão.
Nome do parâmetro: left
Valor real era -1.
   em System.Console.SetCursorPosition(Int32 left, Int32 top)     
   em Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   em Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   em Microsoft.PowerShell.PSConsoleReadLine.ForceRender()        
   em Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)       
   em Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   em Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
