### ISSUE TITLE
bug - Visual Studio Code

### ISSUE THREAD

**Issue by Abdullah-Jannadi** [PowerShell/PSReadLine#1746]
Last 134 Keys:
 & Space p y t h o n Space " c : / U s e r s / a b j a n / D o c u m e n t s / p a y t h 
o n / v e c t o r / N e s t e d Space L i s t s . p y " Enter
 & Space p y t h o n Space " c : / U s e r s / a b j a n / D o c u m e n t s / p a y t h 
o n / v e c t o r / N e s t e d Space L i s t s . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 7.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
dLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
