### ISSUE TITLE
Fish style abbreviations

### ISSUE THREAD

**Issue by r-darwish** [PowerShell/PSReadLine#1753]
## Description of the new feature/enhancement
Powershell doesn't allow creating an alias called `gco` that performs `git checkout`. The fish shell offers a slightly different feature called [abbreviations](https://fishshell.com/docs/current/cmds/abbr.html). When you define an abbreviation named `gco`, writing `gco` will be replaced by `git checkout` inside the command prompt whenever you hit enter or space. I think such feature will be a great addition to Powershell

**Comment by SeeminglyScience** [comment]
Related: PowerShell/PowerShell#12962

**Comment by lzybkr** [comment]
It should be simple to tweak this [sample](https://github.com/PowerShell/PSReadLine/blob/70249682ed8d87ddc3869e5d0ba852a0d6da99da/PSReadLine/SamplePSReadLineProfile.ps1#L440) to do this.

**Comment by daxian-dbw** [comment]
@r-darwish This should be an enhancement to PowerShell engine, instead of in PSReadLine. You are welcome to join the discussion in PowerShell/PowerShell#12962

**Comment by lzybkr** [comment]
@daxian-dbw IMO this is more of an editor feature (command line or other) that shouldn't require any PowerShell engine support.

**Comment by daxian-dbw** [comment]
@lzybkr Sorry for missing your comment. I agree that having this support in PSReadLine may be better as that would enforce the `abbreviation` to be an interactive feature only, which is not supported in script execution.
I have captured your comment in the corresponding PS issue.
