### ISSUE TITLE
Unable to start debugging. Program path is missing or invalid !!!

### ISSUE THREAD

**Issue by dungtrieu-git** [PowerShell/PSReadLine#1756]
Hello everyone, I'm a newbie to VS Code and I'm trying to debug a simple program shown below:

![code](https://user-images.githubusercontent.com/64150159/90362332-9483dd80-e08a-11ea-9f09-73e41f421c30.png)

When I start debugging (F5), VS Code raise up an error, it says: UNABLE TO START DEBUGGING. THE PROGRAM PATH IS MISSING OR INVALID.  GDB FAILED WITH MESSAGE: "....\demo.exe" NOT IN EXECUTABLE FORMAT: FILE FORMAT NOT RECOGNISE". 

I've read on the Internet and they said that I had to have launch.json, tasks.json, c_cpp_properties.json. Here are my 3 files:

launch.json

![launch-json](https://user-images.githubusercontent.com/64150159/90362646-4b805900-e08b-11ea-9855-c953ce9049d3.png)

tasks.json

{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "C/C++: cl.exe build active file",
			"command": "cl.exe",
			"args": [
				"/Zi",
				"/EHsc",
				"/Fe:",
				"${fileDirname}\\${fileBasenameNoExtension}.exe",
				"${file}"
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$msCompile"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
		{
			"type": "shell",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\MinGW\\bin\\g++.exe",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": "build"
		}
	]
}

c_cpp_properties.json

![c_cpp](https://user-images.githubusercontent.com/64150159/90362789-9dc17a00-e08b-11ea-9a4b-5a46ee44cd20.png)

I've scanned through other topics about this problem but it cannot solve mine. Hope that anyone could help me to find the solution. Thank you a lot for reading my topic.

**Comment by daxian-dbw** [comment]
Closing this issue as it is not related to PSReadLine.
