### ISSUE TITLE
System.ArgumentOutOfRangeException occurs when entering UpArrow

### ISSUE THREAD

**Issue by loonfactory** [PowerShell/PSReadLine#1759]
Last 1 key:
  UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to 0 and less than the console's buffer size in that range.
Parameter name: top 
The actual value is -1.
    Location: System.Console.SetCursorPosition(Int32 left, Int32 top)
    Location: Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
    Location: Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
    Location: Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
    Location: Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
    Location: Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
    Location: Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
    Location: Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
