### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Micraow** [PowerShell/PSReadLine#1762]
Vscode let me report this. I don't know what happened.
-----------------------------------------------------------------------
上 200 个密钥:
 a \ L o c a l \ P r o g r a m s \ P y t h o n \ P y t h o n 3 8 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ 7 7 9 3 3 \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 8 . 1 0 1 1 4 
4 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 5 8 1 4 1 ' Space ' - - ' Space ' c : \ P y J o b s \ O 3 6 5 - C l i e n t \ m a i n . p y ' Space Enter
 Ctrl+v Enter

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -4。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
