### ISSUE TITLE
cant't paste this multiplication sign with powershell "-geometry 1280×1024"

### ISSUE THREAD

**Issue by wswind** [PowerShell/PSReadLine#1771]
I use powershell 7.0 on win10 with win32_openssh to manage remote linux servers.
When I try to paste the following line into vnc service config file, the multiplication sign is missing.
```
ExecStart=/sbin/runuser -l username -c "/usr/bin/vncserver %i -geometry 1280×1024"
```
This is PSReadline's issue, with discussions here:<https://github.com/PowerShell/PowerShell/issues/13514>

## Steps to reproduce

1.copy 
```
1280×1024
```
2.past it into powershell window

## Expected behavior

can past multiplication sign

## Actual behavior

 the multiplication sign will be missing
![image](https://user-images.githubusercontent.com/18399096/91129912-5c5d4a00-e6dd-11ea-8425-8f2a152652b8.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
This works correctly with <kbd>Ctrl+v</kbd>, so it only fails with right click to paste which is roughly equivalent to typing the characters. I'll mention https://github.com/PowerShell/PSReadLine/issues/579, but I think this issue is distinct.

I notice that right click pasting works with the following:

```
×
×1
```

But the following does not work:

```
1×
1×1
 × # Note leading space
```

In other words, if the missing character is first, right click paste works, otherwise it does not.

It's possible this is PSReadLine at fault, but could also be .Net or conhost - that will require more investigation.

**Comment by wswind** [comment]
I made some compare tests with conemu and powershell 5 , hope it's helpful.
## test environment

powershell 5.x: version

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

ModuleType Version    Name
---------- -------    ----
Manifest   3.1.0.0    Microsoft.PowerShell.Utility
Script     2.0.0      PSReadline
```
powershell 7.x version
```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Manifest   7.0.0.0               Microsoft.PowerShell.Management
Script     2.0.2                 PSReadLine
```

## test with origin console

### powershell 5 

paste `×1`
the cursor went left when paste  mutiple times with ctrl+v or right click
![image](https://user-images.githubusercontent.com/18399096/91244625-60da3f00-e77f-11ea-88e2-a1e31ca14f50.png)

paste `1×`
`×`  will be missing with right click ,  
`ctrl + v`  works fine  but the cursor went left too.
![image](https://user-images.githubusercontent.com/18399096/91245847-080ba600-e781-11ea-974a-665b3b72fd00.png)

### powershell 7 
paste `×1` 
works fine with ctrl+v and right click
paste  `1×`
works  fine with ctrl+v but `×`  wil be missing with right click ,  


## tests with conemu
<https://conemu.github.io/>
![image](https://user-images.githubusercontent.com/18399096/91246577-c3810a00-e782-11ea-98c4-30f4a44a1ebc.png)
![image](https://user-images.githubusercontent.com/18399096/91246433-62f1cd00-e782-11ea-83a0-42fffcd4ad2a.png)

### powershell 5

paste `×1`  / `1×`
the cursor went left when paste mutiple times with ctrl+v or right click,`×`  will not be missing
![image](https://user-images.githubusercontent.com/18399096/91246841-781b2b80-e783-11ea-811b-0d2694384b91.png)

### powershell 7

paste `×1`  / `1×`
the cursor went left when paste mutiple times with ctrl+v or right click,`×`  will not be missing
![image](https://user-images.githubusercontent.com/18399096/91247205-52daed00-e784-11ea-8b0f-2b1af4343d11.png)

**Comment by daxian-dbw** [comment]
Closing as a dup of #1603

**Comment by nu8** [comment]
https://github.com/dotnet/runtime/issues/38966
