### ISSUE TITLE
i found the bugs in the Vscode powershell 

### ISSUE THREAD

**Issue by Nish76ant** [PowerShell/PSReadLine#1772]
i founded a bug in vs code powershell when i was found that regular expressions are not executing because of some bugs i am just giving the those python code below please execute in vscode after import re (regular expressions)
i was just operation of regular expressions but unable to do these operations in vscode
i hope that i will sure i will get reward for this bugs boundy
![bugs12](https://user-images.githubusercontent.com/55913847/91267272-a3f0de00-e790-11ea-9fa9-a3775a7ef95e.PNG)
![bugs12](https://user-images.githubusercontent.com/55913847/91267299-b3702700-e790-11ea-8259-a0aded6cfe48.PNG)

Name - Nishant Kumar
gmail - nk484969@gmail.com
Add - Jaipur Rajasthan India
Contact - 7691026822

import re
mystr = '''Tata Limited
Dr. David Landsman, executive director
18, Grosvenor Place
London SW1X 7HSc
Phone: +44 (20) 7235 8281
Fax: +44 (20) 7235 8727
Email: tata@tata.co.uk
Website: www.europe.tata.com
Directions: View map

Tata Sons, North America
1700 North Moore St, Suite 1520
Arlington, VA 22209-1911
USA
Phone: +1 (703) 243 9787
Fax: +1 (703) 243 9791
66-66
455-4545
Email: northamerica@tata.com 
Website: www.northamerica.tata.com
Directions: View map fass
harry bhai lekin
bahut hi badia aadmi haiaiinaiiiiiiiiiiii'''

#findall,search,split,sub,finiter

#patt = re.compile(r'fass')

# matches = patt.finditer(mystr)

# for match in matches:

#     print(match)
#     print(mystr[448:452])

# patt = re.compile(r'.adm')
# matches = patt.finditer(mystr)

# for match in matches:

#     print(match)

patt = re.compile(r'^Tata')

matches = patt.finditer(mystr)

for match in matches:

    print(match)

**Comment by vexx32** [comment]
See #1306

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
