### ISSUE TITLE
Exception:

### ISSUE THREAD

**Issue by ranvirgahir** [PowerShell/PSReadLine#1784]
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

**Comment by daxian-dbw** [comment]
This was likely fixed (see #1306 and #1315). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
