### ISSUE TITLE
Error on git commando terminal VSCode Powershell

### ISSUE THREAD

**Issue by vitorsv1** [PowerShell/PSReadLine#1792]
path/to/folder> git tag -a v1.1.1 -m "solving issue"

Last 75 Keys:
 UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow g i t Space t a g Space - a Space v 1. 1 . 1 Space - m Space "c l ea r Enter
 UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow g i t Space t a g Space - a Space v 1. 4 Space - m Space "m y Space v e r s i n n Space 1. 4"

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the size of the console buffer in this dimension.
Parameter name: left
Actual value was -1.
   in System.Console.SetCursorPosition (Int32 left, Int32 top)
   in Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft (Int32 value)
   in Microsoft.PowerShell.PSConsoleReadLine.ReallyRender (RenderData renderData, String defaultColor)
   in Microsoft.PowerShell.PSConsoleReadLine.ForceRender ()
   in Microsoft.PowerShell.PSConsoleReadLine.Insert (Char c)
   in Microsoft.PowerShell.PSConsoleReadLine.SelfInsert (Nullable`1 key, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey (ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.InputLoop ()
   in Microsoft.PowerShell.PSConsoleReadLine.ReadLine (Runspace runspace, EngineIntrinsics engineIntrinsics)
-------------------------------------------------- ---------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
