### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bjorginho** [PowerShell/PSReadLine#1814]
Last 200 Keys:
 Space w 3 8 Enter
 N e w Space Backspace _ i t e Backspace Backspace Backspace Backspace - I t e m Space - n a m e Space " l e c t u r e 2 . h s " Enter
 l s Enter
 Ctrl+l l s Enter
 L Backspace Ctrl+l g h c i Enter
 c d Space . . / Enter
 c d Space u k e s o p p g a v e r Enter
 l s Enter
 Ctrl+l l s Enter
 c d Space . . / Enter
 l s Enter
 c d Space u k e s o p p g a v e r Enter
 l s Enter
 N e w Backspace Backspace Backspace m k d i r Space w 5 Enter
 c d Space 2 5 Backspace Backspace w 5 Enter
 Ctrl+l N e w . Space Ctrl+h Backspace - Space I Backspace Backspace I t e m Space n - Backspace Backspace - n a m e Space " a s s i g n m e n t . h s " Enter
 Ctrl+l g h c i Enter
 p w s Backspace d Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: Verdien må være større enn eller lik null, og mindre enn konsollens bufferstørrelse i den dimensjonen.
*Main> parse' "+ABC"

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1315). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
