### ISSUE TITLE
Cannot find module 'fabric-shim' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ManpreetSingh28** [PowerShell/PSReadLine#1819]
Log File is attached. Please help me with the solution for this. I have tried installing 'fabric-shim' in 'demo-contract' directory, initially it gets installed but after installing throws the below error - 

LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\manpr\Desktop\demo-contract\node_modules\fabric-
shim\node_modules\@ampretia\x509\build\x509.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1      
gyp ERR! stack     at ChildProcess.onExit (C:\Users\manpr\AppData\Roaming\nvm\v10.15.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\manpr\\AppData\\Roaming\\nvm\\v10.15.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\manpr\Desktop\demo-contract\node_modules\fabric-shim\node_modules\@ampretia\x509
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN demo-contract@0.0.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ampretia/x509@0.4.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ampretia/x509@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\manpr\AppData\Roaming\npm-cache\_logs\2020-09-17T21_13_30_817Z-debug.log
[debug-log fabric shim.txt](https://github.com/PowerShell/PSReadLine/files/5241938/debug-log.fabric.shim.txt)

**Comment by daxian-dbw** [comment]
Not related to PSReadLine.
