### ISSUE TITLE
Occasional error in Set-PSReadlineKeyHandler

### ISSUE THREAD

**Issue by FallenGameR** [PowerShell/PSReadLine#182]
PsReadLine is initialized in my profile. Sometimes (once in a day or two) I get error such as this one on Powershell start (I've seen it fail with ' and ` chars):

```
Set-PSReadlineKeyHandler : Unable to translate ''' to virtual key code: The virtual key code 255 does not map to a known System.ConsoleKey enumerated value..
At C:\Users\alexko\Documents\WindowsPowerShell\Helpers\Initialize-PsReadLine.ps1:187 char:1
+ Set-PSReadlineKeyHandler -Key "Alt+'" `
```

It looks like the logic that translates chars to virtual keys sometimes fails to initialize. If the same Set-PSReadlineKeyHandler command is repeated within the same console, it fails. Module unloading doesn't seem to help. If you open a new console, it succeeds.

**Comment by FallenGameR** [comment]
Any work around for this?

During our build it looks like lots of new PS processes are created (for some reason they are created with profile inclusion - can't fix that) and some them exit with this error causing the whole build to fail.

**Comment by lzybkr** [comment]
I haven't investigated the problem yet.
As a workaround, you might consider checking the parent process at the top of your profile and skip it if it isn't explorer.exe, so something like this:

```
$parentProcessId = (Get-CimInstance Win32_Process -Filter "ProcessId='$pid'").ParentProcessId 
if ((Get-Process -Id $parentProcessId).ProcessName -ne 'explorer')
{
    return
}
```

**Comment by FallenGameR** [comment]
Good suggestion, will try it out. Thanks!

**Comment by lzybkr** [comment]
The key binding code has changed a lot recently, but I do still need VkKeyScan, so if that's the api that was failing, I'm not sure if there is another solution. As nobody else has reported this, I'm assume it's no longer a problem, closing. If you still see it, feel free to reopen.
