### ISSUE TITLE
vi-mode: Rescaling issue when maximizing PS Window

### ISSUE THREAD

**Issue by CesarB794** [PowerShell/PSReadLine#1825]
[2020.09.21-01.28_01.zip](https://github.com/PowerShell/PSReadLine/files/5253592/2020.09.21-01.28_01.zip)
Both with Powershell, as with Windows Terminal and Alacritty, the vi mode has problems rescaling when maximizing the window.
It's quite uncomfortable, as from time to time I need to use neovim with the PS window maximized.
I am attaching a zip file with a sample video of the issue.

**Comment by E3V3A** [comment]
1. Please post a screenshot of your issue.
2. Please check if `CTRL-L` refreshes and fixes your issue. 
3. maybe related to [this](https://github.com/lhmouse/nano-win/issues/12) ?

**Comment by CesarB794** [comment]
[2020.09.21-01.28_01.zip](https://github.com/PowerShell/PSReadLine/files/5321115/2020.09.21-01.28_01.zip)

**Comment by CesarB794** [comment]
![2020 10 03-01 05_03](https://user-images.githubusercontent.com/54776512/94983911-b5a66d80-0514-11eb-812b-d9b8153832e4.png)
![2020 10 03-01 06](https://user-images.githubusercontent.com/54776512/94983912-b6d79a80-0514-11eb-84c2-29dcadd1bef9.png)

**Comment by CesarB794** [comment]
native windows powershell application
![2020 10 03-01 14](https://user-images.githubusercontent.com/54776512/94984038-dae7ab80-0515-11eb-9493-da6ec05910fb.png)
![2020 10 03-01 14_01](https://user-images.githubusercontent.com/54776512/94984040-dd4a0580-0515-11eb-96ed-7c3a226630ee.png)

**Comment by CesarB794** [comment]
As you can see, the native PowerShell application works perfect (I had not noticed that before opening this issue, sorry), where if the problem happens it is with other terminals such as Alacritty and Windows Terminal

**Comment by daxian-dbw** [comment]
@CesarB794 I don't think this is related to PSReadLine or PowerShell. You are running `nvim`, which is a separate utility, and it's not the PSReadLine VI mode. It looks `nvim` doesn't work properly with Windows Terminal and Alacritty, but works fine with the legacy console host.

**Comment by CesarB794** [comment]
> @CesarB794 I don't think this is related to PSReadLine or PowerShell. You are running `nvim`, which is a separate utility, and it's not the PSReadLine VI mode. It looks `nvim` doesn't work properly with Windows Terminal and Alacritty, but works fine with the legacy console host.

The problem in the end was neovim. Upgrading to beta 0.5 the problem disappeared.
Anyway, thanks for your time :)
