### ISSUE TITLE
Files beginning with dots confuses auto-completion

### ISSUE THREAD

**Issue by jhclark** [PowerShell/PSReadLine#183]
Files beginning with dots (common for vim users) cause tab auto-complete in emacs mode to delete text.

**Failure case**
- Directory contains:  .Update-ASR.ps1.swp  Update-ASR.ps1       Update-ASR.ps1~
- Prompt begins at: PS> .\Up
- Press tab
- Prompt is now: PS> .\
- Expected behavior was that prompt would be: PS>  .\Update-ASR.ps1

**Success case**
- Delete .*
- Directory contains: Update-ASR.ps1       Update-ASR.ps1~
- Prompt begins at: PS> .\Up
- Press tab
- Prompt is now: PS>  .\Update-ASR.ps1

**Comment by lzybkr** [comment]
Related - #72.  There are other cases where text is deleted too, basically any completion where there is no common prefix, e.g. if you start the completion with a wildcard.  Type completion also has this problem when letting PowerShell figure out the namespace for you.

**Comment by bgshacklett** [comment]
So, the following is some pretty disgusting code, but it seems to do the trick. I'll have to take some time to add a test and refactor it into something that doesn't make me cringe, but here's my general thought on how to work around the problem:

https://github.com/lzybkr/PSReadLine/compare/master...bgshacklett:183_dotfiles-confuse-completion

Effectively, I'm looking to see if the buffer to be completed is a file system path. If so, I look to see if the "leaf" of the path begins with a dot. If not, I strip out any completion items which _do_ begin with a dot. Any thoughts about this general approach?

**Comment by lzybkr** [comment]
I'm thinking of a more generic fix that checks if the unambiguous prefix is shorter than the word to complete.

After detecting that, we would do something like:
* Filter out the completions that don't start with the word to complete (handling possible leading quotes in the completion that aren't in the word to complete)
* Immediately display the menu
* Something else?

**Comment by bgshacklett** [comment]
Would that take place in the same section of code or elsewhere? I'm still learning the codebase.

**Comment by lzybkr** [comment]
Close, and a fix might be possible there, but I think this [condition](https://github.com/lzybkr/PSReadLine/blob/c1c03cf1cf3ef7440e4e28affafb675ae085b99c/PSReadLine/Completion.cs#L258) needs to change.

**Comment by daxian-dbw** [comment]
This seems to be fixed already:

![screen](https://user-images.githubusercontent.com/127450/161855275-23392567-9957-4ec2-a7c6-44d791ac5cb8.gif)
