### ISSUE TITLE
Dotted and dotless i are not handled properly for Turkic languages

### ISSUE THREAD

**Issue by gokcehan** [PowerShell/PSReadLine#1832]
## Environment

```none
PS version: 5.1.19041.1
PSReadline version: 2.0.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30
```

## Steps to reproduce

1. Change keyboard input language to Turkish Q
2. Type `ı` on the keyboard (<kbd>i</kbd> key in English layout)
3. Type `İ` on the keyboard (<kbd>Shift+'</kbd> key in English layout)

## Expected behavior

It should type `ıİ` in the terminal

## Actual behavior

It types `i` in the terminal

This was originally reported to https://github.com/microsoft/terminal/issues/7726. I'm copy pasting below to make the information available here.

The above description may not be the best way to describe this issue. We have this confusing language feature in my native language Turkish as well as other Turkic languages. We have two separate characters for `i` for dotted and dotless versions. As you know fonts draw regular `i` with a dot when it is lowercase (i.e. `i`) and without a dot when it is uppercase (i.e. `I`). Therefore unicode conforming applications need to change the character value when the case is changed and the locale is Turkish. Examples below:

```
istanbul <-> ISTANBUL   (incorrect)
istanbul <-> İSTANBUL   (correct)
ıstanbul <-> ISTANBUL   (also correct but that is not the name of our city)
```

I would not mind this much but windows terminal shows `ı` as `i` which can be confusing when you forget to change your keyboard layout. Also hitting uppercase `İ` does not seem to type anything to the terminal which is kind of weird.

This issue happens in Windows terminal and powershell terminal, but cmd.exe terminal and most other applications like notepad seems to handle this properly.

Some related links below:

https://en.wikipedia.org/wiki/Dotted_and_dotless_I
https://unicode.org/faq/casemap_charprop.html

**Comment by daxian-dbw** [comment]
@gokcehan You are using a very old version of PSReadLine (2.0.0-beta2). The latest PSReadLine (version 2.0.4) fixed a few keyboard layout issues. Can you change to the the 2.0.4 version of PSReadLine and see if you issue is fixed?

**Comment by gokcehan** [comment]
@daxian-dbw I have recently upgraded my machine to Windows 2004 so I had assumed my Powershell would be somewhat recent but apparently not. I now tried installing Powershell Core 7.03 which comes with PSReadLine 2.0.2 and I can confirm this issue is fixed. Sorry for bothering. Closing this issue.
