### ISSUE TITLE
PS-Error / inside VS-Codium / Maybe message to long? -> but worked on second try 

### ISSUE THREAD

**Issue by SDS-Design** [PowerShell/PSReadLine#1837]
PS C:\Users\sscho\Documents\Angular-Workspace\project> git commit -m "Outsourcing ErrorHandling into auth.service.ts, for more flexibility in using connective services - throws Error when email is registered twice, also by unknown Errors"

Leider ist ein Fehler aufgetreten. Geben Sie mit diesem Fehler folgende Details an.
Bericht auf GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------       
Letzte 200 Tasten:
 E r r o r H a n d l i n g Space i n t o Space a u t h . s e r v i c e . t s , Space f o r Space m o r e Space f l e x i b i l i t y Space i n Space u s i n g Space c o n n e c t i v e Space s e r Backspace Backspace Backspace s e r v i c e s " Backspace Space - Space D o e s Space E r r o r Space m e Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace t h r o w w s Space Backspace Backspace Backspace s Space E r r o r Space w h e n Space e m a i l Space i s Space r e g i s t e r e d Space t w i c e " Backspace , Space a l s o Space b y Space u n k n o w n Space e Backspace E r r o r s "

Ausnahme:
System.ArgumentOutOfRangeException: Der Wert muss größer als oder gleich 0 (null) sein und geringer als die Puffergröße der Konsole in dieser Dimension.    
Parametername: top
Der tatsächliche Wert war -1.
   bei System.Console.SetCursorPosition(Int32 left, Int32 top)
   bei Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   bei Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   bei Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   bei Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bei Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
