### ISSUE TITLE
System.IndexOutOfRangeException in ConvertOffsetToCoordinates

### ISSUE THREAD

**Issue by jhclark** [PowerShell/PSReadLine#184]
Hi. Apparently, I break things a lot.

Here's a Happy New Year's stack trace (props on the nice error reporting):

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 200 Keys:
 Tab Tab Spacebar Tab Backspace Backspace - Tab Tab Ctrl+c . Spacebar Ctrl+c Ctrl+r . Spacebar Enter
 UpArrow UpArrow Enter
 UpArrow Spacebar - Tab Tab Ctrl+c Ctrl+r v i m Ctrl+c Ctrl+r . Spacebar Enter
 Ctrl+r w t Enter
 UpArrow Alt+Backspace Alt+Backspace Tab Tab Tab Tab Ctrl+c UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Spacebar - Tab Tab Tab Tab Ctrl+r . Ctrl+c Ctrl+r . Spacebar Enter
 Ctrl+r w t Enter
 UpArrow Spacebar - Tab Tab Ctrl+c UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 Alt+1 Ctrl+r . Spacebar Enter
 Ctrl+r w t Enter
 UpArrow Alt+Backspace Tab Tab Spacebar - Tab Tab Ctrl+c UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 $ p s b o u Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace p s Tab Tab d e f Tab Enter
 UpArrow Alt+Backspace p s s c r Tab Backspace Backspace Backspace Backspace Backspace $ p s s c r Tab Enter
 UpArrow Alt+Backspace $ p s c m d Tab Enter
 UpArrow Alt+Backspace $ p s Ctrl+c UpArrow UpArrow UpArrow Ctrl+c Ctrl+r . Spacebar Enter
 Ctrl+r w t Enter
 UpArrow Alt+1 Ctrl+c

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at PSConsoleUtilities.PSConsoleReadLine.ConvertOffsetToCoordinates(Int32 offset)
   at PSConsoleUtilities.PSConsoleReadLine.PlaceCursor()
   at PSConsoleUtilities.PSConsoleReadLine.ReallyRender()
   at PSConsoleUtilities.PSConsoleReadLine.DigitArgument(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
Thanks, the repro was easy and is now on GitHub.

**Comment by lzybkr** [comment]
Simple repro:
a Alt+1 Ctrl+C

**Comment by jhclark** [comment]
FYI, this isn't a huge deal. This has only happened once and probably because I fat fingered it. :)

small device, small sentences
