### ISSUE TITLE
Show ToolTip when completions exceed CompletionQueryItems

### ISSUE THREAD

**Issue by jfishe** [PowerShell/PSReadLine#1844]
## Description of the new feature/enhancement

Currently PSReadLine shows completion text but not ToolTips when the number of completions exceeds CompletionQueryItems.

It would be nice to have an option to display completions and ToolTips when answering 'y'. to the prompt: Display all 166 possibilities? (y or n) _.

Wonderful tool. Thanks for your effort.

**Comment by mklement0** [comment]
Good point, @jfishe, but I think there may be even a better way to solve this - please see #2306.

**Comment by jfishe** [comment]
That is better. Thanks!
