### ISSUE TITLE
ArgumentOutOfRangeException with narrow console

### ISSUE THREAD

**Issue by jmckoneMS** [PowerShell/PSReadLine#1845]
In Windows Terminal PowerShell 7 profile (with Oh-My-Posh), with a split screen and left side active and narrow (66 chars on left/active side, >200 on right/inactive side)

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Escape q b 1 Enter
 UpArrow Escape a l i a s Spacebar q b 1 Enter
 $ _ b u i l d Q u e u e Enter
 _ h Enter
 _ n p Spacebar $ P r o f i l e Spacebar ; Spacebar $ P S V e r s i o n T a b l e Spacebar Spacebar ; Spacebar Spacebar $ P S E d i t i o n Enter
 UpArrow UpArrow UpArrow Enter
 $ g l o b a l : _ r e p o L o n g N a m e Spacebar = Spacebar G e t - G i t R e p o L o n g N a m e Enter
 $ g l o b a l : _ b u i l d Q u e u e Spacebar = Spacebar " C D P _ $ _ r e p o L o n g N a m e " Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Shift+Home

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'left')
Actual value was 82.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor()
   at Microsoft.PowerShell.PSConsoleReadLine.BeginningOfLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass46.<SelectBackwardsLine>b__45()
   at Microsoft.PowerShell.PSConsoleReadLine.VisualSelectionCommon(Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.SelectBackwardsLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by jmckoneMS** [comment]
Little more info:
No specific steps known to get consistent repro.

Windows Terminal Preview
Version: 1.4.2652.0

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.2                   PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadlineKeyHandler…}

**Comment by daxian-dbw** [comment]
Hi @jmckoneMS, can you please confirm what version of PSReadLine module you were using? The URL `https://github.com/lzybkr/PSReadLine/issues/new` in the exception message indicates it was a pretty old version (prior to 2.0.0-beta2). If it's an old version you were using, then the issue is likely fixed in the latest version (2.0.4).

**Comment by jmckoneMS** [comment]
See above comment where additional version info was added.  
Script **1.2** PSReadLine {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadlineKeyHandler…}

I didn't realize this was so out of date.  I will update and open new issue if it repros on new version.
