### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by madbliss11** [PowerShell/PSReadLine#1852]
Произошла ошибка. Сообщите об этой ошибке, указав данные ниже.
Напишите в GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Последние клавиши 200:
 o n . e x e ' Space ' c : \ U s e r s \ K a m i k a z e \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 9 . 1 1 2 7 8 6 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 6 5 4 2 1 ' Space ' - - ' Space ' c : \ U s e r s \ K a m i k a z e \ D e s k t o p \ p r o g s \ p y _ 0 1 _ v i s u a l _ s t u d i o \ f o r m a t t i n g . p y ' Space Enter

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Фактическое значение было 14.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
