### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PhyllisXiong** [PowerShell/PSReadLine#1867]
上 200 个密钥:
 . 1 p n ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - h 5 u v 1 5 5 g . y c 2 ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - f x e 3 j 0 n b . q h 2 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - f k d 5 x 5 2 l . s z 1 ' Space ' - - d b g E x e = c : \ m i n g w 6 4 \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控
制台缓冲区在该维度的大小。
参数名: top
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object 
arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
