### ISSUE TITLE
Ctrl m(carriage return) execute current line.

### ISSUE THREAD

**Issue by unavaliabl3** [PowerShell/PSReadLine#1868]
## Description of the new feature/enhancement
Ctrl+m or ^m is the control character for carriage return (CR) and press Ctrl+M is equivariant to press the enter key in most UNIX shell (bash, fish, zsh...), But in pwsh Ctrl+M just insert a ^M under cursor.

**Comment by daxian-dbw** [comment]
FYI, this can be easily achieved by `Set-PSReadLineKeyHandler -Key ctrl+m -Function AcceptLine`.
But it's not convincing yet to make it a default.
