### ISSUE TITLE
Customize MenuComplete selection/inverted colors

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#187]
Is there a way to control the bg/fg colors of the selected item when using MenuComplete?  I have a system where the colors used make the text not readable.  It would be nice if I could configure those colors.

**Comment by lzybkr** [comment]
There isn't.  Ideally I could just set the Inverse property on the characters and conhost would do the right thing, but it doesn't.

I was trying to avoid more color options - would you mind sharing the colors you have so I can experiment a bit more to see if there is some suitable formula that works better?

**Comment by rkeithhill** [comment]
This shows the problem:
![invertedcolors](https://cloud.githubusercontent.com/assets/5177512/5850858/273c9718-a1ba-11e4-8c79-14131129c050.png)
Here is my color config:
![colorconfig](https://cloud.githubusercontent.com/assets/5177512/5850862/2ef43ba0-a1ba-11e4-8e0f-d986d5ffc6ea.png)

**Comment by godeater** [comment]
Wow. Someone that still uses the old command prompt window, and not ConEmu!

**Comment by lzybkr** [comment]
I used to use ConEmu, but it actually made me less productive unfortunately.

I noticed significantly slower builds when using ConEmu - and one somewhat flaky internal build tool would occasionally crash only in ConEmu.

Keith - what are the RGB values for Screen Text?

**Comment by rkeithhill** [comment]
Screen text color is 255,255,255 i.e. white.

**Comment by erichiller** [comment]
Piggybacking on this, as it is exactly what I was looking for as well. Specifically though with   
`Set-PSReadlineKeyHandler -Key Tab -Function Complete`   
When running autocomplete on file/path type inputs, say `cat` (`Get-Content`) or `ls` (`Get-ChildItem`)

Whereas a colorized prompt (using the module `PSColor` in addition) yields:
![image](https://cloud.githubusercontent.com/assets/5379325/24324232/ee7b9d5a-113f-11e7-9ab1-1f2b06f0953a.png)


Tab-Complete Yields:
![image](https://cloud.githubusercontent.com/assets/5379325/24324233/f75ffa92-113f-11e7-882b-c5c14ce29ca0.png)

It'd be tremendous if both outputs matched. I hope this is the same vein (_not trying to hijack_). Or is this a separate topic?

**Comment by lzybkr** [comment]
@erichiller - that's a good idea, maybe open a new issues though because it's different enough.

As for the original issue from @rkeithhill - it will be interesting to try the ANSI escape sequence for inverse - an option not available when I originally wrote this code, and also only available on Win10, but it's still possible it's an improvement.

**Comment by erichiller** [comment]
@lzybkr Thanks Jason - I wrote it up as a standalone in #523

**Comment by lzybkr** [comment]
FYI - I switched to using the ANSI escape sequence for inverse in #561 - I'm not totally happy with the result though, it looks weird when you have a bunch of different colors.

**Comment by daxian-dbw** [comment]
I think this is already addressed. See the [documentation](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.2) for `Set-PSReadLineOption -Colors`
> Selection: The color to highlight the menu selection or selected text.
