### ISSUE TITLE
'InlinePredictionColor' is not a valid color property in 2.1.0 rc1

### ISSUE THREAD

**Issue by LuanVSO** [PowerShell/PSReadLine#1876]
it seems that this line is the culprid since InlinePrediction is recognized:
https://github.com/daxian-dbw/PSReadLine/blob/ac226ba2ac8accb7c7b429dfd842fc6b33604040/test/SuggestionTest.cs#L243

**Comment by LuanVSO** [comment]
doing a search on #1860 files it seems the "color" at the end of the string is omitted in some other lines actually

**Comment by daxian-dbw** [comment]
Yes, please refer to the help documentation https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.1 and search for `-Colors`. You will find detailed description about how to set color there.

**Comment by daxian-dbw** [comment]
Yes, please refer to the help documentation https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.1 and search for `-Colors`. You will find detailed description about how to set color there.

**Comment by LuanVSO** [comment]
yeah, figured as much after some search 😅, sorry 😬
