### ISSUE TITLE
Errored out after clearing screen with powershell shortcut "Ctrl+L"

### ISSUE THREAD

**Issue by ConnorJamesLow** [PowerShell/PSReadLine#1880]
Might be nothing since I can't reproduce, but I'm just following the terminal message instructions:

## Environment

```[none]
PS version: 5.1.19041.1
PSReadline version: 2.0.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)       
HostName: ConsoleHost
BufferWidth: 103
BufferHeight: 82
```

## Exception report

```bash
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 55 Keys:
 c o d e Space - - u n i n s t a l l - e x t e n s i o n Space J a m e s B i r t l e s . s v e l t e - 
v s c o d e Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

## Steps to reproduce

1. Clear the console with `ctrl+L`
2. Be (un)lucky?

## Expected behavior

The console should clear, leaving an empty terminal.

## Actual behavior

Output the error above.

**Comment by daxian-dbw** [comment]
Thanks for the detailed information in the bug report!

This issue was fixed (see #1315). Please upgrade to the [2.1.0-rc1 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0-rc1) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by ConnorJamesLow** [comment]
I left out that this occurred in the built-in VS Code terminal. Should I post this bug there or is it just a fluke? I don't think I could reproduce it.

**Comment by daxian-dbw** [comment]
The issue should be fixed in VS Code terminal too. Please give the 2.1.0-rc1 version a try.
