### ISSUE TITLE
How can I get CTRL-D to execute my own function before ViExit?

### ISSUE THREAD

**Issue by eabase** [PowerShell/PSReadLine#1881]
I'm using this to exit my powershell sessions:
```powershell
Set-PSReadlineKeyHandler -Key ctrl+d -Function ViExit
```
But I would like to do something else before exiting, so how can I have another function be executed before [ViExit](https://github.com/PowerShell/PSReadLine/blob/a45ab815a8b1255be9d75bb157ee056aeb6a1725/PSReadLine/ReadLine.vi.cs#L204-L210) when doing `CTRL-d`?

**Comment by gwojan** [comment]
Why not bind <kbd>Ctrl+d</kbd> to a user defined function that ultimately calls `ViExit`?

**Comment by eabase** [comment]
@gwojan

> Why not bind Ctrl+d to a user defined function

That's what i wanted to do, but I was under the impression that `...-Function ViExit` was internal to PSReadLine and thus could not be replaced by `myfun()`. 

I managed to solve this by setting an event handler inside my profile script like this: 
```powershell
Register-EngineEvent PowerShell.Exiting -SupportEvent –Action { 
    Write-Host "`nExiting...`n" -fore Magenta; sleep(3); 
}
Set-PSReadlineKeyHandler -Key ctrl+d -Function ViExit
```

However, I don't think this is actually executed *before* `ViExit`, but worked for my purposes.

**Comment by gwojan** [comment]
> @gwojan
> 
> > Why not bind Ctrl+d to a user defined function
> 
> That's what i wanted to do, but I was under the impression that `...-Function ViExit` was internal to PSReadLine and thus could not be replaced by `myfun()`.
> However, I don't think this is actually executed _before_ `ViExit`, but worked for my purposes.

Yeah, sorry I meant `ScriptBlock`... That's what I get when I reply from my phone and don't really pay attention.

```PowerShell
Set-PSReadLineKeyHandler -Key 'Ctrl+d' -ScriptBlock {
   # Stuff goes here
   [Microsoft.PowerShell.PSConsoleReadLine]::ViExit()
}

**Comment by eabase** [comment]
@gwojan 
^^ That didn't work. It resulted in: 
```error
An exception occurred in custom key handler, see $error for more information: 
Exception calling "ViExit" with "0" argument(s): 
"Exception of type 'Microsoft.PowerShell.ExitException' was thrown."
```

**Comment by gwojan** [comment]
> @gwojan
> ^^ That didn't work. It resulted in:
> 
> ```
> An exception occurred in custom key handler, see $error for more information: 
> Exception calling "ViExit" with "0" argument(s): 
> "Exception of type 'Microsoft.PowerShell.ExitException' was thrown."
> ```

Of course it didn't work... ☹️ I forgot the `param()` block. Something like:

```PowerShell
Set-PSReadLineKeyHandler -Key 'Ctrl+d' -ScriptBlock {
    param($key, $arg)
    # Stuff goes here
    [Microsoft.PowerShell.PSConsoleReadLine]::ViExit()
}
```

should work but it still doesn't. `[Microsoft.PowerShell.PSConsoleReadLine]::EndOfLine()` has the calling signature and it's used in the PSReadLine example file. Maybe @daxian-dbw or @lzybkr can shed some light?

**Comment by lzybkr** [comment]
You would use:

```powershell
Set-PSReadLineKeyHandler -Key 'Ctrl+d' -ScriptBlock {
    param($key, $arg)
    # Stuff goes here
    [Microsoft.PowerShell.PSConsoleReadLine]::ViExit($key, $arg)
}
```

That said, the [exception handler](https://github.com/PowerShell/PSReadLine/blob/67f09a4136b922469c96b3f20a73eb541f4fc73c/PSReadLine/Options.cs#L243) for custom key bindings catches and reports all exceptions. It should probably ignore `Microsoft.PowerShell.ExitException`.

**Comment by eabase** [comment]
^^ Still no go: 
```
An exception occurred in custom key handler, see $error for more information: 
Exception calling "ViExit" with "2" argument(s): 
"Exception of type 'Microsoft.PowerShell.ExitException' was thrown."
```

@lzybkr 
How to catch that exception?
Should this be filed as a bug?

**Comment by gwojan** [comment]
> You would use:
> 
> ```powershell
> Set-PSReadLineKeyHandler -Key 'Ctrl+d' -ScriptBlock {
>     param($key, $arg)
>     # Stuff goes here
>     [Microsoft.PowerShell.PSConsoleReadLine]::ViExit($key, $arg)
> }
> ```
> 
> That said, the [exception handler](https://github.com/PowerShell/PSReadLine/blob/67f09a4136b922469c96b3f20a73eb541f4fc73c/PSReadLine/Options.cs#L243) for custom key bindings catches and reports all exceptions. It should probably ignore `Microsoft.PowerShell.ExitException`.

@lzybkr Do we really need to provide the arguments to `ViExit()`? I was following the examples in the `SamplePSReadLineProfile.ps1` and calls to `[Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()` and others are made without passing the arguments.

Regardless, changing the call to include passing the arguments still resulted in an exception being thrown.

**Comment by lzybkr** [comment]
Ah, `ViExit` does have default arguments (I forgot that PowerShell doesn't show those when printing the signature), so arguments aren't necessary, but it's still a good idea.

But the bottom line is - the exception can't be caught where I pointed out for this to work.
