### ISSUE TITLE
Problem with commiting

### ISSUE THREAD

**Issue by Sarah-Nguyen1993** [PowerShell/PSReadLine#1885]
I have a problem with commiting my work.
I attached the image with the err message.
![Screenshot (229)](https://user-images.githubusercontent.com/69613972/96202300-7b7d9880-0f24-11eb-8c81-63970c20cf99.png)

**Comment by daxian-dbw** [comment]
@Sarah-Nguyen1993 It would be more helpful for us if you can paste the whole exception message the next time you see a similar error -- including the "last xxx keys", "exception stack", and "environment data".

As for this one, the URL shown in the exception indicates that you were using a very old version of PSReadLine module (2.0.0-beta2 or prior). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
