### ISSUE TITLE
Index out of bounds when Powershell (with Windows Terminal) is completing a command after a previous long command was executed

### ISSUE THREAD

**Issue by keuin** [PowerShell/PSReadLine#1890]
## Environment

```none
PS version: 7.0.3
PSReadline version: 2.1.0-beta1
os: 10.0.19041.561 (WinBuild.160101.0800)
PS file version: 7.0.3.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30
```

### Environment
PSReadLine: 2.1.0-beta1
PowerShell: 7.0.3
OS: Microsoft Windows 10.0.19041
Last 6 Keys
```
 p y t h o n
```

### Exception
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToPoint(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

I ran a very long command (about 3000 Bytes) looks like "python -c ...". Then PowerShell seems to be unable to complete all my commands starting with python. Every time when I am typing p-y-t-h-o, then it fails after the 'n' was input. After that, I cannot see my cursor and the screen is flushed.

## Expected behavior

It is not expected to crash.

## Actual behavior

The screen is scrolled out and all my previous typing (i.e. p-y-t-h-o) are discarded.

Actually, this bug is related with the window size: if the window is large enough, it won't crash.

**Comment by daxian-dbw** [comment]
> Then PowerShell seems to be unable to complete all my commands starting with python.

@keuin Are you using the predictive intellisense feature while seeing this exception? (namely, does `Get-PSReadLineOption | % PredictionSource` return `History`?) Can you share a screenshot?

**Comment by keuin** [comment]
> > Then PowerShell seems to be unable to complete all my commands starting with python.
> 
> @keuin Are you using the predictive intellisense feature while seeing this exception? (namely, does `Get-PSReadLineOption | % PredictionSource` return `History`?) Can you share a screenshot?

No. This command does not echo anything. The screenshot is provided  in the attachment.

![option2](https://user-images.githubusercontent.com/9404034/97830778-1c33cc80-1d09-11eb-867a-4cc991ec06be.PNG)
![option1](https://user-images.githubusercontent.com/9404034/97830780-1dfd9000-1d09-11eb-91ee-bd89c5b0242a.PNG)

However, I have bypass this bug by running some commands like "python -c ..." which shares the same prefix with that very long command. Now my terminal works fine, but the bug still remains.

**Comment by daxian-dbw** [comment]
@keuin Can you share a screenshot of your terminal when you run into that exception? (I guess it's easy for you to reproduce it)
I would like to see the text right before the "Oops, something is wrong ..." error message.
