### ISSUE TITLE
PSReadLine Colors not setting for "Error" (always black text)

### ISSUE THREAD

**Issue by IBIT-ZEE** [PowerShell/PSReadLine#1904]
# VERSION
PowerShell 7.1rc2 (same in version 7.0x)

# STEPS to reproduce

`Set-PSReadLineOption -Colors @{ "Error" = "Red" }`

`Set-PSReadLineOption -Colors @{ "Error" = "#AABBCC" }`

`Set-PSReadLineOption -Colors @{ "Error" = [System.ConsoleColor]::Red }`

**not changing the color, always leave it black...**

**Comment by daxian-dbw** [comment]
>  always leave it black...

@IBIT-ZEE Can you please clarify what is left black?

Note that the `ErrorColor` is for rendering errors that happen in PSReadLine, not the color setting for the `ErrorRecord` thrown by a PowerShell command execution. For example, the `ErrorPrompt` feature in PSReadLine uses this color setting:

![image](https://user-images.githubusercontent.com/127450/97747182-ca8d0700-1aa8-11eb-884c-5c4184b41d47.png)
![image](https://user-images.githubusercontent.com/127450/97747232-dd074080-1aa8-11eb-9593-225dc9cc8fdd.png)

It's also used when there is a problem saving commands to the history file.

**Comment by IBIT-ZEE** [comment]
Thanks for the tip daxian... 
something very strange is happening...
The setting for the Error color I mentioned is at $Host.PrivateData.ErrorForegroundColor
When I set it to GREEN... the text come black???
I set it to RED (or other color not GREEN) and it works...

I use a console with a dark backgroud... so the GEEN-THAT-IS-BLACK do not work!

**Comment by daxian-dbw** [comment]
> The setting for the Error color I mentioned is at $Host.PrivateData.ErrorForegroundColor
When I set it to GREEN... the text come black???

I cannot reproduce that, see the screenshot below:

![image](https://user-images.githubusercontent.com/127450/97893012-99e5e100-1ce5-11eb-842e-cf8af5481f4b.png)

Also, if it's related to `$Host.PrivateData.ErrorForegroundColor`, then it's not a PSReadLine issue.
You'd better share the PowerShell version that reproduces for you, as well as the repro steps. Screenshots would be helpful.
