### ISSUE TITLE
Oops something went wrong on load of PSReadline

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/PSReadLine#191]
I restarted my pssession and received the following error:

[3:35:08 PM] [0030] » powershell
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

WARNING: Could not find ssh-agent
WARNING: Could not find ssh-agent
[3:35:18 PM] [0001] »
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at PSConsoleUtilities.PSConsoleReadLine.Initialize(Runspace remoteRunspace)
##    at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace)

Is there any more data I can provide.  Closing the powershell session and restarting it cleared the problem.

**Comment by lzybkr** [comment]
Interesting - I have almost no idea what's going on.  Is this with 1.0.0.12?  (I should add that info in the dump).

Some wild guesses:

Are you using ConEmu?
Do you do anything unusual in your profile?
Maybe there is an OnIdle event handler or some other event handler you that might be running shortly after your profile was loaded?

**Comment by tysonjhayes** [comment]
Yes I was using ConEmu (I'm assuming it's doing something weird in general? :grin: )

I'm not aware of anything 'unusual' in my profile.  I saw this after running some Pester tests which may be doing something strange.'

I will point out I haven't been able to repro this since filing this issue, but I figured filing this would at least point out a problem and might warrant adding some more info for this type of crash. :+1:

**Comment by lzybkr** [comment]
Yes, ConEmu does some crazy things because Windows makes it unnecessarily hard to do the cool things ConEmu does.

It could be Pester related too.  Based on the except, it might be related to #158.

**Comment by tysonjhayes** [comment]
Without diving into how exactly Pester is calling the tests or the ConEmu code I can't say for sure it's #158 but on the surface level I'm completely willing to buy it.

**Comment by tysonjhayes** [comment]
I haven't run into this again, so I'm closing this.
