### ISSUE TITLE
Oops, something went wrong. Second terminal window running selected PS command

### ISSUE THREAD

**Issue by FindsTheLost** [PowerShell/PSReadLine#1921]
I have script running powershell in one terminal window in second window tried to import CSV file and do exchange commands on each user in that file.  I got this message I hit ctrl + c and CTRL +X to try to stop as it kept scrolling 

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 n s e s Space " f m c n a : V I S I O C L I E N T " Space - E r r o r A c t i o n Space 
S t o p Enter
 Space Space Space Space Space Space Space Space w r i t e - h o s t Space " R e m o v i 
n g Space V I S I O C L I E N T Space f o r : " Space $ U P N Space - F o r e g r o u n d C o l o r Space G r e y Enter
 Space Space Space Space } Enter
 Space Space Space Space c a t c h Space { Enter
 Space Space Space Space Space Space Space Space W r i t e - h o s t Space $ U P N Space 
" h a s Space n o Space V I S I O C L I E N T Space l i c e n s e " Space Enter
 Space Space Space Space } Enter
 } # > Enter
 Ctrl+z

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -41.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0-rc1 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0-rc1) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
