### ISSUE TITLE
Code is not runnig properly

### ISSUE THREAD

**Issue by manvendrarawal** [PowerShell/PSReadLine#1927]
Whenever I run the code in the  VS code terminal it doesn't get compiled properly or I can say it doesn't get executed somehow .It just shows the complete code in the terminal and  shows that your code cannot be executed ,report the complain on the github.

**Comment by daxian-dbw** [comment]
@manvendrarawal Please follow the [bug report template](https://github.com/PowerShell/PSReadLine/issues/new?assignees=&labels=&template=Bug_Report.md&title=) to report the issue.
