### ISSUE TITLE
After BSD font color of varialbes is dark blue

### ISSUE THREAD

**Issue by dhcgn** [PowerShell/PSReadLine#193]
Helllo,

after my PC crashed, the font color of variables is dark blue.
I tried to delete everything under [HKEY_CURRENT_USER\Console] but it doesn't change anythink.

Sadly the font color is excatly my background color, so variables are invsibile ;)

With white background:
![ps](https://cloud.githubusercontent.com/assets/6566207/5872474/6121f3c8-a2ec-11e4-939b-01f748e230b2.png)

If I start powershell from here C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe the font color is correct.
![ps](https://cloud.githubusercontent.com/assets/6566207/5872538/f40814c4-a2ec-11e4-9428-8217808435c7.png)

**FIXED: Delete  [HKEY_CURRENT_USER\Console] for all User.**

Thx
Daniel

**Comment by lzybkr** [comment]
PSReadline relies on the console settings for the colors.  The console settings come from one of two places, the registry (which it seems you've checked) or the shortcut.  So it seems the shortcut has corrupted settings now.

You could try deleting the shortcut and creating a new one.  Alternatively, in the window with the white background, choose the system menu, then "Defaults" and correct the colors there.
