### ISSUE TITLE
A Bug in VScode

### ISSUE THREAD

**Issue by shabidabian** [PowerShell/PSReadLine#1939]
![image](https://user-images.githubusercontent.com/71911160/98443098-2e1bd200-2144-11eb-91eb-c8372e3f71ed.png)

**Comment by daxian-dbw** [comment]
@shabidabian You are using a very old version of PSReadLine, maybe 2.0.0-beta2 or prior. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
