### ISSUE TITLE
HistorySavePath docs unclear

### ISSUE THREAD

**Issue by crayy8** [PowerShell/PSReadLine#1941]
I'm a bit confused regarding the HistorySavePath param. I've used it to change the location of the history and it seems to be reset after closing out the powershell console and reopening. Is this expected? I would have expected it to be saved. 

Ex.) Set-PSReadlineOption -HistorySavePath C:\some\path\history.txt

**Comment by daxian-dbw** [comment]
`Set-PSReadlineOption` is used to configure the current session, and the configuration is not persisted in any way and that means it doesn't affect a different session. Use the user's profile (`$PROFILE`) if you want to configure some options for all sessions. For example, you can have `Set-PSReadlineOption -HistorySavePath C:\some\path\history.txt` in your profile and it will be honored for all your PS sessions.
