### ISSUE TITLE
Issue with spaces in address using PS terminal in VS code

### ISSUE THREAD

**Issue by luvitchumber** [PowerShell/PSReadLine#1949]
cd 'c:\Users\luvit\OneDrive - Queen's University\5th Year\SOFT437\Assn3'; & 
'c:\Users\luvit\.vscode\extensions\vscjava.vscode-java-debug-0.29.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-14.0.1\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:63602' '-XX:+ShowCodeDetailsInExceptionMessages' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\luvit\AppData\Roaming\Code\User\workspaceStorage\0f997c238651f3334d7e226b937a3b3b\redhat.java\jdt_ws\Assn3_3ae82188\bin'
Oops, something went wrong.  Please report this bug with the details below.     
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 d e D e t a i l s I n E x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ l u v i t \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ 0 f 9 9 7 c 2 3 8 6 5 1 f 3 3 3 4 d 7 e 2 2 6 b 9 3 7 a 3 b 3 b \ r e d h a t . j a v a \ j d t _ w s \ A s s n 3 _ 3 a e 8 2 1 8 8 \ b i n ' Space ' A s s n 3 ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by luvitchumber** [comment]
Fixed by upgrading PS 5.1 to 7
if anyone ends up here with the same issue, check PowerShell version ($PSversionTable) and then either update [PSReadLine](https://github.com/PowerShell/PSReadLine#upgrading) module or [PS](https://docs.microsoft.com/en-us/powershell/scripting/install/migrating-from-windows-powershell-51-to-powershell-7?view=powershell-7.1) if your environment allows

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
