### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by dresken** [PowerShell/PSReadLine#195]
Was wondering if a new release was coming soon?

I have been seeing lots of updates coming through - but the last version release was almost 6 months ago.

Keep up the good work
Cheers

**Comment by lzybkr** [comment]
Yeah, I probably have enough fixes in now to make a new release worthwhile - so soon I'd say.

**Comment by lzybkr** [comment]
v1.0.0.13 has been published to GitHub and to the PowerShell Gallery.
