### ISSUE TITLE
 Se produjo un error. Informa de este error indicando los detalles que tienes a continuación. Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by Gabriel0377** [PowerShell/PSReadLine#1953]
Últimas 127 claves:
 p y t h o n Space - u Space " f : Ctrl+Alt+\ U N I V E R S I D A D Ctrl+Alt+\ S E G U N D O Space C U 
A T R I M E S T R E Ctrl+Alt+\ 2 ° C u a t r i m e s t r e Space - Space ( C I 0 1 0 ) Space - Space F 
u n d a m e n t o s Space d e Space I n f o r m á t i c a Ctrl+Alt+\ P r a c t i c a s Ctrl+Alt+\ c a l c u l a d o r a . p y " Enter

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: left
Valor actual -1.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)  
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by Gabriel0377** [comment]
hola buenos días, como serian los pasos, para poder ejecutar lo que me a dicho, es que nunca e echo antes esto
