### ISSUE TITLE
Exception : System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by VincentPetit** [PowerShell/PSReadLine#1954]
-----------------------------------------------------------------------
Dernières 200 touches :
 e Space d e s Space G r a p h e s / p r o j e t / p r o j e t / p r o j e t . p y " Enter
 & Space " C : / P r o g r a m Space F i l e s Space ( x 8 6 ) / M i c r o s o f t Space V i s u a l Space S t u d i o / S h a r e d / P y t h o n 3 7 _ 6 4 / p y t h o n . e x e " Space " c : / U s e r s / v i n c e / D o c u m e n t s / E F R E I / L 3 / T h é o r i e Space d e s Space G r a p h e s / p r o j e t / p r o j e t / p r o j e t . p y " Enter

Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
La valeur réelle était -1.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   à Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   à Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   à Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
