### ISSUE TITLE
Bell on completion

### ISSUE THREAD

**Issue by narnaud** [PowerShell/PSReadLine#196]
Using PSReadlin in emacs mode (or with the bash completion in Windows mode), I have a bell when the completion is triggered and I have multiple choices.
Only the second tab show the choices.

For example, if I have "Downloads" and "Documents" in the same folder:
D:\nicolas> cd .\Do<press tab>
=> bell is ringing
D:\nicolas> cd .\Do<press tab second time>
=> show completion

I couldn't find anyway to remove the need for the first tab, is there an option for that?

**Comment by lzybkr** [comment]
That behavior is what people expect coming from Bash.  Typically it will complete the unambiguous part and beep, but in your example, you've already typed the full unambiguous part.

I believe Bash or some other shell has an option to display the completions on the first tab, I haven't implemented that exactly.

Try Ctrl+Space - this will display the possible completions immediately, it also lets you select the completion.

**Comment by narnaud** [comment]
Right, I'm not complaining about the lack of completion when filling up the unambiguous part.
I just fill strange that you have to type it twice every time: I'm more used to zsh behavior:
- if there are some unambiguous part, then fill them
- if there's no unambiguous part, then display the multiple choices
  => no need to type tab twice.

Any chance to implement it?

**Comment by lzybkr** [comment]
Sure - there's definitely a chance.

Is there a good reason for how Bash works, or is zsh just better?  If I can avoid adding an obscure, hard to explain configuration flag, I'd prefer that and just emulate zsh here.

**Comment by narnaud** [comment]
I find the zsh behavior more convenient, but it's probably because I'm used to it: if I press tab, I want to either fill the unambiguous part or show choices, I don't want a bell with the need to press tab a second time.

There's one thing that changes between bash and zsh: when showing multiple choice, bash create a new prompt line under the choices, wheres zsh keep the cursor on the same prompt line. For example, if I type `cd Do<tab>`, here is the result:
- Bash:

``` bash
boo@nicolas > cd Do
Downloads  Documents
boo@nicolas > cd Do<cursor>
```
- Zsh:

``` bash
boo@nicolas > cd Do<cursor>
Downloads  Documents
```

And once the command is executed (or canceled), the multiple choices are removed from the zsh console - uncluttering the output.

I'm not asking you to implement the whole zsh behavior, just pointing out the differences between bash and zsh.
One could argue that the first tab (with the beep) in bash is a way for the user to know that the output will be messed up with completion choices... 

For me, showing the completion choices just after pressing tab (if there's no unambiguous part to fill in) will give a better user experience to the whole prompt.

**Comment by favorini** [comment]
> For me, showing the completion choices just after pressing tab (if there's no unambiguous part to fill in) will give a better user experience to the whole prompt.

This seems good to me, also.

> There's one thing that changes between bash and zsh: when showing multiple choice, bash create a new prompt line under the choices, wheres zsh keep the cursor on the same prompt line. [...] And once the command is executed (or canceled), the multiple choices are removed from the zsh console - uncluttering the output.

I could also go for this, but the current behavior is OK.

**Comment by jibbers42** [comment]
This would be a nice change, but in the meantime time how do I disable the completion bell?

**Comment by narnaud** [comment]
@jibbers42 `Set-PSReadlineOption -BellStyle None` in your Microsoft.PowerShell_profile.ps1

**Comment by daxian-dbw** [comment]
> if I press tab, I want to either fill the unambiguous part or show choices, I don't want a bell with the need to press tab a second time.

This seems to be addressed already (in Emacs mode).

![screen](https://user-images.githubusercontent.com/127450/161856360-9cb3cf07-9e66-4462-af24-d36c3f9b96fc.gif)
