### ISSUE TITLE
PSReadLine grabs mouse input from ConEmu

### ISSUE THREAD

**Issue by kriszentner** [PowerShell/PSReadLine#197]
It seems that when loading PSReadLine in ConEmu in the Profile. The mouse input is taken from ConEmu, and no noticeable benefit is made. Would be nice to have an option to disable this (or remove it altogether until there's a reason to grab the mouse).

**Steps to reproduction**
1. Install PSReadLine using the steps here: https://github.com/lzybkr/PSReadLine
2. Put "Import-Module PSReadline" in your Powershell profile. Alternatively, you can start powershell.exe with "-NoExit -Command {Import-Module PSReadLine}
3. Type some random text, attempt to use a mouse click to position the cursor at the beginning of the line (which fails).

The ConEmu team produced a workaround for the issue, however it'd be nice to see this fixed in PSReadLine.
More information here:
https://code.google.com/p/conemu-maximus5/issues/detail?id=1886

**Comment by lzybkr** [comment]
Strange - I have considered handling mouse events, but I never wrote any code, so PSReadline isn't intentionally grabbing mouse input.  I'll have to investigate.  PowerShell could also be to blame based on something PSReadline is doing.

**Comment by hapklaar** [comment]
Was this ever fixed? I seem to run into the same issue where mouse input, specifically context menu, no longer works after updating my profile.pst with "import-module psreadline"

ps Great module overall!

**Comment by daxian-dbw** [comment]
I assume this is no longer an issue given that PSReadLine has moved to depend on .NET `Console.ReadKey` instead of Win32 APIs, so I will close this one. Feel free to open an issue if this reproduces with the latest PSReadLine module.
