### ISSUE TITLE
Feature Request: Add mouse events to PowerShell Engine

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PSReadLine#1982]
Originally posted here: https://github.com/PowerShell/PowerShell/issues/14247

It was recommended to move this to PSReadLine.

## Description of the new feature/enhancement

Whereas:

1. Both tmux and PowerShell are terminal-based applications
1. tmux supports mouse events, such as click-and-drag to resize panes, select a window, and scroll through history
1. PowerShell scripts could benefit from mouse interactions

## Proposed technical implementation details (optional)

This might be implemented using a PowerShell "engine event."

### Right-Click Event

The right-click event should include event data that describes the terminal coordinates of the click event.

```
Register-EngineEvent -Action { Draw-ContextMenu -At $event.Coordinates } -SourceIdentifier [System.Management.Automation.PsEngineEvent]::RightClick
```

### Scroll Event

The scroll up/down event should include event data about the speed / length / height (???) of the scroll.

Example

```
Register-EngineEvent -Action { GrabAndDisplay-SomeHistoricalLogData } -SourceIdentifier [System.Management.Automation.PsEngineEvent]::ScrollUp
```

### Click Event

The click event should support both a single click and double-click events. Both should include terminal coordinates where the event occurred.

```
Register-EngineEvent -Action { Perform-AnAction -At $event.Coordinates } -SourceIdentifier [System.Management.Automation.PsEngineEvent]::DoubleClick
```

**Comment by GaryAtlan82** [comment]
Will this feature ever get picked up? Its still stuck on "Not-Planned". I really need it.

**Comment by theJasonHelmick** [comment]
@GaryAtlan82  - Thank you for checking on this issue. The majority of the work required would come from .NET -- I would suggest adding a feature request to their repository. https://github.com/dotnet/runtime

**Comment by GaryAtlan82** [comment]
> @GaryAtlan82 - Thank you for checking on this issue. The majority of the work required would come from .NET -- I would suggest adding a feature request to their repository. https://github.com/dotnet/runtime

If isn't the legend himself :D . I did not know, I will do that then. Thanks allot!

**Comment by kilasuit** [comment]
@GaryAtlan82 once you've done that could you please link to this issue so that we can track if/when that feature is added to .NET

**Comment by GaryAtlan82** [comment]
> @GaryAtlan82 once you've done that could you please link to this issue so that we can track if/when that feature is added to .NET

Hey I created the feature request on the **.NET** page. I hope they pick it up. Cheers

https://github.com/dotnet/runtime/issues/89694
