### ISSUE TITLE
Reporting a bug -se details below

### ISSUE THREAD

**Issue by LuisSan** [PowerShell/PSReadLine#1988]
Last 200 Keys:
 Space b a l a n c e d Space - - i m a g e = k 8 s . g c r . i o / e c h o s e r v e r : 1 . 4 Space Enter
 k u b e c t l Space e x p o s e Space d e p l o y m e n t Space b a l a n c e d Space - - t y p e = L o a d B a l a n c e r Space - - p o r t = 8 0 8 0 Enter
 Ctrl+UpArrow ` ` UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace d e p l o y e m e n t Space b a l a n c e Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 c u r l Space 8 0 8 0 Ctrl+LeftArrow l o c a l h o s t : Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Delete Enter
 Ctrl+l

Exception:
System.IO.IOException: Felaktig parameter.

   vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   vid System.Console.SetWindowPosition(Int32 left, Int32 top)
   vid Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   vid Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   vid Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
