### ISSUE TITLE
Error when trying to activate PredictionMode

### ISSUE THREAD

**Issue by belotn** [PowerShell/PSReadLine#1992]
Hello, 

When i try to activate PredictionMode, i ran into an error  saying that the mode cannot be activated.

## Environment

```PS version: 5.1.14409.1018
PSReadline version: 2.1.0
os: 6.3.9600.16384 (winblue_rtm.130821-1623)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
HostName: ConsoleHost
BufferWidth: 170
BufferHeight: 500
```

## Exception report

Set-PSReadLineOption : The predictive suggestion feature cannot be enabled because the console output doesn't support virtual terminal processing or it's redirected.
Au caractère Ligne:1 : 1
+ Set-PSReadLineOption -PredictionSource History
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-PSReadLineOption], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.SetPSReadLineOption

## Steps to reproduce

 Set-PSReadLineOption -PredictionSource History

**Comment by daxian-dbw** [comment]
That's by design. You are uisng Windows 8, which doesn't support Vitual Terminal sequences in console output. The predicitive intellisense feature depends on the VT sequences support.

**Comment by SeidChr** [comment]
how can i test for this virtual terminal support?

**Comment by daxian-dbw** [comment]
On Windows, if virtual terminal is supported, PowerShell will turn it on by default. To quickly verify, run ``"`e[44;1mYEAH YEAH YEAH YEAH`e[0m"``, and see if the output is formatted like the following:

![image](https://user-images.githubusercontent.com/127450/142036374-b77ae229-d675-4dd9-9e5c-b8ef52cec340.png)

If not, then virtual terminal is not supported.

**Comment by SeidChr** [comment]
@daxian-dbw 
I have the activation of this in my profile, which is also being used in terminals that do not support this. There muss be a way to run the same test they do, in order to avoid seeing errors in the log for no useful reason
Right now i just see an error when it's activated, without any way of avoiding it

**Comment by hongwen000** [comment]
My workaround:
```
function Test-WindowsTerminal {
    $p = (Get-Process -Id $PID)
    while($p -Ne $null -and $p.GetType().Name -Eq "Process") {
        $name = $p.Name
        if($name -Eq "WindowsTerminal") {
            return $True
        }
        $p = $p.parent
    }
    return $False
}

Test-WindowsTerminal
```

**Comment by BusHero** [comment]
A more complex version:

```powershell
function IsVirtualTerminalProcessingEnabled {
	$MethodDefinitions = @'
[DllImport("kernel32.dll", SetLastError = true)]
public static extern IntPtr GetStdHandle(int nStdHandle);
[DllImport("kernel32.dll", SetLastError = true)]
public static extern bool GetConsoleMode(IntPtr hConsoleHandle, out uint lpMode);
'@
	$Kernel32 = Add-Type -MemberDefinition $MethodDefinitions -Name 'Kernel32' -Namespace 'Win32' -PassThru
	$hConsoleHandle = $Kernel32::GetStdHandle(-11) # STD_OUTPUT_HANDLE
	$mode = 0
	$Kernel32::GetConsoleMode($hConsoleHandle, [ref]$mode) >$null
	if ($mode -band 0x0004) { # 0x0004 ENABLE_VIRTUAL_TERMINAL_PROCESSING
		return $true
	}
	return $false
}

function CanUsePredictionSource {
	return (! [System.Console]::IsOutputRedirected) -and (IsVirtualTerminalProcessingEnabled)
}
```
Basically, a powershell version of the check used by PSReadLine [here](https://github.com/PowerShell/PSReadLine/blob/6c7ccc933fa5cea3dc092541f5a042639c930b55/PSReadLine/PlatformWindows.cs#L141)

**Comment by daxian-dbw** [comment]
> Right now i just see an error when it's activated, without any way of avoiding it

Another way is to wrap `Set-PSReadLineOption -PredictionSource History` in a try/catch block, and ignore the error in case the cmdlet fails to run.

**Comment by WojciechNagorski** [comment]
The profile file should look:
```ps1
function IsVirtualTerminalProcessingEnabled {
	$MethodDefinitions = @'
[DllImport("kernel32.dll", SetLastError = true)]
public static extern IntPtr GetStdHandle(int nStdHandle);
[DllImport("kernel32.dll", SetLastError = true)]
public static extern bool GetConsoleMode(IntPtr hConsoleHandle, out uint lpMode);
'@
	$Kernel32 = Add-Type -MemberDefinition $MethodDefinitions -Name 'Kernel32' -Namespace 'Win32' -PassThru
	$hConsoleHandle = $Kernel32::GetStdHandle(-11) # STD_OUTPUT_HANDLE
	$mode = 0
	$Kernel32::GetConsoleMode($hConsoleHandle, [ref]$mode) >$null
	if ($mode -band 0x0004) { # 0x0004 ENABLE_VIRTUAL_TERMINAL_PROCESSING
		return $true
	}
	return $false
}

function CanUsePredictionSource {
	return (! [System.Console]::IsOutputRedirected) -and (IsVirtualTerminalProcessingEnabled)
}

if (CanUsePredictionSource){ 
  Import-Module -Name Terminal-Icons
  Import-Module PSReadLine
  Set-PSReadLineOption -PredictionViewStyle ListView -PredictionSource History -HistoryNoDuplicates
}

```
