### ISSUE TITLE
Error when doing a simple tab completion 

### ISSUE THREAD

**Issue by Lucretiel** [PowerShell/PSReadLine#1994]
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 130 Keys:
 c a t Space ~ \ . Backspace D o c u Tab M i c Tab Backspace Backspace Backspace W i n Tab M i c Tab Tab Enter
 c a t Space ~ / Backspace \ D o w n Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Space Backspace Backspace \ Tab Tab Backspace Tab Backspace Tab Tab Space c Backspace Backspace Ctrl+d Backspace Enter
 Ctrl+c Ctrl+c c a t Space ~ Tab / Backspace \ Tab Backspace / D o c Tab Tab Backspace Escape Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Enter
 C : \ L Backspace U s e r l s Backspace Backspace s \ L u c r e \ Tab

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -31.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

I can consistently reproduce this by pressing `tab` when the completion prompt is at my expanded home directory. For example:

- type `~\Docu<tab>`. Exampands to `C:\Users\Lucre\Documents\`.
- Backspace until only the home directory is shown: `C:\Users\Lucre\`.
- Hit tab again. An error matching the above stacktrace is shown (obviously with a different set of reported keystrokes)

When I do some basic interactions, tab-completing my way through a directory, one of the `tab` presses triggers the error report shown above. Additionally, after that report is shown, `^C` doesn't do anything (where I'd expect it to clear the command and start a new line) until I hit enter to run a command.

# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3243.0
```

The only custom powershell configuration I do is:

- Use [starship](https://starship.rs/) for my prompt: `Invoke-Expression (&starship init powershell)`. I've confirmed that the issue is still present when this is disabled.
- Use a more sensible autocomplete behavior: `Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete`

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
