### ISSUE TITLE
Would you consider supporting PowerLine-like custom prompts?

### ISSUE THREAD

**Issue by springcomp** [PowerShell/PSReadLine#1997]
I’m a big fan of [Oh My Posh](https://github.com/jandedobbeleer/oh-my-posh3) custom prompts and have customized my PSRL `PromptText` and `ContinuationPromptText` options like so:

```
Set-PSReadLineOption -ContinuationPrompt "`e[48;2;88;88;88m `e[0m`e[38;2;88;88;88m$([char]0xE0B0)`e[0m "
Set-PSReadLineOption -PromptText "`e[38;2;88;88;88m$([char]0xE0B0)`e[0m "
```
Looks a bit barbarian but it gives me a nice prompt like this:

![image](https://user-images.githubusercontent.com/8488398/100548584-c30a7a80-326d-11eb-901e-93535ed2daaa.png)

## Description of the new feature/enhancement

The problem with customizing the `PromptText` option with ANSI escape sequences is that this prevents the default processing in `RenderErrorPrompt` behaviour to kick in.  It would be awesome if PSRL would behave like this:

![PowerShell 7 Preview 2020-11-29 18-13-41](https://user-images.githubusercontent.com/8488398/100548853-7d4eb180-326f-11eb-884b-840ab136f6ea.gif)

## Proposed technical implementation details (optional)

I would like to propose an additional option named `ErrorPromptText` that could be customized.
If set to a particular value, it would take precedence over `PromptText` being rendered in red and would be written as is.

What do you think?

**Comment by lzybkr** [comment]
This is already supported, but it's maybe not very discoverable.

The `PromptText` option can optionally accept an array where the first element is the normal prompt and the second is the error text.

This is an extract from my profile:

```powershell
$esc = [char]0x1b
$pc = [char]0xe0b0
$fg = "0"
$nbg = "8;2;95;158;160"
$ebg = "1"

$options = @{
    PromptText = "$esc[4${nbg};3${fg}mPS$esc[4${fg};3${nbg}m$pc",
                 "$esc[4${ebg};3${fg}mPS$esc[4${fg};3${ebg}m$pc"
}

Set-PSReadLineOption @options
```

And this prompt in action:

![prompt](https://user-images.githubusercontent.com/2148248/100672487-dde4f980-3316-11eb-862b-94602311af81.gif)

**Comment by springcomp** [comment]
Oh, that's awesome. Thank you !

**Comment by daxian-dbw** [comment]
We will have a series of blogs about PSReadLine functionalities in the next month of so, and this one will be included.

**Comment by mattcargile** [comment]
Was there ever a blog created for this? I searched around a little bit and couldn't find one. It is a really cool feature. I'm about to integrate it with my [`oh-my-posh.exe`](https://ohmyposh.dev/) setup.

**Comment by daxian-dbw** [comment]
@mattcargile Sorry, obviously our PM team didn't get the bandwidth to do this. I have added this issue to the "Features-for-Blogging" milestone to track it for the future blogging work.

**Comment by JanDeDobbeleer** [comment]
@mattcargile SOON™️ 👀 


https://user-images.githubusercontent.com/2492783/154807780-3769846f-6ade-4b82-a679-a283d492449f.mp4

**Comment by mattcargile** [comment]
Oh snap, @JanDeDobbeleer ! That is awesome! So beautiful!
