### ISSUE TITLE
Remove a keybinding?

### ISSUE THREAD

**Issue by moswald** [PowerShell/PSReadLine#200]
Is there a way to remove/clear a keybinding? I have multiple Powershell windows open at once, and PSReadLine shares history across all of them (which I like), but _usually_ when I hit `UpArrow` I want to get the last command run _in the current shell_. I've bound `Shift+UpArrow` to `PreviousHistory`, and I want to unbind `UpArrow` to get the Powershell default.

**Comment by lzybkr** [comment]
Remove a binding - see #154 - but it won't help you here.
See #179, #175 and #163 for discussions about history shared across sessions.  A quick summary - the next release should work pretty much exactly how you want - you can build it yourself right now or wait until I publish a new release, I'm hoping this weekend.

**Comment by moswald** [comment]
Nice. I don't mind building a new version myself. Thanks.
