### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Numieo** [PowerShell/PSReadLine#2006]
上 200 个密钥:
 s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - x r b u f p c x . b q r ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 1 n a h d 2 2 n . e a v ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - d q z y v l 1 g . 2 l n ' Space ' - - d b g E x e = C : \ P r o g r a m s \ m i n g w 6 4 \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

异常:
System.ArgumentOutOfRangeException: 该值必
须大于或等于零，且必须小于控制台缓冲区在该
维度的大小。
参数名: top
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)

**Comment by daxian-dbw** [comment]
Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
