### ISSUE TITLE
发现bug 大佬看看

### ISSUE THREAD

**Issue by hlw8895** [PowerShell/PSReadLine#2008]
异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -2。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\java练习+项目\shopping-management-system-master\0#Java基础项目\shopping-management-system>  & 'c:\Users\admin\.vscode\extensions\vscjava.vscode-java-debug-0.29.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-11.0.8\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:61767' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\admin\AppData\Roaming\Code\User\workspaceStorage\4caa9b928c66e7c7dc2e0201d81cc3bc\redhat.java\jdt_ws\shopping-management-system_754a6c78\bin' 'lyons.page.MainP
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 200 个密钥:
 l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ a d m i n \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a 
c e S t o r a g e \ 4 c a a 9 b 9 2 8 c 6 6 e 7 c 7 d c 2 e 0 2 0 1 d 8 1 c c 3 b c \ r e d h a t . j a v a \ j d t _ w s \ s h o p p i n g - m a n a g e m e n t - s y s t e m _ 7 5 4 a 6 c 7 8 \ b i n ' Space ' l y o n s . p a g e . M a i n P a g e ' Space Enter

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
