### ISSUE TITLE
Interrupted cmd files can cause problems

### ISSUE THREAD

**Issue by FallenGameR** [PowerShell/PSReadLine#201]
When a long running cmd (like build.cmd) is being interrupted with Ctrl-C, PsReadline sometimes enters some buggy state. It starts to ignore every second or 2 out of 3 keystrokes. So you type 'aa' or 'aaa' and get single 'a' in the console. When that happens if I do Remove-Module PSReadLine console fixes itself.

So far I don't have a solid repro. But I run into this program once in a week. Just today I found out that it is PsReadLine since the problem goes away if it is unloaded.

**Comment by FallenGameR** [comment]
Update - console is not fully resurrected on Remove-Module. The keyboard behaves normally, but commands are executed inconsistently:

```
D:\autopilot\apgold\autopilotservice\HK2\Acceptance-Test [ALEXKO-DEV] XYZ\alexko
» remove-module psr*
D:\autopilot\apgold\autopilotservice\HK2\Acceptance-Test [ALEXKO-DEV] XYZ\alexko
» ls

    Directory: D:\autopilot\apgold\autopilotservice\HK2\Acceptance-Test

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-ar--         6/26/2014      0:03       1178 deployment.ini
-ar--        11/26/2014      0:02         69 Machines.csv
-ar--         6/26/2014      0:03        536 MonitoringConfig.xml

D:\autopilot\apgold\autopilotservice\HK2\Acceptance-Test [ALEXKO-DEV] XYZ\alexko
» ls

D:\autopilot\apgold\autopilotservice\HK2\Acceptance-Test [ALEXKO-DEV] XYZ\alexko
» ls

```

**Comment by lzybkr** [comment]
I'm not sure this has anything to do with PSReadline - in fact, I'm not sure it has anything to do with PowerShell - I know I've seen this problem forever, so I'm guessing it's a cmd.exe problem.

**Comment by lzybkr** [comment]
Closing - this problem is not specific to PSReadLine.
