### ISSUE TITLE
Cant paste combining characters

### ISSUE THREAD

**Issue by 89z** [PowerShell/PSReadLine#2010]
I am using latest version:

~~~
PS C:\> Get-InstalledModule
2.2.0-beta1          PSReadLine                       
~~~

but if I have a character like this in the clipboard:

# a̎ (U+030E)

when I paste it, it just puts a normal `a`. This is with right click, or
control V.

**Comment by daxian-dbw** [comment]
Are you able to copy this character in cmd.exe by rigth click (or cltr+shift+v in Windows Terminal)?

**Comment by 89z** [comment]
Yeah, CMD.EXE works as expected, with Right Click and Ctrl+V - both in Console Host and Windows Terminal

**Comment by daxian-dbw** [comment]
It doesn't work for me when pasting in CMD.exe in both console host and windows terminal ...
What keybord layout are you using?

![image](https://user-images.githubusercontent.com/127450/101393568-2868f780-387c-11eb-9c8a-25c83c678c57.png)
![image](https://user-images.githubusercontent.com/127450/101393608-37e84080-387c-11eb-8069-f3be2f3ddf4c.png)

**Comment by 89z** [comment]
I dont understand your comment.

You say it doesnt work with CMD.EXE, but your screenshots show that it does work
with CMD.EXE.

To be clear, when I say "work", I mean ability to insert the character
U+030E COMBINING DOUBLE VERTICAL LINE ABOVE or similar with pasting. Granted in
your picture, you have some graphical glitches, but you are able to paste as I
am.

However with PowerShell, you cant paste at all, as any combining characters are
stripped.

**Comment by daxian-dbw** [comment]
In my screenshot, it's not a single character `a̎`, what got pasted is 2 characters `a` and `"`, I don't think we can call that works, right?

If `a"` is what you want, then <kbd>Ctrl+v</kbd> can paste the same in PowerShell:

![demo](https://user-images.githubusercontent.com/127450/101443820-1cf4eb00-38d3-11eb-9b40-43a0935c0ee9.gif)

**Comment by 89z** [comment]
Yeah its working for me now, but I just upgraded today to PowerShell 6.2. Still does not work with PowerShell 5.1. Not sure if you support that

**Comment by daxian-dbw** [comment]
It works the same on Windows PowerShell. I believe what you need is to upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.

![demo](https://user-images.githubusercontent.com/127450/101524428-c2917400-393e-11eb-8f47-b5c3bdf555ad.gif)

**Comment by 89z** [comment]
Dont you mean downgrade? See original post

**Comment by daxian-dbw** [comment]
Sorry I missed that, but <kbd>Ctrl+v</kbd> in the 2.0.0-beta1 version of PSReadLine in Windows PowerShell 5.1 works for me too:

![demo1](https://user-images.githubusercontent.com/127450/101810468-abcd5780-3acd-11eb-930f-b4ff57212c1d.gif)
