### ISSUE TITLE
Help me!!

### ISSUE THREAD

**Issue by gonzvbrr** [PowerShell/PSReadLine#2019]
Últimas 200 claves:
 i a Space B a b a r o v i c h Ctrl+Alt+\ . v s c o d e Ctrl+Alt+\ e x t e n s i o n s Ctrl+Alt+\ m s - p y t h o n . p y t h o n - 2 0 2 0 . 1 1 . 3 7 1 5 2 6 5 3 9 Ctrl+Alt+\ p y t h o n F i l e s Ctrl+Alt+\ l i b Ctrl+Alt+\ p y t h o n Ctrl+Alt+\ d e 
b u g p y Ctrl+Alt+\ l a u n c h e r ' Space ' 5 4 9 0 3 ' Space ' - - ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ C y n t h 
i a Space B a b a r o v i c h Ctrl+Alt+\ D e s k t o p Ctrl+Alt+\ U n i v e r s i d a d Ctrl+Alt+\ P r o g r a Ctrl+Alt+\ T a r e a 1 0 _ 4 . p y ' Space Enter
 Space c d Space ' c :

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: top
Valor actual -25.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
