### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by bobityw** [PowerShell/PSReadLine#2021]
When I execute my program this message appears, how should I fix it? 
Dernières 200 touches :
 n f o Ctrl+Alt+\ D M Ctrl+Alt+\ m p . p y " Enter
 p y t h o n Space - u Space " c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ i n e s r Ctrl+Alt+\ O n e 
D r i v e Ctrl+Alt+\ B u r e a u Ctrl+Alt+\ I n t r o I n f o Ctrl+Alt+\ D M Ctrl+Alt+\ m p . 
p y " Enter
 p y t h o n Space - u Space " c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ i n e s r Ctrl+Alt+\ O n e 
D r i v e Ctrl+Alt+\ B u r e a u Ctrl+Alt+\ I n t r o I n f o Ctrl+Alt+\ D M Ctrl+Alt+\ m p . 
p y " Enter
 p y t h o n Space - u Space " c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ i n e s r Ctrl+Alt+\ O n e 
D r i v e Ctrl+Alt+\ B u r e a u Ctrl+Alt+\ I n t r o I n f o Ctrl+Alt+\ D M Ctrl+Alt+\ m p . 
p y " Enter

Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : left
La valeur réelle était -1.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   à Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   à Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   à Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   à Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
