### ISSUE TITLE
CTRL-V Not working properly

### ISSUE THREAD

**Issue by RoelRotti** [PowerShell/PSReadLine#2025]
First I couldn't paste anything in my VM command line, and later when I tried pasting outside of the VM it did not work either, or only pasted a part. I'm reporting this because of an error message now and continuing to trying to make it work

**Comment by daxian-dbw** [comment]
> The maintainer may close your issue without further explanation or engagement if:
>- You delete this entire template and go your own path;
>- You file an issue that has many duplicates;
>- You file an issue completely blank in the body

Please follow the bug report template to provide needed information. Feel free to re-open this issue after having all information filled out.
