### ISSUE TITLE
Lose the ability to interact with PowerShell after superkey+right arrow

### ISSUE THREAD

**Issue by jpeazy** [PowerShell/PSReadLine#2037]
Was trying to split two separate powershell instances and when I went from Maximized to using win/superkey+right arrow, I can't interact with the shell anymore or see any text unless I maximize again. This is all the output I saw:

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 66 Keys:
 c o n Tab Enter
 ` Ctrl+v Enter
 c a t Space g e t . m Tab Enter
 ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` UpArrow UpArrow Enter
 ` Ctrl+l Ctrl+c l l s Enter
 Ctrl+c Ctrl+l ` Ctrl+l Enter
 Ctrl+v Ctrl+c ` Ctrl+c Ctrl+Enter c l s Enter
 e x i t Enter

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
>  when I went from Maximized to using win/superkey+right arrow, I can't interact with the shell anymore or see any text unless I maximize again.

This looks like a problem of the console host. CMD.exe shows the same behavior in the console host. Windows terminal works fine though.

As for the exception you got, the bug reporting URL `https://github.com/lzybkr/PSReadLine/issues/new` indicates you are using a very old version of PSReadLine (2.0.0-beta2 or prior). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same exception with the latest version.
