### ISSUE TITLE
The predictive suggestion feature cannot be enabled

### ISSUE THREAD

**Issue by EArminjon** [PowerShell/PSReadLine#2046]
Hi, 

How avoid this warning with PSReadLine and predictionsource  ?
## Environment

```none
PS version: 5.1.19041.610
PSReadline version: 2.1.0
os: 10.0.19041.561 (WinBuild.160101.0800)
PS file version: 10.0.19041.561 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30
```

## Modules :
![image](https://user-images.githubusercontent.com/37028599/102413897-f0894f00-3ff5-11eb-8f31-b5509fdb5fb6.png)

## Exception report

Some script throw error like flutter for example :

![image](https://user-images.githubusercontent.com/37028599/102413519-5a552900-3ff5-11eb-9e98-07085d5e102d.png)

Or minikube :

![image](https://user-images.githubusercontent.com/37028599/102472556-aedcc080-4056-11eb-92bd-61550d1cc643.png)

This error can stop script execution...

**Comment by daxian-dbw** [comment]
@EArminjon The prediction feature in PSReadLine depends on the underlying terminal supporting virtual terminal (ANSI control sequences). It looks like you were using a pretty old Windows 10 that doesn't support vitual terminal.

It seems you have `Set-PSReadLineOption -PredictionSource History` in your profile, so you can avoid this error by commenting out that line.

**Comment by EArminjon** [comment]
I'm using the last windows 10 pro.

**Comment by EArminjon** [comment]
I would use predictive feature so I won't disable it ...

**Comment by EArminjon** [comment]
Must i use powershell 7.1 instead 5.1 ?

**Comment by daxian-dbw** [comment]
@EArminjon My apology that I miss-read the OS build version in the environment section.

What are the `flutter` and `minikube` scripts? How is `Set-PSReadLineOption` get called in your scenario? Is it called by those script?

**Comment by EArminjon** [comment]
These scripts are just some examples. Some complexe scripts call some commands and fail because of predictive feature. 

It's seems like with theses scripts, powershell is launched with a special mode / option and the predictive feature failed.

So, i'm looking for a variable to check to disable predictive feature base on that :

```
if (not weird_powershell_config) {
 enable predictivee
}
```

**Comment by daxian-dbw** [comment]
Do these scirpts start a powershell process? If so, how do they start it?

**Comment by WojciechNagorski** [comment]
The profile file should look:
```ps1
function IsVirtualTerminalProcessingEnabled {
	$MethodDefinitions = @'
[DllImport("kernel32.dll", SetLastError = true)]
public static extern IntPtr GetStdHandle(int nStdHandle);
[DllImport("kernel32.dll", SetLastError = true)]
public static extern bool GetConsoleMode(IntPtr hConsoleHandle, out uint lpMode);
'@
	$Kernel32 = Add-Type -MemberDefinition $MethodDefinitions -Name 'Kernel32' -Namespace 'Win32' -PassThru
	$hConsoleHandle = $Kernel32::GetStdHandle(-11) # STD_OUTPUT_HANDLE
	$mode = 0
	$Kernel32::GetConsoleMode($hConsoleHandle, [ref]$mode) >$null
	if ($mode -band 0x0004) { # 0x0004 ENABLE_VIRTUAL_TERMINAL_PROCESSING
		return $true
	}
	return $false
}

function CanUsePredictionSource {
	return (! [System.Console]::IsOutputRedirected) -and (IsVirtualTerminalProcessingEnabled)
}

if (CanUsePredictionSource){ 
  Import-Module -Name Terminal-Icons
  Import-Module PSReadLine
  Set-PSReadLineOption -PredictionViewStyle ListView -PredictionSource History -HistoryNoDuplicates
}

```

**Comment by EArminjon** [comment]
> The profile file should look:
> 
> ```powershell
> function IsVirtualTerminalProcessingEnabled {
> 	$MethodDefinitions = @'
> [DllImport("kernel32.dll", SetLastError = true)]
> public static extern IntPtr GetStdHandle(int nStdHandle);
> [DllImport("kernel32.dll", SetLastError = true)]
> public static extern bool GetConsoleMode(IntPtr hConsoleHandle, out uint lpMode);
> '@
> 	$Kernel32 = Add-Type -MemberDefinition $MethodDefinitions -Name 'Kernel32' -Namespace 'Win32' -PassThru
> 	$hConsoleHandle = $Kernel32::GetStdHandle(-11) # STD_OUTPUT_HANDLE
> 	$mode = 0
> 	$Kernel32::GetConsoleMode($hConsoleHandle, [ref]$mode) >$null
> 	if ($mode -band 0x0004) { # 0x0004 ENABLE_VIRTUAL_TERMINAL_PROCESSING
> 		return $true
> 	}
> 	return $false
> }
> 
> function CanUsePredictionSource {
> 	return (! [System.Console]::IsOutputRedirected) -and (IsVirtualTerminalProcessingEnabled)
> }
> 
> if (CanUsePredictionSource){ 
>   Import-Module -Name Terminal-Icons
>   Import-Module PSReadLine
>   Set-PSReadLineOption -PredictionViewStyle ListView -PredictionSource History -HistoryNoDuplicates
> }
> ```

Ty ;) !

**Comment by alpinesox** [comment]
This can be simplified, from the looks of it. `IsVirtualTerminalProcessingEnabled` can be replaced with `$Host.UI.SupportsVirtualTerminal`. That said, you helped me years later. Thank you!

The docs:
https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostuserinterface.supportsvirtualterminal?view=powershellsdk-1.1.0

**Comment by kotylo** [comment]
Reused that `$Host.` variable from above, for copy-pasting people ;)

```powershell
function CanUsePredictionSource {
	return (! [System.Console]::IsOutputRedirected) -and $Host.UI.SupportsVirtualTerminal
}

if (CanUsePredictionSource) {
    Import-Module -Name Terminal-Icons

    Import-Module PSReadLine
    Set-PSReadLineOption -PredictionSource History
    Set-PSReadLineOption -PredictionViewStyle ListView
    Set-PSReadLineOption -EditMode Windows
}
```
