### ISSUE TITLE
run python script，itaccidently 

### ISSUE THREAD

**Issue by Tracyummy** [PowerShell/PSReadLine#2056]
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 200 个密钥:
 d a / c o n d a / e n v s / t o r c h / p y t h o n . e x e Space c : / z h a i c h a o / g i t h u b / d e t e c t _ s t e e l _ b a r / r e t i n a n e t / z c . p y Enter
 & Space C : / U s e r s / T r a c y / A p p D a t a / L o c a l / c o n d a / c o n d a / e n v s / t o r c h / p y t h o n . e x e Space c : / z h a i c h a o / g i t

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 14。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
@Tracyummy You were using a very old version of PSReadLine (2.0.0-beta2 or prior). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
