### ISSUE TITLE
PSReadline 1.0.0.13 problems on $ErrorActionPreference = 'Stop'

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PSReadLine#206]
PSReadline 1.0.0.13 is not working _sometimes_ in the following scenario
- Start PowerShell without loading PSReadline, i.e. without the profile
- Invoke commands

```
PS> $ErrorActionPreference = 'Stop'
PS> ipmo PSReadline
```

As a result, PSReadline seems to be not working. Interestingly, on Win7 x32 it started to work after a while. On two other machines (Win8 x64, Win7 x64) it does not work.

The problem did not exist in PSReadline 1.0.0.12

**Comment by lzybkr** [comment]
Thanks - it looks like PSReadline is failing on the first command line, but the module is loaded, and the second command line will work as expected.

If you looked at $error, you'd see something like:

Cannot convert argument "options", with value: "PSConsoleUtilities.PSConsoleReadlineOptions", for "SetOptions" to type
"PSConsoleUtilities.SetPSReadlineOption": "Cannot convert the "PSConsoleUtilities.PSConsoleReadlineOptions" value of
type "PSConsoleUtilities.PSConsoleReadlineOptions" to type "PSConsoleUtilities.SetPSReadlineOption"."
Cannot convert argument "options", with value: "PSConsoleUtilities.PSConsoleReadlineOptions", for "SetOptions" to type
"PSConsoleUtilities.SetPSReadlineOption": "Cannot convert the "PSConsoleUtilities.PSConsoleReadlineOptions" value of
type "PSConsoleUtilities.PSConsoleReadlineOptions" to type "PSConsoleUtilities.SetPSReadlineOption"."
At C:\Users\Jason\Documents\WindowsPowerShell\Modules\psreadline\PSReadLine.psm1:31 char:13
-             [PSConsoleUtilities.PSConsoleReadLine]::SetOptions($options)
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodException
  - FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

**Comment by nightroman** [comment]
Sorry, this is a little bit not clear to me. Is the problem confirmed? I.e. is it to be fixed?

BTW. In some cases `$Error` is populated and the PSReadline works. And sometimes `$Error` is empty and PSReadline does not work. Weird...

**Comment by lzybkr** [comment]
The error is (mostly) harmless - the fix is to just remove the line of script causing the error - it was unnecessary.  It does mean I broke the scenario of loading history yourself (HistorySaveStyle.SaveNothing), but I'll bet few people use that.

**Comment by lzybkr** [comment]
I just pushed a fix for the problem I saw.  Let me know if you still see the problem with this fix (you can just edit PSReadline.psm1, you don't need to build anything.)

**Comment by nightroman** [comment]
What you see and what I have is different. When I posted the issue I never saw this error. I did check $Error, I am sure. When you answered, I tried again and I saw this error just once. Now I cannot repro this error.

But the most important PSReadline does not work for me when I load it with `$ErrorActionPreference = 'Stop'`. This is not "harmless".

**Comment by nightroman** [comment]
I have tried the updated _PSReadline.psm1_. The problem seems to be fixed. Thank you!
