### ISSUE TITLE
web based configuration editor

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PSReadLine#2066]
Hi guys

the idea is simple but great to simplify the PSREADLINE configuration to customize the shell.

this web based config is inspired to fishshell it simplify the configuration for all users and its universal to all devices

example:

`PS> Start-PSReadlineConfiguration`

![Capture](https://user-images.githubusercontent.com/36144546/102716181-09606180-428f-11eb-9492-69d9d2ecad2f.PNG)

**Comment by daxian-dbw** [comment]
For reference: https://fishshell.com/docs/current/cmds/fish_config.html

**Comment by theJasonHelmick** [comment]
It's an interesting idea but would want to understand more about expected implementation. For example, these settings are in the users profile along with whatever additional configuration and functions they may have created.  Should this try and respect those user-made configuration?
