### ISSUE TITLE
Error when I start my asynchronous server

### ISSUE THREAD

**Issue by KonstantinShv** [PowerShell/PSReadLine#2068]
Последние клавиши 200:
 a m s \ P y t h o n \ P y t h o n 3 8 - 3 2 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ I v a n \ . v s c o d e \ e x t e 
n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 1 2 . 4 2 4 4 5 2 5 6 1 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 6 1 1 5 0 ' Space ' - - ' Space ' c : \ U s e r s \ K o n s t a n t i n \ S e r v e r 
\ a s y n c 2 V 4 . p y ' Space Enter

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности. 
Имя параметра: top
Фактическое значение было -1.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
