### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pygoov** [PowerShell/PSReadLine#2069]
Произошла ошибка. Сообщите об этой ошибке, указав данные ниже.    
Напишите в GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Последние клавиши 159:
 з н е Backspace Backspace Backspace Backspace p y t h o n 3 Backspace Space Tab Backspace Backspace Backspace Backspace Backspace Backspace . Backspace Backspace . / a s d Backspace Backspace Backspace s r v Tab Backspace Backspace r c Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace m a i Tab Enter
 Ctrl+c Ctrl+c p i p Space i n s t a l l Space p y c r y p t o d p m e Enter
 UpArrow Home RightArrow RightArrow RightArrow 3 Enter

**Comment by daxian-dbw** [comment]
The exception stack trace was not provided. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
