### ISSUE TITLE
Ctrl + Space to list available values errored

### ISSUE THREAD

**Issue by lazypowershelluser** [PowerShell/PSReadLine#2073]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow UpArrow UpArrow UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Tab Space Space Space Space UpArrow End ' Backspace ; DownArrow ; Home Delete Delete Delete Delete UpArrow End Backspace DownArrow UpArrow ; DownArrow End UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Backspace Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow LeftArrow UpArrow UpArrow UpArrow DownArrow LeftArrow LeftArrow LeftArrow UpArrow UpArrow UpArrow Home Delete C RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Delete L Enter
 UpArrow UpArrow Enter
 i n Backspace e x Space " [ ] LeftArrow End PageDown Shift+Home [ ] LeftArrow H e l l o w . Backspace Backspace Backspace Backspace Backspace l l o w Backspace W Tab . p e Tab Backspace Tab End : : ( Backspace Ctrl+Space RightArrow Enter
 ) Enter
 r e m o v e - t y Tab Tab Tab Tab Space - Tab Space Ctrl+Space h h e l l Ctrl+Space Backspace Backspace Backspace Backspace Ctrl+Space y

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1938.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Windows\system32> Remove-TypeData -TypeName

**Comment by doctordns** [comment]
I see similar output using VS Code and PowerShell 7.1.0

**Comment by daxian-dbw** [comment]
@lazypowershelluser The bug reporting URL indicates you were using a very old version of PSReadLine (2.0.0-beta2 or prior). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by daxian-dbw** [comment]
@doctordns If you run into a similar exception with 7.1.0, can you please open a new issue with detailed repro steps? That would be very helpful to the investigation.
