### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by osvgar** [PowerShell/PSReadLine#2078]
Getting the following exception when typing 'git commit -m "':
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.

**Comment by daxian-dbw** [comment]
Important information is missing, such as the exception strack trace and version of PSReadLine in use. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
