### ISSUE TITLE
Error in console output

### ISSUE THREAD

**Issue by LautaroLabarca** [PowerShell/PSReadLine#2082]
Compile Code as normally from VSC, and obtained the following message in the console: 

Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
---------------------------------------------------------------------------------------------
Últimas 200 claves:
 s c o d e Ctrl+Alt+\ e x t e n s i o n s Ctrl+Alt+\ m s - p y t h o n . p 
y t h o n - 2 0 2 0 . 1 2 . 4 2 4 4 5 2 5 6 1 Ctrl+Alt+\ p y t h o n F i l 
e s Ctrl+Alt+\ l i b Ctrl+Alt+\ p y t h o n Ctrl+Alt+\ d e b u g p y Ctrl+Alt+\ l a u n c h e r ' Space ' 5 4 7 4 0 ' Space ' - - ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ l a u t a Ctrl+Alt+\ O n e D r i v e Ctrl+Alt+\ E s c r i t o r i o Ctrl+Alt+\ P y t h o n Ctrl+Alt+\ . v s c o d e Ctrl+Alt+\ S u p e r c o n d u c t i n g - c i r c u i t s Ctrl+Alt+\ T 3 - F l u x o n i u m . p y ' Space Enter

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: left
Valor actual -1.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)      
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
----------------------------------------------------------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
