### ISSUE TITLE
Powershell Readline Error

### ISSUE THREAD

**Issue by nasserakhter** [PowerShell/PSReadLine#2084]
-----------------------------------------------------------------------
Last 200 Keys:
 t e m Backspace Backspace Backspace Backspace Backspace s t e m . R e f l e c t i o n ; End ' Backspace " @ Enter
 UpArrow Backspace Backspace Home DownArrow Home Enter
 UpArrow Space Space Space Space u s i n g Space S y s t m Backspace e m ; End End " 2 Backspace @ Enter
 UpArrow Backspace Backspace Backspace Home UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Home Home DownArrow End Enter
 Tab Space Space Space Space i s o g Backspace Backspace Backspace Backspace u s i n g Space M i c r o s o f t . C S h a r p ; End End Enter
 " @ Enter
 UpArrow Backspace Backspace Backspace Home Home DownArrow DownArrow DownArrow DownArrow End Enter
 Tab Space Space Space Space u s i n g Space S y s t e m . T e x t ; Enter
 Space Space Space Home Home Home Home Home Home Home Home UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Space Space Backspace Backspace Backspace

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
