### ISSUE TITLE
The parameter is incorrect.

### ISSUE THREAD

**Issue by kisikisikisi** [PowerShell/PSReadLine#2095]
直前 59 個のキー:
 c d Space D o c u m e n t s / s i m i l a r i t y ^ t Backspace Backspace - t a s k Enter
 i Backspace Ctrl+v Backspace i i i Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+v Ctrl+v Ctrl+v ` Enter

例外:
System.IO.IOException: パラメーターが間違っています。

   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
No information was provided about what version of PSReadLine was in use. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
