### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by PeterHolzer75** [PowerShell/PSReadLine#2101]
Last 200 Keys:
 h Space k u r s e r Ctrl+Alt+\ P y t h o n Space P r o g r a m m i n g Space f o r Space D e v e l o p e r s Ctrl+Alt+\ 
E g n a Space P r o g r a m Ctrl+Alt+\ a p p 4 . p y " Enter
 p y t h o n Space " c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ P e t e r Space H o l z e r Ctrl+Alt+\ O n e D r i v e Space - Space A B Space H e l s i n g b o r g s h e m Ctrl+Alt+\ P r i v a t Ctrl+Alt+\ M o s h Space k u r s e r Ctrl+Alt+\ P y t h o n Space P r o g r a m m i n g Space f o r Space D e v e l o p e r s Ctrl+Alt+\ E g n a Space P r o g r a m Ctrl+Alt+\ a p p 4 . p y " Enter

Exception:
System.ArgumentOutOfRangeException: Värdet måste vara större än eller lika med noll och mindre än konsolens buffertstorlek i dimensionen.
Parameternamn: left
Det faktiska värdet var -1.
   vid System.Console.SetCursorPosition(Int32 left, Int32 top)
   vid Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   vid Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   vid Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   vid Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   vid Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   vid Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   vid Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   vid Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
