### ISSUE TITLE
windows powershell Error asked me to report this...

### ISSUE THREAD

**Issue by web-advisor** [PowerShell/PSReadLine#2102]
I was compiling the following cpp code : 
#include<iostream>
#include<string>
#define N 5
using namespace std;

class Stack{
  private: 
    int arr[N];
    int top;
  public:
    Stack(){
        top = -1;
        for(auto &i:arr){
            i = 0;
        }
    }
    void display();
    
};

void Stack::display(){
      cout << "\n\t Value of Top : " << top<<endl;
      for(auto i:arr){
        cout << "\t " << i;
      }
    }

int main(){
  Stack S;
  S.display();
  return 0;
}

And I got this ::: 
Oops, something went wrong.  Please report this bug with the details below.Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 _ J o u r n e y - \ B a s i c s \ " Space ; Space i f Space ( $ ? ) Space 
{ Space g + + Space S t a c k . c p p Space - o Space S t a c k Space } Space ; Space i f Space ( $ ? ) Space { Space . \ S t a c k Space } Enter
 Space LeftArrow LeftArrow LeftArrow c l s Enter
 c d Space " c : \ A m a r Space s t u d y \ O n Space t h e Space W a y \ 
C + + \ C P P _ J o u r n e y - \ B a s i c s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space S t a c k . c p p Space - o Space S t a c 
k Space } Space ; Space i f Space ( $ ? ) Space { Space . \ S t a c k Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)      
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
