### ISSUE TITLE
Right-click paste with specific input results in a traceback

### ISSUE THREAD

**Issue by chrisbcarl** [PowerShell/PSReadLine#2112]
Priority: p4-very low, non-blocking
Affects: Powershell when launched via VSCode

Versions:
* winver: Windows Version 1909 (OS Build 18363.1256)
* code --version: 1.52.1 ea3859d4ba2f3e577a159bc91e3074c5d85c0523 x64
* $PSVersionTable:
    * PSVersion                      5.1.18362.1171
    * PSEdition                      Desktop
    * PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    * BuildVersion                   10.0.18362.1171
    * CLRVersion                     4.0.30319.42000
    * WSManStackVersion              3.0
    * PSRemotingProtocolVersion      2.3
    * SerializationVersion           1.1.0.1
* ms-vscode.powershell extension: v2020.6.0

To Reproduce:
* apply vscode global settings.json or maybe this'll work with a new project
* open network-adapters.psm1 in vscode
* open an integrated terminal (THIS MUST BE THE powershell VANILLA TERMINAL, not the weird vscode debug version of powershell that opens when the powershell language server load)
    * This does not produce a traceback launching powershell normally from desktop or cmd
* ctrl+a, right-click in the terminal
* Should see the traceback

exact upload of file which I selected and right-click pasted into vscode powershell - [network-adapters.psm1.txt](https://github.com/PowerShell/PSReadLine/files/5789285/network-adapters.psm1.txt)

visually what happened in editor / shell - [visually-what happened](https://user-images.githubusercontent.com/8985690/104062042-8b68e980-51ae-11eb-97e4-ece4ee781e06.png)

visual output of the results in full text - [right-click-copy-of-code-powershell.txt](https://github.com/PowerShell/PSReadLine/files/5789277/right-click-copy-of-code-powershell.txt)

Start-Transcript Transcript: - [2021-01-08-12-28-21-powershell.log](https://github.com/PowerShell/PSReadLine/files/5789274/2021-01-08-12-28-21-powershell.log)

vscode global user settings.json - [global-user-settings.json.txt](https://github.com/PowerShell/PSReadLine/files/5789291/global-user-settings.json.txt)

project wide .vscode/settings.json - n/a

**Comment by chrisbcarl** [comment]
might be related to #2074

**Comment by chrisbcarl** [comment]
might be related to #1944

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
