### ISSUE TITLE
an interesting bug

### ISSUE THREAD

**Issue by ljlVink** [PowerShell/PSReadLine#2116]
81 个密钥:
 c l e a r - H i s t o r y LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace C Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -16。
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   在 Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Vink\Documents\CodeSync\Sync> Clear-History
PS C:\Users\Vink\Documents\CodeSync\Sync> #include<bits/stdc++.h>
>> using namespace std;
>> int main(){
>>     cout<<"\\";
>>     return 0;
>> }#include<bits/stdc++.h>
>> using namespace std;
>> int main(){
>>     cout<<"\\";
>>     return 0;
>> }#include<bits/stdc++.h>
>> using namespace std;
>> int main(){
>>     cout<<"\\";
>>     return 0;
>> }#include<bits/stdc++.h>
>> using namespace std;
>> int main(){
>>     cout<<"\\";
>>     return 0;
>> }#include<bits/stdc++.h>
>> using namespace std;
>> int main(){
>>     cout<<"\\";
>>     return 0;
>> }

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
