### ISSUE TITLE
Argument out of range exception using latest Vi mode build

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#212]
I'm not sure if this is the correct place to post this:

1110# Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 200 Keys:
 o t e p a d p l u s p l u s Enter
 UpArrow Spacebar | Shift+Spacebar i n s t a l l - a p Backspace Backspace p a k c Tab Backspace Backspace c k Tab Enter

 LeftWindows u n b l o k c Backspace Backspace c k - f i l Tab Tab Spacebar . . / w o j Tab n Backspace d o w n Tab n o
Tab Backspace Backspace v i s Tab Enter
 c p Spacebar Alt+. Backspace Alt+. Alt+. Backspace Backspace Escape d d k b b b b b b b b b b b d 3 w i c p Spacebar Es
cape A Spacebar / p r o g r a m Tab Tab n o Tab p l u Tab Enter
 e Spacebar c : / b i n / s c r i p t s / a d d - w m i Tab Enter
 Escape k Enter
 k Backspace Escape k k k k j j j j k k j k k k k j j j j j j k k k j j j h Spacebar i h

Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collectio
n.
Parameter name: index
   at System.Text.StringBuilder.Insert(Int32 index, Char\* value, Int32 valueCount)
   at PSConsoleUtilities.PSConsoleReadLine.Insert(Char c)
   at PSConsoleUtilities.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreI
fNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()

**Comment by srdubya** [comment]
I just committed a change to fix this bug in my fork.  Thanks for finding it.

Please note, I haven't sync'd with lzybkr:master in while.  I will try to do so this weekend.

**Comment by twsouthwick** [comment]
Awesome - I just encountered this as well.  I'll watch for your fix and try out on my sequence of characters :)

**Comment by srdubya** [comment]
I sync'd with lzybkr:master last weekend, so please give it a try.

**Comment by lzybkr** [comment]
Closing presumably fixed vi mode issues.
