### ISSUE TITLE
Get-PSReadLineKeyHandler not listing Shift key

### ISSUE THREAD

**Issue by jtbm37** [PowerShell/PSReadLine#213]
I have this function in my profile :

```
Set-PSReadlineKeyHandler -Key Ctrl+Shift+j -BriefDescription MarkDirectory -Description "Mark the current directory" -ScriptBlock {

    param($key, $arg)

    $key = [Console]::ReadKey($true)

    $global:PSReadlineMarks[$key.KeyChar] = $pwd

}
```

When I want to list all keys via Get-PSReadlineKeyHandler it is listed as Ctrl+j not Ctrl+Shift+j.

However the correct key binding is working (ie Ctrl+Shift+j).

**Comment by jtbm37** [comment]
![psreadlinebug](https://cloud.githubusercontent.com/assets/536407/6546761/802f3cf0-c5b8-11e4-93f6-d27c11bacf19.png)

See screenshot attached.
Note that I have another function bound to Ctrl+j.

**Comment by jtbm37** [comment]
I just realized it is being interpreted and it is printing upper case j.

Feel free to close this if not considered a bug.

**Comment by lzybkr** [comment]
Yeah, it's working as intended.  Maybe the current behavior is too subtle, but sometimes the display was too wide and Shift wasn't strictly needed.
