### ISSUE TITLE
Search history failed(failed-fwd-i-search)

### ISSUE THREAD

**Issue by Andy-AO** [PowerShell/PSReadLine#2130]
Press `Ctrl + s`, then enter the content to search, and 'failed-fwd-i-search' will be displayed directly, and the search will fail.

PS version: 7.1.1
PSReadline version: 2.1.0-beta2
os: 10.0.18362.1014 (WinBuild.160101.0800)
PS file version: 7.1.1.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001

**Comment by p0W3RH311** [comment]
![Capture](https://user-images.githubusercontent.com/36144546/104814383-73ebbb00-57c3-11eb-868e-a1033589a972.PNG)

in 7.1.0 too

**Comment by Andy-AO** [comment]
> ![Capture](https://user-images.githubusercontent.com/36144546/104814383-73ebbb00-57c3-11eb-868e-a1033589a972.PNG)
> 
> in 7.1.0 too

It turns out that someone else has encountered this problem. Thank you for your report. I hope this problem can be solved as soon as possible, which really affects the user experience.

@daxian-dbw

**Comment by lzybkr** [comment]
History search always starts from the end of the list, so you should start with a reverse search using <kbd>Ctrl+r</kbd>.

The forward search is used when you go too far in your reverse search, similar to how you start with <kbd>UpArrow</kbd> but when you go too far, you use <kbd>DownArrow</kbd>.

**Comment by Andy-AO** [comment]
> History search always starts from the end of the list, so you should start with a reverse search using Ctrl+r.
> 
> The forward search is used when you go too far in your reverse search, similar to how you start with UpArrow but when you go too far, you use DownArrow.

In most editors, circular search is provided,It would be great if PSReadline was supported as well.
In addition, when the search is over, it's better to give a clear prompt instead of directly showing the search failure. After all, this is different from simple failure.

**Comment by lzybkr** [comment]
PSReadLine emulates GNU readline which does not wrap. I think this is a good thing as it can be hard to know when you've wrapped. Editors naturally provide a nice visual cue that you've wrapped (either implicit in the context, or explicit in the current line number in the status bar). PSReadLine could provide something similar but does not, so I would not expect wrapping to be popular.
