### ISSUE TITLE
Vi mode ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#214]
Try this `<Esc>$i$`

1828# Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 200 Keys:
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace \ $ h a ' Enter UpA
rrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter UpArrow UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftA
rrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow DownArrow DownA
rrow Escape d d i h a Spacebar \ ^ Backspace Backspace ' ^ h a . \* ' Enter # 1 7 3 4 Tab Enter r Spacebar 1 7 3 4 Backsp
ace 5 , Spacebar 1 7 3 6 , Spacebar Spacebar Backspace 1 7 3 7 , Spacebar 1 7 3 8 , Spacebar 1 7 4 1 , Spacebar 1 4 7 2
, Spacebar 1 7 4 5 Enter Escape k d d Escape k B B B B B B B e l D Enter Escape k r 6 Enter Escape k r 7 Enter r Backspa
ce Escape k r 8 Enter k Backspace Escape k h c w 4 1 Enter Escape k r 2 Enter Escape F1 k r 5 Enter b u b b a Enter Esca
pe d d l s Spacebar Backspace Backspace l s Spacebar - Ctrl+Spacebar Escape d d $ i $ Enter Escape $ i $

Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collectio
n.
Parameter name: index
   at System.Text.StringBuilder.Insert(Int32 index, Char\* value, Int32 valueCount)
   at PSConsoleUtilities.PSConsoleReadLine.Insert(Char c)
   at PSConsoleUtilities.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreI
fNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()

**Comment by srdubya** [comment]
Fixed.

**Comment by lzybkr** [comment]
Closing presumably fixed vi mode issues.
