### ISSUE TITLE
Prompt takes ~10 seconds to arrive.

### ISSUE THREAD

**Issue by Silex** [PowerShell/PSReadLine#2143]
## Environment

```none
PS version: 7.1.0
PSReadline version: 2.1.0
os: 10.0.14393.0 (rs1_release.160715-1616)
PS file version: 7.1.0.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001
```

I'm here from https://github.com/PowerShell/PowerShell/issues/14266

The OS is Windows 10, heavily restricted with policies and no internet.

Using `pwsh -NonInteractive` doesn't have this problem.

Tell me what I should investiguate, maybe use the latest master? some wireshark trace?

## Exception report

No exceptions

## Steps to reproduce

Simply run `pwsh`.

## Expected behavior

Almost instant prompt.

## Actual behavior

it displays this instantly:

```
PowerShell 7.1.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.
```

Then after ~10 seconds it displays `PS C:\Users\foo>` and I can enter commands.

**Comment by msftrncs** [comment]
PSReadLine does retrieve a command history file at start up.  I find that some of my installations take a while to load this file.

Try the command:
```PowerShell
(Get-PSReadLineOption).HistorySavePath
```

Check out the file it returns, and see if it is really large, or if access to it is very slow, possibly by network redirection.

**Comment by Silex** [comment]
@msftrncs: nothing weird here, the history file can open instantly when I `Get-Content` it. I also tried to delete it and the same thing happen.

```
PS C:\Users\ext-adm-pva> (Get-PSReadLineOption).HistorySavePath
C:\Users\ext-adm-pva\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt
```

I cannot reopen the issue, is this normal?

I just installed `7.1.2` and this happens as well, so it's a deeper issue.

**Comment by msftrncs** [comment]
@Silex, when powershell opens, does it indicate how much time it look to load user profile?   I do not see this in your reports, which probably means it is NOT the profile loading section causing the problem, and in that case it is probably NOT PSReadLine causing the issue.   What modules do you have installed when you run `-NoProfile`?

```pwsh
pwsh -noprofile
get-module
````

By some chance to you have PoshGit?  I have PoshGit load in my profile, and I notice it considerably slows the loading of my profile, so the loading delay goes away when I run with `-NoProfile`.  Any other modules that are still loaded when using `-NoProfile` may potentially be the source of the delay.

**Comment by Silex** [comment]
Actually `-NoProfile` is slow as well now.

It's the default install I don't have any modules:

```
PS C:\Users\philippe> pwsh -NoProfile
PowerShell 7.1.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.
>>>>>>>>>>>>>>> 10 SECONDS WAIT HERE <<<<<<<<<<<<<<<<
PS C:\Users\philippe> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

PS C:\Users\philippe>
```
