### ISSUE TITLE
Array Output Error

### ISSUE THREAD

**Issue by SeaGoose** [PowerShell/PSReadLine#2147]
Last 200 Keys:
 e Space $ w v d 1 ` Enter
 Space - G r o u p N a m e Space $ w v d 2 Space ` Enter
 Space - N a m e Space $ w v d 3 Space ` Enter
 Space - F i l e P a t h Space $ w v d 4 Space ` Enter
 Space - F r i e n d l y N a m e Space $ w v d 5 Space ` Enter
 Space - I c o n I n d e x Space $ w v d 6 Space ` Enter
 Space - I c o n P a t h Space $ w v d 7 Space ` Enter
 Space - C o m m a n d L i n e S e t t i n g Space $ w v d 8 Space ` Enter
 Space - S h o w I n P o r t a l : $ t r u e Enter
 # > Enter
 Space Space Space Space } Enter
 S t o p - T r a n s c r i p t Enter

**Comment by daxian-dbw** [comment]
@SeaGoose The issue description is missing important context information (e.g. exception strack trace, repro steps, environment data) for us to triage the issue, so it will be closed. Feel free to reopen once you include those information.
