### ISSUE TITLE
Vi Mode: Visual editing doesn't work if 'temp' directory has '$' in it.

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#215]
We have accounts that begin with a `$` so PowerShell has issues unless the string is quoted. Vi visual mode can't write to the temp file because the path is invalid.

What would be cool is if `v` invoked the Windows visual mode with inline selection and `V` invoked Vi visual mode via $env:VISUAL.

**Comment by srdubya** [comment]
Attempted a fix to the $ problem by wrapping the temporary filename in quotes, as suggested.  Please let me know whether or not this works for you.

I'd like to hear more about the  v vs V idea.  In BASH, V does nothing and v invokes $VISUAL/$EDITOR.  If anything, V would be what I would make do Visual Mode, but I'm not sure what is meant by that.

**Comment by gwojan** [comment]
Thanks Steve. I gave it a try and it didn't work but at least I was able to correct it after I saw what to change. I changed line 41 in VisualEditing.vi.cs to

``` c#
_singleton._buffer.Append(editorOfChoice + " \'" + _singleton._visualEditTemporaryFilename+ "\'");
```

Notice the single quotes to override PowerShell's variable substitution. :D 

Regarding `v` vs. `V`; I'm so used to the visual mode inside vim/gVim that's the behavior on the command line that I would like to emulate. In my brain `v` would allow me to visually select and edit the line without loading and editor like PSReadLine currently allows in Windows mode. `V` would actually invoke the $env:VISUAL editor. Does that make sense?

**Comment by srdubya** [comment]
Thank you, Greg.  I made the switch to single quotes.

I have never used visual mode in vim, so I'll have to play with it to get a sense of what you're talking about.  Jason mentioned that he has this working in Emacs mode, so I'm hopeful.  But first, I'll work on the other defects you're finding.
