### ISSUE TITLE
'System.Management.Automation.Subsystem.PredictionResult

### ISSUE THREAD

**Issue by menghe999** [PowerShell/PSReadLine#2150]
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.1.0-preview.2
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 9001

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
The 7.1.0-preview.2 version of PowerShell doesn't support the predictive intellisense feature which was introduced in 2.2.0-beta1. Please use the latest [7.1.1 vesrion of PowerShell](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.1).

**Comment by menghe999** [comment]
> The 7.1.0-preview.2 version of PowerShell doesn't support the predictive intellisense feature which was introduced in 2.2.0-beta1. Please use the latest [7.1.1 vesrion of PowerShell](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.1).

ok , thanks

**Comment by scotgopal** [comment]
Hello there. This problem resurfaced when I updated Powershell to v7.2.0. The following error prompts when I start my terminal.

> ### Environment
> PSReadLine: 2.2.0-beta1
> PowerShell: 7.2.0
> OS: Microsoft Windows 10.0.22000
> BufferWidth: 123
> BufferHeight: 30
> 
> Last 0 Keys
> 
> ### Exception
> ```
> System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
>    at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
>    at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
>    at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
>    at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
>    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
> ```

The following is my Powershell Profile:-

> oh-my-posh --init --shell pwsh --config D:\External-GitHub-Repos\github\prompt\ohmyposhv2.json | Invoke-Expression
> 
> Import-Module -Name Terminal-Icons
> Import-Module z
> Import-Module PSReadLine
> 
> Set-PSReadLineOption -PredictionSource History
> Set-PSReadLineOption -PredictionViewStyle ListView
> Set-PSReadLineOption -EditMode Windows

**Comment by scotgopal** [comment]
> Hello there. This problem resurfaced when I updated Powershell to v7.2.0. The following error prompts when I start my terminal.
> 
> > ### Environment
> > PSReadLine: 2.2.0-beta1
> > PowerShell: 7.2.0
> > OS: Microsoft Windows 10.0.22000
> > BufferWidth: 123
> > BufferHeight: 30
> > Last 0 Keys
> > ### Exception
> > ```
> > System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> >    at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
> >    at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
> >    at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
> >    at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
> >    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
> > ```
> 
> The following is my Powershell Profile:-
> 
> > oh-my-posh --init --shell pwsh --config D:\External-GitHub-Repos\github\prompt\ohmyposhv2.json | Invoke-Expression
> > Import-Module -Name Terminal-Icons
> > Import-Module z
> > Import-Module PSReadLine
> > Set-PSReadLineOption -PredictionSource History
> > Set-PSReadLineOption -PredictionViewStyle ListView
> > Set-PSReadLineOption -EditMode Windows

Managed to solve this by updating the PSReadLine module to v2.2.0-beta4. 🥳

**Comment by shentyrenty** [comment]
> > Hello there. This problem resurfaced when I updated Powershell to v7.2.0. The following error prompts when I start my terminal.
> > > ### Environment
> > > PSReadLine: 2.2.0-beta1
> > > PowerShell: 7.2.0
> > > OS: Microsoft Windows 10.0.22000
> > > BufferWidth: 123
> > > BufferHeight: 30
> > > Last 0 Keys
> > > ### Exception
> > > ```
> > > System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> > >    at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
> > >    at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
> > >    at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
> > >    at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
> > >    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
> > > ```
> > 
> > 
> > The following is my Powershell Profile:-
> > > oh-my-posh --init --shell pwsh --config D:\External-GitHub-Repos\github\prompt\ohmyposhv2.json | Invoke-Expression
> > > Import-Module -Name Terminal-Icons
> > > Import-Module z
> > > Import-Module PSReadLine
> > > Set-PSReadLineOption -PredictionSource History
> > > Set-PSReadLineOption -PredictionViewStyle ListView
> > > Set-PSReadLineOption -EditMode Windows
> 
> Managed to solve this by updating the PSReadLine module to v2.2.0-beta4. 🥳

I got the same error: `Install-Module PSReadLine -AllowPrerelease -Force` fixed it - From Scott Hanselman's Blog: (https://www.hanselman.com/blog/powershell-720-could-not-load-type-systemmanagementautomationsubsystempredictionresult?utm_source=feedly&utm_medium=webfeeds)
