### ISSUE TITLE
Vi Mode: Request change cursor for insert/normal mode

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#216]
Is there any way the cursor can be changed to indicate the insert/normal mode status?

**Comment by srdubya** [comment]
Done.  Use the -ChangeCursor switch parameter to turn it on (-ChangeCursor:$false for off).

**Comment by gwojan** [comment]
AWESOME!

A couple of minor nits though. :wink:

Shouldn't `-ChangeCursor` be `-ChangeViCursor` just like the property name just for the sake of consistency?

Also, to be more consistent with console vim could you make the cursor block in `normal` mode and small in `insert` mode?

**Comment by srdubya** [comment]
I initially had it as ChangeViCursor, but changed it to be more general in case other opportunities come up.  I should have changed the property name as well.  I don't know enough about Emacs or Windows mode to know whether they'd ever benefit from a cursor change.  Thoughts?

The cursor in normal mode should be the opposite of what the user has the default cursor set to (or should be).  I just tried it, and it worked for me.  So, if you want insert mode to be small, set your default via Properties - Options - Cursor Size to small.  You have to restart your console for the change to take hold as far as my code is concerned.

**Comment by lzybkr** [comment]
Windows mode should (but doesn't yet) support overstrike mode, in which case the cursor should change.

I'm not sure it's worth having an option here - it feels like there should always be a visual way to know you're in one or the other modes.  If there was an option, I would expect to choose from alternate visual styles, maybe something like: -ViNormalModeIndicator [StatusLine|Cursor].

**Comment by gwojan** [comment]
Thanks Steve. I forgot I had changed my default cursor size to `Large`. I'm getting too old I think. :pensive:

I just set my cursor size back to small and the changes were reflected immediately -- no restart. Awesome!

**Comment by gwojan** [comment]
Oops, I take that back. The cursor changed for one command and then reverted back. Oh well, restart it is. :smile:

**Comment by srdubya** [comment]
I changed the parameter to -ViModeIndicator [Cursor|StatusLine|None].  The default is None.
