### ISSUE TITLE
Parameter Preview on Multiple Parametersets over same parameters fails partially

### ISSUE THREAD

**Issue by Bosparan** [PowerShell/PSReadLine#217]
Hi,

Let's assume I have a function Get-Test with a dozen parameters, including the switch parameters $a, $b and $c.
- Parameters $a and $b are both the sole members of ParameterSet "Test1".
- Parameters $a, $b and $c are the sole members of ParameterSet "Test2".

Then in the console, I'll type this:
Get-Test -a -b -
and try using "CTRL" + "Space" to get your awesome preview of the options I have. Parameter "c" will not be in the list of options shown.

I'll admit that scenario is not all too common, but occasionally one of my functions ends up with this situation (I can define individual Output types per ParameterSet. PowerShell Studio can detect this correctly and provide the correct Primal Sense).

Not the most pressing of issues, but I thought I'd place it in the pipeline.

Cheers and thanks for all the awesome work,
Bosparan

**Comment by lzybkr** [comment]
This most likely has nothing to do with PSReadline, but I can't repro anyway, using:

```
function Get-Test
{
    param(
        [Parameter(ParameterSetName = 'Test1')]$a,
        [Parameter(ParameterSetName = 'Test1')]$b,
        [Parameter(ParameterSetName = 'Test1')]
        [Parameter(ParameterSetName = 'Test2')]$c
    )
}

Get-Test -a -b -
```

**Comment by lzybkr** [comment]
Closing as no repro.
