### ISSUE TITLE
Bug in vscode

### ISSUE THREAD

**Issue by Swanand88** [PowerShell/PSReadLine#2182]
g r a m s / P y t h o n / P y t h o n 3 9 / p y t h o n . e x e Space " c : / U s e r s / s h r e e / D e s k t o p / P y t h o n / P r o j e c t Space 2 / m a i n . p y " Enter
 & Space C : / U s e r s / s h r e e / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 9 / p y t h o n . e x e Space " c : / U s e r s / s h r e e / D e s k t o p / P y t h o n / P r o j e c t Space 2 / m a i n . p y " Enter

**Comment by theJasonHelmick** [comment]
Please help us by following the issue template to provide feedback so we can investigate.
