### ISSUE TITLE
Set-PSReadLineOption : A parameter cannot be found that matches parameter name 'PredictionSource'

### ISSUE THREAD

**Issue by DBremen** [PowerShell/PSReadLine#2189]
## Environment

```none
PS version: 5.1.19041.610
PSReadline version: 2.2.0-beta1
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 190
BufferHeight: 5000
```

## Exception report
Set-PSReadLineOption : A parameter cannot be found that matches parameter name 'PredictionSource'.

## Steps to reproduce
In PowerShell 5.1 with PSReadline 2.2.0-beta1
Attempt to set 'PredictionSource' setting

## Expected behavior
PredictionSource aka predictive IntelliSense should be available in 2.2.0-beta1 with PowerShell 5.1.

## Actual behavior
Error message as described in title.
I feel, that I'm missing something obvious, but I can't get it to work. In PowerShell 7 on the same machine, it does work just fine.

**Comment by DBremen** [comment]
I got it to work eventually by manually removing all older versions of PSReadline on my machine.

**Comment by Luttik** [comment]
@DBremen How did you ensure that all old versions are removed?

**Comment by DBremen** [comment]
@Luttik I just delete the respective folders that I found using Everything. You might be able to do it via PowerShell, too: `Get-InstalledModule -Name psreadline -AllVersions | Uninstall-Module`

**Comment by Neilblaze** [comment]
Maybe the issue is being caused by these two lines —

```
Set-PSReadLineOption -PredictionViewStyle ListView
Set-PSReadLineOption -PredictionViewStyle InlineView
```

**Comment by codeunitone** [comment]
I do not use the option PredictionViewStyle and getting the same error with PS 5.1

**Comment by gwojan** [comment]
> I do not use the option PredictionViewStyle and getting the same error with PS 5.1

If you upgrade `PSReadLine` to the latest beta version from the PowerShell Gallery your issues should be resolved.

**Comment by eabase** [comment]
To install latest _Beta_ release, open _Admin_ CMD:
```powershell
cd C:\Program Files\PowerShell\7
pwsh.exe -noprofile -command "Install-Module PSReadLine -Force -AllowPrerelease -SkipPublisherCheck"
```
(Note: Apparently no need to uninstall the older version.)

**Comment by PStoreGR** [comment]
I have the same problem so i try to put
Set-PSReadLineOption -PredictionSource History
Set-PSReadLineOption -PredictionViewStyle ListView
in my user_profile.ps1 and it work properly :)

**Comment by johannmoraes** [comment]
You need install pre release:

`Install-Module -Name PSReadLine -AllowPrerelease -Scope CurrentUser -Force -SkipPublisherCheck`

Restart terminal and try again.

**Comment by kevinlinxc** [comment]
Ok I actually ran into like 4 different errors, this thread was just the first. I compiled everything into an article:
https://kevinlinxc.medium.com/how-hard-could-installing-autocomplete-for-powershell-be-4c8a2cbc69be

**Comment by JxDarkAngel** [comment]
I had a similar problem, I did the following:
- Run terminal as admin
- `Install-Module PowerShellGet -Force`
- Log out and start terminal as admin
- `Update-Module PowerShellGet -Force`
- `Install-Module -Name PSReadLine -AllowPrerelease -Scope CurrentUser -Force -SkipPublisherCheck`
- `Set-PSReadLineOption -PredictionSource History`

Reference and more info in
https://kevinlinxc.medium.com/how-hard-could-installing-autocomplete-for-powershell-be-4c8a2cbc69be

**Comment by mohamed-f-abdelrahman** [comment]
I'm still hitting same error, do I still need to use `-AllowPrerelease ` , seems risky.

**Comment by HenkPoley** [comment]
btw, to load the pulldown history menu automatically you can drop:

```PowerShell
Set-PSReadLineOption -PredictionSource History
Set-PSReadLineOption -PredictionViewStyle ListView
```

in: `[Environment]::GetFolderPath("MyDocuments") + '\WindowsPowerShell\profile.ps1'`

You can find the location with `$PROFILE | Select-Object *Host* | Format-List`

**Comment by dkellycode** [comment]
> Ok I actually ran into like 4 different errors, this thread was just the first. I compiled everything into an article: https://kevinlinxc.medium.com/how-hard-could-installing-autocomplete-for-powershell-be-4c8a2cbc69be

@kevinlinxc your comment and blog post does not get enough recognition! You are the only person that accounted for the underlying assumption of "the user already has Winget and keeps it up to date".

**Comment by kevinlinxc** [comment]
> > Ok I actually ran into like 4 different errors, this thread was just the first. I compiled everything into an article: https://kevinlinxc.medium.com/how-hard-could-installing-autocomplete-for-powershell-be-4c8a2cbc69be
> 
> [@kevinlinxc](https://github.com/kevinlinxc) your comment and blog post does not get enough recognition! You are the only person that accounted for the underlying assumption of "the user already has Winget and keeps it up to date".

Thanks for the recognition!
