### ISSUE TITLE
Vi Mode: '<esc>r<spacebar>' on a blank line causes exception

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#219]
Pressing `<esc>r<spacebar>` on a blank line causes an exception.

1959# Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 200 Keys:
 Enter # m o d e Backspace u l e Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspa
ce Backspace $ m o d u l e UpArrow UpArrow UpArrow Enter $ m o d Tab . c o u Tab ` Backspace Enter $ m o d Tab Enter UpA
rrow Spacebar | Shift+Spacebar Backspace Backspace f i n Escape Escape d d f i n Backspace i f i n d - m o d Tab Enter P
ageUp PageDown UpArrow Spacebar - f Backspace Tab Tab Tab Tab Tab Tab Tab Spacebar \* Enter UpArrow Backspace Backspace B
ackspace Backspace Backspace Backspace Backspace Backspace n a m e Tab Spacebar \* Enter UpArrow Enter Escape k b b D Ent
er f i n d - m o d Tab Spacebar \* p x Enter K Escape d d f i n i f i n d - m o d Tab d d Escape d d f i n d Spacebar i f
 Backspace Escape f i n d Spacebar g i Escape g i t Backspace Backspace f i n d - m o d Tab Spacebar - Ctrl+Spacebar Esc
ape d d Escape r Spacebar Enter Escape r Spacebar

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at PSConsoleUtilities.PSConsoleReadLine.ReplaceCharInPlace(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreI
fNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()

**Comment by srdubya** [comment]
Fixed.  I made the console ding when you do this, as you're attempting to replace nothing with <space>.  I'm open to suggestions.

**Comment by lzybkr** [comment]
Closing presumably fixed vi mode issues.
