### ISSUE TITLE
I don't understand this bug.

### ISSUE THREAD

**Issue by uxiun** [PowerShell/PSReadLine#2201]
-----------------------------------------------------------------------
直前 200 個のキー:
 n 3 8 / p y t h o n . e x e Space c : / U s e r s / t p p / D o c u m e n t s / 学 習 / 英 語 / i d i o 
m - s c r a p e / s c r a p _ t o g e t t e r . p y Enter
 & Space C : / U s e r s / t p p / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o 
n 3 8 / p y t h o n . e x e Space c : / U s e r s / t p p / D o c u m e n t s / 学 習 / 英 語 / i d i o m - s c r a p e / s c r a p _ t o g e t t e r . p y Enter

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの次元のバッファー サイズ未満を指定しなけ 
ればなりません。
パラメーター名:top
実際の値は 8 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
@Teyugudeyuaru You didn't provide the environment data that is necessary for us to triage. If you are using a version of PSReadLine that is prior to 2.1.0 GA, then please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
