### ISSUE TITLE
visualize/tab-completion with forward slash as separator on Windows

### ISSUE THREAD

**Issue by alanlivio** [PowerShell/PSReadLine#2219]
## Description of the new feature/enhancement
I'm beginning user in PSREadLine and would like to use more a Unix-like behavior inside PowerShell  on Windows.
Two things come to my mind to extends PSReadLine:

1) Visualize slash as separator. For instance, I would like to configure PSReadLine to show the local directory indication as   
```PS /Users/alan>``` instead of ```PS C:\Users\alan>```   

2) Enable tab-completion using forward slash.  Today when using tab-completion the forward slash is converted to slash. For instance, ```ls /Users/``` followed by tab is automatic converted to ```C:\Users```  

Thanks in advance for any feedback.

**Comment by daxian-dbw** [comment]
@alanlivio Thanks for your comments. Those behavior are by design, when using PowerShell on Linux, PSReadLine will naturally use forward slash as the path separator.

**Comment by alanlivio** [comment]
Thank you @daxian-dbw. I edited my comment to make clear that I was talking about running PowerShell on Windows.
Is there a way to enable that in PSReadLine on Windows?

**Comment by jd1378** [comment]
well, no offense, but the design sucks
why not provide an option to let us decide ?
this feature is really one of the main reasons I hate using powershell
imagine you have a bash script and you want to execute it in wsl, and you are on windows
you start typing `bash press_some_letters<press_tab>` and you end up with a path thats not gonna work inside wsl :)

**Comment by 3N4N** [comment]
@jd1378 @alanlivio I looked into the code and there is no way, at least no simple way, to use unix-directory-separator in PSReadLine.  There is a place that appends a directory separator, and that's patchable, but that only changes the last directory separator, not the preceding ones.  The preceding separators are decided here:

https://github.com/PowerShell/PSReadLine/blob/9957183ff2eb128a8f9df9e077c22acf21b72fdd/PSReadLine/Completion.cs#L291

`CompleteInput` is a PowerShell builtin method, unalterable.  And the value it returns is of type `CommandCompletion`, which is readonly, so you can't even manually edit it after its creation.  In other words, there is no simple way to patch PSReadLine so it uses unix directory separator in Windows.

@daxian-dbw could you care to verify my observations?

**Comment by alanlivio** [comment]
Many thanks @jd1378. It will be nice if @daxian-dbw can confirm if is possible.

**Comment by daxian-dbw** [comment]
Sorry for the late response. @3N4N was right, the completion results for path are returned from the tab completion APIs in PowerShell engine, not generated by PSReadLine. So, the ask should better post in the PowerShell repo.
