### ISSUE TITLE
PSReadLine doesn't work on 7.2.0-preview.3

### ISSUE THREAD

**Issue by andrew-boyarshin** [PowerShell/PSReadLine#2221]
Ref: PowerShell/PowerShell#14649
Cc: @daxian-dbw

## Environment

```none
PS version: 7.2.0-preview.3
PSReadline version: 2.2.0-beta1
os: 10.0.21313.1000 (WinBuild.160101.0800)
PS file version: 7.2.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 314
BufferHeight: 62
```

## Exception report

```
System.MissingMethodException: Method not found: 'Void System.Management.Automation.Subsystem.CommandPrediction.OnCommandLineAccepted(System.Collections.Generic.IReadOnlyList`1<System.String>)'.
   at Microsoft.PowerShell.PSConsoleReadLine.Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.OnCommandLineAccepted(IReadOnlyList`1 history)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

Try running anything. Cannot even `cd` into directory, exception on `Enter` key press, aborting execution.

## Expected behavior

Working PowerShell, no exceptions.

## Actual behavior

Exception, not working command prediction and even basic stuff.

**Comment by daxian-dbw** [comment]
@andrew-boyarshin It's by design. The `ICommandPrediction` interface was changes in 7.2.0-preview.3. We will release a new beta version of PSReadLine next week to work with the new interface.
