### ISSUE TITLE
I was asked by VScode to report this problem

### ISSUE THREAD

**Issue by Shnagarsheth** [PowerShell/PSReadLine#2233]
If I write idf.py build in the terminal of VScode of the example of esp32, it does nothing. 

If I use the inbuilt ESP-IDF: Build command that it shows some error occurred during the build.

**Comment by daxian-dbw** [comment]
@Shnagarsheth Thanks for opening the issue. However, it's missing important context information that is necessary for investigation. If you ran into issues with PSReadLine, make sure upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
