### ISSUE TITLE
autocompletion of directory relative to pwd, i.e. using ..\, doesn't complete correctly 

### ISSUE THREAD

**Issue by rdcoe** [PowerShell/PSReadLine#224]
If I am in C:\Users\rcoe\Downloads and I want to switch to Documents, I type:
PS C:\Users\rcoe\Downloads> cd ..\doc
when I hit TAB, it completes as:
PS C:\Users\rcoe\Downloads> cd ..\docrs\rcoe\Documents

It looks like it knows that the path begins with C:\Users but the completion process doesn't replace the ..\doc with C:\Use.

**Comment by lzybkr** [comment]
I don't have time to check on this for a month, but I think my tabexpansion++ module (also on github) has an option for this.

**Comment by lzybkr** [comment]
Sorry - a bit more than a month :) but if you have TabExpansionPlusPlus installed, you can run:

```
Set-TabExpansionOption -Option RelativePaths -Value $false
```

This option is actually coming from PowerShell, but TabExpansionPlusPlus makes it easier to set the option.
