### ISSUE TITLE
Predictive color settings

### ISSUE THREAD

**Issue by Keene-Chen** [PowerShell/PSReadLine#2243]
## Environment

```none
PS version: 7.1.2
PSReadline version: 2.1.0
os: 10.0.19041.860 (WinBuild.160101.0800)
PS file version: 7.1.2.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 100
BufferHeight: 30
```

## Exception report
![1](https://user-images.githubusercontent.com/46097224/108957658-d7171a00-76ac-11eb-9ba4-a0692dba89be.png)

## Expected behavior

I want to change the color of the Predictive color settings, I searched the issues and the official website documents, prompted me to do so, and then the above situation appeared

**Comment by Hello-Chen** [comment]
Predictive color settings

**Comment by Keene-Chen** [comment]
![2](https://user-images.githubusercontent.com/46097224/108958633-3295d780-76ae-11eb-8b00-755f86882168.png)
### I found the answer, the color key should be InlinePrediction
