### ISSUE TITLE
v2.2b2: set-PSReadLineOption -PredictionSource HistoryAndPlugin fails with  "you need PS 7.2" error

### ISSUE THREAD

**Issue by WascawyWabbit** [PowerShell/PSReadLine#2252]
## Environment

```none
PS version: 7.1.2
PSReadline version: 2.2.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.2.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 34
```

## Steps to reproduce

set-PSReadLineOption -PredictionSource HistoryAndPlugin

## Expected behavior

No screen output, but PSReadline should make predictions based on plugins (e.g. Az.Tools.Predictor)
## Actual behavior

Error: "Set-PSReadLineOption: The prediction plugin source is not supported in this version of PowerShell. The 7.2 or a higher version of PowerShell is required to use this source."

The History and None options are valid, but no options containing plugin.

This behaviour is a change vs beta1, where enabling HistoryAndPlugin prediction sources works fine.

**Comment by DHowett** [comment]
I suspect that this is by design. It's a _beta_ release of PSReadline targeting the prediction interface of a _preview_ version of PowerShell. PSReadline has no responsibility to _lock in a version dependency_ until PSReadline exits beta, and I would guess that they won't exit beta until PowerShell stops changing its prediction interface (which they would also only do once they declare a "release" build.)

**Comment by WascawyWabbit** [comment]
I'm aware it's a beta etc.  I have accepted the usual caveats & set expectations accordingly.

It could be by design, or it could be unexpected.  I'm just reporting a change in behaviour between b2 and b1.
If it's by design then that's fair enough, as b1 works, but otherwise they may wish to restore the functionality in b3.

**Comment by DHowett** [comment]
Since a very specific error message was written for it, I suspect that they did this on purpose 😄

**Comment by daxian-dbw** [comment]
@WascawyWabbit Thanks for the report. This is by design. We made changes in the `ICommandPredictor` interface in PowerShell 7.2.0-preview.3 and corresponding changes in PSReadLine for 2.2.0-beta2, so the 2.2.0-beta2 version of PSReadLine works only on PS 7.2.0-preview.2 and later versions.
