### ISSUE TITLE
Strange effect when exiting powershell while VMWare PowerCLi  and PSReadline loaded.

### ISSUE THREAD

**Issue by MVKozlov** [PowerShell/PSReadLine#226]
powershell -noprofile
Add-PSSnapin VMware.VimAutomation.Core
Import-Module PSReadLine

when I close PS window by X-title button, before window is closed I see current directory name about several hundred times in console. something like D:\D:\D:\D:\D:\D:\D:\D:\D:.
On 'exit' there is no such effect.

Win7SP1 x64, PowerCLi v5.8R1, PSReadline - current -master, PS v4.0
It was first watched in december PSreadline release.
I'm not sure about PSReadline and not VMWare problem, but don't know how to debug.
need confirmation.

**Comment by cprugar** [comment]
Reproduced with PowerShell version 3.0, PowerCLI version 5.5, and PSReadLine 1.2.

You can workaround this by importing PSReadLine first and then adding the snapin.

**Comment by lzybkr** [comment]
If the workaround of importing PSReadLine fixes this, then I'm considering this resolved - Windows PowerShell loads PSReadLine by default starting in v5.
