### ISSUE TITLE
Set-PSReadlineOption -HistoryNoDuplicates borks value of -ViModeIndicator

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#227]
My profile loads 

``` PowerShell
Set-PSReadlineOption -EditMode Vi
Set-PSReadlineOption -ViModeIndicator Cursor
```

For the first time I set `Set-PSReadlineOption -HistoryNoDuplicates` and noticed my block cursor stopped working. Eventually I discovered `(Get-PSReadlineOption).ViModeIndicator` returned `None`.

Setting the order to

``` PowerShell
Set-PSReadlineOption -HistoryNoDuplicates
Set-PSReadlineOption -EditMode Vi
Set-PSReadlineOption -ViModeIndicator Cursor
```

is a temporary workaround.

**Comment by gwojan** [comment]
Actually, after working with this some more, it appears that any call to `Set-PSReadlineOption` turns off the mode indicator even though the the option value remains unchanged:

`ViModeIndicator                        : Cursor`

Simply executing `Set-PSReadlineOption -ViModeIndicator Cursor` restores correct behavior.

**Comment by srdubya** [comment]
I fixed the problem where the indicator mode was being reset to None.  Please give it a try and let me know if you still see it.

I also added an option called Prompt.  I haven't spent much time trying to get StatusLine working, so it is presently not available as a choice.

**Comment by gwojan** [comment]
@srdubya Thanks Steve. :smile: 

I apologize for not replying sooner -- I tested and then forgot. Everything looks good with respect to the mode indicator changing. I also like the `Prompt` option. I'm not sure I'll use it very often but it's kind of neat.
