### ISSUE TITLE
Empty line before prompt, after using Clear-Host

### ISSUE THREAD

**Issue by brunovieira97** [PowerShell/PSReadLine#2276]
## Environment

```none
PS version: 7.1.2
PSReadline version:
os: 10.0.19041.860 (WinBuild.160101.0800)
PS file version: 7.1.2.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 110
BufferHeight: 35
```

## Steps to reproduce

Have a prompt that spans for two lines, like:

```powershell
bruno@computer in ~
❯
```

I've tested this on my home directory, where there are enough items for `Get-ChildItem` output to be vertically bigger than the Terminal's line count.

```powershell
bruno@computer in ~
❯ Get-ChildItem

# Output

bruno@computer in ~
❯ Get-ChildItem

# Output

bruno@computer in ~
❯ Clear-Host
```

## Expected behavior

Prompt is written to console and there is no scroll bar, like this:
![image](https://user-images.githubusercontent.com/19749621/110251680-60a5d200-7f60-11eb-93c0-3b656baa3814.png)

## Actual behavior

After two or three `Get-ChildItem`'s (there's no exact count, except that it must be more than 1 time in a row), `Clear-Host` will add an extra empty line before writing the prompt to console. The cursor position, though, will be on the correct location, meaning that Windows Terminal will display a scrollbar so you can go one line up.

![image](https://user-images.githubusercontent.com/19749621/110251737-a95d8b00-7f60-11eb-8635-1ce8bb57676f.png)

If you drag the scrollbar to the top, this is shown:
![image](https://user-images.githubusercontent.com/19749621/110251763-c85c1d00-7f60-11eb-9267-1836898e9ada.png)

 - I've tested disabling PSReadLine on current session by running `Remove-Module PSReadLine` and everything started to work as expected.
 - Tested with ConHost, but could not reproduce the error there.
 - Tried calling `Set-PSReadLineOption -ExtraPromptLineCount 1`, with no effect whatsoever on console output

**Comment by daxian-dbw** [comment]
I cannot reproduce this in both Windows Terminal and Conhost, with a simple 2-line prompt ``function prompt { "abc`n> " }``:

![demo1](https://user-images.githubusercontent.com/127450/110702866-ec5d6f80-81a7-11eb-98e0-068afc0aba6e.gif)

Is the issue related to your specific prompt function?

**Comment by iSazonov** [comment]
Maybe key is "After **two or three** Get-ChildItem's (there's no exact count, except that it must be more than 1 time in a row)"

**Comment by daxian-dbw** [comment]
Still cannot repro "after two or three Get-ChildItem's":

![demo1](https://user-images.githubusercontent.com/127450/110828115-93471780-824b-11eb-9e6b-0899b7faf78f.gif)

**Comment by iSazonov** [comment]
I can not repro with Windows Terminal latest preview 1.7.572.0 and Microsoft Windows 10.0.18363

**Comment by brunovieira97** [comment]
I use Oh-My-Posh and Posh-Git, but that does not seem related to the problem.

Just removed those modules Import statements from my profile, and left just PSReadLine. This is the result:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/19749621/110960846-f14c2b80-832d-11eb-9106-7ee3c5659c49.gif)

It appears as the line being left behind is always the first one to be displayed on console's "viewport".
 - My prompt has 2 lines height
 - My `Get-ChildItem` output has a height of 43 lines
 - My Windows Terminal window allows for exhibition of 35 lines
 - When printing the items, `Get-ChildItem` makes Windows Terminal scroll down 12 lines, making `.m2` directory the first item listed
 - Whenever the issue occurs (it's not 100% of the time, apparently), it's always `.m2` being displayed over the prompt.

**Comment by iSazonov** [comment]
Could you please start with `pwsh -NoProfile` and check again?

**Comment by brunovieira97** [comment]
Just tested with -NoProfile. Here's the result:

![2021-03-13-115739](https://user-images.githubusercontent.com/19749621/111034294-b8768a00-83f3-11eb-9da5-454e1712bd67.gif)

As I said, some times it will not happen. It's very, very strange lol

**Comment by iSazonov** [comment]
Could you please share `gcm clear` output?
And `gcm clear-host -ShowCommandInfo` too.

**Comment by brunovieira97** [comment]
Sorry for the delay! Here it goes:
```
PS C:\Users\bruno> gcm clear

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           clear -> Clear-Host
```

```
PS C:\Users\bruno> gcm clear-host -ShowCommandInfo

Name          : Clear-Host
ModuleName    :
Module        : @{Name=}
CommandType   : Function
Definition    :
                $RawUI = $Host.UI.RawUI
                $RawUI.CursorPosition = @{X=0;Y=0}
                $RawUI.SetBufferContents(
                    @{Top = -1; Bottom = -1; Right = -1; Left = -1},
                    @{Character = ' '; ForegroundColor = $rawui.ForegroundColor; BackgroundColor =
                $rawui.BackgroundColor})
                # .Link
                # https://go.microsoft.com/fwlink/?LinkID=2096480
                # .ExternalHelp System.Management.Automation.dll-help.xml

ParameterSets : {@{Name=__AllParameterSets; IsDefault=False;
                Parameters=System.Management.Automation.PSObject[]}}
```

**Comment by iSazonov** [comment]
The cleaning appears to be working correctly. I can only assume that after clearing, a buffer is output to the console (this is not a console buffer, but some other buffer) that contains the first line of the previous output although it should be empty, then the prompt is displayed. 

~~For normal output, rather the last line might get stuck but we see first line. So my guess is that the problem is in the table output code where we delay to collect multiple rows to define the column widths.(Related discussion and link to code https://github.com/PowerShell/PowerShell/issues/4594#issuecomment-565709392 .)~~

@brunovieira97 Can you repro with `ls | ft`? If yes, please try `ls | ft -AutoSize:$false` and share results.

**Comment by brunovieira97** [comment]
Yes, I could reproduce using `ls | ft` as well as `ls | ft -AutoSize:$false`. Didn't post any GIFs as they'd be the same as the previous ones. If you need any further tests, or even schedule a synchronous talk on this (so you can test in real time or something), I'm all in.

More than fixing my situation, I'm focused on giving everything you PowerShell guys need for finding this nasty bug

**Comment by iSazonov** [comment]
Many thanks! I see my guess was wrong and a root of the issue in another place.

The fastest way to find the problem would be using debugging. Perhaps @daxian-dbw could attach to your session and help but you need to setup PowerShell dev environment:
1. Install latest preview of Visual Studio 2019 Community Edition (select .Net features in the installer)
2. Install latest Visual Code with C# extension
3. Install Git (and GitHub Desktop if you want)
4. Fork https://github.com/PowerShell/PowerShell/ repository and make local copy
5. Try to build pwsh (see instructions in PowerShell repo)
    5.1 Run pwsh
    5.2 cd to local PowerShell fork folder
    5.3 ipmo Build.ps1
    5.4 Start-PSBootstrap
    5.5 Start-PSBuild
6.  Try debug. If you don't want to learn PowerShell sources - wait @daxian-dbw (today I haven't ideas where we could catch the issue.)
----

Also you could do two more experiments:
1. Remember size of your windows and try to change it. Can you reproduce the problem?
2. In original sized Windows run `$a = ls | ft | Out-String` and use `$a` instead of `ls` in your experiment. 
(Perhaps @mklement0 has ideas how we could catch the issue in best way.)

**Comment by brunovieira97** [comment]
Sorry for taking so much time to respond! I had no time to set up a dev environment for PowerShell, so I took the 2 experiments you recommended:

1. I did increment a line in vertical size, which meant the first line was a different one on `ls` output. And yes, the problem still happened, this time with the newer first line.
2. Still happens when getting the text from a variable as well. Again, using `Out-String` adds an empty trailing line on the content, meaning a different line is the first visible on my console. Based on this, a different content is displayed on this leftover line before my prompt.

And I discovered a behavior that might mean something: when the bug occurs, whenever I type anything the console pulls the content up (or the scroll bar down), trying to hide the buggy line. Maybe it's related? Here a GIF I just recorded on this:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/19749621/111783852-6d4bf380-8899-11eb-9c6e-2f36414e0d88.gif)

**Comment by iSazonov** [comment]
> And I discovered a behavior that might mean something: when the bug occurs, whenever I type anything the console pulls the content up (or the scroll bar down), trying to hide the buggy line. Maybe it's related?

if scrolling occurs, it will continue until cleaning is performed by Clear-Host. It is expected behavior.

To continue experiments:
1. Please write the output to a file
` ls | ft | Out-File <testFileName>`

Open the file in Notepad and copy-paste to PowerShell console. Do you see the bug? If yes, please attach the file to your next post.

2. Try `ls` in other folders. Do you see the bug?

**Comment by brunovieira97** [comment]
Continuing experiments:

1. I couldn't reproduce this writing to a file. I guess that's due to the bug being related do running `Clear-Host` and not having anything related to `Get-ChildItem`, since it won't show any strange behavior before I clear the console. Anyway, `Clear-Host` writes nothing to the file, and `Get-ChildItem` writes as expected, a list of files without any bugs.
2. I could reproduce the bug on other folders as well.

**Comment by iSazonov** [comment]
As for 1. please confirm you copy the content from the file and paste to console (check to options - Ctrl-V and mouse right click) - do you see the scrolling?

As for 2. please check with other cmdlets, ex. Get-Content an text file (large enough to fill the console over)  - do you see the scrolling?

Please share a output of ` Get-Command prompt | fl`

I want to understand whether the issue related to pipeline output, specific cmdlet output, specific format (format-table, format-list and so on) output or just a text output (like a paste).

**Comment by brunovieira97** [comment]
So, I guess I just answered both items with a single mistake of mine haha. I'm almost sleeping in front of my PC and I accidentally pasted the file content on the console (meaning it would try to parse the lines as PS commands). Anyway, by that a whole lot of error output came out, cause it was trying to run each line as a program, etc.

As it scrolled the window, I ran `clear` and confirmed: it's not related exclusively to `Get-ChildItem`, but to anything that prints to the screen.

You can see below a print of a random error output on the console after `Clear-Host` and the bug occurs:

![image](https://user-images.githubusercontent.com/19749621/111861549-ef85f780-892d-11eb-8dde-35e33d771f8f.png)

**Comment by brunovieira97** [comment]
As for the `Get-Command prompt | fl`, here's it's output:

```powershell
Name        : prompt
CommandType : Function
Definition  :
                  #store if the last command was successfull
                  $lastCommandSuccess = $?
                  #store the last exit code for restore
                  $realLASTEXITCODE = $global:LASTEXITCODE
                  $errorCode = 0
                  Set-PoshContext
                  if ($lastCommandSuccess -eq $false) {
                      #native app exit code
                      if ($realLASTEXITCODE -is [int] -and $realLASTEXITCODE -gt 0) {
                          $errorCode = $realLASTEXITCODE
                      }
                      else {
                          $errorCode = 1
                      }
                  }

                  $executionTime = -1
                  $history = Get-History -ErrorAction Ignore -Count 1
                  if ($null -ne $history -and $null -ne $history.EndExecutionTime -and $null -ne
              $history.StartExecutionTime) {
                      $executionTime = ($history.EndExecutionTime -
              $history.StartExecutionTime).TotalMilliseconds
                  }
                  # Save current encoding and swap for UTF8
                  $originalOutputEncoding = [Console]::OutputEncoding
                  [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
                  $omp =
              "C:/Users/bruno/Documents/PowerShell/Modules/oh-my-posh/3.106.2/bin/posh-windows-amd64.exe"
                  $config = $global:PoshSettings.Theme
                  $cleanPWD = $PWD.ProviderPath.TrimEnd("\")
                  $cleanPSWD = $PWD.ToString().TrimEnd("\")
                  $standardOut = @(&$omp --error="$errorCode" --pwd="$cleanPWD" --pswd="$cleanPSWD"
              --execution-time="$executionTime" --config="$config" 2>&1)
                  # Restore initial encoding
                  [Console]::OutputEncoding = $originalOutputEncoding
                  # the ouput can be multiline, joining these ensures proper rendering by adding line breaks
              with `n
                  $standardOut -join "`n"
                  Set-PoshGitStatus
                  $global:LASTEXITCODE = $realLASTEXITCODE
                  #remove temp variables
                  Remove-Variable realLASTEXITCODE -Confirm:$false
                  Remove-Variable lastCommandSuccess -Confirm:$false
```

**Comment by iSazonov** [comment]
I see you customized the prompt function. Please reset it to default and check again:
```powershell
Get-Command prompt | fl

Name        : prompt
CommandType : Function
Definition  :
              "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) ";
              # .Link
              # https://go.microsoft.com/fwlink/?LinkID=225750
              # .ExternalHelp System.Management.Automation.dll-help.xml
```

**Comment by brunovieira97** [comment]
Also, I guess I just found a probably new, but also related bug. When typing a lot of text as a command, that overflows the console area causing scrolling, PowerShell will just repeat the prompt and the command typed multiple (many) times:



https://user-images.githubusercontent.com/19749621/111861894-7045f300-8930-11eb-84dc-dca41fc812ff.mp4

**Comment by brunovieira97** [comment]
> I see you customized the prompt function. Please reset it to default and check again:
> 
> ```powershell
> Get-Command prompt | fl
> 
> Name        : prompt
> CommandType : Function
> Definition  :
>               "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) ";
>               # .Link
>               # https://go.microsoft.com/fwlink/?LinkID=225750
>               # .ExternalHelp System.Management.Automation.dll-help.xml
> ```

Well, I did test this before, due to using PowerShell with -NoProfile option. That said, I just tested again and the bug still occurs, even when printing a file's content through `Get-Content` using the default prompt.

**Comment by iSazonov** [comment]
> Well, I did test this before, due to using PowerShell with -NoProfile option.

Did you check with `Get-Command prompt | fl` in the test?

**Comment by iSazonov** [comment]
I tried your prompt function but I can not reproduce the issue.

**Comment by brunovieira97** [comment]
> > Well, I did test this before, due to using PowerShell with -NoProfile option.
> 
> Did you check with `Get-Command prompt | fl` in the test?

Yes, the prompt function with -NoProfile is the expected default, and the bug's there.

Funny thing, as I was saying the bug is not exclusively related to `Get-ChildItem` before... Running `Get-Command prompt | fl` multiple times with scrolling and clearing host will present the bug as well (so will any command, but this one's kinda funny).

**Comment by brunovieira97** [comment]
I'm starting to think this is related to Windows Terminal. I could not reproduce the error using conhost, as I said before.

I guess the `Clear-Host` behavior (repainting the console area?) is having a bit of trouble on this new terminal.

I did test deleting my settings.json and starting `pwsh -NoProfile`, but the bug is still happening. So, no fault on my settings, but maybe some deep code on this conhost killer... ?

**Comment by iSazonov** [comment]
> I'm starting to think this is related to Windows Terminal.

What is version you use? Can you install latest preview from Store?

**Comment by brunovieira97** [comment]
> > I'm starting to think this is related to Windows Terminal.
> 
> What is version you use? Can you install latest preview from Store?

I use the latest stable version from the Store.

Just tested on latest preview release and the bug happens.

**Comment by iSazonov** [comment]
You could try to turn on a trace https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/trace-command?view=powershell-7.1 for WriteLine option ( or All option). And maybe a transcript too.https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-7.1 Perhaps there will be something useful.
Otherwise I run out of ideas :-)

**Comment by brunovieira97** [comment]
I tried to trace a sequence of commands, but couldn't find a way to do it. Is there a way to trace to file this sequence?

1. Get-ChildItem
2. Get-ChildItem
3. Clear-Host

Also would want to write all of this to a file, so I can send it here. Tried transcripting, and all it did was print the session's text, didn't see anything meaningful there.

Here's the trace command I tried:
```
Trace-Command -Name trace -FilePath C:\Users\bruno\Desktop\Trace.txt -Option All -Expression { Get-ChildItem; Get-ChildItem; Clear-Host }
```

All it did was print the command set regular output (the trace file was empty). Tried with -Command, tracing individual steps, but still no content on the trace file and just the regular output on the console.

**Comment by brunovieira97** [comment]
Also, I've tried setting a debug environment using VS Code and the C Sharp extension. Installed .NET 4.6.1, .NET 5.0 (which from my understanding is .NET Core 3.0's successor), and cloned the repo.

I'm receiving an insane ammount of errors on the IDE after running `.\build.ps1 -Bootstrap`. All of them are about a type (Object, Enum for example) that is defined on a non-referenced assembly. I'm not a C Sharp guy, although I am interested in debugging so I can help you guys find this bug. Anything I should do?

P.S.: I'm just opening the repo's root folder on VS Code and loading PSReadLine.sln on the C Sharp extension.

**Comment by iSazonov** [comment]
I hope @daxian-dbw suggest that is better to start debugging PowerShell or PSReadline.

**Comment by brunovieira97** [comment]
As I've stated before, I have a suspicion on Windows Terminal being guilty of this whole bug story. So if it comes to debugging WT, PowerShell or PSReadLine to discover this, again, I'm available (within my free time) to do this locally or even on a synchronous call with @daxian-dbw or any other project maintainer ;)

Since I'm more into Java than any C-something language, I'll just need some instructions on how I can better assist you with this.

**Comment by iSazonov** [comment]
> I've tested disabling PSReadLine on current session by running Remove-Module PSReadLine and everything started to work as expected.

So we can guess it is related PSReadline and we need to debug the module. I never debug PSReadline and can not advice you.

**Comment by brunovieira97** [comment]
> > I've tested disabling PSReadLine on current session by running Remove-Module PSReadLine and everything started to work as expected.
> 
> So we can guess it is related PSReadline and we need to debug the module. I never debug PSReadline and can not advice you.

Yes, but again, it only happens in Windows Terminal, not Conhost. So it's something on PSReadLine-WT's relation, maybe?

**Comment by iSazonov** [comment]
If you can reproduce this problem in this configuration only, then yes :-)

**Comment by LuanVSO** [comment]
could you try overriding the clear host command to this and see what happens?
```powershell
function clear-host{
write-host "`e[2J`e[3J`e[0;0H" -NoNewline
}
```

**Comment by brunovieira97** [comment]
> could you try overriding the clear host command to this and see what happens?
> 
> ```powershell
> function clear-host{
> write-host "`e[2J`e[3J`e[0;0H" -NoNewline
> }
> ```

Oh, it definitely works!

Edit:
Just looked at the default code for `Clear-Host`, and now I have two functions:

 * Code provided by @LuanVSO, which does not present the bug
 * Default code returned in `GetClearHostFunctionText` when platform is Windows

Since the latter is the default `Clear-Host` function, the bug does occur with it declared on my Profile as well.

Also, this is my function with the default code I'm talking about:
```powershell
function Clear-Host {
    $RawUI = $Host.UI.RawUI
    $RawUI.CursorPosition = @{X=0;Y=0}
    $RawUI.SetBufferContents(
        @{Top = -1; Bottom = -1; Right = -1; Left = -1},
        @{Character = ' '; ForegroundColor = $rawui.ForegroundColor; BackgroundColor = $rawui.BackgroundColor}
    )
}
```

**Comment by LuanVSO** [comment]
yeah, the old console API's behave Kinda weird under ConPTY (what windows terminal uses)

**Comment by brunovieira97** [comment]
So this bug is actually a combination of PSReadLine and weird behavior of the `$Host.UI.RawUI` manipulation under ConPTY?

I would never think something such as `Clear-Host` itself was the culprit, specially considering the bug doesn't happen when I remove PSReadLine from my session. Maybe it's some buffer problem that's caused by ConPTY, as @iSazonov theorized, but obviously PowerShell and Conhost/ConPTY is not my area of expertise lol

Thanks @LuanVSO for giving me a temp solution!

I see two ways for fixing this altogether: either changing the default code for `Clear-Host` so it won't behave strangely under ConPTY or really do some digging on why manipulation of `$Host` buffer will do this.

**Comment by LuanVSO** [comment]
powershell should remove/change everything that uses `system.console` (.net itself also has some work to do in this regard) on windows, Virtual terminal sequences are the new recomended way to interact with the console on windows, the conpty translation layer is a patch

**Comment by iSazonov** [comment]
I don't think a bus is in Windows API. Rather, PSRL switches a mode and there is a race condition.

/cc @DHowett for information.
