### ISSUE TITLE
Respect SupportsVirtualTerminal

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#2277]
## Environment

```none
PS version: 7.2.0-preview.3
PSReadline version: 2.2.0-beta2
os: Darwin MININT-E57SBHC.europe.corp.microsoft.com 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
PS file version: 7.2.0.0
HostName: ConsoleHost
BufferWidth: 165
BufferHeight: 42
```

On systems where `$Host.UI.SupportsVirtualTerminal` is `false` (and not Windows), PSReadLine needs to disable some feature that rely on VT as the console output makes it unreadable.

Also, output should go through the Host and not using Console directly.

**Comment by daxian-dbw** [comment]
> On systems where $Host.UI.SupportsVirtualTerminal is false (and not Windows)

Currently PSReadLine assumes VT is always supported when running on Linux and macOS. See the code snippet below. To allow PSReadLine to work on Linux without VT, an `IConsole` implementation like [`LegacyWin32Console`](https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/PlatformWindows.cs#L404) would be needed.

https://github.com/PowerShell/PSReadLine/blob/f8fb650774a0c0e9421d9389f4a6dee5b8718b07/PSReadLine/ReadLine.cs#L640-L642

> Also, output should go through the Host and not using Console directly.

PSReadLine uses `System.Console` directly all over the places, and it would be hard to change that. Why do you think the output should always go through the `Host`?

**Comment by DHowett** [comment]
PSReadline should probably not be loaded if the user’s requested a dumb terminal :)
