### ISSUE TITLE
Partially Matching input

### ISSUE THREAD

**Issue by tahir-hassan** [PowerShell/PSReadLine#228]
I am wondering if PSReadline can be changed to work a little like the PowerShell ISE in one very important regard. 

If I type

$> $userpro

In PS ISE, then it will offer me $env:USERPROFILE as an option in the completion list.  In PSReadline it only matches the _start_ of a variable name so I won't have completion.  

Is this already supported?  If so, what do I do to get partial matching.  If not, how hard is it to implement?

Thanks,
Tahir

**Comment by lzybkr** [comment]
This is a known bug, see #126
