### ISSUE TITLE
WebPack

### ISSUE THREAD

**Issue by diogo-soares** [PowerShell/PSReadLine#2289]
Exceção:
System.ArgumentException: A matriz de destino não era longa
o suficiente. Verifique destIndex e o comprimento, bem como
os limites inferiores da matriz.
   em System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 leng
PS C:\Users\Diogo\Documents\ignite-aula-reactjs\01-github-explorer> yarn webpack
yarn run v1.22.5
$ C:\Users\Diogo\Documents\ignite-aula-reactjs\01-github-explorer\node_modules\.bin\webpack
asset bundle.js 2.48 KiB [emitted] [minimized] (name: main) 1 related asset
orphan modules 95 bytes [orphan] 1 module
modules by path ./node_modules/ 8.54 KiB
  ./node_modules/react/index.js 190 bytes [built] [code generated]
  ./node_modules/react/cjs/react.production.min.js 6.3 KiB [built] [code generated]
  ./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
./src/index.jsx 55 bytes [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

webpack 5.24.4 compiled with 1 warning in 1381 ms
Done in 2.40s.

**Comment by daxian-dbw** [comment]
This is not related to PSReadLine.
