### ISSUE TITLE
I got `問題が発生しました。このバグを以下の詳細と共に報告してください。`

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#2300]
GitHub で報告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
直前 200 個のキー:
 y . o r m . e x c . D e t a c h e d I n s t a n c e E r r o r : Space I n s t a n c e Space < A p i K e y Space a t Space 0 x 2 3 9 9 0 8 f 2 b 5 0 > Space i s Space n o t Space b o u n d Space t o Space a Space S e s s i o n ; Space a t t r i b u t e Space r e f r e s h Space o p e r a t i o n Space c a n n o t Space p r o c e e d Space ( B a c k g r o u n d Space o n Space t h i s Space e r r o r Space a t : Space h t t p : / / s q l a l c h e . m e / e / 1 3 / b h k 3 ) \ n '

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの次元のバッファー サイズ未満を指定しなければなりません。
パラメーター名:top
実際の値は -14 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by iSazonov** [comment]
Dup #2298

**Comment by daxian-dbw** [comment]
@iSazonov This is not a duplicate of the #2298. The bug report URL indicates this is from a very old version of PSReadLine. Also the call stack is not from `CalculateWhereAndWhatToRender`.
