### ISSUE TITLE
PSReadline reports "command X cannot be found" when connected to remote box.

### ISSUE THREAD

**Issue by bielawb** [PowerShell/PSReadLine#231]
When using interactive psremoting session and try to run command that is present only on the remote box you would get error message, even though command is there and works just fine if you ignore error from PSReadline:

```
[remote]: PS C:\Users\myuser\Documents> Get-Command Add-DnsServerResourceRecordCName

CommandType     Name                                               ModuleName
-----------     ----                                               ----------
Function        Add-DnsServerResourceRecordCName                   DnsServer


[remote]: PS C:\Users\myuser\Documents> Add-DnsServerResourceRecordCName -ZoneName domain.com -Name nickname -HostNameAlias server.domain.com
Command 'Add-DnsServerResourceRecordCName' cannot be found.
```

Also: if you try command that exists locally but is absent on the remote end you won't get hint that commands is missing.

Not sure how difficult it would be to support this scenario and show proper feedback, but would it be possible to maybe at least turn it off when in remote session? Currently you get errors for commands that would work and you won't be warned about missing commands for commands that won't.

**Comment by JPRuskin** [comment]
The same thing happens when referencing non-local commands / scripts for Invoke-Command and similar - example:

```
PS> Invoke-Command -ComputerName RemoteComputer -Credential $creds -Authentication Credssp -ScriptBlock {C:\Apps\test-script.ps1}
Command 'C:\Apps\test-script.ps1' cannot be found.
```

The script exists on the remote machine, but obviously won't be found by PSReadline locally.

**Comment by lansalot** [comment]
Can't believe this is still an issue.. +1 to get this fixed.

Surely a way to escape the confines of psreadline wouldn't be impossible?

**Comment by lzybkr** [comment]
This is not an issue unless you're still using a very old version of PSReadLine or you've customized your key bindings - the default key bindings do not validate on `Enter`.

Note that this is an unpaid side project for me - so I and the rest of the community greatly appreciate contributions and bug fixes.

**Comment by daxian-dbw** [comment]
I cannot repro this issue with the latest PSReadLine. Please try out 2.0.0-rc1 from PowerShell Gallery.
