### ISSUE TITLE
System.IO.IOException on Windows 10

### ISSUE THREAD

**Issue by samlieshout** [PowerShell/PSReadLine#232]
Pressing windows key + pageup on a maximized Powershell window will throw a System.IO.IOException. 

Powershell used to crash as a result, however, after running `powershell -noprofile -command "Install-Module -Force PSReadline"` as suggested in other issues, now the error is still thrown but Powershell does not at least crash :)

Screenshot below
![bug](https://cloud.githubusercontent.com/assets/590454/7490730/4a2485bc-f3e3-11e4-8068-7ca1bf9e8305.PNG)

**Comment by samlieshout** [comment]
Just to aid in repro steps make sure that the legacy console is not being used (you can see this properties menu if you right click the title bar)

**Comment by lzybkr** [comment]
This is a bug in Windows 10 (conhost).  I can imagine some hacks to work around this bug, but I think I'll just wait for the fix to conhost.

The workaround is to not use full screen mode.
