### ISSUE TITLE
Is it possible to access internal PSReadline functionality?  Specificially "Paste"?

### ISSUE THREAD

**Issue by andrewducker** [PowerShell/PSReadLine#233]
I want to do something like:
_Get-Content (Get-PSReadlineOption).HistorySavePath | out-gridview -passthru | Paste-AtCommandLine_

to give me my complete history in a big list, and then stick it into the console window.

I can do all of the bit up to the end - and then stick it in the clipboard instead, but there doesn't seem to be a way of telling PSReadLine that I want this text to be the next command line.

Is this possible?

Thanks!

**Comment by nightroman** [comment]
@andrewducker I like your idea, thank you. I implemented it in this way. In my profile I added binding to `F7` (like history in CMD):

``` powershell
Set-PSReadlineKeyHandler -Key F7 -BriefDescription History -LongDescription 'Show history' -ScriptBlock {
    $r = [System.Collections.ArrayList](Get-Content (Get-PSReadlineOption).HistorySavePath)
    $r.Reverse()
    $r = $r | Out-GridView -PassThru
    if (!$r) {return}
    [PSConsoleUtilities.PSConsoleReadLine]::RevertLine()
    [PSConsoleUtilities.PSConsoleReadLine]::Insert($r)
}
```

I hope you may find this useful.

**Comment by andrewducker** [comment]
Thank you!  That's exactly what I wanted, and a massive improvement over the previous F7 functionality!

**Comment by andrewducker** [comment]
Improvement - this will refine the search based on whatever is on the current console line (the buffer):

``` PowerShell
Set-PSReadlineKeyHandler -Key F7 -BriefDescription History -LongDescription 'Show history' -ScriptBlock {
    $line = $null
    $cursor = $null
    [PSConsoleUtilities.PSConsoleReadline]::GetBufferState([ref]$line, [ref]$cursor)
    if($line){
        $r = [System.Collections.ArrayList](Get-Content (Get-PSReadlineOption).HistorySavePath | sls $line)
    }
    else{
        $r = [System.Collections.ArrayList](Get-Content (Get-PSReadlineOption).HistorySavePath)
    }
    $r.Reverse()
    $r = $r | Out-GridView -PassThru
    if (!$r) {return}
    [PSConsoleUtilities.PSConsoleReadLine]::RevertLine()
    [PSConsoleUtilities.PSConsoleReadLine]::Insert($r)
}
```

**Comment by nightroman** [comment]
Yes, now it is even better. I used this as well and also added `Get-Unique` in order to remove adjacent duplicates (a rare case when `Get-Unique` is actually useful). My version so far (just the scriptblock without `Set-PSReadlineKeyHandler`):

``` powershell
$history = [System.Collections.ArrayList]([System.IO.File]::ReadAllLines((Get-PSReadlineOption).HistorySavePath))
$history.Reverse()

$line = $null
[PSConsoleUtilities.PSConsoleReadline]::GetBufferState([ref]$line, [ref]$null)
if ($line) {
    $history = $history -match [regex]::Escape($line)
}

$command = $history | Get-Unique | Out-GridView -Title "History $line" -PassThru
if ($command) {
    [PSConsoleUtilities.PSConsoleReadLine]::RevertLine()
    [PSConsoleUtilities.PSConsoleReadLine]::Insert(($command -join '; '))
}
```

**Comment by lzybkr** [comment]
Very cool - this should go in SamplePSReadlineProfile.ps1 - feel free to submit a pull request.

**Comment by KirkMunro** [comment]
I don't have the latest PSReadLine module (1.0.0.12 on my system right now I think), but this had some issues with commands that span multiple lines in the tests that I ran.  There were also some challenges with how it
handles lines containing backticks.  But that may be due to the version of PSReadLine I'm working with -- I simply don't have time to check right now.  Just wanted to share in case there was an issue with this for the
latest version.

**Comment by lzybkr** [comment]
Hmm, yeah - there is some minimal processing done on the file history file for multiple lines.  Maybe I should just add a api to get the history.

**Comment by andrewducker** [comment]
Pull request created!
https://github.com/lzybkr/PSReadLine/pull/235

**Comment by nightroman** [comment]
I have a solution which handles multiple lines. It is being tested. When it is done I will propose a PR.

**Comment by nightroman** [comment]
On the other hand, if the API for getting history is expected relatively soon then this solution is somewhat a hack. @lzybkr please let me know if such a hack is still fine for now.

**Comment by nightroman** [comment]
@lzybkr Any remarks? Is a hacky PR which handles multiple lines needed?

**Comment by lzybkr** [comment]
It's just a sample, so if you implemented, sure, I'll take it, and when I add a proper api, I'll update the sample.

**Comment by nightroman** [comment]
Here it is, #255

**Comment by muzzar78** [comment]
This is awesome. Any ideas on how to provide similar functionality in PS Core which is missing out-gridview?

**Comment by lzybkr** [comment]
@muzzar78 - @SeeminglyScience hinted that he's working on something that uses [fzf](https://github.com/junegunn/fzf).

**Comment by SeeminglyScience** [comment]
You know, I hadn't considered leveraging `fzf`...

That demo was using [my own implementation](https://github.com/SeeminglyScience/EditorServicesCommandSuite/blob/8031bbe652b174bf57b447352df9afd657e1fab1/src/EditorServicesCommandSuite.PSReadLine/SelectItemMenu.cs#L16).  I'm writing that mainly for use in EditorServicesCommandSuite, but if there is interest I could make it a separate project or contribute it to PSRL.

Without any changes it does a decent job at searching history:

![psrl-history-demo](https://user-images.githubusercontent.com/24977523/46583795-0409fa00-ca2a-11e8-9b2d-5cc886a56282.gif)

**Comment by SeeminglyScience** [comment]
Actually `fzf` already does this really well.  If you install it and want a similar history search option, put this in your profile:

```powershell
Set-PSReadLineKeyHandler -Chord 'F1' -ScriptBlock {
    $history = [System.Linq.Enumerable]::Reverse(
        [System.Linq.Enumerable]::Distinct(
            [string[]]([Microsoft.PowerShell.PSConsoleReadLine]::GetHistoryItems().CommandLine)))

    # Enter alternate buffer for history search.
    $Host.UI.Write("$([char]27)[?1049h")
    try {
        $command = $history | fzf --header="PSReadLine History Search"
    } finally {
        # Leave alternate buffer to return to PSReadLine prompt.
        $Host.UI.Write("$([char]27)[?1049l")
    }

    if ($command) {
        [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
        [Microsoft.PowerShell.PSConsoleReadLine]::Insert(($command -join '; '))
    }
}
```

**Comment by markusamshove** [comment]
I've also tried my luck to combine PSReadLine with fzf, but I get strange behavior after exiting fzf:

![6JO7JTp5UJ](https://user-images.githubusercontent.com/2401875/62930003-d9ac6a00-bdbb-11e9-9531-0b36bb6e70dd.gif)

Is there a way to preserve the previous state of the console, or atleast clear the console and get a prompt + the inserted command?

I've tried @SeeminglyScience approach with the buffer, but that doesn't work, as it doesn't even show fzf correctly (notice the top right corner):

![DmJypBfi7O](https://user-images.githubusercontent.com/2401875/62930356-8c7cc800-bdbc-11e9-995a-79652e34720a.gif)

**Comment by tig** [comment]
I found this issue while looking for something else, but figured I'd post this new info.

You can now use `out-consolegridview`  to get great "F7" behavior w/in the console. See:

https://gist.github.com/tig/cbbeab7f53efd73e329afd6d4b838191

**Comment by daxian-dbw** [comment]
The API `PSConsoleReadLine.GetHistoryItems()` was already added. So I assume this issue can be closed now.

```
PS:2> [Microsoft.PowerShell.PSConsoleReadLine]::GetHistoryItems

OverloadDefinitions
-------------------
static Microsoft.PowerShell.PSConsoleReadLine+HistoryItem[] GetHistoryItems()
```
