### ISSUE TITLE
navigate entered commands using up/down keys

### ISSUE THREAD

**Issue by vigyanhoon** [PowerShell/PSReadLine#2333]
Hi,

I want to navigate various commands that I entered previously starting with input.
Ex. adb will return adb connect, if I press up again it will give adb devices depending upon what adb commands I entered.

I can make it work if I run following commands in a tab
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward

But how do I make sure it becomes available to all tabs opened. I don't want to enter this manually on every tab opened on windows terminal.

**Comment by daxian-dbw** [comment]
Put the `Set-PSReadLineKeyHandler` code in your profile, and that will make the settings configured properly for all your sessions.
Run `$PROFILE` to find your profile path, and see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1 for more information about profile in powershell.
