### ISSUE TITLE
Cannot convert value "HistoryAndPlugin", A parameter cannot be found that matches parameter name 'PredictionViewStyle'

### ISSUE THREAD

**Issue by FallenHoot** [PowerShell/PSReadLine#2352]
I couldn't find any duplicates, but I am sure this might be. 

The default PSReadLine that comes with PowerShell Core 7.1 can't be updated, thus I start by removing this and installing it fresh again. After that, I simply run the ``` Set-PSReadLineOption ```. I provided a function to assist with this. 

I tried to just install the Prerelease module without removing the preinstalled one, but it kept telling me I wasn't an Administrator and I showed it who was boss. 

## Environment
PS version: 7.2.0-preview.4
PSReadline version: 2.1.0
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.2.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30

```PowerShell
❯ $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      0      preview.4

```
```PowerShell
❯ Get-InstalledModule -Name "PSReadLine"

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.2.0-beta2          PSReadLine                          PSGallery            Great command line editing in the PowerS…


```

```PowerShell
([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
```
![image](https://user-images.githubusercontent.com/19664186/114161106-fa79e980-9927-11eb-81fe-680cd7f4580c.png)

## Cleanup & Install
```PowerShell
function PowerShell_Intellisense {
$isPSReadlineInstalled = Get-InstalledModule -Name "PSReadline"
    if (!($isPSReadlineInstalled -ne $null )) {
        Write-Host "`Uninstalling preinstalled version of PSReadline..." -ForegroundColor Yellow
        $module = "$HOME\Documents\PowerShell\Modules\PSReadline"
        takeown /F $module /A /R
        icacls $module /reset
        icacls $module /grant "*S-1-5-32-544:F" /inheritance:d /T
        Remove-Item -Path $module -Recurse -Force -Confirm:$false
        Write-Host "`nDownloading latest preview of PSReadline..." -ForegroundColor Yellow
        Install-Module -Name PSReadline -Allowprerelease -Force
        Set-PSReadLineOption -PredictionSource HistoryAndPlugin
        Set-PSReadLineOption -PredictionViewStyle ListView
        Set-PSReadLineOption -Colors @{ InlinePrediction = "$([char]0x1b)[36;7;238m"}
}
    else {
        Write-Host "`nPSReadline is already installed. Will update if needed" -ForegroundColor Green
        Update-Module -Name PSReadline -Allowprerelease
    }

}
```
## Steps to reproduce
```PowerShell
❯ Set-PSReadLineOption -PredictionSource HistoryAndPlugin
Set-PSReadLineOption: Cannot bind parameter 'PredictionSource'. Cannot convert value "HistoryAndPlugin" to type "Microsoft.PowerShell.PredictionSource". Error: "Unable to match the identifier name HistoryAndPlugin to a valid enumerator name. Specify one of the following enumerator names and try again:
None, History"
```
![image](https://user-images.githubusercontent.com/19664186/114160724-86d7dc80-9927-11eb-9f3f-7aa02bda65d1.png)

```PowerShell
❯ Set-PSReadLineOption -PredictionViewStyle ListView
Set-PSReadLineOption: A parameter cannot be found that matches parameter name 'PredictionViewStyle'.
```
![image](https://user-images.githubusercontent.com/19664186/114160671-74f63980-9927-11eb-8cdd-4250db276103.png)

```PowerShell
❯ Enable-AzPredictor -AllSession
Enable-AzPredictor: Cannot bind parameter 'PredictionSource'. Cannot convert value "HistoryAndPlugin" to type "Microsoft.PowerShell.PredictionSource". Error: "Unable to match the identifier name HistoryAndPlugin to a valid enumerator name. Specify one of the following enumerator names and try again:
None, History"
```
![image](https://user-images.githubusercontent.com/19664186/114160612-6871e100-9927-11eb-93dd-d9deb98f7281.png)

## Expected behavior

Should work?
![image](https://user-images.githubusercontent.com/19664186/114158778-6149d380-9925-11eb-8b53-855fc5bd407f.png)

**Comment by daxian-dbw** [comment]
@FallenHoot The error message indicates that you were using the 2.1.0 version of PSReadLine, which doesn't support the `-PredictionViewStyle` parameter and doesn't allow the value `HistoryAndPlugin` for the parameter `-PredictionSource`.

Note that `Get-InstalledModule -Name "PSReadLine"` only shows if a particular version of PSReadLine module was installed by `Install-Module`, but that doesn't necessarily mean it's the version of PSReadLine that is currently loaded in your powershell session. In your case, the currently loaded PSReadLine is 2.1.0.

To find out the version of the loaded PSReadLine, just run `Get-Module PSReadLine`.

**Comment by FallenHoot** [comment]
I just ran the following:

![image](https://user-images.githubusercontent.com/19664186/117363029-4f276a80-aebc-11eb-87f8-354e02bc67b6.png)

I did a few restarts and came back to this a few days later. It now works as it should.
