### ISSUE TITLE
Unable to Install or Upgrade PSReadLine 2.2.0 beta 2 on Windows 10 for Powershell 7

### ISSUE THREAD

**Issue by kashif-khan** [PowerShell/PSReadLine#2368]
## Environment

```none
PS version: 7.1.3
PSReadline version: 2.2.0-beta1
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.3.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 156
BufferHeight: 42
```

## Exception report

```
Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Administrator rights are required to install or update. Log on to the computer with an account that has Administrator rights, and then try
     | again, or install by adding "-Scope CurrentUser" to your command. You can also try running the Windows PowerShell session with elevated
     | rights (Run as Administrator).
```

## Steps to reproduce

Run with administrator privileges any one of the following commands:

- Update-Module -Name PSReadLine -AllowPrerelease -Force
- Install-Module PSReadLine -AllowPrerelease -Force

Both commands produce the same result.

## Expected behavior

PSReadLine 2.2.0 beta2 to be installed on the system.

## Actual behavior

PSReadLine 2.2.0 beta2 is installed successfully.

**Comment by daxian-dbw** [comment]
Please follow the instructions in the [Upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) to upgrade PSReadLine.
