### ISSUE TITLE
FR: Avoid commands with leading spaces be saved in history

### ISSUE THREAD

**Issue by bohrshaw** [PowerShell/PSReadLine#237]

**Comment by lzybkr** [comment]
You can do this today with the following:

```
Set-PSReadlineOption -AddToHistoryHandler { $args[0] -notmatch "^\s" }
```

This way is much more flexible - you can customize this handler more extensively, e.g. you could not save commands where the length is < 3.

**Comment by bohrshaw** [comment]
Thanks! This could also be helpful to others.
