### ISSUE TITLE
If there is only one possible completion and it's folder, second tab should do something

### ISSUE THREAD

**Issue by vors** [PowerShell/PSReadLine#238]
Consider this case with PSReadLine

```
> ls C:\Wind<TAB>
# auto-complete to
> ls C:\Windows\<TAB>
# nothing happens
> ls C:\Windows\<TAB>
# nothing happens
> ls C:\Windows\<TAB>
```

It's quite frustrating (because of the trailing `\`) and it make sense to not circle thru the only option, but to start completion for the next level.

**Comment by gwojan** [comment]
PowerShell without `PSReadLine` behaves similarly -- it just doesn't append the `\`.

While using PSReadLine I've gotten in the habit of hitting `Ctrl+Tab, Tab` or `\, Tab`. Once tab completion starts cycling again the second `\` is removed. Does that make sense? It's still an extra keystroke but it works. :wink:

**Comment by vors** [comment]
🎉
