### ISSUE TITLE
Terminal problem when path name length is too long, or the terminal window is too small

### ISSUE THREAD

**Issue by Sirmyself** [PowerShell/PSReadLine#2388]
when my window is using half my screen, the terminal gets smaller. when the terminal is smaller, I can't type the command "dotnet" because the terminal messes up after I type the "o".  Could also be linked to the length of my folder, but basically, I start typing on the row under the path and then I can't type the whole thing. My guess is that the index of the cursor may eventually point to an invalid index and crashes the command line. This is the trace I get after the error.

```
System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   à Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   à Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   à Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   à Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
