### ISSUE TITLE
[Feature Suggestion]: Allow search in alternate screen buffer

### ISSUE THREAD

**Issue by Glober777** [PowerShell/PSReadLine#2406]
## Description of the new feature/enhancement

It would be great if the alternate screen buffer would have an extra capability to search for strings in the provided output (i.e. similar to string search in `less` tool). 

## Proposed technical implementation details (optional)
It would come handy in the following scenarios:
- Start typing the name of the cmdlet (i.e. `Get-`) and press `F1` to see the list of available cmdlets. If the list is large, the user could invoke a search operation and search for words that should be met in the cmdlet and\or module name, navigating forward or back through the findings
-  Search for keywords in the large cmdlet help articles

**Comment by daxian-dbw** [comment]
@adityapatwardhan Can you please comment? Maybe transfer this issue to https://github.com/PowerShell/Pager?

**Comment by adityapatwardhan** [comment]
@Glober777 Thank you for the suggestion. We have something similar captured as part of the roadmap for the next version of Pager here: https://github.com/PowerShell/Pager/issues/7. It would be great if you could contribute or add comments to the issue.

What you have mentioned is two part, one for searching through multiple cmdlets, which can be achieved by either tabbing or `Ctlr+Space` to see the menu of items that match. Any improvements there would be part of this repository. 

The other part of searching in the help content would be an improvement in the Pager repository.

**Comment by daxian-dbw** [comment]
> Feature | KeyBinding
>1. Search forward | /
>2. Search backward | \
>3. Next forward match | f
>4. Next backward match | b

@Glober777 It looks the searching functionality is already covered in the road map. Feel free to comment there.
As for the other suggestion, we don't plan to overload `F1` for tab completion purpose.

**Comment by Glober777** [comment]
Oh, nice. I didn't realize that it was pulling in an external tool. Thanks for the reference.
