### ISSUE TITLE
What is the status of PSReadLine on GitHub?

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#242]
@Izybkr, Now that PSReadLine is shipping with builds of Windows 10/PowerShell 5 what's the official word for this project?

**Comment by lzybkr** [comment]
We'll continue using GitHub to track issues, build new features, etc. We plan to release versions from GitHub that are newer than what's in Windows, and the new work from GitHub will be made available in future versions of Windows.

New work and pull requests should move to the PowerShell team fork: https://github.com/PowerShell/PSReadLine

We will require a signature from any non-Microsoft employee before accepting pull requests (you'll only need to do this once.)  The PowerShell team fork has automation to make that process basically painless.

I'll regularly pull from the PowerShell team fork to this project, for example, I just pulled to add support for CJK languages.

**Comment by gwojan** [comment]
@lzybkr, Thank you. I don't see an issues tab on the PowerShell fork. Should I continue reporting issues here?

**Comment by lzybkr** [comment]
Uh, sorry for not replying before, but yeah, issues need to be reported against the primary repo, not against a fork.
