### ISSUE TITLE
Strange scrolling behaviour

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PSReadLine#2450]
### System Details

System Details Output
```
### VSCode version: 1.56.0 cfa2e218100323074ac1948c885448fdf4de2a7f x64

### VSCode extensions:
MS-CEINTL.vscode-language-pack-de@1.56.1
ms-vscode.powershell@2021.2.2


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

I am experiencing a problem with the PowerShell terminal scrolling behaviour when switching from side panel view to full panel view:

![Strange scrolling behaviour](https://user-images.githubusercontent.com/9283914/117493211-f8309c80-af72-11eb-8db7-365aae3850e9.gif)

/ref: [#3344](/PowerShell/vscode-powershell/issues/3344)

#### Expected Behaviour

When I hit the `ARROW UP` key, I would expect to see different versions of my execution history, but I don't expect a scrolling behaviour.

#### Actual Behaviour

When I hit the `ARROW UP` key after having switched the PowerShell terminal from side panel to full panel, scrolling is performed that's mimicking the previous side panel layout.

**Comment by daxian-dbw** [comment]
The scrolling behavior you observed is not controlled by PSReadLine, but likely controlled by the VSCode terminal. You get the same scrolling behavior with CMD -- pressing any key will cause the scrolling:

![Animation](https://user-images.githubusercontent.com/127450/120682342-35dcf400-c451-11eb-9d24-e9bc8bcafd2d.gif)

Maybe you should open an issue in the [VSCode repo](https://github.com/microsoft/vscode).

**Comment by SetTrend** [comment]
Thank you, @daxian-dbw. Following your suggestion I opened a corresponding sibling issue [here](/microsoft/vscode/issues/125434).
