### ISSUE TITLE
"Set-PSReadlineOption -EditMode vi" breaks Ctrl+r / bck-i-search

### ISSUE THREAD

**Issue by davetapley** [PowerShell/PSReadLine#2453]
## Environment

```none
PS version: 5.1.19041.906
PSReadline version: 2.0.1
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000
```

## Exception report

N/A

## Steps to reproduce

1. Run `Set-PSReadlineOption -EditMode vi`
2. Press <kbd>Ctrl</kbd> + <kbd>r</kbd> 
3. Enter string occurring in previously entered command
4. Press <kbd>Ctrl</kbd> + <kbd>r</kbd> a second time

## Expected behavior

`bck-i-search:` appears and subsequent <kbd>Ctrl</kbd> + <kbd>r</kbd> scroll through earlier matches.

## Actual behavior

`find:` appears and subsequent <kbd>Ctrl</kbd> + <kbd>r</kbd> do nothing

Example: 

https://user-images.githubusercontent.com/48232/118168605-e3be2b00-b3dc-11eb-909b-f457e0e5e08e.mp4

**Comment by davetapley** [comment]
Difference is explained by:

https://github.com/PowerShell/PSReadLine/blob/dc38b451bee4bdf07f7200026be02516807faa09/PSReadLine/KeyBindings.cs#L208-L209

vs

https://github.com/PowerShell/PSReadLine/blob/dc38b451bee4bdf07f7200026be02516807faa09/PSReadLine/KeyBindings.vi.cs#L89-L90

---

Implemented by:

https://github.com/PowerShell/PSReadLine/blob/dc38b451bee4bdf07f7200026be02516807faa09/PSReadLine/History.cs#L970-L973

vs

https://github.com/PowerShell/PSReadLine/blob/dc38b451bee4bdf07f7200026be02516807faa09/PSReadLine/ReadLine.vi.cs#L934-L941

---

Skimming the history it seems like it's been this way for a long time, but I honesty can't think of a use case where `ViSearchHistoryBackward` would be preferable to `ReverseSearchHistory`?

In any case it's already also bound to <kbd>/</kbd> in command mode:
https://github.com/PowerShell/PSReadLine/blob/dc38b451bee4bdf07f7200026be02516807faa09/PSReadLine/KeyBindings.vi.cs#L204

**Comment by daxian-dbw** [comment]
@lzybkr The code change history shows that the interactive history search feature (`fwd-i-search:` and `bck-i-search:`) was add in January 2014, while the `ViStartSearchBackward` (`find:`) was added in March 2014, 2 months after the interactive history search feature was enabled. Any reason why the VI mode choose to use a different backward history searching UX? Is it OK to use the same interactive search function `ReverseSearchHistory/ForwardSearchHistory` for the VI mode? (the same interactive search is used in both Windows mode and Emacs mode).

**Comment by lzybkr** [comment]
The guiding principle at the time was to emulate GNU readline - with few intentional exceptions.

So when this work was implemented, I think it did emulate vi mode in bash.

I don't think there's been any real effort to track changes to GNU readline, but if today vi mode in bash works just like emacs mode, maybe it does make sense to change PSReadLine too.

**Comment by daxian-dbw** [comment]
I just tried the bash vi mode (`set -o vi`), and `ctrl+r` works just like the emacs mode (`(reverse-i-search)` appears). I guess it's fine then to replace the `find:` in PowerShell with the same interactive history searching as in Windows and Emacs modes. (Especially, the existing `ViSearchHistoryBackward` and `SearchForward` functionalities are already available via the `/` and `?` shortcuts)
