### ISSUE TITLE
error en cargar docker 

### ISSUE THREAD

**Issue by apaican** [PowerShell/PSReadLine#2454]
Últimas 136 claves:
 d o c k e r Space v e r s i o n Enter
 d o c k e r Space h e l p Enter
 c l e a r Enter
 d o c k e r Space v e r s i o n Enter
 Ctrl+v Enter
 UpArrow Enter
 n e t s t a t Space - a n Enter
 UpArrow UpArrow DownArrow DownArrow DownArrow d o c k e r Space v e r s i o n Enter
 d o c k e r Space r u n Space h e l l o - r Backspace w o r l d Enter
 d o c k e r Space i n f o Enter
 ` LeftArrow LeftArrow RightArrow UpArrow d o c k e r Space p s Enter

Excepción:
System.IO.IOException: El parámetro no es correcto.

   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
Thanks for reporting the issue, but it lacks important environment data (versions of PSReadLine and PowerShell, etc.) for investigation.
Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
