### ISSUE TITLE
Copy/paste do not work correctly

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PSReadLine#246]
Hi,
maybe this bug is similar to this one : https://github.com/lzybkr/PSReadLine/issues/77
# PS V4 Seven x64 Fr
# ModuleVersion = '1.0.0.13' or '1.0.0.12'

Open this file with Notepad (Encoding ANSI):
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1

-Select All
-Copy

Open a Powershell console
 Cd C:\temp

-Paste
![copypasteerror1](https://cloud.githubusercontent.com/assets/4894452/8208381/a7ff79f4-1507-11e5-92af-e36b32d97a6e.png)
![copypasteerror2](https://cloud.githubusercontent.com/assets/4894452/8208391/b0e5269a-1507-11e5-8dfd-59f60b2ebbbe.png)

The files  ([a ,[a].txt,...) exist in the current path.

Open this file with Notepad (Encoding UTF8):
Http://laurent-dardenne.developpez.com/Bugs/PsReadline/testPSreadline.ps1

-Select All
-Copy
![copypasteerror3](https://cloud.githubusercontent.com/assets/4894452/8208434/edf3373e-1507-11e5-9980-5fa069828023.png)

**Comment by lzybkr** [comment]
Yeah, this is the same as #77.
