### ISSUE TITLE
Starting Python

### ISSUE THREAD

**Issue by luke982** [PowerShell/PSReadLine#2477]
I am starting to learn coding and i started with Python and the video which i am watching and learning said to write print("hello world"). After that, i safed the file and i clicked the button: run python file in terminal. And if the terminal says the phrase: hello world, then it is done. But when i did it, it says that there is a problem, and it says to report the bug with these messages: System.ArgumenOutOfRangeException

**Comment by daxian-dbw** [comment]
Thanks for reporting. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
