### ISSUE TITLE
Error when screen width is small

### ISSUE THREAD

**Issue by xumarcus** [PowerShell/PSReadLine#2486]
![Capture](https://user-images.githubusercontent.com/51620147/119314247-1ef70e80-bca7-11eb-9cdf-649b92d8d46d.PNG) from VSCode

**Comment by daxian-dbw** [comment]
This was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
