### ISSUE TITLE
Oops, something went wrong: PowerShell Barfed on Tab Completion.

### ISSUE THREAD

**Issue by joslinpr** [PowerShell/PSReadLine#2489]
I am not able to reproduce this error.  I started PowerShell and ran 
`new-item $profile -itemtype file -force` 
to create a profile.
I edited the profile (attached).
I started PowerShell in Windows Terminal Preview Version: 1.8.1032.0.

Error:
`Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 35 Keys:
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow c d Space O Tab \ Space Tab Backspace Backspace Tab Backspace Backspace - Tab Backspace Backspace Backspace Space Tab Tab

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -9.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
[Microsoft.PowerShell_profile.txt](https://github.com/PowerShell/PSReadLine/files/6532780/Microsoft.PowerShell_profile.txt)

`

**Comment by joslinpr** [comment]
PS - Pretty clever to have the error message report what I was doing when I broke it.  I'm totally stealing that!

**Comment by galortega** [comment]
> PS - Pretty clever to have the error message report what I was doing when I broke it. I'm totally stealing that!

Actually it happens kinda randomly when I type certain keys in vsc

```
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 1 claves:
 "

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: left
Valor actual -1.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value) 
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

```
