### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by KnowledgePro** [PowerShell/PSReadLine#2496]
-----------------------------------------------------------------------
Last 200 Keys:
 v e Space - Space U n i v e r s i d a d Space d e Space l o s Space A n d e s / P y t h o n / r e g a e t o n . p y " Enter
 & Space C : / U s e r s / a e . w i l l s 2 2 / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 
3 9 / p y t h o n . e x e Space " c : / U s e r s / a e . w i l l s 2 2 / O n e D r i v e Space - Space U n i v e r s i d a d Space d e Space l o s Space A n d e s / P y t h o n / r e g a e t o n . p y " Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -7.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
@KnowledgePro Thanks for reporting the issue, but it lacks important environment data (version of PSReadLine, PowerShell and etc). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
