### ISSUE TITLE
Following update to Pwsh 7.2.0-preview6 with PSReadline 2.2.0-beta2 exception, console unusable

### ISSUE THREAD

**Issue by HerbM** [PowerShell/PSReadLine#2507]
Following update to Pwsh 7.2.0-preview6 with PSReadline 2.2.0-beta2 exception, console unusable

Starting with -noprofile fails also (apparently PSReadLine autoloads even without my profile which loads and configures it.

Error message and request to report this here follows:

> Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0-preview.6
OS: Microsoft Windows 10.0.21390
BufferWidth: 134
BufferHeight: 9001

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset() in Microsoft.PowerShell.PSReadLine2.dll:token 0x60004ca+0x0
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset() in Microsoft.PowerShell.PSReadLine2.dll:token 0x600049b+0x7
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics) in Microsoft.PowerShell.PSReadLine2.dll:token 0x6000101+0x118
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken) in Microsoft.PowerShell.PSReadLine2.dll:token 0x60000fa+0x60
```

## Expected behavior

pwsh 7.2.0preview6 to run profile correctly as did preview5 and preceding versions.

## What actually happens
Error shown above, console unusable.

Cannot run full report script due to errors but the version show by the exception is above.

**Comment by maxim-shlain** [comment]
@HerbM, looks like the PS team knows about the issue:
at: https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.6
they say:

PSReadLine 2.2.0-beta1 and 2.2.0-beta2 do not work with this preview of PowerShell due to breaking changes in the prediction interface. The upcoming PSReadLine 2.2.0-beta3 release will resolve this. Use PSReadLine 2.1.0 as the temporary workaround.

I've decided to downgrade the pscore to preview 5, works fine for me at the moment

**Comment by HerbM** [comment]
> @HerbM, looks like the PS team knows about the issue:
> at: https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.6
> they say:
> 
> PSReadLine 2.2.0-beta1 and 2.2.0-beta2 do not work with this preview of PowerShell due to breaking changes in the prediction interface. The upcoming PSReadLine 2.2.0-beta3 release will resolve this. Use PSReadLine 2.1.0 as the temporary workaround.
> 
> I've decided to downgrade the pscore to preview 5, works fine for me at the moment

Would have been nice for them to include a warning if "PS team knows" or some more proactive action.

I can confirm that preview5 and PSReadline 2.2.0-beta2 worked together consistently.

**Comment by HerbM** [comment]
...and I've remove Preview6 and then re-installed 7.2.0-Preview5.

Works fine again.

**Comment by HerbM** [comment]
7.2.0-preview.7 and PSReadLine 2.2.0  beta3 seems to be working on first examination.
