### ISSUE TITLE
Make chocolatey package

### ISSUE THREAD

**Issue by tigerhawkvok** [PowerShell/PSReadLine#252]
Because [choco install](https://chocolatey.org) psreadline would be pretty great!

**Comment by rkeithhill** [comment]
Two things. First PSReadline comes with WMF 5.0. Second you can install (and update) this module from the PSGallery using Install-Module PSReadline.

**Comment by rkeithhill** [comment]
With WMF 5.0 you can install Chocolatey pkgs using Install-Package e.g. Install-Package dotPeek.

**Comment by lzybkr** [comment]
See #58 for my comments.
