### ISSUE TITLE
ArgumentOutOfRangeException in SetCursorPosition

### ISSUE THREAD

**Issue by awfulcooking** [PowerShell/PSReadLine#2523]
## Environment

```none
PS version: 5.1.19041.906
PSReadline version: 2.0.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 188
BufferHeight: 47
```

## Exception report

```stacktrace
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

![image](https://user-images.githubusercontent.com/62954746/120226748-b3311a80-c23f-11eb-9726-eac529574c8a.png)

## Steps to reproduce

Last 200 keys show command input to convert a wav file to ogg with ffmpeg.exe.

An hour or so later, I returned to reuse the console and pressed Ctrl+l as usual to get a fresh prompt.

Instead, got this exception. Not happened before.. thousands of invocations across constantly changing DPIs, window sizes, etc.

Upgraded Windows Terminal ~last week

## Expected behavior

Pressing Ctrl+l at a command prompt should 'clear' the screen by inserting newlines, resetting the cursor position to 0,0, and re-rendering the prompt

## Actual behavior

ArgumentOutOfBoundsException in SetCursorPosition

**Comment by daxian-dbw** [comment]
This was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
