### ISSUE TITLE
 Ｉmade a mistake entering the type

### ISSUE THREAD

**Issue by MamiOgura** [PowerShell/PSReadLine#2528]
-----------------------------------------------------------------------
直前 8 個のキー:
 o u t o Backspace Backspace Backspace Backspace

例外:
System.ArgumentException: ターゲット配列の長さが足りません。destIndex、長さ、および配列の最小値を確認してください。
   場所 System.Array.Copy(Array sourceArray, Int32 sourceIndex,
Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   場所 System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
P

**Comment by daxian-dbw** [comment]
@MamiOgura Thanks for reporting the issue, but it lacks important environment data (version of PSReadLine, PowerShell and etc). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
