### ISSUE TITLE
On key hits - System.IO.IOException: The parameter is incorrect.

### ISSUE THREAD

**Issue by one-harsh** [PowerShell/PSReadLine#253]
Last 200 Keys:
 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow
LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow y Enter
 UpArrow Backspace LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Ctrl+RightArrow Ctrl+RightArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace
Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace - Tab Spacebar " " LeftArrow M i c r o s o f t . 1 2 3 4 Backspace Enter
 UpArrow UpArrow UpArrow Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace
 Enter
 UpArrow Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace p Tab Tab Spacebar " M i c r o s o f t . 1 2 3 " Enter
 Ctrl+v Enter
 Ctrl+v ) Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow LeftArrow LeftArrow LeftArrow Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace " LeftArrow RightArrow Ctrl+v Enter
 Ctrl+v Tab Enter
 UpArrow UpArrow UpArrow LeftArrow PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
Duplicate - see #232.
