### ISSUE TITLE
Enhance multiline edit mode to support Shift+Enter and Ctrl+Enter

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#256]
I love these two shortcuts from Visual Studio - Shift+Enter (move to end of current line, insert new line, cursor is at beginning of new line that is below the old line) and Ctrl+Enter (move to beginning of current line, insert new line, move cursor to beginning of new line that is above the old line). It would be great to have these in multiline edit mode.

**Comment by gwojan** [comment]
I just ran into this a couple of days ago. @srdubya, it would be nice to have `o` and `O` added to the Vi support.

**Comment by rkeithhill** [comment]
Let me make a modification to my suggestion.  Shift+Enter is needed to insert "just" a new line since Enter is reserved for accepting the line.  So how about using Ctrl+Shift+Enter to move to end of current line, insert new line, cursor is at beginning of new line that is below the old line i.e. insert new line below current line.

**Comment by srdubya** [comment]
Vi-mode now has 'o', 'O', and 'J'.  @gwojan, please give it a try and let me know if you notice anything weird.

**Comment by gwojan** [comment]
@srdubya, Awesome! Thank you! I had totally forgotten about `J`...

The only thing I've noticed so far is the cursor isn't positioned to the new open line. If, for example, I'm on line 2 of three lines of text `o` leaves me on the line below the new line and `O` leaves me on the line above the new line.

**Comment by srdubya** [comment]
OK, fixed the cursor placement problems on 'o' and 'O'.

**Comment by gwojan** [comment]
@srdubya, Looks good! Thanks again. :smile:

**Comment by rkeithhill** [comment]
This is what I put in my PSReadline_config.ps1 file (which I dot source into my profile script) to accomplish this:

``` powershell
Set-PSReadlineKeyHandler -Key Ctrl+Enter `
                            -BriefDescription InsertLineAbove `
                            -LongDescription "Creates a new line above the current line and moves the cursor there" `
                            -ScriptBlock {
    param($key, $arg)

    [string]$line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    $prevNewlineIndex = $line.LastIndexOf("`n", $cursor)
    [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition([Math]::Max(0, $prevNewlineIndex))
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert("`n")
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    if ($cursor -eq 1) {
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition(0)
    }
}

Set-PSReadlineKeyHandler -Key Ctrl+Shift+Enter `
                            -BriefDescription InsertLineBelow `
                            -LongDescription "Creates a new line below the current line and moves the cursor there" `
                            -ScriptBlock {
    param($key, $arg)

    [string]$line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    $nextNewlineIndex = $line.IndexOf("`n", $cursor)
    if ($nextNewlineIndex -ge 0) {
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($nextNewlineIndex)
    }
    else {
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($line.Length)            
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert("`n")
}
```

**Comment by daxian-dbw** [comment]
The suggested key bindings had already been implemented:
```
Shift+Enter      AddLine
Ctrl+Enter       InsertLineAbove
Shift+Ctrl+Enter InsertLineBelow
```
