### ISSUE TITLE
Unable to map Ctrl+[

### ISSUE THREAD

**Issue by flakfizer** [PowerShell/PSReadLine#2596]
I am trying to map Ctrl+[ to ViCommandMode to match Vim's default key bindings. This worked in PS 5, but is not working in PS 7.1.3.

Set-PSReadLineOption -EditMode vi
Set-PSReadLineKeyHandler -Chord Ctrl+[ -Function ViCommandMode

In PS 5, Ctrl+[ will now successfully enter ViCommandMode in PS 5. But in PS 7, "^[" appears at the command line and command mode is not entered. Get-PSReadLineKeyHandler shows that the mapping took in PS 5, and shows that it did not in PS 7. Seeing the same behavior in the default PS 7 terminal and in Windows Terminal.

**Comment by daxian-dbw** [comment]
Close as a dup of #906
