### ISSUE TITLE
upgrading from 2.2.0-beta2 > beta3 broke Powershell debugger in vscode

### ISSUE THREAD

**Issue by bchap1n** [PowerShell/PSReadLine#2616]
## Environment

PS version: 7.1.3
PSReadline version: 2.2.0-beta3
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.3.0
HostName: Visual Studio Code Host
BufferWidth: 238
BufferHeight: 10

## Steps to reproduce
Upgrade to PSReadline 2.2.0-beta3 from PSReadline 2.2.0-beta2
Open new PowerShell script in VSCode, set breakpoint on first line, and launch debugger

This happens in latest vscode and vscode-insiders, Powershell/Powershell-Insiders Extension and with Powershell 7.1+ and 7.2+

## Expected behavior
debugger should pause at the breakpoint

## Actual behavior
debugger just hangs and I can either pause or stop

## notes

I tried rolling back powershell extension, and rebooting.

**Comment by WorrenB** [comment]
seems to be related to [PSReadLine 2.2.0-beta 3 breaks extension](https://github.com/PowerShell/vscode-powershell/issues/3393)
in my case I couldn't use F8 (Run Selections) either

**Comment by andyleejordan** [comment]
@bchap1n and @WorrenB Can you please downgrade your PSReadLine to the latest compatible version (i.e. the one we ship with the extension) 2.1.0?

https://github.com/PowerShell/vscode-powershell/issues/3393#issuecomment-854095942

**Comment by bchap1n** [comment]
@andschwa 2.1.0 and 2.2.0-beta2 both work ok for me. 

The problem is that I can't use Powershell Preview 7.2.* at all without PSReadline 2.2.0-beta3 and there is no work-around for that.

**Comment by andyleejordan** [comment]
The fix is going to be https://github.com/PowerShell/PowerShellEditorServices/pull/1514

**Comment by andyleejordan** [comment]
Unless, @daxian-dbw, will PowerShell Preview 7.2.x be incompatible with PSReadLine 2.1.0 at some point? Like, what's our priority to upgrade the bundled PSReadLine to 2.2.0?

**Comment by bchap1n** [comment]
@andschwa I see your question was directed at dbw but I understand that PowerShell Preview 7.2.0-preview.7 is not compatible with PSReadLine 2.1.0

**Comment by andyleejordan** [comment]
Hm, FYI @rjmholt we might have to prioritize bumping PSReadLine.

**Comment by daxian-dbw** [comment]
> will PowerShell Preview 7.2.x be incompatible with PSReadLine 2.1.0 at some point? Like, what's our priority to upgrade the bundled PSReadLine to 2.2.0?

Yes, 2.1.0 works with all 7.2 preview releases. It's safe to bundle PSES with 2.1.0 PSReadLine.

**Comment by daxian-dbw** [comment]
@rjmholt found out the root cause why 2.2.0-beta3 breaks VSCode debugging: https://github.com/PowerShell/PSReadLine/blob/ad74cef2501709d2a60a58f61d7cac32d185209f/PSReadLine/ReadLine.cs#L317-L320

The `cancellationToken` should be passed along instead of using the default token. PR is out: #2636

**Comment by ghost** [comment]
:tada: This issue was addressed in 2636, which has now been successfully released in [`v2.2.0-beta4`](https://github.com/PowerShell/PSReadLine/releases/tag/v2.2.0-beta4). :tada:
