### ISSUE TITLE
error gcc.exe: error: No such file or directory

### ISSUE THREAD

**Issue by dhthang** [PowerShell/PSReadLine#2644]
![2021-07-04 (2)](https://user-images.githubusercontent.com/57390801/124380480-f40ccb00-dce6-11eb-9afd-309019243d58.png)
when i run a file code C, i make a error as picture. Help me fix it, thank you so much.

**Comment by rkeithhill** [comment]
These errors are coming from `gcc.exe` via the `Code` terminal - not PowerShell.  Looking at the error messages, I suggest you rename your source file to remove the spaces e.g. `StoreInfoAndDisplay.c`.  Or quote the source file name that you provide to the compiler.
