### ISSUE TITLE
Bug on compiling a cpp code. showing this error -> ----------------------------------------------------------------------- Last 160 Keys:  c d Space " c : \ U s e r s \ A g r i m Space S r i v a a s t a v a \ D o c u m e n t s \ C O D E F O R C E S \ @ 9 0 0 \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space A _ D I Y _ W o o d e n _ L a d d e r . c p p Space - o Space A _ D I Y _ W o o d e n _ L a d d e r Space } Space ; Space i f Space ( $ ? ) Space { Space . \ A _ D I Y _ W o o d e n _ L a d d e r Space } Enter

### ISSUE THREAD

**Issue by dezfuture** [PowerShell/PSReadLine#2645]

**Comment by daxian-dbw** [comment]
Please follow the issue template when reporting an issue. The needed information is important for investigation. 

If you haven't, please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery. It's possible the issue you ran into was fixed. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by dezfuture** [comment]
Yeah, it was resolved, thanks!
