### ISSUE TITLE
For the prediction feature in 2.2.0, slash directions should be ignored

### ISSUE THREAD

**Issue by jethas-bennettjones** [PowerShell/PSReadLine#2647]
When using the new Prediction feature in the 2.2.0 beta, typing a backslash or a forward slash when tying a command should match against regards where the direction of the slash is ignored. This would be helpful for me as I type with a EN-GB layout in an EN-US keyboard, so a backslash (\) is a three-button combination, whereas a forward slash (/) is a single button press.
This is an edge case, certainly, but if and when this becomes sync across multiple different environments with multiple different operation systems, this could be one more stumbling block that can be alleviated.

**Comment by StevenBucher98** [comment]
@jethas-bennettjones so just so I understand correctly, if I have something in my history like `\ExampleBlah` that if you type either a `\` or a `/` this result would show?
