### ISSUE TITLE
Ctrl+a Ctrl+c throws an exception

### ISSUE THREAD

**Issue by parkovski** [PowerShell/PSReadLine#265]
I was just trying to figure out the new editing functionality in Win10 pressing Ctrl+anything, and got an exception. After a little more prodding around, it looks like this is almost always triggered by typing a few characters and then pressing Ctrl+a Ctrl+c.

I was given this message:

```
Last 200 Keys:
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace a s d f a s d f Ctrl+r j k l ; Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 a s d k f j a s l d k f j l s k d j f Ctrl+i Backspace Ctrl+r Backspace Ctrl+r Ctrl+R Backspace Ctrl+R Backspace Ctrl+e Backspace Ctrl+w Backspace Ctrl+q Backspace Ctrl+a Ctrl+s Enter
 Ctrl+s Enter
 Ctrl+w Backspace Ctrl+e Ctrl+e Backspace Backspace Ctrl+r Backspace Enter
 Ctrl+r Enter
 Ctrl+t Backspace Ctrl+y Ctrl+u Backspace Ctrl+y Ctrl+y Ctrl+y Ctrl+h Ctrl+y Ctrl+Backspace Ctrl+h Ctrl+h Ctrl+h Ctrl+f Ctrl+f Ctrl+Backspace Ctrl+h Ctrl+h Ctrl+h Ctrl+t Ctrl+y Ctrl+y Ctrl+y Ctrl+y Ctrl+j Ctrl+i Ctrl+o Ctrl+p Ctrl+[ Ctrl+] Ctrl+\ Ctrl+' Ctrl+; Ctrl+\ Ctrl+Backspace Ctrl+- Ctrl+= Enter
 Ctrl+/ Ctrl+. Ctrl+, Ctrl+l Ctrl+; Ctrl+l Ctrl+k Ctrl+j Ctrl+h Ctrl+g Ctrl+f Ctrl+d Ctrl+s Ctrl+a Ctrl+z Ctrl+x Ctrl+c Ctrl+v Ctrl+b Ctrl+n Ctrl+m Ctrl+, Ctrl+. Ctrl+z Ctrl+x Ctrl+z Ctrl+z a s d f Ctrl+r Ctrl+c j k l Ctrl+z o LeftArrow Ctrl+z LeftArrow Ctrl+z Ctrl+z d a n g Ctrl+m Ctrl+n Ctrl+b Ctrl+v Ctrl+c Ctrl+v Ctrl+v Ctrl+c Ctrl+x j k l j k Ctrl+a Ctrl+c

Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by rkeithhill** [comment]
Looks like the PSReadLine code should be beefed up to handle this scenario as other apps can have the clipboard open and in that case, PSRL can't access the clipboard.  This is usually handled by WinForms retrying after some delay.  But if that doesn't help PSRL, should catch this exception and display an error message like "Could not copy the requested text to the clipboard.  Another application has the clipboard open."  Another option is to PInvoke to the Win32 clipboard APIs to do the copy.  See http://stackoverflow.com/questions/68666/clipbrd-e-cant-open-error-when-setting-the-clipboard-from-net

**Comment by rkeithhill** [comment]
BTW this was a problem for us in the early days of PSCX - lots of clipboard errors.  One of our contributors wrote this clipboard command base class to help: https://pscx.codeplex.com/SourceControl/latest#Trunk/Src/Pscx/Commands/UIAutomation/ClipboardCommandBase.cs

**Comment by mwf19** [comment]
I assume this is oldnews.net but (also don't ask about the last 121 keys)

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 121 Keys:
 UpArrow UpArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+L
eftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow
 Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+L
eftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow
 Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+L
eftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow
 Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+L
eftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow
 Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+L
eftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow
 Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+L
eftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow
 Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+L
eftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow
 Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+L
eftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Ctrl+c

Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by jlucktay** [comment]
+1 again just now

**Comment by lzybkr** [comment]
I believe I've fixed this now using retries like @rkeithhill suggested, see https://github.com/lzybkr/PSReadLine/blob/fb10c6d9c3bb413aafdfe8073004b59d4a294535/PSReadLine/Clipboard.cs#L237. The fix is sitting in the ansi_render branch until I think it's ready for release. You can build it yourself or grab a build out of appveyor.

**Comment by Venryx** [comment]
Seem to have encountered this error today in the latest (basically) version of Visual Studio Code.
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 e c k Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Spacebar r u n Spacebar c r e a t e - v e n d o r s - q u i c k Enter
 n p m Spacebar i n s t a l l Spacebar - - s a v e - d e v Spacebar w e b p a c k - c l i Enter
 n p m Spacebar i n s t a l l Spacebar - - s a v e - d e v Spacebar h a r d - s o u r c e - w e b p a c k - p l u g i n Spacebar m i n i - c s s - e x t r a c t - p l u g i n Spacebar s t r i n g - r e p l a c e - w e b p a c k - p l u g i n Enter
 n p m Spacebar Backspace Backspace Backspace p m Spacebar l i Backspace s Enter
 t a p a b l e Ctrl+a Ctrl+x

Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Cut(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Not a problem for me, but the message said to report it, so I did.

**Comment by lzybkr** [comment]
Thanks for reporting, it is fixed in 2.0.0-beta1.

**Comment by JensMertelmeyer** [comment]
I am not sure if I have an outdated version. I am just getting started with PowerShell.

```
PS C:\Users\Mertelmeyer> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

This is the stacktrace. The message is localized. "Der angeforderte Clipboard-Vorgang war nicht erfolgreich" roughly translates to "The requested clipboard operation was not successful".


```
Da hat etwas nicht geklappt. Geben Sie mit diesem Fehler folgende Details an.
Bericht auf GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Letzte 33 Tasten:
 r e g s v r 3 2 Spacebar / u Spacebar s c v n c c t r l . d l l Enter
 LeftWindows UpArrow Ctrl+Shift+LeftArrow Ctrl+Shift+LeftArrow Ctrl+Shift+LeftArrow Ctrl+Shift+RightArrow Ctrl+c

Ausnahme:
System.Runtime.InteropServices.ExternalException (0x800401D0): Der angeforderte Clipboard-Vorgang war nicht erfolgreich.
   bei System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   bei System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   bei System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   bei Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bei Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
@JensMertelmeyer - you can install the latest version from [here](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta2) and this problem should be fixed.

**Comment by shishini** [comment]
Got this error today
```
Oops, something went wrong.  Please report this bug with the details below.                                                                                                
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new                                                                                                          
-----------------------------------------------------------------------
Last 143 Keys:
 g e t - Tab p Tab a Tab Enter
 g e t Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Enter
 q Backspace UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow $ p s Tab v Tab Enter
 p s r e a Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace i n s Tab s Backspace t a Tab Tab Tab - p Tab Tab Tab Space P s Tab Tab Tab Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace p Tab Tab Tab Space P s Backspace S R e a d L i n e Enter
 g e t Tab Tab Tab Tab

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -11.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```
I am on linux 
I seem to have the latest PSReadLine 

```
PS /home/user> Install-Package PSReadLine                                                                                                                                   

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
WARNING: Version '2.0.0-beta2' of module 'PSReadLine' is already installed at '/opt/microsoft/powershell/6-preview/Modules/PSReadLine/2.0.0'. To install version '1.2', run Install-Module and add the -Force parameter, this command will install version '1.2' in side-by-side with version '2.0.0-beta2'.
```

My powershell version is 

```
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Linux 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by FarfanColin** [comment]
I got this error, any guess!! Tks in advance

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 105 Keys:
 g i t Space s t a t s Backspace u s Enter
 g i t Backspace Backspace Backspace Backspace g i t Space r e m o t e Space - v Enter
 g i t Space a d d Space . Enter
 g i t Space c o m m i t Space - m Space " Ctrl+c Ctrl+c UpArrow DownArrow g i t Space c o m m i t Space - m Space Ctrl+v Ctrl+c Ctrl+c UpArrow Backspace Backspace Backspace Backspace Backspace c o m m i t Space - m Space 2 Backspace d s Backspace Backspace 3 Backspace "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)   
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
