### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by anLpk** [PowerShell/PSReadLine#2650]
n g Space a d d Space @
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left

**Comment by daxian-dbw** [comment]
Please follow the issue template when reporting an issue. The needed information is important for investigation. 

If you haven't, please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery. It's possible the issue you ran into was fixed. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
