### ISSUE TITLE
Ctrl-L seems to have crashed Windows Terminal?

### ISSUE THREAD

**Issue by dennisvanderpool** [PowerShell/PSReadLine#2652]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 20 Keys:
 c d Space A c f - A Tab Enter
 g i t Space p u l l Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by dennisvanderpool** [comment]
If you need more info, please let me know and I will add the info.

**Comment by dennisvanderpool** [comment]
See also #2651

**Comment by daxian-dbw** [comment]
The issue report URL indicates you were using a very old version of PSReadLine (2.0.0-beta2 or prior). This was likely fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
