### ISSUE TITLE
Don't add commands to history if it generated an error

### ISSUE THREAD

**Issue by markdomansky** [PowerShell/PSReadLine#2653]
## Description of the new feature/enhancement

When a command generates an error, it should not be added to the command history.  Adding these to the command history generates unhelpful suggestions that, if selected, just reinforce their own recommendations.

## Proposed technical implementation details (optional)

This could definitely be implemented as an optional feature, but I don't see why someone would want them in the psreadline history.  If it generates an error, the command still exists within the PowerShell command history.

**Comment by iSazonov** [comment]
In this case, we would be forced to retype a long command because of any error.

**Comment by antonklimov** [comment]
> In this case, we would be forced to retype a long command because of any error.

You can always use regular powershell history for that.

**Comment by panekj** [comment]
This is the same behaviour as any other shell, if you don't want it in your history, you should manually delete it.

**Comment by MarkDomansky** [comment]
> This is the same behaviour as any other shell, if you don't want it in your history, you should manually delete it.

This is not possible while the shell is open.  I've tried it.  something about the file is buffered in memory and removing a line results in it getting re-added soon after.  Also, we're not talking about *shell* behavior.  The *shell*'s history would still have it.  We're talking about *psreadline*'s intellisense history.

**Comment by MarkDomansky** [comment]
I've partially mitigated this by using ValidateAndAcceptLine
``` Set-PSReadLineKeyHandler -key Enter -Function ValidateAndAcceptLine ```
This might be enough for me, at least it catches my typos (or some of them).  I still think it would be nice to have a way to 1. detect and remove commands that generate an error, 2. have a command to remove a line from the history.

**Comment by daxian-dbw** [comment]
PSReadLine adds an accepted command to history before it return that command line string to PowerShell for execution, so this is the by design behavior. `ValidateAndAcceptLine` could be the solution for you, especially you can configure the `CommandValidationHandler` to customize the validation you want to perform. Also, you can leverage `AddToHistoryHandler` to customize whether an accepted command line should be put in the history.
