### ISSUE TITLE
Oops, something went wrong.  Please report this  bug with the details below.

### ISSUE THREAD

**Issue by Teknath-jha** [PowerShell/PSReadLine#2654]
Last 137 Keys:
 c d Space " c : \ U s e r s \ j h a t e \ O n e D r i v e \ D e s k t o p \ D S A Space 1 \ s t r i n g \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space s t r i n g H a s h i n g 1 . c p p Space - o Space s t r i n g H a s h i n g 1 Space } Space ; Space i f Space ( $ ? ) Space { Space . \ s t r i n g H a s h i n g 1 Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.  
Parameter name: left
Actual value was -1.

**Comment by daxian-dbw** [comment]
Please follow the issue template when reporting an issue. The needed information is important for investigation. 

If you haven't, please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery. It's possible the issue you ran into was fixed. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
