### ISSUE TITLE
Something went wrong when i compiled

### ISSUE THREAD

**Issue by VinayakHyde** [PowerShell/PSReadLine#2657]
The details:

Output:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\csvin\OneDrive\Desktop\Practise> cd "c:\Users\csvin\OneDrive\Desktop\Practise"
PS C:\Users\csvin\OneDrive\Desktop\Practise> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 78 Keys:
 c d Space " c : \ U s e r s \ c s v i n \ O n e D r i v e \ D e s k t o p \ P r a c t i s e " Enter
 & Space . \ " 2 . D o u b l y _ L i n k e d _ L i s t . e x e " Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and 
less than the console's buffer size in that 
dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String 
defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)     
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\csvin\OneDrive\Desktop\Practise>

My file ( if necessary )

<#include<stdio.h>
#include<stdlib.h>

struct node
{
   int data;
   struct node *prev;
   struct node *next;
};

void display(struct node*);
void insert_head(struct node**, int);
void insert_tail(struct node **, int);
void insert_pos(struct node **,int ,int);
void delete_last(struct node **);
void delete_first(struct node **);
void delete_pos(struct node**, int); 
void delete_node(struct node**, int);
void ordered_insertion(struct node**, int);
void reverse(struct node**);

int main()
{
  struct node *head;
  head=NULL;
  int x,ch,pos;
  while(1)
  {
    display(head);
    printf("\n1..Insert Head..\n");
    printf("2..Insert Tail..\n");
	printf("3..Insert at position..\n");
    printf("4..Delete First..\n");
    printf("5..Delete Last..\n");
	printf("6..Delete at position..\n");
    printf("7..Delete node..\n");
    printf("8..Ordered Insertion..\n");
    printf("9..Reverse..\n");
	printf("10..Autopopulate..\n");    
    printf("11..Order Ins Trial..\n");
	printf("12..Exit..\n");
    
    scanf("%d",&ch);

    switch(ch)
    {
        case 1: printf("Enter the value..\n");
            scanf("%d",&x);
            insert_head(&head,x);
            break;
        case 2: printf("Enter the value..\n");
            scanf("%d",&x);
            insert_tail(&head,x);
            break;
      	case 3: printf("Enter the value and position..\n");
            scanf("%d %d",&x,&pos);
            insert_pos(&head,x,pos);
            break;
        case 4:delete_first(&head);
            break;
        case 5:delete_last(&head);
            break;
       	case 6: printf("Enter the position..\n");
            scanf("%d",&x);
            delete_pos(&head,x);
            break;
        case 7: printf("Enter the value..\n");
            scanf("%d",&x);
            delete_node(&head,x);
            break;
        case 8:printf("Ascending Order Insertion\n");
            scanf("%d",&x);
            ordered_insertion(&head, x);
            break;
        case 9:printf("Reverse\n");
            scanf("%d",&x);
            reverse(&head);
            break;
		case 10:printf("Entered autopopulate\n");		
			insert_head(&head,5);
			insert_head(&head,4);
			insert_head(&head,3);
			insert_head(&head,2);
			insert_head(&head,1);
			break;
        case 11:printf("Ascending Order Insertion Trial\n");
            ordered_insertion(&head, 1);
            ordered_insertion(&head, 4);
            ordered_insertion(&head, 2);
            ordered_insertion(&head, 56);
            ordered_insertion(&head, 25);
            ordered_insertion(&head, 5);
            ordered_insertion(&head, 7);
            break;
	   	case 12: exit(0);
    }

  }
}

void display(struct node *p)
{
   if(p==NULL)
        printf("List is empty\n");

    else
    {
        while(p!=NULL)
        {
            printf("%d<->",p->data);
            p=p->next;
        }
        printf("NULL\n");
    }
}

void insert_head(struct node **p, int x)
{
	struct node* temp;

    temp=(struct node*)malloc(sizeof(struct node));
    temp->data=x;
    temp->next=NULL;
    temp->prev=NULL;

    if(*p==NULL)     //empty list
        *p=temp;

    else            //non empty list
    {
        temp->next=*p;
        (*p)->prev=temp;
        *p=temp;
    }
}	

void insert_tail(struct node **p, int x)
{
	struct node* temp;

    temp=(struct node*)malloc(sizeof(struct node));
    temp->data=x;
    temp->next=NULL;
    temp->prev=NULL;

    if(*p==NULL) //empty list
    {
        *p=temp;
    }

    else        //non empty list
    {
        struct node*q;
        q=*p;

        while(q->next!=NULL)
            q=q->next;
        
        temp->prev=q;
        q->next=temp;
    }
}	

void insert_pos(struct node **p, int x, int pos)
 {
    struct node* temp;

    temp=(struct node*)malloc(sizeof(struct node));
    temp->data=x;
    temp->next=NULL;
    temp->prev=NULL;

    if((*p==NULL)&&(pos==1)) //1st position and empty list
        *p=temp;

    else
    {
        struct node*q;
        q=*p;

        int i=1;

        while((q->next!=NULL)&&(i<pos))
        {
            q=q->next;
            i++;
        }

        if(i==pos) //position found
        {
            if(q->prev==NULL)  //1st position, non empty list
            {
                printf("Sup1\n");
                temp->next=*p;
                q->prev=temp;
                *p=temp;
            }

            else    //between 1st and last
            {
                printf("Sup2\n");
                temp->next=q;
                temp->prev=q->prev;
                q->prev->next=temp;
                q->prev=temp;
            }
        }

        else if (i==pos-1)//last position ,i.e, q is at the last node
            {
                q->next=temp;
                temp->prev =q;
            }	 

        else
            printf("Invalid Position\n");
    }
}	
	
void delete_first(struct node **p)
{
	if(*p==NULL)
        printf("List is empty\n");

    else
    {
        struct node *q;
        q=*p;

        if(q->next==NULL)    //only 1 node
                *p=NULL;

        else    //more than 1 node
        {
            *p=q->next;
            q->next->prev=NULL;
        }

        free(q);
    }
} 		
	
void delete_last(struct node **p)  
{
	if(*p==NULL)
        printf("List is empty\n");

    else
    {
        struct node *q;
        q=*p;

        if(q->next==NULL)    //only 1 node
                *p=NULL;

        else    //more than 1 node
        {
            while(q->next!=NULL)
                q=q->next;
                
            q->prev->next=NULL;
        }

        free(q);
    }
}			

void delete_pos(struct node **p, int pos)
{
    struct node *q;
    q=*p;

    int i=1;

    while((q->next!=NULL)&&(i<pos))
        {
            q=q->next;
            i++;
        }

    if(i==pos) //position found
    {
        if(q->prev==NULL)    //1st position
        {
            if(q->next==NULL)  //only 1 node
                *p=NULL;

            else    //more than 1 node 
            {
                q->next->prev=NULL;
                *p=q->next;
            }
        }

        else if(q->next!=NULL)  //intermediate position
        {
            q->next->prev=q->prev;
            q->prev->next=q->next;
        }
        
        else //last position
            q->prev->next=NULL; //more than 1 node in list
        free(q);    //empty list and 1 node in list conditions are already covered
    }

    else
        printf("Invalid Position\n");
}

void delete_node(struct node **p, int x)	
{
    struct node *q;
    q=*p;

    int i=1;

    while((q->next!=NULL)&&(q->data!=x))
        {
            q=q->next;
            i++;
        }

    if(q->data==x)
    {
        if(q->prev==NULL)       //1st position
            {
                if(q->next==NULL)   //only 1 node
                    *p=NULL;

                else    //more than 1 node
                {
                    q->next->prev=NULL;
                    *p=q->next;
                }
            }

        else if(q->next!=NULL)  //intermediate position 
        {
            q->prev->next=q->next;
            q->next->prev=q->prev;
        }
            
        else                //last
            q->prev->next=NULL; //more than 1 node in list
            //empty list and 1 node in list conditions are already covered

        free(q);
    }

    else            //No matching entry || empty list condition
        printf("No matching position\n");

}

void ordered_insertion(struct node** p, int x)      //will be inserted in ascending order
{
    struct node *temp;

    temp=(struct node*)malloc(sizeof(struct node));
    temp->data=x;
    temp->next=NULL;
    temp->prev=NULL;

    if(*p==NULL)        //empty list
        *p=temp;

    else                //non empty list
    {
        struct node *q;
        q=*p;

        while((q->next!=NULL)&&(q->data<x))
        {
            q=q->next;
        }

        if(q->data>=x) //position found
            {
                if(q->prev==NULL)   //1st position
                {
                    temp->next=q;
                    q->prev=temp;
                    *p=temp;
                }

                else            //between first and last
                {
                    temp->next=q;
                    temp->prev=q->prev;

                    q->prev->next=temp;
                    q->prev=temp;
                }
            }

        else if((x>q->data)&&(q->next==NULL))   //last position
        {
            q->next=temp;
            temp->prev=q;
        }
    }
}

void reverse(struct node **p)
{
    struct node *temp, *curr;

    temp=*p;

    while(temp!=NULL)
    {
        curr=temp;
        temp=curr->next;
        curr->next=curr->prev;
        curr->prev=curr->next;

        /* if(temp!=NULL)
            curr=temp; */
    }
    *p=curr;
}

Thanks for the work.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
