### ISSUE TITLE
“Oops, something went wrong.”

### ISSUE THREAD

**Issue by ifermi** [PowerShell/PSReadLine#2663]
## Environment

```none
[run the script below and paste the output here]
```

**Comment by ifermi** [comment]
![image](https://user-images.githubusercontent.com/74921172/125195108-cc89a580-e286-11eb-91a0-5d4fd7c3e108.png)

**Comment by daxian-dbw** [comment]
This is a known issue and has been addressed in 2.2.0-beta3 release of PSReadLine. Please upgrade to use 2.2.0-beta3 with the latest 7.2.0-preview.9 PowerShell.
