### ISSUE TITLE
Any way to use PSReadline under remote console sessions?

### ISSUE THREAD

**Issue by mkanet** [PowerShell/PSReadLine#271]
My apologies in advance if this is the wrong place to ask this... Does anyone know of a way to get PSReadline to function under remote console sessions (I.E. New-PSSession/Enter-PSSession)?  The module imports without any errors in remote sessions; however, it doesnt change the text color.  I'm guessing, the module is expecting a local console session. Maybe, there's a clever work-around?

**Comment by lzybkr** [comment]
Everything should just work naturally with Enter-PSSession.  You don't import in the remote session, you import in the local session.
Tab completion works against the remote runspace if you've used Enter-PSSession.

**Comment by mkanet** [comment]
Thanks for the reply.  I'm actually trying to do something unusual... My local sessions are all virgin WIn7 machines with PS Version 2.0.  The remote machines are all Powershell 3.0 and above.  I was hoping for a way to get PSLine to work **_in**_ the actual remote session console; at least, while I'm in the remote console.

**Comment by lzybkr** [comment]
Sorry, that scenario doesn't work, you'll have to install V3 or later on your Win7 machines.
