### ISSUE TITLE
Vi mode: minor issue/request

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#273]
When using `/` or `?` to search history pressing `tab` instead of `enter` draws an unprintable character on the screen.

At the very least the `tab` key should just be ignored but I would like to request that `tab` initiates the search just like pressing `enter`.

**Comment by srdubya** [comment]
I'll look into it.

**Comment by srdubya** [comment]
Just pushed this change, `tab` now acts like `enter`.

**Comment by gwojan** [comment]
Awesome! I just tested it out and it works just like my fingers want it to... :wink:
