### ISSUE TITLE
I get "failed-bck-i-search" when ever I CTRL+R in powershell

### ISSUE THREAD

**Issue by wamra** [PowerShell/PSReadLine#2742]
## Environment

```none
PS version: 5.1.18362.1593
PSReadline version: 2.1.0
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 292
BufferHeight: 9999
```

## Exception report

No Exceptions 

## Steps to reproduce

When I press CTRL+R the message "failed-bck-i-search" is displayed. 

I suspect the cause is my history length 
```
gc -path $((Get-PSReadLineOption).HistorySavePath) |Measure-Object -Line

Lines Words Characters Property
----- ----- ---------- --------
16776
```

## Expected behavior

Fast key presses, CTRL+R to not 'fail'

## Actual behavior

My arrow up/down to scroll through history is very slow it takes seconds, and it slows the entire powershell session host.

**Comment by ghost** [comment]
:tada: This issue was addressed in 2867, which has now been successfully released in [`v2.2.0-beta4`](https://github.com/PowerShell/PSReadLine/releases/tag/v2.2.0-beta4). :tada:
