### ISSUE TITLE
Cursor moves to an incorrect place when using Japanese text input

### ISSUE THREAD

**Issue by ronba** [PowerShell/PSReadLine#275]
When typing in Japanese text the cursor is moved to an incorrect place:

Repro steps:
1. Open Powershell and Type (or paste) something like: 日本語
2. Then switch back to English (or continue typing in Japanese) - the cursor remains "behind" the letters as new letters are being inserted.

Attached GIF that shows the behaviour:
![powershelljapanese](https://cloud.githubusercontent.com/assets/10216856/9537785/ca853fba-4d77-11e5-99f2-725c58be38d0.gif)

This only happens if PSReadline is loaded.

**Comment by lzybkr** [comment]
Which version?  I think this should work on Win10 or if you've PSReadline yourself from master, but if you've installed a pre-built version yourself (probably 1.0.0.13), then that would explain it.

**Comment by ronba** [comment]
Version is 1.0.0.13 (like you said) on Windows 10 installed using the new Install-Module command (not PSGet).
I tried building the project from master but compilation failed.
Is there a place where I can get the latest version?

**Comment by rkeithhill** [comment]
Windows 10 comes with the latest version built-in - 1.1.  You don't need to install PSReadLine.  Try running the following to remove version 1.0.0.13:

```
Uinstall-Module PSReadLine -RequiredVersion 1.0.013
```

**Comment by ronba** [comment]
Uninstall-Module didn't do the job, removed it myself and loaded the 1.1 version.
The cursor problem is no longer present like you said however the typing is still weird.

Nothing is displayed on the screen until I press Enter, in some cases I can see the IME completion on the bottom part of the screen (which is pretty cool!) but it disappears if I keep typing in most cases.
Not sure if this is how it's supposed to behave:
1. Open PowerShell
2. Switch to Japanese 
3. Start typing: nininini (in Japanese characters) - nothing is displayed until you press Enter.
Is there no way to allow the user to use the normal Japanese IME like in the gif above?

**Comment by lzybkr** [comment]
I believe this is fixed in #561.

I'll publish a pre-release version to the PowerShell Gallery as soon as they support pre-releases.

If you'd like to try a fix before that, you can build the lastest yourself from the master branch, or
grab a build from AppVeyor like this [one](https://ci.appveyor.com/api/buildjobs/ust6h6k216i5gm81/artifacts/bin%2FRelease%2FPSReadline.zip).

Note the version number is now 2.0, so be sure to copy the contents to \PSReadLine\2.0.

**Comment by lzybkr** [comment]
I'll have an official prerelease build out next week if you want to verify this is fixed, otherwise you can grab a build out of appveyor [here](https://ci.appveyor.com/project/lzybkr/psreadline).
