### ISSUE TITLE
PSReadLine NullReferenceException with 32-bit powershell on 64-bit Windows 10

### ISSUE THREAD

**Issue by veleek** [PowerShell/PSReadLine#279]
When I launch a powershell window from Launchy, I get this errors from the command line every time I do anything.  I'm unable to run any commands and stuff like Tab Completion will cause the same error to occur and reset the prompt.

I'm running 64-bit Windows 10, and when launching powershell from the start menu it's fine.  Launchy is 32 bit only so unfortunately launches a 32-bit powershell.  A relatively easy way to repro this:
1. Start the 32-bit cmd from `c:\windows\syswow64\cmd.exe`
2. Start powershell: `powershell -noprofile`
3. `Import-Module PSReadLine`

```
PS C:\<ProfilePath>\WindowsPowershell\Modules> import-module .\PSReadLine
Exception calling "AddToHistory" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\<ProfilePath>\WindowsPowershell\Modules\PSReadLine\PSReadLine.psm1:17 char:32
+ ... ch-Object { [PSConsoleUtilities.PSConsoleReadLine]::AddToHistory($_.C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

Exception calling "AddToHistory" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\<ProfilePath>\WindowsPowershell\Modules\PSReadLine\PSReadLine.psm1:17 char:32
+ ... ch-Object { [PSConsoleUtilities.PSConsoleReadLine]::AddToHistory($_.C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

Exception calling "AddToHistory" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\<ProfilePath>\WindowsPowershell\Modules\PSReadLine\PSReadLine.psm1:17 char:32
+ ... ch-Object { [PSConsoleUtilities.PSConsoleReadLine]::AddToHistory($_.C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

PS C:\<ProfilePath>\WindowsPowershell\Modules>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Or email: jason@truewheels.net
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PSConsoleUtilities.PSConsoleReadLine.ReadKey()
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
   at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by veleek** [comment]
Seemingly I can also get this to occur if I launch powershell from within an existing working powershell window.

Also calling [PSConsoleUtilities.PSConsoleReadLine]::ReadLine() produces the exact same error.

**Comment by rkeithhill** [comment]
@veleek The version of PSReadLine that is built into Windows 10 has changed the type name of PSConsoleReadLine.  The type name should be [Microsoft.PowerShell.PSConsoleReadLine]. 

It looks like you may have installed PSReadLine 1.0.0.3.  If so, that is unnecessary as Windows 10 comes with version 1.1 built in.  Remove the directory `C:\<ProfilePath>\WindowsPowershell\Modules\PSReadLine` and try again.

**Comment by lzybkr** [comment]
@rkeithhill is right - it looks like you installed PSReadline with Install-Module, but that wasn't necessary.  Just remove the directory and you should be set.

**Comment by veleek** [comment]
Awesome, cool to see that you got top billing in Win 10.  I have my profile shared across a bunch of machines using OneDrive so I just added a condition to not import PSReadLine if it's already available.  Everything seems to be working now!

Thanks!
