### ISSUE TITLE
Ctrl+[ only mappable as Ctrl+Oem4

### ISSUE THREAD

**Issue by parkovski** [PowerShell/PSReadLine#2790]
## Environment

PS version: 7.1.4
PSReadline version: 2.1.0
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.4.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001

## Steps to reproduce

Press `Ctrl+[`. I use vi editing mode and expect this to do the same thing as escape. Instead, it prints `^[`. In addition, I have the following line in my profile, and have tried many variants (e.g. with `-ViMode Insert`, mapping various key codes, anything I could think of), all to no effect:

```
Set-PSReadlineKeyHandler -Key 'Ctrl+[' -Function ViCommandMode
```

All other control key mappings work fine. A while back I added an environment variable, `PSREADLINE_VTINPUT`, and if this is set, this combo does work as an alias for escape, but if it is not set the combo is not mappable at all.

## Expected behavior

Probably in default mode, this would be a separate mapping rather than an alias of escape as Windows reports it differently.

## Actual behavior

It can't be mapped at all, and types `^[` whether in vi insert or command mode.

**Comment by parkovski** [comment]
Update - it is mappable as `Ctrl+Oem4`, at least on my keyboard.

**Comment by daxian-dbw** [comment]
Close as a dup of #906
