### ISSUE TITLE
Console error on clear using "ctrl"+"L"

### ISSUE THREAD

**Issue by rafikalid** [PowerShell/PSReadLine#2804]
Console has many problemes on windows when using as "tab"
copy and past do not work properly, and when trying to clear the console using "cntrl+L", it brocks!
-----------------------------------------------------------------------
Last 61 Keys:
 UpArrow Enter
 Ctrl+c Ctrl+l UpArrow Enter
 Ctrl+l UpArrow Enter
 Ctrl+l UpArrow Enter
 Ctrl+l UpArrow Ctrl+l Enter
 Ctrl+l UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace 
Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace UpArrow Enter
 Ctrl+l UpArrow Enter
 Ctrl+l UpArrow Ctrl+l Enter
 Ctrl+l UpArrow Ctrl+l Enter
 UpArrow Enter
 Ctrl+l Escape Ctrl+l Ctrl+l UpArrow Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -17.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
