### ISSUE TITLE
KeyHandlers in Binary Module (question/help)

### ISSUE THREAD

**Issue by MarcoBuess** [PowerShell/PSReadLine#2811]
## Description of the new feature/enhancement

I'm trying to register a KeyHandler that only works in Vi `command`-mode from within a binary module.

## Proposed technical implementation details (optional)

I can setup a KeyHandler successfully like so:

```fsharp
PSConsoleReadLine.SetKeyHandler([|"v"|], myHandler, "someBriefDesc", "someLongDesc")
```
The problem is though, that this will only work in `insert`-mode when using `EditMode = 'vi'`.

How can I define a KeyHandler, that targets Vi `command`-mode like in PowerShell:

```powershell
Set-PSReadLineKeyHandler -ViMode Command -Key v -ScriptBlock { }
```

I'm building the module using `fsharp`, but a `csharp` example would be highly appreciated too.

**Comment by lzybkr** [comment]
It looks like the api was not made public.

One way would be to invoke the cmdlet. The C# way to do that, using PowerShell syntax, is something like:

```PowerShell
$ps = [PowerShell]::Create([System.Management.Automation.RunspaceMode]::CurrentRunspace)
$null = $ps.AddCommand("Set-PSReadLineKeyHandler")
$null = $ps.AddParameter("ViMode", "Command")
$null = $ps.AddParameter("Key", "v")
$scriptBlock = [ScriptBlock]::Create("[yourstaticclass]::YourStaticMethod($args[0], $args[1])")
$null = $ps.AddParameter("ScriptBlock", $scriptBlock)
$ps.Invoke()
```

I don't think there is a way to bind your function directly, you'll need the scripblock calling your function, so it will need to be a public method in a public class.

I think the only other reasonable alternative is to update the public api to add this capability.

**Comment by MarcoBuess** [comment]
Thanks for the example @lzybkr. Will try that out as soon as I can. I already have an implementation in PowerShell, so I might as well  just stick with that.

**Comment by MarcoBuess** [comment]
@lzybkr I tried out your example. As I apprehended the code isn't able to find my static class. Here is a snipped of my code
```fsharp
module Hello =
    let sayHello = printfn "Hello World!"

let ps =
    PowerShell.Create(RunspaceMode.CurrentRunspace)
    |> fun ps ->
        ps.AddCommand("Set-PSReadLineKeyHandler")
        ps.AddParameter("ViMode", "Command")
        ps.AddParameter("Key", "v")
        ps.AddParameter("ScriptBlock", scriptBlock)
ps.Invoke() |> ignore
```
I expect the `ScriptBlock` need some sort of way to add the assembly to the current session using `Add-Type`. Let me know if I am wrong on this one. 😄 

Thanks.

Edit: Here is the error message
```powershell
$ An exception occurred in custom key handler, see $error for more information: Unable to find type [Hello].
```

**Comment by lzybkr** [comment]
Maybe try:

```f#
module public Hello =
```

**Comment by MarcoBuess** [comment]
That didn't work either. Also specifying the full namespace of the `sayHello` function didn't do the trick. 😞

**Comment by MarcoBuess** [comment]
Thanks for lighting a spark @lzybkr. I was able to get a working example going. Anybody pursuing the same path as I, here are snippets of my working example:

```fsharp
let modulePath = Assembly.GetExecutingAssembly().Location

module Hello =
    let sayHello() = printfn "Hello World!"

type OnModuleImportAndRemove() =
    interface IModuleAssemblyInitializer with
        member __.OnImport() =
            PSConsoleReadLine.SetOptions(SetPSReadLineOption(EditMode = EditMode.Vi))
            let script = sprintf "Add-Type -Path \"%s\"; [MyModule+Hello]::sayHello()" modulePath

            PowerShell.Create(RunspaceMode.CurrentRunspace)
            |> fun ps ->
                ps.AddCommand("Set-PSReadLineKeyHandler")
                ps.AddParameter("ViMode", "Command")
                ps.AddParameter("Key", "v")
                ps.AddParameter("ScriptBlock", ScriptBlock.Create(script))
                ps.Invoke() |> ignore

    interface IModuleAssemblyCleanup with
        member __.OnRemove(_) =
            PSConsoleReadLine.SetOptions(SetPSReadLineOption(EditMode = EditMode.Windows))
```

The code will enable `EditMode = Vi` on import and bind `v` to run `Hello World!`. `EditMode` is automatically set back on module removal.

**Comment by lzybkr** [comment]
I'm glad you found a solution. I don't know why `Add-Type` would be required when the assembly is obviously already loaded, but I'm glad it works.

**Comment by MarcoBuess** [comment]
@lzybkr You are actually right! The crux lies within the method call. For some reason it can't find the `Hello` class in the namespace when using `[PSReadLineViVisualMode.Hello]::sayHello()`. It is only working when I'm using `[PSReadLineViVisualMode+Hello]::sayHello()`. I don't know if thats some sort of inconsistency, but anyway here is the updated code that is working as expected:
```fsharp
module Hello =
    let sayHello() = printfn "Hello World!"

type OnModuleImportAndRemove() =
    interface IModuleAssemblyInitializer with
        member __.OnImport() =
            PSConsoleReadLine.SetOptions(SetPSReadLineOption(EditMode = EditMode.Vi))
            let script = "[PSReadLineViVisualMode+Hello]::sayHello()"

            PowerShell.Create(RunspaceMode.CurrentRunspace)
            |> fun ps ->
                ps.AddCommand("Set-PSReadLineKeyHandler")
                ps.AddParameter("ViMode", "Command")
                ps.AddParameter("Key", "v")
                ps.AddParameter("ScriptBlock", ScriptBlock.Create(script))
                ps.Invoke() |> ignore

    interface IModuleAssemblyCleanup with
        member __.OnRemove(_) =
            PSConsoleReadLine.SetOptions(SetPSReadLineOption(EditMode = EditMode.Windows))
```

**Comment by lzybkr** [comment]
Great, this looks like what I had in mind, I'm glad you've got it working.
