### ISSUE TITLE
PSReadLine Missing on Windows 10

### ISSUE THREAD

**Issue by veleek** [PowerShell/PSReadLine#282]
I have a version of Windows 10 that was updated from the Tech Preview to the RTM version, and it appears that whatever version I got did not have PSReadline included and now even though I'm on the RTM I don't have it.  

Is there anyway for me to easily get the 1.1 version of PSReadLine manually?  Installing a version from PSGet still gives me an earlier version which has issues with Win 10.

Also, is there every going to be any updated documentation indicating that PSReadLine is included with Win10?  Could be worth mentioning ANYWHERE on the page.  The only mention in the changenotes for 1.1 is a namespace rename.

**Comment by rkeithhill** [comment]
That's really weird.  I'm guessing that you could find a WIndows 10 system with 1.1 on it, copy the contents of the folder `C:\Program Files\WindowsPowerShell\Modules\PSReadline\1.1\` to the same location on your Win 10 machine.

**Comment by veleek** [comment]
Based on that comment, it seems like building whatever is currently checked in won't produce the same thing as is included in Windows.  Is that true?

I should be able to find another Win10 machine I can grab the binaries from.  Feel free to close the bug.

**Comment by lzybkr** [comment]
Building the current master should be very close, if not the same, as what shipped in Win10.  You wouldn't get the same binaries though.  That should be fine in most cases.
