### ISSUE TITLE
sudden error appeared in nodeJS execution

### ISSUE THREAD

**Issue by amine82amine82** [PowerShell/PSReadLine#2825]
while i was doing training on node.js i have created object "user". when i executed the code it executed for me the code console.log(user); but after a while it appeared to me that error. i have understood nothing
-----------------------------------------------------------------------
Dernières 200 touches :
 Space r o l e Space : Space " A d m i n " , Enter
 Space Space Space Space l o g i n C o u n t Space : Space 3 2 , Enter
 Space Space Space Space f a c e b o o k S i g n e d I n Space : Space t r u e Enter
 Ctrl+Alt+} v a r Space Space u s e r Space = Space Ctrl+Alt+{ Enter
 Space Space Space Space f i r s t N a m e Space : Space " A m i n e " , Enter
 Space Space Space Space l a s t N a m e Space : Space " B h i r i " , Enter
 Space Space Space Space r o l e Space : Space " A d m i n " , Enter
 Space Space Space Space l o g i n C o u n t Space : Space 3 2 , Enter
 Space Space Space Space f a c e b o o k S i g n e d I n Space : Space t r u e Enter
 Ctrl+Alt+}

Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
La valeur réelle était -1.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)       
   à Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   à Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   à Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) 
-----------------------------------------------------------------------
PS C:\MAMP\htdocs\Node.JS\02Intermediate> var  user = {
>>     firstName : "Amine",
>>     lastName : "Bhiri",
>>     role : "Admin",
>>     loginCount : 32,
>>     facebookSignedIn : true
>> }var  user = {
>>     firstName : "Amine",
>>     lastName : "Bhiri",
>>     role : "Admin",
>>     loginCount : 32,
>>     facebookSignedIn : true
>> }

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
