### ISSUE TITLE
elasticsearch mapping error

### ISSUE THREAD

**Issue by KonnToshinobu** [PowerShell/PSReadLine#2826]
直前 200 個のキー:
 y _ n a m e " " " Space : Space { " " " t y p e " " " : Space " " " s t r i n g " " 
" , Space " " " i n d e x " " " Space : Space " " " n o t _ a n a l y z e d " " " Space } , Enter
 Space Space Space Space " " " l i n e _ i d " " " Space : Space { Space " " " t y p 
e " " " Space : Space " " " i n t e g e r " " " Space } , Enter
 Space Space Space Space " " " s p e e c h _ n u m b e r " " " Space : Space { Space 
" " " t y p e " " " Space : Space " " " i n t e g e r " " " Space } Enter
 Space Space Space } Enter
 Space Space } Enter
 Space } Enter
 } Enter
 ' ;

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの次元のバッファー サ 
イズ未満を指定しなければなりません。
パラメーター名:top
実際の値は -5 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
