### ISSUE TITLE
arrow keys does not work with vim for navigation

### ISSUE THREAD

**Issue by narnaud** [PowerShell/PSReadLine#284]
PSReadline (Windows mode - I didn't try Emacs) is conflicting with vim for the arrow keys handling.

To reproduce, install git-for-windows (that's the one I'm using), in powershell with PSReadline enabled, open a file using vim (C:\Program Files\Git\usr\bin\vim.exe), and try to  navigate with the arrow keys: it doesn't work.
Try the same with a powershell without PSReadline: it works.

For what I can see, the problem affects Windows 8.1 (and probably lower), but not Windows 10.

**Comment by lzybkr** [comment]
Strange.  I normally use gvim, but do occasionally use vim, so I feel like I should have seen this before if the repro was simple.
What version of PSReadline do you have?
Also worth asking, are you using ConEmu?

**Comment by narnaud** [comment]
I'm using the version PsGet is giving me, 1.0.0.13 it seems, according to the changes.txt.
And you are right, I'm using ConEmu. I've tried without it, and I don't see the problem anymore.

**Comment by lzybkr** [comment]
OK, closing as this only happens in ConEmu, so unless I hear otherwise, I'll assume it's ConEmu's fault.
