### ISSUE TITLE
InvokePrompt Crash

### ISSUE THREAD

**Issue by bobbytreed** [PowerShell/PSReadLine#285]
Good Morning, sorry to bother you, discovered this issue, haven't had time to troubleshoot if yet or stack trace it.  Didn't know if you saw it before.

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 39 Keys:
 d i r e Spacebar - r e Backspace Backspace Backspace Backspace Backspace Spacebar 0 - r e Tab Backspace Backspace
ackspace - Backspace Backspace - r e Tab Spacebar - p a Tab Spacebar C : \ Ctrl+z

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.InvokePrompt(Nullable`1 key, Object arg)

**Comment by lzybkr** [comment]
Thanks for reporting it.

There is no need to investigate, I have a fix, I just haven't pushed it yet.

**Comment by bobbytreed** [comment]
Sweet. I've been singing the praises of your module. I teach powershell 14
times a year and I always have it loaded and show it off.

**Comment by lzybkr** [comment]
Closing - I must have fixed this at some point.
