### ISSUE TITLE
error when paste powershell code from clipboard

### ISSUE THREAD

**Issue by Eucrow** [PowerShell/PSReadLine#2862]
When I paste this code in a powershell window:
`$hs = "2019_H1.csv", "2019_HVD.csv"
foreach ($h in $hs)
{
$newFilename = "updated_$h"
(Get-Content $h) -replace 'ESP-IEO_DCF_Onboard_Sampling', 'WGRDBES-EST TEST 4' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'ESP-IEO_DCF_Port_Sampling', 'WGRDBES-EST TEST 4' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace '(DE.*),2019,(.*)', '$1,1965,$2' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace '(OS.*),2019-(.*)', '$1,1965-$2' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace '(FT.*),2019-(.*),2019-(.*)', '$1,1965-$2,1965-$3' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace '(FT.*),2019-(.*)', '$1,1965-$2' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace '(LE.*),2019-(.*)', '$1,1965-$2' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace '(FO.*),2019-(.*)', '$1,1965-$2' | Out-File -encoding ASCII $newFilename

(Get-Content $newFilename) -replace 'DRB_MOL_0_0_0', 'DRB_MOL_>0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'FPO_CRU_0_0_0', 'FPO_CRU_>0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'FPO_FIF_0_0_0', 'FPO_FIF_>0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'FPO_MOL_0_0_0', 'FPO_MOL_>0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'GND_SPF_<40_0_0', 'GND_SPF_31-39_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'GNS_DEF_120-219_0_0', 'GNS_DEF_120-219_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'GNS_DEF_50-59_0_0', 'GNS_DEF_50-59_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'GNS_DEF_60-79_0_0', 'GNS_DEF_60-69_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'GNS_DEF_80-99_0_0', 'GNS_DEF_90-99_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'GTR_DEF_50-59_0_0', 'GTR_DEF_50-59_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'GTR_DEF_60-79_0_0', 'GTR_DEF_60-69_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'HMD_MOL_0_0_0', 'HMD_MOL_>0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'LHM_CEP_0_0_0', 'LHM_CEP_0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'LHM_DEF_0_0_0', 'LHM_DEF_0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'LHM_DWS_0_0_0', 'LHM_DWS_0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'LHM_SPF_0_0_0', 'LHM_SPF_0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'LLS_DEF_0_0_0', 'LLS_DEF_0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'LLS_DWS_0_0_0', 'LLS_DWS_0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'OTB_DEF_100-119_0_0', 'OTB_DEF_100-119_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'OTB_DEF_>=55_0_0', 'OTB_DEF_70-99_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'OTB_DEF_>=70_0_0', 'OTB_DEF_70-99_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'OTB_DEF_70-99_0_0', 'OTB_DEF_70-99_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'OTB_MCD_>=55_0_0', 'OTB_MCD_55-64_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'OTB_MPD_>=55_0_0', 'OTB_MPD_55-64_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'PS_SPF_0_0_0', 'PS_SPF_>0_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'PTB_MPD_>=55_0_0', 'PTB_MPD_55-64_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'SDN_MCF_<55_0_0', 'SDN_MCF_55-64_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace 'TBB_MOL_<55_0_0', 'TBB_MOL_55-64_0_0' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace ',ES_RASCO_CN,GNS_DEF,GNS_DEF_>=100_0_0,', ',ES_RASCO_CN,GNS_DEF,GNS_DEF_>=220_0_0,' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace ',ES_ENMALLE_AC,GNS_DEF,GNS_DEF_>=100_0_0,', ',ES_ENMALLE_AC,GNS_DEF,GNS_DEF_100-119_0_0,' | Out-File -encoding ASCII $newFilename

(Get-Content $newFilename) -replace '(VD.*),2019,(.*)', '$1,1965,$2' | Out-File -encoding ASCII $newFilename
(Get-Content $newFilename) -replace '(SL.*),2019,(.*)', '$1,1965,$2' | Out-File -encoding ASCII $newFilename

}`

This error is thrown, but the script is paste and can be executed properly:
`Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 200 claves:
 e n a m e ) Space - r e p l a c e Space ' ( V D . * ) , 2 0 1 9 , ( . * ) ' , Space ' $ 1 , 1 9 6 5 , $ 2 ' Space Ctrl+Alt+| Space O u t - F i l e Space - e n c o d i n g Space A S C I I Space $ n e w F i l e n a m e Enter
 ( G e t - C o n t e n t Space $ n e w F i l e n a m e ) Space - r e p l a c e Space ' ( S L . * ) , 2 0 1 9 , ( . * ) ' , Space ' $ 1 , 1 9 6 5 , $ 2 ' Space Ctrl+Alt+| Space O u t - F i l e Space - e n c o d i n g Space A S C I I Space $ n e w F i l e n a m e Enter
 Enter
 Ctrl+Alt+}

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: top
Valor actual -23.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)`

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
