### ISSUE TITLE
Cannot paste responses to prompts into PowerShell host

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PSReadLine#290]
Without PSReadline, it's possible to paste both commands and responses to interactive prompts in the same block, like so:

``` powershell
New-Item -Type File foo.txt
Remove-Item -Confirm foo.txt
Y
# (invisible newline here)
```

With PSReadline, the 'Y' is not passed to the interactive prompt, but is parsed as a separate command after the interactive prompt is finished.

**Comment by lzybkr** [comment]
Closing in favor of #579 which covers all of the known issues with right-click paste.
