### ISSUE TITLE
bound method

### ISSUE THREAD

**Issue by ftoureFH** [PowerShell/PSReadLine#2908]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Dernières 200 touches :
 a m s Ctrl+Alt+\ P y t h o n Ctrl+Alt+\ P y t h o n 3 9 Ctrl+Alt+\ p y t h o n . e x e ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ f t Ctrl+Alt+\ . v s c o d e Ctrl+Alt+\ e x t e n s i o n s Ctrl+Alt+\ m s - p y t h o n . p y t h o n - 2 0 2 1 . 9 . 1 2 4 6 5 4 2 7 8 2 Ctrl+Alt+\ p y t h o n F i l e s Ctrl+Alt+\ l i b Ctrl+Alt+\ p y t h o n Ctrl+Alt+\ d e b u g p y Ctrl+Alt+\ l a u n c h e r ' Space ' 5 2 
5 8 1 ' Space ' - - ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ f t  Ctrl+Alt+\ C o d e Ctrl+Alt+\ V e r i f C o n v e r s i o n . p y ' Space Enter
```

### Environment data

```console
Dernières 200 touches :
 M o d e : Space $ ( ( G e t - P S R e a d L i n e O p t i o n ) . E d i t M o d e ) " Enter
 Space Space Space Space W r i t e - H o s t Space " O S : Space $ o s " Enter
 Space Space Space Space W r i t e - H o s t Space " B u f f e r W i d t h : Space $ ( Ctrl+Alt+[ c o n s o l e Ctrl+Alt+] : : B u f f e r W i d t h ) " Enter
 Space Space Space Space W r i t e - H o s t Space " B u f f e r H e i g h t : Space $ ( 
Ctrl+Alt+[ c o n s o l e Ctrl+Alt+] : : B u f f e r H e i g h t ) " Enter
 Space Space Space Space W r i t e - H o s t Space ' ' Enter
 Ctrl+Alt+}
```

### Steps to reproduce

import math
from scipy.fftpack import *
import numpy as np
from scipy import signal
from scipy import interpolate
from matplotlib import pyplot as plt
import CalculDecalage as dec
import GenerationSignal as GS
import Fenetrage as fen
import Calcul_Epsilon

class VerifConversion:
    def __init__(self,signalAB=None,signalBA=None, Dt_mesure=None,echantillonnage=1e-10):
        if signalAB is None:
            signalAB = []
        if signalBA is None:
            signalBA = []
        if Dt_mesure is None:
            Dt_mesure= 100e-9
                
        self.signalAB= signalAB
        self.signalBA= signalBA
        self.Dt_mesure= Dt_mesure 
        self.echantillonnage= echantillonnage

      
    def Ecart_initial(self):

        FenetreE = fen.Kaiser(self.signalAB)
        FenetreR = fen.Kaiser(self.signalBA)
        signalApodiseE = FenetreE.signalApodise()
        signalApodiseR = FenetreR.signalApodise()
        DEC_i = dec.CalculDecalage(signalApodiseE, signalApodiseR)
        Delta_T_i = DEC_i.DeltaT(self.echantillonnage,signalApodiseE ,signalApodiseR)

        return self.Dt_mesure -Delta_T_i

    def Ecart_avec_Conversion(self):
       

        CAMAB = dec.ConversionAvecModulation(self.signalAB,16)
        CAMBA = dec.ConversionAvecModulation(self.signalBA,16)
        signalConvertiE = CAMAB.ConversionAvecModulation()
        signalConvertiR = CAMBA.ConversionAvecModulation()

        FenetreConvE = fen.Kaiser(signalConvertiE)
        FenetreConvR = fen.Kaiser(signalConvertiR)

        signalApodiseConvE = FenetreConvE.signalApodise()
        signalApodiseConvR = FenetreConvR.signalApodise()
        
        DEC2 = dec.CalculDecalage(signalApodiseConvE, signalApodiseConvR)
        Delta_T2 = DEC2.DeltaT(self.echantillonnage, signalApodiseConvE, signalApodiseConvR)
        return self.Dt_mesure -Delta_T2

if __name__ == '__main__':

## Signaux à traiter

    S =  GS.signalGeneration()
    S.allSignals()
    signalE = S.X[0]
    signalR = S.Y[0]
    Dt= 200e-9
    echanti = 1e-10

    Verif = VerifConversion(signalE,signalR,Dt,echanti)
    a = Verif.Ecart_initial
    print(a)

### Expected behavior

Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
La valeur réelle était -1.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)     
   à Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   à Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   à Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

### Actual behavior

Error

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
