### ISSUE TITLE
Exception: System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.       Parameter name: top

### ISSUE THREAD

**Issue by Achchutan-S** [PowerShell/PSReadLine#2909]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------   
Last 200 Keys:
 B a n k D e m o Space } Enter
 c d Space " c : \ U s e r s \ a s u s \ O n e D r i v e \ D e s k t o p \ J a v a Space 3 r d Space s e m \ s t a r p a t t e r n s " Enter        
 c d Space " c : \ U s e r s \ a s u s \ O n e D r i v e \ D e s k t o p \ J a v a Space 3 r d Space s e m \ s t a r p a t t e r n s \ " Space ; Space i f Space ( $ ? ) Space { Space j a v a c Space R e c t a n g l e . j a v a Space } Space ; Space i f Space ( $ ? ) Space { Space j a v a Space R e c t a n g l e Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.      
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo 
key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)    
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

[Java 3rd sem.zip](https://github.com/PowerShell/PSReadLine/files/7313287/Java.3rd.sem.zip)

Here is the environment which I work upon ,
and even after resolving all the errors in all the programs , I encountered such an exception
currently I worked my rectangle.java file which is present in the patters package (provided in the zip folder)

### Expected behavior

I expect that on running the code for beginners such as me , i would be happy if anyone resolves this issue so that i only get to see the output and not the exceptions that blow me off.
![Screenshot (136)](https://user-images.githubusercontent.com/81160697/136602124-9c29d894-25d9-4272-9a4a-e0ce9f6a0958.png)

### Actual behavior

I am noticing this exception happening for a while now since two days so I synced my git-hub and vs code right now.
I don't know what more info to provide , but the exception is killing me without letting me know where it came from.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
