### ISSUE TITLE
Invoke Console Editor to edit long command line

### ISSUE THREAD

**Issue by belotn** [PowerShell/PSReadLine#2915]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

As in ZSH or BASh, use the editor set in $EDITOR to edit long or complex command line

### Proposed technical implementation details (optional)

I used to add this jey handler in my powershell profile
https://gist.github.com/belotn/35a77afd4b2e5e9c96c90e5bb6d469eb

**Comment by lzybkr** [comment]
In vi mode, the binding for <kbd>v</kbd> in command mode does exactly this, or you can set your own custom binding, e.g. to bind <kbd>F4</kbd>:

```powershell
Set-PSReadLineKeyHandler -Key F4 -Function ViEditVisually
```

**Comment by belotn** [comment]
Thanks a lot.
