### ISSUE TITLE
clear screen after zoom-in

### ISSUE THREAD

**Issue by yasircoskun** [PowerShell/PSReadLine#2945]
### Prerequisites

- [x] Write a descriptive title.
- [ ] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [ ] Search the existing issues, especially the pinned issues.

### Exception report

```console
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 74 Keys:
 w m i c Enter
 Ctrl+l w m i c Space p r o c e s s Space g e t Space p i d Enter
 UpArrow Ctrl+Backspace p r o c e s s Ctrl+Alt+i d Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow Backspace Backspace Backspace Backspace Enter
 Ctrl+l Ctrl+` Ctrl+l UpArrow Enter
 Ctrl+l UpArrow UpArrow DownArrow Enter
 Ctrl+l UpArrow Enter
 Ctrl+l UpArrow Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -59.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![image](https://user-images.githubusercontent.com/83482221/140167188-63063987-4be7-40b5-9a9f-ef5ac22966c3.png)

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 209
BufferHeight: 52
```

### Steps to reproduce

i see an error message and report it.

reproduce step by step:
step 1: 'wmic process get'
output is too long and have multiple column
step 2: CTRL+l (clear screen)
step 3: zoom out with mause wheel
step 4: 'wmic process get'
step 5: zoom in with mause wheel
output still too long and complex
step 6: give up and clear screen with CTRL+l
last step: saw the error message

---

i checked all checkbox in 'Prerequisites' but i ignored.
i think this must optional. i wanna help to improve this application but i'm only user this is not my job.

this is so boring bro. if i want to help an opensource project i must more free.
This report form is aggravating. just an opinion don't hate me.

- Sayonara

### Expected behavior

just clear screen without error message

### Actual behavior

show the error message

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
