### ISSUE TITLE
me manda un error y no me deja compilar

### ISSUE THREAD

**Issue by milka06** [PowerShell/PSReadLine#2946]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
no me deja compilar el codigo y me manda muchos errores
```

### Screenshot

![image](https://user-images.githubusercontent.com/93690133/140239966-e87af470-da9d-4355-bcfd-a98d01c32a6b.png)
![Captura](https://user-images.githubusercontent.com/93690133/140240011-bbaed456-19e5-4831-bb9b-d7b601d942dc.PNG)

### Environment data

```console
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
```

### Steps to reproduce

Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

Prueba la nueva tecnología PowerShell multiplataforma https://aka.ms/pscore6

PS E:\Usuarios\Erandi\Escritorio\UNI\METODOLOGIA DE LA PROGRAMACION\EVALUACION 2\SWITCH>  
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 200 claves:
 e - p r e v i e w ' Space ' - X X : + S h o w C o d e D e t a i l s I n E x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ E r a n d i Ctrl+Alt+\ A p p D a t a Ctrl+Alt+\ R o a m i n g Ctrl+Alt+\ C o d e Ctrl+Alt+\ U s e r Ctrl+Alt+\ w o r k s p a c e S 
t o r a g e Ctrl+Alt+\ f 5 e 9 8 6 d 9 d 8 9 2 9 b d 2 1 3 e c 7 4 4 7 0 7 5 6 1 1 c 8 Ctrl+Alt+\ r e d h a t . j a v a Ctrl+Alt+\ j d t _ w s Ctrl+Alt+\ S W I T C

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: left
Valor actual -1.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String 
defaultColor)
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)     
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS E:\Usuarios\Erandi\Escritorio\UNI\METODOLOGIA DE LA PROGRAMACION\EVALUACION 2\SWITCH>
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 200 claves:
 l s I n E x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ E r a n d i Ctrl+Alt+\ A p p D a t a Ctrl+Alt+\ R o a m i n g Ctrl+Alt+\ C o d e Ctrl+Alt+\ U s e r Ctrl+Alt+\ w o r k s p a c e S t o r a g e Ctrl+Alt+\ f 5 e 9 8 6 d 9 d 8 9 2 9 b d 2 1 3 e c 7 4 4 7 0 7 5 6 1 1 c 8 Ctrl+Alt+\ r e d h a t . j a v a Ctrl+Alt+\ j d t _ w s Ctrl+Alt+\ S W I T C H _ 7 3 f a 5 7 e 2 Ctrl+Alt+\ b i n ' Space ' E j e r c i c i o 6 ' Space Enter

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: left
Valor actual -1.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String 
defaultColor)
   en Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)     
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS E:\Usuarios\Erandi\Escritorio\UNI\METODOLOGIA DE LA PROGRAMACION\EVALUACION 2\SWITCH>

### Expected behavior

no ejecuta

### Actual behavior

cuando se ejecuta

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
