### ISSUE TITLE
PS hanged after resizing window - i did not see anything (cursor, characters I enter, only black window)

### ISSUE THREAD

**Issue by mturczyn** [PowerShell/PSReadLine#2952]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 147 Keys:
 c d Space s o r Backspace Tab r e Tab Enter
 c d Space t r Tab Enter
 d i r Enter
 g i t Space d i f f Enter
 g i t Space c o m m i t Space - a m Space ' s m Backspace Backspace C o r r e c t i o n s Space a n d Space s m a l l Space c o d e Space i m p r o v e m e n t s . ' Enter
 g i t Space p u s h Enter
 i i Space * s l n Tab Enter
 d i r Enter
 ` ` i i Space . Enter
 g i t Space s t a t u s Enter
 ` n e w Backspace Backspace Backspace Backspace Backspace c l s Enter


Exception:
System.IO.IOException: Parametr jest niepoprawny.

   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.Console.SetCursorPosition(Int32 left, Int32 top)
   w Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   w Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   w Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   w Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![image](https://user-images.githubusercontent.com/11062920/140607334-639e21ab-304f-426a-8ad8-81fbfe809203.png)

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 144
BufferHeight: 3000
```

### Steps to reproduce

 No steps

### Expected behavior

No expected behavior

### Actual behavior

No actual behavior

**Comment by daxian-dbw** [comment]
@mturczyn  You were using a very old version of PSReadLine (2.0.0-beta2), and it's likely that the issue was fixed in a newer version.
Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
