### ISSUE TITLE
Black screen after using tui apps, but only when using Set-PSReadLineKeyHandler

### ISSUE THREAD

**Issue by AsafMah** [PowerShell/PSReadLine#2954]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6424271/140647038-d093d02d-0386-45cd-9422-1448d52fcaf8.gif)

### Environment data

```console
PS Version: 7.1.5
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

```powershell
#Install fzf (or any other tui app)

fzf # choose an item, it gets printed on the screen and the next prompt appears

Set-PSReadlineKeyHandler -Chord "Shift+Tab" -ScriptBlock {fzf} # Or any key
# Press the the key, select item
# Black screen, after pressing enter the next prompt appears, but the result is never printed

```

### Expected behavior

I expect the behavior when starting the app from the hotkey to be the same as when starting directly - 

When the app quits it prints its result and the next prompt appears.

### Actual behavior

When quitting the app the terminal is a black screen

If the app prints something, like the result in fzf, it never gets displayed.

If you try typing, the text appears on the middle without a prompt:
![image](https://user-images.githubusercontent.com/6424271/140647075-69bc160b-aa81-4d2f-ac7e-6ea94d4b2df4.png)

When pressing enter the prompt appears again, but the result never does.

**Comment by AsafMah** [comment]
I upgraded to 2.2.2:
```
get-module psreadline

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.2                 PSReadLine
```

And the issue still persists

**Comment by daxian-dbw** [comment]
> If you try typing, the text appears on the middle without a prompt:

This was fixed.

> I expect the behavior when starting the app from the hotkey to be the same as when starting directly -

It doesn't work that way. The output from executing the script block will be captured so `fzf` won't write to the console. I guess what you want is `Set-PSReadlineKeyHandler -Chord "Shift+Tab" -ScriptBlock { $s = fzf; [Microsoft.PowerShell.PSConsoleReadLine]::Insert($s) }`, so the selected item will be used as your input.

![Animation](https://user-images.githubusercontent.com/127450/155350423-5ec6b290-131b-4c4f-bd4c-bcaea6fdf233.gif)

**Comment by AsafMah** [comment]
Thanks!

For future reference, that's the full "search history command" I have now:

```pwsh
function fhv() {
    if (Get-Command Get-PSReadLineOption -ErrorAction SilentlyContinue) {
        $result = Get-Content (Get-PSReadLineOption).HistorySavePath | fzf --reverse --no-sort
    } else {
        $result = Get-History | ForEach-Object { $_.CommandLine } | fzf --reverse --no-sort
    }
    return $result
}

Set-PSReadlineKeyHandler -Chord "Ctrl+Shift+R" -ScriptBlock {$s = fhv; [Microsoft.PowerShell.PSConsoleReadLine]::DeletePreviousLines(); [Microsoft.PowerShell.PSConsoleReadLine]::Insert($s.Trim()) }
````
