### ISSUE TITLE
Set-PSReadLineOption: A parameter cannot be found that matches parameter name 'PredictionViewStyle'.

### ISSUE THREAD

**Issue by jeanga** [PowerShell/PSReadLine#2957]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Set-PSReadLineOption: A parameter cannot be found that matches parameter name 'PredictionViewStyle'.
```

### Screenshot

![image](https://user-images.githubusercontent.com/7120091/140820565-66ea9773-3725-498b-a026-16a3e0d875ce.png)

### Environment data

```console
PS Version: 7.2.0
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 124
BufferHeight: 30
```

### Steps to reproduce

Installed PS 7.2.0 released today,
Set-PSReadLineOption does not have the PredictionViewStyle option anymore :-(

### Expected behavior

The nice and shiny ListView for predictions!

### Actual behavior

Sad and sorry old predictions... :'(

**Comment by jeanga** [comment]
Sorry, for some reason, the PS upgrade "downgraded" me to 2.1.0.... So sorry...

**Comment by daxian-dbw** [comment]
The 2.2.0 version of PSReadLine will reach GA in January. We are working on stability issues and bug fixes.

**Comment by daniel-liuzzi** [comment]
FYI, `2.2.0-beta4` works just fine.
