### ISSUE TITLE
Error message in terminal 

### ISSUE THREAD

**Issue by Hayat-kashgari** [PowerShell/PSReadLine#2978]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

N/A

### Environment data

```console
"PS Version: $($PSVersionTable.PSVersion)"
"PS HostName: $hostName"
"PSReadLine Version: $v"
"PSReadLine EditMode: $((Get-PSReadLineOption).EditMode)"  
"OS: $os"
"BufferWidth: $([console]::BufferWidth)"
"BufferHeight: $([console]::BufferHeight)"
```

### Steps to reproduce

count = 0
total = 0
average = 0 

while True:
    user_value = input("Enter number: ")
    if user_value == "done":
        break
    try:
        value = float(user_value)
    except:
        print("error, please enter a number")
        #continoue returns loop to top
        continue
    count = count + 1
    total = total + value
    average = total/count
print("Count:", count, "\nTotal:", total, "\nAverage:", average)

### Expected behavior

Write a program which repeatedly reads numbers until the user enters “done”. Once “done” is entered, print out the total, count, and average of the numbers. If the user enters anything other than a number, detect their mistake using try and except and print an error message and skip to the next number.

### Actual behavior

The excecated and gave results followed by the error message occurs after

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
