### ISSUE TITLE
Predictive Intellisense should pick up history changes from other prompts

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSReadLine#2979]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

Currently, if you set a shared history file, and you run a command in one pwsh instance, the command is added to the history file, but the command does not show up in predictive intellisense for the other instance.
![image](https://user-images.githubusercontent.com/15258962/140955231-e15af9c6-c032-4dfd-987a-f5ab8013ca46.png)

### Proposed technical implementation details (optional)

FIlesystem watcher on the history file that when it is changed, refresh the history (or clear the cache)

**Comment by MarkDomansky** [comment]
What is your HistorySaveStyle set to?
``` get-psreadlineoption | select historysavestyle ```

**Comment by StevenBucher98** [comment]
Closing since we currently support this scenario with predictors, feel free to reopen or submit new issue if there is a case not covered with current release! Thanks!
