### ISSUE TITLE
ArgumentException is thrown when current directory is several nodes deep

### ISSUE THREAD

**Issue by matzi4** [PowerShell/PSReadLine#298]
Steps to reproduce the exception:
- Open powershell either via run or by entering powershell in Windows Explorers address bar, error occurs in both cases
- Navigate to directory several nodes deep (see example path)
- Start typing few chars
- Attach window to fill half the screen
- Delete command just typed

The exception will occur when there is only one character left.

The error is reproducable using the following path: C:\Temp\test\test\test\test\test\test\test\test\test\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

The original directory I was in was only eight levels deep, however the directory names were longer.

OS: Windows 10 Home x64 Build 10240

![ps_bug2](https://cloud.githubusercontent.com/assets/15522607/10864241/1f3c5654-7fe8-11e5-8d52-3941fa8c9efc.PNG)

**Comment by lzybkr** [comment]
Dupe of #292.
