### ISSUE TITLE
Double-cell characters that get wrapped to the next line not removed from the screen when deleting

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PSReadLine#2984]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
No exception.
```

### Screenshot

![Animation](https://user-images.githubusercontent.com/127450/140980069-2b1f1460-e591-4eea-930d-abc98b072685.gif)

![Animation](https://user-images.githubusercontent.com/127450/140980304-d649360a-1111-4051-88e5-9731b0374cc4.gif)

### Environment data

```console
PS Version: 7.2.0-rc.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 91
BufferHeight: 25
```

### Steps to reproduce

1. Make sure the double-cell character wraps to the next line. It means that there is 1 cell buffer left on the current line for the double-cell character, so that character will be rendered to the next line.
2. Start to delete characters, from the end, or from the middle of the line.
3. You will see the double-cell character left behinds even though it's already removed from the buffer.

The GIF's in the screenshot section above are 2 examples.

### Expected behavior

Deletion works as expected to remove the character from screen.

### Actual behavior

The double-cell characters are left on screen, even though the characters were already removed from the text buffer.

**Comment by daxian-dbw** [comment]
The root cause of this issue is how we calculate the physical line count and the length of the last physical line for a logical line ([see code here](https://github.com/PowerShell/PSReadLine/blob/e02b0da57a2bf1b4a27f9e2fad2017480dff7af5/PSReadLine/Render.cs#L474-L514)). The `columns` is the total buffer cells of the logical line ([see code here](https://github.com/PowerShell/PSReadLine/blob/e02b0da57a2bf1b4a27f9e2fad2017480dff7af5/PSReadLine/Render.cs#L147-L149)), but it doesn't count into the possibility of the word warping for a double-cell character, which will make the logical line take up more cells than the calculated sum. This causes the line clearing to not work correctly in this case.

**Comment by iSazonov** [comment]
Intersting, it seems pwsh has such wrapper too. Makes sense to have the code duplicate? I remember we fixed issues in pwsh wrapper code too. Maybe has one well-tested?

**Comment by daxian-dbw** [comment]
I think the "wrapper" code you refer to is for word wrapping. It's different, here is the character wrapping that is done by the terminal/console, not the word wrapping.

**Comment by iSazonov** [comment]
Isn't this based on the "same" helper method to calculate cell width?

**Comment by daxian-dbw** [comment]
I don't know, never really looked at the word wrapping code in PS :)

**Comment by iSazonov** [comment]
It doesn't cover all cases (use a workaround for simplicity). I think it could be good request for new API in .Net Runtime.
