### ISSUE TITLE
psreadline option maxhistory bug

### ISSUE THREAD

**Issue by Sukiyakijango** [PowerShell/PSReadLine#300]
Hi there, i tryed to set history to infinity by setting it to 0... that dosent work as i know now... but if you try to set it back to some int32 value,..., psrealine bugs-out.
thanks for the great module help a lot to unify workflows between *nix/windows worlds

---

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 108 Keys:
 UpArrow UpArrow DownArrow Backspace 1 0 0 0 0 0 0 0 0 0 Enter UpArrow LeftArrow Delete Enter UpArrow LeftArrow LeftArro
w LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Delete 3 Enter UpArrow LeftArrow LeftArrow LeftA
rrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Delete 2 Enter UpArrow LeftArrow B
ackspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Spacebar Enter UpArrow s e t -
P S R e a d l i n e O p t i o n Spacebar - M a x i m u m H i s t o r y C o u n t Spacebar 0 LeftArrow 2 0 Enter

Exception:
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei PSConsoleUtilities.HistoryQueue`1.Dequeue()
   bei PSConsoleUtilities.HistoryQueue`1.Enqueue(T item)
   bei PSConsoleUtilities.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean
readingHistoryFile, Boolean fromDifferentSession)
   bei PSConsoleUtilities.PSConsoleReadLine.InputLoop()

**Comment by daxian-dbw** [comment]
This doesn't repro with the 2.0.0-beta6, so close this issue.
