### ISSUE TITLE
PowerShell 7.2.0 on Ubuntu ARM Exception

### ISSUE THREAD

**Issue by robertstrom** [PowerShell/PSReadLine#3017]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0
OS: Linux 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:54:21 UTC 2021
BufferWidth: 130
BufferHeight: 35

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/3240205/141406193-43c9c429-0eb8-4352-b9d9-a370a823cf9c.png)


### Environment data

```console
I tried running the script above but there are no results. The exception just keeps repeating and PowerShell v7.2.0 is completely unusable.

After I remove PowerSHell v7.2.0 and reinstall PowerShell v7.1.4 everything is functional again.
```

### Steps to reproduce

Install PowerShell v7.2.0 on Ubuntu 20.10 running as a Virtual Machine on ESXi Raspberry Pi

```
rstrom@powercli:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
rstrom@powercli:~$
rstrom@powercli:~$ 
```

Script used to install PowerShell (script based on links shown in script comments below. After installing PowerShell v7.2.0 all I did was type pwsh and press ENTER and the error / exception happens. I have deleted the PowerShell directory ( sudo rm -rf /opt/microsoft/powershell ) and reinstalled at least 3 times between yesterday and today. Eash install results in the same error.

```
### Download and install PowerShell on Linux ARM
### As per Microsoft you need to install the Linux Binaries on ARM
### https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#installation---binary-archives
##
## Alternate ways to install PowerShell on Linux
## https://docs.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.2

# Delete previous instance of PowerShell
sudo rm -rf ./powershell-*.tar.gz*
sudo unlink /usr/bin/pwsh
sudo rm -rf /opt/microsoft/powershell

# Read the version number to download
echo "Please enter the PowerShell version to download"
read PSVersion

# Download the powershell '.tar.gz' archive
wget https://github.com/PowerShell/PowerShell/releases/download/v$PSVersion/powershell-$PSVersion-linux-arm64.tar.gz

# Create the target folder where powershell will be placed
sudo mkdir -p /opt/microsoft/powershell/7

# Expand powershell to the target folder
sudo tar zxf ./powershell-$PSVersion-linux-arm64.tar.gz -C /opt/microsoft/powershell/7

# Set execute permissions
sudo chmod +x /opt/microsoft/powershell/7/pwsh

# Create the symbolic link that points to pwsh
sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

# Cleanup / Delete the downloaded tar.gz file
sudo rm -rf ./powershell-*.tar.gz*
```

### Expected behavior

Get a PowerShell prompt and have a functional version of PowerShell

### Actual behavior

PowerShell exception is displayed on screen and Power is stopped. No commands can be run. The only thing to do is type exist and hit ENTER.

**Comment by iSazonov** [comment]
Please update to latest Beta4 version.

**Comment by daxian-dbw** [comment]
This issue was fixed in 2.2.0-beta3 version of PSReadLine. You can fix this by upgrading to the latest [2.2.0-beta4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.0-beta4). Instructions for doing so:
1. stop all instances of `pwsh`.
2. from `cmd.exe` run: `pwsh -noprofile -command "Install-Module PSReadLine -AllowPrerelease -Force"`

--------

If you want to remove that beta version of PSReadLine and use the 2.1.0 version of PSReadLine that's shipped with PowerShell 7.2, you can:
1. run `pwsh -noprofile -noninteractive` to start `pwsh` without loading PSReadLine
2. run `Uninstall-Module -Name PSReadLine -RequiredVersion <2.2.0-beta1 or 2.2.0-beta2> -AllowPrerelease` to remove the module. Or, you can manually remove that module folder.

**Comment by robertstrom** [comment]
> This issue was fixed in 2.2.0-beta3 version of PSReadLine. You can fix this by upgrading to the latest [2.2.0-beta4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.0-beta4). Instructions for doing so:
> 
> 1. stop all instances of `pwsh`.
> 2. from `cmd.exe` run: `pwsh -noprofile -command "Install-Module PSReadLine -AllowPrerelease -Force"`
> 
> If you want to remove that beta version of PSReadLine and use the 2.1.0 version of PSReadLine that's shipped with PowerShell 7.2, you can:
> 
> 1. run `pwsh -noprofile -noninteractive` to start `pwsh` without loading PSReadLine
> 2. run `Uninstall-Module -Name PSReadLine -RequiredVersion <2.2.0-beta1 or 2.2.0-beta2> -AllowPrerelease` to remove the module. Or, you can manually remove that module folder.

**Run _cmd.exe_? This is PowerShell running on Linux ... no cmd.exe**

I will try the other pieces of the solution and see if they resolve the problem. Right now . PS v 7.1.5 is working fine on the Ubuntu system.

**Comment by daxian-dbw** [comment]
On Linux or macOS, from `bash` or whatever default shell instead of `cmd.exe`.

**Comment by robertstrom** [comment]
> On Linux or macOS, from `bash` or whatever default shell instead of `cmd.exe`.

I ran

`pwsh -noprofile -command "Install-Module PSReadLine -AllowPrerelease -Force"`

and I can now launch pwsh and get a functioning PowerShell v7.2.0 prompt on the Ubuntu system.

Thanks very much!
