### ISSUE TITLE
Complete function not working when pressing tab

### ISSUE THREAD

**Issue by KarlGNassar** [PowerShell/PSReadLine#3035]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1320
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.0-beta4
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 65
BufferHeight: 16
```

### Steps to reproduce

I have the version `2.2.0-beta4` of PSReadLine and these are the options I added on my `$PROFILE`

```
Import-Module PSReadLine

Set-PSReadlineKeyHandler -Key Tab -Function Complete

Set-PSReadLineOption -HistorySearchCursorMovesToEnd
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward

Set-PSReadLineOption -ShowToolTips
Set-PSReadLineOption -PredictionSource History
```

### Expected behavior

Autocompletes the suggestion.

### Actual behavior

When pressing Tab, PSReadLine makes a beeping sound and then clears the suggestion without actually completing it.
Special case: if I am trying to cd into a directory and press Tab, the beeping sound remains but I get `.\` as an output.

**Comment by daxian-dbw** [comment]
The function `Complete` is for tab completion, not for accepting a suggestion. Use `RightArrow` to accept a predictive suggestion. Or you can bind a custom key to the function `AcceptSuggestion` to accept a predictive suggestion.
