### ISSUE TITLE
Exception on opening Powershell within Windows Terminal

### ISSUE THREAD

**Issue by tbergstedt** [PowerShell/PSReadLine#3040]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Exception

System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

N/A (empty window)

### Environment data

```console
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.18363
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

Starting Windows Terminal with Powershell 7 as default, just after upgrading to 7.2.0.

### Expected behavior

A Powershell 7 host within Windows Terminal

### Actual behavior

Exception as above, keeps repeating.

**Comment by brunomartinspro** [comment]
Having the same issue

**Comment by brunomartinspro** [comment]
The fix on https://www.hanselman.com/blog/powershell-720-could-not-load-type-systemmanagementautomationsubsystempredictionresult enables the console again

Run in Admin:
`Install-Module PSReadLine -AllowPrerelease -Force`
