### ISSUE TITLE
Feature - inline history search 

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PSReadLine#306]
Whilst I'm starting to make use and learn about how to use PSReadLine to the best of its ability I'm finding myself whilst in the Shell repeating similar tasks that may be 10+ commands beforehand.

It would be useful if possible to start typing the command and then press a key combination (perhaps Ctrl+Alt+Space) that returns just the matching items from the history like Ctrl+Space does for Tab Completions

I'm sure this is something that either already has been asked for (and I just dont know about it) or could be quickly put together. I intend to spend some time having a look to see if this is something that I could do if not already implemented (any suggestions would be welcomed)

**Comment by rkeithhill** [comment]
Put the following in your profile:

```
Set-PSReadlineKeyHandler -Chord UpArrow    -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Chord DownArrow  -Function HistorySearchForward
```

Starting typing the command and press the UpArrow (multiple times to cycle backwards).  You can also use Ctrl+r to search for text anywhere in a previous command line (not just the beginning).  Press Ctrl+r to cycle backwards through matches.  If you go to far, press Ctrl+s to cycle forward.

**Comment by lzybkr** [comment]
I think Keith's feedback should address your concerns.

PSReadline still doesn't implement the old F7 behavior which is also similar to what you're asking for, but there are issue on that already (#122 and #128).
