### ISSUE TITLE
SamplePSReadlineProfile.ps1 - Microsoft.PowerShell.PSConsoleReadLine could not be found exception

### ISSUE THREAD

**Issue by atus** [PowerShell/PSReadLine#307]
`Microsoft.PowerShell.PSConsoleReadLine` should be replaced with `PSConsoleUtilities.PSConsoleReadLine`
I have tested this for F7

**Comment by lzybkr** [comment]
The current sources are consistent and correct, but the released binaries published on the PowerShell gallery and on the GitHub releases page are using the old namespace.  I need to publish a new release so the namespace matches what was released in Win10.
