### ISSUE TITLE
Allow to remove the selected history entry in Prediction ListView

### ISSUE THREAD

**Issue by Ergamon** [PowerShell/PSReadLine#3070]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

I am now working for a few days with 2.2.0 beta4 and this new prediction style is a huge productivity booster.

If you are working for long time with PowerShell there is also a lot of garbage in your history. I know you can clear it completly, but I would like to conveniently remove single entries. 

I know I can start some manipulation on the history file, but I would prefer to be able to do this while the popup is open.

### Proposed technical implementation details (optional)

While the ListView is active, allow a hotkey to be pressed for deleting the selected entry.

Not sure if the DELETE character is a good choice or maybe SHIFT-DELETE

**Comment by daxian-dbw** [comment]
Close as a dup of #1778
