### ISSUE TITLE
Support Completions as a source for Predictions

### ISSUE THREAD

**Issue by rashil2000** [PowerShell/PSReadLine#3072]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

When the autosuggestions feature was first introduced by Fish shell, the suggestions appeared from both the _history_ and the _completions_, in that order (meaning if no history item is found, suggest the tab-completion candidate).

Zsh supports configuring autosuggestion strategies and their lookup order:

![image](https://user-images.githubusercontent.com/46838874/143836499-b7393eef-2d20-4462-9760-6c4dc196b4f2.png)

The Clink framework also supports the same configurations now:

![image](https://user-images.githubusercontent.com/46838874/143836890-e00f9f27-b33b-4427-91ac-faf6914d37a3.png)

I feel this is a major feature missing in PSReadline.

### Proposed technical implementation details (optional)

Add the option `-PredictionSource Completions`.

Or to modify the order in which suggestions are looked up, `-PredictionSource` should accept an array - `Completions,History`.

The suggestion in Completion strategy will be the first item that appears on pressing Tab.

**Comment by theJasonHelmick** [comment]
Thanks for the input and ideas @rashil2000.  Today, you can have some control over this with Set-PSReadLineOption -PredictionSource History, Plugin, History&Plugin, None.  Currently, history is displayed first, then additional predictors.  We are looking at how to best manage multiple predictors going forward and I appreciate your feedback.  In ListView, we currently support 10 entries from history and predictors. The idea was that history would get the first three slots (if needed) and the ret of the predictors would share the remaining - with the last predictor used being displayed first.  

Now, as we move forward and start to have multiple predictors to work with, we are examining how to best serve predictions to the user.  This is a great issue to continue the conversation.

**Comment by rashil2000** [comment]
My primary motivation for this opening this feature request was that the technical infrastructure for "Completions as a prediction source" are already in place in PSReadline - we use them in the form of tab-completions. I'm not well-versed with C# - but I'm under the impression that we would just need to expose these completion candidates to the prediction API.

Regarding the order of serving predictions - I personally feel that completion sources should get a higher priority than plugins (i.e. the priority order being History & Completions & Plugins) - because:
- external plugins need to be explicitly installed in order for the Plugin source to be useful (I'm not aware of how many people use external plugins - and a search on PowerShell Gallery only returns [one result](https://www.powershellgallery.com/packages?q=predictor)).
- it would match the default experience on other shells (Fish, Zsh, Cmd) and will work out-of-the-box

I will also add that I had not taken the ListView feature into account when opening the issue (and hence I was thinking of only one suggestion/prediction at a time).

**Comment by Luttik** [comment]
I'd love this... @theJasonHelmick I couldn't find any documentation on how to make a prediction-source plugin... If you can point us to that maybe we can create a script that converts the autocompletion/suggestion functions into a plugin.

**Comment by theJasonHelmick** [comment]
@Luttik - The docs for writing your own predictor are being worked on - I would think we should have those out in the next quarter.

**Comment by rashil2000** [comment]
While I support having good documentation for writing custom plugins, I strongly feel that this particular source (i.e. Completions) should be an in-built feature.

**Comment by daxian-dbw** [comment]
If needed, the completion-based prediction plugin can be shipped along with PowerShell.
Having it in PSReadLine has two drawbacks:
1. would need to duplicate the code that wraps synchronous calls to async calls, which already exists in PowerShell engine for handling prediction plugins.
2. would slow down the development and improvements of the completion-based prediction experience due to the risk of breaking something else in PSReadLine.

It would be better to have it evolve as a prediction plugin. Once it becomes stable and turns out to be widely used, we can consider having it shipped along with PowerShell, or even bring the code back to PSReadLine.

**Comment by hongwen000** [comment]
Waiting for the custom plugin document. I'm doing android development and willing to see the *adb* auto-completion based on device-side info (which is supported by fish shell).

**Comment by ThomasNieto** [comment]
Does [CompletionPredictor](https://github.com/PowerShell/CompletionPredictor) meet this request?

**Comment by rashil2000** [comment]
Yes, it does, and it’s awesome 🎉. 

However we might want to keep this issue open until:

> Once it becomes stable and turns out to be widely used, we can consider having it shipped along with PowerShell, or even bring the code back to PSReadLine.

**Comment by yume-chan** [comment]
I tried the CompletionPredictor package, it works for simple parameter and path completion, however, when the completer is more complex, like `Get-Help G|` or `git st|` (provided by posh-git), it almost always exceeds the 20ms timeout proposed by PowerShell (on my Ryzen 5600X they usually take 35~70ms), which makes it unusable.

**Comment by daxian-dbw** [comment]
> I tried the CompletionPredictor package, it works for simple parameter and path completion, however, when the completer is more complex, like Get-Help G| or git st| (provided by posh-git), it almost always exceeds the 20ms timeout proposed by PowerShell (on my Ryzen 5600X they usually take 35~70ms), which makes it unusable.

This is the main reason why completion is not used as a built-in source for prediction. Argument completions tend to be quite slow, especially those for native commands because they usually need to spin up an executable.

Improvements to the `CompletionPredictor` are possible regarding this limitation, by sharing completion results across multiple 
subsequent prediction requests.

I will close this issue, and for issues/suggestions/discussions, please make them happen in https://github.com/PowerShell/CompletionPredictor.
