### ISSUE TITLE
WORKINPLUG

### ISSUE THREAD

**Issue by workitinplug** [PowerShell/PSReadLine#3095]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

New OS

### Proposed technical implementation details (optional)

New Machinecodelanguage

**Comment by Pleijjeri** [comment]
*.*workitin*.*workinplugitin.*.plugitin.*.-/plugged\INside-THROUGH_-_OUTPUTTOINPUT-.PLUGIT<->IN....*.*....POWER\ON STandBy

**Comment by Pleijjeri** [comment]
And There ITIoAIIiS
