### ISSUE TITLE
Exception: System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by 6DAVEROO9** [PowerShell/PSReadLine#310]
## Complete error section is:

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Script that was being worked on is:

PowerShell.exe -windowstyle hidden 
{$msgtxt = "This will only take a moment. Click `"OK`" to begin."

 $output = [System.Windows.Forms.MessageBox](:Show%28$msgtxt,)::Show($msgtxt, "Status", 1) #0-OK 1-OK/Cancel 2-Abort/Retry/Ignore 3-Yes/No/Cancel 4-Yes/No 5-Retry/Cancel
 if($output -eq "OK")
  {$clkspd = Get-WmiObject Win32_Processor | Select-Object -ExpandProperty MaxClockSpeed
   $clkspd = $clkspd/1000
   $totmem = Get-WMIObject Win32_PhysicalMemory | Measure-Object -Property capacity -Sum | Select-Object -ExpandProperty Sum
   $totmem = $totmem/1024/1024/1024
   $fremem = Get-WmiObject Win32_OperatingSystem | select FreePhysicalMemory
   $fremem = $fremem/1024/1024 | % {$_.ToString("#.##")}
   $msgtxt = "Computer Name: "
   $msgtxt += $(Get-WmiObject Win32_Computersystem).name
   $msgtxt += "`n`n"
   $msgtxt += $(Get-WmiObject Win32_BIOS).name
   $msgtxt += "`n`n"
   $msgtxt += "Processor: "
   $msgtxt += Get-WmiObject Win32_Processor | Select-Object -ExpandProperty Name
   $msgtxt += "$clkspd MHz `n`n"
   $msgtxt += "Memory Manufacturer (one name per slot): "
   $msgtxt += Get-WmiObject CIM_PhysicalMemory | Select-Object -ExpandProperty Manufacturer
   $msgtxt += "`n`n"
   $msgtxt += "Total Physical Memory: $totmem GB   Total Free Memory: $fremem GB"
   $msgtxt +=

  }
}

Section from first instance of $clkspd to the second instance of $fremem is the one I was working on at the time of the crash. Crash was preceded by the error:
Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Division'. Internet search mentioned initialization of variable that is its own operator. Tried by making the all the variables in question = @(), as well as = 0.0. It was after returning to the above script that the crash occurred.

**Comment by 6DAVEROO9** [comment]
A System Restore operation did not solve this issue.

**Comment by lzybkr** [comment]
This looks a lot like #158, I'll close it as a dupe, you can reactivate it if I'm wrong, or if the eventual fix doesn't address your issue.
