### ISSUE TITLE
“Demo mode” for prediction 

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PSReadLine#3101]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

When someone is delivering a PowerShell demo, it would be nice to temporarily suppress prediction, to avoid completion text from distracting the audience, or possibly revealing arguments that contain personal information.

Yet, it would be nice if prediction could still build within the current session to minimally assist with the demo delivery.

### Proposed technical implementation details (optional)

A simple on/off switch implemented as a property, where prediction would be based only on text from the current session and not past history.

**Comment by daxian-dbw** [comment]
I think you can achieve this by `set-psreadLineOption -PredictionSource None` before the demo, and restore the original setting after demo.
