### ISSUE TITLE
PSReadline module doesn't load when SSH-ing to PowerShell Host from Android

### ISSUE THREAD

**Issue by cydhaselton** [PowerShell/PSReadLine#311]
I'm running [PowerShellServer](http://www.powershellserver.com/) on a Windows 8.1 box with the 'run profiles' option enabled (runs profile script on connection).  The profile script imports and configures PSReadline as follows:

Import-Module PSReadline
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
Set-PSReadlineOption -HistorySavePath C:\Users\username\Documents\WindowsPowerShell\history.txt

When I SSH to PowerShell, the PSReadline module is imported, but not completely configured.  I can't access previous session history using the up or down arrows, but the HistorySavePath is pointing to the correct location and the HistorySaveStyle option is set to "Save Incrementally"

I have opened a ticket with nsoftware support (makers of PowerShellServer) but it would help troubleshooting if I could find out if there any Host dependencies for PSReadline.

**Comment by lzybkr** [comment]
This is likely related to #158 - so closing as a dupe.
