### ISSUE TITLE
Shift+End key combination doesn't work in WSL prompt

### ISSUE THREAD

**Issue by HasEveryUsernameBeenTaken** [PowerShell/PSReadLine#3126]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.2.1
PS HostName: ConsoleHost
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: Linux Porre-Ubuntu 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

1. Open a Windows Subsystem for Linux window.  I was able to produce this in the standard console window ("debian.exe" and "ubuntu.exe") and Windows Terminal ("WindowsTerminal.exe" and a GNU/Linux profile)
2. Install PowerShell via the instructions in https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2
3. Open PowerShell via "pwsh"
3. Press and hold the Right Shift key
4. Press the End key

I did verify that the key combination is bound via the following:
```
$ Get-PSReadLineKeyHandler -Chord 'Shift+End'

Selection functions
===================

Key       Function   Description
---       --------   -----------
Shift+End SelectLine Adjust the current selection to include from the cursor to the end of the line
```

Just in case this helps, here are the results of "showkey -a" for WSL Ubuntu for my End, Shift+End, CTRL+End, and ALT+End:

```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[[F     27 0033 0x1b
         91 0133 0x5b
         70 0106 0x46
^[[1;2F          27 0033 0x1b
         91 0133 0x5b
         49 0061 0x31
         59 0073 0x3b
         50 0062 0x32
         70 0106 0x46
^[[1;5F          27 0033 0x1b
         91 0133 0x5b
         49 0061 0x31
         59 0073 0x3b
         53 0065 0x35
         70 0106 0x46
^[[1;3F          27 0033 0x1b
         91 0133 0x5b
         49 0061 0x31
         59 0073 0x3b
         51 0063 0x33
         70 0106 0x46

```

### Expected behavior

The key combination should select from the currently focused cursor position to the end of the line.

Please note that the Shift+Home key combination seems to work correctly.

### Actual behavior

Pressing the shift key and the end key inserts ";2F" in a console window and "^[1;2F" in Windows Terminal.

**Comment by daxian-dbw** [comment]
`Console.ReadKey` returns unexpected `ConsoleKeyInfo` when pressing `Shift+End` in WSL. Opened the issue in .NET repository: https://github.com/dotnet/runtime/issues/63644.
