### ISSUE TITLE
PredictionViewStyle parameter cannot be found

### ISSUE THREAD

**Issue by LuccaMS** [PowerShell/PSReadLine#3137]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Set-PSReadLineOption: A parameter cannot be found that matches parameter name 'PredictionViewStyle'.
```

### Screenshot

![image](https://user-images.githubusercontent.com/64712028/148317235-e77503ab-7448-4d7b-8ed9-c7f292370796.png)

### Environment data

```console
PS Version: 7.2.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 132
BufferHeight: 22
```

### Steps to reproduce

I Installed the PSReadLine with that command 
`Install-Module -Name PSReadLine -AllowPrerelease -Scope CurrentUser -Force -SkipPublisherCheck`
and then
` Set-PSReadLineOption -PredictionSource History` that part works without problems
and then that line 
`Set-PSReadLineOption -PredictionViewStyle ListView` which is the line that causes the error.

### Expected behavior

To change the style of view of PSReadLine showing a list of commands that were used before.

### Actual behavior

Gives me `Set-PSReadLineOption: A parameter cannot be found that matches parameter name 'PredictionViewStyle'.` error.

**Comment by daxian-dbw** [comment]
The `PredictionViewStyle` parameter was introduced in PSReadLine 2.2.0-beta1, while you are using 2.1.0. Please upgrade to the latest 2.2.0 preview version `2.2.0-beta4`.

**Comment by LuccaMS** [comment]
Hum, i don't know why, but when i use get-Module PSReadline it says that i'm using the version 2.1.0 but when i use Get-InstalledModule it says that i'm using the right version, 2.2.0-beta4

**Comment by daxian-dbw** [comment]
You might have installed both versions at different module paths. Try `Get-Module PSReadLine -list` to see all PSReadLine modules in your module paths. Make sure the module path where `2.2.0-beta4` got installed comes before the module path where `2.1.0` got installed to in `$env:PSModulePath`.
