### ISSUE TITLE
Any way to modify vi cmd mode bindings?

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PSReadLine#314]
First: @srdubya and @lzybkr : Woooooooo! Vi mode! Thank you!

 I'm interested in changing what the 'v' key does when in command mode. I poked around, but didn't see a way--am I correct that there is currently no way to change cmd-mode bindings?

If not, is there a plan or proposed to design to add such capability?

Thanks!

**Comment by jazzdelightsme** [comment]
I took a look at the code and I think I could take a crack at it. My plan is for the PSReadLineKeyHandler cmdlets, if the EditMode is Vi, then add a new dynamic parameter "-ViMode [Insert|Command]". Depending on the value of that parameter, I'll temporarily swap the dispatch/chord tables.

**Comment by lzybkr** [comment]
I see no need for a dynamic parameter.  Maybe throw an error if not in vi mode, but dynamic parameters are annoying.

**Comment by jazzdelightsme** [comment]
Okay, that sounds good. Thanks!

**Comment by jazzdelightsme** [comment]
Fixed by PR: https://github.com/PowerShell/PSReadLine/pull/9

Thanks!
