### ISSUE TITLE
Is there some trick to run unit tests?

### ISSUE THREAD

**Issue by idealist1508** [PowerShell/PSReadLine#316]
If I run unit tests in Visual Studio, only 14 are passed and  other 134 are failed. 
They all are failed with the same exception:

```
Result StackTrace:  
bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   bei System.Console.Clear()
   bei UnitTestPSReadLine.UnitTest.TestSetup(KeyMode keyMode, KeyHandler[] keyHandlers) in Z:\github\sp\PSReadLine\UnitTestPSReadLine\UnitTestReadLine.cs:Zeile 610.
   bei UnitTestPSReadLine.UnitTest.ViTestSearchHistory() in Z:\github\sp\PSReadLine\UnitTestPSReadLine\HistoryTest.VI.cs:Zeile 56.
Result Message: 
Test method UnitTestPSReadLine.UnitTest.ViTestSearchHistory threw exception: 
System.IO.IOException: Das Handle ist ungültig.
```

Do you have some tip for me?
Thanks.

**Comment by lzybkr** [comment]
I'm in the process of fixing.  The tests all worked for a long time in VS2013, but something changed in the unit test framework.  I'm basically introducing a mocking layer for the use of console apis, and the unit test implement the mock interface without actually using the console at all.  All the tests are working in VS2013 right now (changes were pushed last night), but there is one remaining issue with VS2015 I need to fix.

**Comment by lzybkr** [comment]
Tests should all pass now in both VS2013 and VS2015 with this commit accc20dfe.
