### ISSUE TITLE
ViMode - When invoking PsReadline.Delete(), deleted text isnt memorize in clipboard and there's no api function to add it 

### ISSUE THREAD

**Issue by belotn** [PowerShell/PSReadLine#3160]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.17763.1490
PS HostName: ConsoleHost
PSReadLine Version: 2.2.0-beta4
PSReadLine EditMode: Vi
OS: 10.0.17763.1630 (WinBuild.160101.0800)
BufferWidth: 97
BufferHeight: 1000
```

### Steps to reproduce

Hello;

I use a custom function to do some text manipulation in VIMODE. In the API, it seems there is no function to add cleared text in clipboard to reinsert them with <p> or <P>

### Expected behavior

In vimode, Either deleted text is added in clipboard, or there s a function in the API to add deleted text to clipbord

### Actual behavior

Deleted text is lost except using system clipboard

**Comment by springcomp** [comment]
@belotn What about the _[PasteBefore](https://docs.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-7.2#pasteafter)_ and _PasteAfter_ commands?

```pwsh
Set-PSReadLineKeyHandler -Key 'q' -ViMode Command -ScriptBlock {
    [Microsoft.PowerShell.PSConsoleReadLine]::PasteAfter();
}
Set-PSReadLineKeyHandler -Key 'Q' -ViMode Command -ScriptBlock {
    [Microsoft.PowerShell.PSConsoleReadLine]::PasteBefore();
}
```

**Comment by belotn** [comment]
My apologies, i wasn't specific enought. When using,
```
		[Microsoft.PowerShell.PSConsoleReadLine]::Delete($StartChar,`
					$EndChar - $StartChar)

```
deleted text isn't memorize in Vi register, and i didn't found any function in help, that allow to add text in the register

**Comment by springcomp** [comment]
@belotn 

That is because `Delete` is not used at all in Vi mode. You will need to use any of the `ViDeleteXXX` variants.

It maybe tricky to replicate exactly what you are trying to do, though. But I think you can calculate the relative positions of `$startChar` and `$endChar` from that of the cursor using `GetBufferState`. This would be good for single line buffers only though.

**Comment by belotn** [comment]
Ok, i'm trying to append key binding around ci ca ( https://github.com/belotn/PsReadLineVIExtension )
I'll try to rewrite using ViDeleteXXX and ViReplaceXXX
