### ISSUE TITLE
msdos disk.d80

### ISSUE THREAD

**Issue by Polizzotto** [PowerShell/PSReadLine#3162]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
file
>>  Cannot open extract file
>>  Close error on extract file
>>   0^CE^C  ^Ð 5^B^H 5^B^TREMOVELIBRARYRECORDS^KWIDTHOFLINELibrary File:  No library file specified
>>  .LIBLibrary does not exist. Create?  Operations:  List file:   Cannot create list file.
>>  Cannot write library file
>>  ðý^A.OBJ CON NUL LPT1 AUX  Cannot nest response files.
>>      " "
>>  Cannot open response file.
>>   Ambiguous switch:
>>  Unrecognized switch:
>>      " "
>>  Invalid switch.
>>
>>    Microsoft Library Manager V1.02
>> (C) Copyright 1981 by Microsoft Inc.
>>
>>                                              



PS C:\Windows\system32> .\dwm.exe80 dup (?)

Cmdlet Where-Object nella posizione 1 della pipeline dei comandi
Specificare i valori per i seguenti parametri:
Property:
```

### Screenshot

![Immagine 2022-01-15 202611](https://user-images.githubusercontent.com/82771856/149635343-754df8f3-c89b-473c-8919-00c06bc9c18c.png)
![Immagine 2022-01-15 202611_](https://user-images.githubusercontent.com/82771856/149635417-482a5883-3da9-4499-9423-6aa7bc86bc91.png)

### Environment data

```console
pwsh 7.2 
windows 10 64 bit
```

### Steps to reproduce

>.ps1  (paste,il contenuto del file objet)

### Expected behavior

prevedibile, sistema ms dos 1 per commodore..

### Actual behavior

se incolli più volte i contenuti dei file del pacchetto "Microsoft MS-DOS 1.25 for Commodore CBM B Series" reperito sul sito  [winworld](https://winworldpc.com/download/c3a92827-0744-c3ac-11c3-a4c2a83d7054)
il dos su pwsh si ricompila quasi tutto.

**Comment by daxian-dbw** [comment]
Not sure what this issue is really about just based on the screenshot, but it doesn't seem to be related to PSReadLine.
If you are sure this is an PSReadLine issue, please be clear on what is the problem, the repro steps, and the environment data. Also, please file the issue in English, thanks.

**Comment by Polizzotto** [comment]
Salve,
aahahahahahahah

cordiali saluti

Il giorno mar 18 gen 2022 alle ore 18:25 Dongbo Wang <
***@***.***> ha scritto:
