### ISSUE TITLE
Tab completion for bash arguments will either convert forward slashes to backslashes, or insert backslashes, breaking pathing

### ISSUE THREAD

**Issue by Arlieth** [PowerShell/PSReadLine#3173]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![image](https://user-images.githubusercontent.com/13109234/150106946-1e2ac671-6e56-4e1c-9012-1b99ac2afb4a.png)

### Environment data

```console
PS Version: 5.1.19041.1320
PS HostName: ConsoleHost
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

1. Invoke bash and use tab-completion when calling a file name (of a shell script) as an argument.
2. Observe tab completion prepending .\ to the file name
3. Observe failure when attempting to run shell script

### Expected behavior

bash runs shell script invoked as an argument (either by not inserting new backslashes or by accepting forward slash to backslash conversions)

### Actual behavior

Bash returns an error of "No such file or directory".

**Comment by daxian-dbw** [comment]
PowerShell path completion normalizes path separators to backward slashes on Windows and forward slashes on Unix platforms, and that's a by-design behavior for PowerShell. For your case, you are calling bash on Windows, and thus see the backward slash as the path separator.

You can customize the completion behavior for the `bash.exe` native command by using `Register-ArgumentCompleter`. Here is [an example](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.2#example-3--register-a-custom-native-argument-completer) of using it to complete argument for `dotnet.exe`.
