### ISSUE TITLE
System.MissingMethodException (Error on VS code terminal)

### ISSUE THREAD

**Issue by gaurpiyush001** [PowerShell/PSReadLine#3182]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS B:\Nodejs\complete-node-bootcamp\4-natours\after-section-09> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.MissingMethodException: Method not found: 'System.TimeSpan System.DateTime.op_Subtraction(System.DateTime, System.DateTime)'.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![image](https://user-images.githubusercontent.com/67181265/151138287-c8198ff3-7d36-4306-a553-b5672687bddc.png)

### Environment data

```console
PS Version: 5.1.19041.1320
PS HostName:
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 154
BufferHeight: 37
```

### Steps to reproduce

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS B:\Nodejs\complete-node-bootcamp\4-natours\after-section-09> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

Exception:
System.MissingMethodException: Method not found: 'System.TimeSpan System.DateTime.op_Subtraction(System.DateTime, System.DateTime)'.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

### Expected behavior

Command Line is not working correctly

### Actual behavior

Exception:
System.MissingMethodException: Method not found: 'System.TimeSpan System.DateTime.op_Subtraction(System.DateTime, System.DateTime)'.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by gaurpiyush001** [comment]
I am not able to download NuGet package, please someone help me

**Comment by gaurpiyush001** [comment]
![image](https://user-images.githubusercontent.com/67181265/151164871-2176a58d-b014-45ed-be71-ac1e52290bd8.png)

**Comment by daxian-dbw** [comment]
Can you run `Get-PSRepository` and `Get-PackageProvider -ListAvailable` respectively and share the results here?

**Comment by gaurpiyush001** [comment]
![image](https://user-images.githubusercontent.com/67181265/151225990-0fa50946-d643-4f54-a20a-cdb83acd9102.png)

**Comment by gaurpiyush001** [comment]
okay thanks now it is working, thank u for helping
