### ISSUE TITLE
Error after Get-FileHash, then fullscreen (alt enter) and zoom (ctrl mousewheel)

### ISSUE THREAD

**Issue by Masterxilo** [PowerShell/PSReadLine#3185]
### Prerequisites

- [X] Write a descriptive title.
- [ ] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [ ] Search the existing issues, especially the pinned issues.

### Exception report

```console
Leider ist ein Fehler aufgetreten. Geben Sie mit diesem Fehler folgende Details an.
Bericht auf GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Letzte 37 Tasten:
 g e t - f i l Tab Space - A l Tab Space s h Tab Space l z Tab Enter
 Ctrl+V Ctrl+v Ctrl+c F11 Ctrl+` Ctrl+` Ctrl+` Ctrl+` Ctrl+` Ctrl+` Ctrl+` Ctrl+` Ctrl+` Ctrl+l Ctrl+l

Ausnahme:
System.IO.IOException: Falscher Parameter.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.Console.SetWindowPosition(Int32 left, Int32 top)
   bei Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bei Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![image](https://user-images.githubusercontent.com/2378665/151219110-1f4bfd85-9d77-4c06-b6b9-2884bb62b8a1.png)

### Environment data

```console
PS Version: 5.1.19041.1320
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 190
BufferHeight: 3000
```

### Steps to reproduce

doesn't happen anymore/again...

### Expected behavior

no ps readline exception

### Actual behavior

ps readline exception

**Comment by Masterxilo** [comment]
Unfortunately, my organization manages this device and all software on it... how come they ever installed a -beta Version of something?!

**Comment by daxian-dbw** [comment]
I guess it was from an early Win10. It was refreshed to version `2.0.0` in recently Win10, but the latest version is always released outside of Windows.
