### ISSUE TITLE
blank lines after output of `ctrl+space`

### ISSUE THREAD

**Issue by LuanVSO** [PowerShell/PSReadLine#3196]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![image](https://user-images.githubusercontent.com/43626415/151897414-bdaaef0e-8ca7-4c2e-92ca-54c373941ced.png)

### Environment data

```console
PS Version: 7.2.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.1-rc1
PSReadLine EditMode: Windows
OS: 10.0.19041.1466 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 35
```

### Steps to reproduce

1. go to a folder with at least 57 files or folders
```powershell
mkdir test
cd test
for ($i = 0;$i -ne 58;$i++){mkdir " kind of long name so it has to render in multiple lines $i"}
```
2. type any command + space
3. press ctrl + space

### Expected behavior

all folders are printed

### Actual behavior

all folders are printed + some empty lines

**Comment by daxian-dbw** [comment]
@LuanVSO Thanks for the report. It's a regression from 2.2.0-beta4 (at least). Will get it fixed.
