### ISSUE TITLE
If `AddToHistoryHandler` always returns `$false`, commands will be written to the history anyway

### ISSUE THREAD

**Issue by schittli** [PowerShell/PSReadLine#3200]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

In this example, I expect to have an empty `get-history` List!:

![image](https://user-images.githubusercontent.com/8282673/152534461-1c1c6ce0-0020-4a67-9ccb-b3ebb4403913.png)

### Environment data

```console
PS Version: 7.2.1
PS HostName: ConsoleHost
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 155
BufferHeight: 20000
```

### Steps to reproduce

That's easy 😃:
```
# Set AddToHistoryHandler to never add Lines to the History
Set-PSReadLineOption -AddToHistoryHandler {param([string]$line); Return $false}
# Clear the History
Clear-History
# Call some commands
(pwd).path
(pwd).path
(pwd).path
# Get the History - It should be empty, shouldn't it?
Get-History

```

### Expected behavior

- Because `AddToHistoryHandler` handles wich lines are added to the history (`get-history`)
- then I expect that lines are never added to the history, if `AddToHistoryHandler` returns `$false`

### Actual behavior

PowerShell's current history behavior is **extremely** tedious because the history lists 90% duplicates, see the typical screenshot below.

### Duplicates in `get-history` are only useful if 
one wants to understand exactly what has happened and in what order.
But this knowledge is usually needed at most 3 times a year.

### But what one needs all the time from `get-history`
is the list of the commands listed so far - without useless duplicates.

### An example of an usually useless history 😞 

![image](https://user-images.githubusercontent.com/8282673/152534856-ad0ec8f9-c4fa-4c78-a63f-664dffb723d3.png)

**Comment by daxian-dbw** [comment]
`Set-PSReadLineOption -AddToHistoryHandler` is to configure whether or not the `PSReadLine` module will persist command lines to the `history.txt` file. You can find the file by `get-psreadlineOption | % HistorySavePath`.

`Get-History` is a command that works with the PowerShell built-in command history cache. It has nothing to do with the `PSReadLine` module, and thus not affected by `Set-PSReadLineOption -AddToHistoryHandler`. The PowerShell built-in history cache is per session only, meaning that it's gone when you close the session.

**Comment by schittli** [comment]
Thank you very much, @daxian-dbw , for your answer and explanation!
