### ISSUE TITLE
TabComplete allow specification of DirectorySeparatorString to better work with WSL

### ISSUE THREAD

**Issue by raphaelschnaitl** [PowerShell/PSReadLine#3205]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

It would be helpful to allow customizing the `TabCompleteNext` to select which directory separator I want to use. I am on Windows using WSL a lot. But autocompleting path does break the WSL Commands. 

### Proposed technical implementation details (optional)

* Add another option to the `PSConsoleReadLineOptions` to specify the `TabCompleteDirectorySeparator`. 
* Change the PSConsoleReadLine Class to use this option instead of the
```
private static string DirectorySeparatorString = Path.DirectorySeparatorChar.ToString();
```

I can provide a PR.

**Comment by daxian-dbw** [comment]
`DirectorySeparatorString` is only used to append the trailing directory separator to a path returned from PowerShell tab completion. The directory separator used in the path is determined by PowerShell, not PSReadLine.

Your scenario is using `wsl.exe` on Windows, not working directly in a WSL Linux environment, right? What you are looking for can be done through a custom script block key binding -- map a key to a script block execution that is specific for `wsl.exe`, which change back slashes in the string argument of `wsl.exe` to forward slashes.

**Comment by raphaelschnaitl** [comment]
Thanks for your suggestion. I did something similar by including this into the TAB completion Handler:

```ps1
Set-PSReadLineKeyHandler -Chord Tab -ViMode Command -ScriptBlock {
  $content = ""
  $index = 0

  [Microsoft.PowerShell.PSConsoleReadLine]::ViTabCompleteNext()
  [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref] $content, [ref] $index)
  [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
  [Microsoft.PowerShell.PSConsoleReadLine]::Insert($content.Replace('\','/'))
  [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($index)
}
```

This replaces every backslash, which might cause Problems for other PPL. I do not know of any usecase where I do require backward slashes.

**Comment by daxian-dbw** [comment]
That looks good. You can remove the `$content.Replace('\','/')` line I think.
Good news is that PowerShell is able to normalize forward slash to backslash internally on Windows (except for when invoking an executable where the argument will be passed in as is), so it should work mostly fine for you.
It would be nicer if you only replace backslashes for the arguments of the `wsl` command, but that requires a bit more work.
