### ISSUE TITLE
Error while launching

### ISSUE THREAD

**Issue by jphellemons** [PowerShell/PSReadLine#3208]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
had this on 7.2 and now also after updating to 7.2.1
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.19044
BufferWidth: 120
BufferHeight: 9001

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

running on surface pro 3 with win 10 19044.1503 in the windows terminal but also by starting ps seperate
```


### Screenshot

<img width="859" alt="ss" src="https://user-images.githubusercontent.com/1119134/153395153-ce956858-4f76-480e-ab6d-fa525e99a80f.png">


### Environment data

```console
had to execute from ISE as the normal one does not start

PS Version: 5.1.19041.1320
PS HostName: Windows PowerShell ISE Host
PSReadLine Version: 
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
De ingang is ongeldig.
At line:25 char:32
+     Write-Host "BufferWidth: $([console]::BufferWidth)"
+                                ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], IOException
    + FullyQualifiedErrorId : System.IO.IOException
 
BufferWidth: 
De ingang is ongeldig.
At line:26 char:33
+     Write-Host "BufferHeight: $([console]::BufferHeight)"
+                                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], IOException
    + FullyQualifiedErrorId : System.IO.IOException
 
BufferHeight:
```

### Steps to reproduce

just launch ps

### Expected behavior

a normal terminal ready to rock

### Actual behavior

the crash above

**Comment by jphellemons** [comment]
step 2 fails:
Microsoft Windows [Version 10.0.19044.1503]
(c) Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\x>pwsh -noprofile -noninteractive
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\x> Uninstall-Module -Name PSReadLine -RequiredVersion 2.2.0-beta2 -AllowPrerelease
WARNING: The version '2.2.0-beta2' of module 'PSReadLine' is currently in use. Retry the operation after closing the applications.
Uninstall-Package: Module 'PSReadLine' is in currently in use or you don't have the required permissions.

**Comment by daxian-dbw** [comment]
You will need to close all pwsh instances before doing this, including VSCode if pwsh is opened in the VSCode terminal.
I recommend to use the latest [2.2.1-rc1](https://www.powershellgallery.com/packages/PSReadLine/2.2.1-rc1) version of PSReadLine.

**Comment by jphellemons** [comment]
Thanks, that solved it. Can be closed now
