### ISSUE TITLE
Multiple versions of PSReadLine

### ISSUE THREAD

**Issue by Archer456** [PowerShell/PSReadLine#3221]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
I have multiple versions, but I can't uninstall the old version under the specified path.

I am win10 system, the default is 5.1, I hardly use it.
I have installed and uninstalled PSReadLine under 7.2.1.
1 I have installed PSReadLine 2.2.0-beta5 first.
  Install-Module -Name PSReadLine -RequiredVersion 2.2.0-beta5 -AllowPrerelease
2 Then I uninstalled 2.2.0-beta5, installed 2.2.2
Install-Module -Name PSReadLine -RequiredVersion 2.2.2 -AllowPrerelease
Update-Module -Name PSReadLine -RequiredVersion 2.2.2 -AllowPrerelease

Now see the image below, I have multiple versions of PSReadLine
```

### Screenshot

![image](https://user-images.githubusercontent.com/18392901/155668109-9ce66a8c-ab07-4e0e-a4ec-797c15012e68.png)

### Environment data

```console
PS Version: 7.2.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.2
PSReadLine EditMode: Windows
OS: 10.0.19041.1526 (WinBuild.160101.0800)
BufferWidth: 160
BufferHeight: 38

PS Version: 5.1.19041.1320
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1526 (WinBuild.160101.0800)
BufferWidth: 160
BufferHeight: 38
```

### Steps to reproduce

I am win10 system, the default is 5.1, I hardly use it.
I have installed and uninstalled PSReadLine under 7.2.1.
1 I have installed PSReadLine 2.2.0-beta5 first.
  Install-Module -Name PSReadLine -RequiredVersion 2.2.0-beta5 -AllowPrerelease
2 Then I uninstalled 2.2.0-beta5, installed 2.2.2
Install-Module -Name PSReadLine -RequiredVersion 2.2.2 -AllowPrerelease
Update-Module -Name PSReadLine -RequiredVersion 2.2.2 -AllowPrerelease

Now see the image below, I have multiple versions of PSReadLine

### Expected behavior

I want to keep the versions in the directories above the same, all 2.2.2.
I now want to be able to specify the path to uninstall or install updates.

### Actual behavior

In 7.2.1 directory C:\Users\Archer\Documents\PowerShell\Modules it is 2.2.2.

Under the directory C:\program files\powershell\7\Modules it is 2.1.0

In 5.1 directory C:\Program Files\WindowsPowerShell\Modules it is 2.0.0 beta

**Comment by Archer456** [comment]
I tried the solution in this issue.
https://github.com/PowerShell/PSReadLine/issues/3208
If you want to remove that beta version of PSReadLine and use the 2.1.0 version of PSReadLine that's shipped with PowerShell 7.2, you can:

run pwsh -noprofile -noninteractive to start pwsh without loading PSReadLine
run Uninstall-Module -Name PSReadLine -RequiredVersion <2.2.0-beta1 or 2.2.0-beta2> -AllowPrerelease to remove the module. Or, you can manually remove that module folder.

But it keeps prompting me "psreadline is currently in use"

No way, I go directly to these two directories
C:\program files\powershell\7\Modules it is 2.1.0
C:\Program Files\WindowsPowerShell\Modules it is 2.0.0 beta
Physically deleted their folder directly!

After restarting the terminal, execute Get-Module PSReadLine -ListAvailable and 2.2.2 is left!

After restarting, there is no problem, God bless me.

**Comment by Archer456** [comment]
it keeps prompting me "psreadline is currently in use" 
why?
I have closed all process programs on the machine. Only open the powershell terminal.
Also, I also commented out the loading of notepad $Profile related PSReadLine.

implement 
pwsh -noprofile -noninteractive to start pwsh without loading PSReadLine
 Uninstall-Module -Name PSReadLine -RequiredVersion 2.2.2 -AllowPrerelease

Still keeps prompting me "psreadline is currently in use"

Can anyone tell me why why why

**Comment by daxian-dbw** [comment]
VSCode could have a PowerShell session opened on Windows, so if you have VSCode running, the VSCode terminal may have PowerShell started which loads the 2.2.2 version of PSReadLine. Another way to check the pwsh processes that are running is by `Get-Process -Name pwsh`.

It looks you already manually removed the module folder, that works too.
