### ISSUE TITLE
Not working in VSCode, but works great in Windows Terminal and PowerShell

### ISSUE THREAD

**Issue by adambrubaker** [PowerShell/PSReadLine#3224]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Hello

Not sure if this is the correct place for this or not.  Just installed version 2.2.2 and it works great on everything except VSCode.  So far I have verified that the correct module is imported.  I have also uninstalled and reinstalled VSCode and the PSReadLine module.  Still running PowerShell 5.1.  I'm guessing that I'm missing something simple. 

Thank you!
```

### Screenshot

![vscode_vs_ps](https://user-images.githubusercontent.com/65352063/156050563-03d2f1a8-d646-4ccd-97b9-588e38036ddd.PNG)

### Environment data

```console
PS Version: 5.1.19041.1320
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.2.2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 225
BufferHeight: 29
```

### Steps to reproduce

Open VSCode and start typing.

### Expected behavior

Suggestions for line completion based on command history.

### Actual behavior

Nothing.

**Comment by daxian-dbw** [comment]
I believe you do the setup in your profile. The profile used by VSCode extension is at a different path, run `$PROFILE` in the integrated console in VSCode to check the path.

**Comment by adambrubaker** [comment]
Just did a quick check and there is a different file listed in vscode vs ps but neither file exists.  I just utilize the profile.ps1 in C:\Windows\system32\WindowsPowerShell\v1.0 so I have the same environment in any application.
