### ISSUE TITLE
Option to disable all syntax highlighting

### ISSUE THREAD

**Issue by rahul-ramadas** [PowerShell/PSReadLine#324]
It would be nice if there was an option to disable all syntax highlighting.

**Comment by lzybkr** [comment]
I don't plan on adding an option, but you can set the colors easily enough today, e.g:

[enum]::GetNames([Microsoft.PowerShell.TokenClassification]) | % { Set-PSReadlineOption -TokenKind ([Microsoft.PowerShell.TokenClassification]::$_) -ForegroundColor ([Console]::ForegroundColor) -BackgroundColor ([Console]::BackgroundColor) }

This doesn't stop the color highlighting when searching your history, nor will it disable making the prompt turn red during an error, Set-PSReadlineOption has setting for those options as well.

**Comment by daprahamian** [comment]
Can we revisit this? PSReadline is causing issues when writing over a pty. The cursor keeps moving and when bytes are written fast enough it causes them to get mangled and/or dropped.
