### ISSUE TITLE
Commands that contain the string `token` are not written to command history file

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PSReadLine#3243]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.3.0-preview.2
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 209
BufferHeight: 46
```

### Steps to reproduce

1. Attempt to run the command `token`, or any command containing the string (e.g. `echo "token"`).
2. Open the PSReadLine history file (`(Get-PSReadLineOption).HistorySavePath`).
3. See that the command is missing.

### Expected behavior

The command is present in the history.

### Actual behavior

The command is missing.

**Comment by MatejKafka** [comment]
Apparently, this is an intended feature: https://github.com/PowerShell/PSReadLine/blob/0824ad134fcfd7e8eb31cfbccd5c7456ca3d24be/PSReadLine/History.cs#L116

Is it possible to turn this behavior off? I'd prefer to have my command history complete, even with potentially sensitive information.

**Comment by daxian-dbw** [comment]
It's not the expected behavior, the function `GetDefaultAddToHistoryOption` in that file should not mark `echo "token"` as sensitive. But you can disable the sensitive-content filter by `Set-PSReadLineOption -AddToHistoryHandler $null`.

**Comment by daxian-dbw** [comment]
Actually, I was wrong. After looking at the code, this is the by-design behavior. `Token` is considered a sensitive word and the default command-line scrubbing is somewhat strict on it, and thus false positive cases like what you observed may happen.

If the sensitive string scrubbing doesn't make sense to your daily use scenarios, feel free to disable it by `Set-PSReadLineOption -AddToHistoryHandler $null`.

**Comment by KalleOlaviNiemitalo** [comment]
A similar scenario:

```PowerShell
(Import-Clixml "${Env:HOME}\credential.clixml").GetNetworkCredential().Password | Set-Clipboard
```

`[Microsoft.PowerShell.PSConsoleReadLine]::GetDefaultAddToHistoryOption` returns MemoryOnly for that. `innerAst` is a StringConstantExpressionAst with StringConstantType : BareWord. Its parent is a MemberExpressionAst, the grandparent is a CommandExpressionAst, and the great grandparent is a PipelineAst.

I imagine the heuristic could be changed to allow MemberExpressionAst in which the name of the member is sensitive, if it is not at the left side of an assignment operator like `$shield.Password = "12345"`.

**Comment by daxian-dbw** [comment]
@KalleOlaviNiemitalo This is an interesting scenario where the heuristics should be improved. Can you open a new issue for it?

**Comment by KalleOlaviNiemitalo** [comment]
Filed <https://github.com/PowerShell/PSReadLine/issues/3318>.
