### ISSUE TITLE
Debug by .NET 6.0 failed

### ISSUE THREAD

**Issue by Andy-AO** [PowerShell/PSReadLine#3247]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Import-Module: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

### Screenshot

<img width="439" alt="image_966" src="https://user-images.githubusercontent.com/38101170/160277166-3934ba04-d474-4156-9dd6-34d6c32d16df.png">
<img width="734" alt="image_967" src="https://user-images.githubusercontent.com/38101170/160277167-fce419cc-7f09-4603-94cb-1d4326ef7843.png">

### Environment data

```console
PS Version: 7.1.3
PS HostName: ConsoleHost
PSReadLine Version:
Get-PSReadLineOption:
Line |
  21 |      Write-Host "PSReadLine EditMode: $((Get-PSReadLineOption).EditMod …
     |                                          ~~~~~~~~~~~~~~~~~~~~
     | The 'Get-PSReadLineOption' command was found in the module 'PSReadLine', but the module could not be loaded. For more information, run 'Import-Module PSReadLine'.
PSReadLine EditMode:
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

<img width="439" alt="image_966" src="https://user-images.githubusercontent.com/38101170/160277166-3934ba04-d474-4156-9dd6-34d6c32d16df.png">

### Expected behavior

run without errors just like debugging by .net461

### Actual behavior

loading failed

**Comment by daxian-dbw** [comment]
@Andy-AO It's not clear to me what your problem is (not sure what the UI shown in your screenshot is). Can you clarify the issue you run into?

**Comment by Andy-AO** [comment]
> @Andy-AO It's not clear to me what your problem is (not sure what the UI shown in your screenshot is). Can you clarify the issue you run into?

When I start debugging PSReadLine in Visual Studio(.NET 6), it turns out this problem.
Why are you not sure the UI? Do you never debug in Visual Studio?

**Comment by daxian-dbw** [comment]
PSReadLine doesn't support building in Visual Studio. The `PSReadLine.sln` is for editing in Visual Studio but does not cover the building. To debug PSReadLine in Visual Studio:
1. build it using the `build.ps1` targeting the desired framework
2. deploy the produced module (published in `<repo-root>\bin\<configuration>\PSReadLine`)
3. start pwsh with the produced PSReadLine module, then attach to the process from Visual Studio

**Comment by Andy-AO** [comment]
> PSReadLine doesn't support building in Visual Studio. The `PSReadLine.sln` is for editing in Visual Studio but does not cover the building. To debug PSReadLine in Visual Studio:
> 
> 1. build it using the `build.ps1` targeting the desired framework
> 2. deploy the produced module (published in `<repo-root>\bin\<configuration>\PSReadLine`)
> 3. start pwsh with the produced PSReadLine module, then attach to the process from Visual Studio

To Debugging this module is so complex, while it's only one key pressing for other PS module.

Why .net461 can do it in Visual Studio, but .net6 can't?

**Comment by Andy-AO** [comment]
> PSReadLine doesn't support building in Visual Studio. The `PSReadLine.sln` is for editing in Visual Studio but does not cover the building. To debug PSReadLine in Visual Studio:
> 
> 1. build it using the `build.ps1` targeting the desired framework
> 2. deploy the produced module (published in `<repo-root>\bin\<configuration>\PSReadLine`)
> 3. start pwsh with the produced PSReadLine module, then attach to the process from Visual Studio

PSReadLine can build and run by .net6 in Visual Studio, it only can't debug.

**Comment by Andy-AO** [comment]
> PSReadLine doesn't support building in Visual Studio. The `PSReadLine.sln` is for editing in Visual Studio but does not cover the building. To debug PSReadLine in Visual Studio:
> 
> 1. build it using the `build.ps1` targeting the desired framework
> 2. deploy the produced module (published in `<repo-root>\bin\<configuration>\PSReadLine`)
> 3. start pwsh with the produced PSReadLine module, then attach to the process from Visual Studio

I found that debugging work well in my VM thus maybe there is something wrong with my programming environment.

![image](https://user-images.githubusercontent.com/38101170/161662921-a8a6e7cc-7da3-4086-b9ca-d9d77d3c7946.png)

I'm surprised you don't know that you can debug this project in Visual Studio directly. 😂

**Comment by Andy-AO** [comment]
It doesn't turn out this problem after I have updated pwsh to the latest version(7.2.2). 
Now I can debug it by .net6 in Visual Studio directly.

**Comment by Andy-AO** [comment]
You can add the information about debugging to the contribution guide because there is nothing about it.

**Comment by daxian-dbw** [comment]
Yep, I totally forgot about #1319 which enabled F5 debugging in VS. Apology for that :)
I rarely used it because I need to debug net461 build with pwsh for most part, and that requires the polyfiller.dll built against net6.0+. That doesn't work with the F5 debugging.
