### ISSUE TITLE
Exception thrown when stopping a stuck git log session with Alt+Pause

### ISSUE THREAD

**Issue by scaramushe** [PowerShell/PSReadLine#3260]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.1.0
PowerShell: 5.1.22000.282
OS: Microsoft Windows 10.0.22000
BufferWidth: 138
BufferHeight: 70

Last 200 Keys

 2 e 1 Enter
 g i t Spacebar l o g Spacebar 3 3 9 8 2 e 1 Enter
 UpArrow UpArrow UpArrow DownArrow Ctrl+Backspace - - a b o Tab Enter
 UpArrow UpArrow DownArrow Ctrl+Backspace Backspace Backspace c 5 9 5 5 f 7 0 7 6 8 c 2 2 3 9 1 7 9 b 3 5 5 b 7 b 5 4 6 3 9 1 a 4 a d 6 4 7 7 Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Ctrl+Backspace 6 5 b 9 b 8 2 Enter
 UpArrow Ctrl+Backspace 6 d 7 3 8 e c Enter
 UpArrow Ctrl+LeftArrow Ctrl+Backspace Ctrl+Backspace l o g Spacebar Enter
 q Backspace g i t Spacebar m e r g e t Tab Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow DownArrow Ctrl+Backspace Backspace Backspace 5 1 f e 6 8 0 6 a b e 7 2 d d 8 9 6 c c 3 d a d 8 3 e c e 3 2 1 7 2 7 3 d b 5 b Enter
 UpArrow UpArrow Enter
 g i t Spacebar l o g Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 Alt+Pause
```

### Exception
```
System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/72554978/161705111-03c65705-4d87-4aac-8878-6af0466f8ef4.png)

### Environment data

```console
PS Version: 5.1.22000.282
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 138
BufferHeight: 70
```

### Steps to reproduce

When recovering from issue reproted in https://github.com/microsoft/terminal/issues/12828, pressed Alt+Pause to break out of stuck state.
Then pressed it again and got this error 

### Expected behavior

No exception

### Actual behavior

Exception

**Comment by scaramushe** [comment]
Another comment - the git autocomplete is posh-git

**Comment by daxian-dbw** [comment]
This is a very strange issue. I cannot reason from the [ReadOneOrMoreKeys](https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/ReadLine.cs#L94) method about when it would return with an empty `_queuedKeys`. Seems impossible to me ...

You mentioned in the windows terminal issue that you pressed `Alt+Pause` to break out of the unresponsive `git log`. Did you then, as indicated by your screenshot, start to debug a PowerShell script and press `Alt+Pause` again which led to the exception? I ask this because your `last 200 keys` shows `Alt+Pause` as the last input.

**Comment by scaramushe** [comment]
Yes, this is the sequence - pressing Alt-Pause to break out and again (for no reason :) ) and getting the error

**Comment by PrzemyslawKlys** [comment]
Hi,

```
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.3
PowerShell: 2022.4.2
OS: Microsoft Windows 10.0.22000 
BufferWidth: 293
BufferHeight: 31

Last 23 Keys:

 Ctrl+@ $ S y Tab Enter
 Ctrl+@ $ A u d i Tab UpArrow Enter
 Ctrl+@ UpArrow UpArrow Ctrl+a Backspace $ A u

### Exception

System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

Adding to this one. Happens when during debug in VSCode and while trying to type something.

**Comment by daxian-dbw** [comment]
@PrzemyslawKlys, the issue you run into is in VSCode. That's tracked by https://github.com/PowerShell/PSReadLine/issues/3292 and will be fixed by PowerShell/PSReadLine#3294.

**Comment by StevenBucher98** [comment]
Related PowerShell/vscode-powershell#4470

**Comment by andyleejordan** [comment]
> This is a very strange issue. I cannot reason from the [ReadOneOrMoreKeys](https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/ReadLine.cs#L94) method about when it would return with an empty `_queuedKeys`. Seems impossible to me ...
> 
> You mentioned in the windows terminal issue that you pressed `Alt+Pause` to break out of the unresponsive `git log`. Did you then, as indicated by your screenshot, start to debug a PowerShell script and press `Alt+Pause` again which led to the exception? I ask this because your `last 200 keys` shows `Alt+Pause` as the last input.

We were looking at this issue again and the hunch we've got is that the Break key (aka Alt+Pause) is "[often translated instantly](https://en.wikipedia.org/wiki/Break_key#Usage_for_breaking_the_program's_execution)" in contrast to a key like Ctrl+C where the keyboard buffer still receives input. This would explain why we have nothing to dequeue, because while we _expected_ an input to be queued, nothing was. We'll need to look at what .NET is doing for the Break key.
