### ISSUE TITLE
PR 3074 somehow breaks hyper-letters (hyper terminal plugin) on Mac

### ISSUE THREAD

**Issue by corbob** [PowerShell/PSReadLine#3267]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![2022-04-09_17-32-36 (1)](https://user-images.githubusercontent.com/30301021/162596200-45defde7-132d-4e27-acb0-c2ae3f45d825.gif)

### Environment data

```console
PS Version: 7.2.2
PS HostName: ConsoleHost
PSReadLine Version: 2.2.2
PSReadLine EditMode: Emacs
OS: Darwin Corys-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
BufferWidth: 200
BufferHeight: 80
```

### Steps to reproduce

On a mac:

1. Install [hyper](https://hyper.is)
2. Install hyper-letter (`hyper install hyper-letter`)
3. Notice that letters fall only when PSReadLine is not active

**NOTE:** I found that this was related to #3074 by tracking it down to working in `2.2.0-beta4` but not `2.2.0-beta5`, then with the PRs included in beta5 just running `git revert <merge commit hash>` and seeing if the issue was resolved. I have verified that working off of develop, reverting #3074 resolves this issue for me, but haven't tested anything else.

### Expected behavior

Letters fall as they're typed.

### Actual behavior

No letters produced.

**Comment by StevenBucher98** [comment]
@corbob does this still occur in the latest version of PSReadLine, either 2.2.6 or 2.3.0-beta.0?

**Comment by corbob** [comment]
@StevenBucher98 honestly, I stopped using Hyper a while ago when I noticed that it was the only shell that didn't handle `sudo` as a password entry.

I've checked with someone that still uses Hyper, and he reports that the issue still exists in both 2.2.6 and 2.3.0-beta.0, but neither of us really use the `hyper-letters` extension, so we can probably close this issue.
