### ISSUE TITLE
Bug (Error in Japanese)

### ISSUE THREAD

**Issue by ayarmkt** [PowerShell/PSReadLine#3281]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
-----------------------------------------------------------------------
直前 35 個のキー:
 g i t Space a d d Space . Enter
 g i t Space s t a t u s Enter
 g i t Space c o m m i t Space - m "

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの次元のバッファー サイズ未満を指定しなければなりません
。
パラメーター名:left
実際の値は -1 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

"N/A"

### Environment data

```console
PS Version: 5.1.19041.1645
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1645 (WinBuild.160101.0800)
BufferWidth: 119
BufferHeight: 12
```

### Steps to reproduce

Typing the quotes mark when typing `git commit -m""`

### Expected behavior

No error to occur

### Actual behavior

Error above displayed

**Comment by ayarmkt** [comment]
I read the instructions but couldn't understand / didn't work. Do you have an easier instructions?

**Comment by ayarmkt** [comment]
Hello,

Thank you for the message. I read the instructions but struggling to update
the PSReadLine. My error is this
<https://github.com/PowerShell/PSReadLine/issues/3281>. Can you help me
with this? Below are my questions.

1.
https://www.powershellgallery.com/packages/PSReadLine/2.2.2
For the code above, where do I run the command? How do I check if I have
PowerShellGet or not? (If I need to install PowerShellGet, I'm struggling
with that too...)

2.
https://github.com/PowerShell/PSReadLine#upgrading
For the instructions above, where am I supposed to run the command? (VSCode
or Windows PowerShell?). I guess my computer only has Windows PowerShell,
but here ist says PowershellGet needs to be updated beforehand, which I do
not have.

Aya

2022年4月20日(水) 17:14 github-actions[bot] ***@***.***>:

**Comment by daxian-dbw** [comment]
@ayarmkt 
> For the code above, where do I run the command?

Quoted from the doc:
"_if you are on Windows, run the suggested command below from `cmd.exe`, `powershell_ise.exe`, or via the `Win+R` shortcut;_"
But make sure all PowerShell sessions have exited, including close VSCode in case VSCode terminal uses PowerShell as its default shell.

> How do I check if I have PowerShellGet or not?

Run `Get-Module PowerShellGet -list` from PowerShell and see if it returns any results. If so, you have PowerShellGet.
Also, take a look at the version of the returned PowerShellGet module, if it's above 1.6.0, you don't need to upgrade it.

If you don't have PowerShellGet, then start PowerShell as administrator, then run `Install-Module -Name PowerShellGet -Force` in it to install the module.
