### ISSUE TITLE
Proposal: read default values from JSON file if it exists

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PSReadLine#3282]
### Description of the new feature/enhancement

As prediction gains popularity, there will be questions about how to manage enablement at scale. The current default is to not enable any prediction source. If the defaults were read from a JSON file if it exists when the module is imported, it would be easy for administrators/operators to write file to control the default for users.
This would address #1839.

### Proposed technical implementation details

The file could be created by an admin using an example from the module. It could be stored in ProgramData/PSReadLine so it is consistent across versions. The change to the module would be to check if the file exists and if so, use the values stored there. I don't think a cmdlet to manage the file is needed unless feedback is otherwise.

**Comment by StevenBucher98** [comment]
Adding issues/config requests that could be covered by this:
- https://github.com/PowerShell/PSReadLine/issues/3518

**Comment by daxian-dbw** [comment]
It turns out #635 already has lots of discussions about this, so close this one as a duplicate.
