### ISSUE TITLE
No module in unelevated prompt.

### ISSUE THREAD

**Issue by devkhan** [PowerShell/PSReadLine#329]
Syntax highlighting is not working on a normal PowerShell console, but working on an elevated one. Both point to same profile(which doesn't exist btw), there are no differences in task parameters.

Also, in the results of **Get-Module**, **PSReadLine** is only available in elevated console, not in default one.

I'm using ConEmu on Windows 10 Build 10586.

Anyone know why is this happening?

**Comment by lzybkr** [comment]
I can think of a couple possible explanations:
- Your unelevated prompt is x86.  This is a known issue on Win10
- Your unelevated prompt has an incorrect PSModulePath
