### ISSUE TITLE
How do I enable vi mode?

### ISSUE THREAD

**Issue by mynamewastaken** [PowerShell/PSReadLine#330]
I've tried setting it this way which errors out:

```
PS C:\users\me\Downloads> Set-PSReadlineOption -EditMode Vi
Set-PSReadlineOption : Cannot bind parameter 'EditMode'. Cannot convert value "Vi" to type
"PSConsoleUtilities.EditMode". Error: "Unable to match the identifier name Vi to a valid enumerator name.  Specify one
of the following enumerator names and try again: Windows, Emacs"
At line:1 char:32
+ Set-PSReadlineOption -EditMode Vi
+                                ~~
+ CategoryInfo          : InvalidArgument: (:) [Set-PSReadlineOption], ParameterBindingException
+ FullyQualifiedErrorId :     CannotConvertArgumentNoMessage,PSConsoleUtilities.SetPSReadlineOption
```

I've tried installing both via Github as well as via PSGet and get the same result both ways. Am I missing a step somewhere?

**Comment by lzybkr** [comment]
You need to build it yourself for now.  I haven't published a build with vi mode support yet.

**Comment by mynamewastaken** [comment]
@lzybkr Are there any instructions on how to do that? I'm happy to send in a PR to update documentation if you would like.

**Comment by lzybkr** [comment]
The MakeRelease.ps1 script will build and package up the release, it's at the root of the repo:
https://github.com/lzybkr/PSReadLine/blob/master/MakeRelease.ps1
It will also install if you pass -Install, but you can't have PSReadline loaded in any instance of PowerShell, so you could run (after killing all instances of powershell):

```
powershell -noprofile -command path\to\repo\MakeRelease.ps1 -Install
```

**Comment by idvorkin** [comment]
@mynamewastaken  did you get this working? Can you provide details.

**Comment by lzybkr** [comment]
@idvorkin - vi mode is in version 1.2 - included in Win10 or just follow the [instructions](https://github.com/lzybkr/psreadline#install-from-powershellgallery-preferred) for installing the latest version

**Comment by idvorkin** [comment]
Perfect - works like a charm -- thanks.

**Comment by idvorkin** [comment]
Dude - this plugin is incredible, thank you!!! I can finally make the switch to powershell after being trapped in cmd (w/clink) since forever.

**Comment by lzybkr** [comment]
You can thank @srdubya for vi mode. I'd have gotten around to it eventually, but he deserves all the credit for that feature.

**Comment by idvorkin** [comment]
Thank you @srdubya - Much obliged!!
