### ISSUE TITLE
PowerShell Error

### ISSUE THREAD

**Issue by bryoncline** [PowerShell/PSReadLine#331]
Got an error in powershell; appears to be something with a keystroke.
![powershell 01092016 1139am pst](https://cloud.githubusercontent.com/assets/2557042/12217984/2b64f3fe-b6c6-11e5-9a1f-c95e6bc4e20b.png)
![powershell 01092016 1139am pst](https://cloud.githubusercontent.com/assets/2557042/12217986/305009b2-b6c6-11e5-8a87-1fc07f0d766a.png)

**Comment by lzybkr** [comment]
Dupe of #292.
