### ISSUE TITLE
VSCode Python Extension debugger is broken

### ISSUE THREAD

**Issue by enricogandini** [PowerShell/PSReadLine#3321]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

When I was running a Python script using the debugger in the VSCode Python Extension, I got the following error:

```console
Si è verificato un problema. Segnala il bug con i dettagli riportati di seguito.
Segnala su GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Ultimi 70 tasti:
 & Space C : / U s e r s / N B - G A N D I N I / v i r t u a l e n v s / r e b e c c 
a 0 1 / S c r i p t s / A c t i v a t e . p s 1 Enter
 Space & Space ' C

Eccezione:
System.ArgumentOutOfRangeException: Il valore deve essere maggiore o uguale a zero e 
minore della grandezza del buffer della console in tale dimensione.
Nome parametro: left
Valore effettivo: -1.
   in System.Console.SetCursorPosition(Int32 left, Int32 top)
   in Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)      
   in Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   in Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   in Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   in Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)  
   in Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   in Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   in Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1706 (WinBuild.160101.0800)
BufferWidth: 110
BufferHeight: 10
```

### Steps to reproduce

I am using VSCode 1.67.2, with the official Python Extension v2022.6.2.

I started a debugger session with the following configuration in the `launch.json` file:
```
{
    "name": "Simple File",
    "type": "python",
    "request": "launch",
    "program": "${fileBasename}",
    "cwd": "${fileDirname}",
},

```

The debugger immediately crashed with the above Exception report.

### Expected behavior

I should be able to run the VSCode Python debugger without this exception.

### Actual behavior

The above exception makes it impossible to use the VSCode Python debugger. It had worked perfectly until now. I tried to restart VSCode and Windows, but the problem persists.

**Comment by Backist** [comment]
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 4 claves:
 Ctrl+c UpArrow Enter
 Ctrl+l

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: top
Valor actual -22.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by Backist** [comment]
When I was running a Python script using the debugger in the VSCode Python Extension, I got the following error:
```
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 4 claves:
 Ctrl+c UpArrow Enter
 Ctrl+l

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: top
Valor actual -22.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```
