### ISSUE TITLE
Make settings persistent in the config file in "WellKnown" location

### ISSUE THREAD

**Issue by agirko** [PowerShell/PSReadLine#3322]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

Make settings to be persistent in some config file (JSON file in the user profile path perhaps?) so desired configuration is persistent and not relying on execution of the `$profile` execution of which may be restricted in some scenarios.

**Comment by daxian-dbw** [comment]
Close as a duplicate of #3282
