### ISSUE TITLE
Error in running code

### ISSUE THREAD

**Issue by Pvsaraf** [PowerShell/PSReadLine#3328]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.ArgumentOutOfRangeException: The value must be greater than or equal 
to zero and less than the console's buffer size in that dimension
```

### Screenshot

<img width="443" alt="VSCodePRoblem" src="https://user-images.githubusercontent.com/64657857/170873313-5f0efdcc-2a4e-4c6d-b8a5-2c3b24641474.png">

### Environment data

```console
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
```

### Steps to reproduce

`#include <bits/stdc++.h>

using namespace std;

struct ListNode
{
    int val;
    ListNode *next;
    ListNode() : val(0), next(nullptr) {}
    ListNode(int x) : val(x), next(nullptr) {}
    ListNode(int x, ListNode *next) : val(x), next(next) {}
};

ListNode *rotateList(ListNode *head, int K)
{
    // Complete the function
    ListNode *temp = head;
    if (head == NULL)
        return head;
    int cnt = 0;
    ListNode *last = NULL;
    while (temp)
    {
        cout << temp->val << " ";
        temp = temp->next;
        last = temp;

        cnt++;
    }
    K = K % cnt;
    cout << K << "\n";
    cout << cnt << "\n";

    if (K == 0)
        return head;

    ListNode *next_ptr = NULL;
    temp = head;
    int temp_cnt = 0;
    while (temp)
    {
        temp_cnt++;
        if (temp_cnt == cnt - K)
        {
            next_ptr = temp->next;
            temp->next = NULL;
            last->next = head;
            head = next_ptr;
            break;
        }

        temp = temp->next;
    }

    return head;
}

ListNode *GetList(vector<int> &num)
{
    ListNode *head = nullptr;

    if (num.empty())
    {
        return head;
    }

    ListNode *cur = head;

    for (int i = 0; i < (int)num.size(); i++)
    {
        ListNode *temp = new ListNode(num[i]);
        if (!cur)
        {
            cur = temp;
            head = cur;
        }
        else
        {
            cur->next = temp;
            cur = temp;
        }
    }

    return head;
}

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cout.tie(0);

    int n;
    cin >> n;

    vector<int> num;
    for (int i = 0; i < n; i++)
    {
        int x;
        cin >> x;
        num.push_back(x);
    }

    int K;
    cin >> K;

    ListNode *head = GetList(num);

    while (head)
    {
        cout << head->val << " ";
        head = head->next;
    }

    head = rotateList(head, K);

    while (head)
    {
        cout << head->val << " ";
        head = head->next;
    }
    cout << "\n";

    return 0;
}`

### Expected behavior

It will run and give the output

### Actual behavior

It gives exception which I am unable to understand. Please resolve this issue

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the 2.2.3 version of PSReadLine from PowerShell Gallery.
See the upgrading section for instructions. Please let us know if you run into the same issue with the latest version.
