### ISSUE TITLE
MenuComplete behaves oddly in folder with many (>50) items

### ISSUE THREAD

**Issue by MartinSGill** [PowerShell/PSReadLine#3344]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![image](https://user-images.githubusercontent.com/2271740/173592606-3a111111-8972-4404-89d5-8df47a9e445c.png)

### Environment data

```console
PS Version: 7.3.0-preview.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 122
BufferHeight: 29
```

### Steps to reproduce

Create many sub-folders (or files), e.g. 

```powershell
@(1..60) | % { mkdir Some.Very.Very.Very.Very.Long.Prefix.Folder.With$_ }
```

Set MenuComplete as handler

```powershell
Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
```

Type: `ls Som<TAB>`

### Expected behavior

Same as when

```powershell
Set-PSReadLineKeyHandler -Key Tab -Function Complete
```

i.e.

Current text at cursor updated to `Some.Very.Very.Very.Very.Long.Prefix.Folder.With`

### Actual behavior

A list of folders is displayed (no menu) and the **text at the cursor is not updated**.

Presumably, there is too much data to render a menu and MenuComplete tries to fall back to the `Complete` function, but it seems to not do this correctly.

I would expect the text at cursor to be updated to the longest unique value (as [described in the docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.psconsolereadline.menucomplete?view=powershellsdk-1.1.0#:~:text=If%20trying%20to%20complete%20the%20longest%20unambiguous%20completion%2C%20a%20list%20of%20possible%20completions%20is%20displayed.))

**Comment by daxian-dbw** [comment]
This is the by design behavior. It's not falling back to `Complete`, but falling back to the _"Display all xxx possibilities? (y or n)"_ UI, which is also used by `Complete`. For `Complete`, the step that completes to the longest unique sub-string is done before getting to the _"Display all possibilities"_ UI.
