### ISSUE TITLE
Crash on running powershell with ssh

### ISSUE THREAD

**Issue by da1024** [PowerShell/PSReadLine#335]
---

Last 0 Keys:

Exception:
System.IO.IOException: Wrong descriptor.

   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   in PSConsoleUtilities.PSConsoleReadLine.Initialize(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
I haven't seen this message before, but in all likelihood, it's the same error I see in #158.
