### ISSUE TITLE
Update-Help -Module PSReadLine is (still) broken on Powershell 5.1

### ISSUE THREAD

**Issue by goldug** [PowerShell/PSReadLine#3359]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Update-Help : Failed to update Help for the module(s) 'PSReadline' with UI culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI culture en-US. Make sure the HelpInfoUri property in the module manifest is valid or check your network connection and then try the command again.
At line:1 char:1
+ Update-Help -UICulture en-US -Module PSReadLine -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand
```

### Screenshot

![e5b1c559677a479b47f8372d5b82edfc](https://user-images.githubusercontent.com/15221208/175787234-95287a18-213e-4a2e-b8ed-b65389387d87.png)

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost
PSReadLine Version: 2.2.5
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

Run Update-Help -UICulture en-US -Module PSReadLine -Force in Powershell 5.1

### Expected behavior

To update the help for PSReadLine

### Actual behavior

The above exception happens.

**Comment by daxian-dbw** [comment]
This is a known issue. Please see this blog post for workaround: https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

**Comment by goldug** [comment]
No, that solution doesn't work. It's already renamed to PSReadLine. I've done all the steps in the workaround, but it still doesn't work.

**Comment by daxian-dbw** [comment]
![image](https://user-images.githubusercontent.com/127450/176018753-a20e8793-bc4f-44d8-a831-fa7579a41586.png)

@goldug It still shows up as `PSReadline` in your error message, so did you rename the `PSReadline` module folder to `PSReadLine`? If that doesn't work, maybe you will have to update the `PSReadline.psd1` and `PSReadline.psm1` files in that folder to `PSReadLine.psd1` and `PSReadLine.psm1` as well. By the way, those changes were already done to the latest Windows.
/cc @sdwheeler for comments.

**Comment by sdwheeler** [comment]
The problem is in Windows. This has been fixed in Windows 11. Prior to Windows 11, Windows PowerShell loaded the module using the `PSReadline` name. That is the name used by `Update-Help`. You can work around this by unloading PSReadLine then reloading it with the proper letter case.

```powershell
Remove-Module PSReadLine
Import-Module PSReadLine
Update-Help PSReadLine -Force
```
