### ISSUE TITLE
Vi mode: "v" commands (to edit buffer in vim) are showing up in history

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PSReadLine#339]
Ideally, the command-mode "v" command (which should launch an editor to edit the buffer in a temp file) would not leave any trace in the user's command history (I don't think there is any reason why a user would want to recall that command).

The repro steps assume that "vim" will launch vim; adjust step 4 as necessary to launch an editor of your choice.
1. ipmo PSReadLine
2. Set-PSReadLineOption -EditMode Vi
3. $env:VISUAL='vim'
4. abcde[ESC]v
5. (do whatever you like to the command line in the editor, then quit it)
6. Get-History

**Expected result:**
    No "vim 'C:\users<me>\AppData\Local\Temp\asdfadfasdf.asdf.ps1'" command in my history.

**Actual result:**
    There is a "vim 'C:\users<me>\AppData\Local\Temp\asdfadfasdf.asdf.ps1'" command in my history. (from the temp file created when we edited the command line in a temp file during step 4-5).

**Comment by lzybkr** [comment]
Thanks for opening the issue.  @srdubya is already aware of the issue.

I think the best fix is to use something like:

PowerShell.Create(RunspaceMode.UseCurrentRunspace).AddCommand(visualEditor).AddArgument(tempFile).Invoke();

I'm pretty sure that won't add to the history.

**Comment by srdubya** [comment]
I tried PowerShell.Create(RunspaceMode.UseCurrentRunspace).AddCommand(visualEditor).AddArgument(tempFile).Invoke().  It runs the visual editor but the editor does not use the console window for output.  I will try a few things, but I'd appreciate any other ideas you may have.
