### ISSUE TITLE
Support Predictions as a Source for Completions

### ISSUE THREAD

**Issue by s-nix** [PowerShell/PSReadLine#3400]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

When using a predictor (specifically one that is a plugin for an application) I would like to be able to `Ctrl-Space` and see the available options like a Completer. Currently when using a predictor the experience when typing is:

![WindowsTerminal_Afbg8tOoxQ](https://user-images.githubusercontent.com/11358399/183451539-805b9da6-be5f-4b1c-944c-da57b4297d18.gif)

But the `Ctrl-Space` completion does not use the same predictions:

![WindowsTerminal_paapEHJhJO](https://user-images.githubusercontent.com/11358399/183451939-39c48504-05d0-43f3-9725-919c2671af07.gif)

The `PredictiveSuggestion` class even has a Tooltip property that is seemingly unused currently.

![image](https://user-images.githubusercontent.com/11358399/183452423-88fa36e3-1d65-4856-9345-fda37c8557dc.png)

I may be missing something in the scope or purpose of Predictors vs. Completer, but I think that this would unify the two more and allow for a single API to create both Predictors and Completion options.

### Proposed technical implementation details (optional)

I think implementing this would require prepending some code to the `TabExpansion2` function to read the current Predictors and display them instead of the default. It would be similar to [ChocolateyTabExpansion.ps1](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1) but using the AST instead of the more primitive implementation in `TabExpansion`.

**Comment by StevenBucher98** [comment]
You can register your predictor module as an argument completer with the data you provide with your predictor so that it shows up in the `Ctrl+Space`, you can check out this documentation for registering with argument completers, https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.3

**Comment by daxian-dbw** [comment]
The vagrant predictor looks great!
To get `Ctrl+space` show similar completion results, like @StevenBucher98 mentioned above, please register the argument completer for `vagrant` using `Register-ArgumentCompleter`. The actual implementation can be done in C#, and the script block registered can just call into a static C# method from your model to do the completion.
