### ISSUE TITLE
How to restore the initial state of settings?

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#3414]
### Description of the new feature/enhancement

If it is because of my ignorance, then I thank you for your help.
If there is no such function, I hope to add a reset function.
or
The corresponding configuration will be restored automatically after deleting the corresponding code. `$PROFILE`

### Proposed technical implementation details (optional)

I set a lot of shortcut keys and colors
Now I want to reset, back to PSReadLine's initial default settings.
Checked a lot of information and currently solved the method of deleting shortcuts, but I don't know how to reset/ or delete the color settings.
##1 This is a guide to deleting shortcuts
[https://docs.microsoft.com/en-us/powershell/module/psreadline/remove-psreadlinekeyhandler?view=powershell-7.2](url)

Waiting for the answer, thanks for your help and good luck.🙂

**Comment by daxian-dbw** [comment]
The user defined key bindings are all in the `Custom` group, so you can get all user-defined key bindings by:
```
$bindings = Get-PSReadLineKeyHandler | ? Group -eq Custom
```

Then, you can remove them by looping through the results and call `Remove-PSReadLineKeyHandler` on each binding:
```
foreach ($i in $bindings) { Remove-PSReadLineKeyHandler -Chord $i.Key }
```
