### ISSUE TITLE
Psreadline for Gitbash terminal 

### ISSUE THREAD

**Issue by Rohit-wagh** [PowerShell/PSReadLine#3419]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

Hey Team, 
I really like the psreadline for PowerShell but the same thing I want to use in gitbash terminal. 
Is there any existing way to implement this? if so then please let me know 
Thanks

**Comment by daxian-dbw** [comment]
PSReadLine is for PowerShell, while git bash is a bash emulator, so PSReadLine won't work in git bash.
