### ISSUE TITLE
Conemu & LShift click

### ISSUE THREAD

**Issue by majkinetor** [PowerShell/PSReadLine#342]
Conemu allows for cursor setting using LShift click, which is very convenient for long commands. Unfortunately this feature does not work once you import psreadline.

Any way to fix it ?

**Comment by lzybkr** [comment]
Do you have any idea how conemu accomplishes this?  The only way I can imagine supporting conemu doing this is to check where the cursor is before every keystroke.

Alternatively, the win32 console apis do support mouse events, so it's possible to support this fully in PSReadline w/o conemu - this might be more useful, but it also might be more work.

**Comment by majkinetor** [comment]
ConEmu isn't console application for start - it also supports regular GUI apps in its tab etc... It keeps regular windows shell hidden in the background and somehow gets the data from it ( I believe via windows hooks).

About supporting mouse in psreadline, I wouldn't do it as this is feature that wouldn't get too much attention and besides, you have forward and backward char search witch is how its done in Vim basically...
