### ISSUE TITLE
Tooltips generated by predictor not showing in ListView

### ISSUE THREAD

**Issue by DiaAzul** [PowerShell/PSReadLine#3433]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![Screenshot 2022-09-14 102929](https://user-images.githubusercontent.com/28156158/190117458-c9ad9c9e-451f-47ca-bc04-c42316a6c8fc.png)

### Environment data

```console
PS Version: 7.2.6
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

Create the sample predictor as set out in the Microsoft Article: [Sample predictor](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/create-cmdline-predictor?view=powershell-7.2)

Change the SuggestionsPackage returned by the predictor to specify a tooltip (addition of "This is toolTip." string in the PredictiveSuggestion constructor.
```csharp
return new SuggestionPackage(new List<PredictiveSuggestion>{
    new PredictiveSuggestion(string.Concat(input, " HELLO WORLD"), "This is a toolTip.")
});
```

Import the module into PowerShell.
```csharp
Import-Module ".\bin\Debug\net6.0\SamplePredictor.dll"
```

Set `PSReadLine` options:
`PredictionSource` : HistoryAndPlugin
`ShowToolTips`: True
`PredictionViewStyle`: ListView

Type text at the prompt and review list view output.

### Expected behavior

I was expecting to see the tool tip shown in the ListView between the suggested completion and name of the plugin.

### Actual behavior

There is no tool tip shown.

**Comment by daxian-dbw** [comment]
@DiaAzul Thanks for reporting this. This behavior is by design to PSReadLine. A predictor plugin can work with any PowerShell host that choose to support the predictive intellisense feature, and the `tooltip` field is for the hosts that support popup window, so when a suggestion is in the highlighted selection, its tooltip can be displayed without interfering with other suggestion results.

For PSReadLine, it works in terminal. Most terminals don't support popup window (VSCode terminal started to support it, but most other popular ones don't). So, PSReadLine doesn't use the tooltip field as of today.

**Comment by DiaAzul** [comment]
@daxian-dbw Thank you for the response. 

When you say: "For PSReadLine, it works in terminal", what does this mean? Which terminal? VT220?

When you say: "VSCode started to support it...", do you mean they started, but have subsequently removed support? Or, that it is currently supported from version X.X?

Sorry to be pedantic, but details matter.

**Comment by daxian-dbw** [comment]
> When you say: "For PSReadLine, it works in terminal", what does this mean? Which terminal? VT220?

Console terminals in general.

> When you say: "VSCode started to support it...", do you mean they started, but have subsequently removed support? Or, that it is currently supported from version X.X?

They started to roll out a feature in VSCode terminal called `Shell Integration`. I heard it would support popup intellisense windows in VSCode terminal, similarly to what you get when editing in the VSCdoe editor. But I don't know much about the details.
[Fig](https://fig.io/) is another terminal that supports popup window for intellisense.
