### ISSUE TITLE
PSReadLine History doesn't scrub sensitive information as documented

### ISSUE THREAD

**Issue by clr2of8** [PowerShell/PSReadLine#3442]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

The documentation [here](https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-5.1#notes) says the history won't contain lines containing sensitive words like "password" or "token" but that isn't the case.

![image](https://user-images.githubusercontent.com/22311332/192402628-2199da5b-27c2-4e92-a2a7-5f471d3f0ea4.png)

**Comment by clr2of8** [comment]
![image](https://user-images.githubusercontent.com/22311332/192402827-eea9c5f0-c1fe-4fba-b33d-925e6fd9bcd4.png)

**Comment by daxian-dbw** [comment]
What version of PSReadLine are you using? You can check it out by `Get-Module PSReadLine`.
I cannot reproduce using the latest version of PSReadLine (v2.2.6). Please upgrade to the latest version and try again.

BTW, the built-in history in PowerShell (`h`, `Get-History`) has nothing to do with PSReadLine. PSReadLine doesn't save the sensitive command lines to the history file.

**Comment by clr2of8** [comment]
![image](https://user-images.githubusercontent.com/22311332/192580413-b5c4a10e-536e-4a1a-8022-82c5a9805b34.png)

I'll upgrade and try it.

**Comment by clr2of8** [comment]
Confirmed, not an issue in the latest version. Thank you 

![image](https://user-images.githubusercontent.com/22311332/192581965-524f265c-c6b3-4a77-856a-10320cd18dcf.png)
