### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Prashant-Kumar-321** [PowerShell/PSReadLine#3449]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 200 Keys:
 c v . x w b ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - y p n 4 f r m 4 . o u v ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - d n 0 g p j 2 b . q v j ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - e h r y 4 l n l . j h u ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter
```

### Screenshot

Last 200 Keys:
 c v . x w b ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - y p n 4 f r m 4 . o u v ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - d n 0 g p j 2 b . q v j ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - e h r y 4 l n l . j h u ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

### Environment data

```console
Last 200 Keys:
 c v . x w b ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - y p n 4 f r m 4 . o u v ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - d n 0 g p j 2 b . q v j ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - e h r y 4 l n l . j h u ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter
```

### Steps to reproduce

Last 200 Keys:
 c v . x w b ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - y p n 4 f r m 4 . o u v ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - d n 0 g p j 2 b . q v j ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - e h r y 4 l n l . j h u ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

### Expected behavior

Last 200 Keys:
 c v . x w b ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - y p n 4 f r m 4 . o u v ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - d n 0 g p j 2 b . q v j ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - e h r y 4 l n l . j h u ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

### Actual behavior

Last 200 Keys:
 c v . x w b ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - y p n 4 f r m 4 . o u v ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - d n 0 g p j 2 b . q v j ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - e h r y 4 l n l . j h u ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

**Comment by StevenBucher98** [comment]
@Prashant-Kumar-321 it is unclear what the exact problem is. Please edit or resubmit an issue that clearly states the issue you are facing, steps to reproduce and expected behavior vs real behavior.
