### ISSUE TITLE
How to load locally built module

### ISSUE THREAD

**Issue by dkaszews** [PowerShell/PSReadLine#3451]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

I wanted to test some changes to the module, but cannot figure out how to load it. The readme only says that build artifacts are in `bin/(Debug|Release)/PSReadLine`, but `Import-Module PSReadLine.psm1` does nothing, while `Import-Module PSReadLine.psd1` causes error `Assembly with same name already loaded`. I gather that the problem is that I'm using PowerShell 7.3 which autoloads the PSReadLine it ships with and you cannot unload the assembly according to StackOverflow.

Please provide at least one of the following, in form of instructions in readme/contributor guide or a script:
1. Replace already loaded module with one built locally
2. Start new PowerShell instance which loads module built locally instead of the default one

**Comment by iSazonov** [comment]
You could start pwsh without PSRL with `-NonInteractive`.

**Comment by dkaszews** [comment]
Thanks, had to use combination of `-NonInteractive -NoProfile` to get it to work, probably because I have, `Set-PSReadLineOption` in my `$PROFILE` which forced load anyway. After that, I can load profile to get back my settings. 

Should I add this hint to `README.md`? I think a `Start-DevPowerShell.ps1` like in the main repo would make sense, something like `pwsh -NonInteractive -NoProfile -c 'Import-Module ... && . $PROFILE'` with some extra options would be great. 

Is it possible to enable interactive mode back on, or should this be a non-issue not impacting `PSReadLine`?

**Comment by springcomp** [comment]
@dkaszews You may be interested in [this discussion](https://github.com/PowerShell/PSReadLine/issues/2912#issuecomment-954262032).
