### ISSUE TITLE
Can't run multi-line scriptblocks longer than console vertical buffer size with transient prompt enabled in PowerShell

### ISSUE THREAD

**Issue by DEberhardt** [PowerShell/PSReadLine#3452]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
[2022-10-19 13:07:39]❯ $Error[0].Exception.Message
Exception calling "InvokePrompt" with "0" argument(s): "The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1."
[2022-10-19 13:07:57]❯ $Error[0].ScriptStackTrace
at <ScriptBlock>, <No file>: line 142
at PSConsoleHostReadLine, C:\Users\david\Documents\WindowsPowerShell\Modules\PSReadline\2.2.5\PSReadLine.psm1: line 7
```
```


### Screenshot

N/A, but easily reproducible

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.5
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 171
BufferHeight: 60

and



PS Version: 7.3.0-preview.8
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.5
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 171
BufferHeight: 60
```

### Steps to reproduce

I am trying to define an array of 59 users, like this:
```powershell
$UCS = @(
'sip:User1@domain.com',
'sip:User2@domain.com',
'sip:User3@domain.com',
...
'sip:User58@domain.com',
'sip:User59@domain.com'
)
```

and I get the above error.
If I paste longer text with multiple commands, this does not occur, as long as no command is longer than 50 lines for example

```powershell
$UCS = @(
'sip:User1@domain.com',
'sip:User2@domain.com',
'sip:User3@domain.com',
[...]
'sip:User49@domain.com'
)
$UCS += @(
'sip:User50@domain.com',
'sip:User51@domain.com',
[...]
'sip:User59@domain.com'
)
```

### Expected behavior

no keyhandler issue

### Actual behavior

Command is not executed

**Comment by DEberhardt** [comment]
I inquired with Jan on the issue, and he pointed me your way. I could not find an open issue quickly, but you may still have this on the books. Some history on oh-my-posh regarding Transient Prompt and Oh-my-posh:
https://github.com/JanDeDobbeleer/oh-my-posh/issues/2906
and
https://github.com/JanDeDobbeleer/oh-my-posh/issues/2979

**Comment by daxian-dbw** [comment]
Given this is also related to using `InvokePrompt` within Transient Prompt of Oh-my-posh, I will resolve it as a duplicate of #3447.
We will need to triage and see whether `InvokePrompt` is designed for the use of it in Oh-my-posh.

**Comment by lahma0** [comment]
Why is this marked completed? Has the issue been fixed because I'm still having the same issue across multiple machines.
