### ISSUE TITLE
Opening PowerShell with another user (afer su) causes an IOException on PSReadLineHistoryFile

### ISSUE THREAD

**Issue by VashSan** [PowerShell/PSReadLine#3489]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.0
OS: Linux 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29)
BufferWidth: 122
BufferHeight: 33

Last 0 Keys:



### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_3617841288'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://user-images.githubusercontent.com/2479263/202853971-2436822e-2f35-46e5-81c9-f0d7c2092062.png)

### Environment data

```console
PS Version: 7.3.0
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Emacs
OS: Linux v2202211131407207693 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux
BufferWidth: 122
BufferHeight: 33
```

### Steps to reproduce

1. Start PowerShell
2. Switch User (bash open)
3. Start a nested PowerShell 

### Expected behavior

PowerShell can be used just

### Actual behavior

IOException on file "PSReadLineHistoryFile_[0-9]?" everytime send a command

**Comment by andyleejordan** [comment]
Hi @VashSan. I think what's gone on here is that the history file `PSReadLineHistoryFile_3617841288` was created by the original user when you started the first PowerShell session. After you've substituted in the `postgres` user with `su`, your UID no longer has permissions to read that history file (by design, since you wouldn't want your history readable by any user but yourself).
