### ISSUE TITLE
CommandValidationHandler for non-existing command

### ISSUE THREAD

**Issue by majkinetor** [PowerShell/PSReadLine#350]
How can I get the invalid commands ? If i type `meh` the PSReadline types "Command 'meh' not found" and on enter PS reports non-recognized cmdlet but non of this is catched by the handler. 

The case is that I would like to search for non existing commands on software repository and install them if necessary.

**Comment by KirkMunro** [comment]
What you're looking for has nothing to do with PSReadLine.  PowerShell has native support for actions related to command lookup.  See the following properties in $ExecutionContext.InvokeCommand:
- CommandNotFoundAction
- PreCommandLookupAction
- PostCommandLookupAction

Note that each of these is a property that accepts a script block event handler, not an actual Event that you can subscribe to, which means they may be overwritten if, for example, a module that is installed on the system defined its own CommandNotFoundAction for some reason (I have a module that does this).

**Comment by majkinetor** [comment]
Thanks for the information.
