### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by AlfianMusthofa** [PowerShell/PSReadLine#3510]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

![bug](https://user-images.githubusercontent.com/95052996/207036556-1dc6dd12-992f-4d59-87e1-5260464321ef.png)

**Comment by daxian-dbw** [comment]
You are using a very old version of PSReadLine (2.0.0-beta2 or prior).  Please upgrade to the latest version and the issue should've been fixed.
