### ISSUE TITLE
Installed PSWSMan - Issues after restarting PowerShell session

### ISSUE THREAD

**Issue by alfiogennaio** [PowerShell/PSReadLine#3521]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.1
OS: Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
BufferWidth: 226
BufferHeight: 57

Last 0 Keys:



### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_1039836058'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

Install-WSMan
Copy-Item: Access to the path '/usr/local/microsoft/powershell/7/libmi.dylib.bak' is denied.
Copy-Item: Access to the path '/usr/local/microsoft/powershell/7/libmi.dylib.bak' is denied.
Copy-Item: Access to the path '/usr/local/microsoft/powershell/7/libmi.dylib' is denied.
Copy-Item: Access to the path '/usr/local/microsoft/powershell/7/libpsrpclient.dylib.bak' is denied.
Copy-Item: Access to the path '/usr/local/microsoft/powershell/7/libpsrpclient.dylib.bak' is denied.
Copy-Item: Access to the path '/usr/local/microsoft/powershell/7/libpsrpclient.dylib' is denied.
New-Item: Administrator privilege required for this operation.
New-Item: Administrator privilege required for this operation.
**WARNING: WSMan libs have been installed, please restart your PowerShell session to enable it in PowerShell**

### Environment data

```console
From Environment data script

PS Version: 7.3.1
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.2.6
PSReadLine EditMode: Emacs
OS: Darwin MWQLVWMYXC 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
BufferWidth: 205
BufferHeight: 15

From $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Steps to reproduce

Install PowerShell and.NET on Mac (macOS Ventura - M1 Pro)

Get-InstalledModule
Install-Module -Name AWS.Tools.Common
Install-Module -Name AWSLambdaPSCore
Install-Module -Name ExchangeOnlineManagement
Install-Module -Name PSWSMan
Install-WSMan

Restart pwsh

### Expected behavior

The PowerShell should have reloaded.

### Actual behavior

PowerShell is not restarting/initializing

**Comment by daxian-dbw** [comment]
Close as a duplicate of #2658

**Comment by darthwalsh** [comment]
@alfiogennaio  did you get this error repeatedly? Only on system boot? Do you know how you were able to reproduce it?

**Comment by alfiogennaio** [comment]
@darthwalsh I have closed the project which required development with PWSH. It was consistent, and It was not on system reboot. I don't recall the details and how I was able to reproduce it.
