### ISSUE TITLE
PSReadline interferes with doskey macros

### ISSUE THREAD

**Issue by Alan-d** [PowerShell/PSReadLine#353]
I'll include the error details that I had, but first I'll provide a way to repro what I see, though the below repro is not what gave the error.

[Example, with PS> starting lines you type]
Open powershell.exe
PS> doskey /exename=powershell.exe hello=Write-Host "hello world"
PS> hello
hello : The term 'hello' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
- hello
- ~~~~~
  - CategoryInfo          : ObjectNotFound: (hello:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

PS> Remove-Module PSReadline
PS> hello
hello world
# 

Error that made me realize something was going wrong with PSReadline:

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 31 Keys:
 s . Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace d a a Enter
 Enter
 Enter
 c a b n s g Enter
 w e

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
I have no plans to support doskey macros.  There are replacements in PowerShell and/or PSReadline (PowerShell functions or custom PSReadline key bindings.)

In many cases, doskey macros can be automatically converted to PowerShell functions.  I could share a script that I use that works for my scenarios.

I think the error you've hit is a known issue not related to PSReadline, but can you share the OS you're on and any other details that might be relevant, e.g. how did you start PowerShell?

**Comment by HerbM** [comment]
No plans to support DosKey is unfortunate and I would ask you to reconsider.

There really is no PowerShell replacement for the full capabilities of DosKey (Aliases don't do what DosKey does fully -- e.g., you can do more than just replace the COMMAND but also do tests and change how parameters are used with DosKey.)

DosKey is also a lot easier to get onto other machines and to make work similarly to CMD favorite commands.

For me personally, if it is either PSReadline or Doskey Macros, then I'll have to stick with Doskey BUT note that I have 20 years of DosKey macros build and habits for using them which most people don't have.

If you can't spend the time on DosKey support but have a strategy that might work, then please post or send me the ideas and perhaps I can look at adding this (as an option).

In any case, THANK YOU for your work on PSReadLine, it is a nice module.

**Comment by rkeithhill** [comment]
I used to use Doskey back in the late 90's / early 00's.  What are a few of your most commonly used macros?  They "might" be easier to convert than you think.  I realize your example above is trivial but so is the function equivalent:

``` powershell
function hello {Write-Host 'hello world'}
```

Also, if you are in PowerShell as your `PS>` prompt indicates, why take the perf hit of firing up another PowerShell exe instance?

**Comment by HerbM** [comment]
They probably are easy enough to convert, and much of it is having years of them and mostly that they are mostly the same or very similar to my CMD macros (e.g., %UserProfile% references become $ENV:UserProfile and the 'if' tests change to accommodate the PS syntax differences.

However, if I look at it as a "new project" it really would not be that hard to write all this in PowerShell -- after all, PowerShell is a full language.

Much of my clinging to these Macros is that they made it INITIALLY possible for me to adopt PowerShell as an "everyday shell" -- I had CMD down to the point that somethings are still easier for me to do there than in PowerShell (my fingers just know the answer without much thinking.)

I am going to have to rethink just changing all these to PowerShell functions and sticking them in my powershell profile.

Thanks for the push (whether I change or not, just thinking about this is likely to both improve my macros and my PowerShell.)

**Comment by rkeithhill** [comment]
I would recommend the push to PowerShell.  PSReadline makes the line editing (and history recall) much nicer than what CMD supports.  I just love being able to press <kbd>Ctrl+a</kbd>, <kbd>ctrl+c</kbd> to copy the current command line to the clipboard.  I love that I can search my command history not based on the beginning part of the command but with any text in the command using <kbd>Ctrl+r</kbd>.  And the multiline editing is pretty nice too.  

And I love it that I can write custom handlers for keyboard shortcuts of my own choosing. Here is one of my favs lately:

``` powershell
# Copy the current path to the clipboard
Set-PSReadlineKeyHandler -Key Alt+c `
                         -BriefDescription CopyCurrentPathToClipboard `
                         -LongDescription "Copy the current path to the clipboard" `
                         -ScriptBlock {
    param($key, $arg)

    Add-Type -Assembly System.Windows.Forms
    [System.Windows.Forms.Clipboard]::SetText($pwd.Path, 'Text')
}
```

For more of these check out my [PSReadline_config.ps1](https://gist.github.com/rkeithhill/3103994447fd307b68be) file.

**Comment by HerbM** [comment]
Thanks, I have grabbed your config and will review, steal, and adapt it as I two would love to press ctrl-a ctrl-c to copy the current line and since that is the same as most GUI programs it will require very little adaptation.

Curious (but we are to the point it won't stop me).  Do I get to keep select, right click right click to copy a selection into the current cursor position?  

You've also tempted me with the Alt-C; I've rigged my prompt specifically to make doing that less painful:  Quotes and no adjacent touching characters so that double click would grab it.  :)

Thanks again

**Comment by rkeithhill** [comment]
Yup.  The console mechanisms for mark, copy and paste are still available.

**Comment by nigurr** [comment]
Even I am stuck with this issue. It would be nice to have some switch to execute `doskey` commands over `psreadline`.

@lzybkr Would be nice if you can share script to convert them to PS alias

**Comment by rkeithhill** [comment]
@nigurr  Can you share a few of your doskey macros here?  I can show you how to convert them.  After you see a few, it will probably be pretty easy to convert the rest yourself.

**Comment by nigurr** [comment]
`bl=msbuild /m "/flp1:LogFile=msbuild.log;PerformanceSummary;Summary;ShowTimestamp" "/flp2:LogFile=msbuild.wrn;WarningsOnly" "/flp3:LogFile=msbuild.err;ErrorsOnly" $*`

`f=findstr /ips /c:"$*" *`

**Comment by rkeithhill** [comment]
OK so `bl` is the macro name, right?  What is timer and what does it do?  It doesn't seem to be a standard Windows utility - at least it's not on my Windows 10 PC.

**Comment by nigurr** [comment]
@rkeithhill it's bit complicated. So i simplified it :)

**Comment by rkeithhill** [comment]
Try this:

``` powershell
function bl {
    msbuild /m $args --% /flp1:LogFile=msbuild.log;PerformanceSummary;Summary;ShowTimestamp /flp2:LogFile=msbuild.wrn;WarningsOnly /flp3:LogFile=msbuild.err;ErrorsOnly
}

function f {
    $OFS = " "
    findstr /ips /c:"$args" *
}
```

**Comment by lzybkr** [comment]
With PowerShell running cross platform now, I have no plans to support doskey as there are typically other ways that you can accomplish the same thing in PowerShell and those solutions will work on all platforms.

**Comment by HerbM** [comment]
**FIRST:  I love PSReadline and wan to say:  THANK YOU**

So can we just put our "macros" right into PSReadline?
Does it have that possibility?
(Or would that be easy to add -- I forked it with the idea of looking but have about 20 years of "ideas" like this to get to....)

Here's the one I am using a LOT to invoke the clipboard without actually pasting:    ic.ps1 is in my path and contains:
```
. ([scriptblock]::Create($((Get-Clipboard) -join "`n")))   # that first character is DOT
# then I invoke it as:

.  ic   ### dot again

```
It  needs to work this way because it needs to operate OUTSIDE of a function and in the Global scope.

The main issues are to get it to execute in the **global scope**, to **avoid cluttering the History**, work **even with right click** so PSReadline won't try to **match braces** and screw it up.  Ideally it would be a function so it could be pasted even on a "pristine machine" with no existing scripts (like my "ic.ps1")` but they probably won't have PSReadline anyway.

**Comment by lzybkr** [comment]
You could try something like this (untested, but should give get you close):

```PowerShell
Set-PSReadlineOption -AddToHistoryHandler {
    param([string]$line)
    return $line -notmatch '<#NOHISTORY#>'
}

Set-PSReadlineKeyhandler -Key Ctrl+w -ScriptBlock {
    [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
    $toRun = ". { $((Get-Clipboard) -join ""`n"")`n} <#NOHISTORY#>'
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert($toRun)
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
}
```

You could even get fancy and accept an argument to decide whether or not to add `<#NOHISTORY#>`. You can use Alt-num to pass integers to a handler, e.g. `Alt-2 Alt-3` would pass the value 23 as the second argument to the handler (the first argument is the key that triggered the handler, useful if you reuse a handler for multiple keys.

**Comment by HerbM** [comment]
I was WRONG -- PSReadline is BETTER than Doskey in the long run but is going to take some effort to build the functions/commands.

It is (should be?) easy to produce PSReadline functions that mimic and exceed those in DosKey and I've been working to parse DosKey to automatically do that (still want to share DosKey with CMD.exe).
 
I've been switched to PSReadline for some time now, but still want the functionality of DosKey -- and simplicity.

Anyway, anyone (still?) delaying PSReadline, we can have PSreadline with all the doskey goodness and more.  (There are probably 3 or 4 people somewhere on the Internet who still care. :) )
