### ISSUE TITLE
Set-PSReadLineOption: The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.

### ISSUE THREAD

**Issue by davetapley** [PowerShell/PSReadLine#3538]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

```
➜ Set-PSReadlineOption
Set-PSReadLineOption: The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
```

### Environment data

```console
PS Version: 7.3.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
Get-PSReadLineOption:
Line |
  21 |      Write-Host "PSReadLine EditMode: $((Get-PSReadLineOption).EditMod …
     |                                          ~~~~~~~~~~~~~~~~~~~~
     | The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
PSReadLine EditMode:
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 24
```

### Steps to reproduce

Update to Powershell 7.3

### Expected behavior

It works

### Actual behavior

```
     | The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.

```

**Comment by davetapley** [comment]
I was able to uninstall and downgrade to PowerShell 7.2.5 and it's working again.

**Comment by StevenBucher98** [comment]
@davetapley can you provide better reproduction steps? Can you also provide results from `Get-Error`?
