### ISSUE TITLE
ViModeIndicator not in effect on Vi mode during initilaization

### ISSUE THREAD

**Issue by darg2012** [PowerShell/PSReadLine#3542]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

<img width="895" alt="Screen Shot 2023-01-11 at 10 31 53 AM" src="https://user-images.githubusercontent.com/60045376/211863506-4a8a1ea2-e4a3-46cd-acef-28052d9bf776.png">
<img width="895" alt="Screen Shot 2023-01-11 at 10 32 26 AM" src="https://user-images.githubusercontent.com/60045376/211863510-df3cc279-6093-4775-a4fe-df53bd8c4d70.png">
<img width="895" alt="Screen Shot 2023-01-11 at 10 33 12 AM" src="https://user-images.githubusercontent.com/60045376/211863517-79b6e239-5b75-4578-86a4-478cca71490e.png">

### Environment data

```console
PS Version: 7.2.0
PS HostName: ConsoleHost
PSReadLine Version: 2.1.0
PSReadLine EditMode: Vi
OS: Darwin Davids-M1-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:29:57 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T8101 arm64
BufferWidth: 85
BufferHeight: 24
```

### Steps to reproduce

Have in profile or type in cli the following
```powershell
Set-PSReadlineOption -EditMode Vi
Set-PSReadlineOption -ViModeIndicator Cursor
```

### Expected behavior

Cursor should change as `Set-PSReadlineOption -ViModeIndicator Cursor` is being set.

The ViModeIndicator setting is not loaded initially on Vi mode until insert mode is escaped from and reentered. This applies to both the cursor option or a custom script like in #1233.

### Actual behavior

No change to the cursor.

**Comment by StevenBucher98** [comment]
This was fixed by #3374 and should be working correctly in the latest 2.3.0 preview! Give that a try! You can install here, https://www.powershellgallery.com/packages/PSReadLine/2.3.0-beta0
