### ISSUE TITLE
Can't import after updating to 2.2.6

### ISSUE THREAD

**Issue by Drllap** [PowerShell/PSReadLine#3575]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS>Import-Module PSReadline
Import-Module : Errors occurred while loading the format data file:
C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.2.6\PSReadLine.format.ps1xml, , C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.2.6\PSReadLine.format.ps1xml: The file was skipped because of the following validation exception: File C:\Program
Files\WindowsPowerShell\Modules\PSReadline\2.2.6\PSReadLine.format.ps1xml cannot be loaded because its operation is blocked by software restriction policies, such as those created by using Group Policy..
At line:1 char:1
+ Import-Module PSReadline
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

### Screenshot

n/a

### Environment data

```console
PS Version: 5.1.19041.2364
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version:
Get-PSReadLineOption : The 'Get-PSReadLineOption' command was found in the module 'PSReadline', but the module could not be loaded. For more information, run 'Import-Module PSReadline'.
At line:21 char:41
+     Write-Host "PSReadLine EditMode: $((Get-PSReadLineOption).EditMod ...
+                                         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PSReadLineOption:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PSReadLine EditMode:
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 280
BufferHeight: 71
```

### Steps to reproduce

Update PSReadLine
execute Import-Module PSReadLine

### Expected behavior

PSReadLine should be imported

### Actual behavior

Get error

**Comment by daxian-dbw** [comment]
> ... its operation is blocked by software restriction policies, such as those created by using Group Policy..

It's likely your execution policy setting is blocking the execution of script files. You can view your execution policy by `Get-ExecutionPolicy`. Try changing it to `RemoteSigned` to unblock it.

**Comment by Drllap** [comment]
I'm already using `Unrestricted`

But if I try to set to `RemoteSigned` I get:
```
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
execution policy of Unrestricted. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
information please see "Get-Help Set-ExecutionPolicy".
At line:1 char:1
+ Set-ExecutionPolicy RemoteSigned
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
```

**Comment by daxian-dbw** [comment]
Then it looks something with the group policy is enforced on your machine, which may be the cause of the issue you saw.

**Comment by Drllap** [comment]
@daxian-dbw Is there a way to find this group policy and delete it?

**Comment by Drllap** [comment]
Interestingly, importing the old version still works:
```
Import-Module PSReadLine -RequiredVersion 2.0.0
```

**Comment by daxian-dbw** [comment]
The `2.0.0` version came with the Windows OS at `"Program Files\PowerShell\Modules"`, right?

That would explain it. The 2.0.0 version that was shipped in-box with Windows is catalog signed, which means that it's recognized as part of the OS files, and thus is fully trusted. So, whatever policy that is enforced on your machine will believe the 2.0.0 version PSReadLine file are trusted and won't block it from execution.

The new PSReadLine module installed from PowerShell Gallery won't be treated as part of the OS files, and thus is blocked by the enforced policy. You may want to take a look at the [Windows PowerShell related Group Policy settings](https://techgenix.com/powershell-execution-policy/) on your machine, but they are likely enforced by your organization and cannot be altered locally.

**Comment by Drllap** [comment]
@daxian-dbw This is my personal PC, so there shouldn't be any organization enforced policy.

**Comment by Drllap** [comment]
Had a look at the article you posted, as far as I can see all the PowerShell related group policies are set to "Not Configured"

**Comment by Drllap** [comment]
@daxian-dbw How come I need to supply `-SkipPublisherCheck` when installing PSReadLine except when installing v2.2.3? Is that normal?

**Comment by Drllap** [comment]
I can also import v2.2.3 just fine but not the others

**Comment by daxian-dbw** [comment]
> This is my personal PC, so there shouldn't be any organization enforced policy.
> Had a look at the article you posted, as far as I can see all the PowerShell related group policies are set to "Not Configured"

Then I really don't know what "software restriction policies" are blocking the loading of the module ...

I cannot reproduce your issue locally:

![image](https://user-images.githubusercontent.com/127450/218378488-46d79238-fefd-4f77-8eeb-1f7817cc2be6.png)

This is the only report about 2.2.6 cannot be loaded at startup. I checked out [the change history between 2.2.3 and 2.2.6](https://github.com/PowerShell/PSReadLine/compare/v2.2.3...v2.2.6), and the only build related change was moving from building against .NET Framework 4.6.1 to 4.6.2, but I doubt that is the cause of your issue.
