### ISSUE TITLE
PSReadLine Exception: Windows Aero Snap Right With Keyboard

### ISSUE THREAD

**Issue by draccicgeb** [PowerShell/PSReadLine#3582]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 5.1.19041.2364
OS: Microsoft Windows 10.0.19045
BufferWidth: 134
BufferHeight: 9999

Last 56 Keys

 UpArrow Enter
 PageUp PageUp PageUp c l s Enter
 UpArrow UpArrow Enter
 PageUp PageUp PageDown PageDown UpArrow Enter
 PageUp c l s Enter
 UpArrow UpArrow Enter
 PageUp c l s Enter
 UpArrow Enter
 UpArrow UpArrow PageUp DownArrow DownArrow Enter
 PageUp PageDown UpArrow Enter
 PageUp PageDown c l s Enter
 UpArrow UpArrow Enter
 PageUp PageDown LeftWindows PageUp
```

### Exception
```
System.ArgumentOutOfRangeException: The window position must be set such that the current window size fits within the console's buffer, and the numbers must not be negative.
Parameter name: left
Actual value was 0.
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![Screenshot 2023-02-16 095904](https://user-images.githubusercontent.com/25541788/219400460-3b2a39cc-b749-4d64-973a-6a61a2f2f331.png)

### Environment data

```console
PS Version: 5.1.19041.2364
PS HostName: ConsoleHost
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 134
BufferHeight: 9999
```

### Steps to reproduce

Console window maximized. More than one screen output with wide lines. Hit [Windows Logo]+[Right Arrow].

### Expected behavior

Changing the window size should result in display of the contents with long lines wrapped if the window is narrower than these.

### Actual behavior

Window snaps to right half but appears to be blank. Hitting [Enter] does not cause the prompt to be displayed.

I did not attempt to reproduce this in the current version.

**Comment by StevenBucher98** [comment]
@draccicgeb Do you encounter this same issue when on the latest version of PSReadLine (2.2.6)?
