### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by BBSRKhelp** [PowerShell/PSReadLine#3586]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N / A
```

### Screenshot

![2023-02-18_22-38-48](https://user-images.githubusercontent.com/106028955/219884929-b300d6ea-a597-412b-8525-11daa24743aa.jpg)

### Environment data

```console
N / A
```

### Steps to reproduce

N / A

### Expected behavior

N / A

### Actual behavior

N / A

**Comment by daxian-dbw** [comment]
@RomanKapitanov You may be able to get help on this error in the `PowerShellGet` GitHub repo.
