### ISSUE TITLE
Problem with the latest version of the official Python interpreter ; I am obeying an automatic demand to report this

### ISSUE THREAD

**Issue by clarence-chm** [PowerShell/PSReadLine#3587]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.22621.963
OS: Microsoft Windows 10.0.22621
Last 200 Keys

 r s / a n n e p / D e s k t o p / I n f o r m a t i q u e / N S I / 0 0 1 4 _ A r b r e s _ b i n a i r e s . p y Enter
 & Spacebar C : / U s e r s / a n n e p / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 1 1 / p y t h o n . e x e Spacebar c : / U s e r s / a n n e p / D e s k t o p / I n f o r m a t i q u e / N S I / 0 0 1 4 _ A r b r e s _ b i n a i r e s . p y Enter
 RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow &
```

### Exception
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToPoint(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
```

### Screenshot

<img width="892" alt="image" src="https://user-images.githubusercontent.com/126008205/220422074-39bc5812-a834-4fc9-a959-bec63cb341c6.png">
Taken right before it happened

### Environment data

```console
PS Version: 5.1.22621.963
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 135
BufferHeight: 20
```

### Steps to reproduce

I ran this code in order to solve a school problem that was about printing a binary tree with the terminal and the Python interpreter.

class Noeud:
    def __init__(self,contenu,sous_arbre_gauche,sous_arbre_droit):
        self.contenu = contenu
        self.sous_arbre_gauche = sous_arbre_gauche
        self.sous_arbre_droit = sous_arbre_droit
        
    def Contenu(self):
        return self.contenu
    
    
class Arbre:
    def __init__(self,noeud=None):
        self.noeud = noeud
        
    def ArbreVide():
        return Arbre()
    
    def FaireArbre(racine,sous_arbre_gauche,sous_arbre_droit):
        return Arbre(Noeud(racine,sous_arbre_gauche,sous_arbre_droit))
    
    def Feuille(racine):
        return Arbre(Noeud(racine,Arbre.ArbreVide(),Arbre.ArbreVide()))
    
    def Racine(self):
        return self.noeud
    
    def SousArbreGauche(self):
        return self.noeud.sous_arbre_gauche
    
    def SousArbreDroit(self):
        return self.noeud.sous_arbre_droit
    
    def EstArbreVide(self):
        return self.noeud is None
    
    def EstFeuille(self):
        assert not self.EstArbreVide(), "L'arbre considéré est vide."
        if self.noeud.sous_arbre_gauche.EstArbreVide() and self.noeud.sous_arbre_droit.EstArbreVide() :
            return True
        else :
            return False
        
    def Taille(self):
        if self.EstArbreVide():
            return 0
        elif self.EstFeuille():
            return 1
        else :
            return 1 + self.SousArbreGauche().Taille() + self.SousArbreDroit().Taille()
        
    def Hauteur(self):
        if self.EstArbreVide() or self.EstFeuille():
            return 0
        else :
            if self.SousArbreDroit().EstArbreVide():
                return 1 + self.SousArbreGauche().Hauteur()
            elif self.SousArbreGauche().EstArbreVide():
                return 1 + self.SousArbreDroit().Hauteur()
            else :
                return 1 + max(self.SousArbreGauche().Hauteur(),self.SousArbreDroit().Hauteur())

    
     
    #Fonctions permettant l'affichage de l'arbre sur le terminal       
    def SuivreInstructions2(self,instructions="",i=0): #renvoit l'arbre obtenu plutôt que le contenu de sa racine
        if i == len(instructions):
            return self
        elif instructions == "":
            return self
        else :
            if instructions[i] == "g":
                return self.SousArbreGauche().SuivreInstructions2(instructions,i+1)
            else :
                return self.SousArbreDroit().SuivreInstructions2(instructions,i+1)
            
    
            
    def ParLignes(self,lignes=[],milieu=0): 

        
            
        if self.EstArbreVide():
            return ""
        elif self.EstFeuille():
            lignes.append(str(self.Racine().Contenu()))
        else :
            #Remplissage des branches "venant avant"
            if not self.SousArbreDroit().EstArbreVide():
                lignes = self.SousArbreDroit().ParLignes(lignes,milieu)
                i = milieu
                while not lignes[i][0].isnumeric():
                    lignes[i] = "  "+lignes[i]
                    i += 1
                lignes[i] = "┌─"+lignes[i]
                i += 1
                while i < len(lignes):
                    lignes[i] = "│ "+lignes[i]
                    i += 1
                    
                    
            lignes.append(str(self.Racine().Contenu())) 
            depart = len(lignes)
            milieu = len(lignes)
            
            
             
            
            #Remplissage des branches "venant après"
            if not self.SousArbreGauche().EstArbreVide():
                lignes = self.SousArbreGauche().ParLignes(lignes,milieu)
                i = depart
                while not lignes[i][0].isnumeric():
                    lignes[i] = "│ "+lignes[i]
                    i += 1
                lignes[i] = "└─"+lignes[i]
                i += 1
                while i < len(lignes):
                    lignes[i] = "  "+lignes[i]
                    i += 1
                
          
        return lignes
        
    
    def AffichageCote(self):
        print()
        parLignes = self.SuivreInstructions2().ParLignes()
        for ligne in parLignes :
            print(ligne)  
        
            
        
        

        

    
    
#Arbre 1   
un = Arbre.Feuille(1)
deux = Arbre.Feuille(2)
trois = Arbre.Feuille(3)
cinq = Arbre.FaireArbre(5,trois,deux)
arbre1 = Arbre.FaireArbre(6,cinq,un)
#arbre1 = Arbre.FaireArbre(3,un,deux)

#arbre1.AffichageCote()
#print("*****")

#Arbre 2
six = Arbre.Feuille(6)
cinq = Arbre.FaireArbre(5,un,six)
neuf = Arbre.FaireArbre(9,cinq,trois)
zero = Arbre.FaireArbre(0,deux,Arbre.ArbreVide())
moinsHuit = Arbre.FaireArbre(8,Arbre.ArbreVide(),zero)
arbre2 = Arbre.FaireArbre(7,neuf,moinsHuit)

arbre2.AffichageCote()

### Expected behavior

Here is the right output of my code, that I ran again without modifying it right after the exception happened :
<img width="898" alt="image" src="https://user-images.githubusercontent.com/126008205/220423620-080ad20a-f60a-4d92-8997-9ac4a9fa0a64.png">

### Actual behavior

When I run my code, whether this exact exception happens or not seems to be up to "chance" because I never modify it.

**Comment by clarence-chm** [comment]
I didn't put the whole code : only the parts that are necessary for the method that caused the exception to run.

**Comment by daxian-dbw** [comment]
@clarence-chm Thanks for reporting the issue. The version of PSReadLine you are using is very old, so the issue should have been fixed in the more recent versions. Please upgrade to the [2.2.6 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
