### ISSUE TITLE
Handle last command status and syntax errors in one prompt

### ISSUE THREAD

**Issue by eugenesvk** [PowerShell/PSReadLine#359]
In all my shells I have the last symbol showing status of last command (e.g. `current/path >_` with `>` in **green** if last command was a success and `>` in *_red *_if it was an error).
Now, your awesome addon has a very nice feature of warning me on syntax errors by coloring the last prompt symbol in red. However, this doesn't really work if my last command was an error as the last symbol is already red.
Is there a way I could combine both error indicators? I see a few ways of achieving this:
1. Make PSReadLine replace last e.g. space with a symbol (e.g. `current/path >_` would turn into `current/path >!`, last space would be replaced with `!` warning you about the syntax error (`_` is a space as genuine space doesn't get displayed in the end of the code comment)).
2. Make PSReadLine use a different color (maybe there is a separate syntax-error color option I've missed)
3. Change font to bold/underline on error (as far as I understand that's impossible thanks to some stupid design decision by MS)
4. (the one I'm using now) Add an invisible symbol `!` (same color as background) in the end so that PSReadLine would color it. However, this forces me to have two spaces in the end instead of one as I must have a `Return " "` at the end of my prompt function due to another smart design choice by MS). Maybe there is a fix for this I'm just not aware of
5. Something else?

**Comment by lzybkr** [comment]
That's a great idea for your prompt, I might use it myself.

As you've suggested, there are multiple options.  There is an existing configuration option that you can use:

Set-PSReadlineOption -ErrorForegroundColor <not red>

Bold/underline is possible with the latest builds of Win10 (insider builds), VT100 escape sequences are supported.

**Comment by eugenesvk** [comment]
Well, the options I've suggested aren't working at the moment.
And from your comment I don't understand how to make them work. Even with bold/VT100 support, how would I make your addon utilize those functions instead of (or in addition to) using the red color?

Also, `Set-PSReadlineOption -ErrorForegroundColor` doesn't change the color for syntax errors, it's still red. It only affect the color of erros text that powershell outputs. Also I'd really like to make default errors stay as is.

Is there a way to change the color your addon uses? Would you maybe point to the part of the source that deals with it, I could change the hard-coded red to something else and hopefully rebuild it myself?

**Comment by lzybkr** [comment]
Sure enough, I added that option for a different reason and didn't use it for the syntax error indicator, that is hard coded.

The VT100 suggestion helps with your invisible character.  Your prompt function can return a vt100 escape sequence to color the ! character properly instead of returning " ".

**Comment by eugenesvk** [comment]
> Your prompt function can return a vt100 escape sequence to color the ! character properly instead of returning " ".

Thank you, clear now! Now I'd only need to add a function of converting default PowerShell colors to ANSI sequences to make my prompt background-independent (i.e. it would output a proper ANSI matching any background), but that's easy to do. 

Hopefully you could also change the hardcoded color to something that a user can change. Though in my case I'm starting to get attached to my idea of a `!` symbol instead of just changing prompt symbol color :).

P.S.
By the way, in some more advanced terminals like iTerm2 I can actually error-color prompt symbol of the line containing the command rather than the current line (see illustration below, it's helpful when scrolling history). Is PSReadline theoretically able to handle previous prompt functions or is it too much to ask for on Windows :)

```
path > error command   <- this prompt symbol will change color to red AFTER command execution
some error output
path >                 <- this prompt can remain green because it has nothing to do with the previous command
```

**Comment by eugenesvk** [comment]
I've found an even better solution to my proposal No4 without having to wait till VT100 Powershell gets to regular Windows builds — I've adjusted the `Render.cs` to make last whitespace (if it exists) change background to red instead of last non-whitespace (also adjusted the non-whitespace color just in case). This way I don't need to have two spaces at the end since I can work with the one required in `Return " "`.

However, it'd still be nice to have configurable options:
1. What to color (whitespace vs regular char)
2. Foreground color and background color (with an option to have the same as console in case e.g. you don't need a background color)
3. VT100 style (bold, italic, underline)

**Comment by lzybkr** [comment]
I've made some changes in 2.0 that might be useful to you.

First, `ErrorColor` is honored - you can set foreground and background both as a single string using VT escape sequences.
Second, the option `PromptText` tells PSReadLine which character(s) to color - if you say space, it will use space, so you could set the background color on the space and PSReadLine won't touch your error indicator.

Hopefully this is sufficient for you, but if you have other ideas, feel free to suggest them.
