### ISSUE TITLE
Build error when using MakeRelease.ps1

### ISSUE THREAD

**Issue by eugenesvk** [PowerShell/PSReadLine#360]
I was trying to follow the steps outlined in [Purveyor](https://ci.appveyor.com/project/lzybkr/psreadline) to build PSReadLine, but when I ran `.\MakeRelease.ps1` it failed with lots of these errors:
`BasicEditing.cs(9,25): error CS0234: The type or namespace name 'Automation' does not exist in the namespace 'System.Management' (are you mis sing an assembly reference?) [C:\Projects\psreadline\PSReadline\PSReadLine.csproj]`

However, when I open the `PSReadLine.csproj` in Visual Studio and build from there, it all works fine because it copies the required dlls to the new folder `c:\Projects\psreadline\PSReadLine\packages\Microsoft.PowerShell.3.ReferenceAssemblies.1.0.0\lib\net4\`. After I get these files copied to the `packages` folder, the `.\MakeRelease.ps1` continues just fine and is able to build a release.

I stumbled upon this by accident and was wondering why this is happening and whether there is a way to make `MakeRelease.ps1` see the `Automation` dlls (I've tried adding folder with those dlls to path with `$env:path += ";c:\Program Files (x86)\Reference Assemblies\Microsoft\WindowsPowerShell\3.0\"` in `MakeRelease.ps1`, but that didn't help either)

**Comment by lzybkr** [comment]
I'm not sure what was happening, but the build is now using nuget for that package, so I think the problem is fixed.
