### ISSUE TITLE
Provide a way to display error/exception in other available languages (Translation ) after their occurence

### ISSUE THREAD

**Issue by inkebilli** [PowerShell/PSReadLine#3609]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

To provide a way for the user to be able to translate the error messages after their occurrence.

**Why**: When the user ran into an exception and want to share it in other languages.

**example**: I was opening an issue and i realized that the error messages was in french. So i manually translated the messages to English

### Proposed technical implementation details (optional)

A separated command that displays the last output(if it was an error) in the selected language.

**Comment by daxian-dbw** [comment]
This request can be easily fulfilled by searching engines, and also this won't be a common operation one will do in their daily workflow.
