### ISSUE TITLE
Write History in Powershell ISE

### ISSUE THREAD

**Issue by nyukers** [PowerShell/PSReadLine#3619]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PSReadLine doesn't write history of PS commands in PowerShell ISE.
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.2364
PS HostName: Windows PowerShell ISE Host
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

**Get-PSReadlineOption** | select HistoryNoDuplicates, MaximumHistoryCount, HistorySearchCursorMovesToEnd, HistorySearchCaseSensitive, HistorySavePath, HistorySaveStyle

HistoryNoDuplicates           : True
MaximumHistoryCount           : 4096
HistorySearchCursorMovesToEnd : False
HistorySearchCaseSensitive    : False
HistorySavePath               : C:\Users\User01\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\Windows PowerShell ISE Host_history.txt
HistorySaveStyle              : SaveIncrementally

dir

### Expected behavior

File **Windows PowerShell ISE Host_history.txt** is exists.

### Actual behavior

File **Windows PowerShell ISE Host_history.txt** doesn't exist or empty.

**Comment by daxian-dbw** [comment]
PSReadLine works only in terminal/console, not in the ISE. ISE is a WPF application that doesn't rely on terminal/console for input.

**Comment by nyukers** [comment]
I think so, but filename **Windows PowerShell ISE Host_history.txt** was surpised me.

**Comment by daxian-dbw** [comment]
The file gets created when PSReadLine is imported, using the host name.
