### ISSUE TITLE
Scrollable list view with more than 10 items does not work without plugins

### ISSUE THREAD

**Issue by brajjan** [PowerShell/PSReadLine#3620]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.3.3
PS HostName: ConsoleHost
PSReadLine Version: 2.3.0-beta0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 237
BufferHeight: 9001
```

### Steps to reproduce

Set-PSReadLineOption -PredictionSource History

### Expected behavior

Scrollable list view with more than 10 items does not work without plugins. 
If you have PredictionSource set to History it will not generate more than 10 items. 
When installing additional module for prediction and you configure PredictionSource to HistoryAndPlugin the listview will show more than 10 items and is scrollable

### Actual behavior

Only lists 10 items when only using History

**Comment by im-aIex** [comment]
For me it seems even with HistoryAndPlugin, using CompletionPredictor, it only ever shows 10 results.

**Comment by daxian-dbw** [comment]
This is by design for the history results. For history, in general it's way less relevant beyond the first 10 matches, so it only gives back 10 results at most.

For the `CompletionPredictor`, it should now return all matches it can get. The issue https://github.com/PowerShell/CompletionPredictor/issues/17 was opened to track that change.

**Comment by kasini3000** [comment]
1 view with console hight
2 prv/next key need define.

**Comment by dominikjeske** [comment]
@daxian-dbw 10 items in history is very small especially if you have many commands that differ on the end. Is it possible to change this default for history?
