### ISSUE TITLE
Bugging error in python

### ISSUE THREAD

**Issue by Thuzar26** [PowerShell/PSReadLine#3621]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 7 Keys:
 & Space C : / U s

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
aultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)        
 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

N/A

### Environment data

```console
i do not know
```

### Steps to reproduce

def palindromes(s):
    return s == s[::-1]
def main():
    while True:
        s = input("Please type in a palindrome: ")
        if palindromes(s):
            print(s, "is a palindrome!")
            break
        else:
            print("that wasn't a palindrome")

### Expected behavior

running the code and get the result.

### Actual behavior

Actual value was -2.

**Comment by daxian-dbw** [comment]
No environment data is provided, so it's impossible to tell for sure if this was fixed. However, we did fix a lot of issues that would result in the same error, so it's recommended for you to upgrade to the latest stable version v2.2.6. See upgrade instructions in https://github.com/PowerShell/PSReadLine#upgrading.
