### ISSUE TITLE
DefaultAddToHistoryHandler filters too aggressively

### ISSUE THREAD

**Issue by lukeschlather** [PowerShell/PSReadLine#3633]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

So, per https://github.com/PowerShell/PSReadLine/issues/1459 I don't really think this list of things to filter is a good heuristic. I often do things like:

```
$env:token = command-which-outputs-token ; command-which-requires-token-to-function
```

This filter breaks any sort of idiom like that since depending on the context it might be $env:secret, $env:password, or whatever. I just disable this and I don't think it should be on by default.

### Proposed technical implementation details (optional)

Turn off this heuristic, it is very surprising behavior and doesn't really accomplish the intended goal.

**Comment by daxian-dbw** [comment]
Can you please provide some of real command lines that you use to demonstrate the problem?
BTW, you can always turn off the heuristic by `Set-PSReadLineOption -AddToHistoryHandler { $true }` or `Set-PSReadLineOption -AddToHistoryHandler $null`.

**Comment by lukeschlather** [comment]
`kubectl get secret` is one command that triggers the heuristic but doesn't include any secrets in the command.

Another example is the command `gcloud auth print-access-token` which doesn't include any secret info that needs to be filter (similarly `az account get-access-token` does the same thing.)

This isn't a great example but for authenticating to a postgres database in Google Cloud I will do like `$env:PGPASS= gcloud auth print-access-token` I can't think of an example that uses the string "password" off the top of my head but it's the same basic idea, I do it a fair amount.

I know it can be disabled but I think it's a bad default.

**Comment by daxian-dbw** [comment]
@lukeschlather Thanks for the context.

Note to the team: https://github.com/PowerShell/PSReadLine/blob/1e84d68248e429448d2427d34d6efc2a2806d824/PSReadLine/History.cs#L571 needs to be updated to handle retrieving token with [gcloud](https://cloud.google.com/sdk/gcloud/reference/auth/print-access-token), with Azure ([both az cli and Az PowerShell](https://learn.microsoft.com/en-us/azure/healthcare-apis/get-access-token?tabs=azure-cli)), and with `kubectl` (both [`get secret` and `describe secret`](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/)).
