### ISSUE TITLE
PSreadline/issues/new

### ISSUE THREAD

**Issue by gift335** [PowerShell/PSReadLine#3647]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

how do i update my PSreadline

**Comment by ThomasNieto** [comment]
Install-Module PSReadline

or once powershellget is managing it:

Update-Module

**Comment by gift335** [comment]
Thank you for your response!!

**Comment by gift335** [comment]
I have been running my avatarify data on minconda . When it's gets to
solving environment it can load up to 8 hours what's causing that???
