### ISSUE TITLE
History in ISE

### ISSUE THREAD

**Issue by Slion** [PowerShell/PSReadLine#365]
Is there a way to get that persistent history working in ISE?

**Comment by lzybkr** [comment]
Not with PSReadline - PSReadline only supports console hosts.  You could open a suggestion on https://windowsserver.uservoice.com/forums/301869-powershell.  You might also check ISESteriods - if ISESteroids doesn't have persistent history, I'll bet they'd add it.

**Comment by vors** [comment]
You can also try my module https://github.com/vors/PersistentHistory
