### ISSUE TITLE
Strange behavior when using Start-Process with -NonNewWindow

### ISSUE THREAD

**Issue by tbergstedt** [PowerShell/PSReadLine#366]
We have created scripts that launch executables (in this particular case: MSBuild.exe) with `Start-Process` and parameter `-NoNewWindow`. When PSReadline module is enabled and we execute such scripts, the command prompt jumps back to the row after the command execution in window buffer, ignoring all output from Start-Process. This makes the Powershell window starting to overwrite the previous output, which becomes very "messy" and hard to read. 

Example:
Starting command:
`PS C:\TFS\Platform> Start-Process -FilePath 'msbuild.exe' -argumentlist @('Platform.sln','/t:Clean') -NoNewWindow`

End of command execution (command prompt at square below):
`PS C:\TFS\Platform> Start-Process -FilePath 'msbuild.exe' -argumentlist @('Platform.sln','/t:Clean') -NoNewWindow`
`PS C:\TFS\Platform> Microsoft (R) Build Engine version 12.0.40629.0`
`PS C:\TFS\Platform>`:white_medium_small_square:`ersion 4.0.30319.42000]`
`Copyright (C) Microsoft Corporation. All rights reserved.`
`...`

When I skip using `Start-Process` (or unload PSReadline), the output behaves as expected:
`PS C:\TFS\Platform> msbuild Platform.sln "/t:Clean"`
`...`
`Build succeeded.`
`0 Warning(s)`
`0 Error(s)`
` `
`Time Elapsed 00:00:04.17`
`PS C:\TFS\Platform>` :white_medium_small_square:

Using module version 1.2 on WIndows 8.1 with WMF 5.0.

**Comment by lzybkr** [comment]
I see a similar problem without PSReadLine but with `Start-Process`. It looks like (and seems sort of obvious I guess) that `Start-Process` starts the process in a non-blocking manner.

If you add `-Wait`, then it works as you expect.
