### ISSUE TITLE
Comnination of Ctrl+Space not working for "Get-" in Windows Terminal for native PowerShell (PowerShell 5.1)

### ISSUE THREAD

**Issue by Hoadi** [PowerShell/PSReadLine#3663]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [x] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oups, un problème s'est produit. Signalez ce bogue avec les détails ci-dessous.
Signaler sur GitHub : https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Dernières 11 touches :
 c d Space \ Enter
 G e t - Ctrl+Space y

Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
La valeur réelle était -92.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   à Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   à Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   à Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![Capture d’écran 2023-04-22 231136](https://user-images.githubusercontent.com/59395492/233839385-60ca6530-0f2e-4d60-88bc-9c3b2848c5a7.png)
![Capture d’écran 2023-04-22 231221](https://user-images.githubusercontent.com/59395492/233839388-a52073ad-26e8-42b9-84b0-9839d041808a.png)

### Environment data

```console
PS version : 5.1
PSReadLine Version : 2.2.6
OS : Windows 10 Pro 22H2
```

### Steps to reproduce

- Open Windows Terminal
- Type "Get-"
- Type Ctrl + Space combination
- Choose and type "y" for yes

### Expected behavior

List of all cmdlets beginning with "Get-"

### Actual behavior

Oups, un problème s'est produit. Signalez ce bogue avec les détails ci-dessous.
Signaler sur GitHub : https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Dernières 11 touches :
 c d Space \ Enter
 G e t - Ctrl+Space y

Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
La valeur réelle était -92.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   à Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   à Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   à Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by Hoadi** [comment]
PSReadLine is 2.2.6 as I stated.

**Comment by Hoadi** [comment]
> @Hoadi, you were using a pretty old version of PSReadLine (2.0.0-beta2 or prior), and it's likely that the issue was fixed in a newer version. Please upgrade to the [2.2.6 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) from PowerShell Gallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

PSReadLine is 2.2.6 as I stated.
And the error is occuring in Windows Terminal, not when PowerShell.exe is executed.

**Comment by daxian-dbw** [comment]
> Signaler sur GitHub : https://github.com/lzybkr/PSReadLine/issues/new

This URL displayed in your screenshot and exception report indicates that you were using the PSReadLine version 2.0.0-beta2 or prior. Newer versions of PSReadLine doesn't report that URL. Please upgrade to the latest version and try again.
