### ISSUE TITLE
Tooltip `f4` crashes with latest preview on Windows Machine

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/PSReadLine#3678]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environmentproperties of a virtual machine.
PSReadLine: 2.3.1-beta1upName powershell -Name 'ContosoVM07'                          [Az Predictor]
PowerShell: 7.3.4'ContosoVM07'                                                        [Az Predictor]
OS: Microsoft Windows 10.0.22621wershell -Name 'ContosoVM07' -Status                  [Az Predictor]
BufferWidth: 120urceGroupName powershell                                              [Az Predictor]
BufferHeight: 31

Last 200 Keys:

 DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow UpArrow Spacebar DownArrow DownArrow DownArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace V M DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Spacebar Ctrl+z Ctrl+z DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace N e w - A z V Backspace DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow F4 c Enter
 c l e a r Enter
 G e t - A z V M DownArrow DownArrow DownArrow DownArrow F4

### Exception

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.PowerShell.Pager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.PowerShell.Pager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Microsoft.PowerShell.PSConsoleReadLine.Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.RenderFullHelp(String content, String regexPatternToScrollTo)
   at Microsoft.PowerShell.PSConsoleReadLine.ShowFullPredictionTooltip(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

Note the exception clobbered with the ListView predictions as can be seen in screenshot below:

![image](https://github.com/PowerShell/PSReadLine/assets/20605456/4b61e365-3774-4798-9320-b55439d3e09b)

### Environment data

```console
PS Version: 7.3.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.1-beta1
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 31
```

### Steps to reproduce

Seems somehow in my install in PowerShell that the `Microsoft.PowerShell.Pager` is not installed? 

- Listview with Predictor Source being history and plugin
- select a prediction result with arrow keys
- press f4 to show the tool tip in alternate screen buffer
- Crashes

This works fine on my Mac with same PS and PSRL version.

### Expected behavior

Shows the expanded tooltip in the alternate screen buffer

### Actual behavior

Crashes with exception above

**Comment by daxian-dbw** [comment]
@StevenBucher98 Can you please provide detailed repro steps? I cannot reproduce the issue on my Windows 11 machine (Version 22H2, OS Build 22621.1702).

**Comment by StevenBucher98** [comment]
@daxian-dbw I am not sure what else I did to cause this. Somehow the `Microsoft.PowerShell.Pager` assembly got removed? However I am struggling to find information about how to get that package back. I was uninstalling PSRL beta0 and reinstalling beta1 and that seems like the only thing that _may_ have caused this? Trying out some different cases with PSGetv2 and v3 since I was using both but suspect it may be some bug with my Windows VM module path? Will update if I find something more reproducable

**Comment by StevenBucher98** [comment]
I think somehow one of the folders $env:PSModulePath got messed up and was desynced with the module path on my Mac and Windows VM so it wasn't working exactly as expected? Completely deleted the file and reinstalled the module and it works fine now. Very odd.

**Comment by daxian-dbw** [comment]
> I was uninstalling PSRL beta0 and reinstalling beta1 and that seems like the only thing that may have caused this?

Hmm, maybe a bug in PowerShellGet/PSResourceGet? It would be nice if you can reproduce this.
