### ISSUE TITLE
Powershell error

### ISSUE THREAD

**Issue by hsuyanto** [PowerShell/PSReadLine#368]
Using Powershell within Windows Container:
Type Powershell on the command line, tried to get the previous command (thought still at Command Prompt) then Powershell returns:
Last 3 Keys: 
UpArrow UpArrow g

Exception:
System.ComponentModel.Win32Exception (0x80004005): Incorrect Function

**Comment by lzybkr** [comment]
This no longer repros - probably a fix in containers as lots has changed.
