### ISSUE TITLE
CancellationToken does not cancel ReadLine until a character has been pressed

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PSReadLine#3693]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Not an exception
```

### Screenshot

Nothing to show here

### Environment data

```console
PS Version: 7.3.4
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 146
BufferHeight: 40
```

### Steps to reproduce

Sample app

```
#!/usr/bin/env pwsh

Import-Module PSReadLine

$runspace=[System.Management.Automation.Runspaces.Runspace]::DefaultRunspace

$cancellationTokenSource = New-Object -Type System.Threading.CancellationTokenSource
$cancellationTokenSource.CancelAfter(5000)
$cancellationToken = $cancellationTokenSource.Token
try
{
	$line = [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($runspace,$executionContext,$cancellationToken,$null)

	$line
}
finally
{
	$cancellationTokenSource.Dispose()
}
```

The sample app should exit after 5 seconds ( or so ) but requires a key to be pressed before `ReadLine` detects the cancellation

### Expected behavior

ReadLine should respect the cancellation and return immediately and in good order.

### Actual behavior

App hangs until a key is pressed

**Comment by daxian-dbw** [comment]
This is by design because `Console.ReadKey` cannot be cancelled.
To workaround this, PS VSCode extension (integrated terminal) has to override the `ReadKey` method with a custom implementation in a hacky way.

**Comment by andyleejordan** [comment]
Here is that hacky workaround we use:

https://github.com/PowerShell/PowerShellEditorServices/blob/89ce0867c6b119bef8af83ab21c249e10d0e77a2/src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs#L1378-L1408
