### ISSUE TITLE
Predictive History does not work with code on multiple lines

### ISSUE THREAD

**Issue by fullenw1** [PowerShell/PSReadLine#3697]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/23318240/1b437d51-3d7b-4aec-9d59-74b6feb370a1)

### Environment data

```console
PS Version: 7.3.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 209
BufferHeight: 51
```

### Steps to reproduce

1. Type a command line split among two or more lines
2. Type the start of the preceding line
3. Notice that the command line of step 1 does not appear in the predictive history of step 2

### Expected behavior

The predictive history should also display results matching to command lines split among several lines.

### Actual behavior

The predictive history only display results matching to command lines typed on a single line.

**Comment by daxian-dbw** [comment]
This is by design. Multi-line text doesn't play well with the inline view and list view, so history entries with multi-line text are excluded. To search for multi-line history text, use <kbd>Ctrl+r</kbd> for history searching.
