### ISSUE TITLE
Remove auto insertion of trailing separator

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PSReadLine#3699]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

Assuming this: https://github.com/PowerShell/PowerShell/pull/19518 gets merged, the current behavior of adding a separator for containers is made redundant because PowerShell will handle this internally and the PSReadLine implementation will interfere with user choice (users using a different separator, or attempting to turn the feature off).  
PS 5.1 users may still want this feature so maybe it should check the PS version, or a user option should be added to configure this setting.

**Comment by daxian-dbw** [comment]
The https://github.com/PowerShell/PowerShell/pull/19518 was closed, so closing this one for now.
