### ISSUE TITLE
Copy-paste of large body of code can't be interrupted

### ISSUE THREAD

**Issue by FallenGameR** [PowerShell/PSReadLine#37]
Repro 
- copy large body of a Powershell script (~100 lines).
- paste into the console and watch it paint itself
- try to cancel with Ctrl+C - nothing happens, the text would still slowly appear on the screen

And pasting takes significant amount of time. You can see chars appearing one by one as if there is 100ms delay between each character render.

**Comment by lzybkr** [comment]
Closing in favor of #579 which covers all of the known issues with right-click paste.
