### ISSUE TITLE
Fail to connect Anaconda with VSCode | 无法将anaconda与VSCode链接配置

### ISSUE THREAD

**Issue by ZnCu7** [PowerShell/PSReadLine#3706]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS D:\学习\temp>
 C:/Users/asus/anaconda3/Scripts/activate
PS D:\学习\temp> conda activate base
conda : 无法将“conda”项识别
为 cmdlet、函数、脚本文件或可
运行程序的名称。请检查名称的 
拼写，如果包括路径，请确保路 
径正确，然后再试一次。       
所在位置 行:1 字符: 1        
+ conda activate base        
+ ~~~~~
    + CategoryInfo
   : ObjectNotFound: (conda  
  :String) [], CommandNotF   
 oundException
    + FullyQualifiedErrorId  
   : CommandNotFoundExcepti  
  on
 
PS D:\学习\temp>  & 'C:\Users\asus\anaconda3\p哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 111 个密钥:
 C : / U s e r s / a s u s / a n a c o n d a 3 / S c r i p t s / a c t i v a t e Enter    
 c o n d a Space a c t i v a t e Space b a s e Enter        
 Space & Space ' C : \ U s e r s \ a s u s \ a n a c o n d a 3 \ p y t h o n . e x e ' Space ' c : \ U s e r s \        

异常:
System.ArgumentOutOfRangeException: 该值必须大于或
等于零，且必须小于控制台缓冲区在该维度的大小。    
参数名: left
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)      
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\学习\temp> asus\.vscode\extensions\ms-python.python-2023.9.11461009\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '59749' '--' 'd:\学习\temp\test.py'

>> c:\Users\
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息 
。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 113 个密钥:
 C : / U s e r s / a s u s / a n a c o n d a 3 / S c r i p t s / a c t i v a t e Enter
 c o n d a Space a c t i v a t e Space b a s e Enter
 Space & Space ' C : \ U s e r s \ a s u s \ a n a c o n d a 3 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ Ctrl+x Ctrl+v

异常:
System.ArgumentOutOfRangeException: 该值必须大于或
等于零，且必须小于控制台缓冲区在该维度的大小。    
参数名: top
实际值是 -7。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)      
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by ZnCu7** [comment]
补充：确认已经安装了anaconda，并设置环境变量
![image](https://github.com/PowerShell/PSReadLine/assets/130061349/84b50fc2-173f-412a-8946-4071f3b0bd23)
![image](https://github.com/PowerShell/PSReadLine/assets/130061349/4856cf6e-091f-473a-a457-5cc8c13956d3)

**Comment by ZnCu7** [comment]
It shows like this↓
![image](https://github.com/PowerShell/PSReadLine/assets/130061349/f963effc-8b19-4467-b5bf-c573d0ad0927)

**Comment by daxian-dbw** [comment]
You may want to try `Install-Module -Name PSReadLine -RequiredVersion 2.2.6 -Scope CurrentUser`. Without specifying `-Scope CurrentUser`, it will attempt to install the package to your all user location which requires administrator privilege.
