### ISSUE TITLE
Documentation regarding Windows 10 is wrong.

### ISSUE THREAD

**Issue by beruic** [PowerShell/PSReadLine#372]
The documentation states

> If you are on Windows 10, PSReadline is already installed. At this time, you should not use Install-Module or Update-Module because there is not a newer version available for Windows 10.

Which is wrong. The version that comes with Windows 10 is 1.1,  and furthermore, it somehow doesn't support Vi mode.

**Comment by srdubya** [comment]
PSReadline did not have Vi mode in it when it shipped with Windows 10.  At that time it had "regular" mode and Emacs mode.  Vi mode was under development and not quite ready.  Some future release of Windows 10 will get an updated version of PSReadline with Vi mode baked in, but for now we need to roll our own.

**Comment by lzybkr** [comment]
I do need to update the readme.  Vi mode is included in 1.2, which can be installed on Win10 with `Install-Module -Force PSReadline`.

If you are a Windows insider, you might already have 1.2 - the fast ring builds have it.

**Comment by beruic** [comment]
Well, my point is also just that there _is_ a newer version available for Windows 10. Perhaps the readme should state that the newest stable version is included in Windows 10 (and will always be?) :)
