### ISSUE TITLE
Hot to perform Ctrl + Space auto-completion using Tab

### ISSUE THREAD

**Issue by Z-Clive** [PowerShell/PSReadLine#373]
I have tried this command:

`Set-PSReadlineKeyHandler -Key Tab -Function Complete`

and after hit `Tab`, it'll just give a full approved list for entering. 

However, when hit `Ctrl + Space`, it not only gives a complete list, but also let one to tab through or use arrow key for selection.

So I'm wondering if there's a way to perform the `Ctrl + Spce` completion using `Tab` key?

**Comment by lzybkr** [comment]
The key binding `Alt+?` is bound to `WhatIsKey`.  If you type that, then `Ctrl+Space`, you can see the what `Ctrl+Space` is bound to, and you'll see that it is bound to `MenuComplete`.  So you can do:

```
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
```
