### ISSUE TITLE
Blacklisted sensitive keywords for history 

### ISSUE THREAD

**Issue by Still34** [PowerShell/PSReadLine#3732]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

Currently, PSReadLine supports filtering of potentially sensitive keywords such as passwords and tokens out of the box. It would be nice if there is a way to add on to this by setting a PSReadLineOption property that takes a case insensitive blacklisted keywords to prevent them from being saved to the history file.

**Comment by StevenBucher98** [comment]
You can add your own specifications to what to add or not to history file via the `-AddToHistoryHandler` in PSReadLineOptions. Here is an example of how you can use it, its just a simple one to exclude any commands that start with git:
```powershell
$ScriptBlock = { 
    Param([string]$line) 
  
    if ($line -match "^git") {
        return $False
    }
    else {
        return $True
    } 
}
Set-PSReadLineOption -AddToHistoryHandler $ScriptBlock
```
Let us know if this will work for you!

**Comment by Still34** [comment]
Ah right, thanks for the tip! I couldn't find any similar topics in the issue; hopefully this helps others as well.
