### ISSUE TITLE
resolve errors

### ISSUE THREAD

**Issue by fajarnas** [PowerShell/PSReadLine#3737]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

how to solve the problem after installing windows powershell
![Gambar WhatsApp 2023-07-07 pukul 22 06 09](https://github.com/PowerShell/PSReadLine/assets/124814792/05d0c8b5-2f0c-4978-b6c3-46d93ae623e8)

**Comment by daxian-dbw** [comment]
This is not related to this repo.
