### ISSUE TITLE
AcceptSuggestion also built-in to EndOfLine

### ISSUE THREAD

**Issue by terlar** [PowerShell/PSReadLine#3741]
### Summary of the new feature / enhancement

As a user I want to accept the proposed suggestion when going to the end of line

### Proposed technical implementation details (optional)

Just like `AcceptSuggestion` is built-in to `ForwardChar` I would propose it would be handled the same way for `EndOfLine`.

**Comment by StevenBucher98** [comment]
Just so I understand correctly, are you suggesting having `AcceptSuggestion` be also triggered when you hit the `End` Key? If so you can bind `AcceptSuggestion` to `End` key to get this behavior.
`Set-PSReadLineKeyHandler -Chord Enter -Function ValidateAndAcceptLine`

**Comment by daxian-dbw** [comment]
I believe the ask is to make `End` key complete the suggestion in addition to its current behavior -- when the cursor is not at the end of the current text, `End` moves the cursor to the end of the text; when the cursor is at the end, `End` accepts the current inline suggestion.

**Comment by terlar** [comment]
Sorry, I completely missed that this ticket had replies and then I was travelling.

Yes, that interpretation is correct, basically how we have this same behavior for `ForwardChar` and many other operations to move forward.

I do already have a workaround:
```powershell
Set-PSReadLineKeyHandler -Chord 'Ctrl+e' -ScriptBlock {
  [Microsoft.PowerShell.PSConsoleReadLine]::AcceptSuggestion()
  [Microsoft.PowerShell.PSConsoleReadLine]::EndOfLine()
}
```

However, I do think it should be the default behavior, hence me opening this issue.

**Comment by daxian-dbw** [comment]
Close as a duplicate of #3705
