### ISSUE TITLE
git commit giving error when " or ' key is pressed

### ISSUE THREAD

**Issue by shantanuSakpal** [PowerShell/PSReadLine#3742]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
When i stage the modified files using add . it works fine.
but when i try to commit using "git commit -m "message" ", the moment i press " , there is a error.

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or e
qual to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int3
2 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData re
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
 Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyIn
fo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object ar
g)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
, EngineIntrinsics engineIntrinsics)

i am using webstorm ide , version 2023.1.3
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/108987556/88ed06e2-619f-4898-804c-e093ad1794d6)
![image](https://github.com/PowerShell/PSReadLine/assets/108987556/de40dac4-9c16-4b8a-ac93-1ca520107ab6)

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 71
BufferHeight: 26
```

### Steps to reproduce

1. open webstorm ide, modify the files, add them to staging area ( use git add .)
2. then type "git commit -m" 
3. the moment you press the " key, the above exception is thrown.

### Expected behavior

No exception.

### Actual behavior

The above exception happens

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.2.6 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
