### ISSUE TITLE
How to customize ListView

### ISSUE THREAD

**Issue by yorkeJohn** [PowerShell/PSReadLine#3743]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

Documentation does not cover how to customize the ListView. I want to remove this part:
![image](https://github.com/PowerShell/PSReadLine/assets/12224398/5286f119-e7c0-41ad-8ae6-50326943aa94)

**Comment by daxian-dbw** [comment]
That metadata line cannot be removed from the list view, and that's a by-design behavior.
It shows the needed information about the source and number of results, which is especially useful when predictor plugin is used or when the terminal height is not big enough to show all the results in one page.
