### ISSUE TITLE
Tab MenuCompletion didn't work

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [PowerShell/PSReadLine#3747]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
I already add line `Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete` in `$PROFILE`. However it doesn't work.
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/52443370/c0516d07-253f-4daf-8fda-7e4e03348e6d)
![image](https://github.com/PowerShell/PSReadLine/assets/52443370/e9d84a47-65b4-4032-b76e-05d501a407aa)
![image](https://github.com/PowerShell/PSReadLine/assets/52443370/392e699a-7f3a-4a86-8ca4-dd58e2fd2133)

### Environment data

```console
PS Version: 7.3.6
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 90
BufferHeight: 21
```

### Steps to reproduce

1. code $PROFILE

2. add line `Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete` in $PROFILE. Saved.

3. reopen Powershell

### Expected behavior

![image](https://github.com/PowerShell/PSReadLine/assets/52443370/76a00fb8-ae56-4414-87ef-3d66f64f6335)

### Actual behavior

![image](https://github.com/PowerShell/PSReadLine/assets/52443370/aac0bf4b-74f0-4502-9641-7c667fb97356)
No menucompletion

**Comment by daxian-dbw** [comment]
I cannot reproduce this locally (see the GIF below) with the specified repro steps.

![repro-ws-2022](https://github.com/PowerShell/PSReadLine/assets/127450/42ca00b9-191c-4095-8283-6c47a990e136)

Can you simply run `Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete` in your PS session and see if that works as expected? Also, please try this without loading your profile (starts by `pwsh -noprofile`) to rule out the possible influence from the other code within your profile.

**Comment by Michaelzhouisnotwhite** [comment]
> I cannot reproduce this locally (see the GIF below) with the specified repro steps.
> 
> ![repro-ws-2022](https://user-images.githubusercontent.com/127450/255702546-42ca00b9-191c-4095-8283-6c47a990e136.gif)
> 
> Can you simply run `Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete` in your PS session and see if that works as expected? Also, please try this without loading your profile (starts by `pwsh -noprofile`) to rule out the possible influence from the other code within your profile.

![image](https://github.com/PowerShell/PSReadLine/assets/52443370/ed447a7e-1090-497c-927e-7bd69e3a58e9)
after I enter this `Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete` ,it works. But I can't find the bug in $PROFILE. It does not have any effect when pwsh.exe is started. the code below is my $PROFILE:

```pwsh
Import-Module gsudoModule
Import-Module posh-git
Import-Module PSReadLine
Import-Module dircolors
Import-Module Terminal-Icons
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\tokyonight_storm.omp.json" | Invoke-Expression


$env:Path += ";C:\Users\tssh\Documents\PowerShell\Modules"
$env:Path += ";C:\Users\tssh\AppData\Local\Android\Sdk\platform-tools"
Import-Module PSFzf

# set PowerShell to UTF-8
# [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete
Set-PSReadLineKeyHandler -Chord UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Chord DownArrow -Function HistorySearchForward
Set-PSReadLineKeyHandler -Chord 'Ctrl+d' -Function DeleteChar
Set-PSReadLineOption -PredictionSource HistoryAndPlugin
Set-PSReadLineOption -PredictionViewStyle ListView

$PSReadLineOptions = @{
    EditMode            = "Windows"
    HistoryNoDuplicates = $true
    Colors              = @{
            InlinePrediction = "#858585"
            Parameter        = "969696"
    }
}
Set-PSReadLineOption @PSReadLineOptions

Set-PSReadLineOption -BellStyle None
Set-PSReadLineKeyHandler -Key Shift+Tab -Function SwitchPredictionView
Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+f' -PSReadlineChordReverseHistory 'Ctrl+r'
function WhereCommand {
    param($Cmdlet)
    Get-Command -Name $Cmdlet -ErrorAction SilentlyContinue |
    Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue
}
function NewItem {
    param ($Cmdlet)
    New-Item -Path $Cmdlet -ItemType file
}
function GetPath {
    Get-Location -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue
}
function ls_linux { 
    Get-ChildItem $args | Format-Wide -AutoSize
}
function lsh_linux { 
    Get-ChildItem $args -Hidden | Format-Wide -AutoSize
}

function lsa_linux { 
    Get-ChildItem $args -Force | Format-Wide -AutoSize
}

Set-Alias -Name touch -Value NewItem
Set-Alias -Name which -Value WhereCommand
Set-Alias -Name ls -Value ls_linux -Option AllScope
Set-Alias -Name lsa -Value lsa_linux -Option AllScope
Set-Alias -Name lsh -Value lsh_linux -Option AllScope
Set-Alias pwd GetPath

```

**Comment by daxian-dbw** [comment]
In you case, I suggest you starting from an empty profile with only `Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete` in it, and gradually adding back the other configurations from your original profile, and figure out where it starts to fail. Then, you will have a minimal repro for the issue. Once you have the minimal repro, please share it here.

**Comment by Michaelzhouisnotwhite** [comment]
> In you case, I suggest you starting from an empty profile with only `Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete` in it, and gradually adding back the other configurations from your original profile, and figure out where it starts to fail. Then, you will have a minimal repro for the issue. Once you have the minimal repro, please share it here.

That's a great way to find the problems. Thx. I think the problems is `Set-PSReadLineOption @PSReadLineOptions` overwrite the previous configuration. `EditMode            = "Windows"` will overwrite `Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete`. 

Before:
```ps1
Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete
Set-PSReadLineKeyHandler -Chord UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Chord DownArrow -Function HistorySearchForward
Set-PSReadLineKeyHandler -Chord 'Ctrl+d' -Function DeleteChar
Set-PSReadLineOption -PredictionSource HistoryAndPlugin
Set-PSReadLineOption -PredictionViewStyle ListView
$PSReadLineOptions = @{
    EditMode            = "Windows"
    HistoryNoDuplicates = $true
    Colors              = @{
            InlinePrediction = "#858585"
            Parameter        = "969696"
    }
}
Set-PSReadLineOption @PSReadLineOptions

```
After:
```ps1
$PSReadLineOptions = @{
    EditMode            = "Windows"
    HistoryNoDuplicates = $true
    Colors              = @{
            InlinePrediction = "#858585"
            Parameter        = "969696"
    }
}
Set-PSReadLineOption @PSReadLineOptions
Set-PSReadLineKeyHandler -Chord Tab -Function MenuComplete
Set-PSReadLineKeyHandler -Chord UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Chord DownArrow -Function HistorySearchForward
Set-PSReadLineKeyHandler -Chord 'Ctrl+d' -Function DeleteChar
Set-PSReadLineOption -PredictionSource HistoryAndPlugin
Set-PSReadLineOption -PredictionViewStyle ListView
```
