### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Suraj9954** [PowerShell/PSReadLine#3748]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 115 Keys:
 c d Space " c : \ U s e r s \ s u r a 
j Space k u m a r \ D e s k t o p \ C o d i n g \ C + + \ 1 3 O O P s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space 1 b a s i c . c p p Space - o Space 1 b a s i c Space } Space ; Space i f Space ( $ ? ) Space { Space 
. \ 1 b a s i c Space } Enter
```

### Screenshot

![Screenshot (163)](https://github.com/PowerShell/PSReadLine/assets/130101484/517f5ab5-ba27-47a2-a876-40aa2b4871dd)

### Environment data

```console
#include <iostream>
using namespace std;

class Hero{

    //properties
    private:
    int health;
    
    public:
    char level;

    void print(){
        cout << "Health: " << health << endl;
        cout << "Level: " << level << endl;
    }

    // getter - setter
    int getHealth(){
        return health;
    }

    char getLevel(){
        return level;
    }

    void setHealth(int h){
        health = h;
    }

    void setLevel(char ch){
        level = ch;
    }


};

int main(){

    Hero h1;
    h1.setHealth(12);
    h1.setLevel('A');

    h1.print();
    return 0;
}
```

### Steps to reproduce

#include <iostream>
using namespace std;

class Hero{

    //properties
    private:
    int health;
    
    public:
    char level;

    void print(){
        cout << "Health: " << health << endl;
        cout << "Level: " << level << endl;
    }

    // getter - setter
    int getHealth(){
        return health;
    }

    char getLevel(){
        return level;
    }

    void setHealth(int h){
        health = h;
    }

    void setLevel(char ch){
        level = ch;
    }

};

int main(){

    Hero h1;
    h1.setHealth(12);
    h1.setLevel('A');

    h1.print();
    return 0;
}

### Expected behavior

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### Actual behavior

Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.2.6 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
