### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by xthr0** [PowerShell/PSReadLine#3752]
### Prerequisites

- [X] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [ ] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Среда
PSReadLine: 2.0.0
PowerShell: 5.1.22621.1778
ОС: Microsoft Windows 10.0.22621
Последние 27 ключей

 Ctrl+v Backspace Enter
 Ctrl+v Backspace Enter
 Alt+4 Alt+F4 UpArrow DownArrow DownArrow Alt+4 Alt+3 Alt+2 Alt+1 Backspace Alt+1 Alt+2 Alt+3 Alt+4 Alt+5 Alt+6 Alt+7 Alt+8 Alt+9 Alt+0 Alt+q
```

### Исключение
```
System.OutOfMemoryException: Выдано исключение типа "System.OutOfMemoryException".
   в System.String.CtorCharCount(Char c, Int32 count)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.DigitArgument(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/56479125/6bdbd464-60bc-4592-b745-1e15b9769c66)


### Environment data

```console
PS Version: 5.1.22621.1778
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22621.1991 (WinBuild.160101.0800)
BufferWidth: 237
BufferHeight: 9001
```

### Steps to reproduce

Последние 27 ключей
```
 Ctrl+v Backspace Enter
 Ctrl+v Backspace Enter
 Alt+4 Alt+F4 UpArrow DownArrow DownArrow Alt+4 Alt+3 Alt+2 Alt+1 Backspace Alt+1 Alt+2 Alt+3 Alt+4 Alt+5 Alt+6 Alt+7 Alt+8 Alt+9 Alt+0 Alt+q
```

### Expected behavior

No exception

### Исключение
```
System.OutOfMemoryException: Выдано исключение типа "System.OutOfMemoryException".
   в System.String.CtorCharCount(Char c, Int32 count)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.DigitArgument(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by xthr0** [comment]
### Environment
PSReadLine: 2.2.6
PowerShell: 5.1.22621.1778
OS: Microsoft Windows 10.0.22621
BufferWidth: 120
BufferHeight: 9001

Last 29 Keys:

 LeftWindows LeftWindows Ctrl+v Enter
 Alt+4 Alt+4 UpArrow DownArrow DownArrow Alt+4 Alt+3 Alt+2 Alt+1 Backspace Backspace Backspace Backspace Backspace Alt+1 Alt+2 Alt+3 Alt+4 Alt+5 Alt+6 Alt+7 Alt+8 Alt+9 Alt+0 Alt+q

### Exception

System.OutOfMemoryException: Выдано исключение типа "System.OutOfMemoryException".
   в System.String.CtorCharCount(Char c, Int32 count)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.DigitArgument(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)

**Comment by daxian-dbw** [comment]
`OutOfMemoryException` indicates that the memory is running out for the running process -- there could be various reasons for this to happen and may not be related to PSReadLine itself.
Please update the "repro steps" with detailed steps for us to reproduce locally, otherwise, there is nothing we can do to investigate.
