### ISSUE TITLE
bug: Opa, algo deu errado. Relate este bug com os detalhes abaixo.

### ISSUE THREAD

**Issue by gabrielryanft** [PowerShell/PSReadLine#3759]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Opa, algo deu errado. Relate este bug com os detalhes abaixo.
Relate no GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 200 Chaves:
 d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 3 . 1 2 . 0 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ a d a p t e r Ctrl+Alt+/ . . Ctrl+Alt+/ . . \ d e b u g p y \ l a u n c h e r ' Space ' 6 0 1 3 9 ' Space ' - - ' Space ' C : \ U s e r s \ P c \ O n e D r i v e \ D o c u m e n t o s \ c l o n e s \ p y t h o n \ p r o j p r o p r i o s \ g r o u p i n g l i s t i t e m s . p y ' Space Enter


Exceção:
System.ArgumentOutOfRangeException: O valor deve ser maior ou igual a zero e menor que o tamanho do buffer do console nessa dimensão.
Nome do parâmetro: top
Valor real era -1.
   em System.Console.SetCursorPosition(Int32 left, Int32 top)
   em Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   em Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   em Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   em Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   em Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

python debug console:
![error](https://github.com/PowerShell/PSReadLine/assets/135415258/76791dcf-edc9-40fa-8cb3-fe80d0777afd)

powershell:
![errorinpowershell](https://github.com/PowerShell/PSReadLine/assets/135415258/3bd8dcd1-4af0-4fff-a44b-89b3846622de)

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.3203 (WinBuild.160101.0800)
BufferWidth: 200
BufferHeight: 36
```

### Steps to reproduce

the python code i was running:

from itertools import groupby
from time import sleep
from random import randint, shuffle

def listaAleatoria(lista): 
    lista = ["girafa", "elefante", "zebra", "cabra", "beterraba", "carambolas", "entendo", "caramba", "belos Olhos", "foda-se", "carambola Fruta", "melão", "Arroz", "Maria feia", "beterraba", "terror", "Talentos", "America do Sul", "enriquecer", "Gabriel Totosão!"]
    numeroDItens = randint(9, 19)
    shuffle(lista)
    lista = lista[:numeroDItens]
    return lista

while True:
    lista = list()
    try:
        print("Escolha um: ")
        print(" 1 - Você cria uma lista; ")
        print(" 2 - Usar lista pronta.")
        resposta = int(input("Sua resposta: "))
    except (TypeError, ValueError):
        print("Valor inválido. tente de novo.")
        continue
    if resposta == 1:
        itemsNum = int(input("Número de itens da lista: "))
        for contador in range(1, itemsNum + 1):
            lista.append(input(f"Digite o {contador}° item da lista: "))
    elif resposta == 2:
        lista = listaAleatoria(lista)
    else:
        print("Resposta inválida. Usando lista pronta.")
        listaAleatoria(lista)

    print("\r Organizando lista", end="")
    sleep(0.5)
    print("\r Organizando lista.", end="")
    sleep(0.5)
    print("\r Organizando lista..", end="")
    sleep(0.5)
    print("\r Organizando lista...")
    sleep(0.5)

    lista.sort()
    listasAgrupadas = groupby(lista, key=lambda prim: prim[0])
    for chave, grupo in listasAgrupadas:
        print(chave, list(grupo)) # o grupo tem que estar dentro de uma list() porque ele é um bgl mt estranho (um objeto.) e o list() "traduz" isso.

    while True:
        continuar = str(input('Quer continuar? ( S / N ) '))
        if continuar in "SsNn":
            if continuar in "Nn":
                quit()
            else: break
        else:
            print("Resposta inválida. Tente de novo.")
            continue

### Expected behavior

run the code without errors. (i don't know what i should write.)

### Actual behavior

run the code, but with errors. (i don't know what i should write.)

**Comment by eye942** [comment]
You might want to try [updating ps readline](https://github.com/PowerShell/PSReadLine#upgrading) from 2.0.0-beta2

Looks like a similar issue to https://github.com/PowerShell/PSReadLine/issues/1884

**Comment by daxian-dbw** [comment]
Yeah, please upgrade to the 2.2.6 of PSReadLine. The issue should have been fixed.
