### ISSUE TITLE
System.ArgumentOutOfRangeException from UpArrow

### ISSUE THREAD

**Issue by rob5300** [PowerShell/PSReadLine#3761]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
-----------------------------------------------------------------------
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/6060966/9cdb4f8a-1b90-4e15-abbb-30e63dd398af)

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 188
BufferHeight: 18
```

### Steps to reproduce

IHave debugging terminal open from previously started debugging session (cppvsdbg using "integratedTerminal" with prelaunch task of "rust: cargo build")
End session
Press + to open new terminal (powershell was default)
Kill debugging terminal with bin icon
Press up arrow
Exception was thrown.

### Expected behavior

Last console entry would be shown in input field OR no response.

### Actual behavior

This exception was thrown.
After this exception was thrown pressing Up would then show these commands (most likelly from the previously mentioned debug session):
`PS E:\Rust Projects\vtfx_reader>  & 'c:\Users\rob53\.vscode-insiders\extensions\ms-vscode.cpptools-1.16.3-win32-x64\debugAdapters\vsdbg\bin\VsDebugConsole.exe' '\\.\pipe\Microsoft-VisualStudio-Debug-Console-{28A55BD4-B025-4B18-96F6-6EC0966F2A14}' 'Local\{28A55BD4-B025-4B18-96F6-6EC0966F2A14}' '/AutoExit' `

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.2.6 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
