### ISSUE TITLE
programe is not running

### ISSUE THREAD

**Issue by apoorvacse** [PowerShell/PSReadLine#3765]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS C:\Users\apoor\OneDrive\Desktop\coding>

 cd
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 111 Keys:
 c d Space " c : \ U s e r s \ a p o o r \ O n e D r i v e \ D e s k t o p \ c o d i n g \ c + + \ c Space r e v i s i o n \ " Space ; Space i f Space ( $ ? ) Space { Space g c c Space c j d . c Space - o Space c j d Space } Space ; Space i f Space ( $ ? ) Space { Space . \ c j d Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero 
and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)     
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg) 
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\apoor\OneDrive\Desktop\coding> ^A^A^A^A
```

### Screenshot

![Screenshot (10)](https://github.com/PowerShell/PSReadLine/assets/129685480/0aae7b6c-d8a8-4dcb-9fd7-2b602d058157)

### Environment data

```console
PS Version: 5.1.19041.3031PS HostName: ConsoleHost  
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 26
BufferHeight: 36
```

### Steps to reproduce

#include<stdio.h>
int main(){
    printf("hello world");
    return 0;
}

### Expected behavior

it should give output as hello world

### Actual behavior

oops something is wrong with a wide passage is appearing and redirecting the user to report on github.

**Comment by StevenBucher98** [comment]
Looks like you are on a beta version of PSReadLine, can you try updating to the latest [stable version](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) and see if that works? 
You can run
`Install-Module -Name PSReadLine -RequiredVersion 2.2.6`
To update and will need to restart your shell after the install.

If you are still having problems after the upgrade can you please include better reproduction steps?
