### ISSUE TITLE
Cannot start powershell because of missing file on mac

### ISSUE THREAD

**Issue by jimmymain** [PowerShell/PSReadLine#3768]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.6
OS: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
BufferWidth: 80
BufferHeight: 24

Last 0 Keys:



### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_2044101305'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.6
OS: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
BufferWidth: 80
BufferHeight: 24

Last 0 Keys:

### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_2044101305'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)

### Environment data

```console
PS Version 7.3.6
```

### Steps to reproduce

Open powershell

### Expected behavior

Powershell opens correctly.

### Actual behavior

powershell fails with the above message.

**Comment by jimmymain** [comment]
I cannot run the script because powershell will not even start.
I have uninstalled and reinstalled and that doesn't seem to resolve the issue.

**Comment by jimmymain** [comment]
I there some directory I can remove / reset to resolve this?
I have reinstalled, and renamed the powershell directories in .config and .local and no dice.

I removed /usr/local/share/poweshell too, and reinstalled and it's still the same error.

**Comment by StevenBucher98** [comment]
If you are able to get a working prompt, you can run `Get-PSReadLineOPtion` to get the `HistorySavePath` and delete that?

Have you tried searching for the file `PSReadLineHistoryFile_2044101305` and deleting it off of your system? 

@daxian-dbw is this the known mutex issue on Mac? I can't figure out how to reproduce this.

**Comment by jimmymain** [comment]
I have managed to run the command suggested.
There's a lot out output, and the file in question according to the output is.
/Users/MYNAME/.local/share/powershell/PSReadLine/ConsoleHost_history.txt

I have tried to find the file PSReadLineHistoryFile_2044101305 and cannot find it anywhere on the file system.
I have deleted everything I can find powershell related, and reinstalled from the pkg.

Still the same error.

**Comment by jimmymain** [comment]
Here is some of the output.

```
EditMode                               : Emacs
AddToHistoryHandler                    : System.Func`2[System.String,System.Object]
HistoryNoDuplicates                    : True
HistorySavePath                        : /Users/craigmain/.local/share/powershell/PSReadLine/ConsoleHost_history.txt
HistorySaveStyle                       : SaveIncrementally
HistorySearchCaseSensitive             : False
HistorySearchCursorMovesToEnd          : False
MaximumHistoryCount                    : 4096
ContinuationPrompt                     : >> 
ExtraPromptLineCount                   : 0
PromptText                             : {> }
BellStyle                              : Audible
DingDuration                           : 50
```

**Comment by jimmymain** [comment]
Since the reinstall all I have in ~/.local/share/powershell is an empty modules directory.
There MUST be something else I can delete to get this working again?

Windows 1995 was easier than this.
:-)

Powershell is still kind of working, but I get the missing file message every time I hit return.

Having used various methods I am pretty sure that PSReadLineHistoryFile_2044101305.* does not exist.

**Comment by jimmymain** [comment]
Is there a README or something online somewhere were I can try and remove every history or saved variable from powershell from everywhere and try install again from scratch. Very frustrating.

**Comment by StevenBucher98** [comment]
Ah I found previous issues folks had with the same problem, check out https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631941511 and see if this works for you

**Comment by jimmymain** [comment]
I really thought you had it there.
But alas no.

```
Filesystem   1024-blocks      Used Available Capacity iused      ifree %iused  Mounted on
/dev/disk1s2   488245288 165777580 307951552    35% 1017461 3079515520    0%   /System/Volumes/Data
````
I deleted the powerlog folder in /tmp and that did not help either.

**Comment by jimmymain** [comment]
Ok did the permissions changes on /private/tmp, and now it's working, many thanks after so many searches.

```
Anyway, chmod 777 /private/tmp and chmod +t /private/tmp to fix the permissions and PS now works fine
```
