### ISSUE TITLE
https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by quantedgeresearch** [PowerShell/PSReadLine#3770]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.       
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
```

### Screenshot

Oops, something went wrong.  Please report this bug with the details below.       
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/newOops, something went wrong.  Please report this bug with the details below.       

### Environment data

```console
Oops, something went wrong.  Please report this bug with the details below.       
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
```

### Steps to reproduce

Oops, something went wrong.  Please report this bug with the details below.       
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### Expected behavior

Oops, something went wrong.  Please report this bug with the details below.       
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### Actual behavior

Oops, something went wrong.  Please report this bug with the details below.       
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

**Comment by quantedgeresearch** [comment]
Last 1 Keys:
 &

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)   
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Arvind Pandey\OneDrive\Desktop\Arvind Pandey Data Scientist\Python ML>  "C:/Users/Arvind Pandey/AppData/Local/Microsoft/WindowsApps/python3.10.exe" "c:/Users/Arvind Pandey/OneDrive/Desktop/Arvind Pandey Data Scientist/Python ML/13_MLconfusionmatrix.py"
At line:1 char:78
+ ... on3.10.exe" "c:/Users/Arvind       
Pandey/OneDrive/Desktop/Arvind Pandey    
Da ...
+                 ~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '"c:/Users/Arvind 
Pandey/OneDrive/Desktop/Arvind Pandey 
Data Scientist/Python 
ML/13_MLconfusionmatrix.py"' in 
expression or statement.
    + CategoryInfo          : ParserErr  
   or: (:) [], ParentContainsErrorReco  
  rdException
    + FullyQualifiedErrorId : Unexpecte  
   dToken

**Comment by StevenBucher98** [comment]
Can you please provider more information about the system you are on, PowerShell and PSReadLine version you are on and step by step reproduction steps?

**Comment by daxian-dbw** [comment]
The report URL https://github.com/lzybkr/PSReadLine/issues/new indicates you are using a very old version of PSReadLine. Please upgrade to the latest 2.2.6 and try again.
