### ISSUE TITLE
PSReadLine cannot handle super large history file properly

### ISSUE THREAD

**Issue by ajayguptarrk** [PowerShell/PSReadLine#3771]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System out of memory  and it consume lots of memory when i see in task manager.
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/22616154/7d7e1fd9-c0c7-4477-a99b-747958b9b8ee)

### Environment data

```console
PS Version: 5.1.14393.5582
PS HostName: ConsoleHost
PSReadLine Version: 1.2
PSReadLine EditMode: Windows
OS: 10.0.14393.0 (rs1_release.160715-1616)
BufferWidth: 139
BufferHeight: 3000
```

### Steps to reproduce

Start powershell in visual code or windows it always crashed 

### Expected behavior

always crashed

### Actual behavior

Start powershell in visual code or windows it always crashed

**Comment by StevenBucher98** [comment]
It looks like you are on a pretty old version of PSReadLine, can you try upgrading to the latest stable version (2.2.6) and see if you still come across the issue? You can upgrade by running the following:
`Install-Module -Name PSReadLine -RequiredVersion 2.2.6`
Be sure to restart PowerShell session for changes to take affect

**Comment by ajayguptarrk** [comment]
Hi, I have updated the same but now again the same exception has come.

[image: image.png]

*Thanks and RegardsAjay Kumar Gupta *

**Comment by StevenBucher98** [comment]
@ajayguptarrk I cant seem to see the image you attached to the issue, can you please try to reattach it again? Maybe via GitHub instead of email.

**Comment by ajayguptarrk** [comment]
Please see if you are able to see updated image

**Comment by ajayguptarrk** [comment]
Sure .please find attached image.

**Comment by daxian-dbw** [comment]
@ajayguptarrk I still cannot see the updated image. The image above still shows it's a very old version -- 2.0.0-beta2 or prior indicated by the reporting URL:
![image](https://github.com/PowerShell/PSReadLine/assets/127450/f757a7f1-e25c-4d1c-b87b-4f32022c5639)

**Comment by StevenBucher98** [comment]
Unfortunately it does not seem like we can see the images still @ajayguptarrk

**Comment by ajayguptarrk** [comment]
Sorry there was some issue in uploading image. Please look updated screen shot and let me know if i can do anything else.
![image](https://github.com/PowerShell/PSReadLine/assets/22616154/33cf9388-180b-48a6-908a-c26e2ff13acf)

**Comment by daxian-dbw** [comment]
@ajayguptarrk The size of your history file is too big -- it exceeds the size limit of a generic list in .NET (~2 GB).
We should fix PSReadLine to work with super large history file, but for now, you can easily work around it by deleting some of the early history text from the history file. By default, the history file is saved at `c:\Users\<user-name>\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt` on Windows.

**Comment by kilasuit** [comment]
@daxian-dbw this would be another good reason for [this feature request](https://github.com/PowerShell/PSReadLine/issues/1886) as that would move it outside of .NET limitations

**Comment by daxian-dbw** [comment]
Even after moving to using sqlite for history, the file-based history saving will need to be preserved indefinitely to make it backward compatible. I'm planning to update the code to only read the last 1mb content from the history file, so this issue can be avoided.
