### ISSUE TITLE
Improvements for Push-Location, Pop-Location, Get-Location -stack

### ISSUE THREAD

**Issue by LukasMarsch** [PowerShell/PSReadLine#3775]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

This was first proposed in Powershell/Powershell [#19775](https://github.com/PowerShell/PowerShell/issues/19775). I was redirected here to negotiate who should implement this improvement.

Essentially this is a functionality change to keep in line with the [GNU Bash Reference](https://www.gnu.org/software/bash/manual/html_node/Directory-Stack-Builtins.html) for these particular cmdlets.
This is not a full list of necessary changes to completely adhere to GNU Bash Reference but rather the core features.

## Get-Location -stack
(this should really be a seperate Get-DirectoryStack command)

- first item is always the current directory
- list the stack with indexes [ -v ]
- list single items by index (positive and negative indexing) this could be a positional parameter [ -i | -index ]
- clear the whole stack [ -c | -clear ]

## Pop-Location

- flag to suppress change of directory after removing item [ -n ]
- remove item by index (positive and negative indexing) - positional parameter, default value = 0, [ -i | -index ]

## Push-Location

- flag to suppress change of directory when pushing [ -n ]
- rotating the stack, positional parameter, default value = 0 [ -i | -index ]

**Comment by daxian-dbw** [comment]
`Pop-Location` and `Push-Location` are PowerShell cmdlets, not belonging to the PSReadLine module.
If those improvements are to be made, they should be made in PowerShell.
