### ISSUE TITLE
help about_PSReadLine shows twice

### ISSUE THREAD

**Issue by pfmoore** [PowerShell/PSReadLine#378]
When I enter the command `help about_PSReadLine` I see a list of 2 entries. But because they have the same name, I have no way to access the _actual_ helpfile.

```
>help about_psreadline

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
about_PSReadline                  HelpFile                            SHORT DESCRIPTION
about_PSReadline                  HelpFile
```

If I `remove-module PSReadLine` the help command then shows the PSReadline help, as expected.

PSReadLine version 1.2, from the PowerShell gallery. I did have a previous installation from before having `install-module`, that version was installed by hand but I removed it before switching to using `install-module`.

```
>$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10514.6
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10514.6
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by pfmoore** [comment]
Hmm, when I read the help (now that I can see it!) it says "PSReadline, introduced in Windows PowerShell 5.0". Is PSReadLine built into powershell nowadays? If so, surely trying to manually install it should result in an error, rather than allowing it to be installed but behaving oddly, as noted here?

**Comment by lzybkr** [comment]
I think you have 2 different versions - 1.1 (part of Windows 10) and 1.2 (you installed it). Assuming this is true, I think the PowerShell help system can do a better job with this situation.

**Comment by pfmoore** [comment]
I'm actually using Windows 7, with WMF 5 installed, but I guess it's basically the same situation.

I don't see any way to check the version of the "built in" version, and it seems incomplete - if I remove the version 1.2 module, `Get-Command Set-PSReadLineKeyHandler` says that this is an unknown cmdlet (even though about_PSReadLine mentions it!)

So I guess 2 more questions:
1. Is it correct and acceptable to do `Install-Module PSReadLine -Scope CurrentUser` to get version 1.2 even on WMF 5.0 where an older version is built in? If not, how _do_ I get the later version?
2. Assuming it is OK, how can I read the `about_PSReadLine` helpfile given that the help command won't let me select a specific one of the two it displays?

**Comment by lzybkr** [comment]
Well, not quite - PSReadline is not installed by default with WMF5, it's only included with Win10.

The issue remains though - having 2 versions of the module makes it harder to read the about topic.

The easiest fix is to delete the old version.
You can also just read the file directly - about topics are plain text files, so you can read the help with:

```
cat "$(split-path -parent (gmo psreadline).Path)\en-us\about_psreadline.help.txt" | more
```

or even just view it online here: https://raw.githubusercontent.com/lzybkr/PSReadLine/master/PSReadLine/en-US/about_PSReadline.help.txt

The cmdlet help is also in a fairly readable format online: https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/en-US/PSReadline.md

And yes, you can certainly install new versions exactly as you've done - that's expected to work.

I'm closing and will open an internal bug about help with multiple module versions.  You should feel free to open an issue on uservoice as well if you want to: https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by rkeithhill** [comment]
OK I created a [UserVoice issue ](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13650336-get-help-needs-to-work-better-in-the-face-of-multi) for this .
