### ISSUE TITLE
Me sale esto, no se qué ha pasado

### ISSUE THREAD

**Issue by ggelado** [PowerShell/PSReadLine#3798]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Últimas 200 claves:
 U s e r s Ctrl+Alt+\ U s u a r i o Ctrl+Alt+\ A p p D a t a Ctrl+Alt+\ R o a m i n g Ctrl+Alt+\ C o d e Ctrl+Alt+\ U s e r Ctrl+Alt+\ w o r k s p a c e S t o r a g e Ctrl+Alt+\ 0 c 7 a c f d a 6 6 2 f 4 3 c 9 e 3 2 2 0 7 2 c d b 6 c d 5 6 9 Ctrl+Alt+\ r e d h a t . j a v a Ctrl+Alt+\ j d t _ w s Ctrl+Alt+\ P r á c t i c a s _ 7 6 d b 6 7 7 b Ctrl+Alt+\ b i n ' Space ' H a n d e l 
K l a n d e l ' Space Enter
 Space d : ; Space c d Space ' d : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ U s u a r i o Ctrl+Alt+\ O n e D r i v e Space U P M Ctrl+Alt+\ O n e D r i v e Space - Space

Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: left
Valor actual -2.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

Prueba la nueva tecnología PowerShell multiplataforma https://aka.ms/pscore6

PS D:\Users\Usuario\OneDrive UPM\OneDrive - Universidad Politécnica de Madrid\Curso 1\Primer semestre\Programación I\Prácticas>  & '
 & 'C:\Program Files\Java\jdk-20\bin\java.exe' '-XX:+ShowCodeDetailsInExceptionMessages' '-cp' 'C:\Users\Usuario\AppData\Roaminge\Us\Code\User\workspaceStorage\0c7acfda662f43c9e322072cdb6cd569\redhat.java\jdt_ws\Prácticas_76db677b\bin' 'HandelKlandel'
Prueba de HandelKlandel
PS D:\Users\Usuario\OneDrive UPM\OneDrive - Universidad Politécnica de Madrid\Curso 1\Primer semestre\Programación I\Prácticas> 
 
Se produjo un error. Informa de este error indicando los detalles que tienes a continuación.
Informe de GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.3324 (WinBuild.160101.0800)
BufferWidth: 128
BufferHeight: 12
```

### Steps to reproduce

Estaba ejecutando un código de java simple

### Expected behavior

que se ejecutara

### Actual behavior

Me sale un error

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.2.6 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
