### ISSUE TITLE
Provide a way to prompt for input from a custom binding

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PSReadLine#38]
I have a line of PowerShell on the screen and want to do a find/replace.

**ctrl+e,r**

Is there a way to in a handler to suspend typing into the console, capture the input that is typed next and when enter is pressed execute and return back to console input?

**Comment by lzybkr** [comment]
`InvokePrompt` now takes an option int argument specifying the new `Y` where you want the prompt invoked - that should be sufficient to address the concern I mentioned above.

Beyond that, I have no plans for a generic way to prompt within a prompt, though it might come via another enhancement request.
