### ISSUE TITLE
DeleteChar emulates vi mode in Windows/Emacs modes

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#380]
DeleteChar is a bit messed up when the cursor is on the last character of the line.

Type: 123 LeftArrow Delete Delete
Expected:
Emacs mode: line has 12
Windows mode: line has 12
Vi mode: line has 1

Actually, the Vi mode behavior seems a bit wrong too, though it does seem to match bash.  In vim, I see a difference b/w insert and command modes - command mode seems to move the cursor (just like bash), but insert mode leaves the cursor, so you can't delete more than what is under or to the right of the cursor.

I also notice in bash that Delete sometimes gets treated as DigitArgument - is that really expected? It feels like a bug, so I don't think PSReadline needs to emulate that.

@srdubya - what do you think?

**Comment by srdubya** [comment]
Yep, looks like a bug.  Bash isn't correct either.  Vim seems to be doing the right thing.

I'll take a look.

**Comment by lzybkr** [comment]
Fixed with 2a254e6
Thanks @srdubya.
