### ISSUE TITLE
bug in terminal of VScode python 

### ISSUE THREAD

**Issue by gunfighter9901** [PowerShell/PSReadLine#3814]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
on typing enter unwanted keys is auto pressed don't able to come out of it
i was coding python program , it happened suddenly nothing is working not even clear and exit() 
don't understand what it is
```

### Screenshot

![Screenshot (35)](https://github.com/PowerShell/PSReadLine/assets/95130905/22111bee-7392-4e10-bdab-e0c8ee1c8cdd)

### Environment data

```console
latest version 
latest build 
latest python software
```

### Steps to reproduce

unknown but suddenly

### Expected behavior

good behaviour

### Actual behavior

broken behaviour

**Comment by StevenBucher98** [comment]
I believe you have the wrong repo to submit this issue in, this is for PSReadLine and PowerShell.
