### ISSUE TITLE
Cannot define a key handler for Ctrl+B

### ISSUE THREAD

**Issue by sba923** [PowerShell/PSReadLine#3817]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/12860484/063178c1-d676-489b-a905-9782cdf2ccbc)

### Environment data

```console
PS Version: 7.3.7
PS HostName: ConsoleHost
PSReadLine Version: 2.3.3
PSReadLine EditMode: Windows
OS: 10.0.22621.2338 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

Run the code snippet in the second example of https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlinekeyhandler?view=powershell-7.3

```powershell
Set-PSReadLineKeyHandler -Chord Ctrl+B -ScriptBlock {
    [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert('build')
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
}
```

Hit `Ctrl+B`

### Expected behavior

`build<enter>` should be fed to the prompt

(this is what happens e.g. if `-Chord F12` is used)

### Actual behavior

`^B` is displayed

**Comment by daxian-dbw** [comment]
It's a doc issue. It should be `Ctrl+b` instead of `Ctrl+B`. I've opened https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10480
`Ctrl+B` requires pressing <kbd>Ctrl+Shift+b</kbd>, and `Ctrl+b` requires <kbd>Ctrl+b</kbd>. A user would expect the latter to work.

**Comment by sba923** [comment]
I confirm it works with `Ctrl+b`.

The documentation states that "_as of PSReadLine 2.0.0, the Chord parameter is case-sensitive. Meaning, `Ctrl+X` and `Ctrl+x` create different bindings._" But it doesn't state that `Ctrl+X` is interpreted as `Ctrl+Shift+x`, or that you basically have to use lowercase letters if you want e.g. `Ctrl+a` to work "as expected."

**Comment by daxian-dbw** [comment]
`Ctrl+X` is literally how you will type this combination -- you need to press `Shift+x` to produce `X`.
The doc was updated: https://github.com/MicrosoftDocs/PowerShell-Docs/pull/10483. But if you still see any confusion in the doc, please open a new doc issue.

**Comment by sba923** [comment]
> `Ctrl+X` is literally how you will type this combination -- you need to press `Shift+x` to produce `X`.

I'm afraid I cannot concur here. When https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec tells me to use `Ctrl+X` for Cut or `Ctrl+V` for Paste, I don't use the Shift key to perform those operations, and that's just two random examples.

**Comment by sba923** [comment]
> > `Ctrl+X` is literally how you will type this combination -- you need to press `Shift+x` to produce `X`.
> 
> I'm afraid I cannot concur here. When https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec tells me to use `Ctrl+X` for Cut or `Ctrl+V` for Paste, I don't use the Shift key to perform those operations, and that's just two random examples.

I think the new phrasing _Letter key references are defined using lowercase letters_ should suffice--provided users *do* read the doc 😜.
