### ISSUE TITLE
Get exeption when I try to commit a code using git from terminal - git commit -m " then got the exception

### ISSUE THREAD

**Issue by rashaabdulrazzak** [PowerShell/PSReadLine#3818]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
git commit -m 
Oops, something went wrong.  
Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 m i t Space - m Space " g i 
t Space c o m m i t Space - m Space " d i s p l a y Space 
b a n n e r Space u p l o a d Space a n d Space f e t c h 
Space b a n n e r " Enter    
 g i t Space p u s h Space o 
r i g i n Space c a t e g Tab o r y s c r e e n Enter     
 g i t Space c h e c k o u t 
Space m a i n Enter
 g i t Space p u l l Space o 
r i g i n Space m a i n Enter g i t Space c h e c k o u t 
Space - b Space r o w H e a d e r Enter
 G Backspace g i t Space s t 
a t u s Enter
 g i t Space a d d Space . Enter
 g i t Space c o m m i y Backspace t Space - m Space "    

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.   
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)        
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg) 
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()  
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/11816618/a4bd037d-476e-4e8c-aaf9-4d7d06d2b60c)
![image](https://github.com/PowerShell/PSReadLine/assets/11816618/426fca47-fa1f-4c07-acb0-e71798f60910)
![image](https://github.com/PowerShell/PSReadLine/assets/11816618/d1aa1321-9291-434c-bbf7-982925e5a5af)

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 72
BufferHeight: 30
```

### Steps to reproduce

when you have some code and you want to add it to git start with `git add . ` then you have to commit it when writing 
`git commit -m ` but it will generate the exception when you try to put the message in quotation.

### Expected behavior

No Exception. I have to be able to commit the code with the proper message

### Actual behavior

I couldn't commit the code because an exception occurred when I tried to add the commit message
**note**
if I tried  3 times the exception could go for one time

**Comment by daxian-dbw** [comment]
You are using a very old version of PSReadLine, likely prior to 2.0.0-beta2. So, please upgrade to the latest version. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
