### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by yaclnb** [PowerShell/PSReadLine#3823]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 o c a l \ M i c r o s o f t \ W i n d o w s A p p s \ p y t h o n 3 . 9 . e x e ' Space ' c : \ U s e r s \ b o b \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 
 \ D r o p b o x \ B o b Space D o c u m e

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

PS Q:\Dropbox\Bob Documents\SOURCES\Python\Misc. Projects\Bottle 1>  & 'C:\Users\bob\AppData\Local\Microsoft\WindowsApps\python3.9.exe' 'c:\Users\bob\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '10743' '--' 'Q:\Dropbox\Bob Documents\SOURCES\Python\Misc. Projects\Bottle 1\main.py'
My local IP Address is: 192.168.86.100
Bottle v0.12.25 server starting up (using WaitressServer())...
Listening on http://192.168.86.100:8080/
Hit Ctrl-C to quit.

PS Q:\Dropbox\Bob Documents\SOURCES\Python\Misc. Projects\Bottle 1>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 174
BufferHeight: 31
```

### Steps to reproduce

1) I was ruunning VS Code with a Python script. 
2) I don't know how to reproduce this; it just happened.
3) To my knowlege, I haven't seen this message before.

### Expected behavior

No error message. 

### Actual behavior

You know, whoever wrote the "Please report this bug with the details below." message should REALLY think twice about all the other requirements needed to successfully submit a bug report. 

I'm trying to help you guys out here,. I am NOT a PowerShell developer, and I don't know how to fill out most of this form :(

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.3.4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.4) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
