### ISSUE TITLE
Inconsistent behavior between executing directly from the command line and from inside a KeyHandler.

### ISSUE THREAD

**Issue by LittleNewton** [PowerShell/PSReadLine#3826]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
The code in question is as follows:

 powershell
Set-PSReadLineKeyHandler -Chord Ctrl+k `
                         -BriefDescription ClearHost `
                         -LongDescription "Clear the console host screen" `
                         -ScriptBlock {
    Clear-Host
}
```

I intend for the action to clear all command history upon pressing Ctrl+k. However, it should retain the prompt to avoid an unpleasant visual and lack of command indication. When executing Clear-Host directly from the command line, it operates as intended. Yet, when invoking the same through the aforementioned KeyHandler, it wipes the prompt as well, leaving the screen entirely blank.

### Screenshot

After pressing Ctrl+k
![image](https://github.com/PowerShell/PSReadLine/assets/17793356/54ec530a-1f5e-4e8f-9f25-20adb6e4cb8e)

Using `Clear-Host`

![image](https://github.com/PowerShell/PSReadLine/assets/17793356/ab453de9-690a-4509-aa62-5a5ade2176e6)

![image](https://github.com/PowerShell/PSReadLine/assets/17793356/f869bc5f-a8b0-40ac-9ed6-3b57a6b60af1)

### Environment data

```console
PS Version: 7.3.7
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.4
PSReadLine EditMode: Windows
OS: 10.0.19041.3324 (WinBuild.160101.0800)
BufferWidth: 135
BufferHeight: 45
```

### Steps to reproduce

1. Install [oh-my-posh](https://ohmyposh.dev/docs/) using `winget`.

``` powershell
winget install JanDeDobbeleer.OhMyPosh -s winget
```

2. Using `paradox` theme.

How to set the theme? As following,

- `$PS code $PROFILE`
- Add a new line: `oh-my-posh init pwsh --config $env:POSH_THEMES_PATH\paradox.omp.json | Invoke-Expression`

3. Add KeyHandler

``` powershell
Set-PSReadLineKeyHandler -Chord Ctrl+k `
                         -BriefDescription ClearHost `
                         -LongDescription "Clear the console host screen" `
                         -ScriptBlock {
    Clear-Host
```

4. Try Ctrl+k and `Clear-Host`

Just compare the different behavior.

### Expected behavior

I wish `Ctrl k` keyHandler has the same behavior as type `Clear-Host`.

### Actual behavior

`Ctrl k` will clear all characters in the terminal.

**Comment by LittleNewton** [comment]
After pressing Ctrl+k
![image](https://github.com/PowerShell/PSReadLine/assets/17793356/54ec530a-1f5e-4e8f-9f25-20adb6e4cb8e)

Using `Clear-Host`

![image](https://github.com/PowerShell/PSReadLine/assets/17793356/ab453de9-690a-4509-aa62-5a5ade2176e6)

![image](https://github.com/PowerShell/PSReadLine/assets/17793356/f869bc5f-a8b0-40ac-9ed6-3b57a6b60af1)

**Comment by daxian-dbw** [comment]
This is by design. If you want to have a custom key binding that runs `clear-host`, then your key binding handler needs to take care of writing out the prompt message. PSReadLine has a default key binding `Ctrl+l` for clearing screen, you can use that instead of having your own custom binding for it.

```
PS:1> Get-PSReadLineKeyHandler -Chord "ctrl+l"

Miscellaneous functions
=======================

Key    Function    Description
---    --------    -----------
Ctrl+l ClearScreen Clear the screen and redraw the current line at the top of the screen
```

**Comment by thegraffix** [comment]
FWIW, one behavioral difference (that's important to some, but not all) between `Clear-Host` and the PSReadLineKeyHandler function `ClearScreen` is that `Clear-Host` clears the scrollback buffer.  The `ClearScreen` function executes a carriage return everytime it's executed, resulting in a console that looks like this after doing `CTRL+L` 3x and scrolling up:

![image](https://github.com/user-attachments/assets/c4cc17ff-baf1-48ef-802d-7478859a71f6)

It would be cool if the `ClearScreen` function took into account the OS/environment (e.g. Windows/conhost has always cleared the scrollback buffer, whereas Linux/bash traditionally has _not_).
<BR></BR>
But this works just as well:
```
$args = @{
    BriefDescription = 'ClearHost'
    Chord = 'Ctrl+k'
    Description = 'Clear the console host screen'
    ScriptBlock = {
        [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
        [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
        Clear-Host
    }
}
Set-PSReadLineKeyHandler @args
```
