### ISSUE TITLE
`Ctrl+h` in `-EditMode Windows` removes last word without reason and cannot be rebinded

### ISSUE THREAD

**Issue by Podbrushkin** [PowerShell/PSReadLine#3833]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![ctrl-H](https://github.com/PowerShell/PSReadLine/assets/110057725/f8e77eb6-9536-4fca-aedd-392f9a863fb3)

### Environment data

```console
PS Version: 7.3.6
PS HostName: ConsoleHost
PSReadLine Version: 2.3.4
PSReadLine EditMode: Windows
OS: Linux asuspro16x 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
BufferWidth: 124
BufferHeight: 37
```

### Steps to reproduce

1. Run wsl Ubuntu;
2. Execute `pwsh -NoProfile`
3. Type something and press `Ctrl+h`. It removes last character, as it should;
4. Execute `Set-PSReadLineOption -EditMode Windows`
5. Type something and press `Ctrl+h`. It removes last word. Even though this bind isn't listed in `Get-psReadLineKeyHandler`.
6. Execute `Set-PSReadLineKeyHandler -Chord Ctrl+h -Function BackwardDeleteChar`
7. Type something and press `Ctrl+h`.

### Expected behavior

It should remove last character.

### Actual behavior

It removes last word. Even though `Get-psReadLineKeyHandler` shows it should delete last char.

**Comment by Podbrushkin** [comment]
Forgot to mention, in `pwsh -nop` without wsl, Ctrl+h works by default in Windows mode and is listed in KeyHandler.

**Comment by daxian-dbw** [comment]
This is actually by design, due to the difference between how `Ctrl+h` is processed on Windows and Unix platforms.
On Windows, when you press `Ctrl+h`, this is what will be received by `Console.Readkey()` 
```
PS:16> [System.Console]::ReadKey()

KeyChar Key Modifiers
------- --- ---------
        H   Control
```

However, on Unix platforms, this is what will be received:
```
PS /> [System.Console]::ReadKey()

KeyChar       Key Modifiers
-------       --- ---------
      Backspace   Control
```

Yes, on Unix system, `Ctrl+h` is the same as `Ctrl+Backspace`, which is bound to `BackwardKillWord` in the `Windows` edit mode. That's why `ctrl+h` starts to delete a word backward.

> 3. Type something and press Ctrl+h. It removes last character, as it should;

Your step 3 from the repro steps shows `Ctrl+h` does delete the last char initially. This is because PSReadLine uses `Emacs` mode as the default when running on Unix systems, and in `Emacs` mode, `Ctrl+Backspace` is bound to `BackwardDeleteChar`, which is different from the `Windows` edit mode.

**Comment by Podbrushkin** [comment]
So, to get expected behavior, I should execute `Set-PSReadLineKeyHandler -Chord Ctrl+Backspace -Function BackwardDeleteChar`, or add this to psprofile:
```
if ($PSVersionTable.Platform -eq 'Unix') {
	Set-PSReadLineKeyHandler -Chord Ctrl+Backspace -Function BackwardDeleteChar
}
```
Pressing Ctrl+h in any console removes last character, but not in pwsh with `-editmode windows` under unix os. I wonder what kind of a design is it.
Also, if someone is using '-editmode windows' in psreadline probably he will expect it to behave consistently across different platforms.
Anyway, thank you, I will use workaround mentioned above.

**Comment by daxian-dbw** [comment]
To be fair, on Unix system, other popular shells all use emacs mode, which is what PowerShell use by default too. In this default setting, `Ctrl+h` does remove the last character. Just like `bash`, both `Ctrl+Backspace` and `Ctrl+h` in PowerShell remove the character backwards.

With `-EditMode Windows`, `Ctrl+Backspace` is supposed to delete word backwards, and `Ctrl+h` simply produces the same input as `Ctrl+Backspace`, so there is no way to keep the consistency as on Windows system.

Try `showkey -a` on Linux for example, you will get the same codes when pressing `Ctrl+Backspace` and `Ctrl+h`.
This inconsistency is deep down in the operating system.

![image](https://github.com/PowerShell/PSReadLine/assets/127450/c49c15fe-d1ff-43e4-a789-045d8ae18845)

**Comment by Podbrushkin** [comment]
Thank you for your detailed response. 

> ..., which is what PowerShell use by default too. In this default setting, `Ctrl+h` does remove the last character. 

I appreciate it much, really. When you can use same keystrokes for the same tasks in different applications and there is no need to configure them to achieve this behavior (configuration process is very different for different applications), this cannot be underestimated.

I've just now realized binding `Ctrl+Backspace` to `BackwardDeleteChar` in Windows mode under Unix OS makes `ctrl+h` behave as expected but makes `Ctrl+Backspace` behave as not expected, while probably `Ctrl+Backspace` for deleting a word is a shortcut much more known and widely used in Windows. When you have to choose between Ctrl+h and Ctrl+Backspace to work properly latter seems like a better choice. I haven't thought binding Ctrl+Backspace to remove last char (as I proposed) will break another shortcut. Looks like inability of Unix system to properly report what keys have been pressed indeed makes this Ctrl+h inconsistency inevitable.
