### ISSUE TITLE
Inconsistent documentation for default value of HistoryNoDuplicates

### ISSUE THREAD

**Issue by RReverser** [PowerShell/PSReadLine#3836]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

Documentation at https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.3 currently says:

<blockquote>
<p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(162, 160, 156); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 14, 14); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">By default, the<span> </span><strong style="box-sizing: inherit; outline-color: inherit; font-weight: 600;">HistoryNoDuplicates</strong><span> </span>property of the global<span> </span><strong style="box-sizing: inherit; outline-color: inherit; font-weight: 600;">PSConsoleReadLineOptions</strong><span> </span>object is set to<span> </span><code style="box-sizing: inherit; outline-color: inherit; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; direction: ltr; background-color: var(--darkreader-bg--theme-inline-code); overflow-wrap: break-word; border-radius: 3px; padding: 0.1em 0.2em;">True</code>. Using this<span> </span><strong style="box-sizing: inherit; outline-color: inherit; font-weight: 600;">SwitchParameter</strong><span> </span>sets the property value to<span> </span><code style="box-sizing: inherit; outline-color: inherit; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; direction: ltr; background-color: var(--darkreader-bg--theme-inline-code); overflow-wrap: break-word; border-radius: 3px; padding: 0.1em 0.2em;">True</code>. To change the property value, you must specify the value of the<span> </span><strong style="box-sizing: inherit; outline-color: inherit; font-weight: 600;">SwitchParameter</strong><span> </span>as follows:<span> </span><code style="box-sizing: inherit; outline-color: inherit; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; direction: ltr; background-color: var(--darkreader-bg--theme-inline-code); overflow-wrap: break-word; border-radius: 3px; padding: 0.1em 0.2em;">-HistoryNoDuplicates:$False</code>.</p><p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(162, 160, 156); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 14, 14); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Using the following command, you can set the property value directly:</p><p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(162, 160, 156); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 14, 14); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="box-sizing: inherit; outline-color: inherit; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; direction: ltr; background-color: var(--darkreader-bg--theme-inline-code); overflow-wrap: break-word; border-radius: 3px; padding: 0.1em 0.2em;">(Get-PSReadLineOption).HistoryNoDuplicates = $False</code></p>

Type: | SwitchParameter
-- | --
Position: | Named
Default value: | False
Required: | False
Accept pipeline input: | False
Accept wildcard characters: | False

</blockquote>

That is, the text says the default value is `True`, then it says you can change it to `True`, then shows example how you actually set it to `False`, and the table also says default value is `False`.

Looks like this needs some cleanup / update.

**Comment by StevenBucher98** [comment]
Thanks for the issue! The content is correct but I agree the wording is a little confusing, it is trying to convey that just using `-HistoryNoDuplicates` without anything else will set it to true and to set to false you need `-HistoryNoDuplicates:$False`. I will update the wording in the documentation.

In the future you can submit an issue directly to the doc's repo at https://github.com/MicrosoftDocs/PowerShell-Docs/issues. They will be able to provide quick remedies.

**Comment by RReverser** [comment]
> In the future you can submit an issue directly to the doc's repo at [MicrosoftDocs/PowerShell-Docs/issues](https://github.com/MicrosoftDocs/PowerShell-Docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). They will be able to provide quick remedies.

Ah thanks. I saw the docs issue template in this repo, so I assumed this is the right place. Is that template obsolete then or is it for a different set of docs?

**Comment by StevenBucher98** [comment]
@RReverser good question, both options are fine, usually we encourage folks to submit to the documentation itself as it will get a quicker response/fix but since we also watch our other repos often we were able to fix this one pretty quick 😄

**Comment by RReverser** [comment]
Sounds good. Just a thought - if the other repo is preferred, it might be useful to just change the documentation template here to say something like "Please file issue at [link] instead.".

**Comment by daxian-dbw** [comment]
Good point, @RReverser. I have updated the issue template for documentation to point to the PowerShell-Docs repo.
