### ISSUE TITLE
SmartInsertQuote in SamplePSReadLineProfile.ps1 not working

### ISSUE THREAD

**Issue by AmusingMallard** [PowerShell/PSReadLine#3837]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

Related to #3423 and #3440.

The example that was originally in the README.md file is still used in the SamplePSReadLineProfile.ps1 file. It got it to work by replacing the quotes part of the sample profile with the sample from the readme. The parentheses and smart backspace part of the sample profile still works though.

**Comment by StevenBucher98** [comment]
Hmm the `SmartInsertQuote` sample from 2.3.4 seems to be working for me. Did you be sure to include: 
```
using namespace System.Management.Automation
using namespace System.Management.Automation.Language
```
in your profile? I suggest upgrading to 2.3.4 and then using the sample included with that module.
