### ISSUE TITLE
ConsoleHost in pwsh 7.3.4 gets an error when hitting pageUp in console window.  Message asks to report this issue.

### ISSUE THREAD

**Issue by kurtrenner** [PowerShell/PSReadLine#3842]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.4
PowerShell: 7.3.8
OS: Microsoft Windows 10.0.17763
BufferWidth: 172
BufferHeight: 9001

Last 24 Keys:

 LeftWindows UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 $ c o n n Spacebar | Shift+Spacebar f l Enter
 LeftWindows PageUp PageDown PageUp

### Exception

System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/31141683/44a1b206-1ba3-4158-9952-dc12edd7a070)

### Environment data

```console
PS Version: 7.3.8
PS HostName: ConsoleHost
PSReadLine Version: 2.3.4
PSReadLine EditMode: Windows
OS: 10.0.17763.1 (WinBuild.160101.0800)
BufferWidth: 172
BufferHeight: 9001
```

### Steps to reproduce

issue commands in a pwsh session window that cause the content of the screen to scroll outside the window boundaries and then hit the pageUp key on the keyboard.  Error message is produced and the screen content does not scroll up.

### Expected behavior

Expect to see content on previous page(s) of the window output

### Actual behavior

Error noted is displayed

**Comment by daxian-dbw** [comment]
@kurtrenner thanks for reporting the issue! But I cannot reproduce the issue locally with the conhost (your image shows you were using conhost as the terminal). If you are able to consistently reproduce the issue, can you please provide more detailed steps (_including operations like maximizing the window or snap the window to a side/cornor of the screen_) for us to reproduce it in a fresh pwsh session? Thanks!
