### ISSUE TITLE
win10 64bit ：windows powershell bug

### ISSUE THREAD

**Issue by DullSmile** [PowerShell/PSReadLine#385]
> >  new-item -type  file NAME/**init**.py  
> > 题。
> > ## 请报告此 Bug，详细信息如下。                                                  >> https://github.com/lzybkr/PSReadLine/issues/new                   
> > 
> > cebar p r o Tab Enter  
> > indows n e Backspace Backspace Backspace Backspace B  
> >  Backspace Backspace c d Backspace Backspace Backspa  
> > kspace Backspace Backspace Backspace Backspace Backs  
> > kspace c d Spacebar Spacebar Spacebar p r Backspace                 
> > - Tab i Tab Tab Backspace Backspace Backspace Backs  
> >    >> kspace Backspace Backspace n e w - i t e m Spacebar  
> >   l e Spacebar Tab n a m e Backspace Backspace Backspa  
> >   r  
> >   >>  LeftArrow LeftArrow LeftArrow LeftArrow RightArrow  
> >     >> ow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow S  
> >   +LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+Lef  
> >   ow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow S  
> >   +LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+Lef

**Comment by lzybkr** [comment]
This error report is truncated - can you include the call stack of the exception?

**Comment by lzybkr** [comment]
Closing - not enough information to investigate.
