### ISSUE TITLE
Simple variable access throws System.NullReferenceException

### ISSUE THREAD

**Issue by nowakca** [PowerShell/PSReadLine#3877]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.4
PowerShell: 7.4.0
OS: Red Hat Enterprise Linux 8.1 (Ootpa)
BufferWidth: 166
BufferHeight: 48

Last 9 Keys:

 1 + 2 Enter
 $ a = 4 Enter


### Exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at InvokeStub_PredictionClient.set_CurrentLocation(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokePropertySetter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
```

### Screenshot

[root@a32ba66750cf /]# pwsh
PowerShell 7.4.0
PS /> 1+2
3
PS /> $a=4
PS /> 
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment data

```console
Unable to run script as any comments
```

### Steps to reproduce

On my M1 Macbook run the following in Terminal.app

```
docker run --rm -it --name test --platform linux/amd64 registry.access.redhat.com/ubi8/ubi:8.1 bash
```

In that container run 

```
curl --silent --show-error https://packages.microsoft.com/config/rhel/7/prod.repo | tee /etc/yum.repos.d/microsoft.repo
yum -y install powershell-7.4.0
pwsh
```

In that shell run 
```
1+2
```

Observe expected `3` as output

Then run 
```
$a=4
```

Get the exception

Any more enters after that just repeat the exception.
Typing in `1+2` repeats the same exception again

Typing `help` results in a Segmentation fault, and dropping back to Linux's bash

NOTE: If I run pwsh again, it works fine. And when I type in `$a`, it offers `$a=4` as autocomplete even, so it seems to be an issue with starting up from a completely fresh system.

### Expected behavior

After typing in `$a=4` I expect no exception, and I expect to get a functioning new next prompt.

### Actual behavior

The above exception happens, and I'm stuck with that exception.

Relaunching pwsh proceeds as desired, it's just the first run that fails.

Closing the container, starting it up fresh again, and repeating the steps causes the exception again

So it definitely seems to to with some history file or something of that nature not existing.

**Comment by nowakca** [comment]
Having searched around and dug into other issues (going back into 7.3.0), this looks like it might be a more general "newer versions of .Net don't behave on Docker/Linux that runs via Rosetta", which is very sad if true.

**Comment by daxian-dbw** [comment]
@nowakca It does seem to be a .NET issue for 2 reasons:
1. The exception happened in the .NET reflection code stack.
2. The [reflection call](https://github.com/PowerShell/PSReadLine/blob/ff4bbd5ee0e2dea7d72e0adb43d64a3f07c0e7e1/PSReadLine/Prediction.cs#L54) happens on every call to `PSConsoleReadLine.ReadLine`, namely every time you get the prompt back.
   So, the call worked fine for the first 2 commands `1+2` and `$a=4`, but failed when the prompt got back after executing `$a=4`.

Can you please share some pointers about the `"newer versions of .Net don't behave on Docker/Linux that runs via Rosetta"` issue?
