### ISSUE TITLE
Accept single word from auto-complete suggestion instead of whole line

### ISSUE THREAD

**Issue by Simran-B** [PowerShell/PSReadLine#3888]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

I would like to be able to partially use auto-complete suggestions similar to what shells like fish offer.
Using <kbd>Alt</kbd>+<kbd>Right Arrow</kbd> or <kbd>Ctrl</kbd>+<kbd>Right Arrow</kbd>, I can add the next word to my input. The path separator character is considered a word boundary.

The command history with <kbd>F2</kbd> or (<kbd>Shift</kbd>+)<kbd>F8</kbd> is a better option if you used a command before, but if it's not in the list or you never entered it before, it would save time if you could use some of the auto-complete suggestions instead of typing everything or accepting the full suggestion and then having to delete several characters.

https://github.com/microsoft/terminal/assets/7819991/8a3111dc-8632-4db7-8d8f-1cdfec344f37

### Proposed technical implementation details (optional)

<kbd>Ctrl</kbd>+<kbd>Left/Right Arrow</kbd> can already be used to jump one word at a time, with the path separator being a word boundary. This feature could potentially be extended so that one word of the auto-complete suggestion is added to the input when the cursor is at the end of the current input and you hit the <kbd>Ctrl</kbd>+<kbd>Right Arrow</kbd> key combination instead of doing nothing.

_<sup>Originally posted at https://github.com/microsoft/terminal/issues/16341</sup>_

**Comment by daxian-dbw** [comment]
This is already supported by the `ForwardWord` function in PSReadLine. Try running `Set-PSReadLineKeyHandler -Chord "Ctrl+f" -Function ForwardWord` and use `Ctrl+f` to accept a word from the inline prediction.

![new-streaming](https://github.com/PowerShell/PSReadLine/assets/127450/e3560cc6-c9a5-4743-843a-df6b6cca4d85)
