### ISSUE TITLE
Complete function fails when bound to Tab, if AcceptSuggestion is bound to "Tab,Tab" at the same time

### ISSUE THREAD

**Issue by jelenv** [PowerShell/PSReadLine#3895]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.4.0
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.4
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 209
BufferHeight: 51
```

### Steps to reproduce

1. Configure your PowerShell profile like this:
```powershell
Import-Module PSReadLine

Set-PSReadLineOption -PredictionSource History

Set-PSReadlineKeyHandler -Key Tab -Function Complete
Set-PSReadLineKeyHandler -Chord "Tab,Tab" -Function AcceptSuggestion
```
2. Now start PowerShell and try to use "Tab" once to autocomplete something, for example a path (there is a dir `Downloads` in current path): `cd Downl` -> press "Tab" -> Nothing happens.
3. Try writing something which will get predicted from history and then press twice "Tab" -> it correctly accepts the suggestion.
---
When it's set up only with bind for `Complete`, it works:
```powershell
Set-PSReadlineKeyHandler -Key Tab -Function Complete
# Set-PSReadLineKeyHandler -Chord "Tab,Tab" -Function AcceptSuggestion
```
When `AcceptSuggestion` is bound to something else than "Tab,Tab", then both functions work:
```powershell
Set-PSReadlineKeyHandler -Key Tab -Function Complete
Set-PSReadLineKeyHandler -Chord "Shift+Tab" -Function AcceptSuggestion
```

### Expected behavior

`Complete` function should trigger on Tab when bound to Tab and there is no other function bound to "Tab".

### Actual behavior

`Complete` function does not trigger when bound to Tab, if at the same time `AcceptSuggestion` is bound to "Tab,Tab" (double tap of Tab).

**Comment by StevenBucher98** [comment]
I am not sure if we support "tab,tab" or the double tap of keys to trigger a function, @daxian-dbw can confirm.

**Comment by jelenv** [comment]
Triggering a function by "Tab, Tab" works. But when there is "Tab,Tab" set to something, the trigger by "Tab" stops working ("Tab, Tab" still works in this case).

If I remember correctly, I had this setup in past and it worked (but maybe it's a false memory).

**Comment by daxian-dbw** [comment]
This is a duplicate of #1701. Will close as a duplicate.
