### ISSUE TITLE
BUG - System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult

### ISSUE THREAD

**Issue by edbakermct** [PowerShell/PSReadLine#3901]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.3.10
OS: Microsoft Windows 10.0.22621
BufferWidth: 120
BufferHeight: 30

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

I cannot uninstall 7.1.3 andf have installed later versions but they wont run due to this error
would appreciate assistance to remove this version so i can run PoSh

Cannot taker a screenshot as this happens when the terminal loads

I cant run the nvironment script - the systrem is non responsive from start
```


### Screenshot

no screenshot

### Environment data

```console
7.1.3
```

### Steps to reproduce

start terminal in powershell 0or just run powershell 7 in a command window always happens

### Expected behavior

system ruins correctly

### Actual behavior

i always get thgis error

**Comment by edbakermct** [comment]
none of those worked - the remove module didnt work so i deleted the folder in program files and that didnt work either,

**Comment by StevenBucher98** [comment]
Try upgrading to the latest version of PSReadLine, https://www.powershellgallery.com/packages/PSReadLine/2.3.4
