### ISSUE TITLE
exit code -1

### ISSUE THREAD

**Issue by noodlesoul** [PowerShell/PSReadLine#3910]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
n/a
```

### Screenshot

![Screenshot (2)](https://github.com/PowerShell/PSReadLine/assets/154422439/ce7357c6-da63-4dc0-b27d-8ccea6cb7039)

### Environment data

```console
PS Version: 7.4.0
PS HostName: ConsoleHost
PSReadLine Version: 2.3.4
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

i upgraded the thing, restarted the laptop, still the same error on the most basic code

### Expected behavior

i wanted it to run the code as is supposed to

### Actual behavior

well you can see it

**Comment by StevenBucher98** [comment]
This looks to me as something wrong with the C++ VScode module? Can you provide more detailed repro steps that could tie this issue being caused by PSReadLine?

**Comment by noodlesoul** [comment]
I honestly don't have a clue on what is causing this problem, wether it's
the PsReadLine ( which is what I've been told ) or something else. 2 days
ago it was working and now its showing the same error with the -1 exit
code. the code did not change nor did I do anything to the application.

mie., 27 dec. 2023, 19:55 Steven Bucher ***@***.***> a scris:

**Comment by daxian-dbw** [comment]
The screenshot doesn't show anything related to PSReadLine. The failure came from your C++ compilation.

**Comment by noodlesoul** [comment]
I've downloaded the vscode and the compiler from the instructions on the
site but when I tried to run the code provided by the site but it crashes
with that error each time. I don't know anymore

joi, 28 dec. 2023, 00:09 Dongbo Wang ***@***.***> a scris:
