### ISSUE TITLE
NullReferenceException when adding empty event to WebClient

### ISSUE THREAD

**Issue by nachtkriecher** [PowerShell/PSReadLine#394]
I am trying to set up a script to download files asynchronously with PowerShell. I wanted a way to check whether or not the file had finished, so I registered an empty event on my WebClient object. I'm guessing maybe this is what caused the NullReferenceException?

Here is an output of the error:

PS C:\Users\username\Desktop>
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 200 Keys:
 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace a s d f h j k l . t m p Enter
 $ b y t e s Enter
 UpArrow UpArrow Escape $ w c . d o w Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace r e g i s t e r - e v e n t o b j e c t Spacebar Escape r e g i s t e r - o b j e c t e v e n t Spacebar - i n p u t Spacebar $ w c Spacebar - e v e n t n a m e Spacebar D o w n l o a d F i l e C o m p l e t e d Spacebar - s o u r c e i d e n t i f i e r Spacebar $ g u i d Spacebar - a c t i o n Spacebar { } Enter
 Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Here's my history for my session:

cd ~\Desktop
$wc = new-object net.webclient
$wc.downloadfileasync("http://nachtkriecher.com", "C:\users\username\desktop\asdfhjkl.tmp")
ls
ls
ls
$env:tmp

join-path $env:tmp [guid](:newguid%28%29.guid)::newguid()
join-path $env:tmp [guid](:newguid%28%29.guid)::newguid().guid
join-path $env:tmp ([guid](:newguid%28%29.guid)::newguid().guid)
get-job
$outfile = join-path $env:tmp ([guid](:newguid%28%29.guid)::newguid().guid)
get-item $outfile
test-item
test-path $outfile
man gc
ls
ls|select -f 1
$wc.downloadfileasync("http://nachtkriecher.com", "C:\users\username\desktop\asdfhjkl.tmp")
get-job
$wc.downloadfileasync("http://nachtkriecher.com", "C:\users\username\desktop\asdfhjkl.tmp")
get-job
$wc.downloadfileasync("http://nachtkriecher.com", "C:\users\username\desktop\asdfhjkl.tmp")
get-job
ls
$bytes = gc $outfile -encoding byte
$bytes = gc asdfhjkl.tmp -encoding byte
$bytes
register-objectevent -input $wc -eventname DownloadFileCompleted -sourceidentifier $guid -action {}
stop-job
hello
$error[0]
$error[1]
get-job

Here's my PSVersionTable:

Name                           Value

---

PSVersion                      5.0.10586.122
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.122
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by lzybkr** [comment]
Thanks for the detailed report.

I have no idea what happened here, but I can't reproduce the problem. Based on the stack, this must be a very rare problem because every key press hits that stack and I don't recall seeing this problem before, so I'll just have to assume you were unlucky, or lucky depending on your point of view.
