### ISSUE TITLE
i have this error when i running my code on windows 

### ISSUE THREAD

**Issue by ramy23149** [PowerShell/PSReadLine#3940]
### Prerequisites

- [x] Write a descriptive title.

**Comment by ramy23149** [comment]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(161,5): error MSB3073: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [D:\flutter_advanced_projects\fruits_market_app\build\windows\x64\INSTALL.vcxproj]

**Comment by StevenBucher98** [comment]
Hi @ramy23149  thanks for the issue! Can you please provide more detailed reproduction steps, environment details and screenshots to help us debut any issue you are having with PowerShell/PSReadline.
