### ISSUE TITLE
clear screen on 2nd monitor throws IO Exception

### ISSUE THREAD

**Issue by SStauden** [PowerShell/PSReadLine#395]
Hi,
I used windows PS on a 2nd screen. After I wanted to clear the screen with [CRTL + L] the following Exepction was thrown:

System.IO.IOException: Falscher Parameter.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.Console.SetWindowPosition(Int32 left, Int32 top)
   bei Microsoft.PowerShell.PSConsoleReadLine.ClearScreen(Nullable`1 key, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bei Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

It seems that the error occurs because the System.Console.SetWindowPosition(Int32 left, Int32 top) parameters are set wrong for the 2nd monitor. This problem does not occur, when I run PS on my main screen.

Greetings, 

Sven

**Comment by lzybkr** [comment]
Most likely a dupe of #292, reopen with additional information if you disagree.
