### ISSUE TITLE
Tab completion produce different cmd than prediction

### ISSUE THREAD

**Issue by AdrianJMartin** [PowerShell/PSReadLine#3970]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
n/a
```

### Screenshot

I type "code c" the prediction shows c:\notes hit TAB ENTER
but it executes 
code .\Contacts\

*sigh*

### Environment data

```console
PS Version: 7.4.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.4
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 209
BufferHeight: 31
```

### Steps to reproduce

I type "code c" the prediction shows c:\notes hit TAB ENTER
but it executes
code .\Contacts\

sigh

### Expected behavior

it to execute
code c:\notes

### Actual behavior

it completes using the match from history but there is some mismatch

**Comment by daxian-dbw** [comment]
Prediction is different from tab completion. Prediction can show suggestions from history, which I believe is why you saw `c:\notes` in your case. It's not related to the tab completion results. To accept prediction, use the <kbd>RightArrow</kbd> key.
