### ISSUE TITLE
PSReadline.format.ps1xml not included with latest builds

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#399]
I just noticed that the latest builds from AppVeyor aren't including the `PSReadline.format.ps1xml` file. Was this intentional?

It looks like it might have been removed around 1/21/2016 when the Vi mode stuff was merged.

**Comment by lzybkr** [comment]
It was removed to speed up startup, but I put it back in PR #561 because it was necessary to avoid weird output of `Get-PSReadLineOption`.
