### ISSUE TITLE
CHCP command not working as expected

### ISSUE THREAD

**Issue by 20-EverGreen-2** [PowerShell/PSReadLine#4027]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

I think all needed information is on video i have made, but if necessary more info, please let me know

PS: 
Steps to reproduce:
Expected behavior:
Actual behavior:
Video is same below in all cases.

https://github.com/PowerShell/PSReadLine/assets/84293898/878af6ec-b8bf-40ba-bcd5-73361d10e0cf

### Environment data

```console
PS Version: 5.1.19041.4355
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.4165 (WinBuild.160101.0800)
BufferWidth: 110
BufferHeight: 3000
```

### Steps to reproduce

https://github.com/PowerShell/PSReadLine/assets/84293898/2e75a937-6131-4b90-b693-3749c1073d7f

### Expected behavior

https://github.com/PowerShell/PSReadLine/assets/84293898/b5a89df6-94f3-4038-a086-6e6876665efb

### Actual behavior

https://github.com/PowerShell/PSReadLine/assets/84293898/b35f0e56-0621-4586-9359-df94fe2cd54f

**Comment by 20-EverGreen-2** [comment]
> @20-EverGreen-2, you were using a pretty old version of PSReadLine (2.0.0-beta2 or prior), and it's likely that the issue was fixed in a newer version. Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

Sorry but in video, i show PSReadLine upgraded to 2.3.5.

Bug still from version 2.0.0-beta1 and up to 2.3.5 including 2.4.0 beta.
This need to be solved.

**Comment by 20-EverGreen-2** [comment]
> > @20-EverGreen-2, you were using a pretty old version of PSReadLine (2.0.0-beta2 or prior), and it's likely that the issue was fixed in a newer version. Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
> 
> Sorry but in video, i show PSReadLine upgraded to 2.3.5.

Bug still from version 2.0.0-beta1 and up to 2.3.5 including 2.4.0 beta.

This need to be solved.

**Comment by 20-EverGreen-2** [comment]
@daxian-dbw  , @paulcallen

Sorry for tag us on this issue. But i think the github bot is working bad and many issues is marked as completed without corrrect resolution. Please read the issue!!!

**Comment by daxian-dbw** [comment]
@20-EverGreen-2 You specified `2.0.0-beta2` in the `Environment data` section, and that's why the bot believes you are on an old version.
As for the CHCP command, it's due to #964 -- PSReadLine sets `OutputEncoding` to `utf8` when reading input from user. I will mention this issue in that one.

**Comment by 20-EverGreen-2** [comment]
> @20-EverGreen-2 You specified `2.0.0-beta2` in the `Environment data` section, and that's why the bot believes you are on an old version. As for the CHCP command, it's due to #964 -- PSReadLine sets `OutputEncoding` to `utf8` when reading input from user. I will mention this issue in that one.

Yes, I supposed bot check psreadline version line.

No solution right? Or changing $outputencoding / [console]::outputencoding solves my issues with special characters?

**Comment by daxian-dbw** [comment]
No solution for https://github.com/PowerShell/PSReadLine/issues/964 yet. Can you share the special dash character that doesn't work for you? I'd like to try locally.

**Comment by 20-EverGreen-2** [comment]
> No solution for #964 yet. Can you share the special dash character that doesn't work for you? I'd like to try locally.

Of course, i want to contribute to solve!!!

Character: —

Character codes from Babelmap version 15.1.0.3:

NCR (hex): `&#x2014;`
NCR (dec): `&#8212;`
HTML: `&mdash;`
UCN: `\u2014`

Hope this help!
