### ISSUE TITLE
System.OutOfMemoryException: Exception of type  'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by marlonmutia** [PowerShell/PSReadLine#4034]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below
```

### Screenshot

N/A

### Environment data

```console
N/A
```

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by StevenBucher98** [comment]
We are going to need more details on reproduction steps to be able to help resolve this issue, please open a new one with more details.
