### ISSUE TITLE
Argument Variable 

### ISSUE THREAD

**Issue by alainapeeler** [PowerShell/PSReadLine#4050]
### Prerequisites

- [X] Write a descriptive title.

**Comment by alainapeeler** [comment]
![image](https://github.com/PowerShell/PSReadLine/assets/173702485/6c441955-ea86-46b8-af3a-84c9c7c68f39)

**Comment by daxian-dbw** [comment]
The GitHub repo URL shown in the exception indicates you are using a very old version of PSReadLine. Please upgrade to the latest version 2.3.5 and give it another try.
