### ISSUE TITLE
Trying to install oh my posh, in post-install running into issues.

### ISSUE THREAD

**Issue by khraosgenetor** [PowerShell/PSReadLine#4067]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS C:\Users\alien\posh-git> Find-Module -Name PSReadLine -Repository PSGallery | Get-Member
PS C:\Users\alien\posh-git> oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json" | Invoke-Expression
Set-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:456 char:5
+     Set-PSReadLineOption -ContinuationPrompt (@(Start-Utf8Process $sc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-PSReadLineOption], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.SetPSReadLineOption

PS>
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/166394161/ca4b0f03-2cad-4894-bef0-58dbb8751844)

### Environment data

```console
PS Version: 5.1.22621.3810
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.5
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:21 char:41
+     Write-Host "PSReadLine EditMode: $((Get-PSReadLineOption).EditMod ...
+                                         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption

PSReadLine EditMode:
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 208
BufferHeight: 60
```

### Steps to reproduce

exec " oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json" | Invoke-Expression"

### Expected behavior

No normal exeptions

### Actual behavior

Runs into the error: Set-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:456 char:5
+     Set-PSReadLineOption -ContinuationPrompt (@(Start-Utf8Process $sc ...

**Comment by daxian-dbw** [comment]
Can you share the script generated by `oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json"`?
Also, can you share all the inner exceptions of the "type initializer" exception you got?

**Comment by khraosgenetor** [comment]
> Can you share the script generated by `oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json"`? Also, can you share all the inner exceptions of the "type initializer" exception you got?

How do I get the inner exception?

Also the script:
 ```(@(& 'C:/Users/alien/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe' init pwsh --config='C:\Users\alien\AppData\Local\Programs\oh-my-posh\themes\jandedobbeleer.omp.json' --print) -join "`n") | Invoke-Expression```

**Comment by khraosgenetor** [comment]
Nevermind sorry, The Powershell from Terminal did not allow me to use the above script. I manually created a new profile, which now works. Sorry for the trouble.
