### ISSUE TITLE
Interpret control characters pasted into `-LiteralPath` arguments as verbatim characters.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [PowerShell/PSReadLine#4072]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

As https://github.com/PowerShell/PowerShell/issues/24037#issue-2400529452 explains:

<blockquote>

### Expected behaviour

Originally, this issue was going to be about how PowerShell can't handle certain legal UTF-8 characters in inode paths. However, after creating a test script:

~~~pwsh
#!/usr/bin/env pwsh

# Prerequisites
# -------------

	# ~~~pwsh
	# #Requires -PSEdition 'Core'
	# #Requires -Version 7
	# ~~~
	
	Set-Location -LiteralPath "$HOME"

# Example Directory
# -----------------

	# Creates an example directory.
	
	$DirectoryPath = 'TabPrefixed	ExampleDirectory.dir'
	$PrintPath = "$DirectoryPath"
	Write-Output (Show-Markdown -InputObject "The path is ``$PrintPath``.")
	
	New-Item `
		-Path "$HOME" `
		-Name "$DirectoryPath" `
		-ItemType 'directory'

# Example File
# ------------

	# Creates an example file.
	
	$FilePath = 'TabPrefixed	ExampleFile.txt'
	$PrintPath = "$FilePath"
	Write-Output (Show-Markdown -InputObject "The path is ``$PrintPath``.")
	
	New-Item `
		-Path ("$HOME" + [IO.Path]::DirectorySeparatorChar + "$DirectoryPath") `
		-Name "$FilePath" `
		-ItemType 'file' `
		-Value 'Example text.'

# Path Acquisition
# ----------------

	# Lists both.
	
	$FullFilePath = (`
	Get-ChildItem `
		-LiteralPath (
			"$HOME"          + [IO.Path]::DirectorySeparatorChar +
			"$DirectoryPath" + [IO.Path]::DirectorySeparatorChar +
			"$FilePath")
		)[0] | Select-Object -ExpandProperty 'FullName'

# File Content Acquisition
# ------------------------

	# This should fail.
	
	$PrintPath = "$FullFilePath"
	Write-Output (Show-Markdown -InputObject "The path is ``$PrintPath``.")
	
	Get-Content -LiteralPath "$FullFilePath"
	Write-Output $?
~~~

I realized that it could. Instead, I've narrowed it to a fault in how PowerShell, via Konsole and VSCode's terminals, interprets certain characters (like `	` - tabs) as control codes.

### Steps to reproduce

Try pasting your equivalent to the undermentioned command:

~~~pwsh
#!/usr/bin/env pwsh
Get-Content -LiteralPath '/home/RokeJulianLockhart/TabPrefixed    ExampleDirectory.dir/TabPrefixed        ExampleFile.txt'
~~~

...into the shell after successfully invoking it.

This value is able to be acquired by the undermentioned command:

~~~pwsh
#!/usr/bin/env pwsh
(Get-ChildItem -LiteralPath "$DirectoryPath")[0].FullName
~~~

### Actual behavior

1.	The undermentioned is a command that has been pasted:
	
	<blockQuote>

	~~~pwsh
	#!/usr/bin/env pwsh
	Get-Content -LiteralPath "/home/RokeJulianLockhart/Documents/pyside6/prefix^Iexample.txt/example.txt"
	~~~

	</blockQuote>
	
	Note within it, the "`prefix^Iexample`". The original content does not contain that control code.

1.	Alternatively, sometimes, it appears to paste the path correctly, but doesn't recognise the value unless passed in a script:

	1.	<blockQuote>
		
		~~~pwsh
		PS /home/RokeJulianLockhart> (Get-ChildItem -LiteralPath "$DirectoryPath")[0].FullName
		/home/RokeJulianLockhart/TabPrefixed    ExampleDirectory.dir/TabPrefixed        ExampleFile.txt
		~~~
	
		</blockQuote>
	
	1.	<blockQuote>
		
		~~~pwsh
		PS /home/RokeJulianLockhart> Get-Content -LiteralPath '/home/RokeJulianLockhart/TabPrefixed    ExampleDirectory.dir/TabPrefixed        ExampleFile.txt'                                                                                                                                 
		Get-Content: Cannot find path '/home/RokeJulianLockhart/TabPrefixed    ExampleDirectory.dir/TabPrefixed        ExampleFile.txt' because it does not exist.
		~~~
	
		</blockQuote>
	
	1.	<blockQuote>
		
		~~~pwsh
		PS /home/RokeJulianLockhart> Get-Content -LiteralPath "$FullFilePath"                                                                                  
		Example text.
		~~~
	
		</blockQuote>
	
	1.	<blockQuote>
		
		~~~pwsh
		PS /home/RokeJulianLockhart> Write-Output "$FullFilePath"            
		/home/RokeJulianLockhart/TabPrefixed    ExampleDirectory.dir/TabPrefixed        ExampleFile.txt
		~~~
		
		</blockQuote>

### Visuals

[Screencast_20240710_125007.webm](https://github.com/PowerShell/PowerShell/assets/42837531/9e0a2564-9469-438a-8cb2-475f1b06a242)

</blockquote>

**Comment by daxian-dbw** [comment]
Please keep the discussion in PowerShell repo for now. When it's time to open an issue here, you need to follow the template to describe the issue, not just referring to another issue.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PowerShell/PSReadLine/issues/4072#event-13478711151

@daxian-dbw, best to close as invalid (rather than completed) since this hasn't been completed. If you relinquish triage control to me, I can mark it as a duplicate of https://github.com/PowerShell/PSReadLine/issues/4447#issue-2830989421, formally linking them.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PowerShell/PSReadLine/issues/4072#issuecomment-2224037550

@daxian-dbw, refiled at https://github.com/PowerShell/PSReadLine/issues/4447#issue-2830989421. Thank you.
