### ISSUE TITLE
Need to change color of the text.

### ISSUE THREAD

**Issue by ogeccut** [PowerShell/PSReadLine#409]
Just installed by running Install-Module -Name PSReadLine

Now when i try to run Get-Process -Name....
Name i cant see. Not sure what its called. What do i need to change the color for?
Do i need to do it in profile?
Thank you.,

**Comment by rkeithhill** [comment]
You can change the parameter foreground (and background color):

``` powershell
Set-PSReadlineOption -TokenKind Parameter -ForegroundColor Cyan
```

Is your default console background really DarkGray?

**Comment by ogeccut** [comment]
Perfecto!@ Thank you.
