### ISSUE TITLE
Executing changed line but saving original in history

### ISSUE THREAD

**Issue by majkinetor** [PowerShell/PSReadLine#410]
I want to implement my own integrated variables such as `~` that stands for `$HOME`. I would like for example `^` to stand for user desktop so that  `notepad ^\meh` creates meh file on the desktop. Furthermore, I don't wont to replace `^` with correct path as it will also change it in history.

I first did this:

```
Set-PSReadlineKeyHandler -Key "Enter" -ScriptBlock {
    param($key, $arg)

    $word    = '^'
    $replace =  "$Env:USERPROFILE\Desktop"

    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    $word_idx = $line.IndexOf($word)
    if ($word_idx -ne -1) { [Microsoft.PowerShell.PSConsoleReadLine]::Replace($word_idx, $word.Length, $replace) }
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
}
```

This works OK except history. I tried this next:

```
Set-PSReadlineKeyHandler -Key "Enter" -ScriptBlock {
    param($key, $arg)

    $word    = '^'
    $replace =  "$Env:USERPROFILE\Desktop"

    $line = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
    $word_idx = $line.IndexOf($word)
    if ($word_idx -eq -1) { [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine(); return }

    [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($line)
    [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()


    $nline = $line.Replace($word, $replace)

    Write-Host
        iex $nline | Write-Host
    Write-Host
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}
```

and now history is OK and command gets executed but outputed lines will not move the prompt. 

Also, any error will be output via PSReadline, (in this case just typing `^` issues _Oops, something went wrong_ instead _The term 'c:...\Desktop is not recognized as the name of a cmdlet_ (minor issue for me)

How can I achieve this?

**Comment by lzybkr** [comment]
If I understand correctly, you want the unmodified command line in PSReadline history, and not the modified.

Assuming so, maybe you can be creative with `Set-PSReadlineOption -AddToHistoryHandler`.  e.g., if you modify the command line, insert an empty comment like `<##>` at the start, and in your AddToHistoryHandler, return false when the line starts with that text.

Your PowerShell history (Get-History) might look a little weird, but maybe you don't care.

Alternatively, maybe you can set a variable before calling AcceptLine, and clear it after.  Your AddToHistoryHandler would return `$false` when the variable is set.

**Comment by lzybkr** [comment]
Closing - I think this is answered.
