### ISSUE TITLE
Error popped up while typing

### ISSUE THREAD

**Issue by lorenpike** [PowerShell/PSReadLine#4102]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.22621.3958
OS: Microsoft Windows 10.0.22621
Last 39 Keys

 Escape k k k k k k j j j j j j j c d c i c d s a d f Backspace Backspace Backspace c d Spacebar M : / m e Escape Tab r e
```

### Exception
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ReplaceCharInPlace(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://github.com/user-attachments/assets/a1e24976-d879-42fc-bfd6-fa1f7f7720e1)

### Environment data

```console
PS Version: 5.1.22621.3958
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0
PSReadLine EditMode: Vi
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 118
BufferHeight: 98
```

### Steps to reproduce

Not sure what happened.

I do have vi mode set in PowerShell, if that is relevant

### Expected behavior

No exception

### Actual behavior

Mid-type, the error occurred and then returned to a new line

**Comment by daxian-dbw** [comment]
@lorenpike Thanks for reporting the issue. The version of PSReadLine you are using is 2.0.0, which is very old. Can you please upgrade to the latest v2.3.5 and try it again? It's likely the issue was fixed in newer versions.
