### ISSUE TITLE
Color of the text in the console.

### ISSUE THREAD

**Issue by ogeccut** [PowerShell/PSReadLine#411]
I am using PS5. I dont have any color on the commas, 
and 
Get-Service | select -Property \* 
- is not visible either.
  I think there is others but this makes it difficult to work.
  Thanks for the help.

Also this line:
Get-WmiObject Win32_Service | Where-Object { $_.StartMode -eq 'Disabled' }

-eq is not visible either.

**Comment by rkeithhill** [comment]
You can customize the colors (foreground and background) that PSReadline uses with:

``` powershell
Set-PSReadlineOption -TokenKind Parameter -ForegroundColor Cyan
```

Supported TokenKind are:

```
Command    Keyword    None       Operator   String     Variable
Comment    Member     Number     Parameter  Type
```

Comma is an operator so it is probably affect by TokenKind Operator.

**Comment by lzybkr** [comment]
If @rkeithhill didn't address your issue, feel free to reopen with more information.
