### ISSUE TITLE
Oops, something went wrong

### ISSUE THREAD

**Issue by Calendis** [PowerShell/PSReadLine#4119]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

I am on Windows 10
```console
Last 200 Keys:
 UpArrow Enter
 5 6 / 2 Backspace Backspace Backspace Backspace 2 8 Backspace Backspace 1 4 Backspace Backspace Ctrl+PageDown Ctrl+PageDown UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+c Ctrl+l Ctrl+UpArrow Enter
 Enter
 UpArrow Enter
 Ctrl+c Ctrl+l UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+c Ctrl+k Ctrl+c Ctrl+l UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+c Ctrl+l UpArrow Enter
 Ctrl+c Ctrl+l UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Shift+Enter Enter
 UpArrow DownArrow UpArrow Enter
```

### Screenshot
A large area of whitespace exists
![consolestate](https://github.com/user-attachments/assets/e4f69234-9abe-4ef9-b85f-b571b3cf14e5)

### Environment data

```console
PS Version: 5.1.19041.4648
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 148
BufferHeight: 39
```

### Steps to reproduce

idk

### Expected behavior

idk

### Actual behavior

Crashes

**Comment by daxian-dbw** [comment]
2.0.0-beta2 is a very old version of PSReadLine. Please upgrade to the latest '2.3.5' version and try again.
