### ISSUE TITLE
quelque s'est mal passé

### ISSUE THREAD

**Issue by olivierfranckensten** [PowerShell/PSReadLine#4121]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
quelque chose s'est mal passé
```

### Screenshot

![Annotation 2024-08-15 125810](https://github.com/user-attachments/assets/e322f59f-5a45-49c2-98ba-e605ad5528a1)

### Environment data

```console
quelque chose s'est mal passé
```

### Steps to reproduce

![Annotation 2024-08-15 125810](https://github.com/user-attachments/assets/1955424d-7dcd-4d75-ad8a-b42b7178874b)

### Expected behavior

![Annotation 2024-08-15 125810](https://github.com/user-attachments/assets/5412df0e-13f2-49e8-a695-010e000da30d)

### Actual behavior

![Annotation 2024-08-15 125810](https://github.com/user-attachments/assets/1dd62afa-3b2b-440f-851f-376ed99389d0)

**Comment by daxian-dbw** [comment]
![image](https://github.com/user-attachments/assets/a093b633-a016-4778-a0dc-f02d089efbff)

The URL in the picture indicates you were using a very old version of PSReadLine (2.0.0-beta2 or prior). Please upgrade to the latest v2.3.5 and give it a try.
