### ISSUE TITLE
PSReadline does not suggest old history

### ISSUE THREAD

**Issue by mdanish-kh** [PowerShell/PSReadLine#4131]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

Screenshot 1
![image](https://github.com/user-attachments/assets/946bca2c-958d-422b-a47f-1391fddbb02a)

Screenshot 2
![image](https://github.com/user-attachments/assets/452ef2f3-338f-4be6-ba7f-16c7d99de608)

### Environment data

```console
PS Version: 7.4.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.4.0-beta0
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 156
BufferHeight: 40
```

### Steps to reproduce

I have a an entry in my history file for `python manage.py startapp` (see screenshot 2). The current size of history file is 484 KB with ~10,000 lines. This most recent entry for this line is present at 5006 line number. I am not aware how far up the history query goes, judging by this [comment](https://github.com/PowerShell/PSReadLine/issues/3771#issuecomment-1686663871) I suppose it's the last 1 MB. If that's so, I would expect that PSReadline would suggest me this entry.

### Expected behavior

PSReadline doesn't suggest me the line entry (see screenshot 1 above)

### Actual behavior

PSReadline should suggest me the line entry

**Comment by daxian-dbw** [comment]
The maximum history entries read from the history file is controlled by `Set-PSReadLineOption -MaximumHistoryCount`. By default, `MaximumHistoryCount` is 4096, same as the automatic variable `$MaximumHistoryCount` of the PowerShell session.
In your case, please set it to a larger number, so that the history entry you want can be included in.

**Comment by mdanish-kh** [comment]
Ah, I should've poked around more to find it. I''ve put that command in my $PROFILE now. Anyways thank you!
