### ISSUE TITLE
Carriage return (enter key or line break) from clipboard text (when pasted) is not honored in Powershell

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#417]
Scenario: 
1) Connect to VM using vmconnect (Hyper-V Connection) 
2) Start a powershell form cmd window 
3) copy and paste clipboard below text from HOST to guest (Clipboard->Type Clipboard Text) will see that carriage return (or) ENTER key (or) line break is recognized by the powershell instead line break will be showed as ^MM. 

Though there are number of ways to get around to it; it just does not work as expected causing bit of delay in the flow/speed of getting things done. 

More tests done: 
CMD.exe prompt from the same VM could successfully identify carriage returns.

**Comment by lzybkr** [comment]
Closing in favor of #579 which covers all of the known issues with right-click paste.
