### ISSUE TITLE
CaptureScreen shift-up/shift-down arrows don't work on Windows 10

### ISSUE THREAD

**Issue by celebrith** [PowerShell/PSReadLine#419]
Ever since I upgraded to Windows 10, the CaptureScreen utility doesn't seem to work with the shift-up/down arrows to select text.  I can select any SINGLE line just fine and it works like it always has.  But I move the green line to the spot where I want to start, hold shift and then start either the up or down arrows, and the selection is highlighted in white from below the current command prompt, rather than highlighted in green from the selection.  When I press enter, it only captures the single line.
I noticed in the 1.2 release that "\* CaptureScreen allows j/k for up/down (for the vi fans)" - and I tried it, and shift-j/shift-k works fine.
So it seems to be something in the key bindings for the arrow keys, and it may (or may not) be specific to the Windows 10 client.

**Comment by lzybkr** [comment]
If you bind CaptureScreen to a key, it should work fine.  You're describing a known issue when you invoke the method directly (like you'd run any other command or call a .Net method).
