### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Humvy** [PowerShell/PSReadLine#4205]
### Prerequisites

- [X] Write a descriptive title.

**Comment by Humvy** [comment]
(RUS)
Произошла ошибка. Сообщите об этой ошибке, указав данные ниже.
Напишите в GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Последние клавиши 1:
 &

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: left
Фактическое значение было -2.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS F:\Workspace\PWork> & f:/Workspace/PWork/.venv/Scripts/python.exe f:/Workspace/PWork/NextDay.py

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
