### ISSUE TITLE
System.IO.IOException when I press <Ctrl+L>

### ISSUE THREAD

**Issue by dimmo** [PowerShell/PSReadLine#421]
PS C:\Users\dev>
Произошла ошибка.  Сообщите об этой ошибке, указав данные ниже.
## Сообщите в GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Последние разделы: 120:
 d o c k e r Spacebar r u n Spacebar - i t Spacebar - p Spacebar 8 0 : 8 0 Spacebar m i c r o s o f t / i i s : w i n d
o w s s e r v e r c o r e Spacebar c m d d o c k e r Spacebar r u n Spacebar - i t Spacebar - p Spacebar 8 0 : 8 0 Space
bar m i c r o s o f t / i i s : w i n d o w s s e r v e r c o r e Spacebar c m d Ctrl+c Ctrl+l

Исключение:
System.IO.IOException: Параметр задан неверно.

   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.Console.SetWindowPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignore
IfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
Most likely a dupe of #292, reopen with additional information if you disagree.
