### ISSUE TITLE
Should not beep on backspace with cursor at start of line

### ISSUE THREAD

**Issue by craiglandis** [PowerShell/PSReadLine#422]
Beep on backspace with cursor at start of line should not be the default behavior for the default EditMode (-EditMode Windows), but it currently is that way in PowerShell 5.1 (Win10 1607 14393.51).

Right now people are forced to figure out that they must do things like put Set-PSReadlineOption -BellStyle None in their PowerShell profile, or run net stop beep + sc config beep start= disabled, to stop the beeping, as it does not honor the Sounds control panel "No Sounds" scheme, and beeps anyway.

If this change was only intended for -EditMode Vi, maybe as parity, then it should only be the behavior for that edit mode, but should not be the default behavior for -EditMode Windows.

See also http://superuser.com/questions/1113429/disable-powershell-beep-on-backspace

**Comment by lzybkr** [comment]
Beeps are annoying.  @srdubya - is this really expected in vi mode?

**Comment by srdubya** [comment]
I just fired up Bash on Ubuntu on Windows with "set -o vi" and it beeps under this circumstance.  With that said, I have no objection to taking it out or making it an option which defaults to off.

**Comment by gwojan** [comment]
I vote for making it an option... :+1: :smile: 

I'm trying to keep the default behavior as close to bash, cygwin, etc.

**Comment by lzybkr** [comment]
I just noticed it beeps in emacs mode mode on bash - so it's consistent - it definitely shouldn't beep in Windows mode.

I'm not a fan of too many configuration options.  If the only justification is to keep behavior as close as possible to bash, then I'll probably just remove the beep.  If there is a better justification, I'll reconsider.

**Comment by FaustoNascimento** [comment]
Any news on this? It's a (very annoying) bug that's been there for a rather long time now and no updates here...

I've been "forced" to disable the beep service in the office, as it was annoying everyone around me. I realize that I can disable it via Set-PSReadlineOption and a PS profile, but that's just another workaround, not a real fix.

**Comment by lzybkr** [comment]
I'm just busy with other things, hopefully I'll get a new release out with some important fixes soon

**Comment by dazcode** [comment]
It is easy to turn off the beep if you know some basics of powershell,  but beginners who might need help can use this script:

https://www.powershellgallery.com/packages/NoBeep/2.2/DisplayScript

to use just run: 

Save-Script -Name NoBeep -Path <path> -RequiredVersion 2.0
or 
Install-Script -Name NoBeep -RequiredVersion 2.0

hope this helps

**Comment by dazcode** [comment]
I put up a small script on the PSGallery in case new users need a temporary fix:
https://www.powershellgallery.com/packages/NoBeep/2.2/DisplayScript
