### ISSUE TITLE
### Environment PSReadLine: 2.0.0 PowerShell: 5.1.22621.4249 OS: Microsoft Windows 10.0.22631 Last 176 Keys ```  c d Spacebar " c : \ U s e r s \ s a m s o \ s o u r c e \ r e p o s \ C + + Spacebar ( P u r p l e ) Spacebar p r o j e c t s \ H e l l o Spacebar W o r l d \ H e l l o Spacebar W o r l d \ " Spacebar ; Spacebar i f Spacebar ( $ ? ) Spacebar { Spacebar g c c Spacebar t e m p C o d e R u n n e r F i l e . c Spacebar - o Spacebar t e m p C o d e R u n n e r F i l e Spacebar } Spacebar ; Spacebar i f Spacebar ( $ ? ) Spacebar { Spacebar . \ t e m p C o d e R u n n e r F i l e Spacebar } Enter  ```

### ISSUE THREAD

**Issue by Makie-lab** [PowerShell/PSReadLine#4226]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.22621.4249
OS: Microsoft Windows 10.0.22631
Last 176 Keys

 c d Spacebar " c : \ U s e r s \ s a m s o \ s o u r c e \ r e p o s \ C + + Spacebar ( P u r p l e ) Spacebar p r o j e c t s \ H e l l o Spacebar W o r l d \ H e l l o Spacebar W o r l d \ " Spacebar ; Spacebar i f Spacebar ( $ ? ) Spacebar { Spacebar g c c Spacebar t e m p C o d e R u n n e r F i l e . c Spacebar - o Spacebar t e m p C o d e R u n n e r F i l e Spacebar } Spacebar ; Spacebar i f Spacebar ( $ ? ) Spacebar { Spacebar . \ t e m p C o d e R u n n e r F i l e Spacebar } Enter

```

### Screenshot

![image](https://github.com/user-attachments/assets/55f5879e-3486-4474-9cf1-536fbc964700)
![Screenshot 2024-10-15 205251](https://github.com/user-attachments/assets/ebb73309-790e-4df3-918e-696146f411ce)

### Environment data

```console
PSReadLine: 2.0.0
PowerShell: 5.1.22621.4249
OS: Microsoft Windows 10.0.22631
Last 176 Keys
```

### Steps to reproduce

running the program

### Expected behavior

error

### Actual behavior

error

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
