### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below. Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by Lacikika** [PowerShell/PSReadLine#4244]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Exception:
System.ArgumentOutOfRangeException: Az értéknek nullával egyenlőnek vagy annál nagyobbnak és a konzol pufferméreténél kisebbnek kell lennie az adott dimenzióban.
Paraméter neve: top
Az aktuális érték: -1.
   a következő helyen: System.Console.SetCursorPosition(Int32 left, Int32 top)
   a következő helyen: Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   a következő helyen: Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   a következő helyen: Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   a következő helyen: Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   a következő helyen: Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   a következő helyen: Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![kép](https://github.com/user-attachments/assets/0119ede0-9e84-498b-966b-d7a369c4c3d7)

### Environment data

```console
-
```

### Steps to reproduce

i dont know

### Expected behavior

i dont know

### Actual behavior

nothing

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
