### ISSUE TITLE
PowerShell 7.4 issue with Windows 10 1904

### ISSUE THREAD

**Issue by JamesMDorame** [PowerShell/PSReadLine#4245]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.4.6
OS: Microsoft Windows 10.0.19045
BufferWidth: 120
BufferHeight: 30

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://github.com/user-attachments/assets/0e723a5b-de91-46a1-bf47-ab3655b9190e)

### Environment data

```console
PS Version: 6.2.3
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

Using either winget or the downloaded MSI install PowerShell 7.4 and start the Terminal and error occurs

### Expected behavior

PowerShell 7.4 should run

### Actual behavior

Error occurs

**Comment by daxian-dbw** [comment]
The `2.2.0-beta2` version of PSReadLine introduced a breaking change. Please upgrade to the latest v2.3.6 of PSReadLine and you should be good.
