### ISSUE TITLE
Error when using tab delimiter on file path

### ISSUE THREAD

**Issue by JoshSchofield** [PowerShell/PSReadLine#426]
When using get-content -Path ./Downloads/ and then pressing Tab, I am warned that there were 409 options to show and whether or not to show them (y or n) when I typed n the list started to populate then received an errors as listed below:

WhirlLast 48 Keys:ved_questions.xml                                                   g e t - c o n e Backspace t e n t Enterdpoint Manager (BigFix) -unsigned.xml    Ctrl+C UpArrow Spacebar - f i Tab Tab Tab Tab Backspace Backspace p Tab Tab Tab a Tab Spacebar . / D o w n l o a d s Tab Tab Tab y                                           windows-patch_5.10.xml                                            Exception:                                     windows-vuln_5.10.xml            System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.                  Parameter name: top              Windows10Compatibility.xml                     Actual value was -144.                                            Within Critica   at System.Console.SetCursorPosition(Int32 left, Int32 top)                      at Microsoft.PowerShell.Internal.TTYConsole.SetCursorPosition(Int32 left, Int32 top)                                             zabbix_appliance_3.0.3.iso     at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)        at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor()                         at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()                        at Microsoft.PowerShell.PSConsoleReadLine.Render()                  ZBSTAN02.   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)                                            at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Nullable`1 key, Object arg, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
The stack trace is different, but #503 is very likely the same thing. At any rate, the code has been rewritten significantly and likely is fixed.
