### ISSUE TITLE
Error in vs code

### ISSUE THREAD

**Issue by poliii8** [PowerShell/PSReadLine#4267]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   в Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

N/A

### Environment data

```console
res = 7*512**3200 + 6*256**3100 - 5*64**3000 - 4*8**2900 - 1542
count = 0
while res:
    if res % 64 == 0:
        count += 1
        res // 25
        print(count)
```

### Steps to reproduce

res = 7*512**3200 + 6*256**3100 - 5*64**3000 - 4*8**2900 - 1542
count = 0
while res:
    if res % 64 == 0:
        count += 1
        res // 25
        print(count)                    
                

### Expected behavior

Numeric response

### Actual behavior

erroe

**Comment by daxian-dbw** [comment]
You didn't include any environment data, but it's likely you are on an old version of PSReadLine. Please upgrade PSReadLine to the latest v2.3.6 and try again.
