### ISSUE TITLE
List view should include prediction for non-native commandlets (modules) and user functions.

### ISSUE THREAD

**Issue by RalfReddings** [PowerShell/PSReadLine#4276]
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

I think since PSReadLine 2.3.0, its been possible for the list view to also predict the paramters for native commandets such as `get-item` but this feature does not work with third party modules, users own modules and even functions.

It would be nice if PsReadline could parse session modules/functions and provide predictions for paramters and their built in values such as `ValidtateSet` values. 

Am on:
- PSReadLine 2.3.6
- Windows 11
- Powershell 7.4

**Comment by StevenBucher98** [comment]
This is a function of the completion predictor, https://github.com/PowerShell/CompletionPredictor, if the non-inbox modules/cmdlets have registered tab completions then it will work with this module imported.
