### ISSUE TITLE
Não é possível carregar o módulo de PSReadline. O console está sendo executado sem PSReadline.

### ISSUE THREAD

**Issue by Weisdias** [PowerShell/PSReadLine#4299]
### Prerequisites

- [X] Write a descriptive title.

**Comment by StevenBucher98** [comment]
@Weisdias please resubmit this issue with more details and preferably in english 😄  thanks!

**Comment by Weisdias** [comment]
Good morning,

I'm coding in VSCode and when I run the code this message appears "Unable to load the PSReadline module. The console is running without PSReadline." What to do?
