### ISSUE TITLE
Make HistorySearch cursor movement similar to standard readline

### ISSUE THREAD

**Issue by SRGOM** [PowerShell/PSReadLine#438]

**Comment by SRGOM** [comment]
https://github.com/lzybkr/PSReadLine/blob/0ffd1b2351214f1f25a433060a6c75a29c59c90f/PSReadLine/History.cs:487 has `HistorySearch` being called with `moveCursor` being `true` hardcoded. The standard readline behaviour (at least as I observe in bash and zsh on unix/wsl) is that the cursor stays on its place. I see there's even an option for that but its not being used uniformly. 

I can make this change but I need to know what's the right approach here and what the significance of that option is? 

q1: Is the option meant to replace all places where the value is hardcoded right now?

q2: Are you open to setting the option false by default?

The AppVeyor build is failing right now so I'm not very keen on changing stuff, though.

**Comment by lzybkr** [comment]
I fixed AppVeyor, so feel free to fix - if you submit a PR, please do so via https://github.com/PowerShell/PSReadLine so you can sign the CLA.

The [default](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/Cmdlets.cs#L99) for the option is false, so no change is needed there.

I think the call from HistorySearch to UpdateFromHistory can change to use the option. The other calls probably shouldn't change though, they aren't searching history. For example, [this call](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/ReadLine.cs#L574) is used as part of Ctrl+o to execute and recall the next command - there was no search involved in that recall.

**Comment by SRGOM** [comment]
Ok I've moved back from Windows (till WSL has some of my required features) so cannot help with this (Powershell doesn't build on my current OS- Arch). Thank you for PSReadline though. Using Powershell without it is very frustrating! :-)
