### ISSUE TITLE
PSReadLine history should take the max of $MaximumHistoryCount and its MaximumHistoryCount option

### ISSUE THREAD

**Issue by billwert** [PowerShell/PSReadLine#441]
Today, the default number of lines read in from your history file is $MaximumHistoryCount, which defaults to 4096 on Win10. (Not sure on other platforms.) Adding $MaximumHistoryCount to your PS profile increases this, but it maxes out at 32767. I'd love the ability to have it take the larger of $MaximumHistoryCount and options.MaximumHistoryCount (set through Set-PSReadlineOption.)

**Comment by rkeithhill** [comment]
I don't believe these two should be tied together.  The HistoryInfo object collection for the current session history (and who's size is contolled by $MaximumHistoryCount) is different from the history stored (across sessions) by PSReadline.

**Comment by daxian-dbw** [comment]
I agree that these two should be separated.
