### ISSUE TITLE
Some vi functions cannot be set as KeyHandlers

### ISSUE THREAD

**Issue by razaraz** [PowerShell/PSReadLine#445]
I was remapping my Vi KeyHandlers to match my dvorak keyboard layout, when I came across an error:

PS>Set-PSReadlineKeyHandler -Key 'c,s' -Function ReplaceChar -ViMode Command 
_Set-PSReadlineKeyHandler : Cannot validate argument on parameter 'Function'. The argument "ReplaceChar" does not belong to the set "..."_

Then I realized that none of the Vi replacement functions were listed. I browsed the code for a bit, and I'm pretty sure I found the issue: For some reason, all the methods in the file [PSReadLine/Replace.vi.cs](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/Replace.vi.cs) are declared as private. As a result, [SetPSReadLineKeyHandlerCommand.CreateDynamicParametersResult()](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/Cmdlets.cs#L677) won't catch them as valid function arguments.

Thanks for all the work that's been put on this module. It makes working on the command line a joy!

**Comment by razaraz** [comment]
I also found that some functions in [PSReadLine/ReadLine.vi.cs](https://github.com/lzybkr/PSReadLine/blob/0ffd1b2351214f1f25a433060a6c75a29c59c90f/PSReadLine/ReadLine.vi.cs) have the same issue: ViDeleteToChar, ViDeleteToCharBackward, ViDeleteToBeforeChar, and ViDeleteToBeforeCharBackward are some of the ones I've caught.

**Comment by lzybkr** [comment]
I believe #445 fixes this issue.

**Comment by razaraz** [comment]
Thank you!
