### ISSUE TITLE
DarkGray option color in PowerCLI

### ISSUE THREAD

**Issue by Tremorus** [PowerShell/PSReadLine#450]
Hi all!
I can't see no one options in the PowerCLI, because they are transparent!

Like this:

``` powershell
Set-PSReadlineOption            Parameter                  green
```

Next time I see options in near-green colors.

``` powershell
Set-PSReadlineOption -TokenKind Parameter -ForegroundColor green
```

At all, all colors are incorrect: DarkRed, DarkMagenta,Red,Magenta are the same, near-red color, for example.
Help me please! Where can I change those colours in PowerCLI.
p.s. I can't attach screenshot now.

**Comment by lzybkr** [comment]
Unfortunately, the color names come from .Net and do not reflect any specific RGB value.

I'm not familiar with PowerCLI, but one of these links should help:

http://www.leeholmes.com/blog/2008/06/01/powershells-noble-blue/
http://commandwindows.com/configure.htm
