### ISSUE TITLE
Generate PSReadline.dll-help.xml

### ISSUE THREAD

**Issue by razaraz** [PowerShell/PSReadLine#451]
Currently the PSReadline solution does not build as-is since the file PSReadLine/en-US/PSReadline.dll-help.xml does not exist, and the PSReadLine CSProj includes it.

According to #432 the file should be generated via PlatyPS. This generation step could be implemented as an MSBuild custom build step, and PSReadline.dll-help.xml could be removed from the solution, as it would now be a build output, rather than a source file.

**Comment by lzybkr** [comment]
I might get around to this sometime, but I have plenty of other stuff I need to get to first.  I'd love a PR if someone wants to fix this for me.

I've been running MakeRelease.ps1 first, that runs PlatyPS, so that should get you going.

**Comment by lzybkr** [comment]
This was fixed in  7a35e21 when I started using Invoke-Build.
