### ISSUE TITLE
ClearScreen and multi-line prompt

### ISSUE THREAD

**Issue by ebugusey** [PowerShell/PSReadLine#452]
#### Steps

Set prompt like this:

``` powershell
function prompt () {
    $prompt = `
        "$env:USERNAME@$env:COMPUTERNAME $PWD`n" + `
        "`$ "
    return $prompt
}
```

Invoke `ClearScreen`.
#### What I got

Only last string of prompt is visible.
#### Expected

Entire prompt is visible.

**Comment by lzybkr** [comment]
My prompt is similar and it works as expected for me, but you need the following:

``` powershell
Set-PSReadlineOption -ExtraPromptLineCount 1
```

**Comment by ebugusey** [comment]
Oh. Sorry. Didn't know about this option.
