### ISSUE TITLE
ReverseSearchHistory in VI mode

### ISSUE THREAD

**Issue by twsouthwick** [PowerShell/PSReadLine#455]
I really like the reverse search history mode, but it is not enabled by default in VI mode. Is there a reason for this? I found that I could get command back by doing:

```
Set-PSReadlineKeyHandler -Key Ctrl+r -Function ReverseSearchHistory
```

Seems like this should be available by default. Also, this is only available in "Insert" mode - is that by design or is there a way to get it working all the time?

**Comment by lzybkr** [comment]
Yeah, it looks like it should be there by default, it is in `bash`.

To enable in both modes, you could use:

```
Set-PSReadlineKeyHandler -Key Ctrl+r -Function ReverseSearchHistory -ViMode Insert
Set-PSReadlineKeyHandler -Key Ctrl+r -Function ReverseSearchHistory -ViMode Command
```

**Comment by srdubya** [comment]
I'm sorry I missed those.  I've always been a /?nN guy, myself.

**Comment by twsouthwick** [comment]
Cool. I did not realize that the / syntax worked as well. Very cool! Those work fine. I'll keep this open if you want to use it to track adding it by default; I'm fine with the workaround, though (added it to my profile.ps1 and it works like a charm).

**Comment by srdubya** [comment]
As fix for this is now part of my pending pull request.
