### ISSUE TITLE
Clear-History isn't working on OS X 10.11.6

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#465]
_From @blooodorange on August 19, 2016 20:30_

## Steps to reproduce

Clear-History
## Expected behavior

https://technet.microsoft.com/en-us/library/hh849733.aspx
## Actual behavior

Clear-History does not delete previously used commands
## Environment data

``` powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

_Copied from original issue: PowerShell/PowerShell#1968_

**Comment by lzybkr** [comment]
_From @fxlv on August 20, 2016 6:53_

Tried same thing on OSX also, indeed you still get your history with arrow keys, but if you query the history with `Get-History` then it appears cleared.
Perhaps 2 different sets of history are kept?

**Comment by lzybkr** [comment]
_From @fxlv on August 20, 2016 7:0_

I did some dtracing.
Looks like there are indeed 2 sets of history, one from the powershell, other from readline.

The readline one is in `~/.local/share/powershell/PSReadLine/ConsoleHost_history.txt` and it is not cleared when calling `Clear-History`

**Comment by lzybkr** [comment]
_From @fxlv on August 20, 2016 7:21_

I did more digging. This is https://github.com/lzybkr/PSReadLine that is saving the history.

So in fact the `Clear-History` might not even be doing anything wrong (though it is misleading).
There are some workarounds, such as removing the history file - http://stackoverflow.com/questions/13257775/powershell-clear-history-doesnt-clear-history

But probably PowerShell guys will provide much better answer.

**Comment by lzybkr** [comment]
@fxlv - your digging is spot on.  `Clear-History` existed long before `PSReadline`.  There has been some discussion about better integration of history, but it hasn't really happened yet, partly because PSReadline is optional on Windows.

**Comment by daxian-dbw** [comment]
I will close this one as we don't have any plan on making `Clear-History` to work with PSReadLine. Also `PSReadLine` is still optional to PowerShell (not loaded in non-interactive mode).
