### ISSUE TITLE
Console Host redraws the current line after every character

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#469]
_From @DHowett on August 18, 2016 16:23_

## Steps to reproduce

Launch powershell. Type a command.
Observe that the cursor flickers left and right, back and forth, for every character you type.
This may require a terminal with slower refresh.
## Expected behavior

The input is only redrawn when it becomes necessary.
## Actual behavior

The input is redrawn for every input character.

I profiled this, and found that for the input (and output):

```
PS > powershell redraws a lot
```

... which is a paltry few bytes, we emit 52,501 bytes of ANSI escape sequences repositioning the cursor, drawing colours, repositioning the cursor some more, etc.
## Environment data

``` powershell
root@f49460ec9455:/# powershell -c '$PSVersionTable'

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

_Copied from original issue: PowerShell/PowerShell#1877_

**Comment by lzybkr** [comment]
_From @DHowett on August 18, 2016 16:36_

Thought: perhaps this is to mimic the Windows console's support for drawing characters at any coordinates (_without cursor moves_)? It looks like we could be trying to do the same thing, but because it's being used to such a high degree we're emitting a veritable boatload of CSIs.

It's especially noticeable over remote links with nonzero latency.

**Comment by lzybkr** [comment]
The current design exists to keep things simple - e.g. the color of text previously entered _might_ change after typing a character.  The current design also performs much better on Windows than the simple alternatives.

At any rate, thanks for the report, this is a known issue that we definitely plan on addressing.

**Comment by ghost** [comment]
I suppose you can see this in action here: https://www.youtube.com/watch?v=JNiX6PxO4fs
