### ISSUE TITLE
Running core edition of powershell under ssh from windows results in broken UX

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#471]
_From @vors on June 9, 2016 20:25_

## Steps to reproduce
- From windows box, open inbox powershell
- ssh to a linux VM. Use ssh that comes with windows version of git from command line

```
C:\Program Files\Git\usr\bin\ssh.exe
```
- Follow [instructions](https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md#toolchain-setup) to install powershell
- Everything works fine up to this point
- Run powershell
- Try to do something
## Expected behavior

You should be able to work
## Actual behavior

Console UX is broken:
half of commands are entered at the top of the screen, overriding the buffer

![image](https://cloud.githubusercontent.com/assets/816680/15945104/96e1e294-2e45-11e6-8f91-a2c59efa13e0.png)
## Environment data

v0.4.0

_Copied from original issue: PowerShell/PowerShell#1088_

**Comment by lzybkr** [comment]
_From @vors on June 9, 2016 20:28_

![image](https://cloud.githubusercontent.com/assets/816680/15945180/fd55c784-2e45-11e6-9f60-cf90d5f9424b.png)

**Comment by lzybkr** [comment]
_From @vors on June 9, 2016 20:30_

Same for running from inbox cmd

**Comment by lzybkr** [comment]
_From @vors on July 27, 2016 20:56_

Workaround: use `putty` as ssh client

**Comment by lzybkr** [comment]
_From @joeyaiello on July 27, 2016 20:56_

@vors: thanks

**Comment by lzybkr** [comment]
_From @Jaykul on July 31, 2016 4:22_

This problem also affects PowerShell running within _Bash on Ubuntu on Windows_ whether directly in the bash console or in ConEmu. As soon as I start typing, the cursor moves to column 0 ...  and if the prompt past line 10, it goes back to line 0.

**Comment by lzybkr** [comment]
_From @mwrock on August 15, 2016 0:15_

I'm experiencing this as well. Makes the linux experience nearly unusable. Putty is a pretty undesirable workaround.

**Comment by lzybkr** [comment]
_From @mwrock on August 15, 2016 0:46_

I typically use the mingw ssh that ships with git. Note that in SSH my `TERM` is set to `cygwin` I just thought I'd try `ssh` from the Bash on Ubuntu on Windows. This is a much better experience. A few little glitches but workable. `TERM` is set to `xterm` here.

**Comment by lzybkr** [comment]
_From @MathiasMagnus on August 19, 2016 8:10_

Same here. I wanted to try PS on an Ubuntu 16.04 remote cluster node, but the console got really messed up. I tried both ssh.exe that ships with Git for Windows, and also the one from bash.exe (upgraded to Ubuntu 16.04). Neither worked properly. Arrow keys not working properly to move inline and in history, in some places backspace doesn't work... not glitched, but broken.

The few commands that worked got the expected results, so anticipation is not lost, but grew even more. Very eager to try a fixed version, or even start tweaking with a hotfix, but Putty really is not an elegant workaround.

**Comment by lzybkr** [comment]
_From @Jaykul on August 22, 2016 2:31_

By the way guys, if you install PowerShell core on your windows box, you can use PowerShell remoting to the Ubuntu box (over SSH). That seems to be working fine (with the exception that _at least with ConEmu in the way_, the Ctrl+C/Ctrl+V don't work in PSReadLine).

**Comment by lzybkr** [comment]
_From @MathiasMagnus on August 22, 2016 8:47_

I found [this](https://github.com/PowerShell/PowerShell/tree/master/demos/SSHRemoting) tutorial on PowerShell Core and SSH remoting, but it does not work, at all. The installed PS Core 6.0.0.9 fails to ping not just the host, but even itself.

Microsoft PowerShell:

```
PS C:\Users\Matty> Test-Connection 127.0.0.1

Source        Destination     IPV4Address      IPV6Address                              Bytes    Time(ms)
------        -----------     -----------      -----------                              -----    --------
MATTY-Z50-75  127.0.0.1       148.6.182.187    ::1                                      32       0
MATTY-Z50-75  127.0.0.1       148.6.182.187    ::1                                      32       0
MATTY-Z50-75  127.0.0.1       148.6.182.187    ::1                                      32       0
MATTY-Z50-75  127.0.0.1       148.6.182.187    ::1                                      32       0
```

PowerShell Core:

```
PS C:\Kellekek\Microsoft\PowerShell\6.0.0.9> Test-Connection 127.0.0.1
Test-Connection : Az ügyfél nem tud kapcsolatot létesíteni a kérelemben megadott célhellyel.  Ellenőrizze, hogy a célhelyen a szolgáltatás fut és kész kérések fogadására. Tekintse meg a célhelyen futó WS-Management szolgáltatás (általáb
an az IIS vagy a Rendszerfelügyeleti webszolgáltatások) naplóját és dokumentációját. Ha a célhely a Rendszerfelügyeleti webszolgáltatás, a következő parancs azon történő futtatásával elemezheti és konfigurálhatja a Rendszerfelügyeleti w
ebszolgáltatásokat: "winrm quickconfig".
At line:1 char:1
+ Test-Connection 127.0.0.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-Connection], CimException
    + FullyQualifiedErrorId : TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand
```

(Translation: the client cannot establish a connection with the required remote client...) Am I doing something wrong? New-PSSession says:

```
PS C:\Kellekek\Microsoft\PowerShell\6.0.0.9> $session = New-PSSession -HostName ...
New-PSSession : [<hostname here>] An error has occurred which Windows PowerShell cannot handle. A remote session might have ended.
At line:1 char:12
+ $session = New-PSSession -HostName <hostname here> -UserName ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingDataStructureException
    + FullyQualifiedErrorId : PSSessionOpenFailed
```

**Comment by KirkMunro** [comment]
Hey @lzybkr, I just hit this issue with a different scenario.

Ubuntu 16.04 with docker and a modified build of Shell-in-a-Box (all I added was a POSH application value that could be used to docker run microsoft/powershell). When I browse to https://127.0.0.1/ps (my shortcut to the POSH application, which auto-logs in for testing), I get the PowerShell prompt, but any commands I type show up at the top of the terminal window. I can still run them (somewhat, seems clunky this way and I've seen some weird behaviour once I run a few commands), but I want to type/run inline, like I would with a native prompt.

Can you offer pointers on where the bug might be here if someone wanted to fix this?

**Comment by lzybkr** [comment]
I'm not sure where I'd start to be honest, I guess maybe setting a breakpoint in the .Net code that moves the cursor.

**Comment by SteveL-MSFT** [comment]
This appears to be a problem with Git's cygwin based ssh.exe as well as TERM not being set to something powershell uses.  See the original issue https://github.com/PowerShell/PowerShell/issues/1088, this doesn't appear to be a PSReadline issue.

**Comment by lzybkr** [comment]
OK, closing since the original issue was reactivated.
