### ISSUE TITLE
PSReadline should special case the Active Directory provider to not append backslashes

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PSReadLine#473]
Filed via UserVoice: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/16893115-activedirectory-psdrive-problem-with-psreadline-in

Basically, the AD provider doesn't expect trailing backslashes when navigating its "filesystem", and breaks if you don't remove them. I know that the technically correct thing here would probably be for them to support trailing backslashes, but I think this is probably a much quicker, less painful change that we can make to unbreak customers.

**Comment by daxian-dbw** [comment]
Closing this old issue given that there are no more recent complaints or reports on this AD provider issue.
