### ISSUE TITLE
Import-Module tab completion not working when inside $env:PSModulePath

### ISSUE THREAD

**Issue by Aculeo** [PowerShell/PSReadLine#477]
When trying to import a module tab completion isn't working if my current working directory happens to be the same as the module path defined in `$env:PSModulePath`. When I hit tab twice I can see that all modules are listed twice.

**PowerShell Version:**
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
PSReadLine is version 1.2.

**Comment by lzybkr** [comment]
This issue was moved to PowerShell/PowerShell#2813

**Comment by Aculeo** [comment]
I'm pretty sure this is a problem with this module and not PowerShell. If I disable PSReadLine it works fine. When I enable it and try to use tab completion I get this (TestModule listed twice):

![grafik](https://cloud.githubusercontent.com/assets/3977620/20787021/f5d882ce-b7a9-11e6-84a6-cdc1a2ba9ae9.png)

Edit: Forgot to mention I'm also using `Set-PSReadlineKeyHandler -Key Tab -Function Complete` in my PS profile.

**Comment by lzybkr** [comment]
The problem is in PowerShell - it shouldn't be returning multiple effectively identical completions.
