### ISSUE TITLE
How to emulate C-x, C-e using PSReadline

### ISSUE THREAD

**Issue by webframp** [PowerShell/PSReadLine#478]
Thanks for this great project.

I'd like to emulate the behavior of `C-x,C-e` key chord to open whatever is on the current command line in the users configured `$EDITOR` and then run the command when `$EDITOR` exits. Described for example in [this SO post](http://unix.stackexchange.com/questions/6620/how-to-edit-command-line-in-full-screen-editor-in-zsh)

I've been reviewing the sample profile and documentation, but I'm not quite clear on how this could be done.

**Comment by lzybkr** [comment]
@srdubya implemented this for vi mode.

I thought this would work:

```PowerShell
$env:EDITOR = 'gvim'
Set-PSReadlineKeyHandler -Chord 'Ctrl+x,Ctrl+e' -Function ViEditVisually
```

It pops up `gvim`, but the command line is not there to edit  It seems like it shouldn't be hard to fix though.

**Comment by lzybkr** [comment]
New key binding added in 647da39
