### ISSUE TITLE
Incremental Search for MenuComplete

### ISSUE THREAD

**Issue by MVKozlov** [PowerShell/PSReadLine#485]
still can't use Menucomplete because it not have incremental search and **set** first available command  instead of _suggesting_ it

Is any plans for it since 2014 ?

**Comment by lzybkr** [comment]
Most folks find `MenuComplete` plenty useful as is, but I agree that it can be improved. This is a side project for me, so if someone doesn't do it first, I'll get to it when I get to it.

**Comment by MVKozlov** [comment]
I found dirty way to do Incremental search but it is need more efficient way for repeating MenuSelect call 
May be you can help with it ?
Here is the diff, just a few lines added
https://gist.github.com/MVKozlov/04253d87086298e90fecef5ba784c65e
