### ISSUE TITLE
Possible bug embedding `using module` inside a method call

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PSReadLine#489]
Was deleting a `using module Foo` statement inside a `[powershell]::AddStatement(...)` method call. Screenshot attached:
![psbug](https://cloud.githubusercontent.com/assets/7009879/21832463/2d0ba32c-d760-11e6-9eb9-ff4d38a9684f.PNG)

**Comment by lzybkr** [comment]
This issue was moved to PowerShell/PowerShell#2992
