### ISSUE TITLE
Need option for case-insenstive path tab completion for Linux

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#497]
This is driving me a bit bonkers atm.  Sure would be nice to have an option for this like the Bash equiv of `set completion-ignore-case on`.

**Comment by lzybkr** [comment]
This is https://github.com/PowerShell/PowerShell/issues/1273.

**Comment by rkeithhill** [comment]
I couldn't remember exactly who was doing the path expansion.  Thanks.
