### ISSUE TITLE
Port PSReadLine project to compile on .NET Core

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#498]
It must compile on .NET or we wouldn't have it in PowerShell Core.  What I'd like to be able to do is compile/debug PSReadLine on Linux.

**Comment by lzybkr** [comment]
This is wip, see https://github.com/lzybkr/PSReadLine/pull/442

I'm trying to work out a solution where I can generate 1 binary that works on all platforms to avoid shipping 3 binaries (Linux, Windows Core, Windows Full) - like what is happening today with PackageManagement.

**Comment by lzybkr** [comment]
I should mention - I have more changes on top of that PR that I haven't pushed yet because it's not ready.

**Comment by rkeithhill** [comment]
You might talk with @daviwil if you haven't already.  He just did this for the PowerShellEditorServices.  It all builds from within VS Code.

PS. Glad to hear that work is under way.  Cool!

**Comment by lzybkr** [comment]
Right now I'm hitting https://github.com/dotnet/corefx/issues/9658
I might have a sort of workaround to target the netstandard1.6 version of the System.Management.Automation reference assembly, but that could cause problems targeting older versions of PowerShell, e.g. if we use an api that wasn't in V3.

**Comment by daviwil** [comment]
Weird, I use Hashtable in a couple places in PSES and I'm building against netstandard1.6 just fine:

https://github.com/PowerShell/PowerShellEditorServices/blob/2c7709bfe2748e9c832a9488e17010e63c71fb28/src/PowerShellEditorServices/Session/PowerShellVersionDetails.cs#L103

I'm building against the Microsoft.PowerShell.SDK package on MyGet:

https://powershell.myget.org/feed/powershell-core/package/nuget/Microsoft.PowerShell.SDK

I'm also using the v3-v5 reference assemblies to verify that my code builds against the older apis:

- https://github.com/PowerShell/PowerShellEditorServices/blob/develop/PowerShellEditorServices.build.ps1#L135
- https://github.com/PowerShell/PowerShellEditorServices/blob/develop/src/PowerShellEditorServices/PowerShellEditorServices.csproj#L58
