### ISSUE TITLE
Parser or PSReadLine error?

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PSReadLine#500]
The code:
```powershell
class foo
{
    [void]q() { $a=1 }

    [string]$bar
}
```
is failed with PSReadLine loaded. Without PSReadLine the code is succeeed.

@lzybkr  Could you please clarify the problem is in Powershell parser or PSReadLine?

```powershell
PS C:\> class foo
>>> {
>>>     [void]q() { $a=1 }
>>>
At line:3 char:5
+     [void]q() { $a=1 }
+     ~~~~~~~~~~~~~~~~~~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

PS C:\>     [string]$bar

PS C:\> }
At line:1 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\>
PS C:\> Remove-Module PSReadline
PS C:\> class foo
>> {
>>     [void]q() { $a=1 }
>>
>>     [string]$bar
>> }
>>
PS C:\>
```

**Comment by lzybkr** [comment]
This is a bug in the parser - it should be throwing an `IncompleteParseException` instead of a `ParseException`.

Note that the repro only happens if you right-click.  If you paste with Ctrl+v (in Windows PowerShell, not yet available in PowerShell Core), you won't see an error.

**Comment by iSazonov** [comment]
@lzybkr Thanks! I moved the Issue to Powershell repo.
(in Windows PowerShell with Ctrl+v I see the same on Win 5.0.10240.17146)
