### ISSUE TITLE
Single string getting converted to a multiline command in history

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#513]
This string is throwing off PSReadline's history save processing a bit:
```powershell
"- posh-git version/path: $($m = Get-Module posh-git; '{0} {1} {2}' -f $m.Version,$m.PrivateData.PSData.PreReleaseVersion,$m.ModuleBase.Replace($HOME,'~'))`n- PowerShell version: $($PSVersionTable.PSVersion)`n- $(
git --version)`n- OS: $([System.Environment]::OSVersion)"
```
This single line string shows up as multiline in the history file:
```
"- posh-git version/path: $($m = Get-Module posh-git; '{0} {1} {2}' -f $m.Version,$m.PrivateData.PSData.PreReleaseVersion,$m.ModuleBase.Replace($HOME,'~'))`n- PowerShell version: $($PSVersionTable.PSVersion)`n- $(`
git --version)`n- OS: $([System.Environment]::OSVersion)"
```
And during recall you can see it:
```
40:93ms> "- posh-git version/path: $($m = Get-Module posh-git; '{0} {1} {2}' -f $m.Version,$m.PrivateData.PSData.PreRele
aseVersion,$m.ModuleBase.Replace($HOME,'~'))`n- PowerShell version: $($PSVersionTable.PSVersion)`n- $(
>> git --version)`n- OS: $([System.Environment]::OSVersion)"
bck-i-search: $m_
```
This isn't a serious bug I don't think.  Well, at least in this case the recalled string still evaluates correctly.

**Comment by lzybkr** [comment]
Can you simplify or explain it better? I can't quite figure out what's wrong.

**Comment by rkeithhill** [comment]
Copy & paste the first string into PowerShell.  Note that it is a single line at this point.  Execute the line, then recall the command using `Ctrl+R` and notice that the command is now a multiline command.

**Comment by lzybkr** [comment]
Yeah, I tried that, copying it and pasting into both notepad and PSReadline - it was two lines.
I then removed the newline that turned it into 2 lines, assuming that was what you meant.

**Comment by rkeithhill** [comment]
Doh!  You're right.  That was supposed to be a single line but I guess since it is so long either VSCode or GitHub split it two lines.
