### ISSUE TITLE
Powershell bug?

### ISSUE THREAD

**Issue by theovlad** [PowerShell/PSReadLine#520]
IDK how this is done so I will try the most logical approach in my point of view.

Running:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.10586 N/A Build 10586

Scenario:

1. right-click on PS icon and run as Admin
2. run the command:
PS C:\WINDOWS\system32> runas /noprofile /user:user1 powershell
Enter the password for user1:
3. New PS window opens with title PS (running as user1)
4. In the new PS window I run the command <whoami>
Output is as follows:
===============================
PS C:\WINDOWS\system32> whoami

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 34 Keys:
 Enter
 Enter
 w h o a m i Enter
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace
Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace B
ackspace Backspace Backspace Backspace Backspace UpArrow Enter

Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Users\Default\AppData\Roaming\Mi
crosoft\Windows\PowerShell\PSReadline' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirS
ecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func
`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits,
 Int32 undoEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics e
ngineIntrinsics)
-----------------------------------------------------------------------
PS C:\WINDOWS\system32> whoami
===============================

tried <exit>

===============================
PS C:\WINDOWS\system32> exit

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 51 Keys:
 Enter
 Enter
 w h o a m i Enter
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace
 Backspace Backspace Backspace UpArrow Enter
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace
 Backspace Backspace e x i t Enter

Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Users\Default\AppData\Roaming\Microsoft\W
indows\PowerShell\PSReadline' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityOb
j, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOp
ener)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 un
doEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntr
insics)
-----------------------------------------------------------------------
PS C:\WINDOWS\system32> exit
===============================
Closed both PS windows

Replicated step by step.
All worked ok.
Unable to replicate issue.

**Comment by rkeithhill** [comment]
One problem you have here is that Windows is using the Default profile when you log in as evidenced by the path `'C:\Users\Default\...`.  PSReadLine doesn't have modify privileges to that location.  This issue seems to crop up with Windows where when you log in, Windows doesn't use your profile it uses a temp profile and apparently sometimes the Default profile.  Here's a [case where someone was getting the Default profile loaded when they logged in on Windows 7](http://www.landviser.net/content/how-fix-windows-7-loads-default-instead-user-modified-profile-wiping-all-settings-files).

**Comment by theovlad** [comment]
Thank you for the fast reply.
Since it worked the second time I tried it, I'm not concerned. 
But since the message included a request to open a github issue and I had a moment, I assumed I was helping. This is how much of a noob I am. I won't jump out the window because it sais so in an error message, but I'm trying to help when I can.
Sooooo.... I should probably close this? :) 
Anyway. I'm ok with closing it if anybody is wondering.

**Comment by rkeithhill** [comment]
Thanks for taking the time to file the issue.  Let's let @lzybkr decide whether or not to close.  This seems like a corner case issue but it is one that he "might" want to handle (or not).  :-)

**Comment by lzybkr** [comment]
This looks like #322 which was fixed, so maybe it's an old version of PSReadline?
