### ISSUE TITLE
Question about cursor placement in vi mode

### ISSUE THREAD

**Issue by takhyon** [PowerShell/PSReadLine#530]
When in vi mode, is there a way to place the cursor at the end of the line rather Than the beginning when scrolling through your command history using the up and down arrow keys?

**Comment by lzybkr** [comment]
@srdubya?

IIRC, that's why I added `Set-PSReadlineOption -HistorySearchCursorMovesToEnd` in the first place, but it doesn't work in vi mode.

**Comment by srdubya** [comment]
I don't recall noticing that option.  I'll take a look at it this weekend.

**Comment by srdubya** [comment]
Just submitted a pull request with this addressed.  Setting HistorySearchCursorMovesToEnd will always position the cursor at the end while leaving it off will keep the cursor at the beginning.  Keeping the cursor at the beginning is consistent with how my bash operates.
