### ISSUE TITLE
Feature - Command to access contents of History buffer

### ISSUE THREAD

**Issue by MartyGentillon** [PowerShell/PSReadLine#533]
So, I can see the history for the current powershell session with the `Get-History` commandlet, however, there is no way to see the history that PSReadline has read in from its history file.  It would be nice if either `Get-History` could be updated to include the contents of my PSReadline history file, or add a new command to access the PSReadline history queue (`Get-PSReadlineHistory` or some such).

**Comment by kelleyma49** [comment]
I would use this for my [Invoke-FuzzyHistory](https://github.com/kelleyma49/PSFzf/blob/master/docs/Invoke-FuzzyHistory.md) command.  Right now Invoke-FuzzyHistory reads directly from beginning of the the history file.  If I had the ability to read directly from PSReadLine, it would be trivial to start reading history backwards.

**Comment by lzybkr** [comment]
New api added in  b2c0474.
