### ISSUE TITLE
Cannot bind sequence of single characters to -Chord

### ISSUE THREAD

**Issue by lbergnehr** [PowerShell/PSReadLine#539]
Environment data
----------------

PS version: 5.1.14393.1198
PSReadline version: 1.2
os: 10.0.14393.0 (rs1_release.160715-1616)
PS file version: 10.0.14393.0 (rs1_release.160715-1616)

Steps to reproduce or exception report
--------------------------------------

I'm trying create this binding:

```powershell
Set-PSReadlineKeyHandler -Chord "j,k" -Function ViCommandMode
```

The binding succeeds, however, it appears it's bound to just `k`, not `j` and `k` in sequence. That is, just hitting `k` when in insert mode will exit to command mode.

**Comment by daxian-dbw** [comment]
It seems this has been fixed, only that you cannot type `j` in insert mode anymore (which may be a different issue).
