### ISSUE TITLE
ScrollDisplayUp throws on PgUp/PgDn

### ISSUE THREAD

**Issue by rovinbhandari** [PowerShell/PSReadLine#551]
Environment data
----------------
PS version: 5.1.15063.502
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
Hitting PageUp or PageDown keys resulted in an exception.
I could reproduce it in the same PowerShell window as it happened, but couldn't reproduce in a new window.
I did not resize or scroll with the mouse when the failure happened. Here is the output from PSReadLine when it threw:

Last 200 Keys:
```
 7 5 5 Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace C Enter
 g i t Spacebar s t a t u s Enter
 g i t Spacebar c o m m i t Spacebar - m Spacebar " " LeftArrow f i x Spacebar t e s t RightArrow Spacebar - a Enter
 g i t Spacebar p u s h Enter
 UpArrow UpArrow Escape Escape Escape Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Ctrl+c Ctrl+c Ctrl+c DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 g i t Spacebar s t a t u s Enter
 g i t Spacebar s t a t u s Enter
 g i t Spacebar d i f f Enter
 g i t Spacebar c o m m i t Spacebar - m Spacebar " " PageUp
```

```
Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by lzybkr** [comment]
I've reviewed PSReadLine and the .Net api that is used and this seems like an impossible condition. The .Net api `Console.SetWindowsPosition` validates the parameters before calling the Win32 api, yet it's the Win32 api reporting the error.

As this was not reproducible, I'll chalk this up to some random corruption in conhost - it wouldn't be the first transient error like this that I've seen.

Sorry I can't do anything about it, but thanks for reporting it.

**Comment by daxian-dbw** [comment]
Additional information:

`Console.SetWindowPosition(int left, int top)` calls to `ConsolePal.SetWindowPosition(left, top)`, which does the [argument validations](https://github.com/dotnet/runtime/blob/0b25063ec056b0d6668bf0848d108d8c873f3fce/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L941-L947) before calling into the Win32 API `Interop.Kernel32.SetConsoleWindowInfo`:

            // Check for arithmetic underflows & overflows.
            int newRight = left + srWindow.Right - srWindow.Left + 1;
            if (left < 0 || newRight > csbi.dwSize.X || newRight < 0)
                throw new ArgumentOutOfRangeException(nameof(left), left, SR.ArgumentOutOfRange_ConsoleWindowPos);
            int newBottom = top + srWindow.Bottom - srWindow.Top + 1;
            if (top < 0 || newBottom > csbi.dwSize.Y || newBottom < 0)
                throw new ArgumentOutOfRangeException(nameof(top), top, SR.ArgumentOutOfRange_ConsoleWindowPos);

Opened .NET Core issue: https://github.com/dotnet/runtime/issues/31949
