### ISSUE TITLE
VIM command mode crashes on empty line when `w` is pressed

### ISSUE THREAD

**Issue by twsouthwick** [PowerShell/PSReadLine#552]
Environment data
----------------

PS version: 5.1.15063.483
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------

- Enable VIM mode
- Enter command mode
- Press `[Enter]` to get to a new line
- While still in command mode, press `w`

### Stacktrace:

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 2 Keys:
 Escape w

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToCoordinates(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ViNextWord(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by srdubya** [comment]
The steps you outlined don't match the behavior of the shell.  As soon as you press `[Enter]` the shell will revert back to input-mode on a new line, so pressing `w` will simply display a "w".  I've tried a few other combinations, but have been unable to reproduce the exception.  What I've tried:

- [Escape] [Enter]w
- [Escape] [Shift-Enter]w
- [Escape] [Enter] [Escape]w

I'm not sure I'm on the same version of PS, PSReadline, etc. though.  I'll play around with this some more this weekend.  If you have time, please double check the sequence of keystrokes that cause the error.  Perhaps between the two of us we can figure out what's going on.

**Comment by twsouthwick** [comment]
Hmm... I can reproduce with no issue. Here's an image:

![vim-repro](https://user-images.githubusercontent.com/583206/29479339-65757486-8426-11e7-9ffa-561c2ae5969f.gif)

I can capture any other debug traces if needed.

**Comment by srdubya** [comment]
Does the problem occur if you never press `[Enter]`?  That is, you:

1. Start a new shell
2. Press `[Escape]` `w`

**Comment by srdubya** [comment]
I had the occasion to bring up a new machine at work.  Upon firing up PSReadLine with my favorite options (like Vi mode), I encountered the error identified here.  I then cloned the current lzybkr/PSReadLine repo, built it, and switched to it.  "Eureka", no more error.

It appears that the version of PSReadLine available with the OS is a bit out of date on the latest fixes.

BTW, for me there was no need to precede `[Escape]` `w `with `[Enter]` to see the error.

**Comment by lzybkr** [comment]
There are a few vi mode fixes post v1.2, so we'll assume it was fixed.

I'm working on an update with some cool new features and making the module portable (single binary) that works on Windows and in PowerShell Core - all platforms. No promises on when it's ready (this is still just a side project for me), but I'm making good progress.

**Comment by gwojan** [comment]
@izybkr, Any chance the module will be available in the PowerShell Gallery?

**Comment by lzybkr** [comment]
@gwojan  - v1.2 is in the gallery right now - it should be the same as what ships with Windows 10.

I'll publish v2.0 to the gallery when it's ready - early adopters can built it themselves for now - build the branch ansi_render to get the latest.

**Comment by twsouthwick** [comment]
Sounds good. I cloned and built the repo, but couldn't skip loading the built-in 1.2 version. I tried `powershell -noprofile` from `cmd` to no avail.

**Comment by lzybkr** [comment]
Where did you install it?

I think if you put the module in `~\WindowsPowerShell\Modules\PSReadline\1.2`, it should override the one in  `c:\Program Files\WindowsPowerShell\Modules`.

**Comment by twsouthwick** [comment]
Ah - I didn't try "installing it". I was hoping to just to `Import-Module` from a vanilla powershell
