### ISSUE TITLE
How to set the prompt after `-Verbose` output in a PSReadlineKeyHandler 

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PSReadLine#557]
I'm doing a `Copy-Item -Verbose`, the output displays in the console, but when complete, the prompt doesn't position correctly. How do I handle outputting multiple lines to console? Tried `"x"|out-host; []::AcceptLine()` but it did not work.

**Comment by lzybkr** [comment]
Try calling `[Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()`
