### ISSUE TITLE
Suggestion: Add a HistoryNoDuplicates variant that only elides contiguous duplicates

### ISSUE THREAD

**Issue by DHowett-MSFT** [PowerShell/PSReadLine#562]
Environment data
----------------

```powershell
PS version: 5.1.17019.1000
PSReadline version: 1.2
os: 10.0.17019.1000 (WinBuild.160101.0800)
PS file version: 10.0.17019.1000 (WinBuild.160101.0800)
```

Background
--------------------------------------

ZSH offers an option, `HIST_IGNORE_ALL_DUPS`, that operates like PSReadline's `-HistoryNoDuplicates` -- If a command appears anywhere in the session's history, and it is run again, the original instance is removed.

ZSH also offers `HIST_IGNORE_DUPS`, which is the default. It'll only ignore duplicates if they happen in immediate succession.

Suggestion
--------------------------------------

PSReadline could offer a `-HistoryNoDuplicates` variant that operates like zsh's `HIST_IGNORE_DUPS`. Right now, it appears to operate in the manner of `HIST_IGNORE_ALL_DUPS`.

**Comment by lzybkr** [comment]
I'm not sure I'd add an option for this (too many options is not necessarily a good thing).

That said, it might make sense to do this all the time (no option to turn it off.)
