### ISSUE TITLE
HelpInfoUri needs update

### ISSUE THREAD

**Issue by CarnegieJ** [PowerShell/PSReadLine#566]
Environment data
----------------
PS version: 5.1.17017.1000
PSReadline version: 1.2
os: 10.0.17017.1000 (WinBuild.160101.0800)
PS file version: 10.0.17017.1000 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
N/A

The HelpInfoUri is currently, https://go.microsoft.com/fwlink/?LinkId=528806  which redirects to http://download.microsoft.com/download/9/9/7/997F596F-E96D-46F1-89B2-B085A9132401/  which returns 404.

**Comment by lzybkr** [comment]
The latest doesn't have the URI anymore, and the first one I tested works.

**Comment by lzybkr** [comment]
I'll have an official prerelease build out next week if you want to verify this is fixed, otherwise you can grab a build out of appveyor [here](https://ci.appveyor.com/project/lzybkr/psreadline).

**Comment by ghost** [comment]
This issue needs to be reopened, as the issue is not fixed, and the link to the appveyor project is broken.

**Comment by daxian-dbw** [comment]
@tboring-hss-sbcounty-gov, if you mean the current uri `https://aka.ms/powershell71-help` cannot be accessed directly from browser, then that's by design. That uri forwards to `https://pshelpprod.blob.core.windows.net/cabinets/powershell-7.1/`, and from there, the powershell help system adds the module GUID and file name to form the full URL. `Update-Help -Module PSReadLine` works in this way.

**Comment by ghost** [comment]
> 
> 
> @tboring-hss-sbcounty-gov, if you mean the current uri `https://aka.ms/powershell71-help` cannot be accessed directly from browser, then that's by design. That uri forwards to `https://pshelpprod.blob.core.windows.net/cabinets/powershell-7.1/`, and from there, the powershell help system adds the module GUID and file name to form the full URL. `Update-Help -Module PSReadLine` works in this way.

Nope. Not what I meant at all.

This ticket is about receiving the error in a Powershell 5.1 environment. Judging by your comment, you must be in a Powershell 7.1 environment. It's okay, and expected, that 5.1 and 7.1 use different URLs...but the URL (https://go.microsoft.com/fwlink/?LinkId=528806 that currently redirects to https://pshelpprod.blob.core.windows.net/cabinets/powershell-5.1/) for 5.1 in still broken. Hence, this ticket should be reopened.
