### ISSUE TITLE
Set-PSReadlineOption : The handle is invalid.

### ISSUE THREAD

**Issue by joeminicucci** [PowerShell/PSReadLine#577]
Environment data
----------------

PS version: 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  1770    

PSReadline version: 
Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      -1     -1      

Windows 8 x64

Steps to reproduce or exception report
--------------------------------------
This occurs in ISE and not vanilla powershell:

PS C:\WINDOWS\system32> Import-Module psreadline

PS C:\WINDOWS\system32> Set-PSReadlineOption -EditMode vi
Set-PSReadlineOption : The handle is invalid.
At line:1 char:1
Set-PSReadlineOption -EditMode vi
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : NotSpecified: (:) [Set-PSReadlineOption], IOException
    FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.SetPSReadlineOption

**Comment by lzybkr** [comment]
PSReadLine is not supported in the ISE.

Once there was an entry in the `psd1` restricting PSReadLine to the console host, but I had a request to remove that for another console like host, so the nice error message is no longer there.

The [readme](https://github.com/lzybkr/PSReadLine#post-installation) suggests checking the host in your profile, you should do the same when calling `Set-PSReadLineOption`.
