### ISSUE TITLE
Command line does not render properly after executing git commands with PSReadline 2.0

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#582]
PSReadline doesn't render ANSI escape sequences properly resulting in a unusable commnand line experience after executing git commands or the git bash shell.

![image](https://user-images.githubusercontent.com/6855215/32794136-ff530222-c935-11e7-8654-b6f16a7cac43.png)

Environment data
----------------
PS version: 5.1.15063.674
PSReadline version: 2.0
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------

- Open PowerShell with PSReadline 2.0
- Navigate to directory under git version control
- Execute a git command, ie ```git log -1```
- Begin to type anything else...

This behavior appears if you invoke git bash or any other Cygwin based shell from within PowerShell. Once returned to the parent shell raw escape sequences are rendered on the command line as you type.

**Comment by lzybkr** [comment]
Oh, this is a PowerShell bug that I've worked around in my prompt but forgotten that I did that.
I'll have to add the workaround to PSReadLine.

My workaround is to add this to my prompt:

```
    Set-ConsoleMode -ANSI
```

And this command comes from this [gist](https://gist.github.com/lzybkr/f2059cb2ee8d0c13c65ab933b75e998c).

**Comment by gwojan** [comment]
@lzybkr Sweet! That helps a lot! 😀 

Do you want me to close or leave this open for tracking purposes?

**Comment by lzybkr** [comment]
I need to leave it open so I don't forget to fix it.

**Comment by lzybkr** [comment]
BTW, this is also fixed in Windows PowerShell in the Fall Creators Update, but I'll still make a change to PSReadLine for folks who can't upgrade.
