### ISSUE TITLE
MissingMethodException: PSEventManager.get_Subscribers() in InputLoop

### ISSUE THREAD

**Issue by SmirnovArsenty** [PowerShell/PSReadLine#585]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
```
An exception:
System.MissingMethodException: Method not found: 
"System.Collections.Generic.List`1<System.Management.Automation.PSEventSubscriber>
      System.Management.Automation.PSEventManager.get_Subscribers()".

Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by lzybkr** [comment]
I'll need more information to reproduce the problem.

The error is coming from a loop that is running literally all the time while PowerShell is idle - I think it's conservative to say it's hit 1 billion times a day across all PowerShell users.

**Comment by lzybkr** [comment]
Closing - no additional information to reproduce at it seems impossible, or more likely only reproduces with a private build of PowerShell.
