### ISSUE TITLE
No completions given on two tab key presses

### ISSUE THREAD

**Issue by drvink** [PowerShell/PSReadLine#586]
Environment data
----------------
PS version: 6.0.0-beta.9
PSReadline version: 2.0
os: Linux arch-vm 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux
PS file version: (blank)

(This is the latest tagged beta release of PowerShell with PSReadLine master as of 46eb22f merged.)

Steps to reproduce or exception report
--------------------------------------
Try `$PSVersionTable.`, then hit tab twice. Nothing appears, but you should get completion candidates.

**Comment by lzybkr** [comment]
Thanks for the report - I was doing a demo a couple days ago and hit this bug but didn't realize what was going on.
