### ISSUE TITLE
PowerShell Gallery does not include latest PSReadLine

### ISSUE THREAD

**Issue by dougbu** [PowerShell/PSReadLine#587]
Environment data
----------------
PS version: 5.1.16299.19
PSReadline version: 1.2
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 10.0.16299.15 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
1. Head to https://www.powershellgallery.com/
2. Search for PSReadLine

or
1. Head to https://www.powershellgallery.com/packages/PSReadLine/

### Expected
Land on download page for PSReadLine 2.0 e.g. https://www.powershellgallery.com/packages/PSReadline/2.0
### Actual
Still land on download page for PSReadLine 1.2: https://www.powershellgallery.com/packages/PSReadline/1.2
https://www.powershellgallery.com/packages/PSReadline/2.0 page does not exist.

**Comment by lzybkr** [comment]
I think 2.0 needs more testing before it's rock solid, so the plan is to release it as a prerelease on the galllery. I'm waiting on this [PR}(https://github.com/PowerShell/PowerShellGet/pull/185) before I make that release though.

**Comment by lzybkr** [comment]
It's on the gallery now - [here](https://www.powershellgallery.com/packages/PSReadline/2.0.0-beta1)

Installing requires PowerShellGet 1.6.0 which has not been officially released just yet, but should be soon.
