### ISSUE TITLE
Alt shortcuts on macOS don't work - iTerm2

### ISSUE THREAD

**Issue by parkovski** [PowerShell/PSReadLine#594]
Because alt is "option", which as far as I'm aware doesn't have a `ConsoleKey` value. Most sequences emit a double escape for option - the ones with numeric modifiers use a 9 and higher numbers when combined with control or shift.
ex. Option+A - `^[^[A`, Home - `^[1H`, Option+Home - `^[1;9H`

It doesn't look like Terminal.app supports Option shortcuts at all, and they're not parsed correctly by .NET.

**Comment by lzybkr** [comment]
I don't have access to a Mac, so it's up to the community to fix this.

**Comment by parkovski** [comment]
Looks like there's an iTerm option to enable normal alt sequences under Preferences->Profiles->Keys. Not sure where the non-standard ones come from, but if anyone else comes across this, you have to change the option key mode to 'Esc+', and change the custom key bindings that say `Send Hex Codes: 0x1b 0x1b ...`.
Standard escapes for arrow keys are:
- Alt+Up: `^[[1;3A` (use the Send Escape Sequence action, type `[1;3A` in the Esc+ box)
- Alt+Down: `^[[1;3B`
- Alt+Right: `^[[1;3C`
- Alt+Left: `^[[1;3D`
