### ISSUE TITLE
Latest AppVeyor release (v1.0.246) has issues piping cmdlet output to less/vim/gvim.

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#601]
I am not able to pipe the output of ```Get-ChildItem``` to a Win32 native port of ```less.exe | gvim.exe | vim.exe```.

Environment data
----------------
PS version: 6.1.0-preview.503
PSReadline version: 2.0
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 6.1.0```

Steps to reproduce or exception report
--------------------------------------
```powershell
Get-ChildItem 'C:\Program Files\dotnet\' -Recurse | less
Get-ChildItem 'C:\Program Files\dotnet\' -Recurse | gvim -
Get-ChildItem 'C:\Program Files\dotnet\' -Recurse | vim -
```
The first command piping to ```less``` works almost normally but when exiting ```less``` hangs for about 10 seconds before returning to the shell unless I hit ```Ctrl+C```.

The second command opens ```gvim``` with the following:
![image](https://user-images.githubusercontent.com/6855215/33568264-e99a3e1e-d8f3-11e7-8469-6061446bb301.png)
then renders the content after about 10-15 seconds. Closing ```gvim``` returns immediately to PowerShell with no delay.

The third command behaves similarly to the second command -- it's just opening ```vim``` inside the PowerShell frame.

Under Windows PowerShell 5.1 behavior is almost identical to the PowerShell Core results except for piping to ```less``` pauses for about 10 seconds before rendering the content.

Native commands like ```cmd /c dir /s | less``` appear to work correctly.

**Comment by bgshacklett** [comment]
This doesn't seem like a PSReadline issue. Can you repro after removing the module?

```
PS>rmo psreadline       
PS>Get-Module psreadline
PS>Get-ChildItem | less 
```
