### ISSUE TITLE
PSReadLine 2.0 Vi mode visual editing with vim doesn't work

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#603]
I can't edit a command line in ```vim``` with PSReadLine 2.0. This worked fine in previous versions so I think it might have something to do with the change in output encoding.

Environment data
----------------
PS version: 6.1.0-preview.503
PSReadline version: 2.0
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 6.1.0

Steps to reproduce or exception report
--------------------------------------
* set ```$env:VISUAL = 'vim.exe'```
* type command to edit
* press ```ESC```
* press ```v```

result:
![image](https://user-images.githubusercontent.com/6855215/33570795-015ae938-d8fc-11e7-872f-254cd881ea4b.png)

* press ```ZQ``` to exit vim and the previous screen is cleared.

If I change ```$env:VISUAL = 'gvim.exe'``` everything is fine since gvim opens out of process.

Behavior is the same with PSReadLine under Windows PowerShell 5.1...

**Comment by lzybkr** [comment]
Unfortunately it works fine for me so it will be harder for me to diagnose. I specifically tested `vim.exe` when I made the change.

If you want to test your encoding theory (which is a good theory), you would make the change [here](https://github.com/lzybkr/PSReadLine/blob/c1c03cf1cf3ef7440e4e28affafb675ae085b99c/PSReadLine/PlatformWindows.cs#L230).

**Comment by bgshacklett** [comment]
I'm unable to repro as well. ~, but I'm on an insider release the latest stable release of Windows. 15063 is quite old, and there have been some improvements made to ConHost in the recent flights. Do you have access to a newer Windows release to see if you can still reproduce the problem?~

edit: Apparently, the first Google hit didn't give me very good information. I didn't realize 15063 was equivalent to version 1703. Also, I did just find that GVim does not load any text in the buffer if I switch `$env:VISUAL` to `gvim.exe` and attempt a visual edit.

**Comment by gwojan** [comment]
@lzybkr, @bgshacklett It's clearly a v2.0 thing for me. If I revert back to back to v1.2 ```<esc>v``` works just fine on all the machines (Windows 10 and WS2012R2).

The weird thing is if I just execute ```vim``` from Windows PowerShell 5.1 or PowerShell-6.0.0-rc ```vim``` loads into the shell window as I expect. If I attempt to run ```vim``` from the **PowerShell 6 daily build** I get the same results as ```<esc>v```.

**Comment by lzybkr** [comment]
So you're saying it's not PSReadLine, it's PowerShell daily builds?

I just tried the very latest (built myself) and still can't repro, either via PSReadLine or just running it directly.

I am running Fall Creators update, but guessing it doesn't matter. I'm also running vim 8.0, but also guessing that shouldn't matter.

**Comment by gwojan** [comment]
_So you're saying it's not PSReadLine, it's PowerShell daily builds?_

No, I definitely think it's PSReadLine. If I revert back to PSReadLine 1.2 everything works as I expect in all three versions of PowerShell.

I'll do some more testing tonight on my laptop with the Fall Creator's Update to see if that makes a difference.

**Comment by gwojan** [comment]
BTW, this image is from a WS2012R2 server, PowerShell 5.1, PSReadLine 2.0:

![image](https://user-images.githubusercontent.com/6855215/33621437-c309c4e8-d9b8-11e7-83c6-cc22a3fe0068.png)

PS version: 5.1.14394.1000
PSReadline version: 2.0
os: 6.3.9600.16384 (winblue_rtm.130821-1623)
PS file version: 10.0.14394.1000 (rs1_srvoob.160718-1700)

**Comment by bgshacklett** [comment]
@gwojan Can you try this without loading your PowerShell Profile and see if you can still reproduce it?
```
> pwsh.exe -NoProfile
> Import-Module PSReadLine
> ...
```

Also, do you have any non-default environment variables set at the OS layer?

**Comment by gwojan** [comment]
@bgshacklett Starting PowerShell with ```-NoProfile``` doesn't do any good. Ever since PowerShell 5.0 PSReadLine is loaded by default... Perhaps @lzybkr can explain the rational for that.

This little fact, has burned me more than a few times. ☹️

**Comment by lzybkr** [comment]
PSReadLine is not loaded if you run a command and don't specify `-NoExit`, so e.g. `powershell -noprofile -command 'vim.exe'`

The rationale was that if it's good enough to be installed by default, it should be used by default.

**Comment by gwojan** [comment]
_PSReadLine is not loaded if you run a command and don't specify -NoExit, so e.g. powershell -noprofile -command 'vim.exe'_

Interesting... What about the ```-file``` parameter?

Also, what about the trick of putting your PowerShell script in a batch file and piping/redirecting the script to PowerShell? For example:

```
@findstr/v "^@findstr.*&" "%~f0"|powershell -ExecutionPolicy Bypass -NoProfile -&goto:eof
<# PowerShell script goes here #>
.
.
.
# EOF
```

**Comment by lzybkr** [comment]
There are a number of checks done before loading PSReadLine with the intent of not loading it if the session is not interactive. It's possible some scenario was missed, but I think your scenarios are covered.

**Comment by gwojan** [comment]
Awesome! Thanks for the information. Do the checks for an interactive session only apply to PSReadLine 2.0 or earlier versions as well?

I will do some more testing with wrapping PowerShell in a batch file with PSReadLine 2.0 because I had to ```Remove-Module PSReadLine``` in my previous attempts where PSReadLine 1.2 was installed.

**Comment by lzybkr** [comment]
The interactive checks are in PowerShell, not PSReadLine, and IIRC, the checks haven't changed since being introduced in V5.0.

**Comment by gwojan** [comment]
I verified last night that I could not reproduce my original issue on Windows 10 Fall Creator's Update. Where do we go from here?

**Comment by lzybkr** [comment]
Try:

```
$env:VISUAL = "vim -T dumb"
#or
$env:VISUAL = "vim -T win32"
```

One of those should turn of generating escape sequences.

Alternatively, you can use this [module](https://gist.github.com/lzybkr/f2059cb2ee8d0c13c65ab933b75e998c), run `Set-ConsoleMode -ANSI` somewhere, e.g. in your prompt. If this fixes the problem, I think that explains the difference b/w Creator's Update and Fall Creator's Update - I think there was a bug fix in Windows PowerShell to keep the console mode enable virtual terminal processing on after running external applications.

**Comment by gwojan** [comment]
@lzybkr Adding VIM switches to ```$env:VISUAL``` breaks ```ViEditVisually``` functionality do to the way the command is validated. I'll see if I can fix that.

In the mean time, I created a batch file ```@vim.exe -T win32 %*``` which is called instead. Using ```win32``` has no effect. ```dumb``` actually works but all the VT sequences are written to the console as well:

![image](https://user-images.githubusercontent.com/6855215/33684259-a4925690-da9b-11e7-82a2-e41affcfef34.png)

As far as ```Set-ConsoleMode```, I've been using that since you published the Gist for me -- it has no effect.

**Comment by gwojan** [comment]
I'm closing this issue. It's long been resolved and I must've forgotten to close it then. 😦
