### ISSUE TITLE
PS Core 6.0 RC2 issue with 2.0.0 version not being catalog signed

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#612]
Environment data
----------------
```
PS version: 6.0.0-rc.2
PSReadline version: 1.2 - but I'm trying to get to 2.0
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 6.0.0
```

Steps to reproduce or exception report
--------------------------------------
Install PS Core 6.0 rc2 and execute:
```posh
PS C:\Program Files\PowerShell\6.0.0-rc.2> Install-Module psreadline -RequiredVersion 2.0.0-beta1 -AllowPrerelease -Scope CurrentUser
```
This is what I get:
```
PackageManagement\Install-Package : The version '2.0.0' of the module 'PSReadLine' being installed is not catalog signed. Ensure that the version '2.0.0' of the module 'PSReadLine' has the catalog file 'PSReadLine.cat' and signed with the same publisher 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module 'PSReadLine' with version '1.2' under the directory 'C:\program files\powershell\6.0.0-rc.2\Modules\PSReadLine'. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\program files\powershell\6.0.0-rc.2\Modules\PowerShellGet\1.6.0\PSModule.psm1:2057 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
I should probably mention there is a simple workaround, use `-SkipPublisherCheck` but still, we shouldn't need a workaround.

**Comment by vr8hub** [comment]
I ran into this today as well. If you're not going to fix this (until release?), you might at least update the instructions on PowerShell Gallery to include the -SkipPublisherCheck (those instructions also need -Force).

**Comment by lzybkr** [comment]
@vr8hub - The PowerShell Gallery provides the installation instructions, I could only put a note somewhere, like in the release notes.

You could make suggest the gallery do that automatically for modules that do not include the catalog signature - I think this is the right [repo](https://github.com/PowerShell/PowerShellGet/issues) to do that.

**Comment by mikemaccana** [comment]
Weird it doesn't seem to install even when skipping the publisher check:

![image](https://user-images.githubusercontent.com/172594/41717048-59f669be-7550-11e8-8eb8-8376e6cf819e.png)

(Same with adding `-Force`)

**Comment by rkeithhill** [comment]
You need to specify the `-AllowPrerelease` parameter since `2.0.0` hasn't been released yet.

**Comment by mikemaccana** [comment]
Ah thanks @rkeithhill that worked perfectly

**Comment by daxian-dbw** [comment]
The 2..0.0-beta4 is catalog signed. Closing this issue.
