### ISSUE TITLE
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PSReadLine#614]
Environment data
----------------
```powershell
& {
    "PS version: $($PSVersionTable.PSVersion)"
    "PSReadline version: $((Get-Module PSReadline).Version)"
    if ($IsLinux -or $IsOSX) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $((dir $pshome\pwsh.exe).VersionInfo.FileVersion)"
}
```
```
PS version: 6.0.0-rc.2
PSReadline version: 2.0.0
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 6.0.0
```
```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0-rc.2}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Steps to reproduce or exception report
--------------------------------------
```powershell
Get-PSReadLineOption
```
```
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineOption
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption
```
```powershell
Get-PSReadLineKeyHandler
```
```
Get-PSReadLineKeyHandler : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineKeyHandler
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineKeyHandler], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetKeyHandlerCommand
```
note : the  issue template dont reference 'pwsh.exe'

**Comment by lzybkr** [comment]
It looks like you built PSReadLine yourself - can you try with beta1 from the PSGallery?

And if that doesn't repro, but it does repro with the latest, do let me know.

I've done minimal testing on Win7 and haven't seen this. I have also done some testing with the "legacy" console on Win10 (from the console properties menu, on the Options tab, select "Use legacy console (requires relaunch)" - that option tends to help behavior specific to pre-Win10 systems.

**Comment by LaurentDardenne** [comment]
_can you try with beta1 from the PSGallery?_
This version comes from PSGallery, via Install-Module.
I can test again on Win7 and on a new VM with Server 2016.

**Comment by lzybkr** [comment]
Thanks - I updated the issue template so the script now reports the prerelease version properly and also checks pwsh.exe.

**Comment by LaurentDardenne** [comment]
Same error on Windows 7 (via Install-Module)

Same error on Windows Server 2016 :
New Azure VM : _Windows Server 2016 Datacenter - with Containers_

Install PowerShell-6.0.0-win-x64.msi

```Powershell
PS C:\Program Files\PowerShell\6.0.0> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Program Files\PowerShell\6.0.0> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemPropert...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...


PS C:\Program Files\PowerShell\6.0.0> install-module psreadline -verbose -force -SkipPublisherCheck  -AllowPrerelease
...
VERBOSE: InstallPackageLocal' - name='PSReadLine', version='2.0.0-beta1',destination='C:\Users\Laurent\AppData\Local\Temp\2\1222363818'
VERBOSE: Skipping the Publisher check for the version '2.0.0' of module 'PSReadLine'.
VERBOSE: Module 'PSReadLine' was installed successfully to path 'C:\Program Files\PowerShell\Modules\PSReadLine\2.0.0'.

#Close pwsh.exe
#run pwsh.exe 
PS C:\Program Files\PowerShell\6.0.0> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


PS C:\Program Files\PowerShell\6.0.0> dir 'C:\Program Files\PowerShell\Modules\PSReadLine\2.0.0'


    Directory: C:\Program Files\PowerShell\Modules\PSReadLine\2.0.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/17/2018  11:27 AM                en-US
-a----        12/5/2017  11:22 PM          14164 Changes.txt
-a----        12/5/2017  11:22 PM           1322 License.txt
-a----        12/5/2017  11:22 PM         249856 Microsoft.PowerShell.PSReadLine2.dll
-a----        12/5/2017  11:22 PM           8770 PSReadLine.format.ps1xml
-a----        12/5/2017  11:22 PM            869 PSReadLine.psd1
-a----        12/5/2017  11:22 PM            180 PSReadLine.psm1
-a----        12/5/2017  11:22 PM          21379 SamplePSReadLineProfile.ps1
-a----        12/5/2017  11:22 PM          33256 System.Runtime.InteropServices.RuntimeInformation.dll

PS C:\Program Files\PowerShell\6.0.0> Get-PSReadLineOption
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineOption
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption
```

**Comment by tobiasdiez** [comment]
I've the same issue after a upgrade of Windows 10 (insider preview). I'm not aware that I've installed PSReadLine so I think that it comes bundled with Win 10 (in fact, I cannot remove it via Remove/Uninstall-Module)

````
 Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.17744
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

PSReadLine version: 2.0.0

**Comment by KurtDeGreeff** [comment]
I have the same issue here on Windows 7 with latest Powershell 6.1 installed :

**Comment by KurtDeGreeff** [comment]
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineOption
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption

**Comment by RobertSpir** [comment]
Same thing happens in latest win10 1809 insider build (build 17763.1) which will likely be the RTM build, any of the PSReadline commands throws an exception making it entirely useless

PS version: 5.1.17763.1
PSReadline version: 2.0.0-beta2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)

```
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineOption
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption
```

**Comment by lzybkr** [comment]
@RobertSpir - I'll need some help tracking this down, I'm always using the latest and never hit this problem.

A memory dump or time trace debug trace would be very helpful if you don't have time to investigate yourself.

**Comment by RobertSpir** [comment]
```
Set-PSDebug -Trace 2; Get-PSReadLineOption
DEBUG:    1+ Set-PSDebug -Trace 2;  >>>> Get-PSReadLineOption
DEBUG:   19+                                         if ( &  >>>> { Set-StrictMode -Version 1; $_.PSMessageDetails } )
{
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:   19+                                         if ( & {  >>>> Set-StrictMode -Version 1; $_.PSMessageDetails } )
{
DEBUG:   19+                                         if ( & { Set-StrictMode -Version 1;  >>>> $_.PSMessageDetails } )
{
DEBUG:    1+ &  >>>> { Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails }
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:    1+ & {  >>>> Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails }
DEBUG:    1+ & { Set-StrictMode -Version 1;  >>>> $this.Exception.InnerException.PSMessageDetails }
DEBUG:    1+ & { Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails  >>>> }
DEBUG:   19+                                         if ( & { Set-StrictMode -Version 1; $_.PSMessageDetails  >>>> } )
{
DEBUG:   26+                                         $errorCategoryMsg = &  >>>> { Set-StrictMode -Version 1;
$_.ErrorCategory_Message }
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:   26+                                         $errorCategoryMsg = & {  >>>> Set-StrictMode -Version 1;
$_.ErrorCategory_Message }
DEBUG:   26+                                         $errorCategoryMsg = & { Set-StrictMode -Version 1;  >>>>
$_.ErrorCategory_Message }
DEBUG:   26+                                         $errorCategoryMsg = & { Set-StrictMode -Version 1;
$_.ErrorCategory_Message  >>>> }
DEBUG:   42+                                         $originInfo = &  >>>> { Set-StrictMode -Version 1; $_.OriginInfo
}
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:   42+                                         $originInfo = & {  >>>> Set-StrictMode -Version 1; $_.OriginInfo
}
DEBUG:   42+                                         $originInfo = & { Set-StrictMode -Version 1;  >>>> $_.OriginInfo
}
DEBUG:   42+                                         $originInfo = & { Set-StrictMode -Version 1; $_.OriginInfo  >>>>
}
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:23
+ Set-PSDebug -Trace 2; Get-PSReadLineOption
+                       ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption
```
this happens on all three machines that are upgraded to 17763

**Comment by RobertSpir** [comment]
downgrading to 1.2 fixed this issue

**Comment by lzybkr** [comment]
Unfortunately the PowerShell debug trace isn't useful because PSReadLine is written in C#.

Ideally I could get a [TTD trace](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview), but I could probably also debug from a [memory dump](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-dump--create-dump-file-).

Note that if you can provide either - they both could contain secrets, e.g. all of your environment variables. Also note that either method will produce very large files, probably too large to email. If you can collect either the `.run` file form TTD or the `.dmp` file from `.dump`, then I can set up a secure location to share the file - you can email me or PM on twitter, whatever works for you.

**Comment by copdips** [comment]
I had exactly the same issue very recently since the release of pwsh 6.1.0.

I fixed the issue by installing a new pwsh with the same version but in another folder. I installed the zip one: [PowerShell-6.1.0-win-x64.zip](https://github.com/PowerShell/PowerShell/releases/download/v6.1.0/PowerShell-6.1.0-win-x64.zip), and launched it, no more PsReadline issue.
Then I closed the new one, and launched the old one (the same version but in another folder), no more issue.

I'm on Windows 10 v10.0.17134.285.

**Comment by copdips** [comment]
@lzybkr,

Thx for your tips, when I'm on french layout, I have the issue. I switch the keyboard layout to english, no more issue.

**Comment by lzybkr** [comment]
Thanks.

You can trying switching back to your preferred layout after PSReadLine is initialized, but there are known issues with switching after the process has started. One of those issues *might* be fixable withing PSReadLine, but there @powercode found that a Win32 api used by PSReadLine also does not work correctly when switching layouts.

So for the time being, installing `1.2` might be the best workaround.

**Comment by SteveL-MSFT** [comment]
The problem seems to be that for some Windows keyboard layouts, the key modifiers are not considered distinct so that when the code [here](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/Keys.cs#L429) tries to add a new key into the dictionary, it already exists which throws an exception.  My proposal for now is to not add keys that already exist.  This doesn't fix the fundamental issue that some key bindings won't work for some keyboard layouts, but they wouldn't work currently anyways.  The temporary fix will resolve the unhandled exception so that errors aren't being generated and `Get-PSReadLineOption` works for different keyboard layouts beyond En-US.

**Comment by RobertSpir** [comment]
Confirming that with this fix applied everything works with slovak keyboard layout

**Comment by eliohann** [comment]
>           Confirming that with this fix applied everything works with slovak keyboard layout

Can you explain how to Apply fix ? can find how to do it …

**Comment by SteveL-MSFT** [comment]
@eliohann you would need a new build of PSReadLine.  There isn't a new beta coming soon, but you can pick up the nightly build which has the fix: https://ci.appveyor.com/project/lzybkr/PSReadLine/branch/master/artifacts

**Comment by Nicolas01** [comment]
@eliohann I installed the [nightly build](https://ci.appveyor.com/project/lzybkr/PSReadLine/branch/master/artifacts) by replacing files in `C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0`
And now it works with my custom keyboard layout !

**Comment by Kralizek** [comment]
Is there a better solution now? I tried to use the artifact from the AppVeyor build but I get 

> Cannot load PSReadline module.  Console is running without PSReadline.

**Comment by lzybkr** [comment]
You could try this [build](https://ci.appveyor.com/project/lzybkr/psreadline/builds/20961423/artifacts) from this [PR](https://github.com/lzybkr/PSReadLine/pull/831).

It's not tested on Linux/Mac yet and I expect I've broken some things there, but I think it fixes all the issues on Windows.

**Comment by LaurentDardenne** [comment]
I have the same error with a new install of Windows 10 Fr (1809).

Installing the specified build no longer causes the exception, but some key combinations no longer work, for example ctrl-space.

```powershell
# Microsoft Windows [version 10.0.17763.253]
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.134}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment]
@LaurentDardenne that is a known issue and being addressed by https://github.com/lzybkr/PSReadLine/pull/831

**Comment by Kralizek** [comment]
Strangely enough, I was able to get the previous version to work by simply renaming the 2.0.0 folder so that it doesn't respect the pattern.

I might be very well be exposed to some error but so far I haven't experienced anything strange.

**Comment by silverqx** [comment]
@RobertSpir How did you downgrade to 1.2? I don't know how to downgrade, I created #860 question when I describe what I tried

**Comment by silverqx** [comment]
Ok, resolved at https://github.com/lzybkr/PSReadLine/issues/860#issuecomment-470163815
