### ISSUE TITLE
Keys that use AltGr in non-US keyboards do not work in 2.0.0-beta1

### ISSUE THREAD

**Issue by barcexwiki** [PowerShell/PSReadLine#617]
Installed 2.0.0-beta1 on pwsh 6.0.0 on Windows 10 and all the characters that make use of the AltGr key on the Spanish keyboard stopped working (@#~€¬[]{}\\|)

Environment data
----------------

```powershell
PS version: 6.0.0
PSReadline version: 2.0.0
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 6.0.0
```

Steps to reproduce or exception report
--------------------------------------
Installed the module with:

Install-Module PSReadLine -AllowPrerelease -Force -AllowClobber -SkipPublisherCheck

All keys with AltGr stop working: @#~€¬[]{}\\|

**Comment by akselkvitberg** [comment]
Same with norwegian keyboard.
AltGr does not work, with the exception of ~ and ´
Norwegian keyboard require AltGr for: @ £ $ € { [ ] } ´ ~ € µ

**Comment by thorstenkampe** [comment]
Can confirm on Windows - although they work on Linux

**Comment by lzybkr** [comment]
Sorry about that folks - forcing myself to use a different keyboard layout until this is fixed :)

**Comment by kimbirkelund** [comment]
Also suffering from this bug.

**Comment by lzybkr** [comment]
Sorry, I push a fix tonight (it's sitting on my computer at home).
I'll try to get a new beta release out soon - there are a couple more fixes that I think are important to fix before another release.

**Comment by flxflx** [comment]
I just installed 6.1.0-preview.1 and the issue still persists. Do you know when the fix will be distributed? Without altgr, PS core is quite unusable on foreign keyboard layouts.

**Comment by lzybkr** [comment]
@flxflx - All releases of PowerShell Core ship with a fork of PSReadLine 1.2, and I thought AltGr works with that release.

I thought I introduced the bug with AltGr in PSReadLine 2.0.0-beta1 - which you may have installed from the PowerShell Gallery.

I have a few more important fixes before releasing another `2.0.0-beta2`, but you can grab a build with the AltGr fix from appveyor [here](https://ci.appveyor.com/project/lzybkr/PSReadLine/build/artifacts).

**Comment by thorstenkampe** [comment]
@lzybkr PowerShell doesn't even start with that build:
```
The shell cannot be started. A failure occurred during initialization:
The static PrimaryRunspace property can only be set once, and has already been set.
```

**Comment by lzybkr** [comment]
@thorstenkampe  - I can't reproduce that error on Windows (with either powershell.exe or pwsh.exe) - but I do need to run `Unblock-File` before the module will load correctly.

Are you running on Linux or Mac?

**Comment by thorstenkampe** [comment]
Unblocking the module directory solved the issue, thanks.

**Comment by flxflx** [comment]
Thanks @lzybkr! I indeed had v2.0 installed.
