### ISSUE TITLE
Please allow F7 to work

### ISSUE THREAD

**Issue by AceHack** [PowerShell/PSReadLine#620]
PSReadline stops F7 from working.  Please allow F7 to continue working.  Thanks.

**Comment by lzybkr** [comment]
Maybe someday, but until then, see this sample that uses `Out-GridView` to get similar functionality: https://github.com/lzybkr/PSReadLine/blob/c3868e125069d87adbc5ee8f0274762a99510957/PSReadLine/SamplePSReadLineProfile.ps1#L23

**Comment by TylerLeonhardt** [comment]
@omniomi's AdvancedHistory module is also a good substitute:
https://github.com/omniomi/AdvancedHistory

**Comment by SteveL-MSFT** [comment]
@TylerLeonhardt perhaps it's time to integrate this with out-consolegridview...

**Comment by daxian-dbw** [comment]
Close this issue as the script for F7 key-binding is provided and a user can customize their profile to enable it.
