### ISSUE TITLE
Implement Text Object Selection in Vi Mode

### ISSUE THREAD

**Issue by bgshacklett** [PowerShell/PSReadLine#622]
I'm a heavy user of motions like `iw`, `aw`, `i(`, `i[` etc. I would find it very useful to have these key bindings implemented in PSReadline's Vi Mode.

**Comment by reaching-for-libra** [comment]
I'd also like to see this enhancement added to the module, but just wanted to add that you can implement it yourself using Set-PSReadlineKeyHandler.

```Set-PSReadlineKeyHandler -Key 'c,i' -BriefDescription ViReplaceInside -LongDescription "Replace Inside" -ViMode Command -ScriptBlock { ... }```

**Comment by springcomp** [comment]
This is a duplicate of #584.

**Comment by bgshacklett** [comment]
Closing as duplicate
