### ISSUE TITLE
Fix vi-mode cf  behavior

### ISSUE THREAD

**Issue by reaching-for-libra** [PowerShell/PSReadLine#623]
When using <cf> to replace text in vi-mode, the cursor is often placed one character to the right of where it should.

`asdf asdf`
`<0>` to go to beginning of line
`<W>` to go to next word
`<cfs>` to remove 'as' and drop into insert mode.
the cursor is now after the 'd' instead of before it.

i think that this happens any time the cursor is not in the first character of the command string when starting the <cf> action.

`PS version: 6.0.0`
`PSReadline version: 2.0.0-beta1`
`os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)`
`PS file version: 6.0.0`

**Comment by srdubya** [comment]
Thanks for submitting this.  I'll take a look soon.

**Comment by reaching-for-libra** [comment]
awesome - i just remembered a similar issue. if you are on the last character of the line in normal mode and you type `<s>`, it will put the cursor before what is now the last character (instead of placing it after)

**Comment by srdubya** [comment]
Pushed a fix to both issues to the srdubya branch and submitted a pull request to lzybkr, but I've been struggling to keep the srdubya branch clean.  We'll see what happens.
