### ISSUE TITLE
fix vi-mode text completion 

### ISSUE THREAD

**Issue by reaching-for-libra** [PowerShell/PSReadLine#624]
text completion, with vi-mode on and Tab key mapped for the complete function, is not always visible after completion in vi-mode.

to reproduce:

```
Set-PSReadLineOption -EditMode vi
Set-PSReadlineKeyHandler -Key Tab  -Function Complete -vimode Insert
PS C:\Program Files\PowerShell\6.0.0> ls .\System.Drawing.*


    Directory: C:\Program Files\PowerShell\6.0.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/22/2017  10:38 AM          14312 System.Drawing.dll
-a----       11/22/2017  10:38 AM          93184 System.Drawing.Primitives.dll


PS C:\Program Files\PowerShell\6.0.0> ls .\System.Drawing.dll


    Directory: C:\Program Files\PowerShell\6.0.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/22/2017  10:38 AM          14312 System.Drawing.dll
```

`<esc>` 
`k` to show previous command
`<$Fd>` to place cursor on the d character
`<C>` to clear out the d and everything after it, and drop into edit mode
`P<tab>` should auto complete the command to `ls .\System.Drawing.Primitives.dll`

the auto completed `Primitives.dll` does not show on the screen, but is there in the buffer.

i get around this by tabbing an extra time or adding a space to force the buffer to refresh, but would love to see this fixed.

**Comment by daxian-dbw** [comment]
I cannot reproduce this with the latest version of PSReadLine, so it seems to be fixed.
