### ISSUE TITLE
Ctrl+u should work in vi insert mode

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#628]
Ctrl+u (BackwardDeleteLine) is a convenient way to clear the line - it doesn't quite work from Command mode because the cursor can't be 1 past the end, but it should work from insert mode, plus it works in bash.

**Comment by srdubya** [comment]
I have a fix, but cannot create a new branch off of lzybkr/master for it.  I figure it's time to stop messing with my srdubya branch.  
Getting this when I attempt to push my branch:  

> ERROR: Permission to lzybkr/PSReadLine.git denied to srdubya.
