### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by vklimin** [PowerShell/PSReadLine#631]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
-----------------------------------------------------------------------
Последние клавиши (82):
 c d Spacebar " C : \ U s e r s \ 0 0 0 0 0 0 0 Spacebar 0 . Spacebar 0 0 0 0 0 0 \ G o o g l e Spacebar 0 0 0 0 \ 0 0 0 0 0 0 0 0 0 0 0 0 \ E x p G " Enter
 p h p Spacebar e x p g . p h p Enter
 UpArrow Enter
 UpArrow UpArrow DownArrow Enter
 Ctrl+l

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было -240.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by lzybkr** [comment]
This is likely fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadline/2.0.0-beta1) or (less likely) a bug in conhost.

If you can reproduce the problem with 2.0.0-beta1, can you reopen and include more details on how to reproduce?
