### ISSUE TITLE
MenuComplete function not showing menu

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PSReadLine#639]
Environment data
----------------

PS Version: 6.0.1
PSReadLine version: 2.0.0-beta1
OS: macOS High Sierra

Steps to reproduce or exception report
--------------------------------------

```
> Get-Co # Hit Ctrl+Space or whatever your MenuComplete is set to
```

Expected behavior would show the menu, however, currently nothing happens - the prompt stays as is.

**Comment by lzybkr** [comment]
I think this is another case of a key binding that can't work on non-Windows.

On Linux, `showkey -a` shows that `Ctrl+Space` is 0 - the nul character, which actually maps to other characters, e.g. `Ctrl+2`.

**Comment by felixfbecker** [comment]
It's possible to make Ctrl+Space work by remapping it in iTerm to a character you don't normally use (e.g. `ç` aka Alt+C) or any code point from the Unicode Private Use Area (e.g.  aka E000).

```powershell
Set-PSReadLineKeyHandler -Key '' -Function MenuComplete
```

![image](https://user-images.githubusercontent.com/10532611/57461314-1590da00-7277-11e9-8cad-22759c9ff62f.png)

**Comment by daxian-dbw** [comment]
Given this is by design, I will close this issue.

**Comment by Elgirhath** [comment]
For future usages - you can also rebind the powershell function
```
Set-PSReadLineKeyHandler -Chord 'Ctrl+@' -Function MenuComplete
```

since Ctrl+Space produces output equivalent to Ctrl+@
