### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by tongnian0613** [PowerShell/PSReadLine#641]
Environment data
----------------

Steps to reproduce or exception report
-------------------------------------------------------------------------------------------------------------
上 1 个密钥:
 0

异常:
System.ArgumentException: 目标数组的长度不够。请检查 destIndex 和长度以及数组的下限
。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArra y, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dict ionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntr insics engineIntrinsics)

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).
