### ISSUE TITLE
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。

### ISSUE THREAD

**Issue by WilliamJiH** [PowerShell/PSReadLine#642]
-----------------------------------------------------------------------
上 3 个密钥:
 Alt+' Backspace f

异常:
System.ArgumentException: 目标数组的长度不够。请检查 destIndex 和长度以及数组的下限。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationInd ex, Int32 length, Boolean reliable)
   在 System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable,  Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics )

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).
