### ISSUE TITLE
System.ArgumentException with PS as default task after splitting consoles

### ISSUE THREAD

**Issue by ravelus** [PowerShell/PSReadLine#649]
Stack trace:
Últimas 1 claves:
 c

Excepción:
System.ArgumentException: La matriz de destino no es suficientemente larga. Compruebe destIndex, la longitud y los límites inferiores de la matriz.
   en System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   en System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   en Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   en Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   en Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Environment data
----------------
PowerShell version:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  248

Steps to reproduce or exception report
--------------------------------------
1.- Configure Powershell as default task.
2.- Reopen (task powershell started)
3.- Duplicate powershell task splitted to the right
4.- Ctrl + Tab to come back to the original task
5.- Type something -> error

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).
