### ISSUE TITLE
Vi mode menu completion error

### ISSUE THREAD

**Issue by parkovski** [PowerShell/PSReadLine#651]
I'm using vi mode and have tab set to menu complete. I get an `EditItemInsertString -> GroupedEdit` cast exception when I've edited part of the line with vi commands (at least `C` which I use most often) and then press tab for completion. The menu complete works although the completion doesn't show up on the edit line, the error just happens after I press enter or ^C on the line. Additionally, sometimes ^C doesn't work on the first line after the exception is thrown, but this is the only non-reproducible part. The rest is entirely reproducible for me, I'm just not familiar enough with the completion code to track it down.

Environment data
----------------
PS version: 6.0.1
PSReadline version: 2.0 (built from Git)
os: 10.0.17120.1 (WinBuild.160101.0800)
PS file version: 6.0.1

Steps to reproduce or exception report
--------------------------------------
Turn on vi mode and bind tab to menu complete, then type `asdf^[0Cls -^I` (using `^[` = esc and `^I` = tab). You can cycle through a couple completions to see the 'ghost text', but accepting or canceling the line gives me the same exception every time after this.

**Comment by srdubya** [comment]
Please excuse my ignorance...  How do I go about binding tab to menu complete?

**Comment by parkovski** [comment]
Probably should have included my config just in case - here are the options I have set, which includes that setting.

```powershell
  Set-PSReadlineOption -EditMode vi
  Set-PSReadlineOption -BellStyle None
  Set-PSReadlineOption -ViModeIndicator Cursor
  Set-PSReadlineKeyHandler -Key 'Shift+Tab' -Function Complete
  Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
  Set-PSReadlineKeyHandler -Key 'Ctrl+[' -Function ViCommandMode

  Set-PSReadlineKeyHandler -Key 'Ctrl+b' -ViMode Command -Function ScrollDisplayUp
  Set-PSReadlineKeyHandler -Key 'Ctrl+f' -ViMode Command -Function ScrollDisplayDown
  Set-PSReadlineKeyHandler -Key 'Ctrl+y' -ViMode Command -Function ScrollDisplayUpLine
  Set-PSReadlineKeyHandler -Key 'Ctrl+e' -ViMode Command -Function ScrollDisplayDownLine
  Set-PSReadlineKeyHandler -Key 'Ctrl+b' -ViMode Insert -Function ScrollDisplayUp
  Set-PSReadlineKeyHandler -Key 'Ctrl+f' -ViMode Insert -Function ScrollDisplayDown
  Set-PSReadlineKeyHandler -Key 'Ctrl+y' -ViMode Insert -Function ScrollDisplayUpLine
  Set-PSReadlineKeyHandler -Key 'Ctrl+e' -ViMode Insert -Function ScrollDisplayDownLine
```

**Comment by srdubya** [comment]
I've submitted a pull request with a fix.  But, it's a bit "hacky" so I'm not sure @lzybkr  is going to like it.  The problem looks like some inconsistent assumptions around the use of edit histories between the various modes and the menu completion implementation.  Figuring those all out is more work than I have time available, hence the hack.
