### ISSUE TITLE
Build against .Net Core and run tests on Linux

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#652]
By design, PSReadLine builds against .Net Desktop to minimize the number of dlls that need to be included in the module, but it should be possible to build against .Net Core.

This would be useful for 2 reasons - development on non-Windows platforms, and adding CI for non-Windows platforms.

The unit tests already use xUnit, so hopefully it won't be too hard to get them running on Linux.

**Comment by SteveL-MSFT** [comment]
I'm working on this

**Comment by felixfbecker** [comment]
It makes me uncomfortable that this module is bundled in PowerShell Core but only runs CI in Windows.

**Comment by lzybkr** [comment]
@felixfbecker - as the primary author and maintainer, I'm not uncomfortable with the status quo. Hopefully Steve can finish up the work, but CI is unlikely to catch any issues specific to .Net Core, Linux, or Mac.

.Net Core vs. Desktop is a theoretical problem, but essentially a non-issue - most changes are trivial, manipulating strings or whatever.

Linux and Mac are a bigger issue. The existing tests have great coverage (IIRC, >75% block coverage) but cannot easily test UI aspects that typically show up on *any* platform. The tests emulate a console via a mocked console interface, partly because even on Windows, I couldn't reliably scrape the console buffer to validate the UI, and scraping isn't possible on Linux/Mac, so we rely on humans to notice UI issues.

Furthermore - I often manually test PRs before merging. This is not too bad, I'm always using the latest, there are few PRs, and it just makes sense because some things are really hard to test via automation.

And the last line of defense - everybody uses PSReadLine. If something got merged that shouldn't, I'd find out quickly.

**Comment by SteveL-MSFT** [comment]
I'm hoping to continue on this next week.   Maybe a separate PR after this gets merged to integrate with AzDevOps Pipelines (aka VSTS) so we can get Windows, Linux, and macOS coverage in CI)
