### ISSUE TITLE
Proper way to paste a link

### ISSUE THREAD

**Issue by joeky888** [PowerShell/PSReadLine#659]
## Environment data

```powershell
PS version: 5.1.16299.251
PSReadline version: 1.2
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 10.0.16299.15 (WinBuild.160101.0800)
```

## Steps to reproduce or exception report

Well this is not a bug but a question.

I have this binding in profile.ps1

```powershell
Set-PSReadlineKeyHandler -Chord Ctrl+V -ScriptBlock {
    $clipboard = Get-Clipboard -Raw
    $clipboard = $clipboard -replace "&","``&"
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert($clipboard)
 }
```

When I press Ctrl-V, it will paste the data from system clipboard and `&` character will be escaped.

It is convenient when the clipboard data is a web link like `https://example.com?a=b&c=d` .

However, if the clipboard data contains double quotes like this `"https://example.com?a=b&c=d"` , then there is no need to escape the `&` character.

How can I do a smart pasting. Thanks :)

**Comment by lzybkr** [comment]
You could use the PowerShell [parser](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.language.parser.parseinput?view=powershellsdk-1.1.0#System_Management_Automation_Language_Parser_ParseInput_System_String_System_Management_Automation_Language_Token____System_Management_Automation_Language_ParseError____) to tokenize the text so you know the extents to avoid replacing anything.

**Comment by joeky888** [comment]
This is a workaround:

```sh
Set-PSReadlineKeyHandler -Chord Ctrl+V,Ctrl+v -ScriptBlock {
    $clipboard = Get-Clipboard -Raw
    if ($clipboard -match '^http') {
      $clipboard = $clipboard -replace "&","``&"
      $clipboard = $clipboard -replace "\(","``("
      $clipboard = $clipboard -replace "\)","``)"
      $clipboard = $clipboard -replace ",","``,"
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert($clipboard)
  }
```

Works for most cases.

**Comment by joeky888** [comment]
Better solution:

```powershell 
Set-PSReadlineKeyHandler -Chord Ctrl+V,Ctrl+v -ScriptBlock {
    $clipboard = Get-Clipboard -Raw
    if ($clipboard -match '^\s*(http|ftp|magnet)' -or `
        (Test-Path $clipboard.Trim()) ) {
        $clipboard = $clipboard.Trim()
        $clipboard = "'${clipboard}'"
    }
    [Microsoft.PowerShell.PSConsoleReadLine]::Insert($clipboard)
  }
```
