### ISSUE TITLE
Please add option to autocomplete in lowecase

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#662]
```ps
# Now
ls . -Force -Directory

# With option
ls . -force -directory
```

**Comment by lzybkr** [comment]
I have no plans to add such an option.

One of the goals of this project was to avoid adding too many configuration options and instead choose the ideal default for all users.

It wouldn't be hard to add this capability yourself, and you could do so without PSReadLine. You simply need to define your own version of the function `TabExpansion2` - PSReadLine and other hosts like the ISE all call this function to do completion, so you can customize the results as you see fit.
