### ISSUE TITLE
TabExpansion? failure

### ISSUE THREAD

**Issue by wnparker** [PowerShell/PSReadLine#671]
Last 200 Keys:
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow UpArrow x Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownA
rrow DownArrow Escape UpArrow UpArrow LeftArrow LeftArrow UpArrow UpArrow UpArrow UpArro
w UpArrow UpArrow UpArrow UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftAr
row LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow x L
eftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow
 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArr
ow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftA
rrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow UpA
rrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpA
rrow UpArrow DownArrow LeftArrow RightArrow x DownArrow DownArrow DownArrow DownArrow Do
wnArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow
DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow End Ente
r
 $ o b j Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Bac
kspace f i Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspa
ce Backspace Backspace

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and len
gth, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, In
t32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object a
rg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionar
y`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsic
s engineIntrinsics)

<Environment>

PS version: 5.1.16299.251
PSReadline version: 1.2
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 10.0.16299.15 (WinBuild.160101.0800)

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).
