### ISSUE TITLE
console told me to report issue so I am, I received an exception

### ISSUE THREAD

**Issue by mmiller-callibrity** [PowerShell/PSReadLine#676]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
![image](https://user-images.githubusercontent.com/25014192/39101094-bda7736c-4662-11e8-8b82-8645d170c018.png)

**Comment by lzybkr** [comment]
This is fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).
