### ISSUE TITLE
Menu doesn't clear lines when switch from long to short completion

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#689]
1. Start with a completion that nearly fills the command line
2. Invoke `MenuComplete`
3. Select a long completion that forces the command line to span a second line.
4. Select a shorter completion where the command line now spans just the one line.

The last line of the menu is now displayed twice. If the menu top moves up from the previous render, the extra lines need to be cleared.

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me.

**Comment by lzybkr** [comment]
It still reproduces for me:

![image](https://user-images.githubusercontent.com/2148248/48178880-e0f49380-e2d0-11e8-932a-50b989329a9d.png)

**Comment by SteveL-MSFT** [comment]
That repros, I misunderstood what the first line of your repro meant.
