### ISSUE TITLE
appveyor zip artifact is not compatible with macos

### ISSUE THREAD

**Issue by vors** [PowerShell/PSReadLine#698]
I was hoping to grab a dev build, because of the Ctrl+C issue on 2.0.0-beta-1
But this is how it looks like unzipped on mac

![image](https://user-images.githubusercontent.com/816680/40882138-cf789076-668d-11e8-9f75-19ef196d610a.png)

**Comment by lzybkr** [comment]
Isn't this a bug in `Compress-Archive`?

**Comment by vors** [comment]
It's a dotnet problem, but maybe it's worth to use 7z in appveyor to workaround it for now.
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator

Let me try it out and send PR if it works

**Comment by vors** [comment]
ah, you are using invoke-build. That makes things harder.

I just merged https://github.com/PowerShell/platyPS/pull/362 to fix the same issue in platyPS but it was more straightforward there.
I guess it doesn't worth to keep it open, eventually we will get dotnet full v461 images in appveyor and it will resolve.
