### ISSUE TITLE
Visual selection doesn't work on non-Windows systems

### ISSUE THREAD

**Issue by vors** [PowerShell/PSReadLine#699]
Environment data
----------------

Dev build from master 708787f8f51847a4ebd6a8a3dbe8ebdf1c24bc99

```
PS version: 6.1.0-preview.2
PSReadline version: 2.0.0-beta1
os: Darwin Sergeis-MacBook.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
PS file version: 
```

Steps to reproduce or exception report
--------------------------------------

```
pwsh -noprofile
# ctrl+a works
Set-PSReadLineOption -HistoryNoDuplicates -EditMode Windows
# ctrl+a doesn't work
```

See demo
![psreadline-windows-mode](https://user-images.githubusercontent.com/816680/40896921-c7cb2e8a-676c-11e8-9817-a6c7393fa344.gif)

**Comment by lzybkr** [comment]
<kbd>Ctrl+a</kbd> is bound to `SelectAll` in Windows mode because that's what people would expect, and it works correctly on Windows.

On Linux, it is selecting everything, but you don't see the selection (you can verify by typing <kbd>Delete</kbd>), so I suppose I'm using a VT escape sequence incorrectly.

**Comment by vors** [comment]
I was able to change it before (v1.x) with

```powershell
Set-PSReadlineKeyHandler -Functio BeginningOfLine -Chord "Ctrl+A"
Set-PSReadlineKeyHandler -Functio EndOfLine -Chord "Ctrl+E"
```

I cannot do it anymore.

**Comment by lzybkr** [comment]
Try `Ctrl+a` (lower case).

**Comment by vors** [comment]
It's a dotnet problem, but maybe it's worth to use 7z in appveyor to workaround it for now.
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator

Let me try it out and send PR if it works

**Comment by vors** [comment]
whooo, ok it definitely used to work with capital A for whatever reason (I have this line in profile for ages).

**Comment by lzybkr** [comment]
I know.

It's a side effect of my attempt at better supporting non-English keyboard layouts plus better supporting custom bindings on Linux/Mac using the (mostly) same code as Windows.

**Comment by daxian-dbw** [comment]
Going through old issues.
The only remaining issue is the VT sequence for selection on Linux/macOS. I will close this one in favor of #1411
