### ISSUE TITLE
Home and End buttons not working

### ISSUE THREAD

**Issue by MathiasMagnus** [PowerShell/PSReadLine#702]
Environment data
----------------
```
PS version: 6.1.0-preview.2
PSReadline version: 2.0.0-beta2
os: Linux opteron 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version:
```
Steps to reproduce or exception report
--------------------------------------
```
PS /home/mnagy> sélkdjf~~~~
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 1 0 0 Enter
 UpArrow Escape 1 ~ Ctrl+Backspace LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Ctrl+Backspace Ctrl+Backspace s e t - c o n Tab Enter
 e n v Enter
 a s d f Escape 1 ~ Escape 1 ~ Escape 1 ~ Escape 1 ~ a s d f l k j Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace s u d o Space a p t Space u p d a t e Enter
 a p t Space l i s t Space - - u p g r a d a b l e Enter
 s u d o Space a p t Space u p g r a d e Space - y Enter
 e n v Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace 2 2 0 Enter
 g c i Enter
 s é l k d j f Escape 1 ~ Escape 1 ~ Escape 1 ~ Escape 4 ~ PageUp PageUp PageUp PageUp

Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS /home/mnagy>
```
----------------------------------------------------------
Pressing PgUp or PgDwn causes these reports to fly out. More vexing however is the fact that I cannot use the Home or End buttons either, they just print Tilde characters.

Source system is Windows 10 (1803) with Win32 OpenSSH 7.7.0.0 and destination system is Ubuntu Server 16.04 with PS version in the table above. Happens both with stock and latest PSReadLine module (2.0.0-Beta2). If I log into bash instead of pwsh, Home and End work as expected.

**Comment by MathiasMagnus** [comment]
Do you need any more info on the issue to tackle it? The issue has been open for a while and God it's annoying.

**Comment by lzybkr** [comment]
Sorry about the annoyance. I don't think I need more info.

The fix should be simple enough, just catch the exception and maybe call Ding(). It looks like each call to `SetWindowPosition` needs to be guarded, so maybe we need a helper function.

**Comment by lzybkr** [comment]
Closing as a duplicate of #700.

**Comment by andrewsav-bt** [comment]
@lzybkr  Why is this closed? #700 is about PageUp and PageDown and this is about Home and End?

**Comment by msftrncs** [comment]
@andrewsav-datacom, I think either way, the problem and the solution are ultimately the same, its easier to have only one issue you have to close when you fix it.

**Comment by andrewsav-bt** [comment]
@msftrncs sorry, can you explain why do you believe it is the same? I personally after reading both threads see no indication of this, so if you could explain your reasoning to me that would be appreciated.

**Comment by msftrncs** [comment]
The issue here is probably that the OP indicates an issue in the text different than the title.  The exception report, and the bulk of the text in the OP would indicate it is the SAME report as #700.   Either @mathiasMagnus should change the report to focus on the matter of the subject, or, @andrewsav-datacom, just open a new issue to better describe the issue you are having with home/end keys.

**Comment by AndrewSav** [comment]
Okay, here we go: https://github.com/PowerShell/PSReadLine/issues/1027

**Comment by MathiasMagnus** [comment]
Thank you. Apologies for not commenting. The title really didn't bother me, although perhaps it should've.

**Comment by lzybkr** [comment]
It's been awhile, but I probably closed this as duplicate because of the identical exception and fix to ding instead of reporting the exception.

Actually getting the key bindings to work would be a distinct issue - but I'd assumed if `System.ConsolePal` is reporting PlatformNotSupported, then the fix is probably needed there and not in PSReadLine.
