### ISSUE TITLE
[Feature-Request] History-based up-arrow completion

### ISSUE THREAD

**Issue by pavelbraginskiy** [PowerShell/PSReadLine#703]
Normally, pressing the up arrow while typing in a command automatically fills in the latest command in history, regardless of what's already been typed.

However, other shells, such as zsh, will use the last entry in history that matches what I've already typed.

So if I run `sudo dnf upgrade` and then `ls`, in PowerShell typing `sudo dnf↑` will fill in `ls`, while in zsh it will fill in `sudo dnf upgrade`. This allows for a lot easier access to commonly used commands.

**Comment by lzybkr** [comment]
Presumably you found `HistorySearchBackward`. I am considering making that the default behavior.
