### ISSUE TITLE
Cursor is not set properly so lots of spaces are left out there after showing progress bar

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PSReadLine#707]
Unlike the filesystem which all the files and directories already exist in our system, SHiPS Azure provider initially does not have any data in the local system to search for . When a user is navigating around, it reaches out to Azure for fetching data and builds up the navigation tree. In the SHiPS case, when a user cd and then tab, or get-azurerm tab, the progress bar shows up while fetching data. After write-progress completes, it lefts a large spaces.
![image](https://user-images.githubusercontent.com/10171679/41133419-ac698f8a-6a7b-11e8-83a5-602f5f089c67.png)

Initial Analysis
--------
Both the PowerShell and PSReadline are contributing to this issue. PowerShell does not set the cursor to the place where it starts while the PSReadline does not update the cursor position in case the screen has been scrolled up for displaying progress messages.

Open the issue in pscore site too: https://github.com/PowerShell/PowerShell/issues/7022

Environment data
----------------
6.1.0-preview.2
and
PSReadLine 2.0.0-Beta.1 or PSReadLine 2.0.0-Beta.2

Steps to reproduce or exception report
--------------------------------------
portal.azure.com
select bash
type pwsh
cd tab

**Comment by daxian-dbw** [comment]
I tried the repro steps and didn't see the reported behavior anymore. Given this is an old issue, it might have been fixed from the `SHiPS` provider side. Closing for now.
