### ISSUE TITLE
Add slightly more intelligent tab completion

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PSReadLine#712]
This is less an issue and more a feature request/suggestion.

The scenario that I see that would be useful would be if you are typing at the console and then are Piping to another command.

so for example
``` powershell
Get-Service | <tab>
```
would then intelligently suggest the below first

``` powershell
Get-Service | Stop-Service
Get-Service | Restart-Service
Get-Service | Start-Service
```
I can see this being added as an extension to PSReadline but this could also be better placed in the main PowerShell Repository especially if it is to be an extensible model that would allow module authors to do things like

``` powershell
Get-CUItem | Set-CUItem @params
```

etc etc 

this is only a basic example but hopefully makes some sense

This sh

**Comment by lzybkr** [comment]
This is a good idea and was considered long ago when `OutputType` was introduced.

That said, PSReadLine is just a UI for the completion - PowerShell provides all of the smarts for completion, so you should open the suggestion there.

**Comment by kilasuit** [comment]
@lzybkr - was 50/50 on where would be best to open it but agree this probably is better suited for the main PowerShell repo
