### ISSUE TITLE
Include a CompatiblePSEditions field in the module manifest

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PSReadLine#713]
PowerShell Core has an [RFC open to make a breaking change](https://github.com/PowerShell/PowerShell-RFC/pull/130) where modules that don't have `"Core"` as one of the entries in the `CompatiblePSEditions` field of the module manifest will fail to load (and omitting the field will cause it to default to `@("Desktop")`).

Part of the RFC also proposes that being on the PowerShell Core module path means the compatibility check is skipped, but since PSReadLine 2.0 already breaks compatibility with PowerShell v3/4, it could add the `CompatiblePSEditions` field without any harm (I think).

**Comment by lzybkr** [comment]
Right now I think there is a single v5.0 api that PSReadLine uses and using `dynamic` so I could continue supporting v3/4 wouldn't be too hard.

That said, I haven't had any complaints yet that PSReadLine 2.0 doesn't support v3/4 yet.

If I understand correctly, the only scenario I see where this might be needed - somebody deletes `PSReadLine` from the module path (so it won't be autoloaded at startup) and manually loads it from elsewhere.

**Comment by rjmholt** [comment]
Yeah, that's basically the only scenario -- and the simple workaround would be to just put PSReadLine on the module path again... So I don't imagine there's much compelling reason to add the field right now. But thought I would open the issue anyway.

**Comment by daxian-dbw** [comment]
I don't think this is required anymore. Closing this one.
