### ISSUE TITLE
Better support ANSI escape codes

### ISSUE THREAD

**Issue by pavelbraginskiy** [PowerShell/PSReadLine#717]
It's great that `Set-PSReadlineOption -Colors` supports ANSI escape codes on Unix systems. However, it could support them *better*. These codes support more than just colors. 

For example, my Paramter color setting is:
```
`e[2;3;255;102m 
```
This sets not just color, but also makes the parameter italic. Unfortunatly, PSReadLine doesn't clear formatting between words, so every word after that parameter it also in italics.

The workaround is to put the Clear Formatting escape code (`e[0m) at the start of every single symbol type's color setting, which also means I have to use ANSI for every color setting.

A better solution would be for PSReadLine to automatically write `e[0m between words on Unix systems.

**Comment by ExE-Boss** [comment]
Maybe write <code>\`e[0m</code> between words on all systems, since Windows is [moving to using ANSI escape codes too](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/).

**Comment by daxian-dbw** [comment]
This was fixed by #2925
