### ISSUE TITLE
Version 2.0.0Beta2 Spacebar keyhandler is captureed by setting Shift+Spacebar keyhandler

### ISSUE THREAD

**Issue by HerbM** [PowerShell/PSReadLine#719]
Spacebar keyhandler is captureed by setting Shift+Spacebar keyhandler
PSReadline version 1.2 doesn't do this.

Also, no key handler is defined for Shift-Spacebar

[FYI:  Love PSReadLine]

Reproduce:  
  Get-PSReadlineKeyhandler | Where-Object Key -match 'Space'  
  set-psreadlinekeyhandler -chord 'Shift+SpaceBar' -Func Complete
  # Attempt to type any command with a Space in it:
  # Recall Get-PSReadLineKeyHandler above *you can't type it*
  Get-PSReadlineKeyhandler | Where-Object Key -match 'Space'  

Fix (trivial once the problem is understood -- must be done from profile or with pre-configured script since the spaces in the following command cannot be entered): 
  Remove-PSReadLineKeyHandler SpaceBar -ea Ignore

Environment:
PS version: 5.1.14409.1012
PSReadline version: 2.0.0-beta2
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)Steps to reproduce or exception report
--------------------------------------

**Comment by lzybkr** [comment]
By some luck, the fix for this was in the most recently opened PR, so you got lucky pulling from AppVeyor :).
