### ISSUE TITLE
Tab completion without argument is broken on macOS

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PSReadLine#720]
Environment data
----------------

```powershell
PS version: 6.1.0-preview.3
PSReadline version: 2.0.0-beta2
os: Darwin MkiMac.home 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
PS file version:
 ```

Steps to reproduce or exception report
--------------------------------------

On macOS, if you attempt to tab-complete an argument without having typed at least 1 character, nothing is completed.

```powershell
PS> Get-Process <press tab (once or twice)>
```

No completions are shown (unlike on Windows and Linux).

By contrast, once you've typed at least one character of the process name to complete, things start working.

**Comment by lzybkr** [comment]
I don't have access to a mac - so I can't investigate.

I suspect this is not a PSReadLine issue though - more likely it's a problem with PowerShell. You can simulate what PSReadLine does with:

```powershell
$line = "Get-Process "
$comp = TabExpansion2 $line $line.Length
$comp.CompletionMatches.Count -ne 0 # Should be True
```

**Comment by mklement0** [comment]
Thanks, @lzybkr.

I've since realized that the problem seems to be specific to `Get-Process` and may be related to the `.ProcessName` being blank for many processes on macOS.

Your code yields the following error:

```none
Exception calling "CompleteInput" with "3" argument(s): "Cannot process argument because the value of argument "listItemText" is null. Change the value of argument "listItemText" to a non-null value."
```

I'm happy to report this in the PowerShell repo; let me know if you have additional thoughts before I do.
