### ISSUE TITLE
Set-PSReadLineKeyHandler throws resource error when executed in PoweShell x86 Host

### ISSUE THREAD

**Issue by mkostersitz** [PowerShell/PSReadLine#727]
Environment data
----------------
Powershell Host is x86 launched as admin
PS version: 5.1.17713.1000
PSReadline version: 2.0.0-beta2
os: 10.0.17713.1000 (WinBuild.160101.0800)
PS file version: 10.0.17713.1000 (WinBuild.160101.0800)

Steps to reproduce or exception report
-----------------------------------
Open PowerShell (x86) from the start menu
C:\Temp > Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler : Could not find any resources appropriate for the specified culture or the neutral culture.
Make sure "Microsoft.PowerShell.PSReadLine.PSReadLineResources.resources" was correctly embedded or linked into
assembly "Microsoft.Powershell.PSReadline" at compile time, or that all the satellite assemblies required are loadable
and fully signed.
At line:1 char:1
+ Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-PSReadLineKeyHandler], MissingManifestResourceException
    + FullyQualifiedErrorId : System.Resources.MissingManifestResourceException,Microsoft.PowerShell.SetPSReadLineKeyH
   andlerCommand

**Comment by lzybkr** [comment]
This is an issue with how PSReadLine was installed in Insiders builds of Windows 10, not a problem in this repo.
