### ISSUE TITLE
08/13/2018

### ISSUE THREAD

**Issue by lichtakira** [PowerShell/PSReadLine#745]

**Comment by lzybkr** [comment]
Based on what you've reported, it looks like you really were out of memory.

Is there any reason to think PSReadLine is the cause of being out of memory?

**Comment by lichtakira** [comment]
Is this out of hard disk space or memory? The system has 15G memory, it should not run up all the memory.

Sent from my iPhone

On Aug 13, 2018, at 11:16 AM, Jason Shirk <notifications@github.com<mailto:notifications@github.com>> wrote:


Based on what you've reported, it looks like you really were out of memory.

Is there any reason to think PSReadLine is the cause of being out of memory?

**Comment by lzybkr** [comment]
Memory.

Task manager (if it will start) should tell you which process is using a lot of memory, it might not be PowerShell.
