### ISSUE TITLE
Ctrl + V Paste 6.1.0-rc.1

### ISSUE THREAD

**Issue by majesticpancake** [PowerShell/PSReadLine#748]
Ctrl + V Does not work in PowerShell 6.1.0-rc.1

```powershell
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 13 Keys:
 Ctrl+v Ctrl+c Ctrl+c Ctrl+c $ p s v e r Tab Enter
 Ctrl+v

Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.PowerShell.PSConsoleReadLine.ExecuteOnSTAThread(Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

-----------------------------------------------------------------------

Environment data
----------------

PS version: 6.1.0-rc.1
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 6.1.0

Steps to reproduce or exception report
--------------------------------------

Ctrl + V Paste into PowerShell 6.1.0-rc.1

**Comment by lzybkr** [comment]
PowerShell 6.1.0-preview.4 included PSReadLine 2.0.0-beta2 which does support paste, so I'd hope 6.1.0-rc.1 still includes it.

Can you check to see what was installed? Or maybe this is a problem in your environment/profile?

**Comment by majesticpancake** [comment]
6.1.0-rc.1 shipped with 1.2.  I had to install PSReadLine 2.0.0-beta2 with AllowPrerelease swtich.  Ctrl + V is working as expected now.

**Comment by rkeithhill** [comment]
Are you sure?  My 6.1.0-rc1 has PSRL 2.0.0-beta2 in the installed `Modules` folder. What do you get for version if you cat `'C:\Program Files\PowerShell\6-preview\Modules\PSReadLine\PSReadLine.psd1'`?

**Comment by lzybkr** [comment]
I have confirmed `6.1.0-rc.1` includes `2.0.0-beta2` so I'm going to close this.

If you do find there was a problem with the installation (e.g. not cleaning a previous release properly), then that would need to be reported in the PowerShell repo.
