### ISSUE TITLE
ViMode Command key handler chord lost its "shift"??

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PSReadLine#755]
Environment data
----------------

```
PS version: 5.1.17738.1000
PSReadline version: 2.0.0-beta2
os: 10.0.17738.1000 (WinBuild.160101.0800)
PS file version: 10.0.17738.1000 (WinBuild.160101.0800)
```
Steps to reproduce or exception report
--------------------------------------

Start a clean PowerShell with -NoProfile, then:

```powershell
Set-PSReadlineOption -EditMode Vi
Set-PSReadlineOption -ViModeIndicator Cursor
Set-PSReadlineKeyHandler -ViMode Command -Chord Shift+v -Function CaptureScreen
Get-PSReadLineKeyHandler
```

**Expected:** The `CaptureScreen` command should be bound to Shift+v.

**Actual:** It's bound to just `<v>`. (and it actually works with just `<v>`; I just didn't know to use `<v>` because I bound it to Shift+v in the past, which always worked before)

**Comment by lzybkr** [comment]
This is an intentional change because some platforms do not support getting the shift state. You can simply specify <kbd>V</kbd> instead of <kbd>Shift+v</kbd>.

**Comment by jazzdelightsme** [comment]
Warn/error if setting a handler with "Shift" in the chord on such a platform?

**Comment by jazzdelightsme** [comment]
P.S. What's the markdown for the fancy key symbol things?!

**Comment by lzybkr** [comment]
I suppose an error could be useful.

GitHub markdown uses html like this: `<kbd>Shift+v</kbd>`
