### ISSUE TITLE
CaptureScreen function does not work at all on Linux?

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PSReadLine#756]
Environment data
----------------

```
PS version: 6.1.0-rc.1
PSReadline version: 2.0.0-beta2
os: Linux danthom-x1 4.4.0-17738-Microsoft #1000-Microsoft Fri Aug 10 17:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version:
```
Steps to reproduce or exception report
--------------------------------------
I have `CaptureScreen` bound to Shift+v in Vi command mode, which doesn't quite work as expected any more (see #755), but still does work in Windows PowerShell. But I can't get `CaptureScreen` to work at all in Linux (Ubuntu 16.04.4, on WSL), even with setting the edit mode to Windows and trying different key bindings.

**Comment by lzybkr** [comment]
`CaptureScreen` relies on Win32 apis, so this is expected for any non-Windows version of PowerShell.

I'm not aware of a portable way to implement `CaptureScreen`.

**Comment by jazzdelightsme** [comment]
Okay, thanks for the info.

Are there any others that do not work? Perhaps an error or warning could be generated when attempting to bind a command that does not work. It would've saved me fiddling around with it and then bugging you with a GitHub issue.

**Comment by lzybkr** [comment]
The clipboard, so copy/paste is NYI, but there is a PR that will enable it in some scenarios - if you have the correct binary in your path (depends on the platform).

**Comment by daxian-dbw** [comment]
Close as "By Design".
