### ISSUE TITLE
vi mode

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#76]
I'm considering addng vi mode.  Speak up if you'd use it.

Update - vi mode has been implemented and the author has graciously offered to share his implementation.  I asked him to provide unit tests and he'll send a pull request when that's done.

**Comment by jedahu** [comment]
Absolutely +1!

**Comment by lzybkr** [comment]
Thanks to @srdubya - I can close this now.  Sorry it took me so long to get around to reviewing and accepting the PR.

**Comment by ysangkok** [comment]
A PSReadLine with ViMode was released with the Windows 10 Anniversary Update according to http://www.powershellmagazine.com/2016/08/02/pstip-new-powershell-commands-in-windows-10-anniversary-update/

**Comment by lzybkr** [comment]
Yes @ysangkok, thanks to @srdubya, vi mode is in Windows 10 Anniversary Update as well as v1.2 of PSReadline available on [github](https://github.com/lzybkr/PSReadLine/releases/tag/v1.2) and the [powershell gallery](https://www.powershellgallery.com/packages/PSReadline/1.2)
