### ISSUE TITLE
System.ArgumentOutOfRangeException at Microsoft.PowerShell.PSConsoleReadLine.ReadLine

### ISSUE THREAD

**Issue by muliar** [PowerShell/PSReadLine#762]
Environment data
----------------
```PS version: 5.1.17134.228
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------
0. This is possible sequence of steps to reproduce.
1. Have open powershell in admin mode, running the command:
```powershell
PS C:\Users\amuliar> get-help Install-WindowsUpdate
Do you want to run Update-Help?
The Update-Help cmdlet downloads the most current Help files for Windows PowerShell modules, and installs them on your computer. For more information about the Update-Help
cmdlet, see https:/go.microsoft.com/fwlink/?LinkId=210614.
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y` 
```
2.  Have another open powershell in admin mode, with some history. Typed a space and enter, i suppose, I got an exception:
```powershell
PS C:\Users\amuliar\Projects\Solutions\AzurePlatformApp> vs_buildtools.exe --add Microsoft.VisualStudio.Workload.WebBuildTools
vs_buildtools.exe : The term 'vs_buildtools.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ vs_buildtools.exe --add Microsoft.VisualStudio.Workload.WebBuildTools
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (vs_buildtools.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\amuliar\Projects\Solutions\AzurePlatformApp>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 80 Keys:
 v s _ b u i l d t o o l s . e x e Spacebar - - a d d Spacebar M i c r o s o f t . V i s u a l S t u d i o . W o r k l o a d . W e b B u i l d T o o l s Enter
 Ctrl+v Enter
 g 8 t n Ctrl+Insert Delete Ctrl+Delete Ctrl+Backspace

Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.PowerShell.PSConsoleReadLine.Kill(Int32 start, Int32 length, Boolean prepend)
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardKillWord(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\amuliar\Projects\Solutions\AzurePlatformApp>
```

**Comment by lzybkr** [comment]
Thanks for reporting - this is a duplicate of https://github.com/lzybkr/PSReadLine/issues/241 and fixed in 
the latest release [2.0.0-beta2](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta2).

**Comment by ghost** [comment]
[](url)

**Comment by ghost** [comment]
> ## Environment data
> PSReadline version: 1.2
> os: 10.0.17134.1 (WinBuild.160101.0800)
> PS file version: 10.0.17134.1 (WinBuild.160101.0800)
> ## Steps to reproduce or exception report
> 0. This is possible sequence of steps to reproduce.
> 1. Have open powershell in admin mode, running the command:
> 
> PS C:\Users\amuliar> get-help Install-WindowsUpdate
> Do you want to run Update-Help?
> The Update-Help cmdlet downloads the most current Help files for Windows PowerShell modules, and installs them on your computer. For more information about the Update-Help
> cmdlet, see https:/go.microsoft.com/fwlink/?LinkId=210614.
> [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y` 
> 2. Have another open powershell in admin mode, with some history. Typed a space and enter, i suppose, I got an exception:
> 
> PS C:\Users\amuliar\Projects\Solutions\AzurePlatformApp> vs_buildtools.exe --add Microsoft.VisualStudio.Workload.WebBuildTools
> vs_buildtools.exe : The term 'vs_buildtools.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
> path was included, verify that the path is correct and try again.
> At line:1 char:1
> + vs_buildtools.exe --add Microsoft.VisualStudio.Workload.WebBuildTools
> + ~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (vs_buildtools.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> PS C:\Users\amuliar\Projects\Solutions\AzurePlatformApp>
> Oops, something went wrong.  Please report this bug with the details below.
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
> -----------------------------------------------------------------------
> Last 80 Keys:
>  v s _ b u i l d t o o l s . e x e Spacebar - - a d d Spacebar M i c r o s o f t . V i s u a l S t u d i o . W o r k l o a d . W e b B u i l d T o o l s Enter
>  Ctrl+v Enter
>  g 8 t n Ctrl+Insert Delete Ctrl+Delete Ctrl+Backspace
> 
> Exception:
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>    at Microsoft.PowerShell.PSConsoleReadLine.Kill(Int32 start, Int32 length, Boolean prepend)
>    at Microsoft.PowerShell.PSConsoleReadLine.BackwardKillWord(Nullable`1 key, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
>    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
> -----------------------------------------------------------------------

**Comment by ghost** [comment]
RESTREAM
\
