### ISSUE TITLE
ShowToolTips option no longer works with the Complete function in 2.0.0 betas

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PSReadLine#763]
Environment data
----------------

PS version: 5.1.17134.228
PSReadline version: 2.0.0-beta3
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)

Steps to reproduce
--------------------------------------
1: Enable the Complete and ShowToolTips options
`Set-PSReadlineKeyHandler -Chord Tab -Function Complete`
`Set-PSReadlineOption -ShowToolTips`
2: Try to tab complete anything that would show a tooltip (Command, Parameter)

In 1.2 it shows each command/parameter on a list with the default parameter set/The input value for that parameter like this:

```
Get-ChildItem -<TAB><TAB>
Path                 - [string[]] Path
LiteralPath          - [string[]] LiteralPath
Filter               - [string] Filter
...

```
In all of the 2.0 beta releases it shows each entry in a grid like formation with no tooltips anywhere

```
Get-ChildItem -<TAB><TAB>
Path                 Depth                File                 ErrorAction          OutVariable
LiteralPath          Force                Hidden               WarningAction        OutBuffer
...
```

The tooltips are important, but the list view is just as important to me.

**Comment by lzybkr** [comment]
Did you try `beta1` or `beta2`?

I removed the list view, but enabled `ShowToolTips` by default. It seems like it's not working in `beta3` though, maybe related to a PR from @jianyunt who was fixing other issues in that code.

I had essentially no feedback on `ShowToolTips`, so I wasn't sure anyone even used it. I did find that the list view truncated much of the useful information in the tooltip. By moving to the table view **and** displaying the tooltip below the table, I think it's an improved experience. I'm certain there is still room for improvement, but I haven't really had the time or ideas to try for an even better experience.

**Comment by jianyunt** [comment]
It looks like `beta2` and`beta3` have the consistent behavior.

``` PowerShell
PS E:\> $a=Get-Module -name PSReadline
PS E:\> $a.PrivateData.PSData

Name                           Value
----                           -----
Prerelease                     beta2


PS E:\> Get-ChildItem -
Path                 Recurse              Attributes           System               InformationAction    OutBuffer
LiteralPath          Depth                Directory            Verbose              ErrorVariable        PipelineVariable
Filter               Force                File                 Debug                WarningVariable
Include              Name                 Hidden               ErrorAction          InformationVariable
Exclude              UseTransaction       ReadOnly             WarningAction        OutVariable
PS E:\> Get-ChildItem -

**Comment by lzybkr** [comment]
Oh, right, `ShowCompletions` no longer shows tool tips (and I'm not sure I'll revisit that), but `MenuComplete` should.

**Comment by lzybkr** [comment]
@jianyunt - your change did regress `MenuComplete`. If your start in a new window, tooltips appear below the menu, but if you are at the bottom of the buffer, tooltips no longer appear.

**Comment by MartinGC94** [comment]
I agree that the tableview and the dynamic tooltip at the bottom is an improved experience for `MenuComplete`, but for `Complete` the only view that makes sense in my eyes is the list view with tooltips, and it's the perfect view for quickly checking the parameters for a cmdlet.

You said you weren't sure if you would revisit it, but would you be open to the idea of someone else adding back the old listview + tooltips to `complete` as an option?

**Comment by lzybkr** [comment]
@MartinGC94 - I think having too many options is a bad thing - it can be way too confusing.

I am open to improvements though, e.g. using a different UI for specific completion types like parameters.
