### ISSUE TITLE
File name inserted into paste input

### ISSUE THREAD

**Issue by frizop** [PowerShell/PSReadLine#77]
Pasting in the following three lines causes the third line to insert the first tab completed file name (for me, it's .berkshelf):

function Get-Foo {
    $defaultDisplayPropertySet = New-Object System.Management.Automation.PSPropertySet('DefaultDisplayPropertySet',[string[]]$defaultProperties)
    $PSStandardMembers = [System.Management.Automation.PSMemberInfo[]]@($defaultDisplayPropertySet)

Please note, that there are one tab characters preceding the second and third lines.

**Comment by kayasax** [comment]
I have same problem here, but ctrl+V only paste the first line of my clipboard ...? (I'm using powershell within ConEmu)

**Comment by lzybkr** [comment]
Closing in favor of #579 which covers all of the known issues with right-click paste.
