### ISSUE TITLE
PowerShell.OnIdle seems not to fire in PSReadline 2.0 beta

### ISSUE THREAD

**Issue by nickcox** [PowerShell/PSReadLine#773]
Environment data
----------------

PS version: 5.1.17134.228
PSReadline version: 2.0.0-beta1
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
```
> Register-EngineEvent -SourceIdentifier PowerShell.OnIdle -Action {Write-Host 'test message'}
# ...nothing happens
> Remove-Module PSReadline
> test message
test message
test message
...
```

**Comment by SeeminglyScience** [comment]
@nickcox It looks like you are on a slightly older beta build.  Could you try updating to `2.0.0-beta3` see if it still happens for you?

**Comment by lzybkr** [comment]
I can't reproduce this with `2.0.0-beta3` in Windows PowerShell or PowerShell Core.

I saw the same issue reported here - https://github.com/PowerShell/PowerShell/issues/8000 - maybe there's something common about the environments to suggest where the problem lies.

**Comment by nickcox** [comment]
Yep, apologies, it's working fine in `2.0.0-beta3`. 🖖
