### ISSUE TITLE
[console]::backgroundcolor gets reset by PSReadLine

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#774]
Environment data
----------------

PS version: 5.1.18252.1002
PSReadline version: 2.0.0-beta3
os: 10.0.18252.1002 (WinBuild.160101.0800)
PS file version: 10.0.18252.1002 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------

```powershell
[console]::backgroundcolor = "black"
cls
```

Expected:
background to be black

Actual:
background is still dark blue

Removing PSReadLine makes this work correctly

**Comment by DHowett-MSFT** [comment]
[Linking] This was also reported at Microsoft/Console#276.

**Comment by Jaykul** [comment]
Any chance of a release of that fix?

**Comment by lzybkr** [comment]
There are still a couple ugly bugs I'll fix before the next release, should be this year though. :)
