### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by TTicharles** [PowerShell/PSReadLine#775]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
异常:
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.UpdateHistoryDuringInteractiveSearch(String toMatch, Int32 direction, Int32& searchFromPoint)
   在 Microsoft.PowerShell.PSConsoleReadLine.InteractiveHistorySearchLoop(Int32 direction)
   在 Microsoft.PowerShell.PSConsoleReadLine.InteractiveHistorySearch(Int32 direction)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
Which version of PSReadLine are you using?
