### ISSUE TITLE
Custom key handlers don't trigger

### ISSUE THREAD

**Issue by madig** [PowerShell/PSReadLine#776]
Environment data
----------------

PS version: 6.1.0
PSReadline version: 2.0.0-beta3
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 6.1.0

Steps to reproduce or exception report
--------------------------------------

Set:
```Powershell
Set-PSReadlineKeyHandler -Chord Ctrl+Y -Function YankLastArg
Set-PSReadlineKeyHandler -Chord Ctrl+D -Function DeleteCharOrExit
```
These don't do anything. The default key stroke for YankLastArg (`Alt+.`) works. The handlers are listed in `Get-PSReadLineKeyHandler`:
```
Key              Function           Description
---              --------           -----------
[...]
Delete           DeleteChar         Delete the character under the cursor
Ctrl+D           DeleteCharOrExit   Delete the character under the cursor, or if the line is empty, exit the process.
[...]
Alt+.            YankLastArg        Copy the text of the last argument to the input
Ctrl+Y           YankLastArg        Copy the text of the last argument to the input
```
This worked in Pwsh 6.0.4 previously.

**Comment by SeeminglyScience** [comment]
@madig are you expecting the key handler to trigger when pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>y</kbd> or just <kbd>Ctrl</kbd> + <kbd>y</kbd>?

If the latter, try 
```powershell
Set-PSReadLineKeyHandler -Chord Ctrl+y -Function YankLastArg
```

**Comment by madig** [comment]
Ah! Yes, I want no shift :) Thanks!
