### ISSUE TITLE
PowerShell Core 6 with PSReadLine 2 causes double CJK chars under Cmder in Windows 7

### ISSUE THREAD

**Issue by chawyehsu** [PowerShell/PSReadLine#779]
Environment data
----------------
```
PS version: 6.1.0
PSReadline version: 2.0.0-beta3
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 6.1.0
```

Steps to reproduce or exception report
--------------------------------------
![cap](https://user-images.githubusercontent.com/5764917/47072674-1b669580-d229-11e8-920f-519dbdf08ff2.gif)

Won't have this issue when using PSReadLine 1.2.
```
PC reproduce
$ dir

    Directory: C:\reproduce

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2018/10/17     13:45                hello-world
d-----       2018/10/17     13:45                おはよう
d-----       2018/10/17     13:45                你好世界
-a----       2018/10/17     13:45              0 helloworld.txt
-a----       2018/10/17     13:45              0 你好世界.txt

PC reproduce
$ (Get-Module -Name PSReadLine).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      -1     -1
```

**Comment by lzybkr** [comment]
Interesting, this is probably related to https://github.com/Microsoft/console/issues/280.

**Comment by DHowett-MSFT** [comment]
It's likely a combination of that _and_ that Cmder can only act as a terminal by reading the console output buffer. When "Raster Fonts" is selected, there are some observable changes in some console output reading APIs (for compatibility with legacy applications). That may include the duplication of double-width characters.

**Comment by mwhds97** [comment]
I've been struggled with this issue for years, until I found a solution by chance.
Just try adding the following to your profile:
```
$OutputEncoding = [System.Text.Encoding]::UTF8
[System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[System.Console]::InputEncoding = [System.Text.Encoding]::UTF8
```
The 3 lines above saved my conemu, vscode, etc. Hope it works for you.

**Comment by daxian-dbw** [comment]
@mwhds97 Thanks for sharing the workaround. I will close this as an external issue.
