### ISSUE TITLE
Entering VICommand mode failed and gave instructions to report bug here

### ISSUE THREAD

**Issue by HerbM** [PowerShell/PSReadLine#792]
Environment data
----------------
*Provide your command output (your command errored because I have StrictMode version Latest enabled:*
````
PS version: 5.1.14409.1012
PSReadline version: 2.0.0-beta3
The variable '$IsLinux' cannot be retrieved because it has not been set.
At line:9 char:9
+     if ($IsLinux -or $IsMacOS) {
+         ~~~~~~~~
    + CategoryInfo          : InvalidOperation: (IsLinux:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
````
Without the error
-------------------
````
set-strictmode -off     
##  paste in your command in 2nd console
PS version: 5.1.14409.1012
PSReadline version: 2.0.0-beta3
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
````
Steps to reproduce or exception report
-------------------------------------------
1.  Assigned Ctrl-i to VICommandMode
2. Pressed Ctrl-i to enter ViCommand mode 
3. Received the following error.
4.  Console was no longer usable -- could reset the command line but any key redisplayed the error
     (prompt redisplays but any key I've tried rediplays the error)

Actual command and error result:
-------------------------------------
````
<# C:\Users\Name\downloads #> set-psreadlinekeyhandler Ctrl-i ViCommandMode
    *Oops, something went wrong.  Please report this bug with the details below.*
    *Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new*
````

PS:  If you wish to fix the diagnostic "version" command... 
----------------------------------------------------------------
This should work on both PowerShell pre-6/non-Core and core:
````
if ((gv IsLinux,IsMacOS -ea ignore -value) -contains $true) {
    "os: $(uname -a)"
} else {
    "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
}
````

**Comment by daxian-dbw** [comment]
We had lots of fixes to improve the stability of PSReadLine, and this issue looks like one that was fixed in the latest version. Please upgrade to the v2.3.1-beta1 version of PSReadLine and give it a try (see instructions [here](https://github.com/PowerShell/PSReadLine#upgrading)). Feel free to open a new issue if you continue to run into this.
