### ISSUE TITLE
Tooltip not fully cleared

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#794]
Repro w/ latest (unreleased):

```
PS> [Environment]::<Ctrl+Space>P
```

The screen will have part of `CommandLine` at the bottom like:

![image](https://user-images.githubusercontent.com/2148248/47981443-bf04d200-e080-11e8-8029-d9c38c677b56.png)

**Comment by daxian-dbw** [comment]
I cannot reproduce this with the latest 2.3.0-beta0 version of PSReadLine, so consider this was fixed.
