### ISSUE TITLE
Supporting '_' or '^' and '$' to move to the beginning and end of the logical line in Vi mode

### ISSUE THREAD

**Issue by springcomp** [PowerShell/PSReadLine#795]
Currently, the <kbd>^</kbd> key moves the cursor to the first non-blank character of the input.
Likewise, the <kbd>$</kbd> key moves the cursor to the very end of the input.

I would prefer those keys to be restricted to movements in the current logical line of a multi-line buffer.

![vi_movements](https://user-images.githubusercontent.com/8488398/48083917-b2a28580-e1f6-11e8-91e0-85e55383900e.gif)

I have prepared an implementation to this effect, but this touches the `GotoFirstNonBlankOfLine` and `MoveToEndOfLine`methods.

https://github.com/lzybkr/PSReadLine/blob/274381a89e937d70d9fb1b4f77c7cbf38909db8e/PSReadLine/Movement.vi.cs#L194-L207

https://github.com/lzybkr/PSReadLine/blob/274381a89e937d70d9fb1b4f77c7cbf38909db8e/PSReadLine/Movement.vi.cs#L150-L156

What I'm concerned about is that those methods are public and probably relied on in existing scripts. Furthermore, the documentation for the `MoveToEndOfLine` method specifically states that it moves the cursor at the end of the **input**.

What could be the best way to introduce such a change?

**Comment by lzybkr** [comment]
I think it's very uncommon to use methods like these as an api - they are more often used for simple remapping of key bindings.

So from that perspective, I think it's relatively safe to change these methods, but it wouldn't hurt to wait a bit for some feedback before merging a change.

I'm also fine with you opening a PR and maybe someone will chime in on that - we can sit on the PR for some time as well.

**Comment by springcomp** [comment]
All right, thanks. That seems reasonable.
