### ISSUE TITLE
Standard console-window keyboard shortcut Alt+F4 is not recognized

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PSReadLine#815]
Note: Applies to Windows only.

By default (in `cmd.exe` and in PS with `PSReadLine` not loaded), <kbd>Alt+F4</kbd> unconditionally and instantly closes the console window.

With `PSReadLine` imported, this key chord is ignored.

Curiously, executing `[console]::ReadKey()` and _then_ pressing <kbd>Alt+F4</kbd> _does_ close the window.

Workaround:

```powershell
Set-PSReadlineKeyHandler Alt+F4 -ScriptBlock { 
  (New-Object -ComObject WScript.Shell).SendKeys('%{F4}')
}
```

Environment data
----------------

```powershell
PS version: 6.2.0-preview.1
PSReadline version: 2.0.0-beta3
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 6.2.0
```

**Comment by lzybkr** [comment]
This has the same root cause as the report in https://github.com/lzybkr/PSReadLine/issues/280 so I'm closing as a duplicate.

**Comment by mklement0** [comment]
For workarounds for other console-window shortcut keys, see https://github.com/lzybkr/PSReadLine/issues/280#issuecomment-441338880.
