### ISSUE TITLE
Exception while rendering

### ISSUE THREAD

**Issue by flyingdutchmen001** [PowerShell/PSReadLine#817]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
![knipseloeps](https://user-images.githubusercontent.com/32844817/48970034-78632180-f007-11e8-9058-042cbf1daa52.PNG)

**Comment by lzybkr** [comment]
Please do include text when reporting issues, it's much easier to search.

Which version of PSReadLine are you using? If 1.2 and you can easily reproduce the problem, do try 
[2.0.0-beta3](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta3).

**Comment by flyingdutchmen001** [comment]
Thanks i will do that

Verzonden vanuit Mail voor Windows 10

Van: Jason Shirk
Verzonden: maandag 26 november 2018 16:42
Aan: lzybkr/PSReadLine
CC: Arjan Berends; Author
Onderwerp: Re: [lzybkr/PSReadLine] bug (#817)

Please do include text when reporting issues, it's much easier to search.
Which version of PSReadLine are you using? If 1.2 and you can easily reproduce the problem, do try
2.0.0-beta3.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by daxian-dbw** [comment]
Closing this issue as it's pretty old and with no repro steps. Please try out the latest PSReadLine module and see if the issue still repros.
