### ISSUE TITLE
$host.ui.rawui.foregroundcolor difference between v1.2 and v2 under Cmder/Conemu

### ISSUE THREAD

**Issue by chawyehsu** [PowerShell/PSReadLine#818]
Environment data
----------------
```
PS version: 6.1.1
PSReadline version: 1.2 / 2.0.0-beta3
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 6.1.1
```

Steps to reproduce or exception report
--------------------------------------

``` sh
> pwsh -noprofile
> (Get-Module -Name "PSReadline").Version
> $host.ui.rawui.foregroundcolor
```

![capture2](https://user-images.githubusercontent.com/5764917/48971460-fa2d6c00-f054-11e8-861c-31c88bf5e8fd.PNG)
![capture3](https://user-images.githubusercontent.com/5764917/48970566-9b61f580-f048-11e8-8e3d-4fa161cae017.PNG)

**Comment by chawyehsu** [comment]
It looks like a combination issue of PSReadLine2 and Cmder, related to https://github.com/cmderdev/cmder/issues/1899. 📌

**Comment by lzybkr** [comment]
I'm guessing this is fixed in the [latest builds](https://ci.appveyor.com/project/lzybkr/PSReadLine/branch/master/artifacts), and if so, a duplicate of #774.

**Comment by chawyehsu** [comment]
How can I install the snapshot build, I would like to test if it's fixed.

**Comment by chawyehsu** [comment]
![capture4](https://user-images.githubusercontent.com/5764917/48971435-9f941000-f054-11e8-9117-e99cb5a7fdda.PNG)
It works as expected, thank you for providing this information. I'll close this issue as a duplicate of #774.
