### ISSUE TITLE
Windows Key showing as input

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PSReadLine#826]
Environment data
----------------

```raw
PS version: 5.1.17134.407
PSReadline version: 2.0.0-beta3
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------

Since #822 pressing the windows key gets inserted as `^@`, including when using global hotkeys like <kbd>Win</kbd> + <kbd>Left</kbd>. A `Ignore` key binding may be needed.

**Comment by gwojan** [comment]
I just installed the 1.0.486 build from AppVeyor and noticed this as well.

**Comment by lzybkr** [comment]
I'll fix this soon, but I have a big related change in the works so don't bother with any PRs on this one.

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me with beta.4
