### ISSUE TITLE
PSReadline blocking main thread on Linux / MacOS

### ISSUE THREAD

**Issue by Tiberriver256** [PowerShell/PSReadLine#835]
Environment data
----------------
PS version: 6.1.1
PSReadline version: 2.0.0-beta3
os: Linux MYCOMPUTER 4.4.0-17134-Microsoft #345-Microsoft Wed Sep 19 17:47:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce or exception report
--------------------------------------
```powershell
$timer = [timers.timer]::new()
$timer.Interval = 500

Register-ObjectEvent -InputObject $Timer -EventName Elapsed -SourceIdentifier Timer.Random -Action { write-host "$(get-date)" }

$timer.Enabled = $true
```

# Expected behavior

```none
PS /mnt/c/> 12/16/2018 20:46:39
                  12/16/2018 20:46:39
                  12/16/2018 20:46:40
                  12/16/2018 20:46:40
                  12/16/2018 20:46:41
                  12/16/2018 20:46:41
                  12/16/2018 20:46:42
                  12/16/2018 20:46:42
                  12/16/2018 20:46:43
                  12/16/2018 20:46:43
                  12/16/2018 20:46:44
                  12/16/2018 20:46:44
                  12/16/2018 20:46:45
                  12/16/2018 20:46:45
                  12/16/2018 20:46:46
                  12/16/2018 20:46:46
                  12/16/2018 20:46:47
                  12/16/2018 20:46:47
                  12/16/2018 20:46:48
                  12/16/2018 20:46:48
                  12/16/2018 20:46:49
                  12/16/2018 20:46:49
                  12/16/2018 20:46:50
```

# Actual behavior

```none
PS /mnt/c/>
```
It will hang until a key is pressed and then it's like it tries to execute as many of the action blocks that are queued until the prompt takes back over. The time stamps from Get-Date will all be exactly the same because they did not execute on the interval.

Running ```Remove-Module PSReadline``` will bring back expected behavior although I lose all coolness in my console.

Moved from https://github.com/PowerShell/PowerShell/issues/8478

**Comment by Tiberriver256** [comment]
Some discussion happening around an async console.read method here:
dotnet/corefx#25036

Also, I found a nice keyboard interceptor here that works good on Windows as an alternative non-thread blocking to the read method but not sure if it could be implemented x-plat or not. It uses p/invoke and native libraries to intercept the keyboard events:

https://github.com/lontivero/Open.WinKeyboardHook/blob/master/KeyboardInterceptor.cs

**Comment by StevenBucher98** [comment]
Is this still and issue in the latest version of PSReadLine (2.3.4)?
