### ISSUE TITLE
macOS, Windows 10: Using the clear-screen-and-reset-scrollback-buffer keyboard shortcut makes PowerShell misplace user input

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PSReadLine#841]
_Update_:

* The problem may be in PowerShell itself, as it also seems to happen with `PSReadLine` unloaded: see https://github.com/PowerShell/PowerShell/issues/19479

---

On macOS, both Terminal.app and iTerm2.app support keyboard shortcut <kbd>Command-K</kbd> for clearing the screen as well as the scrollback buffer.

PowerShell doesn't realize that the cursor position has been reset, and prints user input on the previously active line instead of the first.

_Update_: @spoyd reports below that _Window 10_ is also affected, but that the issue only started to appear in release _1809_.

# Steps to reproduce

On macOS:

```powershell
Get-ChildItem -Recurse | Select -First 100 # issue command that places cursor on the bottom line
# Press Command-K
```

# Expected behavior

The prompt should be displayed on the 1st line, and typing input should show next to it.

# Actual behavior

While the prompt is displayed on the 1st line, typing input causes it to be printed on the line that was active when the keyboard shortcut was pressed; note how the `a`, typed after clearing the screen, is printed on the bottom line:

![image](https://user-images.githubusercontent.com/588825/50517254-cd370380-0aaf-11e9-8f28-4475e9459af2.png)

# Environment data

```none
PSReadLine 2.0.0-beta3 on macOS 10.14.2
```

**Comment by spoyd** [comment]
Similar issue exists with the PSReadLine that ships with Windows 10 1809 and the default Ctrl+L binding.

Environment:
===============
PS version: 5.1.17763.134
PSReadline version: 2.0.0-beta2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)

**Comment by mklement0** [comment]
Thanks, @spoyd, but, curiously, I don't see the issue on Windows, neither in Windows PowerShell nor in PowerShell Core, having just tried with the latest public PSReadLine beta, 2.0.0-beta3.

My Windows version and Windows PowerShell version are slightly older, but I don't expect that to matter:

Windows: Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.523)
Windows PowerShell: v5.1.17134.407 
PowerShell Core: v6.2.0-preview.3

Are you using a different terminal emulator?

**Comment by spoyd** [comment]
Related to this #851

**Comment by amongonz** [comment]
I'm having a weird variant of this on Windows 10 1809, but it only shows up on VS Code's embedded terminal. When opening a new terminal, nothing shows and typing results in this:

![image](https://user-images.githubusercontent.com/1218253/52901402-4f67bc80-3203-11e9-9a48-def9af556839.png)

but then I realized I could scroll up:

![image](https://user-images.githubusercontent.com/1218253/52901403-5abae800-3203-11e9-9918-333c1cd3d161.png)

As you can see, even the prompt is gone. After I clear the screen, it finally shows up and I just reproduce #851 instead.

**Comment by lighterless** [comment]
Is there an update on this issue? It's still affecting macOS (10.14.6) on PowerShell 7.0.0-preview.3

**Comment by Tahvohck** [comment]
I'm noticing this specifically in PowerShell Core (PS 7.0.0.0-preview.4) whether run via the default conhost or via conemu. Any form of clearing the screen using a PSReadLineKeyHandler (`ClearScreen` builtin, `{ clear }` script block, directly addressing `[System.Console]`) causes the terminal to not be reset correctly. Either it doesn't clear the screen but does reset the cursor position, or the other way around.

Edit: This is specifically on a Windows 7 machine with a stand-alone version of PS Core. (Zip installation)
Edit 2: Also present way back in PSCore 6.1.6. So basically it seems like something about how PSCore handles PSReadLine doesn't play nice with the way that PSReadLine invokes its key handlers.

**Comment by msftrncs** [comment]
@Tahvohck, can you confirm that in each situation, what the version of PSReadLine is?   You may have to use the `module` command, and then read in to the `privatedata.psdata` property to get the beta version.

**Comment by Tahvohck** [comment]
Here's my module data. It's the same module in both cases, as I was just swapping out the PSCore program each time.

```
C:\> module                                                                                                             
                                                                                                                        
ModuleType Version    PreRelease Name                                ExportedCommands                                   
---------- -------    ---------- ----                                ----------------                                   
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It… 
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob… 
Script     1.0.0      beta3      posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-… 
Script     2.0.0      beta5      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, … 
                                                                                                                        
                                                                                                                        
C:\> (get-module PSReadline).PrivateData.psdata                                                                         
                                                                                                                        
Name                           Value                                                                                    
----                           -----                                                                                    
Prerelease                     beta5

**Comment by lighterless** [comment]
@mklement0 were you ever able to find a workaround for this? 

It's still affecting `pwsh 7.0.0-rc.2` with `PSReadLine 2.0 rc2` and I can't find anything on the web except for this GitHub issue regarding this issue. In addition to the issue with `command+k`, `ctrl+l` works as expected in a terminal (Terminal.app, iTerm2.app, Hyper.app) but not within the integrated terminal in VSCode.

This bug has been super frustrating to say the least.

**Comment by mklement0** [comment]
@ben-eai: No direct workaround as such, but you can place the following function in your `$PROFILE`; invoking `clr` then clears the screen and the scrollback buffer, without exhibiting the bug:

```powershell
function clr {
<#
.SYNOPSIS
 Clears the terminal (console) screen as well as the scrollback buffer.
#>
  [Console]::Write("`e[2J`e[3J`e[H")
}
```

In Visual Studio Code, <kbd>cmd+k</kbd> is actually defined by default on macOS, though it may be shadowed if there are key _chords_ starting with that shortcut that are in effect _globally_.

You can work around that by redefining the binding in your `keybindings.json` _explicitly_:

```json
{
  "key": "cmd+k",
  "command": "workbench.action.terminal.clear",
  "when": "terminalFocus"
}
```

The keyboard shortcut isn't predefined on Linux or Windows; you can define it as above, but use `ctrl+k` instead, for instance, but note that in Linux terminals that shortcut is traditionally bound to delete-the-rest-of-the-line, so you may want to look for an alternative.

Finally, you can also invoke the functionality via the integrated terminal's shortcut menu, command `Clear`. On Windows, right-clicking defaults to _pasting_, so you'll first have to turn on the shortcut menu by setting `terminal.integrated.rightClickBehavior` to `default` (`Terminal › Integrated: Right Click Behavior` in the Settings GUI).

**Comment by lighterless** [comment]
> @ben-eai: No direct workaround as such, but you can place the following function in your `$PROFILE`; invoking `clr` then clears the screen and the scrollback buffer, without exhibiting the bug:
> 
> ```powershell
> function clr {
> <#
> .SYNOPSIS
>  Clears the terminal (console) screen as well as the scrollback buffer.
> #>
>   [Console]::Write("`e[2J`e[3J`e[H")
> }
> ```
> 


Thanks for this @mklement0, I'll accept this as a workaround.

**Comment by StevenBucher98** [comment]
I cannot seem to reproduce on iTerm2 or Terminal on Mac, also created an action in Windows Terminal for clearing buffer. Let me know if this is still an issue on latest PSReadLine 2.3.4.
