### ISSUE TITLE
Attempt to use the script Export-AppServiceCertificate

### ISSUE THREAD

**Issue by WiseMack** [PowerShell/PSReadLine#842]
Export-AppServiceCertificate

cmdlet Export-AppServiceCertificate at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
loginId: myMail@gmail.com
subscriptionId: (The big ass line of numbers that shows up in the VMInstance Overview)
resourceGroupName: airheadsbc
name: airheadsbcCert

Account          SubscriptionName TenantId                             Environment
-------          ---------------- --------                             -----------
myMail@gmail.com Pay-As-You-Go    lotsanumbers AzureCloud

Name               : Pay-As-You-Go (BigAssCode) - myMail@gmail.com
Account            : myMail@gmail.com
Environment        : AzureCloud
Subscription       : SubsC
Tenant             : _Tenant_
TokenCache         : Microsoft.Azure.Commands.Common.Authentication.Core.ProtectedFileTokenCache
VersionProfile     :
ExtendedProperties : {}

Set-AzureRmKeyVaultAccessPolicy : Cannot find the Active Directory object '' in tenant '_Tenant_'. Please make sure that the user or application service principal you are authorizing is registered in the current subscription's Azure Active directory. The TenantID displayed by the cmdlet 'Get-AzContext' is the current subscription's Azure Active directory.
At line:38 char:1
+ Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName $keyVaultResourceG ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzKeyVaultAccessPolicy], ArgumentException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

Get Secret Access to account myMail@gmail.com has been granted from the KeyVault, please check and remove the policy after exporting the certificate
Created an App Service Certificate copy at: /home/jorge\appservicecertificate.pfx
WARNING: For security reasons, do not store the PFX password. Use it directly from the console as required.
PFX password:

Environment data
----------------

PS version: 6.1.1
PSReadline version: 2.0.0-beta3
os: Linux cc-11d3989c-85fb59dbf-jkhpq 4.15.0-1036-azure #38~16.04.1-Ubuntu SMP Fri Dec 7 03:21:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version:
Steps to reproduce or exception report
--------------------------------------

Attempt to use the script Export-AppServiceCertificate found in
https://blogs.msdn.microsoft.com/appserviceteam/2017/02/24/creating-a-local-pfx-copy-of-app-service-certificate/

**Comment by WiseMack** [comment]
For the record Issue #821 includes the problems I had using the script

**Comment by daxian-dbw** [comment]
I believe this issue has been fixed in the latest PSReadLine module. Please upgrade and give it a try.
