### ISSUE TITLE
Get/Set-PSReadLineOption -Colors improvements

### ISSUE THREAD

**Issue by raisin-loaf** [PowerShell/PSReadLine#845]
I feel like I'm missing something obvious but I can't seem to change a handful of colours from their defaults. Specifically:

* `ContinuationPromptColor`
* `DefaultTokenColor`
* `MemberColor`
* `NumberColor`

Other colors like `CommandColor` and `CommentColor` seem to accept new values without issue.

This isn't the end of the world but as someone who prefers the solarized-light colour scheme the default for `DefaultTokenColor` (in particular) is so close to the background it renders the text invisible.

```powershell
Set-PSReadLineOption -Colors @{
  ContinuationPromptColor = "`e[91m"
  DefaultTokenColor = "`e[91m"
}
```
```powershell
Get-PSReadLineOption
.....
ContinuationPromptColor : "`e[37m"
DefaultTokenColor : "`e[37m"
```

Am I doing something wrong?

Though I've listed Linux below the same is true for me on Windows 10 v1709 (also PowerShell 6.1.2).

All advice very gratefully received. :)

Environment data
----------------

PS version: 6.1.2
PSReadline version: 2.0.0-beta3
os: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
PS file version:

**Comment by lzybkr** [comment]
The valid keys are documented [here](https://github.com/lzybkr/PSReadLine/blob/master/docs/Set-PSReadLineOption.md#-colors) - note that you don't specify `Colors` in the key.

The output of `Get-PSReadLineOption` is misleading here, I'll have to think about how that could be improved.

**Comment by raisin-loaf** [comment]
Thanks so much for the fast reply. And here I was genuinely thinking I'd read the documentation (the in-line documentation, at least). 🙂 

I suspected I might've had the keys wrong cause I tested with garbage and the cmdlet didn't complain. Perhaps some form of validation would be useful? If I were a better coder I'd submit a PR.

Sorry to have troubled you with this, and thanks again! 👍

**Comment by lzybkr** [comment]
Oh, I think you've found a real issue - the formatting mislead you. I'm keeping the issue open to address the issues you've raised:

* Color keys should be validated
* Get-PSReadLineOption output should not use keys that are not valid.

**Comment by raisin-loaf** [comment]
On a related note, it seems that even after setting all the colours available there are certain elements that still blend into the background (like `bck-i-search:` and the interactive prompt text that changes when there's a parse error). Is it possible to alter those colours too?

**Comment by lzybkr** [comment]
Feel free to open another issue for hard to read text like `bck-i-search:`. There is no setting, but it tries to use `Console.ForegroundColor` and `Console.BackgroundColor`, which return `-1` on Linux and we then default to `ConsoleColor.Gray`.

When the prompt changes to show an error, the `Error` color is used.

**Comment by StevenBucher98** [comment]
Closing to track in #3601
