### ISSUE TITLE
Clear screen using Ctrl+L is misbehaving when using the new console host in Windows 10 1809

### ISSUE THREAD

**Issue by DavidZidar** [PowerShell/PSReadLine#851]
Ever since upgrading to Windows 10 1809 clearing the screen using Ctrl+L no longer works as expected. I have observed the same behavior on at least 3 separate machines so the problem is easily reproduced.

## Steps to reproduce
1. Upgrade to Windows 10 1809
2. Launch PowerShell or PowerShell Core
3. Clear the console using Ctrl+L

Example:
```
ls
[Ctrl+L]
ls
```

## Observed behavior
When I press Ctrl+L the screen is cleared as expected but as soon as type any character the scroll position is reverted and all text comes back.

## Expected behavior
Screen should remain cleared even when I start typing again.

## Workarounds
* Typing `clear` actually properly clears the buffer and does not suffer from this problem
* Pressing enter after Ctrl+L seems to lock the scroll position
* Checking "Use legacy console" in the console host settings seems to restore the normal behavor

## Notes
WSL does not suffer from this problem even using the new console host.

**Comment by rkeithhill** [comment]
I can repro that.

**Comment by Boboss74** [comment]
It seems related

https://github.com/lzybkr/PSReadLine/issues/854#issuecomment-462411250
> Are you using a non-en-US keyboard layout?

**Comment by amongonz** [comment]
I'm reproducing this alongside [this weird variant of #841](https://github.com/lzybkr/PSReadLine/issues/841#issuecomment-464353887), on Windows 10 1809.

@Boboss74 I'm using es-ES layout but I can't reproduce #854.

**Comment by lzybkr** [comment]
It seems this is a conhost bug, see https://github.com/PowerShell/PowerShell/issues/8870#issuecomment-464188918 which points to https://github.com/Microsoft/console/issues/302.

**Comment by oising** [comment]
Yeah, definitely conhost issue. The Clear-Host cmdlet works as expected as it uses the regular console API instead of a VT sequence.

**Comment by DavidZidar** [comment]
Now that Windows 10 1903 is finally released and I have updated three machines and can confirm that the update does indeed resolve the issue. Thanks for the help!
