### ISSUE TITLE
Index out of range after some key-up, key-down

### ISSUE THREAD

**Issue by arthubms** [PowerShell/PSReadLine#862]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
-----------------------------------------------------------------------
Last 200 Keys:
 ; Spacebar g e t - d a t e Enter
 c l s Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow Escape c o n n e c t Tab Enter
 UpArrow UpArrow UpArrow Enter
 c l s Enter
 UpArrow UpArrow Enter
 UpArrow LeftWindows Escape Escape UpArrow c l Escape c l s Enter
 UpArrow UpArrow Enter
 UpArrow DownArrow UpArrow UpArrow DownArrow DownArrow c l s Enter
 g i Backspace Backspace g o t Spacebar Backspace Backspace Backspace Backspace g i t Spacebar v l o n Backspace Backspace Backspace Backspace c l o n e Enter
 . Ctrl+Alt+< s e t - p i m Tab UpArrow UpArrow UpArrow Escape ½ Backspace Backspace Backspace I n v o k e - A z r e u Backspace Backspace Backspace u r e Escape Ctrl+Alt+4 r o l Tab Tab Spacebar Backspace UpArrow Escape Ctrl+Alt+4 s e t t i n UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow Escape Ctrl+Alt+4 s e t t i Tab n g s UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Escape

Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable\`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary\`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by SteveL-MSFT** [comment]
@arthubms can you confirm this repros for you with 2.0.0-beta5?

**Comment by arthubms** [comment]
Cannot repro anymore
