### ISSUE TITLE
Windows key press outputs ^@ to console

### ISSUE THREAD

**Issue by silverqx** [PowerShell/PSReadLine#864]
Environment data
----------------
PS version: 5.1.17763.316
PSReadline version: 2.0.0-beta3
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
When I press windows key, I get `^@` output in console, it happens, when I use en-cz keyboard layout, when I switch to en-us, so it behaves correctly. I'm using latest [nightly build](https://ci.appveyor.com/project/lzybkr/PSReadLine/branch/master/artifacts).

**Comment by SteveL-MSFT** [comment]
@silverqx does this repro with beta4 which should have better support for international keyboards?

**Comment by silverqx** [comment]
I have installed psreadline which is by default in windows 1903, get-module shows it's 2.0.0 version and I don't have this problem anymore.
