### ISSUE TITLE
Support xtermjs keymappings in Windows edit mode

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PSReadLine#877]
[xtermjs](https://github.com/xtermjs/xterm.js)-based terminal emulators are becoming more and more popular.

Here are some examples:
* vscode's terminal (crucial for the vscode-powershell extension)
* [hyper](https://Hyper.is)
* [Fluent](https://github.com/felixse/FluentTerminal)
* [Terminus](https://github.com/Eugeny/terminus)

And with conpty support in Windows, these will likely grow in popularity even more. And more xtermjs based terminals will pop up.

The is great to see but is a problem for PSReadLine for Windows because xtermjs-based terminals align closer with UNIX terminals and can't correctly support certain keybindings like:

<kbd>ctrl</kbd>+<kbd>space</kbd> - interpreted as <kbd>ctrl</kbd>+<kbd>@</kbd>
<kbd>ctrl</kbd>+<kbd>backspace</kbd> - interpreted as <kbd>ctrl</kbd>+<kbd>w</kbd>
etc (I think @rkeithhill knows a few others)

### Ask

Can we set these, and any other xtermjs anomalies, as the default keybindings for the `Windows` edit mode so that user's experience in these other terminals is what they expect in regular pwsh.exe?

In order to make sure it only gets applied to xtermjs-based terminals, @Tyriar will set TERM=xterm in node-pty by default on Windows and recommend to set xterm-256color on the process in the xterm.js repo (as that's more correct). We can then use TERM to apply these additional keybindings or not. (NOTE: we would check for either xterm or xterm-256color to cover our bases)

cc @SteveL-MSFT @rjmholt

**Comment by gwojan** [comment]
I like the idea of better support on Windows for the xtermjs emulators but seriously don't like the idea of setting with `TERM` because it messes with neovim support in the terminal.

I use neovim for git command line integration and setting `$env:VISUAL` for PSReadLine vi mode. Neovim chokes hard with `$env:TERM` set on Windows. After thinking a little more this would only be a problem if `$env:TERM` is being set...

**Comment by Tyriar** [comment]
> Neovim chokes hard with $env:TERM set on Windows

@gwojan any reason for this? Currently VS Code doesn't set `TERM` on Windows so this would be a change for us.

**Comment by lzybkr** [comment]
It should be safe to add these bindings by default in `Windows` mode without checking `TERM`. If a user has a custom binding, I think it will take precedence.

Note that we can't use <kbd>Ctrl</kbd>+<kbd>@</kbd> in Emacs mode - it's already bound.

**Comment by TylerLeonhardt** [comment]
Looks like we just need to add to [the default keybindings here](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/KeyBindings.cs#L173). @rkeithhill do you know of any others off the top of your head that I should add?

**Comment by rkeithhill** [comment]
I know of these three:
```
Set-PSReadLineKeyHandler -Chord 'Ctrl+w' -Function BackwardKillWord
Set-PSReadLineKeyHandler -Chord 'Alt+D' -Function KillWord
Set-PSReadLineKeyHandler -Chord 'Ctrl+@' -Function MenuComplete
```
That's not to say there aren't more.

**Comment by TylerLeonhardt** [comment]
I've added these in https://github.com/lzybkr/PSReadLine/pull/878
