### ISSUE TITLE
Enh Req: rejigger some default shortcuts to avoid use of Shift key

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#88]
This comes down to mapping a shortcut to a key versus a character.  For instance, on US keyboards the ? character is on the / key.  When I invoke a shortcut I tend to think of the key and not a character.  Something like ShowAllBindings is awesome but the shortcut "as invoked on a US keyboard" is Ctrl+Alt+Shift+/ (even though its specified as Ctrl+Alt+?).  That's kind of a handful.

What if you made the default shortcut be "Ctrl+/" or perhaps "Ctrl+Oem2"?  Yeah I don't know how that would play out on non-US keyboards.  At the very least maybe the ShowAllBindings shortcut is "Ctrl+?" which requires Ctrl+Shift+/ on the keyboard which is one less key press.  :-)

**Comment by lzybkr** [comment]
I'm going to close this - I think it's fixed, or at least I don't plan on more changes.  `ShowAllBindings` and `WhatIsKey` no longer show shift:

```
Alt+?: WhatIsKey - Show the key binding for the next chord entered
Ctrl+Alt+?: ShowKeyBindings - Show all key bindings
```
