### ISSUE TITLE
[fr_FR] Ctrl+_ vs Ctrl+8

### ISSUE THREAD

**Issue by springcomp** [PowerShell/PSReadLine#887]
I'm trying to fix some unit-tests that are currently failing.

In particular, the [SwapCharacters](https://github.com/lzybkr/PSReadLine/blob/905ab44ee3404c351e34f61334c5eddc8d65d9ab/test/BasicEditingTest.cs#L174) test uses the <kbd>Ctrl</kbd>+<kbd>underbar</kbd> in `Emacs` mode to perform **undo**. Although I can fix the test by using an alternate combination of <kbd>Ctrl</kbd>+<kbd>x</kbd>, <kbd>Ctrl</kbd>+<kbd>u</kbd> with the same meaning in `Emacs` and which has the benefit of being more portable, I would like to get to the bottom of this.

The <kbd>Ctrl</kbd>+<kbd>underbar</kbd> does not work in this particular case with a french keyboard layout. In fact, it seems that this combination sends scan codes more akin to a <kbd>Ctrl</kbd>+<kbd>8</kbd> combination.

So I'm not sure how to fix this by editing the `KeyInfo-fr-FR-windows.json` file or the keybindings in a portable way.

Any hints?
Would it be acceptable to fix the unit-tests by using the more portable key combination ?

**Comment by springcomp** [comment]
Never mind.

I ran the unit-tests incorrectly in a local PowerShell by switching the input language.
The correct way to test it first to swith the input language, and then, launch a new PowerShell window.

**Comment by lzybkr** [comment]
GUI applications don't need to restart to handle keyboard layout changes, but console applications may be forced to restart because of a bug in a Win32 api. PSReadLine tests hit that bug.

It's hard to say what the impact of the bug is, but the team responsible for the api is waiting for customer feedback before considering a fix.
