### ISSUE TITLE
Ctrl + C often enters "c" instead of copying to the clipboard

### ISSUE THREAD

**Issue by sba923** [PowerShell/PSReadLine#897]
I hate to say, but I have no idea as to how to reproduce / trigger this error.

Quite frequently, with 2.0.0 beta4, which I use _a lot_ in combination with VScode's PowerShell Preview extension, I encounter the following: all Ctrl+_letter_ combinations work, except for Ctrl+C which yields a "c" (and thus, of course, overwrites the very text I'm trying to copy).

I would've liked to use the old Ctrl+Ins equivalent, but this doesn't do anything... (I probably will open another issue for that).

So my current workaround is: Ctrl+X Ctrl+V ;-)

## Environment
At this very moment, the issue is present within VScode, with the following environment:
````
PS version: 6.2.0
PSReadline version: 2.0.0-beta4
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 6.2.0
````

**Comment by lzybkr** [comment]
@TylerLeonhardt - do you know if vscode handles <kbd>Ctrl+c</kbd> or if it passes it through?

**Comment by SeeminglyScience** [comment]
<kbd>Ctrl+c</kbd> comes across in winpty as ```"`u{0003}"``` (or `([char]3)` on Windows PowerShell).  Looks like a control shifted capital <kbd>C</kbd>.  We accounted for it in the `PSHost`, but I didn't think of it when @TylerLeonhardt's PR came through.

**Comment by sba923** [comment]
What PR are you referring to? I'm under the impression that this got broken with version 2.0.2 a.k.a. Preview 3 of the VScode PowerShell extension... and this `Ctrl+c` basically _never_ works in that configuration. Do you concur?

**Comment by SeeminglyScience** [comment]
@sba923 This one: #878

winpty just sends input a little bit differently.  <kbd>Ctrl+c</kbd> should work if you put this in your `$profile`:

```powershell
Set-PSReadLineKeyHandler -Key ([char]0x03) -Function CopyOrCancelLine
```

If that doesn't work you may need to add this to your VSCode `settings.json`:

```json
"terminal.integrated.commandsToSkipShell": [],
```

**Comment by sba923** [comment]
As soon as I add the `Set-PSReadLineKeyHandler` to my profile, hitting "c" at a PowerShell prompt (console host or VScode) yields... `Ctrl+C`

**Comment by daxian-dbw** [comment]
There has been a lot improvements in PowerShell VSCode extension regarding support to PSReadLine in the integrated console.
As shown below, `Ctrl+c` works as expected with the 2020.6.0 version of the PowerShell VSCode extension. Given that, I'm closing this issue.

![tabcom2](https://user-images.githubusercontent.com/127450/96287196-66d9e880-0f96-11eb-99b0-1fad9bd817c9.gif)

**Comment by SeeminglyScience** [comment]
@daxian-dbw yeah at some point VSCode was changed to pass the <kbd>Ctrl</kbd> + <kbd>C</kbd> through to the shell if it knows that the shell is PowerShell. Even works with the non-extension PowerShell terminal 🎉
