### ISSUE TITLE
New Beta release

### ISSUE THREAD

**Issue by musm** [PowerShell/PSReadLine#900]
There's a enough important fixes for a new Beta. Any chance we could see a release soon?

**Comment by SteveL-MSFT** [comment]
https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta4

**Comment by musm** [comment]
awesome thanks

**Comment by musm** [comment]
should probably also update the release version on GitHub

**Comment by lzybkr** [comment]
@daxian-dbw - you'll want to push a tag for this release and probably change the `Publish` task in `PSReadLine.build.ps1` to also push the release tag for future releases.

**Comment by daxian-dbw** [comment]
Will do, let me first merge my changes to the release build yaml file.

**Comment by daxian-dbw** [comment]
Pushing a tag should happen before publishing the module. I will make changes to the build scripts to make sure orders are right next time.
