### ISSUE TITLE
Considerm moving repository to the PowerShell organisation

### ISSUE THREAD

**Issue by ExE-Boss** [PowerShell/PSReadLine#904]
Since **PSReadLine** is effectively the standard **PowerShell** prompt implementation, it might be a good idea to move it to the @PowerShell organisation.

## See also:
- https://help.github.com/articles/transferring-a-repository

**Comment by lzybkr** [comment]
Curious timing on opening this issue - it was planned to coincide with the Beta4 release which we just published - but it is done.
