### ISSUE TITLE
[pre-release] Colors Error setting not being applied

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/PSReadLine#909]
Environment data
----------------

```powershell
PS version: 5.1.17763.316
PSReadline version: 2.0.0-beta3
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------
1. `Set-PSReadlineOption -Colors @{ "error" = ConsoleColor::DarkCyan }
1. Call `Get-PSReadlineOption` and see the Error is set to nothing.
1. Use `Set-PSReadLineOption -Colors @{ "error" = "#1a570e"}`
1. Call `Get-PSReadlineOption` and see the Error is set to `"$([char]0x1b)[38;2;26;87;14m"`

In both cases I cause an error and the output is still showing the default red color text.

Is there something I'm missing to get the error text to display in something other than red?

**Comment by lzybkr** [comment]
Regarding 1 - that should be:

```powershell
Set-PSReadlineOption -Colors @{ "error" = [ConsoleColor]::DarkCyan }
```

This setting only affects PSReadLine - it does not change PowerShell's error color, e.g. when a command writes an error or throws an exception.

In PSReadLine, you normally see this color in your prompt, but there are a few other places you might see this color.

**Comment by wsmelton** [comment]
What purpose is there in changing the error color only for psreadline?

**Comment by lzybkr** [comment]
The error color isn't exposed as a proper api in PowerShell, so I never really considered it.

Yes, you can set `$host.PrivateData.ErrorForegroundColor`, but only in the console host - there are other hosts that use PSReadLine but do not have this proprerty.

To make matters more complicated, the PrivateData properties only support ConsoleColor - so it would be impossible to use an arbitrary VT sequence.
