### ISSUE TITLE
Completion menu background color breaks if completion text contains ESC sequence

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PSReadLine#915]
Environment data
----------------
```
PS version: 6.1.3
PSReadline version: 2.0.0-beta3
os: Darwin Felix-MacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
The property 'VersionInfo' cannot be found on this object. Verify that the property exists.
At line:14 char:25
+ ...  file version: $((dir $pshome\p*[hl].exe).VersionInfo.FileVersion)" }
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at <ScriptBlock>, <No file>:14
at <ScriptBlock>, <No file>:1
PS file version:
```

Steps to reproduce or exception report
--------------------------------------

This completion is for GitHub issues and uses ANSI colors to make the text prettier and communicate the issue state (similar to how GitHub issue autocomplete does it:

```powershell
"`e[32mⓘ`e[0m 3899`t`e[3mIt is not clear that externalURL must be configured`e[0m"
```

The MenuComplete function also applies a black background to the selected item, but doesn't check if the title contains any other sequences, so any escape sequence will reset the background color:

![image](https://user-images.githubusercontent.com/10532611/57457468-e165eb00-726f-11e9-8714-7da6a5cf0ace.png)

I would expect it to repeat its background color sequence after all instances of `ESC[0m` found in the title string.

**Comment by felixfbecker** [comment]
It would also be nice if the selected item was not just indicated by background color, but also by a moving ● before the item. This would make it possible to use the background color too, e.g. for selecting GitHub labels:

![image](https://user-images.githubusercontent.com/10532611/57458925-841f6900-7272-11e9-9e2f-848f8668369b.png)

**Comment by StevenBucher98** [comment]
Is this still happening for you in PSReadLine 2.3.4?
