### ISSUE TITLE
Commit MenuComplete option with Tab instead of Enter

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PSReadLine#916]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

I have committing autocompletion results with <kbd>tab</kbd> in my muscle memory, but that just switches to the next selection. Only <kbd>return</kbd> selects items. Is there a way to configure that?

**Comment by felixfbecker** [comment]
I tried 
```powershell
Set-PSReadLineKeyHandler -Key Tab -Function AcceptLine
```
but that didn't work (and it would probably be wrong because Tab would then also execute commands)

**Comment by lzybkr** [comment]
It is not configurable, see the implementation [here](https://github.com/PowerShell/PSReadLine/blob/33c22915e9d45439ff4a787cc458f140d04090d0/PSReadLine/Completion.cs#L895).

**Comment by vexx32** [comment]
I think that one sorely needs a switch statement, @lzybkr 😂
