### ISSUE TITLE
None of the YankLastArg shortcuts work on WSL Ubuntu

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#920]
Environment data
----------------

```
PS version: 6.2.0
PSReadline version: 2.0.0-beta4
os: Linux Keith-Yoga2 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
PS file version:
```

Steps to reproduce or exception report
--------------------------------------
With beta4 installed in WSL Ubuntu 18.04 with Powershell Core 6.2.0 installed:
```
~$ pwsh -noprofile
PS /home/foo> dir /etc/hosts
...
PS /home/foo> gc <press alt+.>
```
That should put copy the path `/etc/hosts` from the previous command onto the command line but it doesn't.  Not having this default shortcut work is a bummer.

**Comment by lzybkr** [comment]
This is a known issue with the CLR: https://github.com/dotnet/corefx/issues/12336

**Comment by daxian-dbw** [comment]
I have verified that this works with PSReadLine 2.3.0-beta0 in PowerShell 7.3.0 on WSL2 Ubuntu 18.04.
