### ISSUE TITLE
Detect and scrub sensitive information in history

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#934]
There are a number of tools that reads PSReadLine's history file to look for passwords provided in cleartext.  We should see if we can have an option (perhaps default) to detect and scrub any content that could be considered sensitive.

**Comment by SteveL-MSFT** [comment]
We can probably start with some heuristics based on well known patterns or commands and also treat base64 encoded content as sensitive.

**Comment by rkeithhill** [comment]
A long sequence of hexadecimal digits is a decent indication of a token/api key.  

BTW along these lines, I've had this [Optimize-PSReadlineHistory](https://gist.github.com/rkeithhill/4099bfd8420eed0e6dbc) command I've used for years to whack down the size of my history file.  Contrary to what you might believe, it accumulates a lot of duplicate commands.  I've been wanting to contribute this back to PSReadLine.  Is this something, you might be interested in?

One thing that has held me back on PR'ing this before is figuring out the locking mechanism between multiple PS sessions all writing to the same file.  For now, with the command above, I close all PS sessions and remove PSRL from the one session I run the command from.

**Comment by lzybkr** [comment]
First - there is an existing feature that helps avoid adding commands to the history file - I use something like this:

```powershell
Set-PSReadLineOption -AddToHistoryHandler {
    param([string]$line)
    return $line[0] -ne ' ' -and $line.Length -gt 3
}
```

This says - if the command starts with whitespace or is 3 or less characters long, don't add the command to history.

As for the history file itself - I've long wanted to change the format and include other useful things, e.g. to [populate PowerShell history](https://github.com/PowerShell/PSReadLine/issues/120).

Changing the format could provide a nice opportunity to address this issue as well. For example, maybe we can optionally use encryption.

**Comment by rkeithhill** [comment]
Heh, I use:
```
    AddToHistoryHandler           = {
        param([string]$line)
        return $line.Length -gt 3 -and $line[0] -ne ' ' -and $line[0] -ne ';'
    }
```
Just because for some reason I remember to use `;`, less so with a space char.

**Comment by knilecrack** [comment]
@lzybkr I think optional encryption would be super good. What do you think what should be good approach?

**Comment by lzybkr** [comment]
@knilecrack - I'm not aware of any good cross-platform encryption options, and ideally any change here would support all platforms.

One option on Windows is to use [EFS](https://docs.microsoft.com/en-us/windows/win32/fileio/file-encryption). It's nice because decryption doesn't require a password/secret - your Windows credentials protect the secret, but then again if the account is compromised, then so is your history.

**Comment by SteveL-MSFT** [comment]
For now, we can start with what @LeeHolmes proposes https://twitter.com/Lee_Holmes/status/1172640465767682048 by default.
