### ISSUE TITLE
Tab expansion of paths that contain wildcard * 

### ISSUE THREAD

**Issue by dresken** [PowerShell/PSReadLine#94]
Directory structure:
c:\temp\directory\file1.txt
c:\temp\anotherdirectory\file2.txt

We're using Set-PSReadlineKeyHandler -Key Tab -Function Complete

Type the following into Powershell 
c:\temp*\TAB results in "c:\temp\"
Pressing TAB again shows "file1.txt file2.txt" as options
Pressing TABx2 then show "directory anotherdirectory"

I'm not sure what behaviour to expect - but definitely not what we're experiencing
By default powershell cycles through all files in all directories
and Bash doesn't really do anything useful but at least doesn't remove the wildcard from the entered line.

Cheers

**Comment by lzybkr** [comment]
I just tried this now and I think it's working in an intuitive way. Feel free to try it with the latest build and reopen the issue if you aren't seeing reasonable behavior.
