### ISSUE TITLE
PowerShell 7-preview1 Suggestions remians on screen even after selecting an item

### ISSUE THREAD

**Issue by avestura** [PowerShell/PSReadLine#946]
![UqoPy4ryiP](https://user-images.githubusercontent.com/9091958/59467575-4602ff80-8e45-11e9-91a5-704e7b483990.gif)

# Steps to reproduce
Use any suggestion with many items, for example, write `[System.T` and press `ctrl+space`
in console hosts like ConEmu or Visual Studio Code Terminal, then choose an item. (This doesn't happen in the main PowerShell host)

# Expected behavior
The item should be auto-completed and then hide from the screen.

# Actual behavior
The item gets selected but remains on screen.

# Environment data

```
PS version: 7.0.0-preview.1
PSReadline version: 2.0.0-beta4
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
BufferWidth: 193
BufferHeight: 32766
```

**Comment by joeyaiello** [comment]
I think I set up my buffer correctly, but I'm not getting a repro on ConEmu (also tried with 122x29 like you have in your screenshot):

![image](https://user-images.githubusercontent.com/1255187/59721799-f9b61780-91d6-11e9-8364-df635662c734.png)

**Comment by avestura** [comment]
I updated ConEmu to the latest preview version (190526-preview) and it seems the issue fixed. But it still happens in VSCode terminal.

screencast:

![Q7EwZTsusY](https://user-images.githubusercontent.com/9091958/59728335-e0e94880-924e-11e9-89e5-733a177732f5.gif)

**Comment by avestura** [comment]
It still happens in the latest version of ConEmu in some cases tho (:

![l9FFPK2Emy](https://user-images.githubusercontent.com/9091958/59948047-365a6b00-9484-11e9-8778-732ee7107198.gif)

**Comment by avestura** [comment]
Well, It seems this happens on every other host, including PowerShell default host. I first thought it might be some PSReadLine tweaker or something is causing this behaviour, so I launched PS with `-NoProfile` arg, but the issue persists.

PowerShell with `NoProfile` enabled:
![image](https://user-images.githubusercontent.com/9091958/59960168-726beb00-94d9-11e9-9890-194df11010ea.png)

Windows Terminal:
![image](https://user-images.githubusercontent.com/9091958/59960175-80217080-94d9-11e9-88ee-97f4e80bdfa4.png)

**Comment by daxian-dbw** [comment]
I can repro this in beta4.
