### ISSUE TITLE
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by petritbahtiri123** [PowerShell/PSReadLine#954]
[Bug.txt](https://github.com/PowerShell/PSReadLine/files/3347437/Bug.txt)

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by petritbahtiri123** [comment]
[Bug.txt](https://github.com/PowerShell/PSReadLine/files/3347443/Bug.txt)

**Comment by daxian-dbw** [comment]
I assume this is a duplicate of #953.
