### ISSUE TITLE
Exception while creating Azure MI using powershell

### ISSUE THREAD

**Issue by Shashank621** [PowerShell/PSReadLine#955]
Environment data
----------------
When trying to create Azure MI using powershell script given in [This BOL Document](https://docs.microsoft.com/en-us/azure/sql-database/scripts/sql-database-create-configure-managed-instance-powershell) following error is displayed while creating NSG the command is below

**Code that is giving issue**

`Get-AzNetworkSecurityGroup `
                      -ResourceGroupName $resourceGroupName `
                      -Name "myNetworkSecurityGroupMiManagementService" `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 100 `
                      -Name "allow_management_inbound" `
                      -Access Allow `
                      -Protocol Tcp `
                      -Direction Inbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix * `
                      -DestinationPortRange 9000,9003,1438,1440,1452 `
                      -DestinationAddressPrefix * `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 200 `
                      -Name "allow_misubnet_inbound" `
                      -Access Allow `
                      -Protocol * `
                      -Direction Inbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix $miSubnetAddressPrefix `
                      -DestinationPortRange * `
                      -DestinationAddressPrefix * `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 300 `
                      -Name "allow_health_probe_inbound" `
                      -Access Allow `
                      -Protocol * `
                      -Direction Inbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix AzureLoadBalancer `
                      -DestinationPortRange * `
                      -DestinationAddressPrefix * `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 1000 `
                      -Name "allow_tds_inbound" `
                      -Access Allow `
                      -Protocol Tcp `
                      -Direction Inbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix VirtualNetwork `
                      -DestinationPortRange 1433 `
                      -DestinationAddressPrefix * `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 1100 `
                      -Name "allow_redirect_inbound" `
                      -Access Allow `
                      -Protocol Tcp `
                      -Direction Inbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix VirtualNetwork `
                      -DestinationPortRange 11000-11999 `
                      -DestinationAddressPrefix * `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 4096 `
                      -Name "deny_all_inbound" `
                      -Access Deny `
                      -Protocol * `
                      -Direction Inbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix * `
                      -DestinationPortRange * `
                      -DestinationAddressPrefix * `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 100 `
                      -Name "allow_management_outbound" `
                      -Access Allow `
                      -Protocol Tcp `
                      -Direction Outbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix * `
                      -DestinationPortRange 80,443,12000 `
                      -DestinationAddressPrefix * `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 200 `
                      -Name "allow_misubnet_outbound" `
                      -Access Allow `
                      -Protocol * `
                      -Direction Outbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix * `
                      -DestinationPortRange * `
                      -DestinationAddressPrefix $miSubnetAddressPrefix `
                      | Add-AzNetworkSecurityRuleConfig `
                      -Priority 4096 `
                      -Name "deny_all_outbound" `
                      -Access Deny `
                      -Protocol * `
                      -Direction Outbound `
                      -SourcePortRange * `
                      -SourceAddressPrefix * `
                      -DestinationPortRange * `
                      -DestinationAddressPrefix * `
                      | Set-AzNetworkSecurityGroup`

**The exception that comes is** 

> Oops, something went wrong.  Please report this bug with the details below.
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
> -----------------------------------------------------------------------
> Last 200 Keys:
> ```
>  ` Enter
>  Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space - S o u r ce A d d r e s s P r e f i x Space * Space ` Enter
>  Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space - D e s t in a t i o n P o r t R a n g e Space * Space ` Enter
>  Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space - D e s t in a t i o n A d d r e s s P r e f i x Space * Space ` Enter
>  Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space | Space S et - A z N e t w o r k S e c u r i t y G r o u p Enter
> 
> ```
> 
> Exception:
> ```
> System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
> Parameter name: top
> Actual value was -68.
>    at System.Console.SetCursorPosition(Int32 left, Int32 top)
>    at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
>    at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
>    at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
>    at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
>    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
> ```
> 
> 
**Error That comes in PS**

> New-AzSqlInstance : Long running operation failed with status 'Failed'. Additional Info:'Create Managed Instance failed. Provided virtual network subnet is located in eastus, which is a different region than the one you are provisioning Managed Instance in (westus2). To create a VNET-joined Managed Instance, the instance and the virtual network have to be located in the same region.'
> At line:1 char:1
> + New-AzSqlInstance -Name $instanceName `
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : CloseError: (:) [New-AzSqlInstance], CloudException
> + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.ManagedInstance.Cmdlet.NewAzureSqlManagedInstance
> 
> 

Steps to reproduce or exception report
--------------------------------------
1. The issue can be reproduced easily
2. Log into Azure portal and use the script to create MI.
3 The script automatically creates RG, Vnet and other associated network components
4. When you reach creating NSG it fails with exception

**Comment by Shashank621** [comment]
> ## Environment data
> When trying to create Azure MI using powershell script given in [This BOL Document](https://docs.microsoft.com/en-us/azure/sql-database/scripts/sql-database-create-configure-managed-instance-powershell) following error is displayed while creating NSG the command is below
> 
> **Code that is giving issue**
> 
> `Get-AzNetworkSecurityGroup `
> -ResourceGroupName $resourceGroupName `-Name "myNetworkSecurityGroupMiManagementService"`
> | Add-AzNetworkSecurityRuleConfig `-Priority 100`
> -Name "allow_management_inbound" `-Access Allow`
> -Protocol Tcp `-Direction Inbound`
> -SourcePortRange * `-SourceAddressPrefix *`
> -DestinationPortRange 9000,9003,1438,1440,1452 `-DestinationAddressPrefix *`
> | Add-AzNetworkSecurityRuleConfig `-Priority 200`
> -Name "allow_misubnet_inbound" `-Access Allow`
> -Protocol * `-Direction Inbound`
> -SourcePortRange * `-SourceAddressPrefix $miSubnetAddressPrefix`
> -DestinationPortRange * `-DestinationAddressPrefix *`
> | Add-AzNetworkSecurityRuleConfig `-Priority 300`
> -Name "allow_health_probe_inbound" `-Access Allow`
> -Protocol * `-Direction Inbound`
> -SourcePortRange * `-SourceAddressPrefix AzureLoadBalancer`
> -DestinationPortRange * `-DestinationAddressPrefix *`
> | Add-AzNetworkSecurityRuleConfig `-Priority 1000`
> -Name "allow_tds_inbound" `-Access Allow`
> -Protocol Tcp `-Direction Inbound`
> -SourcePortRange * `-SourceAddressPrefix VirtualNetwork`
> -DestinationPortRange 1433 `-DestinationAddressPrefix *`
> | Add-AzNetworkSecurityRuleConfig `-Priority 1100`
> -Name "allow_redirect_inbound" `-Access Allow`
> -Protocol Tcp `-Direction Inbound`
> -SourcePortRange * `-SourceAddressPrefix VirtualNetwork`
> -DestinationPortRange 11000-11999 `-DestinationAddressPrefix *`
> | Add-AzNetworkSecurityRuleConfig `-Priority 4096`
> -Name "deny_all_inbound" `-Access Deny`
> -Protocol * `-Direction Inbound`
> -SourcePortRange * `-SourceAddressPrefix *`
> -DestinationPortRange * `-DestinationAddressPrefix *`
> | Add-AzNetworkSecurityRuleConfig `-Priority 100`
> -Name "allow_management_outbound" `-Access Allow`
> -Protocol Tcp `-Direction Outbound`
> -SourcePortRange * `-SourceAddressPrefix *`
> -DestinationPortRange 80,443,12000 `-DestinationAddressPrefix *`
> | Add-AzNetworkSecurityRuleConfig `-Priority 200`
> -Name "allow_misubnet_outbound" `-Access Allow`
> -Protocol * `-Direction Outbound`
> -SourcePortRange * `-SourceAddressPrefix *`
> -DestinationPortRange * `-DestinationAddressPrefix $miSubnetAddressPrefix`
> | Add-AzNetworkSecurityRuleConfig `-Priority 4096`
> -Name "deny_all_outbound" `-Access Deny`
> -Protocol * `-Direction Outbound`
> -SourcePortRange * `-SourceAddressPrefix *`
> -DestinationPortRange * `-DestinationAddressPrefix *`
> | Set-AzNetworkSecurityGroup`
> 
> **The exception that comes is**
> 
> > ## Oops, something went wrong.  Please report this bug with the details below.
> > Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
> > Last 200 Keys:
> > ```
> >  ` Enter
> >  Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space - S o u r ce A d d r e s s P r e f i x Space * Space ` Enter
> >  Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space - D e s t in a t i o n P o r t R a n g e Space * Space ` Enter
> >  Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space - D e s t in a t i o n A d d r e s s P r e f i x Space * Space ` Enter
> >  Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space | Space S et - A z N e t w o r k S e c u r i t y G r o u p Enter
> > ```
> > 
> > 
> > Exception:
> > ```
> > System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
> > Parameter name: top
> > Actual value was -68.
> >    at System.Console.SetCursorPosition(Int32 left, Int32 top)
> >    at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
> >    at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
> >    at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
> >    at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
> >    at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
> >    at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
> >    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
> > ```
> 
> **Error That comes in PS**
> 
> > New-AzSqlInstance : Long running operation failed with status 'Failed'. Additional Info:'Create Managed Instance failed. Provided virtual network subnet is located in eastus, which is a different region than the one you are provisioning Managed Instance in (westus2). To create a VNET-joined Managed Instance, the instance and the virtual network have to be located in the same region.'
> > At line:1 char:1
> > 
> > * New-AzSqlInstance -Name $instanceName `
> > * 
> > * CategoryInfo          : CloseError: (:) [New-AzSqlInstance], CloudException
> > * FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.ManagedInstance.Cmdlet.NewAzureSqlManagedInstance
> 
> ## Steps to reproduce or exception report
> 1. The issue can be reproduced easily
> 2. Log into Azure portal and use the script to create MI.
>    3 The script automatically creates RG, Vnet and other associated network components
> 3. When you reach creating NSG it fails with exception

**Comment by Shashank621** [comment]
Sorry by mistake closed this, please look into the issue

**Comment by daxian-dbw** [comment]
@Shashank621 What was the environment that you saw this exception happening? Were you running in Cloud Shell?
