### ISSUE TITLE
I can`t install php storm with JetBrains_KeyfileMaker.jar

### ISSUE THREAD

**Issue by CrazyEvilDog** [PowerShell/PSReadLine#956]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
Последние клавиши 1:
 Ctrl+v

Исключение:
System.ArgumentOutOfRangeException: Значение должно быть больше или равно нулю и меньше, чем размер буфера в данной размерности.
Имя параметра: top
Фактическое значение было -1.
   в System.Console.SetCursorPosition(Int32 left, Int32 top)
   в Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   в Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   в Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Program Files\JetBrains\WebStorm 2018.1.4\jre64\bin> java -jar JetBrains_KeyfileMaker.jar

**Comment by daxian-dbw** [comment]
Close this one as a duplicate of #950
