### ISSUE TITLE
Tab expansion of $

### ISSUE THREAD

**Issue by dresken** [PowerShell/PSReadLine#96]
Tab expansion of $ behaves a bit strangely. Mainly erasing characters instead of display matches. Matches are a little strange too.

We're using Set-PSReadlineKeyHandler -Key Tab -Function Complete

$env TAB = $
$env TAB TAB = list of all $env variables (without prepending $)
$env:computer TAB = completes correctly (that is, if it is unique enough and matches one) 

On a similar note:
$ TAB TAB = list of all $ variables (including everything under $env:) (without prepending $ or some (but not all) post pending : )

**Comment by pecigonzalo** [comment]
Similar to : #126 

I would like to add that doing 
$env:P TAB = List of posibilities but clears the $env:P to $
$env:Pa TAB = Correct list of possibilities: Path     PATHEXT and does not clear the $env:Pa
$env:Pat TAB = Completes to the only posibility $env:Path

**Comment by lzybkr** [comment]
I think this was fixed in https://github.com/lzybkr/PSReadLine/pull/515 - at any rate, it doesn't repro anymore.
