### ISSUE TITLE
Some glyphs are not rendered correctly on a PowerShell prompt

### ISSUE THREAD

**Issue by Tragetaschen** [PowerShell/PSReadLine#965]
Environment data
----------------

```
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.239 (WinBuild.160101.0800)
PS file version: 10.0.18362.239 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```
But I'm seeing the issue since build 17763

I had reported it using the Feedback-Hub ages ago and more recently against the new Windows Terminal (https://github.com/microsoft/terminal/issues/1958) and was redirected here.

Steps to reproduce or exception report
--------------------------------------
Open a PowerShell and type `123¹²³` on the prompt (or paste it)

The output on the prompt will render as if I had typed `1231²3`. However in error messages, everything is rendered correctly.

![image](https://user-images.githubusercontent.com/1947968/61175209-a784ce00-a5ab-11e9-84cc-a1b7991df18a.png)

**Comment by daxian-dbw** [comment]
Have you tried 2.0.0-beta4? I cannot repro it with beta4 PSReadLine.

![image](https://user-images.githubusercontent.com/127450/61257424-d0c96980-a725-11e9-8930-c890d432ca0f.png)

**Comment by Tragetaschen** [comment]
I'm using what's shipping with in-box with Windows and tried some of the commands from the README with no success. So please bear with my ignorance if I'm missing something probably obvious.

But: how? :)

**Comment by daxian-dbw** [comment]
The `PSReadLine` module is also released to PowerShell Gallery, see the latest version here: https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta4
You can install the latest beta4 pre-release and give it a try.

I will close the issue as `Fixed`. Feel free to re-open if you still see it with the beta4 version PSReadLine.

**Comment by Tragetaschen** [comment]
Ok, I finally managed to install beta4, but only after following [this](https://evotec.xyz/install-module-a-parameter-cannot-be-found-that-matches-parameter-name-allowprerelease/). This is quite a rough experience :-(

I can confirm that beta4 fixes this issue.

Out of curiosity: I had reported this eight months ago using Feedback Hub: https://aka.ms/AA5mwyy
Did you as a team ever get a notification or is Feedback Hub a black hole?

**Comment by daxian-dbw** [comment]
I didn't know of any notifications from the Feedback Hub. It's most efficient to open issues directly here.

**Comment by Tragetaschen** [comment]
Well, if you happen to know where "here" is beforehand :)

**Comment by daxian-dbw** [comment]
True. Sorry for the inconvenience @Tragetaschen.
