### ISSUE TITLE
c d Space " d : \ 学 习 资 料 \ 就 业 班 资 料 \ v u e \ v u e 项 目 5 - 1 0 天 资 料 \ 7 . v u e - 项 目 实 战 d a y 5 \ c o d e

### ISSUE THREAD

**Issue by woshihaorenbushihuairen** [PowerShell/PSReadLine#966]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by daxian-dbw** [comment]
Closing this as there is no information about the issue.
