### ISSUE TITLE
Allow Set-PSReadLineKeyHandler to redefine keys for Vi command mode

### ISSUE THREAD

**Issue by partdavid** [PowerShell/PSReadLine#972]
As far as I can tell, there is no way to redefine the key handler for a Vi key (a key accessible in command mode). When invoking Get-PSReadLineHandler, these keys are displayed with sharp braces, but this cannot be used to redefine them.

For example, when in Vi command mode, I want the `s` key to invoke the `ForwardChar` function, not `ViInsertWithDelete`. If I examine the current binding, I see that this function is bound to `<s>`:

```
PS> Get-PSReadLineKeyHandler | ?{ $_.Function -eq 'ViInsertWithDelete' }


Basic editing functions
=======================
Key Function           Description
--- --------           -----------
<s> ViInsertWithDelete Deletes the current character and switches to insert mode.
```

If I try to set a handler for this in the obvious way, I get an error:

```
PS> Set-PSReadLineKeyHandler -Key '<s>' -Function ForwardChar
Set-PSReadLineKeyHandler : Unrecognized key '<s>'. Please use a character literal or a well-known key name from the System.ConsoleKey enumeration.
At line:1 char:1
+ Set-PSReadLineKeyHandler -Key '<s>' -Function ForwardChar
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Set-PSReadLineKeyHandler], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.SetPSReadLineKeyHandlerCommand
```

This operation corresponds with placing the following in `.inputrc` for readline:

```
set keymap vi-command
"s": forward-char
```

Environment data
----------------

```
PS version: 6.2.1
PSReadline version: 2.0.0-beta3
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 6.2.1.0
BufferWidth: 132
BufferHeight: 3000
```

**Comment by SeeminglyScience** [comment]
Try this:

```powershell
Set-PSReadLineKeyHandler -Key s -Function ForwardChar -ViMode Command
```

**Comment by partdavid** [comment]
Thank you, brilliant. I missed the relevance of this option in the help for Set-PSReadLineKeyHandler.

**Comment by stanlyonhack** [comment]
> Try this:
> 
> ```powershell
> Set-PSReadLineKeyHandler -Key s -Function ForwardChar -ViMode Command
> ```

How could you put a chord of three letters?

Example: `Set-PSReadLineKeyHandler -Key 'c,i,w' -Function ForwardChar -ViMode Command`
