### ISSUE TITLE
System.Text.EncoderFallbackException无法将位于索引 80 处的 Unicode 字符 \uDA96 转换为指定的代码页。

### ISSUE THREAD

**Issue by firework30** [PowerShell/PSReadLine#975]
异常:
System.Text.EncoderFallbackException: 无法将位于索引 80 处的 Unicode 字符 \uDA96 转换为指定的代码页。
   在 System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   在 System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   在 System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   在 System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   在 System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   在 System.IO.StreamWriter.Dispose(Boolean disposing)
   在 System.IO.TextWriter.Dispose()
   在 Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass65_0.<WriteHistoryRange>b__0()
   在 Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   在 Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by hanzhongyuan** [comment]
处理一下内容的编码格式就可以了
