### ISSUE TITLE
MenuComplete garbled when cursor is at bottom of terminal

### ISSUE THREAD

**Issue by IntelOrca** [PowerShell/PSReadLine#976]
When using MenuComplete at the bottom of the window / buffer, the output is garbled. I only experience this in Windows Terminal or a terminal inside VSCode. When using conhost the behaviour is fine.

![9Q0C6lVtuw](https://user-images.githubusercontent.com/1482259/61860142-6224a280-aec1-11e9-831c-33f541824128.gif)

Environment data
----------------
```powershell
PS version: 7.0.0-preview.2
PSReadline version: 2.0.0-beta4
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
```

Steps to reproduce or exception report
--------------------------------------
Using Windows Terminal or a terminal inside VSCode, enable menu complete for TAB and then use tab completion with the cursor position on the last line of the buffer / window.

#598 seems similar but that was closed a long time ago.

**Comment by msftrncs** [comment]
Also, this may be similar to #946.

**Comment by IntelOrca** [comment]
I have just tried 2.0.0-beta5 and I no longer get the issue. 👍

**Comment by daxian-dbw** [comment]
@IntelOrca Thanks for echoing back after switching to `2.0.0-beta5`. I will close this issue then.
