### ISSUE TITLE
Unable to start `pwsh` on Mac due to System.IO.IOException

### ISSUE THREAD

**Issue by draproctor** [PowerShell/PSReadLine#988]
Error I receive when I start `pwsh`:

### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 7.0.0-preview.2
OS: Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Last 0 Keys
```

```

### Exception
```
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_1159123179'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------
I moved my PowerShell profile to my desktop just in case and the issue remains. Uninstalling and reinstalling pwsh did not change the error.

Environment data
----------------
I'm unable to provide environmental data because I am unable to run anything at the prompt. This is for pwsh 6.2.2. 

Steps to reproduce or exception report
--------------------------------------
Run `pwsh`.

Please let me know what other data I could provide for this error. I don't have much to go on.

**Comment by SteveL-MSFT** [comment]
For now, you can rename the `PSReadLine` module folder to something else so that it doesn't get loaded by default by pwsh.  Of course, the interactive experience will be much degraded with PSReadLine.  Is there anything unique about the user account being used for permissions on the filesystem?  Does a file by that name already exist on the system?

**Comment by draproctor** [comment]
This turned out to be a prompt with the permissions on my `/tmp` directory. I set the permission to 755 and the issue was resolved.
