### ISSUE TITLE
How to use bash/zsh style interactive history search (CTRL-R)

### ISSUE THREAD

**Issue by mehrdadmms** [PowerShell/PSReadLine#997]
Hi
First of all thank you for this awesome tool :)) 
I want to use the history auto suggestion (Bash/zsh style interactive history search (CTRL-R))
but there is no documentation about how to activate this feature 

Can you help me ? 

Regards !

**Comment by msftrncs** [comment]
At a minimum, press CTRL-R to get started, though you may back up to an existing history item first.  Then, press characters from a word or phrase you are searching for.  The nearest history (going backwards) will be found.  Then press CTRL-R to continue going back through the matches.

**Comment by mehrdadmms** [comment]
@msftrncs 
Yes thank you 
I am familiar with this technique 
But in Linux ZSH you have the history as hint and you can get it by pressing right arrow 
it is much easier and handier than Ctrl+R

**Comment by daxian-dbw** [comment]
Closing this issue as the question has been answered (thanks @msftrncs!).
