### ISSUE TITLE
RepeatLastCharSearch(Backwards) are not behaving as expected when SearchChar initiates a character search

### ISSUE THREAD

**Issue by mikebattista** [PowerShell/PSReadLine#998]
Environment data
----------------
PS version: 7.0.0-preview.2
PSReadline version: 2.0.0-beta4
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
BufferWidth: 120
BufferHeight: 9001

Steps to reproduce or exception report
--------------------------------------

1. Configure the below key handlers
```powershell
Set-PSReadLineKeyHandler -Chord F3 -Function SearchChar
Set-PSReadLineKeyHandler -Chord Shift+F3 -Function SearchCharBackward
Set-PSReadLineKeyHandler -Chord F4 -Function RepeatLastCharSearch
Set-PSReadLineKeyHandler -Chord Shift+F4 -Function RepeatLastCharSearchBackwards
```
2. Enter the below text at the command line
```powershell
a b c a b c a b c
```
3. Set the cursor to the beginning of the line, then hit F3 -> b
4. Notice that the cursor moves to the first occurrence of b as expected
5. Press F4 twice, and notice each time that the cursor moves to the next occurrence of b.
6. With the cursor now on the last occurrence of b, press Shift+F4 to trigger RepeatLastCharSearchBackwards, notice that the cursor moves back to the middle occurrence of b as expected.
7. Press Shift+F4 again

Expected behavior:
The cursor continues moving backwards to the first occurrence of b

Actual behavior:
The cursor moves forward again to the last occurrence of b. If you press F4, the cursor will search backwards (not expected given the initial search forward), Shift+F4 will search forward. The expected behavior of RepeatLastCharSearch and RepeatLastCharSearchBackwards gets flipped after the first call to RepeatLastCharSearchBackwards.

Note:
This doesn't repro the other way around. If you start a SearchCharBackward via Shift+F3, RepeatLastCharSearch and RepeatLastCharSearchBackwards behave as expected with any combination searching forward and backward.

Bug:
I believe the bug to be on [this line](https://github.com/PowerShell/PSReadLine/blob/a7af25aa376ea21b356e5d35f4153b376fc424a9/PSReadLine/ReadLine.vi.cs#L79). SearchBackward is resetting isBackward to true in this scenario even if it is triggered by [RepeatLastCharSearchBackwards](https://github.com/PowerShell/PSReadLine/blob/a7af25aa376ea21b356e5d35f4153b376fc424a9/PSReadLine/ReadLine.vi.cs#L157). This overwrites the original intent of the user's search (forwards) and causes the behavior of RepeatLastCharSearch and RepeatLastCharSearchBackwards to flip even though the user's intent didn't change.

Recommendation:
I think [this line](https://github.com/PowerShell/PSReadLine/blob/a7af25aa376ea21b356e5d35f4153b376fc424a9/PSReadLine/ReadLine.vi.cs#L79) should just be removed. It is redundant with the [Set call within SearchCharBackward](https://github.com/PowerShell/PSReadLine/blob/a7af25aa376ea21b356e5d35f4153b376fc424a9/PSReadLine/ReadLine.vi.cs#L179) and inconsistent with how [Search is defined](https://github.com/PowerShell/PSReadLine/blob/a7af25aa376ea21b356e5d35f4153b376fc424a9/PSReadLine/ReadLine.vi.cs#L38) which doesn't call Set.

I built PSReadLine with this fix applied, and the expected behavior of the Repeat* commands in the repro was achieved.

**Comment by msftrncs** [comment]
@mikebattista, could you contribute a PR for this?  Also, can you determine if the same issue might exist in `SearchBackwardDelete()`.

The hardest part might be determining how to write a test for this, but it shouldn't be too bad.
